### ISSUE TITLE
Determine whether user was logged in through WindowsAuthenticate or not?

### ISSUE THREAD

**Issue by jackparnell** [Adldap2/Adldap2-Laravel#100]
Is it possible to determine whether the a user was logged in automatically through WindowsAuthenticate, or whether they logged in through the standard form?

The use case would be to show a "Log Out" link for those logged in through the form, but not for those which came through WindowsAuthenticate.

**Comment by stevebauman** [comment]
Hi @jackparnell, that's a great question.

I've just added a new method to the `WindowsAuthenticate` middleware. This method is meant to be overridden when you extend the class.

https://github.com/Adldap2/Adldap2-Laravel/commit/0699cba16cea3660fdf71114cc55a81c052c8c84

With this method, when a user is authenticated via SSO, you could apply a flag on the user model and save it. For example, if a small int was a database field on the `Users` table:

```php
protected function handleAuthenticatedUser(Model $user)
{
    $user->sso = true;

    $user->save():
}
```

In your navigation view:

```php
@if(!auth()->user()->sso)
    <a href="logout">Logout</a>
@endif
```

**Comment by jackparnell** [comment]
Thanks @stevebauman - that's great!
