### ISSUE TITLE
Protocol incompatability in connect()

### ISSUE THREAD

**Issue by moth** [Adldap2/Adldap2-Laravel#101]
Hello,
I've interesting issue here, which I've managed to solve, but I thought I'd flag it anyway.

I've got two domain controllers, which are one and and the same, but referenced by an External IP and Internal IP;

`'domain_controllers' => ['xx.xxx.xxx.xxx', '192.168.22.x']`

In development, the LDAP connection works out of the box on the local IP.

In production, the connection fails on the External IP (the usual Bind error) and I managed to narrow it to this;

http://php.net/manual/en/function.ldap-connect.php#75571

Removing the prefixed protocol of `ldap:://` in favour of the standalone IP means I can now connect.

We are on;

```CentOS release 6.7 (Final)
LSB_VERSION=base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch```

I honestly don't know if this is a bug, or some manifestation of a Networking/NAT issue our side.

Being a bit new to Laravel, I wonder if you could give me an example of how to extend Ldap::connect() to make my own connection. Right now, I'm reverting to changing the PROTOCOL value in the ConnectionInterface.

Thanks,
Mike

**Comment by moth** [comment]
How would I (elegantly) change/override that PROTOCOL const?

**Comment by stevebauman** [comment]
Hi @moth, this is a good question.

Either way if it's an issue on your end or not, I think this use case should be covered anyway just for availability.

I've added these methods in the root Adldap2 repository which you can then override in your own connection class: https://github.com/Adldap2/Adldap2/commit/2e439d96605a5692fa39b3c324ebb80364ad03ad.

Once you've created your own connection class and extended the `Adldap\Connections\Ldap` class, you can specify it in your `config/adldap.php` configuration:

```php
use Adldap\Connections\Ldap as BaseConnection;

class Ldap extends BaseConnection
{
    protected getProtocol()
    {
        //
    }
}
```

```php
// config/adldap.php

'connection' => App\Connections\Ldap::class,
```

**Comment by moth** [comment]
Thanks. Sorry to be dim, but do you have any docs around the creation of that connection class? I'm unsure as to where it should be sat in my App.

**Comment by stevebauman** [comment]
No problem. That's really up to you where you want the class to be located. I guess that's the beauty of Laravel, it's all up to you and what works in your application.

Here's the small amount of documentation for extending / creating a new connection: https://github.com/Adldap2/Adldap2/blob/master/docs/connecting.md#custom-connections.
