### ISSUE TITLE
how to disable sync model from AD

### ISSUE THREAD

**Issue by jackypu** [Adldap2/Adldap2-Laravel#104]
Hi, I'm connected to the AD server and works well, but there's problem in syncing AD's username and password to database while we don't have the write permit and we also don't have to do this  logically.
how can i disable sync function? 
thanks very much!

**Comment by stevebauman** [comment]
Hi @jackypu,

I'm not sure what you're asking?

You can disable synchronizing the password by setting the `password_sync` configuration option to `false`: https://github.com/Adldap2/Adldap2-Laravel#password-synchronization

You can't disable synchronizing users to the local database. That's the primary feature of this package.

**Comment by jackypu** [comment]
Hi, @stevebauman ,
thanks for your reply.

I updated the code to the latest "v2.0.8", and i did see the password_sync, but i noticed,
"If the developer doesn't want to synchronize AD passwords, we'll set the password to a random 16 character string." 
however, i just don't want to sync password as my database table even doesn't contain column "password", so, that's the problem.

**Comment by stevebauman** [comment]
Hi @jackypu, the easiest way to accomplish this would be to add a password accessor to your `User` model:

```php
class User extends Model
{
    public function setPasswordAttribute($password)
    {
        // Don't set a password.
    }
}
```

This would bypass the password synchronization.

A more complicated way (but a better practice) would be to extend the `AdldapAuthServiceProvider` and override the `newAdldapAuthUserProvider()` method:

https://github.com/Adldap2/Adldap2-Laravel/blob/master/src/AdldapAuthServiceProvider.php#L79

Then, return a new instance of **your own** `AdldapAuthUserProvider`. For example:

```php
use Illuminate\Contracts\Hashing\Hasher;
use Adldap\Laravel\AdldapAuthServiceProvider;
use App\Providers\LdapAuthUserProvider;

class LdapAuthServiceProvider extends AdldapAuthServiceProvider
{
    protected function newAdldapAuthUserProvider(Hasher $hasher, $model)
    {
        return new LdapAuthUserProvider($hasher, $model);
    }
}
```

```php
use Illuminate\Contracts\Auth\Authenticatable;
use Adldap\Laravel\AdldapAuthUserProvider;

class LdapAuthUserProvider extends AdldapAuthUserProvider
{
    protected function syncModelPassword(Authenticatable $model, $password)
    {
        return $model;
    }
}
```

**Comment by jackypu** [comment]
Hi, @stevebauman, You are so nice. I'm very pleased to see your post. and the resolution of adding function "setPasswordAttribute" did work. thanks.
    The scene we're using ldap is this:
===> we just using LDAP server to authenticate the login of the users,  we don't need to bind as the administrator to fetch ADLP's other resources.

    As there's another question is: when logging in a normal user using "auth()->attempt($username,$password) ", i tracked that the code try to bindAsAdministrator not AsUser. so, of course, it fails.   

The question is why it binds As Administrator using logged in's  username and password but not using the configurations in adldap.php (connections['default']['connection_settings']['admin_username'] and ['admin_password']?  And how can i just login  a normal user?

best wishes!

**Comment by stevebauman** [comment]
Hi @jackypu, glad that worked for you!

For a thorough explanation on why administrator credentials are required, visit this comment on another Adldap2 issue:

https://github.com/Adldap2/Adldap2-Laravel/issues/91#issuecomment-216922475

**Comment by jackypu** [comment]
Hi， @stevebauman, thanks for your reply. 
Null function "setPasswordAttribute" seems not work as well. 

As when the authenticate finished, it will ask the provider to validate the user against the given credentials .  as the code below:
Function hasValidCredentials() In "/vendor/laravel/framework/src/Illuminate/Auth/SessionGuaed.php line 349 

`public function attempt(array $credentials = [], $remember = false, $login = true)
    {
        $this->fireAttemptEvent($credentials, $remember, $login);
        $this->lastAttempted = $user = $this->provider->retrieveByCredentials($credentials);

        // If an implementation of UserInterface was returned, we'll ask the provider
        // to validate the user against the given credentials, and if they are in
        // fact valid we'll log the users into the application and return true.
        if ($this->hasValidCredentials($user, $credentials)) {
            if ($login) {
                $this->login($user, $remember);
            }

            return true;
        }

        return false;
    }`

**Comment by stevebauman** [comment]
Hey @jackypu,

This slipped my mind. You're right, since the `AdldapAuthUserProvider` extends the `EloquentUserProvider`, the password field gets validated from the database. I'm not sure there's a way around this.

I've never thought of this use case before. I don't think this will be a fixable option without having a completely separate auth user provider. I'll take a look.

**Comment by SandeepAgrahari** [comment]
Hi @stevebauman,
I set password_sync to true. and After import users in the local database. Now password column in the database has a hashed password.
I verified this password it's not the expected password.

Please help me to sync the same password in the local database as in AD.

**Comment by stevebauman** [comment]
Hi @SandeepAgrahari,

Please read:

https://ldaprecord.com/docs/laravel/auth/importing/#password-synchronization

Namely:

“Passwords cannot be retrieved from users who are being imported from your LDAP server. 
This would be a major security risk if this were possible. If a password is already set for the user being imported, it will be left untouched. This is to retain a possible synchronized password that was set upon login.”
