### ISSUE TITLE
Remember me feature

### ISSUE THREAD

**Issue by strebl** [Adldap2/Adldap2-Laravel#11]
I saw that the remember me feature works with your driver, that's very nice.
But I think there is a security issue. If a user is logged in and checked the remember me box, he will remain logged in forever even if the password changes or the user gets deactivated.

That happens without the flag too, but at least it's not forever.

What do you guys think?

**Comment by stevebauman** [comment]
Hmm true. Might be good to re-authenticate when `retrieveByToken()` is called...

**Comment by strebl** [comment]
Can you do that? You don't know the current password...

I think it's a little bit more complex. An idea is that you check some user attributes like when the password the last time and if the account is disabled. But to compare the change time, I think you have to store it...

And maybe that's not needed for a lot of the apps, therefore maybe it's better if that's an feature you can enable/disable.
But because Active Directory is for business, I think that should be fixed.

**Comment by stevebauman** [comment]
That's true, and since we can't "un-hash" the users database password to send to AD, this might be difficult.

But just to mention, the remember me functionality is up to the developer, and doesn't need to be used / implemented at all if this were the case of security concerns.

**Comment by strebl** [comment]
>But just to mention, the remember me functionality is up to the developer, and doesn't need to be used / implemented at all if this were the case of security concerns.

Yeah, that's totally true!
