### ISSUE TITLE
Fatal error: Call to undefined function Adldap\ldap_explode_dn()

### ISSUE THREAD

**Issue by jtejido** [Adldap2/Adldap2-Laravel#112]
Hi,

I'm getting this error when I used it.

FatalThrowableError in Utilities.php line 20:
Fatal error: Call to undefined function Adldap\ldap_explode_dn()

PHP ver: PHP 5.6.14

Here is a snippet of the stacktrace:
[http://imgur.com/FDkfJIC](url)

and the dc's I have in adldap.php:

'domain_controllers' => ['13.151.185.25', '10.236.24.161'],

**Comment by stevebauman** [comment]
I get a 404 when visiting your stack trace link.

This is strange though, are you sure you're running PHP 5.6? Try calling the method in your routes file and see if you receive the same exception:

```php
// app/Http/routes.php

$dn = ldap_explode_dn('dc=corp,dc=org');
```

**Comment by onrasn** [comment]
its beacuse of your php ldap extension is disabled
