### ISSUE TITLE
Login without admin or database

### ISSUE THREAD

**Issue by EmilMoe** [Adldap2/Adldap2-Laravel#115]
How do I perform a login check (just check if the credentials has access to the AD) without having database or an admin account stored in the config.

**Comment by stevebauman** [comment]
You'll need to use the root Adldap instance to do this, for example:

```php
public function login($request)
{
    $auth = Adldap::auth();
    
    if ($auth->attempt($request->username, $request->password, $bindAsUser = true)) {
        // Passed LDAP authentication.
    }
}
``
