### ISSUE TITLE
Auth login in LDAP

### ISSUE THREAD

**Issue by Albvadi** [Adldap2/Adldap2-Laravel#117]
Hi,
here is your worst nightmare again... :sweat: 

I´m setting the login in a clean Laravel 5.2.
I follow all the steps from the Quick Start and as the connection it´s with LDAP, I made this changes too:
- In adldap_auth.php:

``` php
//change from 
'username_attribute' => ['username' => 'samaccountname'],
// to 
'username_attribute' => ['username' => 'uid'],
```
- and:

``` php
//change from 
'login_attribute' => env('ADLDAP_LOGIN_ATTRIBUTE', 'samaccountname'),
// to 
'login_attribute' => env('ADLDAP_LOGIN_ATTRIBUTE', 'uid'),
```

If I try login from the default login form in Laravel (I changed the input from email to username), I get the following error: **These credentials do not match our records.**

But, `$search = Adldap::getDefaultProvider()->search()->where('uid', 'test.user')->get();` return the data user correctly.

And `Adldap::getDefaultProvider()->auth()->attempt($adminUser, $adminPass)` returns true, where $adminUser and $adminPass are the same values setted in `admin_username` and `admin_password` in `config/adldap.php`

Any idea how can debug what´s happening??
I don´t understand where is the problem... :disappointed_relieved:

**Comment by stevebauman** [comment]
Hey @Albvadi,

Check your `account_prefix` and `account_suffix` configuration options.

Since you're using OpenLDAP, you'll most likely need to encapsulate the users UID. For example:

```php
'account_prefix' => 'uid=',

'account_suffix' => ',dc=corp,dc=acme,dc=org',
```

**Comment by Albvadi** [comment]
Ups, I think I have a big problem... 

I know that LDAP needs the full dn to login, so I tried input the complete dn in the username field and don´t work neither.. and because of this, I think I´m missing something..

Anyway, through [your comment in this issue](https://github.com/Adldap2/Adldap2-Laravel/issues/91#issuecomment-213465993), I thought the implementation was different, but now, I know I´m totally wrong.
I thought that the library bind in LDAP as admin, sync all data with users table and then login using the users table, always, not only when LDAP or AD are down...

And now, I have a problem, because my users don´t have the same dn to setting the account_suffix.
The branch hierarchy of my LDAP is more or less like:
- baseDN
  - Level_1
    - Sub_Level_1
    - Sub_Level_2
  - Level_2
    - Sub_Level_3
    - Sub_Level_4

and there are users in all levels and sublevels... so, for example, some users have a dn like ```uid=test1.user,ou=Level_1,ou=baseDN``` and others a dn like ```uid=test2.user,ou=Sub_Level_4,ou=Level_2,ou=baseDN``` 

So, at this point, I don´t know if there is any way to manage the login with LDAP with multiple ous...
Do you have any idea?

Maybe a Event::listen or Middleware that before login, get the username from login request, make a search with admin credentials, get dn of the user and change the attr in the login request ...?

I have no clear idea... :confused: 

P.S. As always, thank so much for your support... and sorry my poor English, I hope you can understand well everything..

**Comment by Albvadi** [comment]
Hi,
so far not been able to activate the logs, but now, I have more info...

Log from LDAP:
```log
conn=462 op=0 msgId=1 - BIND dn="uid=admin,ou=foo,o=basedn" method=128 version=3
conn=462 op=0 msgId=1 - RESULT err=0 tag=97 nentries=0 etime=0 dn="uid=admin,ou=foo,o=basedn"
conn=462 op=1 msgId=2 - SRCH base="o=basedn" scope=2 filter="(&(objectClass=person)(uid=test.user))" attrs=ALL
conn=462 op=1 msgId=2 - RESULT err=0 tag=101 nentries=1 etime=0
conn=462 op=2 msgId=3 - BIND dn="test.user" method=128 version=3, Invalid DN
conn=462 op=2 msgId=3 - RESULT err=34 tag=97 nentries=0 etime=0
conn=462 op=3 msgId=4 - UNBIND
conn=462 op=3 msgId=-1 - closing - U1
conn=462 op=-1 msgId=-1 - closed.
```
At this point, same as #106, I know exactly what´s happening and the correct config to make work the auth...
But, my question is... why before the bind as user, is binding as admin and make the search? For what is needed this search??

I thought directly make the attempt with the user/pass from the login form, instead a binding as admin and make a search...

Can you explain me this??
Thanks!

**Comment by stevebauman** [comment]
Hi @Albvadi,

Please see this answer for details on why administrator credentials are required:

https://github.com/Adldap2/Adldap2-Laravel/issues/91#issuecomment-216922475

**Comment by Albvadi** [comment]
Hi,
thanks for point me to the explanation.. It´s a rubish need the full dn to login to LDAP...

Besides, I have been searching for others libs to auth in LDAP and almost all of them, uses your lib behind the scenes, so, I don´t understand how anyone has the same problem as me, with users in different levels with different dn´s...

Anyway, I have solved the issue (at least, for my particular case). It´s ugly but works well.
This are the instructions if someone have the same problem as me, or if you want implement somehow if schema in configuration is detected as OpenLDAP for example...

The idea is making a search for the user in the pre login, retrieve the DN, set prefix and suffix acounts and continue with the login..

1. The first step it´s create the new middleware for the prelogin.
   Run `php artisan make:middleware PreLoginLdapMiddleware` in console.

2. Insert the middleware in your `app/Http/Kernel.php` file (in the `routeMiddleware` array):

   ```php
   'prelogin.ldap' => \App\Http\Middleware\PreLoginLdapMiddleware::class,
   ```

3. Change the routes, in your `app/Http/routes.php` file for the real routes:

   ```php
   // FROM 

   Route::auth();
   
   // TO 
   
   //Authentication Routes...
   Route::get('login', ['as' => 'auth.login', 'uses' => 'Auth\AuthController@showLoginForm']);
   Route::post('login', ['as' => 'auth.login', 'uses' => 'Auth\AuthController@login'])->middleware('prelogin.ldap');
   Route::get('logout', ['as' => 'auth.logout', 'uses' => 'Auth\AuthController@logout']);
   
   // Registration Routes...
   Route::get('register', ['as' => 'auth.register', 'uses' => 'Auth\AuthController@showRegistrationForm']);
   Route::post('register', ['as' => 'auth.register', 'uses' => 'Auth\AuthController@register']);
   
   // Password Reset Routes...
   Route::get('password/reset/{token?}', ['as' => 'auth.password.reset', 'uses' => 'Auth\PasswordController@showResetForm']);
   Route::post('password/email', ['as' => 'auth.password.email',  'uses' => 'Auth\PasswordController@sendResetLinkEmail']);
   Route::post('password/reset', ['as' => 'auth.password.reset', 'uses' => 'Auth\PasswordController@reset']);
   ```
   > **Note**: Note the use of the middleware in the second route..

4. The content of the middleware itself, in `app/Http/Middleware/PreLoginLdapMiddleware.php`.
      ```php
   /**
    * Handle an incoming request.
    *
    * @param  \Illuminate\Http\Request  $request
    * @param  \Closure  $next
    * @return mixed
    */
   public function handle($request, Closure $next)
   {
       $resultDN = \Adldap::search()->where('uid', $request->username)->select('dn')->get();
   
       if ( !$resultDN->isEmpty() ){
   
           list($account_prefix, $account_suffix) = explode($request->username, $resultDN[0]->dn);
   
           $provider = \Adldap::getDefaultProvider();
           $provider->getConfiguration()->setAccountPrefix($account_prefix);
           $provider->getConfiguration()->setAccountSuffix($account_suffix);
   
       }
   
       return $next($request);           
   }
   ```

Thanks again for all the support and for this amazing and super configurable library!
