### ISSUE TITLE
Retrieving group name

### ISSUE THREAD

**Issue by Mylo-92** [Adldap2/Adldap2-Laravel#118]
Good Day,

I just wanted to know if it is possible to retrieve the name (CN) of the group a user is assigned to e.g in my case:

**my function**
```
public function index()
    {
        $user = Adldap::getDefaultProvider()->search()->users()->find('Mpiloz Makaez');
        return view('home', compact('user'));
    }
```
**my view**
```
<h4>Groups</h4>
<p>{{$user->getGroups('2')->get('0')->distinguishedname[0]}}</p>
//Do not need the whole array
```
The above returns:
```
CN=Web App Administrators,OU=Groups,OU=JHB,DC=ZTECH,DC=local
```
How do I go about achieving that? Moreover, is there a section in the docs where all the accessor and mutator methods for the AD attributes are listed?

Regards,

**Comment by Mylo-92** [comment]
Don't know if I should open up another issue, nonetheless:

I am trying to create users both on my laravel app and active directory server via seeding. And as such, stumbled upon #81 , thus I tried to do the same as the final setup step mentioned. However, I have encountered the following issue: 
```
local.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 1 passed to Adldap\Adldap::__construct() must be an instance of Adldap\Contracts\Connections\ManagerInterface
```
caused by:
```
$adldap = new \Adldap\Adldap($config);  
$a_user = $adldap->users()->newInstance();
```
Is this the correct syntax or am I missing something?

Regards,

**Comment by stevebauman** [comment]
> I just wanted to know if it is possible to retrieve the name (CN) of the group a user is assigned to

If you use the `bind_user_to_model` config option, this is done for you.

https://github.com/Adldap2/Adldap2-Laravel#binding-the-adldap-user-model-to-the-laravel-user-model

Once you've enabled it, you could do something like this:

```php
public function index()
{
    $user = Auth::user()->adldapUser;

    $groups = $user->getGroups();

    return view('user', compact('user', 'groups'));
}
```

**Comment by Mylo-92** [comment]
Aplogies for the delayed reply, getGroups returns an array in this form:
```[{"objectclass":["top","group"],"0":"objectclass","cn":["Technicians"],"1":"cn","member":["CN=Terry Shektr,OU=Field Operations,OU=Users,OU=Company,DC=zimutech,DC=com"],"2":"member","distinguishedname":["CN=Field Technicians,OU=Groups,OU=Limbe,DC=zimutech,DC=com"],"3":"distinguishedname","instancetype":["4"],"4":"instancetype","whencreated":["20160614101917.0Z"],"5":"whencreated","whenchanged":["20160616125738.0Z"],"6":"whenchanged","usncreated":["13439"],"7":"usncreated","usnchanged":["42210"],"8":"usnchanged","name":["Technicians"],"9":"name","10":"objectguid","11":"objectsid","samaccountname":["Technicians"],"12":"samaccountname","samaccounttype":["268435456"],"13":"samaccounttype","grouptype":["-2147483646"],"14":"grouptype","objectcategory":["CN=Group,CN=Schema,CN=Configuration,DC=zimutech,DC=com"],"15":"objectcategory","dscorepropagationdata":["16010101000000.0Z"],"16":"dscorepropagationdata","dn":"CN=Technicians,OU=Groups,OU=Company,DC=zimutech,DC=com"}]
```
What I am looking for is the CN of the groups or groups e.g Technicians

**Comment by stevebauman** [comment]
No problem.

The `getGroups()` method should return a collection of `Group` models. You seem to be converting that collection into json.

You should be able to use (with the `bind_user_to_model` config option enabled):

```php
$user = Auth::user()->adldapUser;

$groups = $user->getGroups();

foreach ($groups as $group) {
    $group->getCommonName();
}
```

**Comment by Mylo-92** [comment]
Thank you that did the trick :)
