### ISSUE TITLE
Can't login after changing the password.

### ISSUE THREAD

**Issue by strebl** [Adldap2/Adldap2-laravel#12]
If I change the password of an user after he is the database, I can't login again.

My Test Scenario:

1. Login with 'testuser', 'oldPassword' -> works
2. Logout
3. Change password via Active Directory of user 'testuser' to 'newPassword'
4. Login with 'testuser', 'newPassword' <-- fails
5. Login with 'testuser', 'oldPassword' <-- fails

Did I miss something?

**Comment by stevebauman** [comment]
This is due to the password only being changed on profile creation: https://github.com/Adldap2/Adldap2-laravel/blob/master/src/AdldapAuthUserProvider.php#L107

Fixing now, thanks!
