### ISSUE TITLE
These credentials do not match our records.

### ISSUE THREAD

**Issue by Ranfty** [Adldap2/Adldap2-Laravel#120]
Hello,

Having a bit of an issue using Adldap2-Laravel. I've followed the step-by-step guide to configuring Adldap2 on Laravel 5.2 twice but the issue still persists.

I have configured config/adldap.php without an account suffix so users can log in using 'j.doe@ad.test'. 

I am connecting to my AD sever correctly as I receive a Adldap user model when I call:

`$user = Adldap::getDefaultProvider()->auth()->attempt('j.doe@ad.test', 'somePassword');`
`dd($user);`

However, I receive the error 'These credentials do not match our records.' when I attempt to log in through Laravels make:auth views.

Any suggestions?

**Comment by stevebauman** [comment]
Hi @Ranfty,

So your configuration to your LDAP server is fine, can you post your `app/Controllers/Auth/AuthController.php` file as well as your `config/app/auth.php` file?

**Comment by Ranfty** [comment]
AuthController.php

`<?php

namespace App\Http\Controllers\Auth;

use App\Models\User;
use Validator;
use App\Http\Controllers\Controller;
use Illuminate\Foundation\Auth\ThrottlesLogins;
use Illuminate\Foundation\Auth\AuthenticatesAndRegistersUsers;

class AuthController extends Controller
{
    use AuthenticatesAndRegistersUsers, ThrottlesLogins;

    protected $redirectTo = '/';

    public function __construct()
    {
        $this->middleware($this->guestMiddleware(), ['except' => 'logout']);
    }

    protected function validator(array $data)
    {
        return Validator::make($data, [
            'name' => 'required|max:255',
            'email' => 'required|email|max:255|unique:users',
            'password' => 'required|min:6|confirmed',
        ]);
    }

    protected function create(array $data)
    {
        return User::create([
            'name' => $data['name'],
            'email' => $data['email'],
            'password' => bcrypt($data['password']),
        ]);
    }
}
`


config/auth.php
`<?php

return [

    /*
    'defaults' => [
        'guard' => 'web',
        'passwords' => 'users',
    ],

    'guards' => [
        'web' => [
            'driver' => 'session',
            'provider' => 'adldap',
        ],

        'api' => [
            'driver' => 'token',
            'provider' => 'users',
        ],
    ],

    'providers' => [
        'adldap' => [
            'driver' => 'adldap',
            'model'  => App\Models\User::class,
        ],
        
        'users' => [
            'driver' => 'eloquent',
            'model' => App\Models\User::class,
        ],
    ],

    'passwords' => [
        'users' => [
            'provider' => 'users',
            'email' => 'auth.emails.password',
            'table' => 'password_resets',
            'expire' => 60,
        ],
    ],

];
`

Cheers.

**Comment by stevebauman** [comment]
Can you try using an account suffix in your configuration and try authenticating with an email / username?

This is most likely due to the users username not *actually* mapping to the users fully qualified username. The query would return nothing in your current configuration, for example, here's what's essentially going on:

```php
$query->where(['samaccountname' => 'j.doe@ad.test'])->first();
```

**Comment by stevebauman** [comment]
Scratch that, in your `adldap_auth.php` configuration file, use:

```php
'username_attribute' => ['username' => 'userprincipalname'],
```

**Comment by Ranfty** [comment]
I'll have to give it a go on Monday as I'm away from it for the weekend. I'll close this thread and get back to you on Monday.

Thanks for the help.

**Comment by stevebauman** [comment]
Sounds good, no problem!

**Comment by Ranfty** [comment]
Hi Steve,

Cheers for your help, it now works.

I also had to add 

`'login_attribute' => env('ADLDAP_LOGIN_ATTRIBUTE', 'userprincipalname'),`

in `adldap_auth.php`

**Comment by stevebauman** [comment]
That's great, thanks for following up!
