### ISSUE TITLE
Don´t work Accessors & Mutators

### ISSUE THREAD

**Issue by Albvadi** [Adldap2/Adldap2-Laravel#121]
Hi,
I´m trying configure [Accessors & Mutators](https://laravel.com/docs/master/eloquent-mutators#accessors-and-mutators) for some of the users fields and thy don´t work.

In my LDAP, there are users with the name in uppercase and others in lowercase and I´m show in the app with ucwords. 
I create the accessor (and the mutator just in case) like this in `app\User.php` model:
```php
public function getNameAttribute($value){
    return ucwords($value);
}

public function setNameAttribute($value){
    $this->attributes['name'] = ucwords($value);
}
```
but it´s simply ignored, always show the data from LDAP.
In a Laravel with the normal auth against Database, works great.

Thanks!

**Comment by stevebauman** [comment]
How are you trying to access the eloquent accessor? Adldap2 has no effect on these.

Are you trying to sync attributes that are mutated from the `sync_attributes` config option?

**Comment by Albvadi** [comment]
I´m trying only with name attr.
Sync atributes are:
```php
'sync_attributes' => [
        'name' => 'cn',
        'email' => 'mail',
    ],
```
And in Blade template: `{{ Auth::user()->name }}`. I have also tried directly `{{ ucwords(Auth::user()->name) }}` and it doesn´t work too.

I was trying login against database, changing the host in domain_controllers for one doesn´t exist and setting `'login_fallback' => env('ADLDAP_LOGIN_FALLBACK', true),` but it´s launch the excepcion: 
```php
BindException in Guard.php line 86: Can't contact LDAP server

    in Guard.php line 86
```

**Comment by Albvadi** [comment]
With the username field, that isn´t in the sync_attributes, the accessor works great.

**Comment by stevebauman** [comment]
Are you sure you're using the `app\User.php` model you're specifying? I'm using accessors and mutators just fine in my application.

**Comment by stevebauman** [comment]
Maybe try clearing your configuration? `php artisan config:clear`

**Comment by Albvadi** [comment]
Forget all... Sorry for wasting your time without needing.. :sweat: 

The problem it´s that `ucwords` don´t work... (I don´t know why..)
I need return `ucwords(strtolower($value))` and works.. (also I don´t know why..) ...

For the callback problem... I´m wrong with the operation??

**Comment by stevebauman** [comment]
Don't worry about it :), I'm glad to help!

Can you post your `config/auth.php` configuration and your `app/User.php` model?

**Comment by Albvadi** [comment]
`config/auth.php`
```php
return [

    'defaults' => [
        'guard' => 'web',
        'passwords' => 'users',
    ],

    'guards' => [
        'web' => [
            'driver' => 'session',
            'provider' => 'adldap', // Switched to 'adldap' from 'users'
        ],

        'api' => [
            'driver' => 'token',
            'provider' => 'users',
        ],
    ],

    'providers' => [
        // New 'adldap' provider:
        'adldap' => [
            'driver' => 'adldap',
            'model'  => App\User::class,
        ],
        
        'users' => [
            'driver' => 'eloquent',
            'model' => App\User::class,
        ],

        // 'users' => [
        //     'driver' => 'database',
        //     'table' => 'users',
        // ],
    ],

    'passwords' => [
        'users' => [
            'provider' => 'users',
            'email' => 'auth.emails.password',
            'table' => 'password_resets',
            'expire' => 60,
        ],
    ],

];
```
`app/User.php`
```php
namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    protected $fillable = [
        'name', 'email', 'password',
    ];

    protected $hidden = [
        'password', 'remember_token',
    ];

    public function getNameAttribute($value) {
        return ucwords(strtolower($value));
    }

}
```

**Comment by stevebauman** [comment]
Ok, everything looks fine.

So calling `auth()->user->name` doesn't return an uppercased variant of the users name?

Try modifying the accessor to this:

```php
public function getNameAttribute($value) {
    dd($value);
}
```

Then, try and login and see what value is dumped.

**Comment by Albvadi** [comment]
Oh damn.. I´m so sorry
Maybe, because I´m spanish, I haven´t explained well.. :sweat: 

According with the [PHP manual of ucwords](http://php.net/manual/es/function.ucwords.php):
```php
$bar = 'HELLO WORLD!';
$bar = ucwords($bar);             // HELLO WORLD!
$bar = ucwords(strtolower($bar)); // Hello World!
```
And so, like many names of the LDAP users are uppercased, I thought accessor wasn´t working.. but I was wrong. And because of that, in email and username works because all are in lowercase in LDAP.
So, there aren´t any issue with accessor and at this point, no problems.

And as I was testing this, I´d tryed the fallback to login against the database, changing the host in domain_controllers for one doesn´t exist and setting `'login_fallback' => env('ADLDAP_LOGIN_FALLBACK', true)`, but it´s launch the excepcion:
```php
BindException in Guard.php line 86: Can't contact LDAP server
    in Guard.php line 86
```
So, I´m wrong and fallback only work when user doesn´t exist in LDAP or should work when LDAP server return time out??

Thanks again!

**Comment by stevebauman** [comment]
Apologies for the long response @Albvadi.

> So, I´m wrong and fallback only work when user doesn´t exist in LDAP or should work when LDAP server return time out??

Fallback **only** works when your LDAP server **can** be contacted. It will first hit your LDAP server and try to authenticate, and if this fails, it will pass the credentials into the parent `EloquentUserProvider`:

https://github.com/Adldap2/Adldap2-Laravel/blob/master/src/AdldapAuthUserProvider.php#L64

**Comment by Albvadi** [comment]
Perfect, all is clear.

Thanks!

**Comment by stevebauman** [comment]
No problem! :D

**Comment by thuyhyvg** [comment]
i don't fix this bug. 
help me, please.

**Comment by stevebauman** [comment]
@thuyhyvg, can you elaborate? What is your issue?

**Comment by thuyhyvg** [comment]
BindException in Guard.php line 86:
Can't contact LDAP server
i don't know installation ldap server for window 7.
Can you help me?
Thank you

**Comment by warlord0** [comment]
I think that's way out of the scope of this project. :o The whole point of Adldap is to talk to a server you already have.
As to install on windows 7, I'm not sure if you could use AD LDS? https://www.microsoft.com/en-us/download/details.aspx?id=14683

**Comment by stevebauman** [comment]
@warlord0 is right, if you don't have an existing LDAP server and don't have the knowledge of setting one up, I would view the mass amount of tutorials on the web to guide you through this.

If you have any issues connecting to an actual up and running LDAP server on your network using this package, then I'd be glad to help further.

**Comment by Gildder** [comment]
![image](https://user-images.githubusercontent.com/4993652/28393285-f554fd2c-6cb3-11e7-95dd-2bd3d068c43f.png)

Hi guys, I've been reading your comments, and I have this problem with ldap2 I do not know where I can be wrong

**Comment by Gildder** [comment]
My user is null, the password and that is the strange thing since I pass the two parameters
