### ISSUE TITLE
How to display / import users to database?

### ISSUE THREAD

**Issue by ilyadavydyuk** [Adldap2/Adldap2-Laravel#125]
Hi there. I can't display users in view. 
in controller:
`$users = $this->adldap->getDefaultProvider()->search()->users()->get();
return view('home', compact('users));`

in template:
`@foreach ($users as $user)
   <p>{{ $user->username }}</p>
@endforeach`

And i got >400 empty strings. How to do it right?

And how to import users to database? Thanks.

**Comment by stevebauman** [comment]
> in template:
@foreach ($users as $user) <p>{{ $user->username }}</p> @endforeach

And i got >400 empty strings. How to do it right?

You can call the accessor methods such as:

```php
@foreach ($users as $user)
    {{ $user->getCommonName() }}
@endforeach
```
Or just access the users details dynamically by property using:

```php
@foreach ($users as $user)
    {{ $user->cn[0] }}
@endforeach
```

Or use the method `getAttribute($attribute)`:

```php
@foreach($users as $user)
    {{ $user->getAttribute('cn', 0) }}
@endforeach
```

Please take a look at the documentation for more:

https://github.com/Adldap2/Adldap2/blob/master/docs/models.md

> And how to import users to database? Thanks.

That's a good question, I've actually just implemented this feature now (will be released shortly).

https://github.com/Adldap2/Adldap2-Laravel/commit/718c876149ac5041aaf0e5ef18f080d9efb0c124
