### ISSUE TITLE
Adldap Authentication with JWT

### ISSUE THREAD

**Issue by Mylo-92** [Adldap2/Adldap2-Laravel#129]
Good Day,

I am trying to implement  [JSON Web Token Authentication](https://github.com/tymondesigns/jwt-auth) in my project side by side with Adldap authentication however I am not too sure how to proceed or rather what to do exactly. For example, ```JWTAuth::attempt($credentials)```, the package uses ```auth' => 'Tymon\JWTAuth\Providers\Auth\IlluminateAuthAdapter',``` as the authentication provider which looks like : 
```
namespace Tymon\JWTAuth\Providers\Auth;

use Illuminate\Auth\AuthManager;

class IlluminateAuthAdapter implements AuthInterface
{
    /**
     * @var \Illuminate\Auth\AuthManager
     */
    protected $auth;

    /**
     * @param \Illuminate\Auth\AuthManager  $auth
     */
    public function __construct(AuthManager $auth)
    {
        $this->auth = $auth;
    }

    /**
     * Check a user's credentials.
     *
     * @param  array  $credentials
     * @return bool
     */
    public function byCredentials(array $credentials = [])
    {
        return $this->auth->once($credentials);
    }

    /**
     * Authenticate a user via the id.
     *
     * @param  mixed  $id
     * @return bool
     */
    public function byId($id)
    {
        return $this->auth->onceUsingId($id);
    }

    /**
     * Get the currently authenticated user.
     *
     * @return mixed
     */
    public function user()
    {
        return $this->auth->user();
    }
}
```
I tried replacing the 'auth' key's value with ```'Adldap\Laravel\AdldapAuthServiceProvider'``` but to no avail. Should the value of the 'auth' key be something else?

Kind Regards,

**Comment by stevebauman** [comment]
> I tried replacing the 'auth' key's value with 'Adldap\Laravel\AdldapAuthServiceProvider' but to no avail. Should the value of the 'auth' key be something else?

By `auth` key, are you referring to the `$auth` property on the `IlluminateAuthAdapter`?

What exactly are you trying to accomplish? Something like this?

```php
class AuthController extends Controller
{
    public function login(Request $request)
    {
        if (Auth::guard('adldap')->attempt($request->all()) {
            // Failed
        }

        if (Auth::guard('jwt')->attempt($request->all()) {
            // Passe
        }
    }
}
```

**Comment by Mylo-92** [comment]
Basically, make the JWT authentication occur through: Auth::attempt() where the driver has been set to adldap. So if the user exists in Active Directory generate the jwt token

**Comment by Mylo-92** [comment]
E.g: [My query on the jwt repo](https://github.com/tymondesigns/jwt-auth/issues/781)

**Comment by Mylo-92** [comment]
Managed to achieve what I wanted. Slight over thinking on my part, thank you for your time though.

Regards,

**Comment by stevebauman** [comment]
Great to hear, no problem!
