### ISSUE TITLE
Full example available?

### ISSUE THREAD

**Issue by david-nhs** [Adldap2/Adldap2-laravel#13]
Not an 'issue' per-se but wondered if you had a fully functioning set of example files, including routes, controllers and views for a simple login form using Adldap2-laravel? I have installed and configured as per your documentation. 

I am relatively new to Laravel and am trying to fit everything together! For example I have customised login.blade.php as follows, but on submission I just get returned to the login page again regardless of what credentials I enter: http://pastebin.com/7xrCDJzS

Any help/ guidance would be most welcome!

**Comment by stevebauman** [comment]
I'd be glad to help you out. I actually typed out a comment with all of my steps here:

https://github.com/Adldap2/Adldap2-laravel/issues/7#issuecomment-142293763

Though this could be confusing to developers relatively new to laravel. I'm going to create a doc for new users on this matter. I'll copy the link here when it's complete

**Comment by david-nhs** [comment]
Thanks for link Steve! I followed the step through, but now receive this error after attempting to login;

ErrorException in AdldapAuthUserProvider.php line 50:
Undefined index: username

I ideally need to configure this so that users can enter their samaccountname instead of e-mail. Any suggestions welcome?

**Comment by stevebauman** [comment]
No problem!

When using a `samaccountname`, you need to change the stock laravel user migration in `database/migrations/2014_10_12_000000_create_users_table.php.

Change:
```php
Schema::create('users', function (Blueprint $table) {
    $table->increments('id');
    $table->string('name');
    $table->string('email')->unique();
    $table->string('password', 60);
    $table->rememberToken();
    $table->timestamps();
});
```

To:

```php
Schema::create('users', function (Blueprint $table) {
    $table->increments('id');
    $table->string('name');
    $table->string('username')->unique(); // Username instead of email
    $table->string('password', 60);
    $table->rememberToken();
    $table->timestamps();
});
```

Then run the command `php artisan migrate:refresh`. Once that's done, change the `$fillable` property in your `app/User.php` model:

From:
```php
protected $fillable = ['name', 'email', 'password'];
```

To:
```php
protected $fillable = ['name', 'username', 'password']; // Username instead of email
```

**Comment by david-nhs** [comment]
Thank you, but unfortunately still the same error. I then tried to update my login.blade.php file as follows;
    <div>
        Username
        <input type="text" name="username" id="username">
    </div>

but now upon submitting that form it just loops back to itself.

**Comment by stevebauman** [comment]
You need to change the `$username` property on your `app/Http/Controllers/Auth/AuthController`:

```php
class AuthController extends Controller
{
    protected $username = 'username';
}
```

**Comment by david-nhs** [comment]
Ok, my AuthController.php now looks like this: http://pastebin.com/Vv9kCdKF

and my login.blade.php like this: http://pastebin.com/nqXdF2kg

however the auth/login page still loops back on itself when attempting to login?

Sorry if I'm missing some really simple stuff here, but hopefully this is akso helpful for others with similar use cases.

**Comment by stevebauman** [comment]
No problem at all. Did you change the `config/auth.php` driver to `adldap`?

**Comment by david-nhs** [comment]
Yep changed driver already to adldap. Do my login.blade.php and AuthController.php files look ok?

**Comment by stevebauman** [comment]
Hmm everything looks fine. The looping back to the login page would signify a validation error, or the login didn't work. Have you checked that your Adldap settings are correct? Try calling inside your `resources/views/login.blade.php`:

```php
{{ dd(Adldap::authenticate($username, $password)) }}
```

And see if that returns true.

**Comment by david-nhs** [comment]
Fantastic! Using this helped me diagnose a very minor error in my LDAP authentication settings. Thank you!! All working as expected now - brilliant!!

**Comment by NSBrianWard** [comment]
This really helped me a lot. Hopefully this gets posted in the documentation somewhere.
