### ISSUE TITLE
Connections with LDAP in all requests?

### ISSUE THREAD

**Issue by Albvadi** [Adldap2/Adldap2-Laravel#130]
Hi,
the component makes connections with LDAP in all the requests??

In a simple project, before the login with LDAP, all the requests and pages changes are immediate and the time are in ms.
When I do the login, LDAP slow to respond about 1.5~2 seconds, wich it´s normal.
But after the login, when the user it´s authenticated, response time in any request (change from /page1 to /page2 for example) it´s the same as login.

So, if you have already logged, why the component makes connections with LDAP? This causes all requests response time increments in 1,5 seconds...

Thanks!

**Comment by stevebauman** [comment]
This is a configurable option. Do you have `auto_connect` set to true? This will automatically connect to your LDAP server on every request.

**Comment by Albvadi** [comment]
Yes, I'm sure it's set as true because when I installed the component, I saw this option and I remember when putting it to false it's return a exception...

Don't remember what exception and where, because I'm not at work now, but tomorrow I'll try again...

Thanks!!

**Comment by Albvadi** [comment]
Hi again, 
I tried and this works almost completely.

I changed `auto_connect = false` and added in my middleware [(explained here)](https://github.com/Adldap2/Adldap2-Laravel/issues/117#issuecomment-224550280) at the top `\Adldap::connect('default');` and the login works well.

Unique problem at this moment it´s that `bind_user_to_model` don´t work and `Auth::user()->adldapUser` is null.
If I set `auto_connect = true` again, `Auth::user()->adldapUser` contains the user with all the attr of LDAP...

Thanks as always!

**Comment by stevebauman** [comment]
This is intended. `auto_connect` needs to be true for the `bind_user_to_model` option. I'll add some documentatiin clarifying this. Thanks for following up, and no problem at all! :)

**Comment by Albvadi** [comment]
Umm, this is a problem for me..
So, if I want attributes, I have to sync them...

It's possible to process attributes before save them in database? 
For example, if I want get the user photo, I prefer save a string in base64 in the database, instead a content in a blob column and convert always I need... Any form to do this?

**Comment by stevebauman** [comment]
> It's possible to process attributes before save them in database? 
For example, if I want get the user photo, I prefer save a string in base64 in the database, instead a content in a blob column and convert always I need... Any form to do this?

Definitely. There's two ways you can do this.

### Sync Attribute Callback

https://github.com/Adldap2/Adldap2-Laravel#sync-attribute-callbacks

```php
// config/adldap_auth.php

'sync_attributes' => [
    'name' => 'cn',
    'photo' => 'App\Handlers\LdapAttributeHandler@photo',
]
```

```php
namespace App\Handlers;

use Adldap\Models\User;

class LdapAttributeHandler
{
    public function photo(User $user)
    {
        return base64_encode($user->photo[0]);
    }
}
```

### Extending the AdldapAuthUserProvider.php

https://github.com/Adldap2/Adldap2-Laravel/blob/master/src/AdldapAuthUserProvider.php#L103

```php
use Adldap\Models\User;
use Adldap\Laravel\AdldapAuthUserProvider;

class MyAdldapAuthUserProvider extends AdldapAuthUserProvider
{
    protected function handleAuthenticatedWithCredentials(User $user, $model)
    {
        $model->photo = base64_encode($user->photo[0]);

        $model->save();
    }
}
```

**Comment by Albvadi** [comment]
I'm very clumsy... 

Sorry, I read the documentation when I started using the library and I forgot the "Sync Attribute Callback"... :sweat:
I have to re-read again and again the documentation...

I´ll try the callbacks, I thinks it´s better to control the changes that extending the classes...

Thanks as always for pointing me to the right way...
And of course, for the library. Your work it´s superb, always thinking on the users (adding callbacks or with super useful features such import users...)

Thanks so much! :wink:

**Comment by stevebauman** [comment]
No problem at all! Please don't hesitate to create further issues if you encounter any, thanks!
