### ISSUE TITLE
login with to ad

### ISSUE THREAD

**Issue by getcrud** [Adldap2/Adldap2-Laravel#131]
hello everybody,
i newbies on ldap and ad. in current time, i can connect to ldap and get information of specific account but i can't create login. this my code on laravel 5.2`<?php

namespace App\Http\Controllers;

use Adldap\Laravel\Facades\Adldap;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Auth;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        //$this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $user = Adldap::getDefaultProvider()->search()->users()->find('pitt');
        echo '<textarea cols="50" rows="10">', print_r($user, true), '</textarea>';
/* it have user information in textarea */

        $email = 'Pitt.P@xxx.com';
        $email = 'pitt@yyy';

        $credentials = [
           // 'email' => 'Pitt.P@xxx.com',
            'password' => 'ppppp',
            'samaccountname' => 'Pitt@domain.group',
/* samaccountname value as same as in user information  */
        ];

        try {
            if (Auth::attempt($credentials)) {echo 'true';} else {echo 'failed';}
        } catch (\ErrorException $e) {
            echo '<pre>', print_r($e, true), '</pre>';
        }

        $user = Auth::user();

        echo '<pre>', print_r($user, true), '</pre>';exit();

    }
}`

- i used same admin account and test account (pitt)
- may i used getQuery by Auth::attempt ?

**Comment by getcrud** [comment]
**config/adldap.php**
`<?php
return [
    'connections' => [

        'default' => [
            'auto_connect' => true,
            'connection' => Adldap\Connections\Ldap::class,
            'schema' => Adldap\Schemas\ActiveDirectory::class,
            'connection_settings' => [
                'account_prefix' => '',
                'account_suffix' => '@domain',
                'domain_controllers' => ['122.20.8.2'],
                'port' => 389,
                'base_dn' => 'OU=Users, DC=domain, DC=group',
                'admin_account_suffix' => '',
                'admin_username' => env('ADLDAP_ADMIN_USERNAME', 'pitt'),
                'admin_password' => env('ADLDAP_ADMIN_PASSWORD', 'ppppp'),
                'follow_referrals' => false,
                'use_ssl' => false,
                'use_tls' => false,
            ],
        ],
    ],
];
`

**config/adldap_auth.php**
`<?php

return [
    'connection' => env('ADLDAP_CONNECTION', 'default'),
    'username_attribute' => ['username' => 'samaccountname'],
    'limitation_filter' => env('ADLDAP_LIMITATION_FILTER', '(cn=*)'),
    'login_fallback' => env('ADLDAP_LOGIN_FALLBACK', false),
    'password_key' => env('ADLDAP_PASSWORD_KEY', 'password'),
    'password_sync' => env('ADLDAP_PASSWORD_SYNC', false),
    'login_attribute' => env('ADLDAP_LOGIN_ATTRIBUTE', 'samaccountname'),
    'bind_user_to_model' => env('ADLDAP_BIND_USER_TO_MODEL', false),
    'sync_attributes' => [

        'name' => 'cn',

    ],
    'select_attributes' => [
    ],
];`

**config/app.php**
`<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Application Environment
    |--------------------------------------------------------------------------
    |
    | This value determines the "environment" your application is currently
    | running in. This may determine how you prefer to configure various
    | services your application utilizes. Set this in your ".env" file.
    |
     */

    'env' => env('APP_ENV', 'production'),

    /*
    |--------------------------------------------------------------------------
    | Application Debug Mode
    |--------------------------------------------------------------------------
    |
    | When your application is in debug mode, detailed error messages with
    | stack traces will be shown on every error that occurs within your
    | application. If disabled, a simple generic error page is shown.
    |
     */

    'debug' => env('APP_DEBUG', false),

    /*
    |--------------------------------------------------------------------------
    | Application URL
    |--------------------------------------------------------------------------
    |
    | This URL is used by the console to properly generate URLs when using
    | the Artisan command line tool. You should set this to the root of
    | your application so that it is used when running Artisan tasks.
    |
     */

    'url' => env('APP_URL', 'http://localhost/laravel52/public'),

    /*
    |--------------------------------------------------------------------------
    | Application Timezone
    |--------------------------------------------------------------------------
    |
    | Here you may specify the default timezone for your application, which
    | will be used by the PHP date and date-time functions. We have gone
    | ahead and set this to a sensible default for you out of the box.
    |
     */

    'timezone' => 'UTC',

    /*
    |--------------------------------------------------------------------------
    | Application Locale Configuration
    |--------------------------------------------------------------------------
    |
    | The application locale determines the default locale that will be used
    | by the translation service provider. You are free to set this value
    | to any of the locales which will be supported by the application.
    |
     */

    'locale' => 'en',

    /*
    |--------------------------------------------------------------------------
    | Application Fallback Locale
    |--------------------------------------------------------------------------
    |
    | The fallback locale determines the locale to use when the current one
    | is not available. You may change the value to correspond to any of
    | the language folders that are provided through your application.
    |
     */

    'fallback_locale' => 'en',

    /*
    |--------------------------------------------------------------------------
    | Encryption Key
    |--------------------------------------------------------------------------
    |
    | This key is used by the Illuminate encrypter service and should be set
    | to a random, 32 character string, otherwise these encrypted strings
    | will not be safe. Please do this before deploying an application!
    |
     */

    'key' => env('APP_KEY'),

    'cipher' => 'AES-256-CBC',

    /*
    |--------------------------------------------------------------------------
    | Logging Configuration
    |--------------------------------------------------------------------------
    |
    | Here you may configure the log settings for your application. Out of
    | the box, Laravel uses the Monolog PHP logging library. This gives
    | you a variety of powerful log handlers / formatters to utilize.
    |
    | Available Settings: "single", "daily", "syslog", "errorlog"
    |
     */

    'log' => env('APP_LOG', 'single'),

    /*
    |--------------------------------------------------------------------------
    | Autoloaded Service Providers
    |--------------------------------------------------------------------------
    |
    | The service providers listed here will be automatically loaded on the
    | request to your application. Feel free to add your own services to
    | this array to grant expanded functionality to your applications.
    |
     */

    'providers' => [

        /*
         * Laravel Framework Service Providers...
         */
        Illuminate\Auth\AuthServiceProvider::class,
        Illuminate\Broadcasting\BroadcastServiceProvider::class,
        Illuminate\Bus\BusServiceProvider::class,
        Illuminate\Cache\CacheServiceProvider::class,
        Illuminate\Foundation\Providers\ConsoleSupportServiceProvider::class,
        Illuminate\Cookie\CookieServiceProvider::class,
        Illuminate\Database\DatabaseServiceProvider::class,
        Illuminate\Encryption\EncryptionServiceProvider::class,
        Illuminate\Filesystem\FilesystemServiceProvider::class,
        Illuminate\Foundation\Providers\FoundationServiceProvider::class,
        Illuminate\Hashing\HashServiceProvider::class,
        Illuminate\Mail\MailServiceProvider::class,
        Illuminate\Pagination\PaginationServiceProvider::class,
        Illuminate\Pipeline\PipelineServiceProvider::class,
        Illuminate\Queue\QueueServiceProvider::class,
        Illuminate\Redis\RedisServiceProvider::class,
        Illuminate\Auth\Passwords\PasswordResetServiceProvider::class,
        Illuminate\Session\SessionServiceProvider::class,
        Illuminate\Translation\TranslationServiceProvider::class,
        Illuminate\Validation\ValidationServiceProvider::class,
        Illuminate\View\ViewServiceProvider::class,

        /*
         * Application Service Providers...
         */
        App\Providers\AppServiceProvider::class,
        App\Providers\AuthServiceProvider::class,
        App\Providers\EventServiceProvider::class,
        App\Providers\RouteServiceProvider::class,

        Adldap\Laravel\AdldapServiceProvider::class,
        Adldap\Laravel\AdldapAuthServiceProvider::class,
    ],

    /*
    |--------------------------------------------------------------------------
    | Class Aliases
    |--------------------------------------------------------------------------
    |
    | This array of class aliases will be registered when this application
    | is started. However, feel free to register as many as you wish as
    | the aliases are "lazy" loaded so they don't hinder performance.
    |
     */

    'aliases' => [

        'App' => Illuminate\Support\Facades\App::class,
        'Artisan' => Illuminate\Support\Facades\Artisan::class,
        'Auth' => Illuminate\Support\Facades\Auth::class,
        'Blade' => Illuminate\Support\Facades\Blade::class,
        'Cache' => Illuminate\Support\Facades\Cache::class,
        'Config' => Illuminate\Support\Facades\Config::class,
        'Cookie' => Illuminate\Support\Facades\Cookie::class,
        'Crypt' => Illuminate\Support\Facades\Crypt::class,
        'DB' => Illuminate\Support\Facades\DB::class,
        'Eloquent' => Illuminate\Database\Eloquent\Model::class,
        'Event' => Illuminate\Support\Facades\Event::class,
        'File' => Illuminate\Support\Facades\File::class,
        'Gate' => Illuminate\Support\Facades\Gate::class,
        'Hash' => Illuminate\Support\Facades\Hash::class,
        'Lang' => Illuminate\Support\Facades\Lang::class,
        'Log' => Illuminate\Support\Facades\Log::class,
        'Mail' => Illuminate\Support\Facades\Mail::class,
        'Password' => Illuminate\Support\Facades\Password::class,
        'Queue' => Illuminate\Support\Facades\Queue::class,
        'Redirect' => Illuminate\Support\Facades\Redirect::class,
        'Redis' => Illuminate\Support\Facades\Redis::class,
        'Request' => Illuminate\Support\Facades\Request::class,
        'Response' => Illuminate\Support\Facades\Response::class,
        'Route' => Illuminate\Support\Facades\Route::class,
        'Schema' => Illuminate\Support\Facades\Schema::class,
        'Session' => Illuminate\Support\Facades\Session::class,
        'Storage' => Illuminate\Support\Facades\Storage::class,
        'URL' => Illuminate\Support\Facades\URL::class,
        'Validator' => Illuminate\Support\Facades\Validator::class,
        'View' => Illuminate\Support\Facades\View::class,

        'Adldap' => Adldap\Laravel\Facades\Adldap::class,
    ],

];
`

**Comment by getcrud** [comment]
**app/Http/Controllers/Auth/AuthController.php**`
<?php

namespace App\Http\Controllers\Auth;

use App\Http\Controllers\Controller;
use App\User;
use Illuminate\Foundation\Auth\AuthenticatesAndRegistersUsers;
use Illuminate\Foundation\Auth\ThrottlesLogins;
use Validator;

class AuthController extends Controller
{
    /*
    |--------------------------------------------------------------------------
    | Registration & Login Controller
    |--------------------------------------------------------------------------
    |
    | This controller handles the registration of new users, as well as the
    | authentication of existing users. By default, this controller uses
    | a simple trait to add these behaviors. Why don't you explore it?
    |
     */

    use AuthenticatesAndRegistersUsers, ThrottlesLogins;

    /**
     * Where to redirect users after login / registration.
     *
     * @var string
     */
    protected $redirectTo = '/';

    /**
     * Create a new authentication controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware($this->guestMiddleware(), ['except' => 'logout']);
    }

    /**
     * Get a validator for an incoming registration request.
     *
     * @param  array  $data
     * @return \Illuminate\Contracts\Validation\Validator
     */
    protected function validator(array $data)
    {
        return Validator::make($data, [
            'name' => 'required|max:255',
            'email' => 'required|email|max:255|unique:users',
            'password' => 'required|min:6|confirmed',
        ]);
    }

    /**
     * Create a new user instance after a valid registration.
     *
     * @param  array  $data
     * @return User
     */
    protected function create(array $data)
    {
        return User::create([
            'name' => $data['name'],
            'email' => $data['email'],
            'password' => bcrypt($data['password']),
        ]);
    }

    protected $guard = 'web';

    protected $username = 'email';

}`

**login view**
`<input id="email" type="text" class="form-control" name="email" value="Pitt.P@xxx.com">
<input id="password" type="password" class="form-control" name="password" value="pppppp">`

**Comment by stevebauman** [comment]
Hey @getcrud,

You're passing in the wrong credentials into your `Auth::attempt()` method:

According to your configuration below, you should be using a username input field:

```php
// config/adldap_auth.php
'username_attribute' => ['username' => 'samaccountname'],
```

```html
// resources/views/auth/login.blade.php
<input id="email" type="text" class="form-control" name="username">
<input id="password" type="password" class="form-control" name="password">
```

```php
// app/Http/Controllers/Auth/AuthController.php`
'password' => 'ppppp',
'samaccountname' => 'Pitt@domain.group',
```

**Comment by stevebauman** [comment]
Great to hear, no problem!

**Comment by mayrals** [comment]
hi 
i have it is error
   0/163 [>---------------------------]   0%
   Error

  Class "App\User" not found

  at C:\laragon\www\asfocusnuevo\vendor\adldap2\adldap2-laravel\src\Commands\Console\Import.php:32
2
    318▕         if (! $this->model) {
    319▕             $this->model = $this->option('model') ?? Config::get('ldap_auth.model') ?: $t
his->determineModel();
    320▕         }
    321▕
  ➜ 322▕         return new $this->model();
    323▕     }
    324▕
    325▕     /**
    326▕      * Retrieves the model by checking the configured LDAP authentication providers.

  1   C:\laragon\www\asfocusnuevo\vendor\adldap2\adldap2-laravel\src\Commands\Console\Import.php:1
05
      Adldap\Laravel\Commands\Console\Import::model()

  2   C:\laragon\www\asfocusnuevo\vendor\adldap2\adldap2-laravel\src\Commands\Console\Import.php:7
9
      Adldap\Laravel\Commands\Console\Import::import()
