### ISSUE TITLE
Login by another attribute

### ISSUE THREAD

**Issue by Pawlox** [Adldap2/Adldap2-Laravel#133]
Hey!

First of all - really great package, it save me a lot of time and work, thank you!

I have one last problem now - I managed to configure my application so I can login through my OpenLDAP server. The users are authenticated by common name (cn=common_name;dc=example;dc=com) but I want them to be able to enter they username (uid) in login form in my application instead of full name.

I need some solution to get uid from login form but send common name (related to that uid) to server, Is this even possible? Can I do it some way by the config or simple method instead of changing original package files?

**Comment by stevebauman** [comment]
Hi @Pawlox,

This is definitely possible, all through your `config/adldap_auth.php` file. You need to configure the `username_attribute` and `login_attribute` options. Here's an example (not tested):

```php
    /*
    |--------------------------------------------------------------------------
    | Username Attribute
    |--------------------------------------------------------------------------
    |
    | The username attribute is an array of the html input name and the LDAP
    | attribute to discover the user by. The reason for this is to hide
    | the attribute that you're using to login users.
    |
    | For example, if your HTML input name is `email` and you'd like users
    | to login by their LDAP `mail` attribute, then keep the
    | configuration below. However, if you'd like to login users
    | by their usernames, then change `mail` to `samaccountname`.
    | and `email` to `username`.
    |
    | This must be an array with a key - value pair.
    |
    */

    'username_attribute' => ['username' => 'uid'],
```

```php
    /*
    |--------------------------------------------------------------------------
    | Login Attribute
    |--------------------------------------------------------------------------
    |
    | The login attribute is the name of the active directory user property
    | that you use to log users in. For example, if your company uses
    | email, then insert `mail`.
    |
    | This option must be a string.
    |
    */

    'login_attribute' => env('ADLDAP_LOGIN_ATTRIBUTE', 'cn'),
```

**Comment by Pawlox** [comment]
Thank you very much for quick answear! It works, I don't know how I could miss this configuration set. Thank you again and sorry for waisting your time with such silly question.

**Comment by stevebauman** [comment]
Oh no don't worry about it! No question is silly. Thanks for using Adldap2 :).

**Comment by ibenettaleb** [comment]
Hello,

i cannot find "config/adldap_auth.php". 
i am just have this file "config/adldap.php"

**Comment by stevebauman** [comment]
Hi @ibenettaleb, you need to make sure you insert the `AdldapAuthServiceProvider` in your `config/app.php` and then run the `php artisan vendor:publish` command.
