### ISSUE TITLE
Auth::check() results false

### ISSUE THREAD

**Issue by syphernl** [Adldap2/Adldap2-Laravel#134]
I'm trying to implement this package in our app and according to the Debugbar the user is logged in properly in "web" however if I do an `Auth::check()` or use the `auth` middleware it results in `false` and for the latter it always kicks back to the login page.

**Comment by stevebauman** [comment]
Hi @syphernl,

I'm not experiencing this issue locally. What do you mean by "the user is logged in propery in 'web'"?

Can you post your Auth controller code?

**Comment by syphernl** [comment]
I'm using the [Laravel Debugbar](https://github.com/barryvdh/laravel-debugbar) and it shows that my user is logged in for guard "web":

```
web    array:2 [ "name" => "demouser" "user" => array:10 [ "id" => 1 "username" => "demouser"...
api      array:2 [ "name" => "Guest" "user" => array:1 [ "guest" => true ] ]
```

The auth controller contains:
```
    public function getLogin()
    {
        return view('auth::login');
    }

    public function postLogin(Request $request)
    {
        $rules = [
            'username' => 'required|min:3',
            'password' => 'required|min:3'
        ];
        $this->validate($request, $rules);

        // Form validated, check if the authentication matches
        if (Auth::attempt($request->input(), true)) {
            $user = Auth::user();
            // @todo: Sync the groups
            return redirect()->intended('dashboard');
        }
```

**Comment by stevebauman** [comment]
Are you sure you're passing validation? Can you try dumping your user right after authentication?

```php
// Form validated, check if the authentication matches
if (Auth::attempt($request->input(), true)) {
    $user = Auth::user();

    dd($user);
    // @todo: Sync the groups
    return redirect()->intended('dashboard');
}
```

**Comment by syphernl** [comment]
Yes, the validation passes and the user (with its attributes) is properly displayed.

**Comment by stevebauman** [comment]
Ok, and when you're redirected, you're not logged in? Just want to clarify.

**Comment by syphernl** [comment]
Yes, it redirects back the login page and the whole flow starts again. 
Op 14 jul. 2016 4:12 p.m. schreef Steve Bauman <notifications@github.com>:Ok, and when you're redirected, you're not logged in? Just want to clarify.

**Comment by stevebauman** [comment]
Can you post your `auth` middleware?

**Comment by syphernl** [comment]
The auth middleware, as requested:
```php
<?php

namespace App\Http\Middleware;

use Closure;
use Illuminate\Support\Facades\Auth;

class Authenticate
{
    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @param  string|null  $guard
     * @return mixed
     */
    public function handle($request, Closure $next, $guard = null)
    {
        if (Auth::guard($guard)->guest()) {
            if ($request->ajax() || $request->wantsJson()) {
                return response('Unauthorized.', 401);
            } else {
                return redirect()->guest(route('login'));
            }
        }

        return $next($request);
    }
}

```

**Comment by stevebauman** [comment]
Hmm everything seems fine, can you post your routes?

**Comment by syphernl** [comment]
Ha, apparently the `web` middleware was missing from the route I was testing this on. Silly mistake, annoyingly 'web' isn't the default middleware anymore causing stuff like this.

Seems to be working fine now, thanks for the help @stevebauman !

**Comment by stevebauman** [comment]
Awesome! No problem, I've encountered the same issue many times.

Don't hesitate to create another issue if you experience anything further, thanks!
