### ISSUE TITLE
Fatal error on binding ldap user to model

### ISSUE THREAD

**Issue by skincer** [Adldap2/Adldap2-Laravel#135]
AdldapAuthUserProvider on line 137

Happened to me when the model didn't exist for an unrelated reason. Was wondering if it would make sense to check if the model exists here before trying to bind:

`protected function discoverAdldapFromModel($model)
    {
        if ($this->getBindUserToModel() && $model) {
        }
        return $model;
    }`

**Comment by stevebauman** [comment]
Maybe related to #136? Going to update this now and see if this solves the issue.

**Comment by stevebauman** [comment]
Just pushed https://github.com/Adldap2/Adldap2-Laravel/commit/3b2ae13c3e85ce8a030fca7363462c2b8ba2ee47, thanks for this!

Please give the new release a try and let me know your outcome.

**Comment by skincer** [comment]
Looks great, thanks.
