### ISSUE TITLE
Port isn't used when using LDAP URL as hostname

### ISSUE THREAD

**Issue by jhayiwg** [Adldap2/Adldap2-Laravel#137]
Hello, 

I`m trying to solve this issue but no luck.

Trying to login with this code works fine:
 \Adldap::getDefaultProvider()->auth()->attempt($username, $password)

But if I`m trying to use \Auth::attempt([ 'username'=> $username, 'password'=>$password ]) or \Adldap::getDefaultProvider()->search()->users()->get() it returns nothing/false.

Any advice?

**Comment by stevebauman** [comment]
Hi @jhayiwg,

Are you using OpenLDAP?

**Comment by jhayiwg** [comment]
Thanks Steve,

I found the issue and it works fine, I`m not sure it its my ldap library.

From:
` return $this->connection = ldap_connect($this->getHostname($hostname, $this->getProtocol()), $port);`
To:
`return $this->connection = ldap_connect($this->getHostname($hostname, $this->getProtocol()) .":". $port);`

Base from http://php.net/manual/en/function.ldap-connect.php.
The port to connect to. Not used when using LDAP URIs.

I hope you can advice me the best way to deal with this.

**Comment by stevebauman** [comment]
Fixed: https://github.com/Adldap2/Adldap2/commit/d08beaa8fa0519e93c05c274ea7c5b3a3a6a1faf

Thanks for the report!
