### ISSUE TITLE
Returning selective data on login / auth

### ISSUE THREAD

**Issue by clonerworks** [Adldap2/Adldap2-laravel#14]
Hi,

First up thank you for this brilliant project!
I have built it into what i am developing and find it very useful.

I do have a few questions to see if things are possible in the current repo and if not maybe feature requests.

Currently when i authenticate a use with the default settings it is returning all attributes the user has in AD. Is there a way to select only certain attributes for the user?

Same when i select the users groups with the following method, it returns all attributes for the groups from AD when i only really want 2 of them. The reason i am asking about this is in our AD we have groups with 3 or 4 thousand users so if the tools returns all attributes it may take more time.

Along with this i would like to be able to pull groups recursively for the user so that i can see what groups they are nested it

```php
// Retrieving the authenticated LDAP users groups
$groups = $user->adldapUser->getGroups();
```

Thanks in advance.

**Comment by stevebauman** [comment]
Hi, thanks for creating an issue for this!

To answer your question, no, unfortunately limiting the attributes that are retrieved when the `adldapUser` property is set is not possible, but I completely agree that this should be an option. I'll implement this shortly.

I'll also add the ability to limit the attributes retrieved in the `getGroups()` method as well.

**Comment by clonerworks** [comment]
Thanks heaps! I look forward to playing around with the code once implemented.

**Comment by stevebauman** [comment]
Added ability to limit fields in `getGroups()` method as well: https://github.com/Adldap2/Adldap2/commit/3285dc72818068a8f5f8375cdf40c5ab31702d72

A release will be pushed out shortly.
