### ISSUE TITLE
Import Pagination and Filter stops at 50

### ISSUE THREAD

**Issue by sloan58** [Adldap2/Adldap2-Laravel#140]
I've copied and updated the adldap:import command to use pagination and a raw filter:

$filter = '(iptlocation=*)';
$users = $adldap->search()->users()->rawFilter($filter)->paginate();

but I'm not getting a full sync.  It stops after 50 records:

➜  php artisan myldapimportcommand:import
Found 21663 user(s). Starting import...
Successfully imported 50 user(s).

In the logs I see each of the 50 imports happen successfully but then it just stops.  Any idea why? 

Thanks

**Comment by stevebauman** [comment]
Hi @sloan58,

The `paginate()` method is by default limited to `50` entries **per page**, so if you're iterating **over** the paginator, you'll only be iterating over the first 50.

https://github.com/Adldap2/Adldap2/blob/master/src/Query/Builder.php#L290

Try:

```php
$filter = '(iptlocation=*)';

$users = $adldap->search()->users()->rawFilter($filter)->paginate()->getResults();
```

**Comment by sloan58** [comment]
Hi @stevebauman,

Thanks for the assistance.  I updated the code and receive an error:

`[Symfony\Component\Debug\Exception\FatalThrowableError]
  Call to a member function count() on array`

I'll start to debug but if you have any thoughts it's appreciated.

**Comment by stevebauman** [comment]
You'll need to update this line because the `count()` method doesn't exist:

https://github.com/Adldap2/Adldap2-Laravel/blob/master/src/Commands/Import.php#L54

```php
$filter = '(iptlocation=*)';

$users = $adldap->search()->users()->rawFilter($filter)->paginate()->getResults();

$this->info("Found {count($users)} user(s). Starting import...");
```

**Comment by sloan58** [comment]
Ah, many thanks!  Working perfectly now.  Currently importing all accounts.

**Comment by stevebauman** [comment]
No problem! You've actually given a great idea for the import command.

I'll add a command argument option to specify a filter and use pagination to avoid hitting a limit of imports.

Thanks! :)

**Comment by sloan58** [comment]
Beautiful!  I'm using this in a test app right now and will wait for your update to integrate with my 'real' applications.  Great package!

**Comment by stevebauman** [comment]
Just added in commit https://github.com/Adldap2/Adldap2-Laravel/commit/b288d0e252aa7a098d86911bb6ee233f47c22a07

Appreciate the kind words! Thanks again :)
