### ISSUE TITLE
adldap2-laravel with cartalyst sentinel

### ISSUE THREAD

**Issue by sloan58** [Adldap2/Adldap2-Laravel#141]
I'm using Cartalyst Sentinel for authentication and would like to add adldap2-laravel integration. 

I've added `Adldap::auth()->attempt` after my Sentinel `Sentinel::authenticateAndRemember` login step.  I'm able to authenticate the user but they are not 'logged in' to Laravel.

**Comment by stevebauman** [comment]
You can easily add integration by automatically creating a new user if they pass LDAP authentication:

```php


if (Adldap::auth()->attempt($request->username, $request->password)) {
    $user = Sentinel::registerAndActivate([
        'email' => $request->email,
        'password' => $request->password,
    ]);

    Sentinel::login($user);

    return back()->withMessage("You're logged in!");
}
```
