### ISSUE TITLE
LDAP Auth()->attempt() not working

### ISSUE THREAD

**Issue by arredgroup** [Adldap2/Adldap2-Laravel#144]
Hi, I use Adldap2-Laravel in my project and when I try to configure Auth with LDAP the login doesn't work
if I use:
`
$users = Adldap::getProvider('default')->search()->users()->first();
dd($users);
`
the result print a null value, but, if I use:

`
$users = Adldap::getProvider('default')->search()->where('uid', '=', 'user.test')->get();
//dd($users);
`
the result print the value of user.test

while I'm searching in the files, in AdldapAuthUserProvider.php Line 188-189
`
$user = $this->newAdldapUserQuery()->where([
                $this->getUsernameValue() => $username,
            ])->first();
            dd($user); //print the value of user
`

 the dd function print null

please, can you help me??

**Comment by arredgroup** [comment]
Data Info:

`'account_prefix' => 'uid=',`
`'domain_controllers' => ['*****.ulagos.cl'],`
`'base_dn' => 'ou=pers,dc=ulagos,dc=cl',`
`'admin_username' => env('ADLDAP_ADMIN_USERNAME', 'cn=readadmin,dc=ulagos,dc=cl'),`
`'admin_password' => env('ADLDAP_ADMIN_PASSWORD', 'adminread'),`

**Comment by arredgroup** [comment]
The Answer is this:

In file config/adldap.php
set this: 
`'schema' => Adldap\Schemas\OpenLDAP::class,`

But, When I try to 
`$users = Adldap::getProvider('default')->auth()->attempt('user', 'pass');`
`dd ($users);`
always dd print false

why???

**Comment by dgeyer263** [comment]
I am also getting the same issue with Laravel 5.3-dev when I dd the following

dd(\Adldap::auth()->attempt('username','password'));
=> false

`PHP warning:  ldap_bind(): Unable to bind to server: Invalid credentials in /home/vagrant/test/vendor/adldap2/adldap2/src/Connections/Ldap.php on line 253`

**Comment by stevebauman** [comment]
Hi @arredgroup,

Please make sure the group with the `uid` you're authenticating with is located in the `base_dn` you've specified (`ou=pers,dc=ulagos,dc=cl`).
