### ISSUE TITLE
Windows SSO Middleware

### ISSUE THREAD

**Issue by randyrankin** [Adldap2/Adldap2-Laravel#145]
I have been able to successfully test that logging in as an AD user and a record is created in the users table, I would like to now configure Windows SSO but I'm somewhat confused. The documentation, under Windows Authentication (SSO) Middleware, reads:

> This is configurable in your adldap_auth.php configuration file.

However, I don't see anything about this configuration in the adldap_auth.php. 

Apache is configured to auth my Windows session and I can echo my Windows user name with $_SERVER['AUTH_USER'] . I have also added \Adldap\Laravel\Middleware\WindowsAuthenticate::class to the middleware stack but I am still presented with the login form when trying to access a protected page.

**Comment by stevebauman** [comment]
Hi @randyrankin,

> However, I don't see anything about this configuration in the adldap_auth.php.

Apologies for that, it was previously missing from the `adldap_auth.php` configuration. If you run `composer update` and re-publish the configuration files, you'll be able to see the new option: https://github.com/Adldap2/Adldap2-Laravel/commit/d1fba8256c67a0a4be4ed0bea4ad33939faf91b0

For your issue with automatic login not functioning, some configuration may need to take place. Inside  the `$_SERVER['AUTH_USER']` variable, is your windows user name equal to the users `samaccountname` attribute?

**Comment by randyrankin** [comment]
Thanks Steve. I re-published to configuration files and can now see the section on Windows Auth Attribute., 

Both $_SERVER['REMOTE_USER'] and $_SERVER['PHP_AUTH_USER'] return my UserPrincipalName, not SamAccountName. Do I just need to change 'windows_auth_attribute' => ['samaccountname' => 'AUTH_USER'] to 'windows_auth_attribute' => ['userprinciplename' => 'AUTH_USER']? Are there other areas that I should configure?

**Comment by stevebauman** [comment]
Yup that's correct, just change it to `userprincipalname` and it should automatically login the user.

**Comment by randyrankin** [comment]
Also wanted to mention that `$_SERVER['AUTH_USER'] `returns an error. I think that was removed from PHP at some point? Not sure.

**Comment by randyrankin** [comment]
I made the change and still hang up on the login page with no record being created in the users tables. I'll retrace all my steps from docs.

**Comment by randyrankin** [comment]
OK, got it working! I had to also change AUTH_USER to PHP_AUTH_USER like this `'windows_auth_attribute' => ['userprincipalname' => 'PHP_AUTH_USER'],`

Should I also change `'login_attribute' => env('ADLDAP_LOGIN_ATTRIBUTE', 'samaccountname'),` to `'login_attribute' => env('ADLDAP_LOGIN_ATTRIBUTE', 'userprincipalname'),`?

**Comment by stevebauman** [comment]
That's great! Good to know about the server attribute `PHP_AUTH_USER`, this is probably specific to apache (I've only setup SSO in IIS).

For your login attribute question, you can if you'd like, if you're still allowing LDAP users to authenticate through your login form normally, then it might be good to.

Closing, but if you encounter any further issues please don't hesitate to create another :).
