### ISSUE TITLE
Route Level Access

### ISSUE THREAD

**Issue by randyrankin** [Adldap2/Adldap2-Laravel#146]
Is it possible to create a limitation filter for a route that allows only the user who belongs to a particular group to access that route? For example, route /home would allow all users in group 'Home', route /accounting would allow only users in group 'Accounting', route /marketing would only allow users in group 'Marketing', etc.?

**Comment by stevebauman** [comment]
You'd have to create a middleware for this and have the `bind_user_to_model` option enabled so you're able to retrieve the LDAP users model on every request to verify their access.

https://github.com/Adldap2/Adldap2-Laravel#binding-the-adldap-user-model-to-the-laravel-user-model

For example:

```php
namespace App\Http\Middleware;

use Closure;
use Illuminate\Support\Facades\Auth;

class Accounting
{
    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure                             $next
     *
     * @return mixed
     */
    public function handle($request, Closure $next)
    {
        // Only allow users inside the `accounting` group.
        if (Auth::user()->adldapUser->inGroup('accounting')) {
            return $next($request);
        }

        return response('Unauthorized.', 401);
    }
}
```

Then add it to your `$routeMiddleware` stack inside your `app/Http/Kernel.php`:

```php
/**
 * The application's route middleware.
 *
 * These middleware may be assigned to groups or used individually.
 *
 * @var array
 */
protected $routeMiddleware = [
    'auth' => \App\Http\Middleware\Authenticate::class,
    'auth.basic' => \Illuminate\Auth\Middleware\AuthenticateWithBasicAuth::class,
    'can' => \Illuminate\Foundation\Http\Middleware\Authorize::class,
    'guest' => \App\Http\Middleware\RedirectIfAuthenticated::class,
    'throttle' => \Illuminate\Routing\Middleware\ThrottleRequests::class,
    'accounting' => \App\Http\Middleware\Accounting::class,
];
```

**Comment by randyrankin** [comment]
I've enabled `bind_user_to_model`, created middleware and added to $routeMiddleware as above and created an AD accounting group with myself as a member.

I'm assuming that I would then change `$this->middleware('auth')` to `$this->middleware('accounting')` in the controller. 

With all this in place, when I try to access the route, I receive a site cannot be reached error. The console reports `GET http://test.dev.smith-blair.net/accounting net::ERR_INVALID_HANDLE`.

**Comment by randyrankin** [comment]
OK, so I'm thinking that maybe the group isn't being found? Do I possibly need to set the DN in the middleware?

**Comment by stevebauman** [comment]
You shouldn't need to, you can test your middleware by just visiting the protected route, and see if Adldap can find the groups:

```php
namespace App\Http\Middleware;

use Closure;
use Illuminate\Support\Facades\Auth;

class Accounting
{
    /**
     * Handle an incoming request.
     *
     * @param \Illuminate\Http\Request $request
     * @param \Closure                 $next
     *
     * @return mixed
     */
    public function handle($request, Closure $next)
    {
        $groups = Auth::user()->adldapUser->getGroups();

        // Dump and die all the currently authenticated users groups.
        dd($groups);

        // Only allow users inside the `accounting` group.
        if (Auth::check() && Auth::user()->adldapUser->inGroup('accounting')) {
            return $next($request);
        }

        return response('Unauthorized.', 401);
    }
}
```

**Comment by randyrankin** [comment]
Haha, I figured it out. The middleware reference was 'accounting' and the group name is 'Accounting'. Once I changed the middleware it is working.

**Comment by stevebauman** [comment]
Perfect! Glad it's working :).

**Comment by randyrankin** [comment]
So, just to make sure I understand, I would need to create a middleware for each group and apply it to each route as applicable?

**Comment by randyrankin** [comment]
Can inGroup accept an array? Or is there a way to check multiple groups in the middleware?

**Comment by stevebauman** [comment]
> So, just to make sure I understand, I would need to create a middleware for each group and apply it to each route as applicable?

Yup, or you can create a middleware with a `$group` parameter, so you can specify a group in your routes file like so:

```php
Route::group(['middleware' => ['auth']], function () {

    // Only accountants can visit this route.
    Route::get('accounting', [
        'uses' => 'AccountingController@index',
        'middleware' => ['group:Accounting']
    ]);

    // Only the marketing team can visit this route.
    Route::get('marketing', [
        'uses' => 'MarketingController@index',
        'middleware' => ['group:Marketing']
    ]);

});
```

For creating a middleware with parameters, see: https://laravel.com/docs/5.2/middleware#middleware-parameters

**Comment by stevebauman** [comment]
> Can inGroup accept an array? Or is there a way to check multiple groups in the middleware?

That's a great point, right now you can't use an array in `$user->inGroup()`.

I'll implement this now :).

**Comment by randyrankin** [comment]
Thank you! I've asked you two questions today and you got me answered and on my way quickly and effectively! Great package, great support!

**Comment by stevebauman** [comment]
No problem at all! Thanks for the kind words :)
