### ISSUE TITLE
Importing and updating users that have changed username and/or email in AD

### ISSUE THREAD

**Issue by ovidiubadita** [Adldap2/Adldap2-Laravel#147]
I need to update all fields for an imported user and somehow keep in sync my table with what is in AD. The only key that seems to be immutable in AD is the GUID. Is there a way to specify in config that I want to use GUID as the key to search in AD and after that, on import or on login to update all other fields with the new values?

**Comment by stevebauman** [comment]
Hi @ovidiubadita,

When you mention importing, are you referring to the `php artisan adldap:import` command? Or are you referring to the import of the user account upon authenticating?

**Comment by ovidiubadita** [comment]
Actually, both things. My plan is to run the artisan command daily. But on login, when the request is from a specific IP class, I will use the AD authentication, else, I will not allow AD users in. I suppose I could do that in the Auth controller. But if for some reason, the AD is unavailable, I will default to my user table. The problem is that users from AD can have the username changed marriage, and I can't use the username as a key, and all other keys can change for different reasons.
Maybe my approach is a bit naive... I am new to Laravel. Is my first project with this framework, and as it happens, is a bit bigger than I wanted the first project to be in a new framework. But I love the challenge. :) 
Also, another thing is that I have lots of users and it eats a lot of memory when I run the artisan command. Is there a way to paginate the request and take parts of it at a time? My plan was to search for a way to do it on my own, but is probably something already solved and I just can't figure out what config deals with that.

**Comment by warlord0** [comment]
Just my 0.02c

Once thing we never do in AD is change a users logon credential. Regardless of marriage. All other attributes, fine, but never the logon name. Causes way too much grief for profiles and many other apps that use some form of AD credential sync. Often easier to delete the account and create a new one.

As for the sync on logon, that's already there. I use it now to sync cn, mail and dn attributes to the user model, just using the config\adldap.php

**Comment by ovidiubadita** [comment]
I can understand that in most places this rule is a good one. But where I work, the rule is to change the logon and is nothing I can do about that. I will have to deal with it.

**Comment by stevebauman** [comment]
Hi @ovidiubadita,

> Is there a way to paginate the request and take parts of it at a time?

This has already been added to `v3.0`:

https://github.com/Adldap2/Adldap2-Laravel/blob/master/src/Commands/Import.php#L206-L208

For your other issue, this would be difficult to implement, and you'd most likely have to implement this yourself.

The only option I see for this to work, is to use a different attribute to authenticate users by, and then add their synced options to the `adldap_auth.sync_attributes` array. However this wouldn't resolve your main concern of logging in users with an updated username.

You will need to look at overriding the resolver and the importer (new features in `v3.0`) and locate / import users by an attribute that doesn't change on AD - such as their object SID.

Or, what you could do, is once you change the username in AD, update their user record manually in your applications database with their updated username.
