### ISSUE TITLE
Anonymous User

### ISSUE THREAD

**Issue by randyrankin** [Adldap2/Adldap2-Laravel#148]
I am creating a dashboard application using Laravel (eg; dashboard.example.com) which is driven by a chromebook connected to a large display. Since the chromebook cannot be joined to the domain, the user is anonymous. I have created an admin section  (eg; dashboard.example.com/admin) so that an AD user can change the dashboard content. Adldap2-Laravel is installed, configured and working perfectly for this section and all routes are protected. 

My question is this: how would I allow an anonymous user access to the root url so that is does not prompt for a password? I have tried to add another directive to Apache but because of the way Laravel routes through public/index.php I don't think that will work. I also tried using the User table fallback method until I realized (duh) that the "user" isn't logged in anyway. 

I'm not sure what else to try. Is there possibly a way to programatically pass a user/pass combo for the / route? I hope that this makes sense and I'm sorry if this is actually an Apache question but thought I would ask if anyone had any suggestions.

**Comment by randyrankin** [comment]
I was able to resolve this by creating another middleware for the the / route and manually passing in an AD account. Still not sure if this is the most efficient or effective way but is seems to work. 

**Note: Using Laravel 5.3**

## app/Http/Middleware/AutoAuthADUser.php
```
namespace App\Http\Middleware;

use Closure;
use Adldap\Contracts\AdldapInterface;

class AutoAuthADUser
{
    protected $adldap;

    public function __construct(AdldapInterface $adldap)
    {
        $this->adldap = $adldap;
    }

    public function handle($request, Closure $next)
    {
        if (! $this->adldap->auth()->attempt('user.name', 'user.password', $bindAsUser = true)) {
            abort(403, 'Unauthorized action.');
        }

        return $next($request);
    }
}
```

### App\Http\Kernel

```
protected $routeMiddleware = [
        ...
        'ad.auto.auth' => \App\Http\Middleware\AutoAuthADUser::class,
];
```

### routes\web.php

`Route::get('/', ['uses' => 'DashboardController@index', 'middleware' => ['ad.auto.auth']]);`

**Comment by stevebauman** [comment]
Hi @randyrankin,

In my experience with IIS, SSO seems to be 'all or nothing'. When you enable SSO on your server, if no valid AD credentials are given, it will just deny all requests (correct me if I'm wrong).

For your provided middleware, is this route an exception to SSO in apache? What would be the point in automatically authenticating to your LDAP server on a hard-coded account?

**Comment by randyrankin** [comment]
The 'all or nothing' rule applies to Apache as well because of the Apache `Require valid-user` directive.  

Because we are using a Chromebox, which cannot be joined to the domain, as soon as Chrome (which is configured to automatically start in Kiosk mode) hits the root url, the browser prompts for a password. If I enter user/pass creds for a valid AD user, all is well, but obviously we don't want to have to do that every time one of these devices is restarted which is why I needed to try to come up with a solution that prevents that from happening, hence the middleware. Does that make sense?

I don't really like having to hard-code credentials but that's the only way I could make this all work. I was wondering if the creation of a proxy-user attribute in the adldap-auth.php file might be justified. I know this is an edge case but it might be handy for others in the same situation.

**Comment by stevebauman** [comment]
So when you authenticate manually in your middleware, you don't actually receive the prompt for credentials? Or are you exempting that specific URL from SSO auth in your Apache config?

I'm just curious how you set this up is all :smile:

**Comment by randyrankin** [comment]
That is correct. When I use the above middleware for the `/` route with the AD user manually entered, I do not receive the prompt for credentials. When I use the inGroup middleware from [issue 146](https://github.com/Adldap2/Adldap2-Laravel/issues/146) on the `/admin` route, I am authenticated correctly as myself (because I am in the AD group that Adldap is checking).

Regarding Apache, while it may be possible to define a specific URL and allow all, I couldn't come up with a solution after several hours of searching and trying different configurations. It may be possible, I just couldn't figure out how to override Require valid-user for one URL.

**Comment by randyrankin** [comment]
Fore reference, here is my apache virtual hosts entry

```
ServerName lobby.dashboard.example.net
ServerAlias lobby.dashboard.example.net
DocumentRoot /var/www/dashboards/lobby/public
<Directory /var/www/dashboards/lobby/public>
   DirectoryIndex index.php
   Options Indexes FollowSymLinks
   AllowOverride All
   AuthType Kerberos
   AuthName "Dashboard"
   KrbAuthRealms EXAMPLE.NET
   KrbServiceName HTTP
   Krb5Keytab /etc/dashboard.keytab
   KrbMethodNegotiate On
   KrbMethodK5Passwd On
   Require valid-user
</Directory>
```

**Comment by stevebauman** [comment]
Thanks for the detailed info @randyrankin! I'll be sure to put this in the docs.
