### ISSUE TITLE
Ability to check if model is apart of multiple groups

### ISSUE THREAD

**Issue by stevebauman** [Adldap2/Adldap2-Laravel#149]
Referenced in #146, the ability to check for multiple groups at once needs to be added. This array can contain a Group model, common name, or the groups distinguished name.

```php
$groups  = [
    'cn=My Group,dc=corp,dc=acme,dc=org', // Group DN
    $group // Group Model
    'My Group' // Group Name
];

if ($user->inGroup($groups)) {
    // The user is apart of all of the specified groups
}
```

**Comment by randyrankin** [comment]
Thanks for this @steveauman! Great new feature!

**Comment by randyrankin** [comment]
Just now getting around to looking at this and can't seem to get it working with multiple groups. A single group works fine. 

An example route looks like this: `Route::get('/', ['uses' => 'HomeController@index', 'middleware' => ['auth.group:Systems,Marketing']]);` 

The middleware is as follows: 

```
class VerifyGroupMembership
{
    public function handle($request, Closure $next, ... $groups)
    {
        if ( ! Auth::user()->adldapUser->inGroup($groups)) {
            abort(403, 'Unauthorized action.');
        }

        return $next($request);
    }
}
```
In the middlware, a `dd($groups)` returns the following so I know the variables are arriving to the middleware. 

```
array:2 [▼
  0 => "Systems"
  1 => "Marketing"
]
```
But the auth check fails. 
I also tried manually placing` $myGroups = ['Systems','Marketing'];` in the middlware and passing that to `inGroup()` but that also fails. Any ideas?

**Comment by stevebauman** [comment]
Is the user that's authenticated apart of both the `Systems` and `Marketing` groups?

**Comment by randyrankin** [comment]
I am the user and I am in the Systems group, not the Marketing group.

**Comment by randyrankin** [comment]
`inGroup($groups, $recursive = true)` does not seem to make a difference.

**Comment by stevebauman** [comment]
Oh, that's the reason then. The user must be apart of **both** groups that you give, not just one.

**Comment by randyrankin** [comment]
OK, that makes sense. What does $recursive do?

**Comment by stevebauman** [comment]
If for example, the `Marketing` group was apart of the `Systems` group:

```php
// This would return true
$user->inGroup(['Marketing', 'Systems'], true);

// This would return false
$user->inGroup(['Marketing', 'Systems']);
```

The `$recursive` option pulls in groups of groups, merges the results, then checks if the user is in each of the specified groups.

**Comment by randyrankin** [comment]
OK, perfect. There is my work around then. So, I can create a Domain Universal group called Intranet-Marketing for example, and add groups (eg; Marketing, Systems) or users to it and set the recursive option to true. I just test that and it seems to work well.
