### ISSUE TITLE
Bypassing SSL/TLS while changing user attributes

### ISSUE THREAD

**Issue by ozza** [Adldap2/Adldap2-Laravel#150]
Hello again,

As the title says, is it possible to bypass SSL/TLS while changing a users attributes? Like change password?

I was able to do this by using PHP LDAP library (by binding the administrator account and selecting a specified users attributes). Is Adldap2-Laravel allowing this without using SSL/TLS?

Thank you again.

**Comment by stevebauman** [comment]
Hi @ozza,

How did you previously perform this without utilizing SSL or TLS?

Can you provide a code example?

To my knowledge, SSL / TLS is required when changing passwords through LDAP (you'll receive a `Server is unwilling to perform exception`), but I could definitely be wrong.

**Comment by stevebauman** [comment]
You can always create a custom `BatchModification` object and add it to your model?

```php
$user = Adldap::search()->find('admin');

$mod = new BatchModification('userpassword'. LDAP_MODIFY_BATCH_REPLACE, ["123456QQ"]);

$user->addModification($mod);

if ($user->save()) {
    // Password was saved.
}
```

**Comment by ozza** [comment]
Thank you for your answer.

I already applied a similar solution you just gave. I hope it's a secure way.

**Comment by stevebauman** [comment]
Well the passwords will be sent in plain text unless you use SSL or TLS. There's no way around that unfortunately.
