### ISSUE TITLE
Can not make file config/adldap_auth.php

### ISSUE THREAD

**Issue by nguyen-vq** [Adldap2/Adldap2-Laravel#151]
When i install this package with step by step. But i can see file: config/adldap_auth.php
Could any one help me ?
Thanks

**Comment by stevebauman** [comment]
Did you insert the `AdldapAuthServiceProvider` in your `config/app.php` file and run `php artisan vendor:publish`?

**Comment by nguyen-vq** [comment]
Yes, I follow with step by step in 
https://github.com/Adldap2/Adldap2-laravel#installation-1.
I using laravel 5.2.

**Comment by nguyen-vq** [comment]
Ah, This is my mistake, I don't import AdldapAuthServiceProvider. It's only AdldapServiceProvider.
Thanks @stevebauman

**Comment by stevebauman** [comment]
No problem! Glad you have it resolved :).
