### ISSUE TITLE
Error: Invalid DN syntax

### ISSUE THREAD

**Issue by nguyen-vq** [Adldap2/Adldap2-Laravel#152]
The first time i wanna say thanks to @samwilson @laurin1 @michaelachrisco @chrisbaswell @ralfbecker.
I'm installed this package into my project. But i have issue with DN. 
I trying with base `ldap_bind` of PHP

```
<?php
$ldap = ldap_connect("xxx.xxx.xxx.xxx");
if ($bind = ldap_bind($ldap, 'cn=[Full name],cn=[Group],ou=Users,dc=ldap,dc=domain,dc=vn', 'secret')) {
    echo "Success";
} else {
    echo "Fails";
}
```

It's mean, when i login, i need input full DN into `ldap_bind`. 
Back with this package, I setting:
1. config/adldap.php

```
<?php

return [
    'connections' => [
        'default' => [
            'auto_connect' => true,
            'connection' => Adldap\Connections\Ldap::class,
            'schema' => Adldap\Schemas\ActiveDirectory::class,
            'connection_settings' => [
                'account_prefix' => '',
                'account_suffix' => '',
                'domain_controllers' => ['xxx.xxx.xxx.xxx'],
                'port' => 389,
                'timeout' => 5,
                'base_dn' => 'ou=Users,dc=ldap,dc=domain,dc=vn',
                'admin_account_suffix' => '',
                'admin_username' => env('ADLDAP_ADMIN_USERNAME', 'username'),
                'admin_password' => env('ADLDAP_ADMIN_PASSWORD', 'password'),
                'follow_referrals' => false,
                'use_ssl' => false,
                'use_tls' => false,
            ],
        ],
    ],
];
```
1. config/adldap_auth.php

```
<?php

return [
    'connection' => env('ADLDAP_CONNECTION', 'default'),
    'username_attribute' => ['username' => 'uid'],
    'limitation_filter' => env('ADLDAP_LIMITATION_FILTER', ''),
    'login_fallback' => env('ADLDAP_LOGIN_FALLBACK', true),
    'password_key' => env('ADLDAP_PASSWORD_KEY', 'password'),
    'password_sync' => env('ADLDAP_PASSWORD_SYNC', true),
    'login_attribute' => env('ADLDAP_LOGIN_ATTRIBUTE', 'uid'),
    'windows_auth_attribute' => ['samaccountname' => 'AUTH_USER'],
    'bind_user_to_model' => env('ADLDAP_BIND_USER_TO_MODEL', false),
    'sync_attributes' => [
        // 'name' => 'cn',
        'name' => 'App\Handlers\LdapAttributeHandler@name',
    ],
    'select_attributes' => [
       //
    ],
];
```

And of course i setting like with:
https://github.com/Adldap2/Adldap2-laravel#auth-driver
So, How can i config or update what for authenticate with AD LDAP with my full DN: 
`cn=[Full name],cn=[Group],ou=Users,dc=ldap,dc=domain,dc=vn`

Thank you so much.

**Comment by stevebauman** [comment]
Hi @nguyen-vq,

Just so I understand, you're wanting users to have to enter in their full distinguished name to authenticate in your login form?

**Comment by nguyen-vq** [comment]
Hi @stevebauman,
It's not what i need. 
It's mean, how can i config LDAP Auth with user enter only username and password LDAP.
Example:
My information for auth LDAP is:
username: nguyenvq
Password: secret
When i enter correct username and password into form login, I can access to website.

**Comment by stevebauman** [comment]
Did you follow the auth usage documentation?

https://github.com/Adldap2/Adldap2-Laravel#usage-1

**Comment by nguyen-vq** [comment]
Hi @stevebauman ,
Yes I had follow this document.
I think this problem is DN of LDAP server. :(

**Comment by nguyen-vq** [comment]
Hi @stevebauman 
Can you suggest to me other solutions for this issue?
I found root case of this issue is: My LDAP DN have dynamics cn [Group] `cn=[Group]`. 
Examples:
User A in group: GA. Full DN is:
`cn='User A',cn=GA,ou=Users,dc=ldap,dc=domain,dc=vn`

User B in group: GB. Full DN is:
`cn='User B',cn=GB,ou=Users,dc=ldap,dc=domain,dc=vn`

But this package auth only with statics DN: `ou=Users,dc=ldap,dc=domain,dc=vn`

Big thank to you. :)

**Comment by stevebauman** [comment]
Closing due to no response.
