### ISSUE TITLE
Laravel 5.3 Support

### ISSUE THREAD

**Issue by darylgeyerii** [Adldap2/Adldap2-Laravel#153]
Any news on making this package work with Laravel 5.3. Appears to be Auth issues when trying to authenticate to LDAP or ActiveDrectory.

**Comment by stevebauman** [comment]
Hi @dgeyer263,

I'm definitely going to offer 5.3 support. Can you explain further the issues you're experiencing?

**Comment by dgeyer263** [comment]
See my reply in ticket https://github.com/Adldap2/Adldap2-Laravel/issues/144

**Comment by stevebauman** [comment]
Don't think this is a Laravel 5.3 issue. I just created a test Laravel 5.3 app and I was able to authenticate normally just like in 5.2.

Did you follow the entire setup documentation? Unfortunately the validation error `These credentials do not match our records` could be caused by many different things.

Can you post your `adldap_auth.php` config file along with your `AuthController.php`?

**Comment by randyrankin** [comment]
I am also using Adldap2-Laravel with Laravel 5.3 and it works fine.

**Comment by darylgeyerii** [comment]
@randyrankin are you using the email field or username for Authentication?

**Comment by randyrankin** [comment]
I'm using the Windows Auth Attribute for SSO, however, when I initially installed, I was using the username.  Once that was working I made the switch to SSO. I did have to change the `login_attribute`  and the `windows_auth_attribute` in `adldap_auth` to `userprincipalname`. You might want to take a look at issue #145

**Comment by darylgeyerii** [comment]
```
Found my issue it was in this code

 /*
                |--------------------------------------------------------------------------
                | Account Prefix
                |--------------------------------------------------------------------------
                |
                | The account prefix option is the prefix of your user accounts in AD.
                |
                | For example, if you'd prefer your users to use only their username instead
                | of specifying a domain ('ACME\jdoe'), enter your domain name.
                |
                */

                'account_prefix' => '',
```

I was using 'account_prefix' => 'ACME', and this is the reason it was not authenticating, when I removed the account prefix I am able to login to AD with just the username fine.

Thanks for the help!

**Comment by stevebauman** [comment]
Great to hear you've resolved it, no problem!
