### ISSUE TITLE
Adldap::auth works, Auth::attempt doesn't.

### ISSUE THREAD

**Issue by etern4ever** [Adldap2/Adldap2-Laravel#156]
I am sure I just have something configured wrong, but I can't figure it out.  

So when I use Adldap::auth()->attempt('username', 'password'), it returns true.  Using the incorrect password returns false.

But when I use Auth::attempt(['username' => 'username', 'password' => 'password']), I get the following error.

PHP warning:  ldap_search(): Search: No such object in Project/vendor/adldap2/adldap2/src/Connections/Ldap.php on line 221
PHP warning:  ldap_get_entries() expects parameter 2 to be resource, boolean given in Project/vendor/adldap2/adldap2/src/Connections/Ldap.php on line 113

As far as I can tell, I have all the auth provider elements in place.

Local accounts all still work but when used via tinker, I see the above warnings every time.  No LDAP accounts work.

**Comment by stevebauman** [comment]
Does `Auth::attempt()` work fine inside your application rather than inside `php artisan tinker`?

**Comment by etern4ever** [comment]
Auth using ldap creds wasn't working in my application after installing adldap2.   I started troubleshooting with tinker to determine the problem.  

If I throw Auth::attempt in my routes.php, it only works for local creds. (because I have the local fallback enabled).

**Comment by stevebauman** [comment]
Hmm okay... Are you able to post the entire stack trace of the error?

**Comment by etern4ever** [comment]
Here is a wtf from tinker after the command fails.


> [Psy\Exception\ErrorException]
>   PHP warning:  ldap_get_entries() expects parameter 2 to be resource, boolean given in Project/vendor/adldap2/adldap2/src/Connections/Ldap.php on line 1
>   13
> 
> Exception trace:
>  () at Project/vendor/adldap2/adldap2/src/Connections/Ldap.php:113
>  Psy\Shell->handleError() at n/a:n/a
>  ldap_get_entries() at Project/vendor/adldap2/adldap2/src/Connections/Ldap.php:113
>  Adldap\Connections\Ldap->getEntries() at Project/vendor/adldap2/adldap2/src/Query/Processor.php:54
>  Adldap\Query\Processor->process() at n/a:n/a
>  call_user_func_array() at Project/vendor/adldap2/adldap2/src/Query/Builder.php:1185
>  Adldap\Query\Builder->__call() at Project/vendor/adldap2/adldap2/src/Query/Builder.php:291
>  Adldap\Query\Builder->query() at Project/vendor/adldap2/adldap2/src/Query/Builder.php:200
>  Adldap\Query\Builder->get() at Project/vendor/adldap2/adldap2/src/Query/Builder.php:350
>  Adldap\Query\Builder->first() at Project/vendor/adldap2/adldap2-laravel/src/AdldapAuthUserProvider.php:189
>  Adldap\Laravel\AdldapAuthUserProvider->authenticateWithCredentials() at Project/vendor/adldap2/adldap2-laravel/src/AdldapAuthUserProvider.php:48
>  Adldap\Laravel\AdldapAuthUserProvider->retrieveByCredentials() at Project/vendor/laravel/framework/src/Illuminate/Auth/SessionGuard.php:353
>  Illuminate\Auth\SessionGuard->attempt() at n/a:n/a
>  call_user_func_array() at Project/vendor/laravel/framework/src/Illuminate/Auth/AuthManager.php:292
>  Illuminate\Auth\AuthManager->__call() at Project/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:217
>  Illuminate\Support\Facades\Facade::__callStatic() at Project/vendor/psy/psysh/src/Psy/ExecutionLoop/Loop.php(79) : eval()'d code:1
>  eval() at Project/vendor/psy/psysh/src/Psy/ExecutionLoop/Loop.php:79
>  Psy\ExecutionLoop\{closure}() at Project/vendor/psy/psysh/src/Psy/ExecutionLoop/Loop.php:135
>  Psy\ExecutionLoop\Loop->run() at Project/vendor/psy/psysh/src/Psy/ExecutionLoop/ForkingLoop.php:79
>  Psy\ExecutionLoop\ForkingLoop->run() at Project/vendor/psy/psysh/src/Psy/Shell.php:307
>  Psy\Shell->doRun() at Project/vendor/symfony/console/Application.php:117
>  Symfony\Component\Console\Application->run() at Project/vendor/psy/psysh/src/Psy/Shell.php:273
>  Psy\Shell->run() at Project/vendor/laravel/framework/src/Illuminate/Foundation/Console/TinkerCommand.php:54
>  Illuminate\Foundation\Console\TinkerCommand->fire() at n/a:n/a
>

**Comment by stevebauman** [comment]
It seems that tinker is strange when it comes to keeping the LDAP connection persistent. I'm encountering issues on my end where the `Auth::attempt()` returns true for the first request for an LDAP account, then returns false and displays a bind error on the second request.

I'm not sure whether or not this is a tinker issue (as it may be a limitation). We should troubleshoot your actual application authentication first.

**Comment by etern4ever** [comment]
Gotcha.. ok..

In the browser, I am not getting a stack dump or error.  I just get pushed back to the login screen.

In route.php, when I use:    dd(Adldap::auth()->attempt('username', 'password'));
It returns true.

When I use:    dd(Auth::attempt(['username' => 'username', 'password' => 'password']));
It returns false (using the same username/password as the Adldap auth request).

No errors, etc.  Where do we go next?

**Comment by stevebauman** [comment]
Ok, since you're using a `username` instead of the default `email`, did you change your users migration to use a username field instead of email? Also, can you post your `AuthController.php` as well as your `resources/views/auth/login.blade.php`?

**Comment by etern4ever** [comment]
I switched email to username before trying to use Adlap2 and that was working fine with the local accounts.  It still works fine for local accounts.  See below.  I haven't adjusted the validation and creation pieces because I do not plan to use user registrations.

AuthController.php
```
<?php

namespace App\Http\Controllers\Auth;

use App\User;
use Validator;
use App\Http\Controllers\Controller;
use Illuminate\Foundation\Auth\ThrottlesLogins;
use Illuminate\Foundation\Auth\AuthenticatesAndRegistersUsers;

class AuthController extends Controller
{
    /*
    |--------------------------------------------------------------------------
    | Registration & Login Controller
    |--------------------------------------------------------------------------
    |
    | This controller handles the registration of new users, as well as the
    | authentication of existing users. By default, this controller uses
    | a simple trait to add these behaviors. Why don't you explore it?
    |
    */

    use AuthenticatesAndRegistersUsers, ThrottlesLogins;

    /**
     * Where to redirect users after login / registration.
     *
     * @var string
     */
    protected $redirectTo = '/';


    # Use username
    protected $username = 'username';

    /**
     * Create a new authentication controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware($this->guestMiddleware(), ['except' => 'logout']);
    }

    /**
     * Get a validator for an incoming registration request.
     *
     * @param  array  $data
     * @return \Illuminate\Contracts\Validation\Validator
     */
    protected function validator(array $data)
    {
        return Validator::make($data, [
            'name' => 'required|max:255',
            'email' => 'required|email|max:255|unique:users',
            'password' => 'required|min:6|confirmed',
        ]);
    }

    /**
     * Create a new user instance after a valid registration.
     *
     * @param  array  $data
     * @return User
     */
    protected function create(array $data)
    {
        return User::create([
            'name' => $data['name'],
            'email' => $data['email'],
            'password' => bcrypt($data['password']),
        ]);
    }
}
```

login.blade.php

```
                        <form role="form" method="POST" action="{{ url('/login') }}">

                            {{ csrf_field() }}

                            <fieldset>
                                <div class="form-group">
                                    <input class="form-control" placeholder="Username" id="username" name="username" type="text" value="{{ old('username') }}" autofocus>
                                </div>
                                <div class="form-group">
                                    <input class="form-control" placeholder="Password" name="password" type="password" value="">
                                </div>
                                <div class="checkbox">
                                    <label>
                                        <input name="remember" type="checkbox" value="Remember Me">Remember Me
                                    </label>
                                </div>
                                <!-- Change this to a button or input when using this as a form -->
                                <button type="submit" class="btn btn-lg btn-success btn-block">
                                    Login
                                </button>
                            </fieldset>
                        </form>
```

**Comment by etern4ever** [comment]
I created a new app (laravel new ldap-test) with just adldap2 installed with same configuration (leaving login to email through).  I am having the same issue.   I even attempted to use full domain admin creds, but that didn't work.

I tried to do a user import and got error "ldap_search(): Search: Operations error".  This is going against a 2012 R2 server.

It all appears to be around the search function.  It's probably something dumb in my configuration.  I will keep digging when I get time.

**Comment by etern4ever** [comment]
I got it..  

Through some searching for "ldap_search(): Search: Operations error", I found that someone suggested to set "ldap_set_option($connection, LDAP_OPT_REFERRALS, 0);"

Looking through the config/code, I set follow_referrals to false and this resolved my issues.

Thanks.

**Comment by stevebauman** [comment]
Great! Glad to see it's resolved. Thanks for the update.
