### ISSUE TITLE
Can auth but not login.

### ISSUE THREAD

**Issue by warlord0** [Adldap2/Adldap2-Laravel#159]
I've been pulling my hair out on this and can't figure out what's wrong.

I'm using a Synology diskstation as my LDAP server when I'm developing at home. Don't want to connect to the work domain just for development.

I setup things as I thought I should and try as I might I can't get the logon form to log me in.

If I use:
```php
dd(\Adldap::auth()->attempt('test', 'secret'));
```
Boom it returns `true`

I've left the logon form fields as they are other than changed the type of email to text so it doesn't pattern validate it.

Added into LoginController.php:
```php
    protected $username = 'email';
```

adldap.php:
```php
                'schema' => Adldap\Schemas\OpenLDAP::class,
                'account_prefix' => 'uid=',
                'account_suffix' => ',cn=users,dc=diskstation,dc=local',
                'base_dn' => 'dc=diskstation,dc=local',
                'username_attribute' => ['email' => 'dn'],
                //'login_attribute' => 'email',
                'login_attribute' => env('ADLDAP_LOGON_ATTRIBUTE', 'uid'),
                'login_fallback' => false,
                'limitation_filter' => env('ADLDAP_LIMITATION_FILTER', ''),
```

auth.php:
```php
    'guards' => [
        'web' => [
            'driver' => 'session',
            'provider' => 'adldap',
        ],

        'api' => [
            'driver' => 'token',
            'provider' => 'users',
        ],
    ],
...
    'providers' => [
        'adldap' => [
            'driver' => 'adldap',
            'model' => ServiceManager\User::class,
        ],
        'users' => [
            'driver' => 'eloquent',
            'model' => ServiceManager\User::class,
        ],
...
```

**Comment by stevebauman** [comment]
Hi @warlord0,

Do you get any exceptions after logging in? Or are you just returned to the login form with an error message saying 'Invalid credentials'?

**Comment by warlord0** [comment]
Just returned with "invalid credentials".

**Comment by stevebauman** [comment]
Are you sure your user is located in the `users` OU specified in your configuration for account suffix: `cn=users,dc=diskstation,dc=local`?

Also, since you're binding fine, try searching for the user manually and see if it's returned:

```php
dd(\Adldap::search()->find('jdoe'));
``

**Comment by warlord0** [comment]
I'm 100% on the prefix and suffix as I've tested the auth using Apache Directory Studio.

As to the binding well I notice I've missed out the admin part:
``php
'admin_username' => env('ADLDAP_ADMIN_USERNAME', null), 
'admin_password' => env('ADLDAP_ADMIN_PASSWORD', null),),
```
But getting this detail I've also just spotted these in the `adldap_auth.php` file
```php
'login_attribute' => env('ADLDAP_LOGIN_ATTRIBUTE', 'samaccountname'),
'windows_auth_attribute' => ['samaccountname' => 'AUTH_USER'],
```
So I'm thinking in my case these should be set to 'dn'
