### ISSUE TITLE
Login Fallback doesn't work

### ISSUE THREAD

**Issue by Thaars** [Adldap2/Adldap2-Laravel#160]
Hi,

I've set the login_fallback to true, but when I try to login via username and password, I've got this Exception:

BindException in Guard.php line 86:
Can't contact LDAP server 

The doc says, this option would be handy in local development environments where an AD server may be unavailable. What's wrong here?

**Comment by stevebauman** [comment]
I believe you have to catch the bind exception in this use case:


```php
public function login(Request $request)
{
    try {
        if (Auth::attempt($request->all())) {
            //
        }
    } catch (\Adldap\Exceptions\BindException $e) {
        //
    }
}
```

**Comment by warlord0** [comment]
I've found that fallback does work... but not in the way you mean.

If I use a local database user (non-AD user) it will let me logon using the local credentials. But when the ldap server isn't there, boom you can't use a local user :(

Would be quite a handy feature - based on @stevebauman response I'm looking to tweak the login controller so it tries to find out if the ldap server is alive and if not, revert to another auth provider.

**Comment by warlord0** [comment]
```php
    public function login(Request $request)
    {
        try
        {
            if(\Auth::attempt($request->all()))
            {
                parent::login($request);
            }
        }
        catch (\Adldap\Exceptions\Auth\BindException $e) // <-- The correct exception to catch
        {
            /* Now for the hard bit :) */
        }
    }
```

**Comment by stevebauman** [comment]
Fixed, thanks!

> Would be quite a handy feature - based on @stevebauman response I'm looking to tweak the login controller so it tries to find out if the ldap server is alive and if not, revert to another auth provider.

This is exactly the use case of the bind exception. However, the fallback does already use the `EloquentUserProvider` for fallback.
