### ISSUE TITLE
Is there a way to not import some users from AD based on some conditions in LdapAttributeHandler?

### ISSUE THREAD

**Issue by ovidiubadita** [Adldap2/Adldap2-Laravel#161]
I want to add additional fields in my user table, and from what I read, I can use the LdapAttributeHandler to add any new fields. But is there a way to drop a record from being imported if it fails some validation?

**Comment by stevebauman** [comment]
Unfortunately the only validation you can have is inserting a raw filter into the command:

```php
// In this case, only users that contain an email address and IP phone will be imported.
php artisan adldap:import --filter="(&(mail=*)(ipphone=*))"
```

You would insert this filter into your `config/adldap_auth.php` file in the `limitation_filter` option to have the same effect for users logging in.

Also to clarify adding new fields, you can just add the field into your `sync_attributes` config option and it will be synchronized onto your model automatically. An LdapAttributeHandler doesn't **need** to be created for attributes that don't require any logic to parse.

**Comment by stevebauman** [comment]
There are *before* and *after* methods I've added to the `AdldapAuthUserProvider` to be able to perform tasks on the discovered LDAP user, but these don't allow you to bail out of the authentication:

https://github.com/Adldap2/Adldap2-Laravel/blob/master/src/AdldapAuthUserProvider.php#L115

https://github.com/Adldap2/Adldap2-Laravel/blob/master/src/AdldapAuthUserProvider.php#L103

I actually may add this type of functionality into the method `handleDiscoveredUserWithCredentials(User $user)`, and if false is returned, bail out of the authentication returning false. What do you think?

**Comment by ovidiubadita** [comment]
Thank you for clarification.  
Also, I added the line
`    'limitation_filter' => env('ADLDAP_LIMITATION_FILTER', '(mail=*)'),
`
however, it still brings the users that do not have email. I made the email not null in database, and the insert would fail, but it tries to insert them and pulls from AD lots of users with no email.

**Comment by stevebauman** [comment]
Are you using the import command? If so, you need to specify the filter every time. It doesn't pull the filter from your configuration.

**Comment by ovidiubadita** [comment]
The functionality with `handleDiscoveredUserWithCredentials` would be great, because I could hook into the Eloquent model and pull from database additional data that I need to validate against. For now, all I need is to add a UUID for users that do not have one in my database. But I expect I will need to make additional validations in time, as I expect this project to become large. I will need to look more closely at that method.

**Comment by ovidiubadita** [comment]
I was using the import command. I expected it to use the config filter. I will use it in the command line from now on. Thank you for advice. Is much appreciated.

**Comment by stevebauman** [comment]
Woops - reopening. Going to patch this.

The import command will now use the configured limitation filter.

Thanks!
