### ISSUE TITLE
Unable to login with Auth::attempt($credentials)

### ISSUE THREAD

**Issue by ArabAgile** [Adldap2/Adldap2-Laravel#162]
Where
`$credentials = ['username' => 'user', 'password' => 'password']`

When calling
`Auth::attempt($credentials)`

It returns **false** always.  (The user credentials were incorrect.)

But when calling
```
if (Adldap::auth()->attempt($credentials)) {
        return 'SUCCESS';
}
```

it success when the password is correct, and failed when the password is wrong. Which is the expected result. (I'm assuming no issue with the connection)

Now What I have is fresh installation of Laravel 5.2.45, and beside LDAP configurations I did this change in App/User.php file

```
class User extends Authenticatable
{
    use AdldapUserModelTrait; // THIS IS THE ONLY CHANGE
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        '',
//        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}
```

and I did this is app/auth.php

```
'providers' => [
        'users' => [
            'driver' => 'adldap', // was eloquent
            'model' => App\User::class,
        ],
    ],
```

Why Auth::attempt($credentials) and Auth::once($credentials) returns false?

Regards,
Agile

**Comment by warlord0** [comment]
Do you have the ldap auth service provider in your app config? And do you have the provider set to adldap?

It would seem to me that you're calling Auth and it does the eloquent database auth, but calling Adldap call it's calling the specific ldap auth and working.

**Comment by ArabAgile** [comment]
@warlord0 Yes I'm using
```
'providers' => [
        'users' => [
            'driver' => 'adldap', // 'eloquent',
            'model' => App\User::class,
        ],
]
```

**Comment by warlord0** [comment]
Both providers and fascade in `app.config`?
```php
        Adldap\Laravel\AdldapServiceProvider::class,
        Adldap\Laravel\AdldapAuthServiceProvider::class,

        'Adldap' => Adldap\Laravel\Facades\Adldap::class
```
I know this is still causing me some headaches, so just making sure you're at least where I am :) I can at least authenticate.

I went with a separate provider in `auth.php` to leave `users` alone.
```php
    'guards' => [
        'web' => [
            'driver' => 'session',
            'provider' => 'adldap',
        ],
...
    'providers' => [
        'users' => [
            'driver' => 'eloquent',
            'model' => App\User::class,
        ],
        
        'adldap' => [
            'driver' => 'adldap',
            'model' => App\User::class,
        ],
```

and my `User.php`
```php
<?php

namespace App;

use Adldap\Laravel\Traits\AdldapUserModelTrait;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use AdldapUserModelTrait;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'username',
    ];
...
```

**Comment by ArabAgile** [comment]
@warlord0 Yes both providers in app.config, and tried the separated provider. But the result is the same.

And added use AdldapUserModelTrait; in User.php file as in the documentation.  But unfortunately nothing changed.

I noticed some strange behaviour, which is the result will be the same wether I added the values in 'base_dn' or keep it as empty string! So base_dn seems to be useless in some steps!

I thought it's cached, so I did cache:clear but nothing changed also. Then tried to cache the config `php artisan config:cache` but nothing changed!

`Adldap::auth()->attempt('user', 'pwd') // Success`
`Auth::once($credentials) // Failed!` 

That's why I posted the issue here. 

I guessed Auth is not considering the adldap, but when tried 'adldap2' it returns error, which means

**Comment by stevebauman** [comment]
Hi @ArabAgile, apologies for the long response on this issue. Also, thank you @warlord0 for helping, appreciate it!

>  So base_dn seems to be useless in some steps!

The base DN is only used for performing searches on active directory. It's mandatory that the correct base DN is given, otherwise you won't receive anything from your server, or receive errors.

> And added use AdldapUserModelTrait; in User.php file as in the documentation. But unfortunately nothing changed.

The `AdldapUserModelTrait` is only utilized with the configuration option `bind_user_to_model`, which isn't mandatory. You can remove this from your user model.

What you can do, is go into the actual Adldap2-Laravel code, and try dumping the search results to see if anything is returned.

Right after line 189 here:

https://github.com/Adldap2/Adldap2-Laravel/blob/master/src/AdldapAuthUserProvider.php#L187-L189

Add: `dd($user);`, save the file, and then try logging into your web application. You should be able to see the returned result of the search.

This file should be located at `my-app/vendor/adldap2/adldap2-laravel/src/AdldapAuthUserProvider.php`.

**Comment by stevebauman** [comment]
Also, are you using OpenLDAP or ActiveDirectory?

**Comment by ArabAgile** [comment]
Thanks @stevebauman for your help. Actually I was wondering from where to start debugging.

My issue is fixed thanks. It seems because of I'm passing extra values in base_dn. Another issue with another project is I noticed that I'm using login by email not by username for ActiveDirectory login, so I changed it to username.

**Comment by jjsquad** [comment]
What was a solution for this @ArabAgile ? Can explain it? I have it same issue here :(

Thanks

**Comment by ArabAgile** [comment]
@jjsquad Make sure you're using the adladp as driver for App\User::class.
```
'guards' => [
        'web' => [
            'driver' => 'session',
            'provider' => 'adldap',
        ],
...
    'providers' => [
        'users' => [
            'driver' => 'eloquent',
            'model' => App\User::class,
        ],

        'adldap' => [
            'driver' => 'adldap',
            'model' => App\User::class,
        ],
```

That's it. But make sure you entered the correct credentials for the server you're connecting to.

make sure to set user attribute properly weather it's samaccountname or email
`'username_attribute' => ['username' => 'samaccountname'],`

**Comment by MoiseScalzo** [comment]
Hi @stevebauman ,
I have the same issue but I'm in a NoDatabaseUserProvider environment, with file session.
``$credentials = ['email' => 'email@address.com', 'password' => 'myaccountpassword']``

This return **false**:
`Auth::attempt($credentials)`
but this return **true**:
`Adldap::auth()->attempt($credentials)`

How can I login in the user in my application?
thank you

**Comment by stevebauman** [comment]
Hi @MoiseScalzo, please create your own issue and I can assist you there. Thanks!

**Comment by MoiseScalzo** [comment]
Hi @stevebauman , done here: https://github.com/Adldap2/Adldap2-Laravel/issues/664 thank you very much for your help.
