### ISSUE TITLE
Domain Trusts

### ISSUE THREAD

**Issue by randyrankin** [Adldap2/Adldap2-Laravel#165]
Is it possible to auth users from a trusted domain? I've set up a group containing members from local domain and trusted domain and auth works perfect (using group middleware) for users on the local domain, but users on trusted domain are not auth'ed.

**Comment by warlord0** [comment]
Not sure about that, but as it's ldap it may be using a referral.

```php
'follow_referrals' => false, // <-- change to true
```

**Comment by randyrankin** [comment]
Hmm. That seems logical, but setting `'follow_referrals' => true'` breaks my local domain auth.

**Comment by warlord0** [comment]
I'd have a poke around the ldap using Apache Directory Studio and see what it returns when you try to logon. I've found it pretty handy in anything ad/ldap related.
