### ISSUE TITLE
Laravel 5.3

### ISSUE THREAD

**Issue by warlord0** [Adldap2/Adldap2-Laravel#166]
After moving on to Laravel 5.3 I couldn't get Auth:: to work :(

After checking out the code it was ALWAYS passing `email` as the logon attribute in $credentials. I double checked

My login controller:
```php
protected $username = 'username'; // <-- This is wrong for 5.3
```

I figured out that now it need to be:
```php
public function username()
{
    return 'username';
}
```
And now it works again.

**Comment by stevebauman** [comment]
Fixed, thanks!
