### ISSUE TITLE
Cannot authenticate with dn as adldap_auth.login_attribute

### ISSUE THREAD

**Issue by wunc** [Adldap2/Adldap2-Laravel#167]
I just updated this package from v2.0.14 to v2.1.1, and my auth broke. My LDAP server takes the user dn as the username when authenticating. When setting `'login_attribute' => 'dn'` in adldap_auth.php, authentication now fails due to a null username.

I think this is because the dn was moved from an attribute to a protected property in https://github.com/Adldap2/Adldap2/commit/e1ae5393c7ed725fc8d2a72e86601ba6909ec69d. As a result, Traits/ImportsUsers@getUsernameFromAdUser() cannot access the dn as an attribute.

A simple fix would be to add a special check for 'dn' as login_attribute:

```php
protected function getUsernameFromAdUser(User $user)
{
    $login_attribute = $this->getLoginAttribute();
    $username = ($login_attribute === 'dn') ? $user->getDn() : $user->{$login_attribute};

    if (is_array($username)) {
        // We'll make sure we retrieve the users first username
        // attribute if it's contained in an array.
        $username = Arr::get($username, 0);
    }

    return $username;
}
```

but I'm not sure if that's the best way.

My own temporary workaround for now was to add `"adldap2/adldap2": "6.1.1"` to my composer file, because the breaking change happened in v6.1.2.

**Comment by stevebauman** [comment]
Hi @wunc, try using the attribute 'distinguishedname' instead and let me know the result.

**Comment by wunc** [comment]
`$user->distinguishedname` is null.

If I `dd($user)`, `distinguishedname` is not listed as one of the attributes. Browsing the server with Apache Directory Studio does not show it as a visible attribute, either.

**Comment by stevebauman** [comment]
Thanks for the report!

This has just been fixed: https://github.com/Adldap2/Adldap2/commit/fc1efb21756447d0ddd7375331ac74ff63252c34

A new release will be out shortly.

I'm not sure why my thought process was to remove the 'dn' attribute from models, but this was an unintended BC break.

**Comment by stevebauman** [comment]
Yup, that fix should still be in-tact. As long as developers aren't setting a new DN as an attribute with `setAttribute('dn', '...');` then everything will be working as intended.

The `setDn()` method used to rely on the models `$attributes` property which was unpredictable on occasions (being stored as an array / string).
