### ISSUE TITLE
Password mutator and hardcoded bcrypt function

### ISSUE THREAD

**Issue by tortuetorche** [Adldap2/Adldap2-laravel#17]
Hi folks,

When I try to login, there is always a `These credentials do not match our records.` error.

Because, in my `app\User.php` file, I've a password [mutator](http://laravel.com/docs/5.1/eloquent-mutators#accessors-and-mutators) to bcrypt a `password` parameter.
```php
//...
class User extends Model
{
    //...
    /**
     * Hash the password given
     *
     * @param string $password
     */
    public function setPasswordAttribute($password)
    {
        $this->attributes['password'] = bcrypt($password);
    }
}
```

So I can do:
```php
$u = App\User::create(['name' => 'Foo', 'email' => 'foo@bar.com', 'password' => 'secret']);
$u->password; // returns a Bcrypt hash
=> "$2y$10$.vGA1O9wmRjrwAVXD98HNOgsNpDczlqm3Jq7KnEd1rVAGv3Fykk1a"
```

But `Adldap2-laravel` always insert the `password` attribute value, into the `User` model, as a `bcrypt` hash.
Here the code, where `bcrypt` function is used:
https://github.com/Adldap2/Adldap2-laravel/blob/c7b12085b309928a827d17f2d5a9a7967fa03dbc/src/AdldapAuthUserProvider.php#L109

So maybe, we can extract this line in an `update()` method, to be able to override or aliasing it?
Then my password mutator would be happy :smirk_cat:

Cheers,
Tortue Torche

**Comment by tortuetorche** [comment]
Something like that: 
```php
class AdldapAuthUserProvider extends EloquentUserProvider
{
    //...

    /**
     * Update user credential attributes
     * @param Authenticatable $model
     * @param string $username
     * @param string $password
     * @return Authenticatable
     */
    protected function syncCredentials($model, $username, $password)
    {
        $key = $this->getUsernameKey();
        // Set the username and password in case
        // of changes in active directory
        $model->{$key} = $username;
        $model->password = bcrypt($password);

        return $model;
    }

    /**
     * @return string
     */
    protected function getUsernameKey()
    {
        $attributes = $this->getUsernameAttribute();
        // Get the model key
       return key($attributes);
    }
}
```

**Comment by tortuetorche** [comment]
Or just for password:
```php
class AdldapAuthUserProvider extends EloquentUserProvider
{
    //...

    /**
     * Update user password attribute
     *
     * @param  Authenticatable $model
     * @param  string $password
     * @return Authenticatable
     */
    protected function syncPassword($model, $password)
    {
        // Set the password in case
        // of changes in active directory
        $model->password = bcrypt($password);

        return $model;
    }
}
```

**Comment by tortuetorche** [comment]
I think It'll be also useful if we don't want to store the real password in the database, even if it's hashed.
And if we use a different strategy to hash password.

**Comment by stevebauman** [comment]
Apologies for long response on this. I agree with this, but storing the actual password in the database allows users to log in if AD connectivity is lost. I'll add a separate method for setting the password so it can be overridden for this use case.

**Comment by stevebauman** [comment]
Added `syncModelPassword()` method: https://github.com/Adldap2/Adldap2-laravel/commit/f7dcad79762deb74586ecf96cc4e338bc190eb82

Will be in new release shortly.

**Comment by stevebauman** [comment]
Also just added a check for the `setPasswordAttribute()` mutator so you're able to use your own encryption methods: https://github.com/Adldap2/Adldap2-laravel/commit/520587d8b654afcd01688f81492026fdc13d50d5

**Comment by tortuetorche** [comment]
@stevebauman Many thanks :smile_cat:! I'll try these new features ASAP.

**Comment by tortuetorche** [comment]
@stevebauman It works fine now :+1: 

Have a good day,
Tortue Torche
