### ISSUE TITLE
One user can't logon!

### ISSUE THREAD

**Issue by warlord0** [Adldap2/Adldap2-Laravel#171]
Very odd issue where I have one user who can't logon.

If I delete them from the user table it should get recreated, like any other user does. But it fails to logon and so doesn't create the user.

I added a Failed event and listener in app.php

added into $listen in EventServiceProviders.php
```php
        'Illuminate\Auth\Events\Failed' => [
            'App\Listeners\LogFailedAuthenticationAttempt',
        ],
```
Created LogFailedAuthenticationAttempt.php
```php
namespace App\Listeners;

use Illuminate\Auth\Events\Failed;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Contracts\Queue\ShouldQueue;

class LogFailedAuthenticationAttempt
{
    /**
     * Create the event listener.
     *
     * @return void
     */
    public function __construct()
    {
        //
    }

    /**
     * Handle the event.
     *
     * @param  Illuminate\Auth\Events\Failed  $event
     * @return void
     */
    public function handle(Failed $event)
    {
        dd($event);

    }
}
```
An sure enough I get to the `dd($event)` and see the users model if I create them manually, so the username is being found in the model. I even changed the password to something I know so I could poke it some, knowing I'm not mistyping the password.

So it's definitely failing. But I can't figure out where to debug it at what stage.

If I drop in a `dd(\Adldap::auth()->attempt($event->credentials['username'], $event->credentials['password']));` in the failure handle I get `true` so the password is ok, the account isn't locked.

Any help appreciated.

**Comment by warlord0** [comment]
Ok, was just me being a dick :D

I wasn't even using adldap on the guard :o Just the user model, which of course synced user password, which is why some of us could logon, but those without user models couldn't or even create one. What a moose.

**Comment by stevebauman** [comment]
Haha no problem. Was about to reply to help troubleshoot.

Glad you've resolved the issue!
