### ISSUE TITLE
Implement events

### ISSUE THREAD

**Issue by stevebauman** [Adldap2/Adldap2-Laravel#172]
Implement events for:

- Authenticating via SSO
- Authenticating against LDAP

**Comment by warlord0** [comment]
Lol. Was this spurred by my previous post?

I think it's a great idea. (Y)

**Comment by stevebauman** [comment]
Haha indeed it was! Should be implemented shortly.

**Comment by stevebauman** [comment]
Added: https://github.com/Adldap2/Adldap2-Laravel/commit/7ad0bd2d80793147ff870131209712a1de11acb7
