### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by Edsardio** [Adldap2/Adldap2-Laravel#173]
I followed the quickstart for laravel, tried to implement it in 5.3.

When trying to login I always get the "These credentials do not match our records." message.
When trying to do an import on all the users I get this errorException

ldap_search(): Search: Operations error

Please help me :)

**Comment by Edsardio** [comment]
Found out the user I used didn't have search permissions.. Problem solved!

**Comment by stevebauman** [comment]
Glad you've solved your issue! Thanks for following up.
