### ISSUE TITLE
Class adldap does not exist

### ISSUE THREAD

**Issue by thuyhyvg** [Adldap2/Adldap2-Laravel#177]
Class adldap does not exist

**Comment by warlord0** [comment]
That has to be one of the vaguest issues ever.

Have you tried turning it off an on again? :D

That said the class is case sensitive as is Adldap depending how you use it you may have to refer to it as \Adldap

**Comment by thuyhyvg** [comment]
Hi, 
I have one error
BindException in Guard.php line 86:
Can't contact LDAP server

Can you help me?
thank you

**Comment by warlord0** [comment]
Have you properly completed the details in config\adldap.php for your domain controller etc?

```php
'domain_controllers' => ['myserver'],
'port' => 389,
```

You may want to try with just an IP address. Also is the port you are using correct?

**Comment by thuyhyvg** [comment]
I use localhost then what myserver ??

**Comment by thuyhyvg** [comment]
localhost or virtualhost

**Comment by warlord0** [comment]
You need to specify your Active Directory Domain Controller

**Comment by stevebauman** [comment]
Closing due to no information about the issue as well as no LDAP server knowledge.
