### ISSUE TITLE
use both database and adldap for auth

### ISSUE THREAD

**Issue by timothyrowan** [Adldap2/Adldap2-laravel#18]
i will have some users authing against the db and some authing against the active directory.
i've accomplished this with the standard laravel auth controller and the Adldap::authenticate() method and some duct tape.

just wondering if there is an easier/more seamless way

thanks, i love this

**Comment by stevebauman** [comment]
This already occurs with the Adldap laravel Auth driver, it creates a local database record of an authenticated LDAP user. If you're looking to use the eloquent auth driver along side the Adldap auth driver, you'll need to switch your selected auth driver on the fly using `Config::set('auth.driver', 'eloquent');`.

**Comment by timothyrowan** [comment]
you're awesome, thanks

**Comment by stevebauman** [comment]
No problem! Any other concerns / questions please don't hesitate to create an issue.

**Comment by modbase** [comment]
The Auth driver indeed creates a local database record and syncs the password, but if the Domain Controller is not available, I expect the login still succeeds if the password matches the one in the database.

For local development, I don't have a domain controller available, so authentication always fails when the adldap auth driver is used.

**Comment by stevebauman** [comment]
@modbase I agree that this should be a configurable option. I'll be implementing this on the Laravel repo.
