### ISSUE TITLE
Adldap not authenticating with username and password password from form

### ISSUE THREAD

**Issue by kelvinrolex** [Adldap2/Adldap2-Laravel#180]
Hello and Good  day,

Been trying to implement this, but I noticed that when i use
Auth::attempt(['username' => $username, 'password' => $password]) it will return true even if the password is not correct, but after much debugging i found out that it uses the 'admin_username' and 'admin_password' set in the adldap.php file in the config directory to authenticate and then search for the username passed from the form, when it sees the username it will return true but if i put a wrong username it will return false, my issue here is it is suppose to use both username and password fields to authenticate the user but now its just doing search with the username. Please is there something am doing wrong?

**Comment by stevebauman** [comment]
Hi @kelvinrolex, what version are you on? This is definitely not the case.

You have half the process right. Credentials are used before hand to authenticate to your AD server, a search is performed to find the user on your AD server that is trying to authenticate, then when a user is found, a new authentication request is sent to your AD server with the users credentials.

The result of the users binding is returned, and that determines if the user is authenticated or not.

I need more details, such as your `config/adldap_auth.php` file, your `AuthController` as well as your HTML form for further debugging.

**Comment by kelvinrolex** [comment]
config/adldap.php

<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Connections
    |--------------------------------------------------------------------------
    |
    | This array stores the connections that are added to Adldap. You can add
    | as many connections as you like.
    |
    | The key is the name of the connection you wish to use and the value is
    | an array of configuration settings.
    |
    */

    'connections' => [

        'default' => [

            /*
            |--------------------------------------------------------------------------
            | Auto Connect
            |--------------------------------------------------------------------------
            |
            | If auto connect is true, anytime Adldap is instantiated it will automatically
            | connect to your AD server. If this is set to false, you must connect manually
            | using: Adldap::connect().
            |
            */

            'auto_connect' => true,

            /*
            |--------------------------------------------------------------------------
            | Connection
            |--------------------------------------------------------------------------
            |
            | The connection class to use to run operations on.
            |
            | You can also set this option to `null` to use the default connection class.
            |
            | Custom connection classes must implement \Adldap\Contracts\Connections\ConnectionInterface
            |
            */

            'connection' => Adldap\Connections\Ldap::class,

            /*
            |--------------------------------------------------------------------------
            | Schema
            |--------------------------------------------------------------------------
            |
            | The schema class to use for retrieving attributes and generating models.
            |
            | You can also set this option to `null` to use the default schema class.
            |
            | Custom schema classes must implement \Adldap\Contracts\Schemas\SchemaInterface
            |
            */

            'schema' => Adldap\Schemas\ActiveDirectory::class,

            /*
            |--------------------------------------------------------------------------
            | Connection Settings
            |--------------------------------------------------------------------------
            |
            | This connection settings array is directly passed into the Adldap constructor.
            |
            | Feel free to add or remove settings you don't need.
            |
            */

            'connection_settings' => [

                /*
                |--------------------------------------------------------------------------
                | Account Prefix
                |--------------------------------------------------------------------------
                |
                | The account prefix option is the prefix of your user accounts in AD.
                |
                | For example, if you'd prefer your users to use only their username instead
                | of specifying a domain ('ACME\jdoe'), enter your domain name.
                |
                */

                'account_prefix' => '',

                /*
                |--------------------------------------------------------------------------
                | Account Suffix
                |--------------------------------------------------------------------------
                |
                | The account suffix option is the suffix of your user accounts in AD.
                |
                | For example, if your domain DN is DC=corp,DC=acme,DC=org, then your
                | account suffix would be @corp.acme.org. This is then appended to
                | then end of your user accounts on authentication.
                |
                */

                'account_suffix' => env('ACCOUNT_SUFFIX'),

                /*
                |--------------------------------------------------------------------------
                | Domain Controllers
                |--------------------------------------------------------------------------
                |
                | The domain controllers option is an array of servers located on your
                | network that serve Active Directory. You can insert as many servers or
                | as little as you'd like depending on your forest (with the
                | minimum of one of course).
                |
                */

                'domain_controllers' => [env('DOMAIN_CONTROLLERS')],

                /*
                |--------------------------------------------------------------------------
                | Port
                |--------------------------------------------------------------------------
                |
                | The port option is used for authenticating and binding to your AD server.
                |
                */

                'port' => env('AD_PORT'),

                /*
                |--------------------------------------------------------------------------
                | Base Distinguished Name
                |--------------------------------------------------------------------------
                |
                | The base distinguished name is the base distinguished name you'd like
                | to perform operations on. An example base DN would be DC=corp,DC=acme,DC=org.
                |
                | If one is not defined, then Adldap will try to find it automatically
                | by querying your server. It's recommended to include it to
                | limit queries executed per request.
                |
                */

                'base_dn' => env('BASE_DN'),

                /*
                |--------------------------------------------------------------------------
                | Administrator Account Suffix
                |--------------------------------------------------------------------------
                |
                | This option allows you to set a different account suffix for your
                | configured administrator account upon binding.
                |
                | If left empty, your `account_suffix` option will be used.
                |
                */

                'admin_account_suffix' => env('ADMIN_ACCOUNT_SUFFIX'),

                /*
                |--------------------------------------------------------------------------
                | Administrator Username & Password
                |--------------------------------------------------------------------------
                |
                | When connecting to your AD server, an administrator username and
                | password is required to be able to query and run operations on
                | your server(s). You can use any user account that has
                | these permissions.
                |
                */

                'admin_username' => env('ADLDAP_ADMIN_USERNAME'),
                'admin_password' => env('ADLDAP_ADMIN_PASSWORD'),

                /*
                |--------------------------------------------------------------------------
                | Follow Referrals
                |--------------------------------------------------------------------------
                |
                | The follow referrals option is a boolean to tell active directory
                | to follow a referral to another server on your network if the
                | server queried knows the information your asking for exists,
                | but does not yet contain a copy of it locally.
                |
                | This option is defaulted to false.
                |
                */

                'follow_referrals' => false,

                /*
                |--------------------------------------------------------------------------
                | SSL & TLS
                |--------------------------------------------------------------------------
                |
                | If you need to be able to change user passwords on your server, then an
                | SSL or TLS connection is required. All other operations are allowed
                | on unsecured protocols. One of these options are definitely recommended
                | if you have the ability to connect to your server securely.
                |
                */

                'use_ssl' => false,
                'use_tls' => false,

            ],

        ],

    ],

];


AuthController

$username = $request->username;
$password = $request ->password;
if (Auth::attempt(['username' => $username, 'password' => $password])) {
           return $user = Auth::user();

            var_dump($user); // Returns instance of App\User;

            var_dump($user->adldapUser); // Returns instance of Adldap\Models\User;

            // Retrieving the authenticated LDAP users groups
          return  $groups = $user->adldapUser->getGroups();
        }else{
            return 'failed';
        }

HTML

<input id="username" type="text" name="username">
<input id="password" type="password" name="password" >

Am using Laravel 5.2 and I ran composer update today, so am sure I have the latest version of Adldap.
Thanks

**Comment by kelvinrolex** [comment]
HTML
`<div>
<input id="username" type="text" name="username">
<input id="password" type="password" name="password" >
</div>`

**Comment by stevebauman** [comment]
Ok great, can you also post your `config/adldap_auth.php` file?

**Comment by stevebauman** [comment]
Hmmm, everything looks fine. Strange.

So you can actually authenticate as any AD user using **any** password?

Can you also post your `config/auth.php` file as well?

**Comment by kelvinrolex** [comment]
config/auth.php

`<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Authentication Defaults
    |--------------------------------------------------------------------------
    |
    | This option controls the default authentication "guard" and password
    | reset options for your application. You may change these defaults
    | as required, but they're a perfect start for most applications.
    |
    */

    'defaults' => [
        'guard' => 'web',
        'passwords' => 'users',
    ],

    /*
    |--------------------------------------------------------------------------
    | Authentication Guards
    |--------------------------------------------------------------------------
    |
    | Next, you may define every authentication guard for your application.
    | Of course, a great default configuration has been defined for you
    | here which uses session storage and the Eloquent user provider.
    |
    | All authentication drivers have a user provider. This defines how the
    | users are actually retrieved out of your database or other storage
    | mechanisms used by this application to persist your user's data.
    |
    | Supported: "session", "token"
    |
    */

    'guards' => [
        'web' => [
            'driver' => 'session',
            'provider' => 'adldap',
        ],

        'api' => [
            'driver' => 'token',
            'provider' => 'users',
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | User Providers
    |--------------------------------------------------------------------------
    |
    | All authentication drivers have a user provider. This defines how the
    | users are actually retrieved out of your database or other storage
    | mechanisms used by this application to persist your user's data.
    |
    | If you have multiple user tables or models you may configure multiple
    | sources which represent each model / table. These sources may then
    | be assigned to any extra authentication guards you have defined.
    |
    | Supported: "database", "eloquent"
    |
    */

    'providers' => [
        'users' => [
            'driver' => 'adldap',
            'model' => App\Models\User::class,
        ],

        'adldap' => [
            'driver' => 'adldap',
            'model'  => App\Models\User::class,
        ],

         'users' => [
             'driver' => 'eloquent',
             'model'  => App\Models\User::class,
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Resetting Passwords
    |--------------------------------------------------------------------------
    |
    | Here you may set the options for resetting passwords including the view
    | that is your password reset e-mail. You may also set the name of the
    | table that maintains all of the reset tokens for your application.
    |
    | You may specify multiple password reset configurations if you have more
    | than one user table or model in the application and you want to have
    | separate password reset settings based on the specific user types.
    |
    | The expire time is the number of minutes that the reset token should be
    | considered valid. This security feature keeps tokens short-lived so
    | they have less time to be guessed. You may change this as needed.
    |
    */

    'passwords' => [
        'users' => [
            'provider' => 'users',
            'email' => 'auth.emails.password',
            'table' => 'password_resets',
            'expire' => 60,
        ],
    ],

];
`

**Comment by stevebauman** [comment]
Ok. So you can actually authenticate as any AD user using any password?

**Comment by kelvinrolex** [comment]
Ok lemme explain, the admin_username and admin_password in config/adldap.php file, if i change it to a wrong one, it will show me an error message saying adldap_search() error, but if i enter the correct username and password to an account in the LDAP Server it will work, then 

if (Auth::attempt(['username' => $username, 'password' => $password])) {
           return $user = Auth::user();

            var_dump($user); // Returns instance of App\User;

            var_dump($user->adldapUser); // Returns instance of Adldap\Models\User;

            // Retrieving the authenticated LDAP users groups
          return  $groups = $user->adldapUser->getGroups();
        }else{
            return 'failed';
        }

this line  `return $user = Auth::user();` will display the user information that is passed from the form even though the password in the form is wrong, that means its not authenticating using this line
`if (Auth::attempt(['username' => $username, 'password' => $password])) {`

But if you see nothing wrong with it, that means i will have to remove the package and reinstall it again because I last worked on this project about 3 months, i just decided to continue today and i ran composer update to update all the dependencies.

**Comment by stevebauman** [comment]
That's strange? Have you tried clearing your config's cache using `php artisan config:clear`? It's possible that you're not actually using the `adldap` driver if the configuration is cached.

**Comment by kelvinrolex** [comment]
I have cleared config's cache more than 20 times today, but i think when i get to work tomorrow i will reinstall it again and let you know the outcome.

**Comment by kelvinrolex** [comment]
Hello and good day @stevebauman,
Just reinstalled the package in my project and i followed the setup instructions and everything is now working well, i think the problem was when i did composer update at first the update didn't download the new settings, so after removing the package and reinstalling, some of the settings that where missing from the the previous one i was using. So thanks for your help, everything is now working as expected.

**Comment by kelvinrolex** [comment]
@stevebauman, it was working fine after setup, now after like 3hours later i tried logging in and am getting `UsernameRequiredException in Guard.php line 116:A username must be specified.`

I ahve attached the image of the error am getting.

I have tried everything but can't resolve it, do you have any idea on what i can do?
![image 2](https://cloud.githubusercontent.com/assets/10676937/18872640/7163a632-84b3-11e6-9c4b-438bc263a1ca.PNG)
![image 3](https://cloud.githubusercontent.com/assets/10676937/18872641/71683b02-84b3-11e6-85b7-8e3406f27380.PNG)
![image 4](https://cloud.githubusercontent.com/assets/10676937/18872642/716ef42e-84b3-11e6-8a92-7f21c68c6738.PNG)
![image1](https://cloud.githubusercontent.com/assets/10676937/18872643/7175079c-84b3-11e6-9999-1d6598c9b438.PNG)

**Comment by stevebauman** [comment]
There must be something wrong with your `adldap_auth.php` config. You're either specifying a username attribute that doesn't exist, or the attribute doesn't exist on the user you're authenticating.

See method `getUsernameFromAdUser`:

https://github.com/Adldap2/Adldap2-Laravel/blob/master/src/Traits/ImportsUsers.php#L247-L258

Called from `AuthenticateWithCredentials`:

https://github.com/Adldap2/Adldap2-Laravel/blob/master/src/AdldapAuthUserProvider.php#L195

Did you change anything in your configuration?

**Comment by stevebauman** [comment]
Also, does this user you're authenticating have a `samaccountname`?

**Comment by kelvinrolex** [comment]
Yes, the user has samaccountname, i just tried running php artisan adldap:import from the command line and it imported the user to my database that means it is working, its actually validating but not sending the username to the Guard.php file. Here is my Models/User.php file 

`<?php

namespace App\Models;
use Adldap\Laravel\Traits\AdldapUserModelTrait;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use AdldapUserModelTrait;
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $table = 'users';

    protected $fillable = [
        'name', 'first_name', 'last_name', 'email', 'password',
    ];
    public $timestamps = true;

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
    
}
`

**Comment by kelvinrolex** [comment]
Hello
Dunno if this is the problem, but i search for that vendor/adldap2/adldap2/src/Auth/Guard.php,  noticed that this line `public function attempt($username, $password, $bindAsUser = false)
    {
        $this->validateCredentials($username, $password);

        try {
            $this->bind($username, $password);
        } catch (BindException $e) {
            // We'll catch the BindException here to return false
            // to allow developers to use a simple if / else
            // using the authenticate method.
            return false;
        }

        // If we're not allowed to bind as the user,
        // we'll rebind as administrator.
        if ($bindAsUser === false) {
            // We won't catch any BindException here so
            // developers can catch rebind failures.
            $this->bindAsAdministrator();
        }

        // No bind exceptions, authentication passed.
        return true;
    } ` does get the $username, even when i use `public function attempt($username = 'student', $password, $bindAsUser = false)
    {
        $this->validateCredentials($username, $password);

        try {
            $this->bind($username, $password);
        } catch (BindException $e) {` i still get same error until i change it to `public function attempt($username, $password, $bindAsUser = false)
    {
        $username = 'student';
        $this->validateCredentials($username, $password);

        try {
            $this->bind($username, $password);
        } catch (BindException $e) {` and it works. So pls do you have any idea what is causing the $username variable not to have the data passed to it?

**Comment by JoshBargar** [comment]
Any update on this? I am having the exact same issue.

**Comment by stevebauman** [comment]
Hi @kelvinrolex,

After looking further, it looks like you have conflicting configurations here.

Your using a the HTML input name `username` which is mapped to the users `samaccountname` here:

```php
'username_attribute' => ['username' => 'samaccountname'],
```

Though, you don't have a `username` column in your `users` database table (shown by your `$fillable` fields - as well as your `sync_attributes` option):

```php
protected $fillable = [
    'name', 'first_name', 'last_name', 'email', 'password',
];
```

```php
'sync_attributes' => [

    'name' => 'cn',
    'email' => 'mail',
    'first_name' => 'givenname',
    'last_name' => 'sn',
    'description' => 'description',
    'user_group' => 'distinguishedname',
    'department' => 'physicaldeliveryofficename',
    'member_of'  =>  'memberof',

],
```

Change your `username_attribute` option to:

```php
'username_attribute' => ['email' => 'mail'],
```

And your `username` HTML input field on your login view to:

```html
<input type="text" name="email" />
```

If you're trying to get users to login with their `samaccountname`, you'll have to create a `username` column in your `users` database table, as described in the documentation:

https://github.com/Adldap2/Adldap2-Laravel#username-attributes

**Comment by kelvinrolex** [comment]
@stevebauman thanks for the response but I actually got it to work today just by changing  'login_attribute' => env('ADLDAP_LOGIN_ATTRIBUTE', 'samaccountname'), to 'login_attribute' => env('ADLDAP_LOGIN_ATTRIBUTE', 'cn'), in adldap_auth.php.

Thanks once again...

**Comment by stevebauman** [comment]
Great to hear! Thanks for following up.
