### ISSUE TITLE
adldap:import - soft delete disabled AD users?

### ISSUE THREAD

**Issue by eleftrik** [Adldap2/Adldap2-Laravel#183]
Hi, if I try to login with a disabled Active Directory user (I mean, disabled as a domain user), I correctly cannot authenticate in my login form.

At the moment, if I run `php artisan adldap:import`, disabled Active Directory do not get updated in the users table.

Additionally, When I run `php artisan adldap:import`, would it be possible to soft delete these kind of users? Possibly with a config option which allows to specify if we want to soft delete users or not (when running the command).

I mean:
- user j.doe, once enabled, gets disabled in Active Directory
- I run  `php artisan adldap:import`
- on my users table, user j.doe has been soft deleted

Thank you very much for your attention.

**Comment by stevebauman** [comment]
Hi @eleftrik,

This is a great suggestion, I'll definitely add a command option for this use case.

**Comment by eleftrik** [comment]
Thank you very much @stevebauman, I tried the `--delete=true` option and it worked as expected. Your work helped me a lot!
