### ISSUE TITLE
Generate events depending on authentication failure

### ISSUE THREAD

**Issue by stevebauman** [Adldap2/Adldap2-Laravel#184]
Events need to be fired depending on:

- If a user is soft deleted and they're trying to authenticate
- If a user is disabled / locked out of the AD account they're trying to authenticate

This is in reference to issue #181.

**Comment by eleftrik** [comment]
Hi @stevebauman, thank you for adding these events.
I can't figure out how I can take advantage of them in showing a different message (in the login form) to a disabled user who's trying to authenticate. Have you any suggestion?
Thank you

**Comment by Ranfty** [comment]
Hi @stevebauman, our AD has a policy where the users account is locked after 4 incorrect password attempts. If I attempt to log in to a locked account (`deleted_at` column in on my user model is null) I receive the session message:

`These credentials do not match our records.`

Where I would like to display a message similar to:

`Account locked. Contact IT to reset your password.`

The `AuthenticatedModelTrashed` event is only fired if the account isn't locked, the credentials of the user match and the `deleted_at` column on the user model is not null.

Any suggestions?

Thanks.
