### ISSUE TITLE
Login Limitation Filter for Specific Pages

### ISSUE THREAD

**Issue by annajeanine** [Adldap2/Adldap2-Laravel#186]
Hi!

I was wondering if it would be possible to specify login limitations for specific pages. I've managed to create a global login limitation filter in the `config/adldap_auth.php.` I've also managed to create a check for logged in users and guest. Like so:

 `@if (Auth::guest())`
                    `<div class="panel-heading">Welcome</div> `
                    `<div class="panel-body">`
                           ` <h class="lead"> You need to log in!</h><br><br>`
                            `<p>Please go to the <a href="{{ url('/login') }}">Login</a></li> page</p>`
                   ` </div>`
   `@else`
                    `<div class="panel-heading"> Welcome  {{ Auth::user()->name }}</div>`
                    `<div class="panel-body">`
                           `<h class="lead">You're logged in!</h><br><br>`
                    `</div>`
   `@endif`

Would it be possible to specify an array/string of groups, that are allowed to see a section of a specific page so others who are not authorized can still view the page but not all information? And if so, how would you specify this? 

Thank you!

**Comment by stevebauman** [comment]
Hi @annajeanine,

Unfortunately the limitation filter is only utilized during authentication. All the filter does is limit how the user is found in your active directory server, and if the user record is found, that means they are allowed to try and authenticate against your AD.

The only way you could perform this is by creating groups / permissions on your app locally to restrict access to certain places, or by using the Adldap configuration option `bind_user_to_model`: [Documentation](https://github.com/Adldap2/Adldap2-Laravel#binding-the-adldap-user-model-to-the-laravel-user-model)

Once you've configured the option, you could then perform authorization like so:

```php
@if (Auth::check())

    <p>You're logged in!</p>

    @if (Auth::user()->adldapUser->inGroup('Accounting'))

        <p>You're also in the accounting active directory group!</p>

    @endif

@else

    You're not logged in.

@endif
```

If the user isn't authenticated, there isn't really a way to perform authorization.

Hopefully I've answered your question? If not please let me know.

**Comment by annajeanine** [comment]
Hi @stevebauman,

Thank you (again) for you're fast reply! This is exactly what I was looking for! 

Cheers!

**Comment by stevebauman** [comment]
No problem! If you have any other questions / issues please don't hesitate to create another issue here.
