### ISSUE TITLE
Using other attributes for authentication

### ISSUE THREAD

**Issue by darthtaco** [Adldap2/Adldap2-Laravel#187]
Our `users` table has an attribute `is_enabled` which is a boolean value supposed to govern whether or not a user account is active.  I would like to include this in the criteria for authentication.  In other words, in order to log in successfully, I would like to check 1) that the credentials match what is in LDAP, and 2) that the user's `is_enabled` flag is set to TRUE.

I note that user accounts which did not exist in the `users` table would have to be created -- or would have to have an `is_enabled` default value of TRUE for when Adldap2-Laravel creates them...

Any pointers on what is the best way to accomplish this?

Many thanks.

**Comment by stevebauman** [comment]
Hi @darthtaco,

Right now, the only option to reject a users authentication request if a field on their model is equal to a condition, would be extending the `AdldapAuthUserProvider`:

```php
namespace App\Providers;

LdapAuthUserProvider extends AdldapAuthUserProvider
{
    public function retrieveByCredentials(array $credentials)
    {
        $model = parent::retrieveByCredentials($credentials);

        return $model->is_enabled ? $model : null;
    }
}
``` 

Then, extend the `AdldapAuthServiceProvider`, and insert that into your `config/app.php` file:

```php
namespace App\Providers;

use Illuminate\Contracts\Hashing\Hasher;

class LdapAuthServiceProvider extends AdldapAuthServiceProvider
{
    protected function newAdldapAuthUserProvider(Hasher $hasher, $model)
    {
        return new LdapAuthUserProvider($hasher, $model);
    }
}
```

```php
'providers' => [
    '...',
    //Adldap\Laravel\AdldapAuthServiceProvider::class,

    App\Providers\LdapAuthServiceProvider::class, // Your custom LDAP auth provider.

]
```

**Comment by stevebauman** [comment]
To accomplish your second request, you could catch the event `Adldap\Laravel\Events\AuthenticatedWithCredentials`, which allows you to have access to the authenticated users Adldap model, as well as their Eloquent model.

```php
    /**
     * Create the event listener.
     *
     * @return void
     */
    public function __construct()
    {
        //
    }

    /**
     * Handle the event.
     *
     * @param  AuthenticatedWithCredentials  $event
     * @return void
     */
    public function handle(AuthenticatedWithCredentials $event)
    {
        $model  = $event->model;

        if (! $model->exists) {
            $model->is_enabled = true;
        }
    }
```

**Comment by darthtaco** [comment]
Great @stevebauman!  I was hoping to avoid extending your class but the way you have laid it out it seems to be a clean way of accomplishing what I'm looking for.  I had not considered an event handler as well.  Thanks for the detailed and quick response, very helpful.

**Comment by stevebauman** [comment]
No problem! If you encounter anything else please don't hesitate to create another issue here.
