### ISSUE TITLE
"Can't contact LDAP server" with the new version

### ISSUE THREAD

**Issue by isbkch** [Adldap2/Adldap2-Laravel#188]
I just upgraded my app from Laravel 5.2 to 5.3

And now using the version 2.1.* gives an error: Can't contact LDAP server
PS: login works just fine with version 1.4.*

Do you have an idea ?

**Comment by stevebauman** [comment]
Hi @isbkch,

There were configuration changes from v1 to v2. Delete your adldap configuration files and then republish them.

Let me know if you encounter any further issues!
