### ISSUE TITLE
Login limitations

### ISSUE THREAD

**Issue by strebl** [Adldap2/Adldap2-Laravel#19]
Just a question:
How would you set login limitations. For example only users from a special group should be able to login.
Without changing the `base_dn`...

**Comment by stevebauman** [comment]
Hmm this doesn't exist yet, but this is definitely something I want to implement. I'll work on this now and see what I can do.

**Comment by shaynejellesma** [comment]
How goes a solution Steve? I need something like this for the project i'm working on. Been playing around with some ways of doing it, at least for what I need in my project and came up with some dirty hack job like this https://gist.github.com/shaynejellesma/d6a9a2a4771e6ff79c04 I am sure you could come up with something better, but just throwing a bit of inspiration your way. Thanks for the package :smiley:

**Comment by stevebauman** [comment]
Hi @shaynejellesma, that's a good implementation, and I think it'd be nice to set the groups inside the `adldap_auth.php` configuration file. I'll see what I can do tonight (current working on `v6` of Adldap).

**Comment by clonerworks** [comment]
@shaynejellesma and @stevebauman, is it possible to search though the groups recursively? To allow for group nesting.

**Comment by stevebauman** [comment]
@clonerworks, by default all searches on LDAP through Adldap are recursive.

**Comment by lukasnasc** [comment]
HI guys.........@stevebauman i looking for some thinks like  @shaynejellesma said and try to implement but i dont know where put this:
$allowedGroups = ['Domain Admins', 'App Login Users'];
Auth::attempt('username' => 'user', 'password' => 'password', 'allowedGroups' => $allowedGroups);

??

I started study laravel now........ Appreciate the help!

**Comment by strebl** [comment]
Groups are only example. Another would be a specific filter, for example only users with an email address. I think there should be a way to set a ldap filter.

**Comment by lukasnasc** [comment]
Right, but how filter by ldap group? Only a especific group can login?  

Thanks the reply!

**Comment by stevebauman** [comment]
There's always the option of overriding the `newAdldapUserQuery()` method to include a custom filter.

https://github.com/Adldap2/Adldap2-Laravel/blob/v1.4/src/Traits/ImportsUsers.php#L208

Though this shouldn't be hard to implement. I'll take a look right now.

**Comment by stevebauman** [comment]
Added in the most recent commit. Will be creating a new release shortly.

https://github.com/Adldap2/Adldap2-Laravel/commit/7e27250e89cecc82797a2460f19ae1fb21dd333e

**Comment by strebl** [comment]
Didn't know that exists: `Config::get('adldap_auth.limitation_filter');` I think that's exactly what I was asking for :+1: 

Thans @stevebauman for your hard work!

**Comment by stevebauman** [comment]
You'll need to re-publish the configuration file to see the new option :)

No problem at all!

**Comment by lukasnasc** [comment]
Awesome! ...Thanks  @stevebauman !!

**Comment by lukasnasc** [comment]
Test and work great! ....just a think......if a type a valid user but with wrong password,this message happens: 

ErrorException in Ldap.php line 501:
ldap_bind(): Unable to bind to server: Invalid credentials

A miss something?

**Comment by stevebauman** [comment]
You must have debugging enabled inside your configuration. Disable it and you won't have that error message come up (inside your `.env` file).

Or if you want to stay in debug mode, you can catch the exception:

```php
try {
    if (Auth::attempt($credentials)) {
        // User passed authentication.
    } 
} catch (\ErrorException $e) {
     // Catch LDAP Bind Errors
}
```

**Comment by lukasnasc** [comment]
Thanks and sorry about the basic questions.........

**Comment by stevebauman** [comment]
No problem at all! No need to apologize.

**Comment by rnrstar** [comment]
I'm trying to get more information on the login limitation filter however, your link https://github.com/Adldap2/Adldap2-Laravel#login-limitation-filter no longer appears to work. It just takes me to the repository home page. 

I'm trying to limit login to a specific group but it doesn't seem to be working. I've added the following to the file config/adldap_auth.php but it seems to ignore it.

'limitation_filter' => '(memberof=CN=FoneFactory Report Users,DC=internal,DC=[mydomain],DC=com)',

I'm using Laravel 5.5 and adldap2/adldap2-laravel v3.0.5, adldap2/adldap2 v7.0.15.

**Comment by stevebauman** [comment]
Hi @rnrstar, the limitation filter was removed in favor of [scopes](https://github.com/Adldap2/Adldap2-Laravel/blob/master/docs/auth/scopes.md) and [rules](https://github.com/Adldap2/Adldap2-Laravel/blob/master/docs/auth/rules.md).

This is why my link no longer works and you don't see this option in the published configuration.

You will need to create a scope that limits the user query to your filter like so:

```php
namespace App\Scopes;

use Adldap\Query\Builder;
use Adldap\Laravel\Scopes\ScopeInterface;

class MemberOfScope implements ScopeInterface
{
    public function apply(Builder $query)
    {
        $group = 'CN=FoneFactory Report Users,DC=internal,DC=[mydomain],DC=com';

        $query->whereMemberOf($group);
    }
}
```

Remember to add this scope into your `config/adldap_auth.php` file when you're done.

For more details please visit this doc:

https://github.com/Adldap2/Adldap2-Laravel/blob/master/docs/auth/scopes.md#scopes

**Comment by rnrstar** [comment]
Thanks Steve. Got it working using the rules.

**Comment by stevebauman** [comment]
Great, glad you're up and running!
