### ISSUE TITLE
Laravel 5.0. Driver [adldap] not supported.

### ISSUE THREAD

**Issue by Zilurex** [Adldap2/Adldap2-Laravel#194]
Hello,

I've installed package, added 'Adldap\Laravel\AdldapServiceProvider' into config/app, changed config/auth driver to 'adldap' and I got `Driver [adldap] not supported.`

Is Laravel 5.0 supported?

**Comment by annajeanine** [comment]
Hi @Zilurex!

Have you followed the whole instruction from https://github.com/Adldap2/Adldap2-Laravel/blob/master/quick-start.md ?

**Comment by Zilurex** [comment]
Thank you for fast answer. I've been missing `Adldap\Laravel\AdldapAuthServiceProvider` in config/app. Problem solved.

**Comment by annajeanine** [comment]
No problem! Good luck! :-D

**Comment by Zilurex** [comment]
Thank you :)
