### ISSUE TITLE
No LDAP query results for filter

### ISSUE THREAD

**Issue by f0nt4** [Adldap2/Adldap2-Laravel#195]
Hi,

I'm trying to get this to work, but unfortunatly no luck yet so I hope you can help me out.
I already managed to be able to connect to the DC but it gives me no results back.
When I use `php artisan adldap:import {username}` on the command line, it gives me this back:
````
[Adldap\Exceptions\ModelNotFoundException]
No LDAP query results for filter: [(&(objectclass=person)(objectcategory=pe
rson)(anr=username))] in: [dc=companyname,dc=corp]
````
Also I tried to set corp in front of the company name, but that didn't work.

**Comment by stevebauman** [comment]
Hi @f0nt4,

Are you sure your `base_dn` in your `config/adldap.php` file is correct? You'll need it set correctly to retrieve any results from your AD server.

Also, just to make sure, are you literally passing in `php artisan adldap:import {username}`. or passing in `php artisan adldap:import johndoe`?

The beginning argument for the `adldap:import` command is your AD users username / email.

You can also just omit the argument and call `php artisan adldap:import` to import all AD users.

**Comment by f0nt4** [comment]
Hi Steve,

thanks for the fast answer! As I was still trying to get it to work, I found that I get an result when I set the base dn to a deeper level within the OU's.
This:
`OU=DTB Desktop,DC=companyname,DC=corp`
Gives me:
````
PHP Fatal error:  Class 'App\Models\User' not found in D:\InetPub\wwwroot\vendor
\adldap2\adldap2-laravel\src\Commands\Import.php on line 186

  [Symfony\Component\Debug\Exception\FatalErrorException]
  Class 'App\Models\User' not found

````
So, I'm a little further, but not yet there.

**Comment by stevebauman** [comment]
Sounds like your `User` model is missing / has been moved in your app. Check your `config/auth.php` file and see your `providers.uses.model` option.

**Comment by f0nt4** [comment]
And again I got a little further I think.
I now get a message "These credentials do not match our records." when I login.
I changed:
`protected $username = 'email';`
to:
````
public function username()
{
    return 'username';
}
````
in app/http/controllers/auth/LoginController.php

**Comment by f0nt4** [comment]
Hmmm, executing the following:
````
$username = 'myusername';
$password = 'mypassword';

dd(Adldap::authenticate($username, $password));
````
Gives:
````
ErrorException in Adldap.php line 87:
 
call_user_func_array() expects parameter 1 to be a valid callback, class 'Adldap\Connections\Provider' does not have a method 'authenticate'
````
and:
`dd(Adldap::users()->find('myusername'));`
Gives:
````
ErrorException in Adldap.php line 87:
 
call_user_func_array() expects parameter 1 to be a valid callback, class 'Adldap\Connections\Provider' does not have a method 'users'
````
exuting:
`$check = Adldap::search()->where('samaccountname', '=', $user )->first();`
And var_dumping it returns an array with all information.

Als some command I used to dd() outputted 1000 users or so.

**Comment by f0nt4** [comment]
Next update:
executing: 
```php
$username = 'username';
$password = 'password';
var_dump(Adldap::auth()->attempt($username, $password));
````
Gives back a true. Turned out I did have to fill in a account_prefix or a account_suffix.
I already tried this before, but turned out that you have to add 2x \ at the end of the prefix or include the @ in the suffix.
So it will look like this:
`'account_prefix' => 'domainname\\',` or `'account_suffix' => '@domain.corp',`

But using the login form still gives a "These credentials do not match our records. ".

**Comment by stevebauman** [comment]
Ok great, so you're connected, we just need to tweak your application now.

Did you change your `create_users_table` migration to match the `username` field instead of the `email` field? Also, can you post your `config/adldap_auth.php` as well as your `LoginController`?

**Comment by f0nt4** [comment]
Yup, did change the db table: http://i.imgur.com/n4upI1f.png
This is adldap_auth.php: http://i.imgur.com/HgvOtun.png
And this is the LoginController: http://i.imgur.com/o37DNSL.png

**Comment by stevebauman** [comment]
Hmm everything looks fine. Are you using OpenLDAP or Active Directory? Also can you post your `config/adldap.php` file (with the sensitive details omitted)?

**Comment by f0nt4** [comment]
Here you go: http://i.imgur.com/LLK7OiM.png

**Comment by stevebauman** [comment]
Can you try enabling `auto_connect` in your `config/adldap.php` file and then try authenticating?

**Comment by f0nt4** [comment]
Not working either :(

**Comment by stevebauman** [comment]
Hmmm, okay. Try disabling `follow_referrals` and authenticating.

**Comment by f0nt4** [comment]
HOLY MOLY! http://i.imgur.com/RrhBQxc.png

**Comment by stevebauman** [comment]
Haha great! Unfortunately LDAP is extremely picky. Enabling following referrals can cause some side effects.

**Comment by f0nt4** [comment]
I see. In the testing I probably enabled it because never disabled it again.
Because we have a large forest I thought this option could have helped. 
Well.. it didn;t.
Now on to the next step: SSO :)
And I'm gonna try to sync more attributes. Like the user membersships.

**Comment by stevebauman** [comment]
Great! If you need any more help don't hesitate to create another issue, thanks :).

**Comment by f0nt4** [comment]
Thank you too!

**Comment by groundbreaker08** [comment]
We have the same configurations. also follow_referrals is disabled. and yet it seems I cant authenticate it. And did what she did for checking if I have good connection on the ldap server and yes I did. I can retrieve all the info. it's just I cant authenticate in laravel 5.6
