### ISSUE TITLE
getManager method failed after updating to 6.1.10

### ISSUE THREAD

**Issue by jagDanJu** [Adldap2/Adldap2-Laravel#196]
Hey Guys,

after updating the Adldap2/adldap2 from version 6.1.9 to 6.1.10, i get the following error:

ErrorException: call_user_func_array() expects parameter 1 to be a valid callback, class 'Adldap\Connections\Provider' does not have a method 'getManager' in ..\vendor\adldap2\adldap2\src\Adldap.php:108

I had opend a issue on the Adldap2/adldap2 package (https://github.com/Adldap2/Adldap2/issues/338) and user let me know that the method getManager() has been removed (https://github.com/Adldap2/Adldap2/blob/e18e17d90994ce635608da93f350cc32bae2f663/docs/upgrading.md#--removed-1)

Is there any solution or workarround for this package?

Greetings Daniel

**Comment by xBytez** [comment]
If you use Adldap2-Laravel and you get this error. you need to change Line 272 on https://github.com/Adldap2/Adldap2-Laravel/blob/f4a183369076a184e4135599ad3391c5c74d470f/src/Traits/ImportsUsers.php#L272 to the current version on Git. I assume composer hasn't updated for adldap2-laravel. Doing that fixed this issue for me.

**Comment by stevebauman** [comment]
*facepalm* Sorry guys, completely my fault.

I tagged the master branch with `6.1.10` instead of the `6.1` branch. Please re-pull update using `composer update`.

**Comment by lukhan** [comment]
Hello
Problem is in Adldap2/Adldap2-Laravel . Version master is ok, but 2.1.3 not working. How can I fix it?

**Comment by jagDanJu** [comment]
@lukhan Read the post from @stevebauman
