### ISSUE TITLE
The connection provider 'xxx.xxx.xxx.xxx' does not exist. in Manager.php line 44

### ISSUE THREAD

**Issue by naretini** [Adldap2/Adldap2-Laravel#197]
What it's working for me 
$user = Adldap::search()->users()->find('jhon');
So my app is correctly autoconnecting to ldap.

But trying to login using custom laravel Auth scaffholding I get the error in the subject.
 This is the first lines of error dump:

in Manager.php line 44
at Manager->get('xxx.xxx.xxx.xxx') in ImportsUsers.php line 272
at AdldapAuthUserProvider->getAdldap() in ImportsUsers.php line 258
at AdldapAuthUserProvider->getSchema() in ImportsUsers.php line 337
at AdldapAuthUserProvider->getUsernameAttribute() in ImportsUsers.php line 304
at AdldapAuthUserProvider->getUsernameKey() in AdldapAuthUserProvider.php line 241
at AdldapAuthUserProvider->getUsernameFromCredentials(array('email'=>'myemail@xxx.com', 'password'=>'12345678'))

**Comment by stevebauman** [comment]
Can you paste both your `adldap.php` and `adldap_auth.php` configuration files? It sounds like the connection you specified in your `adldap_auth.php` file doesn't exist.

**Comment by naretini** [comment]
<?php
return [
    
    'connections' => [
        'default' => [
            
            'auto_connect' => true,
            
            'connection' => Adldap\Connections\Ldap::class,
            
            'schema' => Adldap\Schemas\ActiveDirectory::class,
            
            'connection_settings' => [
               
                'account_prefix' => '',
                
                'account_suffix' => env('ADLDAP_ACCOUNT_SUFFIX'),
                
                'domain_controllers' => [env('ADLDAP_D_CONTROLER02'), env('ADLDAP_D_CONTROLER01')],
                
                'port' => env('ADLDAP_PORT'),
               
                'timeout' => 5,
               
                'base_dn' => env('ADLDAP_BASE_DN'),
                
                'admin_account_suffix' => env('ADLDAP_ACCOUNT_ADMIN_SUFFIX'),
                'admin_username' => env('ADLDAP_ADMIN_USERNAME'),
                'admin_password' => env('ADLDAP_ADMIN_PASSWORD'),
                
                'follow_referrals' => false,
               
                'use_ssl' => false,
                'use_tls' => false,
            ],
        ],
    ],
];

-------------------------------------------------------------

<?php
return [

    'connection' => env('ADLDAP_CONNECTION', 'default'),

    'username_attribute' => ['email' => 'mail'],

    'limitation_filter' => env('ADLDAP_LIMITATION_FILTER', ''),
 
    'login_fallback' => env('ADLDAP_LOGIN_FALLBACK', false),
    
    'password_key' => env('ADLDAP_PASSWORD_KEY', 'password'),

    'password_sync' => env('ADLDAP_PASSWORD_SYNC', true),

    'login_attribute' => env('ADLDAP_LOGIN_ATTRIBUTE', 'samaccountname'),

    'windows_auth_attribute' => ['samaccountname' => 'AUTH_USER'],
  
    'bind_user_to_model' => env('ADLDAP_BIND_USER_TO_MODEL', true),
    
    'sync_attributes' => [
        'name' => 'cn',
    ],
    
    'select_attributes' => [
        //
    ],
];

**Comment by stevebauman** [comment]
Strange... Can you post your `Auth` / `Login` controller?

**Comment by naretini** [comment]
<?php

namespace App\Http\Controllers\Auth;

use App\Http\Controllers\Controller;
use Illuminate\Foundation\Auth\AuthenticatesUsers;

class LoginController extends Controller
{
    /*
    |--------------------------------------------------------------------------
    | Login Controller
    |--------------------------------------------------------------------------
    |
    | This controller handles authenticating users for the application and
    | redirecting them to your home screen. The controller uses a trait
    | to conveniently provide its functionality to your applications.
    |
    */

    use AuthenticatesUsers;

    /**
     * Where to redirect users after login.
     *
     * @var string
     */
    protected $redirectTo = '/home';

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('guest', ['except' => 'logout']);
    }
}

**Comment by stevebauman** [comment]
Closing due to configuration issue.

Please try deleting your `adldap.php` and `adldap_auth.php` configuration files and republishing default ones by the `php artisan vendor:publish` command.

Also, make sure you're registering the `AdldapServiceProvider` and the `AdldapAuthServiceProvider` properly in your `app.php` configuration file.
