### ISSUE TITLE
admin_account_prefix is missing in config/adldap.php? 

### ISSUE THREAD

**Issue by kayrules** [Adldap2/Adldap2-Laravel#201]
Variable `admin_account_prefix` is missing in config/adldap.php? When login a user, I got this error below:

```
BindException in Guard.php line 84:
Invalid credentials
in Guard.php line 84
at Guard->bind('username', 'password', '', '') in Guard.php line 100
at Guard->bindAsAdministrator() in Provider.php line 200
``` 

Tried to put config in the file `'admin_account_prefix' => 'domain',`, but still no luck.
However, this error gone after I feed the `ADLDAP_ADMIN_USERNAME=domain\username` in .env file config.

Thanks

**Comment by stevebauman** [comment]
Hi @kayrules,

There is no option named 'admin_account_prefix', only 'admin_account_suffix'.

I can see how this can be confusing since there's an option for one but not the other.

You can just utilize the option 'account_suffix' and it will be used binding the admin account as well.

**Comment by kayrules** [comment]
Thank you @stevebauman,
It turns out that I just need to add a backslash on `account_prefix` for the domain name as below:
```
'account_prefix' => 'domain\\',
```
now it will able to bind both for users & admin.

Thanks
