### ISSUE TITLE
Issues with retrieving results

### ISSUE THREAD

**Issue by cisvpn-sai** [Adldap2/Adldap2-Laravel#202]
Does this class work with Laravel 5.3?  I noticed the main difference is that AuthController got deprecated.  But everything else seems the same. I am relatively new to Laravel and LDAP in general.  I followed the instructions and things seem to not pass the login.  It doesn't even hit the LDAP server.  The login just seems to refresh when I submit.  Is there something wrong with my code?  I removed the comments for ease of reading.  The XXXXXX's would contain my information.

```
# Auth.php

<?php

return [

    'defaults' => [
        'guard' => 'web',
        'passwords' => 'users',
    ],

    'guards' => [
        'web' => [
            'driver' => 'session',
            'provider' => 'users',
        ],

        'api' => [
            'driver' => 'token',
            'provider' => 'users',
        ],
    ],

    'providers' => [
        'users' => [
            'driver' => 'adldap',//'eloquent',
            'model' => App\User::class,
        ],

        // 'users' => [
        //     'driver' => 'database',
        //     'table' => 'users',
        // ],
    ],

    'passwords' => [
        'users' => [
            'provider' => 'users',
            'table' => 'password_resets',
            'expire' => 60,
        ],
    ],

];
```

```
# adldap.php

<?php

return [

    'connections' => [

        'default' => [

            'auto_connect' => true,

            'connection' => Adldap\Connections\Ldap::class,

            'schema' => Adldap\Schemas\ActiveDirectory::class,

            'connection_settings' => [

                'account_prefix' => '',

                'account_suffix' => '@xxxxxxxxx.com',

                'domain_controllers' => ['xxxxxxxxxx','xxxxxxxxxxx'],

                'port' => 389,

                'timeout' => 5,

                'base_dn' => 'OU=XXX,OU=XXX,DC=xxx,DC=xxxxxx',

                'admin_account_suffix' => '@xxxxxx.com',

                'admin_username' => env('ADLDAP_ADMIN_USERNAME', 'xxxxx'),

                'admin_password' => env('ADLDAP_ADMIN_PASSWORD', 'xxxxx'),

                'follow_referrals' => false,

                'use_ssl' => false,

                'use_tls' => false,

            ],

        ],

    ],

];
```

```
# adldap_auth.php

<?php

return [


    'connection' => env('ADLDAP_CONNECTION', 'default'),

    'username_attribute' => ['username' => 'samaccountname'],

    'limitation_filter' => env('ADLDAP_LIMITATION_FILTER', ''),

    'login_fallback' => env('ADLDAP_LOGIN_FALLBACK', false),

    'password_key' => env('ADLDAP_PASSWORD_KEY', 'password'),

    'password_sync' => env('ADLDAP_PASSWORD_SYNC', true),

    'login_attribute' => env('ADLDAP_LOGIN_ATTRIBUTE', 'samaccountname'),

    'windows_auth_attribute' => ['samaccountname' => 'AUTH_USER'],

    'bind_user_to_model' => env('ADLDAP_BIND_USER_TO_MODEL', false),

    'sync_attributes' => [

        'name' => 'cn',

    ],

    'select_attributes' => [

    ],

];

```

**Comment by stevebauman** [comment]
Hi @cisvpn-sai, apologies for the late response.

There are no issues using Adldap2 with Laravel 5.3. Your configuration looks fine, but are you **sure** it's not hitting your LDAP server? There's a possibility that your account suffix or your base DN might be incorrect and it's just failing binding to your LDAP server.

Can you post your login view?

**Comment by cisvpn-sai** [comment]
Hi Steve,  Thank you for the reply.  Thank you for confirming that things should work with Laravel 5.3.  I was able to get the login page to finally give a response.  I skipped the AuthController portion of your guide because it didn't exist.  I found this article: https://laracasts.com/discuss/channels/general-discussion/login-by-username-in-laravel-53 that said to override username in the LoginController.php itself.  After I did that my form now sends back error messages.  I still can't login with my valid credentials though.

Login.blade.php
```
@extends('layouts.app')

@section('content')

<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Login</div>
                <div class="panel-body">
                    <form class="form-horizontal" role="form" method="POST" action="{{ url('/login') }}">
                        {{ csrf_field() }}

                        <div class="form-group{{ $errors->has('username') ? ' has-error' : '' }}">
                            <label for="username" class="col-md-4 control-label">Username</label>

                            <div class="col-md-6">
                                <input id="username" type="text" class="form-control" name="username" value="{{ old('username') }}" required autofocus>

                                @if ($errors->has('username'))
                                    <span class="help-block">
<?php
var_dump($errors);
?>
                                        <strong>{{ $errors->first('username') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('password') ? ' has-error' : '' }}">
                            <label for="password" class="col-md-4 control-label">Password</label>

                            <div class="col-md-6">
                                <input id="password" type="password" class="form-control" name="password" required>

                                @if ($errors->has('password'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('password') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-4">
                                <div class="checkbox">
                                    <label>
                                        <input type="checkbox" name="remember"> Remember Me
                                    </label>
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-8 col-md-offset-4">
                                <button type="submit" class="btn btn-primary">
                                    Login
                                </button>

                                <a class="btn btn-link" href="{{ url('/password/reset') }}">
                                    Forgot Your Password?
                                </a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

```

LoginController.php

```
<?php

namespace App\Http\Controllers\Auth;

use App\Http\Controllers\Controller;
use Illuminate\Foundation\Auth\AuthenticatesUsers;

class LoginController extends Controller
{
    /*
    |--------------------------------------------------------------------------
    | Login Controller
    |--------------------------------------------------------------------------
    |
    | This controller handles authenticating users for the application and
    | redirecting them to your home screen. The controller uses a trait
    | to conveniently provide its functionality to your applications.
    |
    */

    use AuthenticatesUsers;

    /**
     * Where to redirect users after login.
     *
     * @var string
     */
    protected $redirectTo = '/home';

    /**
     * Username value
     *
     * @var string
     */
    protected $username = 'username';

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('guest', ['except' => 'logout']);
    }

    /**
     * Override the username method used to validate login
     *
     * @return string
     */
    public function username()
    {
        return 'username';
    }
}

```

**Comment by stevebauman** [comment]
Are you sure the user you're authenticating with exists inside the `OU` you're specifying in your `base_dn`?

```php
OU=XXX,OU=XXX,DC=xxx,DC=xxxxxx
```

**Comment by cisvpn-sai** [comment]
Hi @stevebauman I ran the artisan adldap:import myusername call and it came back with a ModelNotFoundException.  But the IT person showed me that my username is in the BASE_DN OU specified.  He even showed me previous ldap projects with same settings that work.  Could there another reason why I am getting an Exception back from the call?

**Comment by stevebauman** [comment]
Are you using ActiveDirectory or OpenLDAP?

**Comment by cisvpn-sai** [comment]
ActiveDirectory

**Comment by stevebauman** [comment]
This sounds like it could be a server side issue since it's just not finding a user (indicated by the `ModelNotFoundException`), but it's connecting fine.

In your `routes/web.php` file, at the top, can you insert:

```php
$users = \Adldap\Laravel\Facades\Adldap::search()->users()->get();

dd($users);
```

And see what is returned when you visit your dev site?

**Comment by cisvpn-sai** [comment]
Yes, I got this:

Collection {#138 ▼
  #items: []
}

**Comment by stevebauman** [comment]
Oh hmm, no results at all. Can you get rid of the `OU`s specified in your `base_dn` and try running it again?

So your base DN in your config should be:


```
DC=XXXXX,DC=XXXXX
```

**Comment by cisvpn-sai** [comment]
Thanks BTW, Steve.  Appreciate your time and help.
Same result: 
Collection {#138 ▼
  #items: []
}

'base_dn' => 'DC=abc,DC=xyz',

abc and xyz not literal.

**Comment by stevebauman** [comment]
No problem!

Okay, try running just a general search and see if absolutely anything is returned (replace with previous):

```php
$models = \Adldap\Laravel\Facades\Adldap::search()->all();

dd($models);
```

**Comment by cisvpn-sai** [comment]
I am having trouble getting my User.php to access my alternate local database instead of default.  Would that have any effect on this LDAP results?  I wouldn't think so but throwing that out there.

Im doing this but doesnt change: `protected $connection = 'mysql_ldap_users';`

Just did your general search and same result:

Collection {#138 ▼
  #items: []
}

**Comment by stevebauman** [comment]
> I am having trouble getting my User.php to access my alternate local database instead of default. Would that have any effect on this LDAP results? I wouldn't think so but throwing that out there.

Yea this wouldn't affect your ability to retrieve LDAP users. It seems like there's literally no records at all being returned. Try running `php artisan config:clear` and then try visiting your dev site to see if any results are returned.

If no results are returned, I'm out of ideas. It must be the `base_dn` configuration as that's the only reason no results would be returned on a global search.

**Comment by cisvpn-sai** [comment]
Cleared and is same result.  I will keep trying to get some results from the ldap.  I will post when I get something.  Thanks @stevebauman !

**Comment by cisvpn-sai** [comment]
@stevebauman We just used a Ldap client on my machine and we were able to connect to the ldap server. No problems.  Just an update. :)

**Comment by stevebauman** [comment]
Okay, but are you able to retrieve any results?

**Comment by cisvpn-sai** [comment]
Yes, I should have been more specific.  I saw many results.  I was even able to look at the data using this tool.

**Comment by cisvpn-sai** [comment]
Yes we placed a basic php script that connected and pulled data in the public area of the laravel directory.  So strange.

**Comment by stevebauman** [comment]
With this script, are you binding with the admin account that you've specified in your `adldap.php` file?

**Comment by cisvpn-sai** [comment]
Yes, We made a simple form where we binded two fields, username and password with 
$bind = @ldap_bind($ldapconn, $user, $pass);
I tried the admin login and my own personal.  Different data came back but there was data. 

Just an update: I tried doing a fresh install as I thought maybe I broke things somewhere and its the same issue.  I installed a fresh copy of laravel in a new directory, configured adldap2 and tried to $models = \Adldap\Laravel\Facades\Adldap::search()->all(); in the web.php.

Collection {#135 ▼
  #items: []
}

**Comment by stevebauman** [comment]
Can you try:

```php
$models = \Adldap\Laravel\Facades\Adldap::search()->raw()->get();

dd($models);
```

**Comment by cisvpn-sai** [comment]
I get [] returned.

**Comment by cisvpn-sai** [comment]
I recently changed my computers subnet mask.  Would that effect this in some way?

**Comment by cisvpn-sai** [comment]
Hello @stevebauman , I was able to get the data pulling from active directory.  Honestly, I dont know what I did other than configure migration file and User file correctly to the local database.  After I got that working, it seemed the AD connection just kicked in.  I can now php artisan adldap:import the users and $users = \Adldap\Laravel\Facades\Adldap::search()->users()->get(); dd($users);

I have a new issue with username and displayName not matching breaks the authentication.  I will open a new issue for this new problem.

**Comment by stevebauman** [comment]
> I recently changed my computers subnet mask. Would that effect this in some way?

If you're still receiving results from other tools on that same PC from your AD server, then it shouldn't have affected anything.

> Honestly, I dont know what I did other than configure migration file and User file correctly to the local database.

That's strange, configuring those wouldn't have anything to do with receiving results from AD.

> I have a new issue with username and displayName not matching breaks the authentication. I will open a new issue for this new problem.

Okay, sounds good! I'd be glad to assist you. I'll close this issue.
