### ISSUE TITLE
 These credentials do not match our records. Laravel 5.2

### ISSUE THREAD

**Issue by georgehk** [Adldap2/Adldap2-Laravel#203]
Im getting this error after follow up all the steps, could you please guide me where should be the error.

**auth.php**

return [
    'defaults' => [
        'guard' => 'web',
        'passwords' => 'users',
    ],
    'guards' => [
        'web' => [
            'driver' => 'session',
            'provider' => 'adldap',
        ],
        'api' => [
            'driver' => 'token',
            'provider' => 'users',
        ],
    ],
    'providers' => [
        'adldap' => [
            'driver' => 'adldap',
            'model' => App\User::class,
        ],
    ],
    'passwords' => [
        'users' => [
            'provider' => 'users',
            'table' => 'password_resets',
            'expire' => 60,
        ],
    ],
];

**adldap.php**

return [
    'connections' => [
        'default' => [
            'auto_connect' => true,
            'connection' => Adldap\Connections\Ldap::class,
            'schema' => Adldap\Schemas\ActiveDirectory::class,
            'connection_settings' => [
                'account_prefix' => '',
                'account_suffix' => '@sos.school',
                'domain_controllers' => ['sos.school'],
                'port' => 389,
                'timeout' => 5,
                'base_dn' => 'dc=sos,dc=school',
                'admin_account_suffix' => '@sos.school',
                'admin_username' => env('ADLDAP_ADMIN_USERNAME', 'admin'),
                'admin_password' => env('ADLDAP_ADMIN_PASSWORD', 'admin'),
                'follow_referrals' => false,
                'use_ssl' => false,
                'use_tls' => false,
            ],
        ],
    ],
];

**adldap_auth.php**

return [
    'connection' => env('ADLDAP_CONNECTION', 'default'),
    'username_attribute' => ['username' => 'username'],
    'limitation_filter' => env('ADLDAP_LIMITATION_FILTER', ''),
    'login_fallback' => env('ADLDAP_LOGIN_FALLBACK', false),
    'password_key' => env('ADLDAP_PASSWORD_KEY', 'password'),
    'password_sync' => env('ADLDAP_PASSWORD_SYNC', true),
    'login_attribute' => env('ADLDAP_LOGIN_ATTRIBUTE', 'samaccountname'),
    'windows_auth_attribute' => ['samaccountname' => 'AUTH_USER'],
    'bind_user_to_model' => env('ADLDAP_BIND_USER_TO_MODEL', true),
    'sync_attributes' => [
        'name' => 'cn',
    ],
    'select_attributes' => [
    ],
];

**routes.php**

Route::get('/', function () {
    return view('welcome');
});
Route::auth();
Route::get('/home', 'HomeController@index');
Route::get('about',function()
{
    $login=null;
    if(Adldap::auth()->attempt('test','password')){
        $login='okay';
    }
    else
    {
        $login='wrong';
    }
    return $login;
}
);

**for testing I added 'about' route and it return true**. Also when i run **php artisan adldap:import**

C:\Users\georgeSOS\Desktop\lara52>php artisan adldap:import
[32mFound 3222 user(s). Importing...[39m
[2K 3221/3221 [============================] 100%[32m
Successfully imported / synchronized 0 user(s).[39m

I changed username instead of email in all the necessary places, including the migrations.

Appreciate for your help

**Comment by stevebauman** [comment]
If you're using `username` instead of `email`, insert this into the `username_attribute` config option:

```php
'username_attribute' => ['username' => 'samaccountname'],
```

Also, you said you've changed the migration to `username` instead of `email` in your migrations, but just to double check, have you re-run your migrations to make sure your table is using `username` instead of `email`?

**Comment by georgehk** [comment]
Hello Steve,
Thank you for your reply, one more time you are right, after i changed that variable name everything works perfectly.
Thanks a lot.
