### ISSUE TITLE
Updating User Model

### ISSUE THREAD

**Issue by skratter** [Adldap2/Adldap2-Laravel#204]
Hello,
i've got a problem understanding whats going on behind the scenes.

I set adldap2-laravel up in laravel 5.3. 
I have a custom User Model where laravel updates the record of an user when he logs in. 

If the user which is trying to login, is not on this database table, the login should fail.

Now after setting up adldap2 the system trys to insert the new record if the user is not on the table.

But all i want is to be redirected back with the error that there is no such record. like it behaved the times before. The best case would be, that adlap2 is looking in the table, if the user-login is present and proceed to login and if the user is not present it redirect back with information that the user has no right or something like this.

I also set up a couple of custom fields in the table which should be considered as well but thats another story i guess.

aside: login in with correct user functions well. :) 

best regards
Daniel

**Comment by stevebauman** [comment]
Hi @skratter,

> if the user which is trying to login, is not on this database table, the login should fail.

Like you've discovered, this is the opposite of the purpose of the auth driver. The point of the Adldap auth driver, is to automatically import an AD user into your local database and synchronize data if they have an AD account.

You'll have to implement this yourself while using the default `eloquent` auth driver which shouldn't be too difficult:

```php
<?php

namespace App\Http\Controllers\Auth;

use App\User;
use Illuminate\Http\Request;
use Adldap\Laravel\Facades\Adldap;
use App\Http\Controllers\Controller;
use Illuminate\Foundation\Auth\AuthenticatesUsers;

class LoginController extends Controller
{
    /*
    |--------------------------------------------------------------------------
    | Login Controller
    |--------------------------------------------------------------------------
    |
    | This controller handles authenticating users for the application and
    | redirecting them to your home screen. The controller uses a trait
    | to conveniently provide its functionality to your applications.
    |
    */

    use AuthenticatesUsers {
        login as traitLogin;
    }

    /**
     * Where to redirect users after login.
     *
     * @var string
     */
    protected $redirectTo = '/home';

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('guest', ['except' => 'logout']);
    }

    /**
     * Handle a login request to the application.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function login(Request $request)
    {
        $user = Adldap::search()->where('mail', '=', $request->email);

        if ($user) {
            // Looks like the user exists in our AD,
            // let's allow them to authenticate.
            return $this->traitLogin($request);
        }

        return redirect()->back()->with('message', 'User not found in AD.');
    }
}
```

**Comment by skratter** [comment]
Thx alot. :)
