### ISSUE TITLE
LDAP Authentication issue when samaccountname and displayName do not match

### ISSUE THREAD

**Issue by cisvpn-sai** [Adldap2/Adldap2-Laravel#205]
Hi @stevebauman, 
After getting my AD to work I am now trying to log in.  However there is a very strange issue where I cannot log with an account where the displayName does not match the username I am logging in with.  We stumbled upon this when we were able to log in as one user but not with another.  After trial and error we found that the displayName field had to match.  When we added a matching displayName to any non-working account.  It started to work.  Is there a something I am doing wrong that is causing this?

my adldap_auth.php

```
return [
'connection' => env('ADLDAP_CONNECTION', 'default'),
'username_attribute' => ['username' => 'samaccountname'],
'limitation_filter' => env('ADLDAP_LIMITATION_FILTER', ''),
'login_fallback' => env('ADLDAP_LOGIN_FALLBACK', true),
'password_key' => env('ADLDAP_PASSWORD_KEY', 'password'),
'password_sync' => env('ADLDAP_PASSWORD_SYNC', true),
'login_attribute' => env('ADLDAP_LOGIN_ATTRIBUTE', 'samaccountname'),
'windows_auth_attribute' => ['samaccountname' => 'AUTH_USER'],
 'bind_user_to_model' => env('ADLDAP_BIND_USER_TO_MODEL', true),
'sync_attributes' => [
    'name' => 'cn'
],
'select_attributes' => [
        //
 ],
];
```

**Comment by stevebauman** [comment]
That's strange, I have the same configuration and I'm able to authenticate users who don't have a display name.

Are you sure this isn't server related?

**Comment by cisvpn-sai** [comment]
When you say server related, do you mean data is not being pulled? If I do a php artisan adldap:import, it will pull in all the data into my local DB.  If I have an empty local DB with migrated tables, and I login to a AD user that has a matching displayName.  Itll log me in and create the user in the local DB.  If I try to log in to a AD user without a matching displayName.  It will say "These credentials do not match our records."  We are using the default Laravel 5.3 LoginController and Blade.  Are you using the default Laravel Login Controller and Blade to test?

**Comment by stevebauman** [comment]
> When you say server related, do you mean data is not being pulled?

I'm saying it seems like when an `ldap_bind()` takes place (which is how Adldap authenticates against your AD server), your server is just saying 'Invalid credentials'. For what reason, I'm not sure. I'm assuming this is the case because you can successfully authenticate against other AD accounts.

> Are you using the default Laravel Login Controller and Blade to test?

Yes I'm using a completely stock Laravel 5.3 install with the newest Adldap instance installed.

**Comment by stevebauman** [comment]
The adldap auth driver authentication method:

https://github.com/Adldap2/Adldap2-Laravel/blob/v2.0/src/AdldapAuthUserProvider.php#L166-L169

Which calls the Adldap Guard instance:

https://github.com/Adldap2/Adldap2/blob/v6.1/src/Auth/Guard.php#L36-L59

**Comment by cisvpn-sai** [comment]
Thank You, I will dig in to see what I can find.  I will update you.  Thanks @stevebauman

**Comment by stevebauman** [comment]
No problem, and thanks! I'll also continue investigating on my end as well to ensure there's no issues.

**Comment by cisvpn-sai** [comment]
Thanks, So far I have tracked it down to:
```
 if (!@$this->connection->bind($username, $password)) {
            var_dump("BIND ERROR: ".$this->connection->getLastError());
            throw new BindException($this->connection->getLastError(), $this->connection->errNo());
 }

```

So the bind is failing for some reason.  Error is as you said, "Invalid Credentials"

**Comment by stevebauman** [comment]
Yea that's odd, your server is rejecting the credentials.

Do you maybe have any group policies that may prevent authenticating without a display name that matches their username? Though I'm not sure to be honest, as I've never heard of any rules that would do that.

**Comment by cisvpn-sai** [comment]
We dont have any group policies set up like that. We have Ldap working in different locations and even works with different applications on the same box. :/  I'll keep digging.

**Comment by cisvpn-sai** [comment]
I noticed my AdldapAuthUserProvider.php is different from the one you referenced:
Here is one obvious function thats different:

```
public function retrieveByCredentials(array $credentials)
    {
        $user = $this->authenticateWithCredentials($credentials);

        // Check if we've authenticated and retrieved an AD user.
        if ($user instanceof User && $this->user = $user) {
            // Retrieve the password from the submitted credentials.
            $password = $this->getPasswordFromCredentials($credentials);

            // Construct / retrieve the eloquent model from our Adldap user.
            $model = $this->getModelFromAdldap($user, $password);

            if (method_exists($model, 'trashed') && $model->trashed()) {
                // If the model is soft-deleted, we'll fire an event
                // with the affected LDAP user and their model.
                $this->handleAuthenticatedModelTrashed($user, $model);

                // We also won't allow soft-deleted users to authenticate.
                return;
            }

            // Perform other authenticated tasks.
            $this->handleAuthenticatedWithCredentials($user, $model);

            return $model;
        }

        if ($this->getLoginFallback()) {
            // Login failed. If login fallback is enabled
            // we'll call the eloquent driver.
            return parent::retrieveByCredentials($credentials);
        }
    }

```

Am I using the latest??
My composer.json is "adldap2/adldap2-laravel": "^2.1"

**Comment by cisvpn-sai** [comment]
Got it!  Not sure why but it was the account_prefix.  Our server requires a account_prefix.  However missing that prefix would still work if your displayName was the same as samaccountname.

**Comment by bahman2216** [comment]
I have same problem! what is account_prefix?

**Comment by cisvpn-sai** [comment]
@bahman2216 Hello bahman2216,  Its been a while and my memory fails me but the account prefix is in your config/adldap.php file.  Check to see if you have that filled in correctly.
/*
                |--------------------------------------------------------------------------
                | Account Prefix
                |--------------------------------------------------------------------------
                |
                | The account prefix option is the prefix of your user accounts in AD.
                |
                | For example, if you'd prefer your users to use only their username instead
                | of specifying a domain ('ACME\jdoe'), enter your domain name.
                |
                */

                'account_prefix' => 'your-domain\\',
