### ISSUE TITLE
Login Fallback when unable to bind

### ISSUE THREAD

**Issue by gd-jroberts** [Adldap2/Adldap2-Laravel#206]
When I am developing at home I cannot connect to the company LDAP server because of VPN and firewall issues. Therefore I receive a BindException. Would it be possible to have graceful degradation such that instead of a BindException the package would first try to fallback to local credentials, and then only if both attempts (bind and fallback) fail, throw an exception? I've already synced with AD while at work and would like to be able to transition between home and the office without having to mess with the auth setup.

**Comment by stevebauman** [comment]
If you set `auto_connect` to `false` and `login_fallback` to `true` in the `adldap` configuration files, you'll be able to develop without access to your LDAP server.

**Comment by gd-jroberts** [comment]
#RTM

Thanks. Cooking with gas now.

**Comment by stevebauman** [comment]
No problem! If you encounter anything else please create another issue :).
