### ISSUE TITLE
php artisan adldap:import throws an exception

### ISSUE THREAD

**Issue by eleftrik** [Adldap2/Adldap2-Laravel#207]
Hi, when I launch

`php artisan adldap:import --filter="(memberOf=CN=mygroup,CN=Users,DC=my,DC=company)" --delete=true
`
I got this error:

```
  [Symfony\Component\Debug\Exception\FatalThrowableError]                                                                                               
  Type error: Argument 1 passed to Adldap\Laravel\Commands\Import::import() must be of the type array, object given, called in /var/www/intranet.asl1/vendor/adldap2/adldap2-laravel/src/Commands/Import.php on line 74                                                                                       

```                                                                                                                                                        

If I edit that file and I insert, before line 74

`$users = $users->toArray();`

everything works correctly.

Thank you

**Comment by stevebauman** [comment]
Definitely an oversight on my part. Thanks for the report!

New release will be out in moment.

**Comment by stevebauman** [comment]
Hang on, you must be using `dev-master`? The latest release doesn't contain this bug.

**Comment by eleftrik** [comment]
@stevebauman In my composer.json I see

`        "adldap2/adldap2-laravel": "master",`

**Comment by stevebauman** [comment]
Yea you're using the `dev-master` version. If you're planning on having your application in production, I would use the stable releases though (insert `""adldap2/adldap2-laravel": "v2.1.*",` in your `composer.json`).
