### ISSUE TITLE
Search return empty collection

### ISSUE THREAD

**Issue by marcoacm** [Adldap2/Adldap2-Laravel#209]
I was able to authenticate using 
`Adldap::auth()->attempt($user['email'], $user['password'])`

But, when I try to search like this:
`$results = Adldap::search()->where('cn', 'starts_with', 'Marco')->get();`
It always returns:
`Collection {#485 ▼
  #items: []
}`

I also tried: contains, =, etc.... instead of 'starts_with' 

Can somebody help with this?

**Comment by stevebauman** [comment]
Hi @marcoacm, I believe I just responded to your email (correct me if I'm wrong).

If no results are returned, it's almost always your `base_dn` configuration in your `config/adldap.php` file.

I would remote into your AD server and verify that this is identical to the base DN on your server. 

One miss-typed character will result in no results.

Let me know how you make out!

**Comment by marcoacm** [comment]
@stevebauman, yes you responded to my email. Thank you so much.

I logged into my server and ran the commnad: `dsquery user` and got
`'CN=I2$,CN=Users,DC=Mydomain,DC=com'` which is exactly what I have on my adldap.php conf file.
But still no results.

**Comment by marcoacm** [comment]
@stevebauman here is my config file

`
<?php

return [

    'connections' => [

        'default' => [

            'auto_connect' => true,
            'connection' => Adldap\Connections\Ldap::class,
            'schema' => Adldap\Schemas\ActiveDirectory::class,
            'connection_settings' => [
                'account_prefix' => '',
                'account_suffix' => '@inktel.com',
                'domain_controllers' => ['mydomain.com'], 
                'port' => 389,
                'timeout' => 5,
                'base_dn' => 'CN=I2$,CN=Users,DC=Mydomain,DC=com',
                'admin_account_suffix' => '',
                'admin_username' => env('ADLDAP_ADMIN_USERNAME', 'user'),
                'admin_password' => env('ADLDAP_ADMIN_PASSWORD', 'pass),
                'follow_referrals' => true,
                'use_ssl' => false,
                'use_tls' => false,
            ],
        ],
    ],
];

`

**Comment by stevebauman** [comment]
Hi @marcoacm, your `base_dn` is incorrect, just use `DC=Mydomain,DC=com` and try retrieving results again.

**Comment by marcoacm** [comment]
I tried that already... Nothing.
Should I restart my server after changing the base_dn? or do anything else?

**Comment by marcoacm** [comment]
@stevebauman, I changed 'follow_refferrals' to 'false' and it works!
I am not sure why, but it does. 

Thanks for your help....

**Comment by stevebauman** [comment]
Thanks for the update @marcoacm, I didn't catch that it was enabled in your config. That would definitely do it in some environments.

No problem!
