### ISSUE TITLE
laravel 5.3 These credentials do not match our records.

### ISSUE THREAD

**Issue by nota141** [Adldap2/Adldap2-Laravel#210]
HI

quick note this is my first attempt at a project in a framework. and it has been awhile since I did more than a quick hack fix so my php might be a little rusty. 

I have been trying for a few days now to get Ldap login to work with my laravel 5.3 project with no success. I have had a various issues but I finally got stuck on the "These credentials do not match our records" error.
Today I thought maybe it was something i got wrong in one of the many attempts to fix one of the error so started a new project and following the quick start guide. 

only change i could see incorrect was step 13 

in app/Http/Controllers/Auth/LoginController.php added

    public function username()
    {
            return 'username';
    }
as this appears to be the new way to change email to username.

however I am still getting the These credentials do not match our records error. When I try and login.
are there any other changes that need to be made for a 5.3 install

edit: note running "php artisan adldap:import username" works to import a user into the table. but that user still can't login.

**Comment by stevebauman** [comment]
Hi @nota141,

Can you post your `config/adldap.php` file as well as your `config/adldap_auth.php` file (with sensitive details omitted)?

**Comment by nota141** [comment]
adldap_auth
`<?php

return [
    'connection' => env('ADLDAP_CONNECTION', 'default'),
    //'username_attribute' => ['email' => 'mail'],
   'username_attribute' => ['username' => 'samaccountname'],
    'limitation_filter' => env('ADLDAP_LIMITATION_FILTER', ''),
    'login_fallback' => env('ADLDAP_LOGIN_FALLBACK', false),
    'password_key' => env('ADLDAP_PASSWORD_KEY', 'password'),
    'password_sync' => env('ADLDAP_PASSWORD_SYNC', true),
    'login_attribute' => env('ADLDAP_LOGIN_ATTRIBUTE', 'samaccountname'),
    'windows_auth_attribute' => ['samaccountname' => 'AUTH_USER'],
    'bind_user_to_model' => env('ADLDAP_BIND_USER_TO_MODEL', false),
    'sync_attributes' => [
        'name' => 'cn',
    ],
    'select_attributes' => [
        //
    ],
];
`

and adldap
`<?php

return [
    'connections' => [
        'default' => [
            'auto_connect' => true,
            'connection' => Adldap\Connections\Ldap::class,
            'schema' => Adldap\Schemas\ActiveDirectory::class,
            'connection_settings' => [
                'account_prefix' => '', //left blank
                'account_suffix' => '',//left blank
                'domain_controllers' => ['X.X.X.X'],
                'port' => 389,
                'timeout' => 5,
                'base_dn' => 'dc=XXXXX,dc=XXXXX',
                'admin_account_suffix' => '',
                'admin_username' => env('ADLDAP_ADMIN_USERNAME', 'CN=XXXXXX,OU=XXXXXX,DC=XXXXX,DC=XXXXX'),
                'admin_password' => env('ADLDAP_ADMIN_PASSWORD', 'XXXXXX'),
                'follow_referrals' => false,
                'use_ssl' => false,
                'use_tls' => false,
            ],
        ],
    ],
];
`

**Comment by stevebauman** [comment]
Are you including account suffix / prefix when the user is logging it?

Otherwise, you'll need to include a prefix / suffix, for example:

```php
'account_suffix' => '@corp.acme',
```

**Comment by nota141** [comment]
OK thanks that was the problem we have a funky ad setup and some users have the external domain as there suffix some have there internal. So new problem can i support multiply account_suffixes?

**Comment by stevebauman** [comment]
Unfortunately no, you'd have to programmatically add this in, probably by:

1. Checking active directory for the user first
2. Then determine the correct suffix for the user
3. Append it onto the users username
4. Process the login

**Comment by nota141** [comment]
no problem thanks I will see if there is a valid reason for this set-up and work from there thanks for the assistance.

**Comment by stevebauman** [comment]
No problem at all! Please create another issue if you need any further help or encounter anything else :).

**Comment by vermaboys** [comment]
I have solved this issue. Click https://github.com/vermaboys/change-error-message-of-login-laravel5.4
