### ISSUE TITLE
Allow login only for already imported users

### ISSUE THREAD

**Issue by eleftrik** [Adldap2/Adldap2-Laravel#215]
Is there a way to let a (ldap) user login if and only if that user has already been imported in the `users` table?

Currently, iIf a user tries to login with valid LDAP credentials and its record is not present in the `users` table, the record gets created and the user logs in correctly (this is the standard behaviour, I see)

Instead, for me it would be useful that the user cannot login, until the user itself has been imported (via artisan command, ora in another way).

Is it possible to configure such a behaviour?

Thank you

**Comment by stevebauman** [comment]
Hi @eleftrik, good suggestion! Unfortunately this isn't built in, but I think this might be a great configurable option. Before passing the users credentials you could simply verify that they are an AD user and they exist in your `users` table:

```php
public function login(Request $request)
{
    $ldapUser = Adldap::search()->users()->whereMail($request->email)->first();

    $user = User::whereEmail($request->email)->first();

    if (
        $ldapUser instanceof \Adldap\Models\User &&
        $user instanceof \App\User &&
        Auth::attempt($request->only('email', 'password')
    ) {
        return redirect()->to('home')->withMessage('Successfully logged in!');
    }

    return redirect()->to('login')->withMessage('Username or password is incorrect');
}
```

I'll see what I can do though with another configurable option!

**Comment by eleftrik** [comment]
Thank you so much @stevebauman, it works like a charm!
