### ISSUE TITLE
These credentials do not match our records

### ISSUE THREAD

**Issue by ownmaster** [Adldap2/Adldap2-Laravel#216]
Hi,

I get this error when trying to login.

I use Laravel 5.3 and its authentication with Entrust 1.8.0-alpha1 and now added Adldap2/Adldap2-Laravel 2.1.
I made configuration based on reading [manual](https://github.com/Adldap2/Adldap2-Laravel), and comments ([this](https://github.com/Adldap2/Adldap2-Laravel/issues/7#issuecomment-142293763) and [this](https://github.com/Adldap2/Adldap2/issues/188#issuecomment-185719456)).
I also checked issues #46 and #90 but couldn't solve anything.

Before adding Adldap2 I already configured system to use **username** column instead of **email**, though **email** column stays in **users** table.

When I run `{{ dd(Adldap::search()->users()->find('test.user')) }}` it successfully finds and returns information about user.
But `{{ dd(Adldap::auth()->attempt('test.user', 'password')) }}` returns **false**.
I also tried supplying admin_username and admin_password to `Adldap::auth()->attempt()` and also got **false** response.

I double checked **connection_settings** parameters in config/adldap.php and all seems OK (I guess they are really OK, since I can search user).

Also, authentication over local DB still works normally: checked by enabling **login_fallback** option.

Where else can be the problem?

**Comment by stevebauman** [comment]
Hi @ownmaster,

Can you post your `config/adldap.php` as well as your `config/adldap_auth.php` file with sensitive details removed?

**Comment by ownmaster** [comment]
Hi,

Thanks. :) While posting the configs I re-read them again and was able to fix the problem:
1) I initially set both suffix and prefix as shown below:
`'account_prefix' => 'companyname',`
`'account_suffix' => '@companyname.com',`
After I set prefix to empty string, attempt() method started to work.
Though, I don't quite understand why it doesn't work with the prefix set to domain name, since documentation says:
> if you'd prefer your users to use only their username instead of specifying a domain ('ACME\jdoe'), enter your domain name

And now I don't set prefix and don't provide domain name during login, but authentication works.

2) I missed and left with default values **username_attribute** for login form, now changed it to:
`'username_attribute' => ['username' => 'samaccountname']`
