### ISSUE TITLE
Password hash

### ISSUE THREAD

**Issue by Keldarne** [Adldap2/Adldap2-Laravel#218]
Hi, 

I just imported my active directory users. Now I'm doing login system with database users imported, but I need to know if there is a way to hash password I get in login request to match database one.

I thought that using bcrypt() helper on the password I from my form was enough, but it isn't.

Any idea on how to achieve this in my loginController ?

**Comment by stevebauman** [comment]
Hi @Keldarne,

Adldap2-Laravel already uses `bcrypt()` to hash the passwords for imported users:

https://github.com/Adldap2/Adldap2-Laravel/blob/v2.0/src/Traits/ImportsUsers.php#L102-L123

Can you elaborate on your use case?

**Comment by Keldarne** [comment]
Hi @stevebauman,
I know that it's already using `bcrypt()` but my problem is in my case that I'm comparing user input with database user imported for login like this :

`public function postLogIn(Request $request)
    {
        $isSuccess = 0;
        $token = '';
        if ($request->has('username') and $request->has('password')) {
            $username = $request->input('username');
            $password = $request->input('password');
            dd(bcrypt($password));
            $user = User::where('username', $username)->first();
            if (bcrypt($password) == $user->password) {
                $token = $user->createToken('UserToken')->accessToken;
            }
        }
        return json_decode('{"login":"' . $isSuccess . '","token":"' . $token . '"}');

    }`

But when I check `dd(bcrypt($password));` it doesn't match my hashed password in database. Can't understand why.

If you need further information just ask ;)

**Comment by Keldarne** [comment]
Failed didn't want to close issue :(

**Comment by Keldarne** [comment]
Found solution, i had set an automatic salt after importing users, importing users again disabling my salt made it work sorry for inconvenience, I'm new to coding.

**Comment by stevebauman** [comment]
You actually need to validate the hash using `if (Hash::check($request->password, $user->password))`.

For your example:

```php
public function postLogIn(Request $request)
{
        $isSuccess = 0;
        $token = '';

        if ($request->has('username') and $request->has('password')) {
            $username = $request->input('username');
            $password = $request->input('password');

            $user = User::where('username', $username)->first();

            if (Hash::check($password, $user->password)) {
                $token = $user->createToken('UserToken')->accessToken;
            }
    }

    return json_decode('{"login":"' . $isSuccess . '","token":"' . $token . '"}');
}
```

**Comment by stevebauman** [comment]
> Found solution, i had set an automatic salt after importing users, importing users again disabling my salt made it work sorry for inconvenience, I'm new to coding.

No problem :). If you encounter anything else please create another issue.
