### ISSUE TITLE
Admin & User rules Adldap2

### ISSUE THREAD

**Issue by georgehk** [Adldap2/Adldap2-Laravel#220]
Hello Everyone,

I want to know if any of you guys implemented Admin and Users roles using adlap2, maybe based on a table roles.
Once they login check on the table and see what Authorization have and redirect to the right page.
Im implementing a single sign on for a school where teachers and students have different email domain and i would like to use this advantage to redirect to different pages based on their email address.

Any clue or suguestion please?

Cheers
georgehk

**Comment by stevebauman** [comment]
Hi @georgehk,

This would heavily depend on how you implement roles / permissions and doesn't really have much to do with LDAP authentication if you're relying on their email domain to determine their role, but here would be some psuedo-code to get you started:

```php
public function login(Request $request)
{
    if (Auth::attempt($request->only('email', 'password'))) {
        $user = Auth::user();
        $student = Role::whereName('student')->first();
        $teacher = Role::whereName('teacher')->first();
        list($name, $domain) = explode('@', $user->email);
        switch ($domain) {
            case 'teacher.email.com':
                $user->roles()->save($teacher);
                return redirect()->to('teachers/home');
            default:
                $user->roles()->save($student);
                return redirect()->to('students/home');
        }
    }
    return redirect()->to('login')->withMessage('Invalid credentials');
}
```
