### ISSUE TITLE
Login fallback priority

### ISSUE THREAD

**Issue by ownmaster** [Adldap2/Adldap2-Laravel#221]
Hi,

Is it possible to change authorization priority when using `login_fallback` option, for example, first attempt to authorize against local database and then, if it fails, try to authorize via LDAP?
Or, maybe, you can add such option in the future?

**Comment by stevebauman** [comment]
Hi @ownmaster, unfortunately this isn't possible at the moment.

Since the feature is named `fallback`, it's meant to fallback in cases where LDAP authentication fails.

I'm definitely not against this as an option if you have any suggestions on how it could be implemented to keep compatibility with how it currently functions.

**Comment by ownmaster** [comment]
Thanks, I will try to implement your recipe.

About suggestions, I can't say any details, since I'm fairly new to Laravel, but in general I think it should be exactly "priority", i.e. it will tell the system which authentication method should be used first. In such way it will work in both cases: when `login_fallback=true` and when `login_fallback=false`.

The thing I'm not sure about, is that probably this option should be a part of another package which will manage authentication selection based on providers defined in `auth.php`.

But since you already have `login_fallback` in this package, this new option will be useful anyway.

**Comment by stevebauman** [comment]
> EDIT: one of the benefits of this option could be that local DB authentication will still work in case LDAP connection fails. Now if something is wrong with LDAP connection the whole website will not work.

Actually, if you turn off `auto_connect`, and turn on `login_fallback`, you can try connecting manually and catch the exception on connection failure:

```php
public function login(Request $request)
{
    try {
        Adldap::connect();
    } catch (\Adldap\Auth\BindException $e) {
         // Couldn't connect to LDAP server.
    }

    if (Auth::attempt($request->only('username', 'password'))) {
        //
    }
}
```

**Comment by ownmaster** [comment]
I simulated wrong connection (using non-exsiting `ADLDAP_ADMIN_USERNAME` account) but I couldn't catch exception
```
try {
 \Adldap::connect('default');
 // code specific to LDAP auth
}
 catch (\Auth\BindException\Auth\BindException $e) {
 info('Could not connect to LDAP server.');
}
```
Instead of going to catch block, I get redirected to the error page with exception description:
> BindException in Guard.php line 84: Invalid credentials

The code is located in overridden `login()` method of `LoginController`.

**Comment by stevebauman** [comment]
That's because you're not catching the correct exception:

```php
try {
 \Adldap::connect('default');
 // code specific to LDAP auth
}
 catch (\Auth\BindException\Auth\BindException $e) { // This exception doesn't exist.
 info('Could not connect to LDAP server.');
}
```

Should be:

```php
try {
 \Adldap::connect('default');
 // code specific to LDAP auth
}
 catch (\Adldap\Auth\BindException $e) { // Correct exception.
 info('Could not connect to LDAP server.');
}
```

**Comment by ownmaster** [comment]
Sorry, didn't mention it, but I tried that initially. Actually, I tried other options and couldn't catch the exception (because of stupid mistakes). :)
But now I checked your source files and found that it is actually in
`\Adldap\Exceptions\Auth\BindException`

Below is the whole modified part of `login` action (Laravel 5.3, Adldap 2.1), probably it will be useful for someone - it combines 'LDAP offline' authentication and requires LDAP user to be in the local DB before he can login:
```
try {
  \Adldap::connect('default');

  $username = $credentials[$this->username()];
  $ldapUsernameField = current(config('adldap_auth.username_attribute'));
  $ldapUser = \Adldap::search()->users()->where($ldapUsernameField, '=', $username)->first();
  if (!is_null($ldapUser)) {
	$dbUser = User::where($this->username(), $username)->first();
	if (is_null($dbUser)) {
	  return redirect()->back()
		 ->withInput($request->only($this->username(), 'remember'))
		 ->withErrors([$this->username() => 'User is not in the database']);
	}
  }
}
catch (\Adldap\Exceptions\Auth\BindException $e) {
   info('Could not connect to LDAP server');
}

if ($this->guard()->attempt($credentials, $request->has('remember'))) {
	return $this->sendLoginResponse($request);
}
```

**Comment by stevebauman** [comment]
> But now I checked your source files and found that it is actually in
\Adldap\Exceptions\Auth\BindException

Oh apologies, I was referring to the master Adldap2 branch:

https://github.com/Adldap2/Adldap2/blob/master/src/Auth/BindException.php

I'm glad you've resolved your issue, thanks for posting your code!
