### ISSUE TITLE
Adldap-Laravel import user filter

### ISSUE THREAD

**Issue by jbowm2** [Adldap2/Adldap2-Laravel#223]
Not sure if this is possible:

I have 700+ users that import when I run the adldap:import command. I would like to only import users associated with a specific group or groups.  When using the '-f' filter on the import command How can i see what options would be available to be filtered upon?

**Comment by stevebauman** [comment]
Hi @jbowm2,

> When using the '-f' filter on the import command How can i see what options would be available to be filtered upon?

What do you mean by "see what options are available to be filtered upon"? Would you perhaps be able to elaborate?

**Comment by jbowm2** [comment]
I am not entirely sure on which groups I need to import and would like to see what groups are available. Can I import all with associated group keys?

**Comment by stevebauman** [comment]
Unfortunately this isn't possible at the moment. You'll need to look on your AD server to verify the distinguished name of the group and then enter it in the filter option on the command:

```php
php artisan adldap:import --filter="(memberof=CN=YourGroup,OU=Users,DC=YourDomain,DC=com)"
```

This will import all users that are members of the group: `YourGroup`.

**Comment by jbowm2** [comment]
Thank you @stevebauman 

I wasn't sure what capabilities I would have without having direct access to the AD server to verify the distinguished name. 

Thanks, again

**Comment by stevebauman** [comment]
No problem! You've given me an idea though. I'm implementing the ability to list users to be imported before the import takes place, and also give the ability to cancel the import afterwards :).

**Comment by stevebauman** [comment]
Added:

https://github.com/Adldap2/Adldap2-Laravel/commit/834dee922600d6733ee915cbfee0a4397ab584b2

**Comment by jbowm2** [comment]
@stevebauman 

I'm sure its an error on my end, but I had my IT dept make a new group to corral the users I need to import called "Sales" i added the filter to the adldap:import like you suggested above and added memberof=CN=Sales and the correct DC domain. returns 0 users?

**Comment by stevebauman** [comment]
Are you sure you have the correct distinguished name of the group and it isn't contained in any OU or anything?

**Comment by stevebauman** [comment]
Since you're referring to your IT Dept, I'm assuming you're in an enterprise environment. They'll most likely be storing that group inside an OU of some sort.

**Comment by jbowm2** [comment]
would the OU be Sales?

**Comment by stevebauman** [comment]
No, if it's a group, it would be named regularly like any other object. Usually these groups are contained in OU's (Organizational Units) in Active Directory. So it's distinguished name would be:

```
cn=Sales,ou=User Groups,dc=corp,dc=acme,dc=org
```

If you have connectivity to your AD server already, you can easily query for this group in your routes file and then visiting your dev site:

```php
use Adldap\Laravel\Facades\Adldap;

Route::get('/', function () {

    $group = Adldap::search()->groups()->find('Sales');

    dd($group->getDn());

});
```

**Comment by jbowm2** [comment]
@stevebauman 

That is amazing!!! Users Imported everything looks Correct

**Comment by stevebauman** [comment]
Haha glad you've found it useful!

If you encounter any further issues or need any help, definitely create an issue and I'll be able to assist.
