### ISSUE TITLE
Can't login with the form

### ISSUE THREAD

**Issue by broodstare** [Adldap2/Adldap2-Laravel#225]
Hi, first I want to thank @stevebauman creating such a great package, however i'm facing some question here, I wish someone could help me how to figure out. I'm not a native English speaker, so please correct me if i have wrong :)

I'm developing a web service (like classroom registration) which needs to authenticate whether user is in AD server. After authenticating, the user is able to use the service.

I have followed the **quick-start.md**, and now I'm able to authenticate user by `Adldap::auth()->attempt($username, $password)` and `Adldap::search()->users()->find('john doe');`, it all works!

However, the thing that quite confusing me is: then I'm trying to use form (which is generated by `make:auth`) to let user login the service, but it's fail. The error message tells that 

> 3/3
> QueryException in Connection.php line 769:
> could not find driver (SQL: select top 1 * from [] where ([username] = balala...))

> 3/2
> PDOException in PDOConnection.php line 47:
> could not find driver

> 3/1
> PDOException in PDOConnection.php line 43:
> could not find driver

Is it so weird? Why Adldap tries to query user in other database used for other things instead to query AD server? I'm sure setting `domain_controller` to the right IP, and `driver` to `adldap`.

Also, the second thing confusing me is: does we still use original Laravel auth controller and middleware, then combining with Adldap? I mean, is Adldap an extension to original Laravel auth? Or, should I create new controller and middleware that handle Adldap authentication?

**Comment by stevebauman** [comment]
Hi @broodstare,

> Is it so weird? Why Adldap tries to query user in other database used for other things instead to query AD server? I'm sure setting domain_controller to the right IP, and driver to adldap.

This is because Adldap creates a local user on your app to authenticate against once it has found a user on your AD server and authenticated against it. This is the main purpose of the current auth driver.

Judging by your exceptions, you don't have a local app database?

> Also, the second thing confusing me is: does we still use original Laravel auth controller and middleware, then combining with Adldap? I mean, is Adldap an extension to original Laravel auth? Or, should I create new controller and middleware that handle Adldap authentication?

You can continue to use laravel's auth controller and middleware. They are 100% compatible with the `adldap` auth driver.

**Comment by broodstare** [comment]
Thanks for @stevebauman replying!! :D 

You're right, i don't have a local app database, because I only want to authenticate user through Adladp without creating a local user. Is it able to do that?

> You can continue to use laravel's auth controller and middleware. They are 100% compatible with the adldap auth driver.
> Did you happen to read the included docs?: https://github.com/Adldap2/Adldap2-Laravel#auth-driver

Yes, i did, maybe i should re-think about the part you mention. I feels like i'm not totally understand the part of **Auth Driver**. One more question, 

```
public function login(Request $request)
{
    if (Auth::attempt($request->only(['email', 'password'])) {
        $user = Auth::user();
        return redirect()->to('home')
            ->withMessage('Logged in!');
    }
    return redirect()->to('login')
        ->withMessage('Hmm... Your username or password is incorrect');
}
```
Does this section of codes means I need to modify the login method in original Laravel AuthenticateUsers.php, or I need to create this method (to where?) Thanks for replying again!

**Comment by stevebauman** [comment]
Hi @broodstare, no problem at all! I'm glad to help :).

> You're right, i don't have a local app database, because I only want to authenticate user through Adladp without creating a local user. Is it able to do that?

This was a large requested feature and it's actually implemented, but hasn't been released yet.

If you instead require `"adldap2/adldap2-laravel": "dev-master",` you can use the new configuration option `provider` in your `config/adldap_auth.php` file:

https://github.com/Adldap2/Adldap2-Laravel#auth-providers

**Comment by stevebauman** [comment]
> Does this section of codes means I need to modify the login method in original Laravel AuthenticateUsers.php, or I need to create this method (to where?) Thanks for replying again!

Also, nope you don't need to change a thing with your current code.

**Comment by broodstare** [comment]
> Also, nope you don't need to change a thing with your current code.
So, you means this section of code is custom? Like i should create a middleware and put this part in it? Sorry if i mistake your meaning.

**Comment by stevebauman** [comment]
> So, you means this section of code is custom? Like i should create a middleware and put this part in it? Sorry if i mistake your meaning.

No problem. I'm saying the default `AuthController.php` (or `LoginController.php` in Laravel 5.3) will work just fine, as well as the standard `auth` middleware.

**Comment by broodstare** [comment]
OK, I put the following code into `LoginController.php` (in Laravel 5.3):

```
public function login(Request $request)
{
    if (Auth::attempt($request->only(['email', 'password'])) {

        // Returns \App\User model configured in `config/auth.php`.
        $user = Auth::user();


        return redirect()->to('home')
            ->withMessage('Logged in!');
    }

    return redirect()->to('login')
        ->withMessage('Hmm... Your username or password is incorrect');
}
```

Will it conflict with the method login in trait `AuthenticatesUser.php`? Also, when I paste this code section into `LoginController.php`, it comes to some error. :(

**Comment by stevebauman** [comment]
> OK, I put the following code into LoginController.php (in Laravel 5.3):

You don't need to modify anything in the `LoginController` that ships with Laravel 5.3.

> Also, when I paste this code section into LoginController.php, it comes to some error. :(

What error are you receiving?

**Comment by broodstare** [comment]
Hi, @stevebauman  :D , now i have tried two options you said:

1. Try the dev-master

> If you instead require "adldap2/adldap2-laravel": "dev-master", you can use the new configuration option provider in your config/adldap_auth.php file:

I modified the `composer.json` as the below:

```
    "require": {
        "php": ">=5.6.4",
        "laravel/framework": "5.3.*",
        "adldap2/adldap2-laravel": "dev-master"
    },
```
after `composer update`, it shows:

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for adldap2/adldap2-laravel dev-master -> satisfiable by adldap2/adldap2-laravel[dev-master].
    - adldap2/adldap2-laravel dev-master requires adldap2/adldap2 dev-master 
-> satisfiable by adldap2/adldap2[dev-master] 
but these conflict with your requirements or minimum-stability.
```
how should I correct this problem? 

2. Logging in part

Sorry for i still confuse in this section, I have no idea how should I use this part of code. Please let me describe how i put and use, correcting me if wrong :D 
In **Logging In** section:
> Login a user regularly using ``Auth::attempt($credentials);``.
> Once a user is authenticated, retrieve them as you would regularly:
> ```
> public function login(Request $request)
> {
>    if (Auth::attempt($request->only(['email', 'password'])) {
>
>        // Returns \App\User model configured in config/auth.php.
>        $user = Auth::user();
> ... balabala```

then, so far as I know, the Login part of Laravel 5.3 is `LoginController.php` which contains `AuthenticatesUsers.php` trait:

**LoginController.php**
```
<?php

namespace App\Http\Controllers\Auth;

use App\Http\Controllers\Controller;
use Illuminate\Foundation\Auth\AuthenticatesUsers;

class LoginController extends Controller
{
    use AuthenticatesUsers;

    protected $redirectTo = '/home';

    public function __construct()
    {
        $this->middleware('guest', ['except' => 'logout']);
    }
}
```
what i do is just put **Loggin In** part into `LoginController.php`, as below:

```
<?php

namespace App\Http\Controllers\Auth;

use App\Http\Controllers\Controller;
use Illuminate\Foundation\Auth\AuthenticatesUsers;

class LoginController extends Controller
{
    use AuthenticatesUsers;

    protected $redirectTo = '/home';

    public function __construct()
    {
        $this->middleware('guest', ['except' => 'logout']);
    }

    public function login(Request $request)
    {
        if (Auth::attempt($request->only(['email', 'password'])) {
            // Returns \App\User model configured in `config/auth.php`.
        $user = Auth::user();


        return redirect()->to('home')
            ->withMessage('Logged in!');
    }

        return redirect()->to('login')
            ->withMessage('Hmm... Your username or password is incorrect');
    }
}
```

then, the error shows:
>1/1
>FatalErrorException in LoginController.php line 42:
>syntax error, unexpected '{'

I have noticed that @stevebauman you said I don't need to modify anything. Does this mean that I can ignore **Logging In** part, just using the original `Login method` in `AuthenticateUsers.php` (like below), and it'll work?

```
    /**
     * Handle a login request to the application.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function login(Request $request)
    {
        $this->validateLogin($request);

        // If the class is using the ThrottlesLogins trait, we can automatically throttle
        // the login attempts for this application. We'll key this by the username and
        // the IP address of the client making these requests into this application.
        if ($this->hasTooManyLoginAttempts($request)) {
            $this->fireLockoutEvent($request);

            return $this->sendLockoutResponse($request);
        }

        if ($this->attemptLogin($request)) {
            return $this->sendLoginResponse($request);
        }

        // If the login attempt was unsuccessful we will increment the number of attempts
        // to login and redirect the user back to the login form. Of course, when this
        // user surpasses their maximum number of attempts they will get locked out.
        $this->incrementLoginAttempts($request);

        return $this->sendFailedLoginResponse($request);
    }
```

**Comment by broodstare** [comment]
After trying [Quick Start - From Scratch](https://github.com/Adldap2/Adldap2-Laravel/blob/master/quick-start.md) again, this time I do not pass establishing localhost database to store user data, and it all work!! Like @stevebauman said before: You don't need to modify any original `LoginController.php` code, Adldap2-Laravel is well match original Laravel Auth!! Oh god, how thankful to this great package!

If anyone is new as me, I really suggest you should try **Qucik Start** at first without any custom trying. I think the remaining problem that I face is how to login without saving locally, and I know it's coming soon which lets me so exciting! But as I asked before, setting `"adldap2\adldap2-laravel": "dev-master"` happens some problem? Does @stevebauman have any suggestion of this? Deeply thanks again! : )

**Comment by stevebauman** [comment]
Hi @broodstare, glad you've resolved the issues! Thanks for your kind words :).

This is due to composer and your stability settings.

In your `composer.json` file, insert this into the root:

```json
"minimum-stability": "dev"
```

For an example, here's the default `composer.json` that comes with Laravel:

```json
{
    "name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "type": "project",
    "require": {
        "php": ">=5.6.4",
        "laravel/framework": "5.3.*"
    },
    "require-dev": {
        "fzaninotto/faker": "~1.4",
        "mockery/mockery": "0.9.*",
        "phpunit/phpunit": "~5.0",
        "symfony/css-selector": "3.1.*",
        "symfony/dom-crawler": "3.1.*"
    },
    "autoload": {
        "classmap": [
            "database"
        ],
        "psr-4": {
            "App\\": "app/"
        }
    },
    "autoload-dev": {
        "classmap": [
            "tests/TestCase.php"
        ]
    },
    "scripts": {
        "post-root-package-install": [
            "php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "php artisan key:generate"
        ],
        "post-install-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postInstall",
            "php artisan optimize"
        ],
        "post-update-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postUpdate",
            "php artisan optimize"
        ]
    },
    "config": {
        "preferred-install": "dist"
    },
    "minimum-stability": "dev" // Inserted here.
}

```
