### ISSUE TITLE
Access users within a CN group?

### ISSUE THREAD

**Issue by shawndibble** [Adldap2/Adldap2-Laravel#23]
I have a base_dn that I have been given, however instead of being your usual `'base_dn' => 'OU=Users,DC=Company,DC=local'`, I also have a cn in the base_dn as our IT sets up security groups like that. Unfortunately when I use `'base_dn' => 'CN=Group,OU=Users,DC=Company,DC=local'`, I am unable to authenticate, in fact I don't even think it is able to pick up my user account. 

Is there a way to utilize the CN with the base_dn and grab the users inside?

**Comment by stevebauman** [comment]
The base DN is passed directly to PHP's `ldap_search()` method. Are you able to receive any results from this group when you set it as the base DN? Try:

```php
$dn = 'CN=Group,OU=Users,DC=Company,DC=local';

$results = \Adldap::search()->setDn($dn)->get();

dd($results);
```

**Comment by shawndibble** [comment]
All I get back is false. Even if I set the $dn string to something that works in the 'base_dn' field of the adldap.php file.

**Comment by stevebauman** [comment]
Are you using a domain Administrator account for the connection?

**Comment by shawndibble** [comment]
Yes, I am. I ended up just using a more general OU connection and then manually managed the users I wanted via PHP.

**Comment by eleftrik** [comment]
I have a similar problem. I want to enable only Active Directory users belonging to a specific group.

If I try

```PHP
    $dn = 'CN=Users,DC=my,DC=domain';
    $results = \Adldap::search()->setDn($dn)->where('objectClass', '=', 'person')->get();
    dd($results);
```

I get a Collection with items. But If I run 

```PHP
    $dn = 'memberOf=CN=myGroup,CN=Users,DC=my,DC=domain';
    $results = \Adldap::search()->setDn($dn)->where('objectClass', '=', 'person')->get();
    dd($results);
```

I get a Collection with no items.

I also would like to set 'limitation_filter' in adldap_auth.php, but I can't figure out what value to use.

Thank you

**Comment by stevebauman** [comment]
Hi @eleftrik, try running a raw filter for retrieving all entries in a particular group:

```php
$results = \Adldap::search()
        ->rawFilter('(memberof:1.2.840.113556.1.4.1941:=CN=MyGroup,DC=example,DC=com)')
        ->get();
```

**Comment by eleftrik** [comment]
Hi @stevebauman, thanks for your reply.
Ok, with `rawFilter()` it works perfectly:

```PHP
    $results = \Adldap::search()
        ->rawFilter('(memberOf=CN=myGroup,CN=Users,DC=my,DC=domain)')
        ->get();
```

Pardon my ignorance, but what are the numbers (1.2.840.113556.1.4.1941) in your rawFilter example?

Thanks for solving my problem.

**Comment by stevebauman** [comment]
That's great that it works for you!

The OID (`1.2.840.113556.1.4.1941`) tells the search that you want all entries inside that group, **as well as nested groups**. So for example, if you had an `Office` group that contained `Accounting` and `Marketing` groups, it would grab all entries in the `Office` group, then grab all entries in each `Marketing` and `Accounting` groups.
