### ISSUE TITLE
howto: Multiple Authentication Connections

### ISSUE THREAD

**Issue by f0nt4** [Adldap2/Adldap2-Laravel#230]
I'm using Laravel 5.3 and would like to use the multiple connections so I can authenticate users to different domains.
I already made the second connection, but how should i utillize it?

**Comment by stevebauman** [comment]
Hi @f0nt4, this may be tricky since by default we only support authenticating against one connection:

https://github.com/Adldap2/Adldap2-Laravel/blob/master/src/Config/auth.php#L5-L18

You could try authenticating against the first domain, and if that fails, change your configured default connection at run-time and try re-authenticating?

For example:

```php
public function login(Request $request)
{
    $connections = config('adldap.connections');

    foreach($connections as $connection => $config) {
        config(['adldap.auth.connection' => $config]);

        if (Auth::attempt($request->only('email', 'password'))) {
            return redirect()->to('home')->withMessage("You're logged in!");
        }
    }

    return redirect()->to('login')->withMessage("Looks like your credentials are incorrect.");
}
```

**Comment by f0nt4** [comment]
@stevebauman Thanks! But can I just past this in the logincontroller?
I'm using the built-in authentication of Laravel 5.3 at the moment.
What I'm searching for is, how I use this: https://github.com/Adldap2/Adldap2-Laravel#multiple-authentication-connections in Laravel 5.3.

**Comment by stevebauman** [comment]
Hi @f0nt4,

> Thanks! But can I just past this in the logincontroller?

No, you'll need to override the `login()` method on the built in laravel controller for authenticating.

**Comment by stevebauman** [comment]
It depends on which laravel version you're using, but if you're using the most current version, you can actually just override the `attemptLogin()` method instead:

**Stock Laravel attemptLogin Method:**
```php
/**
 * Attempt to log the user into the application.
 *
 * @param  \Illuminate\Http\Request  $request
 * @return bool
 */
protected function attemptLogin(Request $request)
{
    return $this->guard()->attempt(
        $this->credentials($request), $request->has('remember')
    );
}
```

```
/**
 * Attempt to log the user into the application.
 *
 * @param  \Illuminate\Http\Request  $request
 * @return bool
 */
protected function attemptLogin(Request $request)
{
    $authenticated = false;

    $credentials = $this->credentials($request);

    if($this->guard()->attempt($credentials,  $request->has('remember'))) {
        $authenticated = true;
    } else {
        // Login failed, swap and try other connection.
        Config::set('adldap_auth.connection', 'other-connection');

        if($this->guard()->attempt($credentials,  $request->has('remember'))) {
            $authenticated = true;
        }
    }

    if ($authenticated === true ) {
        return redirect()->to('dashboard');
    }

    return redirect()->to('login')->withMessage('Credentials are incorrect.');
}
```

**Comment by ZaeemFarooqui** [comment]
Hello Steve,
Can I still follow this procedure to authenticate user over multiple domains or is there any alternative? 

> It depends on which laravel version you're using, but if you're using the most current version, you can actually just override the attemptLogin() method instead inside your Http/Controllers/Auth/LoginController.php:
> 
> Stock Laravel attemptLogin Method:
> 
> /**
>  * Attempt to log the user into the application.
>  *
>  * @param  \Illuminate\Http\Request  $request
>  * @return bool
>  */
> protected function attemptLogin(Request $request)
> {
>     return $this->guard()->attempt(
>         $this->credentials($request), $request->has('remember')
>     );
> }
> Overridden Laravel attemptLogin method:
> 
> /**
>  * Attempt to log the user into the application.
>  *
>  * @param  \Illuminate\Http\Request  $request
>  * @return bool
>  */
> protected function attemptLogin(Request $request)
> {
>     $authenticated = false;
> 
>     $credentials = $this->credentials($request);
> 
>     if($this->guard()->attempt($credentials,  $request->has('remember'))) {
>         $authenticated = true;
>     } else {
>         // Login failed, swap and try other connection.
>         Config::set('adldap_auth.connection', 'other-connection');
> 
>         if($this->guard()->attempt($credentials,  $request->has('remember'))) {
>             $authenticated = true;
>         }
>     }
> 
>     if ($authenticated === true ) {
>         return redirect()->to('dashboard');
>     }
> 
>     return redirect()->to('login')->withMessage('Credentials are incorrect.');
> }
