### ISSUE TITLE
Authenticate with multiple OUs

### ISSUE THREAD

**Issue by ArabAgile** [Adldap2/Adldap2-Laravel#231]
I have this in base_dn previously:

`OU=Staff,DC=acme,DC=com`

Now I need to limit to either Staff or Manager OUs

I tried this but it's not working

`OU=Staff,OU=Manager,DC=acme,DC=com`

So please advice!

**Comment by stevebauman** [comment]
Hi @ArabAgile, you can't limit with two OU's. See:

http://stackoverflow.com/questions/9184978/ldap-root-query-syntax-to-search-more-than-one-specific-ou

You'll need to create a Group and then add the users you'd like to the specified group.

This way you can enter the group inside the `limitation_filter` option, which would only allow users from that specific group to authenticate:

```php
'limitation_filter' => '(memberOf=cn=Allowed,dc=acme,dc=com)',
```
