### ISSUE TITLE
I can import users from AD but login failed

### ISSUE THREAD

**Issue by scorlink** [Adldap2/Adldap2-Laravel#233]
Hello and happy new year,

First, thank you for this plugin more than useful.

I think the title summarizes my problem. I can connect to AD via ADLDAP, I'm able to import users who are in a specific group to my database. but the login does not work !! "These credentials do not match our records."

in Route.php : 
dd(Adldap::auth()->attempt('user', 'pass')); ==> false
dd(Adldap::search()->where('cn', '=', 'My Name')->get()); ==> retreive the user requested.

thank you for your help.

**Comment by scorlink** [comment]
when I set 'account_prefix' to empty string and put dd(Adldap::auth()->attempt('DOMAINE\user', 'pass')); in Route.php, it returns true, but still don't login.

**Comment by stevebauman** [comment]
Hi @scorlink,

You're authenticating with the wrong method. `Adldap::auth()->attempt()` performs authentication directly against your domain controller, and that's it. Basically, it just says `true / false` if your credentials are valid. It won't authenticate you in your Laravel application.

That's what the auth driver is for: https://github.com/Adldap2/Adldap2-Laravel#auth-driver

Did you implement the auth driver by following the included docs?

If so, I can definitely assist you in troubleshooting.

**Comment by scorlink** [comment]
Hi @stevebauman,
Thanks for your answer. indeed I'm authenticating with the auth driver as described in your docs.
I use `Adldap::auth()->attempt()` only for troubleshooting.
I already fixed my issue by adding `\\` after the account_prefix in adldap.php.
thanks once again for this plugin and your fast assistance 👍

**Comment by stevebauman** [comment]
Great to hear! No problem at all :).
