### ISSUE TITLE
Login if user is active

### ISSUE THREAD

**Issue by scorlink** [Adldap2/Adldap2-Laravel#234]
Hi @stevebauman,

Normally, to connect with a third credential besides the username and the pass ('active = true' for my case), we must override the method 'getcredentials' to add another one.
Now, with adldap, its method 'attempt' does not allow to add another credential.
Must i edit the AdLdap source code to do this? Is there any other method?

Also, how to verify that username exists in database before binding AD?

Thank you :-)

**Comment by scorlink** [comment]
Hi @stevebauman,

I fixed the problem by overriding login method as below:

```
public function login(Request $request)
    {
        $this->validateLogin($request);

        $throttles = $this->isUsingThrottlesLoginsTrait();

        if ($throttles && $lockedOut = $this->hasTooManyLoginAttempts($request)) {
            $this->fireLockoutEvent($request);

            return $this->sendLockoutResponse($request);
        }

        $credentials = $this->getCredentials($request);
        $user = User::whereUsername($request->username)->first();

        if($user->actif){
            if ($user instanceof \App\User && Auth::guard($this->getGuard())->attempt($credentials, $request->has('remember'))) {

                  return $this->handleUserWasAuthenticated($request, $throttles);
            }
        }

        if ($throttles && ! $lockedOut) {
            $this->incrementLoginAttempts($request);
        }

        return $this->sendFailedLoginResponse($request);
    }
```
Do you think that this is a good solution?

**Comment by stevebauman** [comment]
Hi @scorlink,

You could actually perform this in reverse if you rely on a `active` user property on your model:

```php
public function login(Request $request)
{
    $credentials = $this->getCredentials($request);

    if (Auth::attempt($credentials) && Auth::user()->active) {
        return redirect()->to('home')->with('message', 'Successfully logged in!');
    }

    return $this->sendFailedLoginResponse($request);
}
```

**Comment by stevebauman** [comment]
Since a successful `Auth::attempt()` sets the current user, we can immediately access it on the same `if` statement. You may even be able to do this:

```php
public function login(Request $request)
{
    $credentials = $this->getCredentials($request);

    if (Auth::once($credentials) && Auth::user()->active) {
        Auth::login(Auth::user());

        return redirect()->to('home')->with('message', 'Successfully logged in!');
    }

    return $this->sendFailedLoginResponse($request);
}
```

**Comment by stevebauman** [comment]
Just another addition, if you rely an AD attribute (such as an enabled user), then you can utilize the `adldap_auth.php` config option named `limitation_filter`. However if you're relying on eloquent model attributes, then this would be difficult to implement into Adldap2-Laravel, and would cause confusion between other config options.

**Comment by scorlink** [comment]
Hi @stevebauman,

The purpose of adding this option is to not grant the right to an AD Administrator who is not an Administrator of the application to connect to it.

So the active field exists in the local database.

Except that, I find that my code is better since it does not launch an attempt to the AD if the user is not activated in the application's database.

don't you think so?

**Comment by stevebauman** [comment]
> Except that, I find that my code is better since it does not launch an attempt to the AD if the user is not activated in the application's database.

Yes absolutely, if that's the way you'd like it to work then your code is fine.

**Comment by scorlink** [comment]
To clear any misunderstanding, I mean it works better for my situation since a newly added user in Active Directory (or added to the group) needs to go through validation first before he can access the application. and this validation is done locally in the application database.
Anyway, thanks for your help, I appreciate it :-)
