### ISSUE TITLE
inGroup() error

### ISSUE THREAD

**Issue by randyrankin** [Adldap2/Adldap2-Laravel#235]
When testing the following on a new project I receive this error: ```Call to a member function inGroup() on null```

```
@if (Auth::check())

  <p>You're logged in!</p>

   @if (Auth::user()->adldapUser->inGroup('Intranet-Users'))

     <p>You're also in the Intranet Users AD group!</p>

    @endif

@else

   You're not logged in.

@endif
```

**Comment by stevebauman** [comment]
Hi, do you have the config option `bind_user_to_model` enabled, as well as the trait inserted on your `User` model?

**Comment by randyrankin** [comment]
lol, I didn't have the ```bind_user_to_model``` option set to to true. It's working now. 

I use this repo in another project and it works perfectly. I compared this project to that one trying to figure out the issue but I missed that option. I feel rather silly right now. Thanks @stevebauman for such a quick reply!

**Comment by stevebauman** [comment]
No problem! Glad you've resolved it :).
