### ISSUE TITLE
How To:  Add additional data into Users after authentication for first time

### ISSUE THREAD

**Issue by cisvpn-sai** [Adldap2/Adldap2-Laravel#236]
Hi Steve,  Sorry this isn't an issue as your code is working beautifully.  Hope you had a good holiday season.  

I have a question though on how to do something.  While I understand I shouldn't make any changes to your code because any updates will overwrite.  I am inquiring about whats the best way to tap into the moment where a user has just finished authenticating with ADLDAP and your code is about to write the AD retrieved data into the local DB.  At this point I would like to pull additional data from a different server and plug in more data into the USER table in local database. 

Is it possible to tap into your code here by overriding something without changing your code?  Also where in your code is this happening?

**Comment by stevebauman** [comment]
HI @cisvpn-sai, no problem at all! Thanks for the question.

You can sync more columns in your local database by adding the column into the `sync_attributes` config option:

https://github.com/Adldap2/Adldap2-Laravel#sync-attribute-callbacks

>  Also where in your code is this happening?

This depends on which version you're using. If you're using `dev-master`, it's located in the `ImportsUsers` trait:

https://github.com/Adldap2/Adldap2-Laravel/blob/master/src/Traits/ImportsUsers.php#L36

https://github.com/Adldap2/Adldap2-Laravel/blob/master/src/Traits/ImportsUsers.php#L93-L112

If you need any further assistance getting this set up, let me know!

**Comment by cisvpn-sai** [comment]
Thank you again Steve.  Got it working.
