### ISSUE TITLE
ADLdap delete entry 

### ISSUE THREAD

**Issue by simonvolk** [Adldap2/Adldap2-Laravel#237]
Hi

i am building a project with Laravel that includes OpenLadp. I know that Adldap is designed to work with AD anyway in my case i am trying to make it work with openldap.
I am already able to create new contact in the database the problem is i cannot delete it.
 Creation procedure works fine with little modification in Ldap.php

$user = Adldap::make()->user([
                 'cn' => $cn,
                ]);
$user->save();

For deletion procedure i tried two approaches: 

 1.) find the user and than i use the
$user = Adldap::search()->whereEquals('cn', $cn)->get();
 $user->delete() function.  >>**Error:  "Method delete does not exist."**

 2.) find the user
$user = Adldap::search()->whereEquals('cn', $cn)->get();
 $ad = new Adldap($configuration);
 $deleted = $ad->user()->delete($cn);  >**> Error: "Call to undefined method Adldap\Laravel\Facades\Adldap::user()"**

I can't find a way out any help will be appreciated.

thx

**Comment by stevebauman** [comment]
Hi @simonvolk,

When you call `get()` you're actually receiving a collection of results, not a single result.

You need to call `first()` instead of `get()` to receive a since result:

```php
$user = Adldap::search()->whereEquals('cn', $cn)->first();

$user->delete();
``

**Comment by simonvolk** [comment]
Hi stevebauman,

using first() it works, 

thx
