### ISSUE TITLE
restore() disabeled UserAccounts - in reference to #183

### ISSUE THREAD

**Issue by MatthiasHertel** [Adldap2/Adldap2-Laravel#239]
hi steve,

in #183 u implemented a softDeletes() for disabled ad-users ... that is really cool and works like a charme - thank u for that.

**my question is:**
is there a "revert" , i mean a restore() function for reenabling users ?

the eloquent operation  is `restore()` 
https://laravel.com/docs/5.3/eloquent#soft-deleting

**the situation:**

i have many accounts on my ad which are disabled ... and so in my users table of my app softdeleted ... now when i re enable an account on my ad - i want to restore() the soft-deleted users in my app.

best regards
matthias

**Comment by stevebauman** [comment]
Hi @MatthiasHertel,

Definitely agree, this should be an option.

Going to built this in now. Thanks!
