### ISSUE TITLE
can't login using ldap

### ISSUE THREAD

**Issue by ram536** [Adldap2/Adldap2-Laravel#240]
hi Steve,
 i have followed all the steps and try to login but i can't login .but the credentials i have provided is write.
do you have an idea where this might goes wrong.

thanks

**Comment by stevebauman** [comment]
Hi @ram536,

I need a lot more information to assist you with your issue.

- Do you have connectivity to your LDAP server?
- Which steps did you follow? Did you configure the auth driver correctly?
- Do you receive any errors / exceptions when you try to authenticate?

**Comment by ram536** [comment]
Hi @stevebauman 

 i have followed Adldap2-Laravel steps after following all the steps and try to login its says the credentials 
do not match our records.

thanks

**Comment by ram536** [comment]
hi @stevebauman  i have done the follwing steps

1. freshly installed laravel.

2. next php artisan make:auth

3. place this code in logincontroller
 public function username()
	{
   		 return 'username';
	}
4. Insert Adldap2-Laravel into my composer.json file:

"adldap2/adldap2-laravel": "2.1.*" an upadated composer


5.next php artisan vendor:publish --tag="adldap"

6. i have set the vales in adldap.php and adldap_auth.php

7. i tried to connect but its not going through even though i have entered credentials right.

8. after that i have perform this in my web.php

  $users = Adldap::getProvider('default')->search()->users()->get();

  dd($users);   //it returns a list of values.

9.$user = Adldap::search()->users()->find('john doe');
 it provides the vales of user
10. $search = Adldap::search()->where('cn', '=', 'XXXXX')->get();
     when i perfomed this i got this time empty array


can you please help me where it goes wrong.

**Comment by kimluther18** [comment]
Hi, where can I find the adldap_auth.php and adldap.php?

I followed the steps til' -- > 5.next php artisan vendor:publish --tag="adldap"

then what's next?

Thanks!!

**Comment by kimluther18** [comment]
And when I execute the command: composer update

this one will appear in cmd

[Symfony\Component\Debug\Exception\FatalThrowableError]
  Class 'Laravel\Tinker\TinkerServiceProvider' not found

Please help! Thanks!

**Comment by aankittcoolest** [comment]
I also can't login using LDAP.
I am really novice with LDAP, so please forgvie me if I missed something.

I tried to test against username.
I followed the steps listed on the following link.
https://github.com/Adldap2/Adldap2-Laravel/blob/master/docs/quick-start.md 

The credentials which I tested with are 
username: riemann
password: password

Server Against which I tested is : 
http://www.forumsys.com/tutorials/integration-how-to/ldap/online-ldap-test-server/ 

Here are my config files (Removed comments to reduce the size of comment)

<pre>

<?php

return [
    'connections' => [

        'default' => [
            'auto_connect' => true,
            'connection' => Adldap\Connections\Ldap::class,
            'schema' => Adldap\Schemas\ActiveDirectory::class,
            'connection_settings' => [
                'account_prefix' => env('ADLDAP_ACCOUNT_PREFIX', ''),
                'account_suffix' => env('ADLDAP_ACCOUNT_SUFFIX', '@example.com'),//changed
                'domain_controllers' => explode(' ', env('ADLDAP_CONTROLLERS', 'ldap.forumsys.com')),//changed
                'port' => env('ADLDAP_PORT', 389),
                'timeout' => env('ADLDAP_TIMEOUT', 5),
                'base_dn' => env('ADLDAP_BASEDN', 'cn=read-only-admin,dc=example,dc=com'),//changed
                'admin_account_suffix' => env('ADLDAP_ADMIN_ACCOUNT_SUFFIX', '@example.com'),//changed
                'admin_username' => env('ADLDAP_ADMIN_USERNAME', ''),
                'admin_password' => env('ADLDAP_ADMIN_PASSWORD', ''),
                'follow_referrals' => false,
                'use_ssl' => false,
                'use_tls' => false,
            ],

        ],

    ],

];
</pre>

<pre>

<?php

<?php

return [
    'connection' => env('ADLDAP_CONNECTION', 'default'),

    'provider' => Adldap\Laravel\Auth\DatabaseUserProvider::class,
    'resolver' => Adldap\Laravel\Auth\Resolver::class,
    'importer' => Adldap\Laravel\Auth\Importer::class,
    'rules' => [
        Adldap\Laravel\Validation\Rules\DenyTrashed::class,
    ],
    'scopes' => [
        Adldap\Laravel\Scopes\UpnScope::class,
    ],
    'usernames' => [
        'ldap' => 'samaccountname',
        'eloquent' => 'username',//changed
    ],
    'login_fallback' => env('ADLDAP_LOGIN_FALLBACK', false),
    'password_sync' => env('ADLDAP_PASSWORD_SYNC', true),

    'windows_auth_attribute' => ['samaccountname' => 'AUTH_USER'],
    'sync_attributes' => [
        'username' => 'userprincipalname',
        'name' => 'cn',

    ],

];
</pre>


I am sure bind connection is getting successful, as I tried with different permutations.

**Comment by aankittcoolest** [comment]
I also tried to test the workings of server by writing a very basic raw PHP script
There things worked!

<pre>

$ldaphost = "ldap.forumsys.com";
$ldapport = 389;

$ds = ldap_connect($ldaphost, $ldapport) or die("Could not connect to $ldaphost");
ldap_set_option($ds, LDAP_OPT_PROTOCOL_VERSION, 3);
if ($ds) {
 $username = "";
 $upasswd = "password";

 //both connection work
 $binddn = "uid=riemann,cn=read-only-admin,dc=example,dc=com";
 $binddn = "uid=riemann,dc=example,dc=com";

 $ldapbind = ldap_bind($ds,$binddn, $upasswd);

 //check if ldap was sucessfull
 if ($ldapbind) {
   echo "LDAP bind successful...";

   //Test for enteries
   $ldap_base_dn = 'dc=example,dc=com';
   $result = ldap_search($ds, $ldap_base_dn, "sn=r*");

   $entries = ldap_get_entries($ds, $result);
   print_r($entries); //Got entries successfully

 }
 else {
    echo "LDAP bind failed...";
 }
}

 
</pre>

**Comment by stevebauman** [comment]
@ram536 

> 6. i have set the vales in adldap.php and adldap_auth.php
>
> 7. i tried to connect but its not going through even though i have entered credentials right.

You missed a step, did you change your auth driver in `config/auth.php` to `adldap`?

**Comment by stevebauman** [comment]
@aankittcoolest 

You'll need to use this configuration inside your `config/adldap.php` file:

```php
'base_dn' => 'dc=example,dc=com',
'domain_controllers' => ['ldap.forumsys.com'],

'admin_account_prefix' => 'cn=',
'admin_account_suffix' => ',dc=example,dc=com',

'admin_username' => 'read-only-admin',
'admin_password' => 'password',

'account_prefix' => 'uid=',
'account_suffix' => ',dc=example,dc=com',
```

**Comment by aankittcoolest** [comment]
@stevebauman : Thank you so so much for configuring it for me!
As expected things worked beautifully :+1: 

I am really naive with these LDAP thing!
These beginning commas in the following lines were kinda difficult to catch at first go

<pre>
'admin_account_suffix' => ',dc=example,dc=com',
'account_suffix' => ',dc=example,dc=com',
</pre>

Thanks a lot again!

**Comment by aankittcoolest** [comment]
@stevebauman 
Would you help me in confirming that whether the sample LDAP server that I provided 
can be used for login or not?
http://www.forumsys.com/tutorials/integration-how-to/ldap/online-ldap-test-server/

Because in adldap_auth.php has adldap_auth.usernames.ldap set as userprincipalname.
And that's why in Resolver.php byCredentials method is returning NULL.

**Comment by stevebauman** [comment]
@aankittcoolest No problem! Glad I can help :)

Since this test server is using OpenLDAP, you'll need to use usernames instead of email.

Replace `adldap_auth.usernames.ldap` with `uid` instead of `userprincipalname`.

However, this means you'll need to change the `database/migrations/2014_10_12_000000_create_users_table.php` schema to use `username` instead of `email`.

Please take a look at documentation here for further setup:

https://github.com/Adldap2/Adldap2-Laravel/blob/master/docs/auth/installation.md#usernames

**Comment by designvoid** [comment]
Hi there - I am having similar issues to previous poster - I have followed his lead of creating test script and can connect fine but I am struggling to port it to the config settings for this package...

	$ldaphost = "ldaps://ldap.institution.ac.uk";
	$ldapport = 636;

	$ds = ldap_connect($ldaphost, $ldapport) or die("Could not connect to $ldaphost");
	ldap_set_option($ds, LDAP_OPT_PROTOCOL_VERSION, 3);
	if ($ds) {
	 $username = "username@ad.institution.ac.uk";
	 $upasswd = "password";

	 $ldapbind = ldap_bind($ds,$username, $upasswd);

	 //check if ldap was sucessfull
	 if ($ldapbind) {
	   echo "LDAP bind successful...";

		// do some searching
		$fields = array('sn', 'givenname', 'mail');
		$filter = '';

		$filter = "userPrincipalName=" . $username;
		$filter = "(&(objectCategory=person)({$filter}))";

	   //Test for enteries
	   $ldap_base_dn = 'ou=institutionname,dc=ad,dc=institution,dc=ac,dc=uk';
	   $result = ldap_search($ds, $ldap_base_dn, $filter);

	   $entries = ldap_get_entries($ds, $result);
	   echo '<pre>';
	   print_r($entries); //Got entries successfully

	 }
	 else {
	    echo "LDAP bind failed...";
	 }
	}

**Comment by stevebauman** [comment]
@designvoid, here you go:

```php
'domain_controllers' => ['ldap.institution.ac.uk'],

'port' => 636,

'base_dn' => 'ou=institutionname,dc=ad,dc=institution,dc=ac,dc=uk',

'account_suffix' => '@ad.institution.ac.uk',

'admin_username' => 'username',
'admin_password' => 'password',
```

**Comment by designvoid** [comment]
Thanks for that but the username and password that I am using in the test script are what would I would be entering as a user, not a hard coded value... :(

This is what I have in my ENV file:

ADLDAP_CONTROLLERS= ldap.institution.ac.uk
ADLDAP_PORT=636
ADLDAP_BASEDN=ou= institutionname,dc=ad,dc= institution,dc=ac,dc=uk
ADLDAP_ACCOUNT_SUFFIX=@ad.institution.ac.uk

**Comment by stevebauman** [comment]
> Thanks for that but the username and password that I am using in the test script are what would I would be entering as a user, not a hard coded value... :(

A username and password is required for the `adldap` auth driver.

Your `env` configuration looks good, but like mentioned above, you'll need a username and password. You can insert it into your `env`:

ADLDAP_ADMIN_USERNAME=username
ADLDAP_ADMIN_PASSWORD=password

This account does not need to be a domain administrator, but this is how the auth driver works.

It first binds to your server as your configured admin account, then it searches for the user authenticating, authenticates the user against your LDAP server, then imports the user if they successfully bind.

**Comment by designvoid** [comment]
Ahh, this may be the issue then as I don't have a'default' username/password :(

**Comment by stevebauman** [comment]
Unfortunately you'll need it. This is how many applications that implement LDAP authentication work.

For example Atlassian's JIRA (creators of BitBucket) requires you to enter in a username and password to authenticate to your server to setup LDAP authentication.

**Comment by designvoid** [comment]
Ok, no worries! Thanks for your help!

**Comment by stevebauman** [comment]
No problem :).

**Comment by designvoid** [comment]
ooh! Interesting! I have just dug out the following details:

	ADLDAP_ADMIN_USERNAME=CN=ldap_web
	ADLDAP_ADMIN_PASSWORD=#######
	ADLDAP_ADMIN_ACCOUNT_SUFFIX=",OU=Service Accounts,DC=ad,DC=institution,DC=ac,DC=uk"

And I now get +exists: true from :

	$user = \Adldap\Laravel\Facades\Adldap::search()->users()->findBy('userprincipalname', 'username@ad.institution.ac.uk');
	dd($user);

But

	Auth::attempt(['username' => 'username', 'password' => '######']);

Still fails...?

**Comment by designvoid** [comment]
In addition I can also run:

````php artisan adldap:import --filter "(cn=#######)"

using my username in place of ###### and it finds a record and shows the info and asks if I want to import but nothing is ever imported...

**Comment by designvoid** [comment]
OK so I figured the importer out, was some misconfiguration in my User model.
So I can now import users aok but still no joy logging in! :(

**Comment by JerWegener** [comment]
I also have a similar problem.   I can go by command line and do a search for a user, I can then import that user... (php artisan adldap:import some.dude).  That works perfect.  However, on the front I always get a "(1/1) BindException Can't contact LDAP server" when trying to log in.
When I do a
$user = \Adldap\Laravel\Facades\Adldap::search()->users()->findBy('samaccountname', 'some.dude'); 
dd($user);
in the routes/web.php I get the same error with the "Can't contact LDAP server.
Even stranger is I'm using LDAP Browser with the same settings and can hit the server and view all people in on the AD.  
I am using use_ssl = True along with the addition of 
				'custom_options' => [
				// See: http://php.net/ldap_set_option
				LDAP_OPT_X_TLS_REQUIRE_CERT => LDAP_OPT_X_TLS_NEVER
				],
The addition of the custom_options was the key to making the command line search and import to work. But on the front, doing a log in there is no love.

**Comment by 3Descape** [comment]
I am now in the same possition as @aankittcoolest. The `Adldap::search()->where('uid', 'euler')->get()` works perfetly fine using the [Forumsys.com Server](http://www.forumsys.com/tutorials/integration-how-to/ldap/online-ldap-test-server/ testserver ),while on the other hand the login always fails, no mather of what settings I have. I do have set my form, migration and config and LoginController to use `username` and set the rest of the settings as follows:
This is the .env
`
ADLDAP_USERNAMES_LDAP=uid

ADLDAP_BASEDN=dc=example,dc=com
ADLDAP_CONTROLLERS=ldap.forumsys.com

ADLDAP_ADMIN_ACCOUNT_PREFIX=cn=
ADLDAP_ADMIN_USERNAME=read-only-admin
ADLDAP_ADMIN_PASSWORD=password
ADLDAP_ADMIN_ACCOUNT_SUFFIX=,dc=example,dc=com

ADLDAP_ACCOUNT_PREFIX=uid=
ADLDAP_ACCOUNT_SUFFIX=,dc=example,dc=com
`
adldap.php
`
<?php

return [
    'connections' => [

        'default' => [
            'auto_connect' => true,

            'connection' => Adldap\Connections\Ldap::class,

            'schema' => Adldap\Schemas\ActiveDirectory::class,

            'connection_settings' => [
                'account_prefix' => env('ADLDAP_ACCOUNT_PREFIX', ''),

                'admin_account_prefix' => env('ADLDAP_ADMIN_ACCOUNT_PREFIX', ''),

                'account_suffix' => env('ADLDAP_ACCOUNT_SUFFIX', ''),

                'domain_controllers' => explode(' ', env('ADLDAP_CONTROLLERS', 'corp-dc1.corp.acme.org corp-dc2.corp.acme.org')),

                'port' => env('ADLDAP_PORT', 389),

                'timeout' => env('ADLDAP_TIMEOUT', 5),

                'base_dn' => env('ADLDAP_BASEDN', 'dc=corp,dc=acme,dc=org'),

                'admin_account_suffix' => env('ADLDAP_ADMIN_ACCOUNT_SUFFIX', ''),

                'admin_username' => env('ADLDAP_ADMIN_USERNAME', 'username'),

                'admin_password' => env('ADLDAP_ADMIN_PASSWORD', 'password'),

                'follow_referrals' => false,

                'use_ssl' => false,

                'use_tls' => false,
            ],
        ],
    ],
];
`
and adldap_auth.php
`
<?php

return [
    'connection' => env('ADLDAP_CONNECTION', 'default'),

    'provider' => Adldap\Laravel\Auth\DatabaseUserProvider::class,

    'resolver' => Adldap\Laravel\Auth\Resolver::class,

    'importer' => Adldap\Laravel\Auth\Importer::class,

    'rules' => [
        Adldap\Laravel\Validation\Rules\DenyTrashed::class,
    ],

    'scopes' => [
        Adldap\Laravel\Scopes\UpnScope::class,
    ],

    'usernames' => [
        'ldap' => env('ADLDAP_USERNAMES_LDAP', 'uid'),

        'eloquent' => 'username',

    ],

    'login_fallback' => env('ADLDAP_LOGIN_FALLBACK', false),

    'password_sync' => env('ADLDAP_PASSWORD_SYNC', true),

    'windows_auth_attribute' => ['samaccountname' => 'AUTH_USER'],

    'sync_attributes' => [
        'username' => 'uid',
        'name' => 'cn',
    ],
];
`
I tried to debug the package a bit, but could't find the reason. Thank you very much already for helping me out..

**Comment by chinthakanm** [comment]
Hi,
I can query for LDAP server. But I can't use regular ldap authentication. It says invalid credentials. Can anyone help me.

**Comment by chinthakanm** [comment]
Hi steve,
I want to authenticate users using NoDatabaseUserProvider. but  I can't config it properly. Can you help me ?

**Comment by darroosh** [comment]
**### aasdfasfasdfas**
asfdasdfasfas

> sdfsdfsd
