### ISSUE TITLE
call_user_func_array() expects parameter 1 to be a valid callback, class 'Adldap\Connections\Provider' does not have a method 'authenticate'

### ISSUE THREAD

**Issue by ram536** [Adldap2/Adldap2-Laravel#242]
### Overview of the problem

This is about **Adldap2-Laravel**

 I'm using Laravel **version** [5.3] 

### Description
1. when i wrote following code and run i got this error 

$username = 'myusername';

$password = 'mypassword';

dd(Adldap::authenticate($username, $password));

error:$username = 'myusername';
$password = 'mypassword';

dd(Adldap::authenticate($username, $password));

Description of the bug, enhancement, or question 

call_user_func_array() expects parameter 1 to be a valid callback, class 'Adldap\Connections\Provider' does not have a method 'authenticate'

2. when i import user its says imported successfully and syn 0 users

 1/1 [============================] 100%
Successfully imported / synchronized 0 user(s).

can you help me with this

**Comment by stevebauman** [comment]
Hi @ram536, there is no method called `authenticate`.

You should call `Adldap::auth()->attempt($username, $password)`.
