### ISSUE TITLE
error please help in composer update command

### ISSUE THREAD

**Issue by kimluther18** [Adldap2/Adldap2-Laravel#245]
When I execute the command: composer update

this one will appear in cmd

C:\inetpub\testauth>composer update
Key require is a duplicate in ./composer.json at line 53
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files
> Illuminate\Foundation\ComposerScripts::postUpdate
> php artisan optimize

  [Symfony\Component\Debug\Exception\FatalThrowableError]
  Class 'Laravel\Tinker\TinkerServiceProvider' not found

Script php artisan optimize handling the post-update-cmd event returned with error code 1

----------------------------------------------------
Please help! Thanks!

**Comment by stevebauman** [comment]
Hi @kimluther18,

This is a Laravel issue.

Please read their upgrade guide from 5.3-5.4 in the Laravel Tinker section.

https://laravel.com/docs/5.4/upgrade#upgrade-5.4.0
