### ISSUE TITLE
laravel/tinker/.... not found

### ISSUE THREAD

**Issue by kimluther18** [Adldap2/Adldap2-Laravel#247]
I include this in the composer.json,

"require": {
        "adldap2/adldap2-laravel": "2.1.*"
    }

Then I ran the command, composer update, this one still appears,

C:\inetpub\testauth>composer update
Key require is a duplicate in ./composer.json at line 53
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 2 installs, 0 updates, 6 removals
  - Removing laravel/tinker (v1.0.0)
  - Removing psy/psysh (v0.8.1)
  - Removing nikic/php-parser (v3.0.2)
  - Removing dnoegel/php-xdg-base-dir (0.1)
  - Removing jakub-onderka/php-console-highlighter (v0.3.2)
  - Removing jakub-onderka/php-console-color (0.1)
  - Installing adldap2/adldap2 (v6.1.10) Loading from cache
  - Installing adldap2/adldap2-laravel (v2.1.3) Loading from cache
Writing lock file
Generating autoload files
> Illuminate\Foundation\ComposerScripts::postUpdate
> php artisan optimize

  [Symfony\Component\Debug\Exception\FatalThrowableError]
  Class 'Laravel\Tinker\TinkerServiceProvider' not found

Script php artisan optimize handling the post-update-cmd event returned with error code 1

----------------------------

Please help.
My Laravel Version is 5.4.*

**Comment by kimluther18** [comment]
And when I enter the command, composer require laravel/tinker, it gave me the result:

C:\inetpub\testauth>composer require laravel/tinker
Key require is a duplicate in ./composer.json at line 53
Using version ^1.0 for laravel/tinker
./composer.json has been updated
Key require is a duplicate in ./composer.json at line 53
Package "laravel/tinker" listed for update is not installed. Ignoring.
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files
> Illuminate\Foundation\ComposerScripts::postUpdate
> php artisan optimize


  [Symfony\Component\Debug\Exception\FatalThrowableError]
  Class 'Laravel\Tinker\TinkerServiceProvider' not found


Script php artisan optimize handling the post-update-cmd event returned with error code 1

Installation failed, reverting ./composer.json to its original content.

-------------------------------
Please help!

**Comment by stevebauman** [comment]
Hi @kimluther18,

According to your error, you have a duplicate `require` key on line 53 in your `composer.json` file:

> Key require is a duplicate in ./composer.json at line 53

Can you post your `composer.json` file?

This is still a laravel issue, but I will help you out.

**Comment by solokingjec** [comment]
Hello guys. Does anybody know the work around for this?

**Comment by SirJQ** [comment]
Hi.

In the "composer.json" file the "require adldap2/adldap2-laravel" is duplcate. delete the require adldap2 and execute "composer require adldap2/adldap2-laravel".

**Comment by sepvita** [comment]
I have the same problem:
 [Symfony\Component\Debug\Exception\FatalErrorException]
  Class 'Laravel\Tinker\TinkerServiceProvider' not found

Script php artisan optimize handling the post-update-cmd event returned with error code 255

here is my composer.json files:
`{
    "name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "type": "project",
    "require": {
        "php": ">=5.6.4",
        "laravel/framework": "5.4.*",
        "laravel/tinker": "^1.0"
    },
    "require-dev": {
        "fzaninotto/faker": "~1.4",
        "mockery/mockery": "0.9.*",
        "phpunit/phpunit": "~5.7"
    },
    "autoload": {
        "classmap": [
            "database"
        ],
        "psr-4": {
            "App\\": "app/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },

    "prefer-stable": true,
    "minimum-stability": "dev",
    "require": {
        "aimeos/aimeos-laravel": "~2016.10"
    },

    "scripts": {
        "post-root-package-install": [
            "php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "php artisan key:generate"
        ],
        "post-install-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postInstall",
            "php artisan optimize"
        ],
        "post-update-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postUpdate",
            "php artisan optimize",
            "php artisan vendor:publish --tag=public --force",
            "php artisan vendor:publish",
            "php artisan migrate"
        ]
    },
    "config": {
        "preferred-install": "dist",
        "sort-packages": true,
        "optimize-autoloader": true
    }
}
`

**Comment by 36864** [comment]
You have a duplicate `require` key.
>```
>"require": {
>    "aimeos/aimeos-laravel": "~2016.10"
>},
>```

There can only be one `require` key in the file. Put all the packages you require in the first `require` key and remove the second key.
I do wonder how you even got here considering you're not even using the adldap2-laravel package.
