### ISSUE TITLE
Unable to access User attributes

### ISSUE THREAD

**Issue by sc10n** [Adldap2/Adldap2-Laravel#249]
First off, thank you for the work on this package. 

I am not using this as an authentication mechanism, I am simply looking up a specific piece of data from AD and passing it along to another function. I can successfully pull the user I want with the following in a controller:

````
use Adldap;
use Adldap\Models\User;

protected $adldap;

    public static function adLookup($emNum)
    {
          $upn = $emNum.'@corp';

            $user = Adldap::search()->users()->select('mail')->where('userprincipalname', '=', $upn)->get();

            $email = $user->adldap->getEmail();
            
            self::searchUser($email);

    }
````
However, I am unable to access the ->getEmail(); attribute. Is there a disconnect, or am I doing it wrong?

**Comment by stevebauman** [comment]
Hi @sc10n,

It looks like you're just using it incorrectly, try this:

```php
public static function adLookup($emNum)
{
    $upn = $emNum.'@corp';

    $user = Adldap::search()->users()->select('mail')->findBy('userprincipalname', $upn);

    $email = $user->getEmail();
            
    self::searchUser($email);
}
```

**Comment by sc10n** [comment]
Yup, that was it! I need to go look at why findBy and where work differently. Thank you very much, I'll go ahead and close this one.
