### ISSUE TITLE
Can I do this in Adldap2?

### ISSUE THREAD

**Issue by philbrowne** [Adldap2/Adldap2-Laravel#250]
Hi there - I'm using Laravel 5.2 and I have downloaded the package and configured everything and have managed to authenticate ok. However, I'm now wondering if it is still suitable for the following scenario. 

My system should not allow all authenticated users to access it. Instead, it needs to only allow those who's names (samaccountname) are set up in the Users table. Further, once in the system their capabilities are restricted by roles governed by an additional column in the user table.
I have this working fine in a non-Active Directory setup but that means that users have a separate name / password to remember. 

When I tried out the package it seems to write the authenticated user into the users table, but what I need it to do is check that they exist in the table and block their access if not. If they do exist then I need to use their role from the table as now. So - my question is - can I do this using this package and can you guide me how to set this part up if so?
Many thanks!

**Comment by stevebauman** [comment]
Hi @philbrowne,

This actually exists in the master branch right now in the form of authentication rules:

https://github.com/Adldap2/Adldap2-Laravel/blob/master/src/Config/auth.php#L63

It does exactly what you want it to do - only allow pre-existing users in your database to authenticate.

It will be released soon (`v3.0.0`), but just finishing up documentation and tests.
