### ISSUE TITLE
Call to undefined method Adldap\Laravel\Commands\Import::resolver()

### ISSUE THREAD

**Issue by dr3ads** [Adldap2/Adldap2-Laravel#251]
Hi @stevebauman,

I just updated my local instance with the latest in dev-master.  Upon running php artisan adldap:import triggers this error message.

**Comment by stevebauman** [comment]
Hi @dr3ads,

This is due to recent changes. You'll need to run `composer update` again and delete your `adldap_auth.php` config file, then republish it by running `php artisan vendor:publish --tag="adldap"`
