### ISSUE TITLE
error after last update

### ISSUE THREAD

**Issue by tecnical** [Adldap2/Adldap2-Laravel#253]
Hi Steve,

After the last update, i´m getting this error in the end of "composer update"

![image](https://cloud.githubusercontent.com/assets/3150716/22792497/1c0fe1ce-eed4-11e6-956a-0dd956e48726.png)

Best regards,

Tecnical

**Comment by stevebauman** [comment]
Hi @tecnical,

Sounds like a caching issue. The only place where a `getModel()` method is defined & called in `dev-master` is in the `WindowsAuthenticate` middleware.

Try running `php artisan cache:clear` and running `composer update` again.

However, there's a ton of changes in `dev-master` right now, I would heavily advise a complete re-install of the package - and re-publishing the configuration files.
