### ISSUE TITLE
Importing Groups / Other Entities

### ISSUE THREAD

**Issue by jameskraus** [Adldap2/Adldap2-Laravel#254]
Would y'all support changing the adldap function to import any entry into any eloquent model? I'm currently implementing this so I can import groups on a work project, so I wanted to know if you're open to just adding the functionality in this library.

**Comment by stevebauman** [comment]
Hi @jameskraus, it depends how static your implementation is.

Can you upload your code to a git repo so we can take a look?

**Comment by jameskraus** [comment]
Sure, I'll paste something up when I'm done.

**Comment by jameskraus** [comment]
I ended up using this as my script to import groups for my app.

https://gist.github.com/jameskraus/fdffe109fac1d056eb7d2f01530a59f0

With some work, the native adldap command could probably support this.
