### ISSUE TITLE
use_tls

### ISSUE THREAD

**Issue by gaalgergely** [Adldap2/Adldap2-Laravel#256]
- Laravel Version: 5.3
- Adldap2-Laravel Version: 6.1.10
- PHP Version: 7.1

### Description:
config/adldap.php
Line 222
I set use_tls to true. The auth still wokrs. I wanted to track down how it was implemented and I could find anything. I searched for the string 'use_tls'. Still found nothing. Is it implemented?

### Steps To Reproduce:
Testing with the config settings seems fine.

**Comment by stevebauman** [comment]
Hi @gaalgergely.

Inside your `config/adldap.php` file, there is an array with your connection information.

This array is passed directly to a new Adldap connection Provider instance:

https://github.com/Adldap2/Adldap2-Laravel/blob/master/src/AdldapServiceProvider.php#L41-L104

This configuration array is loaded by the connection Provider:

https://github.com/Adldap2/Adldap2/blob/master/src/Connections/Provider.php#L48-L86

And before we connect to your server, we prepare our connection object, and this is where SSL or TLS is used:

https://github.com/Adldap2/Adldap2/blob/master/src/Connections/Provider.php#L246-L269

**Comment by gaalgergely** [comment]
Thank you!
