### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages

### ISSUE THREAD

**Issue by Tpojka** [Adldap2/Adldap2-Laravel#260]
- Laravel Version: 5.4
- Adldap2-Laravel Version: ^3.0
- PHP Version: 7.0

### Description:

    user@host:~$ composer require adldap2/adldap2-laravel
    Using version ^3.0 for adldap2/adldap2-laravel
    ./composer.json has been updated
    Loading composer repositories with package information
    Updating dependencies (including require-dev)
    Your requirements could not be resolved to an installable set of packages.

      Problem 1
        - adldap2/adldap2-laravel v3.0.0 requires adldap2/adldap2 7.0.* -> satisfiable by adldap2/adldap2[v7.0.0, v7.0.1, v7.0.2, v7.0.3, v7.0.4, v7.0.5, v7.0.6, v7.0.7].
        - adldap2/adldap2-laravel v3.0.1 requires adldap2/adldap2 7.0.* -> satisfiable by adldap2/adldap2[v7.0.0, v7.0.1, v7.0.2, v7.0.3, v7.0.4, v7.0.5, v7.0.6, v7.0.7].
        - adldap2/adldap2 v7.0.7 requires ext-ldap * -> the requested PHP extension ldap is missing from your system.
        - adldap2/adldap2 v7.0.6 requires ext-ldap * -> the requested PHP extension ldap is missing from your system.
        - adldap2/adldap2 v7.0.5 requires ext-ldap * -> the requested PHP extension ldap is missing from your system.
        - adldap2/adldap2 v7.0.4 requires ext-ldap * -> the requested PHP extension ldap is missing from your system.
        - adldap2/adldap2 v7.0.3 requires ext-ldap * -> the requested PHP extension ldap is missing from your system.
        - adldap2/adldap2 v7.0.2 requires ext-ldap * -> the requested PHP extension ldap is missing from your system.
        - adldap2/adldap2 v7.0.1 requires ext-ldap * -> the requested PHP extension ldap is missing from your system.
        - adldap2/adldap2 v7.0.0 requires ext-ldap * -> the requested PHP extension ldap is missing from your system.
        - Installation request for adldap2/adldap2-laravel ^3.0 -> satisfiable by adldap2/adldap2-laravel[v3.0.0, v3.0.1].

      To enable extensions, verify that they are enabled in your .ini files:
        - /etc/php/7.0/cli/php.ini
        - /etc/php/7.0/cli/conf.d/10-mysqlnd.ini
        - /etc/php/7.0/cli/conf.d/10-opcache.ini
        - /etc/php/7.0/cli/conf.d/10-pdo.ini
        - /etc/php/7.0/cli/conf.d/15-xml.ini
        - /etc/php/7.0/cli/conf.d/20-bcmath.ini
        - /etc/php/7.0/cli/conf.d/20-calendar.ini
        - /etc/php/7.0/cli/conf.d/20-ctype.ini
        - /etc/php/7.0/cli/conf.d/20-curl.ini
        - /etc/php/7.0/cli/conf.d/20-dom.ini
        - /etc/php/7.0/cli/conf.d/20-exif.ini
        - /etc/php/7.0/cli/conf.d/20-fileinfo.ini
        - /etc/php/7.0/cli/conf.d/20-ftp.ini
        - /etc/php/7.0/cli/conf.d/20-gd.ini
        - /etc/php/7.0/cli/conf.d/20-gettext.ini
        - /etc/php/7.0/cli/conf.d/20-iconv.ini
        - /etc/php/7.0/cli/conf.d/20-igbinary.ini
        - /etc/php/7.0/cli/conf.d/20-imagick.ini
        - /etc/php/7.0/cli/conf.d/20-imap.ini
        - /etc/php/7.0/cli/conf.d/20-intl.ini
        - /etc/php/7.0/cli/conf.d/20-json.ini
        - /etc/php/7.0/cli/conf.d/20-mbstring.ini
        - /etc/php/7.0/cli/conf.d/20-mcrypt.ini
        - /etc/php/7.0/cli/conf.d/20-msgpack.ini
        - /etc/php/7.0/cli/conf.d/20-mysqli.ini
        - /etc/php/7.0/cli/conf.d/20-pdo_mysql.ini
        - /etc/php/7.0/cli/conf.d/20-pdo_pgsql.ini
        - /etc/php/7.0/cli/conf.d/20-pdo_sqlite.ini
        - /etc/php/7.0/cli/conf.d/20-pgsql.ini
        - /etc/php/7.0/cli/conf.d/20-phar.ini
        - /etc/php/7.0/cli/conf.d/20-posix.ini
        - /etc/php/7.0/cli/conf.d/20-readline.ini
        - /etc/php/7.0/cli/conf.d/20-shmop.ini
        - /etc/php/7.0/cli/conf.d/20-simplexml.ini
        - /etc/php/7.0/cli/conf.d/20-soap.ini
        - /etc/php/7.0/cli/conf.d/20-sockets.ini
        - /etc/php/7.0/cli/conf.d/20-sqlite3.ini
        - /etc/php/7.0/cli/conf.d/20-sysvmsg.ini
        - /etc/php/7.0/cli/conf.d/20-sysvsem.ini
        - /etc/php/7.0/cli/conf.d/20-sysvshm.ini
        - /etc/php/7.0/cli/conf.d/20-tokenizer.ini
        - /etc/php/7.0/cli/conf.d/20-wddx.ini
        - /etc/php/7.0/cli/conf.d/20-xmlreader.ini
        - /etc/php/7.0/cli/conf.d/20-xmlwriter.ini
        - /etc/php/7.0/cli/conf.d/20-xsl.ini
        - /etc/php/7.0/cli/conf.d/20-zip.ini
        - /etc/php/7.0/cli/conf.d/25-memcached.ini
      You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.

    Installation failed, reverting ./composer.json to its original content.
    user@host:~$

### Steps To Reproduce:

When you are trying to install package on new server with new Laravel installation, you would get this error from title with bunch of packages that should be installed even those are already there. 

After lot of brainstorming I concluded that prerequisite is having installed php-ldap or better said php7.0 on your system (in my case Ubuntu 16.04.2 LTS)
First I was having same trouble under installation of PHP7.1 and because of reading those extension.
As I am working with LDAP for first time, I believe there could be others with same problem. To avoid it you should just set php5-ldap, php7.0-ldap as required library before pulling repo with composer. Just tell users they should have php-ldap installed upfront. I didn't tried with PHP7.1, just got solution this way though.

Best regards,

**Comment by stevebauman** [comment]
>  Just tell users they should have php-ldap installed upfront.

It's listed in the requirements, as well as shown in the error log you posted:

> adldap2/adldap2 v7.0.7 **requires ext-ldap** * -> the requested PHP extension **ldap is missing from your system.**

https://github.com/Adldap2/Adldap2-Laravel#requirements

**Comment by Tpojka** [comment]
Doh. Sorry. My mistake.

**Comment by stevebauman** [comment]
No problem! :)

**Comment by AguNnamdi** [comment]
Save yourself from headache and run the following:

apt-get install apache2 php php-cli mysql-server php-mysql libapache2-mod-php php-mcrypt php-mbstring php-imap phpunit
