### ISSUE TITLE
Apply Scope to New User Registration

### ISSUE THREAD

**Issue by willneumann** [Adldap2/Adldap2-Laravel#265]
- Laravel Version: 5.4.15
- Adldap2-Laravel Version: 3.0.2
- PHP Version: 5.6.28

### Description:
I've applied a scope to restrict access by AD group membership as outlined in scopes.md, and the login works correctly. However, on the register page, I'm able to create users that aren't in Active Directory. Is there a way to apply the scope before a new user gets written to the database?

**Comment by stevebauman** [comment]
Hi @willneumann,

> However, on the register page, I'm able to create users that aren't in Active Directory. Is there a way to apply the scope before a new user gets written to the database?

The objective for the `adladp` auth driver is so you don't need to actually register users. It automatically creates their account upon login.

If you'd still prefer having a registration page, and only want to allow AD users to register, you'll need to validate this manually. For a quick and dirty example:

```php
public function register(Request $request)
{
    $user = Adldap::search()->find($request->email);

    if ($user) {
        // Proceed with registration.
    }

    // No user found, redirect and display error message.
}
```

You could expand this further by actually writing a custom validation rule:

https://laravel.com/docs/5.4/validation#custom-validation-rules

```php
Validator::extend('user-exists', function ($attribute, $value, $parameters, $validator) {
    return Adldap::search()->find($value) instanceof \Adldap\Models\User;
});
```

**Comment by willneumann** [comment]
Thanks Steve. I didn't realize that it was auto-creating the user in the database upon successful first login (and pulling in the details from AD in the process). I'll remove the register functionality from my site. Thanks again.

**Comment by stevebauman** [comment]
No problem! You can see more detail on how this works by these two methods here:

https://github.com/Adldap2/Adldap2-Laravel/blob/master/src/Auth/DatabaseUserProvider.php#L99-L175
