### ISSUE TITLE
Feature: add scope Uid (OpenLdap)

### ISSUE THREAD

**Issue by Douglasdc3** [Adldap2/Adldap2-Laravel#268]
- Laravel Version: 5.4
- Adldap2-Laravel Version: 3
- PHP Version: 7.1

### Description:

Feature Request:
OpenLdap uses Uid over Upn to authenticate users. Suggestion add  `UidScope` class in the scope 

Typical OpenLdap record
```
dn: uid=jsmith,ou=Users,dc=example,dc=com
givenName: John
uid: jsmith
cn: John Smith
sn: Smith
...
```

If this is a desired feature I can add it. Will wait for the authors/maintainers feedback.

### Steps To Reproduce:

-

**Comment by stevebauman** [comment]
Implementing this now, thanks for the recommendation!

**Comment by Douglasdc3** [comment]
Amazing thanks I'll be able to get rid of my own custom class 👍

**Comment by ThomHurks** [comment]
This change is very handy, @stevebauman Do you intent to release the new version soon? I noticed you already wrote the changelog :)
