### ISSUE TITLE
Question: Adldap2 in Laravel 5.2

### ISSUE THREAD

**Issue by sivon12** [Adldap2/Adldap2-Laravel#275]
- Laravel Version: 5.2
- Adldap2-Laravel Version: 2.1
- PHP Version: 5.5.3

### Description:
Hi, I have used the package to authenticate with LDAP but I don't want it to add any rows to the user table, only check the table to see if the authenticated user can use the system. In other words, the user table holds the usernames of those that can use the system, but the passwords are in LDAP. I understand this was added for V3 but that requires PHP 5.6 and I can't go beyond 5.5.3 / Laravel 5.2 at the moment. Can you tell me if it is possible to do this in the latest V2 version - how I can do this 2 stage check?

**Comment by stevebauman** [comment]
Hi @sivon12,

This is possible with v2, you just need to disable the `password_sync` configuration option:

https://github.com/Adldap2/Adldap2-Laravel/blob/v2.1/src/Config/auth.php#L113\

Then, you can simply add an `exists` rule to your `username` / `email` validation to verify that the user exists before allowing them to authenticate:

https://laravel.com/docs/5.4/validation#rule-exists

I can't assist you with the implementation, but the above will get you started.

**Comment by sivon12** [comment]
Many thanks for your help Steve - I shall try this out.
