### ISSUE TITLE
config/adldap.php

### ISSUE THREAD

**Issue by wilianuhlmann** [Adldap2/Adldap2-Laravel#276]
I'm  not able to configure, can you send me an example of the configured file?
I think I'm forgetting something!

**Comment by stevebauman** [comment]
Have you followed the installation steps? You need to publish the configuration files after you've inserted the service providers in your `config/app.php` file.

**Comment by wilianuhlmann** [comment]
Yes.
File generated.
I have questions on the information to connect on the AD server that is inside the adldap.php.

**Comment by stevebauman** [comment]
Ok, what are your questions?

Each configuration option is well documented.

**Comment by wilianuhlmann** [comment]
In short, I put all the AD information inside config/adldap.php and I can proceed to the Adldap \ Laravel \ Facades \ Adldap part, correct?

**Comment by stevebauman** [comment]
Yup that's correct, though I'd insert your admin username and password inside your `.env` file:

```
ADLDAP_ADMIN_USERNAME=username
ADLDAP_ADMIN_PASSWORD=password
```

**Comment by kordhrufan** [comment]
One question:

Where do I put the LDAP connection url and how?

ADLDAP_CONNECTION goes in `.env ` file?
