### ISSUE TITLE
Authenticating the same user on multiple Laravel projects on the same server

### ISSUE THREAD

**Issue by vincemammoliti** [Adldap2/Adldap2-Laravel#278]
- Laravel Version: 5.4
- Adldap2-Laravel Version: 3.0
- PHP Version: 7.0

### Description:

I have been developing a couple of applications on the same local server which both use Adldap2-Laravel for authenticating against the same active directory server. The configurations are the same between the two applications. Separate databases are used for each application.

If I try to login as the same user on both applications, I can only stay authenticated on the last application I logged into. 

Can I do anything to enable me to stay authenticated on both applications at the same time?

**Comment by stevebauman** [comment]
Hi @vincemammoliti,

This sounds like an issue with Laravel's sessions, not with Adldap2. All Adldap2 does is start a laravel session upon successful authentication and then uses Laravel's default `EloquentUserProvider` for persistence through requests.

What session driver are you using in these applications?

**Comment by vincemammoliti** [comment]
Hi Steve, apologies for my mistake in bringing up the issue here. But thanks for pointing me in the right direction! Turns out one app was using the file driver and the other was using the cookie driver. Changed them both to the cookie driver and it's now working.
Cheers,
Vince

**Comment by vincemammoliti** [comment]
Hi Steve,
I just confirmed that both applications are using the cookie driver, but the issue still exists.
Sorry to bring it up here. This is my first attempt at developing web applications, so I'm not so familiar.

**Comment by vincemammoliti** [comment]
Thanks for pointing me in the right direction. Found out I needed to change the Session Cookie Path in config/session.php for each application, and that fixed the problem.

**Comment by stevebauman** [comment]
Great to here that you've resolved it!

**Comment by DonaldoLog** [comment]
@vincemammoliti hey can you help me with the same problem? I want to share the session between 2 laravel applications

**Comment by vincemammoliti** [comment]
@DonaldoLog what I wanted to achieve and solved was having two laravel applications on the same server, requiring users to log into both separately but simultaneously. The issue I was having originally was that I could only stay logged into one at a time, and was being logged out of the other one. 

I wouldn't say the laravel session is being shared between the two applications (that's what you want to do?) because I still wanted users to log into each application separately.
