### ISSUE TITLE
Login-Fallback not working for me

### ISSUE THREAD

**Issue by Husky110** [Adldap2/Adldap2-Laravel#281]
- Laravel Version: 5.4.16
- Adldap2-Laravel Version: 3.0.4
- PHP Version: 7.1.2

### Description:
Heyho,

I've got an issue regarding the login-fallback.
Whatever I do, if I deactivate my network-connection, to simulate AD not beeing there, and I try to login I get an error stating:
BindException in Guard.php line 80:
Can't contact LDAP server
And the app crashes.
Could you please look into this - weither I've made a mistake or if this is realy a bug?

Greetings!

### Steps To Reproduce:

1. setup an empty laravel-project
2. install adldap-laravel via composer
3. setup the artisan make:auth and reconfigure the project to use a username (see docs)
3. configure the adldap via .env-file:
ADLDAP_CONTROLLERS="controller1 controller2"
ADLDAP_ADMIN_USERNAME=user@domain.local
ADLDAP_ADMIN_PASSWORD=someawesomepassword
ADLDAP_BASEDN="dc=domain,dc=local"
ADLDAP_LOGIN_FALLBACK=true
4. login once and logout again
5. deactivate all network-interface or unplug the cable
6. try to login...

**Comment by stevebauman** [comment]
Hi @Husky110,

The `login_fallback` feature isn't supposed to work in this way. It's only supposed to fall back to the `eloquent` driver if AD authentication fails:

https://github.com/Adldap2/Adldap2-Laravel/blob/master/docs/auth/fallback.md#login-fallback

> The login fallback option allows you to login as a local database user using the Eloquent authentication driver if active directory authentication fails.

Please read: [Developing Locally Without An AD Connection](https://github.com/Adldap2/Adldap2-Laravel/blob/master/docs/auth/fallback.md#developing-locally-without-an-ad-connection).

If you require the possibility of an unavailable AD connection, you'll need to set `auto_connect` to false in your configuration, and then connect manually before `Auth::attempt()` is called.
