### ISSUE TITLE
Import command does not import if --no-interactive is specified

### ISSUE THREAD

**Issue by jameskraus** [Adldap2/Adldap2-Laravel#283]
- Laravel Version: 5.4
- Adldap2-Laravel Version: 3.0.4
- PHP Version: 7.1

### Description:

The import command will not import users if the import command is run with --no-interactive

![image](https://cloud.githubusercontent.com/assets/415057/24297194/3fae91aa-1078-11e7-8fb8-5542470ff865.png)

### Steps To Reproduce:

Run the import script with --no-interaction.

**Comment by jameskraus** [comment]
PR: https://github.com/Adldap2/Adldap2-Laravel/pull/284

**Comment by jameskraus** [comment]
Closed due to merge of PR #284

**Comment by stevebauman** [comment]
Thanks again @jameskraus, I can always tweak it later if necessary.
