### ISSUE TITLE
Unique violation: 7 ERROR: duplicate key value violates unique constraint "users_username_unique"

### ISSUE THREAD

**Issue by wesleyeduardof** [Adldap2/Adldap2-Laravel#285]
- Laravel Version: 5.3
- Adldap2-Laravel Version: 3.0.# (last update)
- PHP Version: 7.#

### Description:
I realized that in the authentication process, the username is case sensitive. So, when using a username with a capital character instead of a lowercase character the package tries to import the user's account and when trying to insert finds an already existing username.
I tried to keep login username in lowercase/uppercase, but the problem persists.
Is it possible to configure some way to overcome this obstacle, so that the login is not case sensitive?
Authentication is working perfectly with login Wesley.Ferreira, but it presents error with wesley.ferreira. I am not fluent in English. Congratulations on the product. 

Table user:
![adldap2](https://cloud.githubusercontent.com/assets/25320467/24308462/603dc780-109e-11e7-8b69-2982cde1aff1.JPG)

adldap_auth.php
![adldap3](https://cloud.githubusercontent.com/assets/25320467/24308464/603f6f40-109e-11e7-96d0-39a4ac8ebf1a.JPG)

Login !=
![adldap4](https://cloud.githubusercontent.com/assets/25320467/24308465/603f9948-109e-11e7-8e45-c9fbb88a46e3.JPG)

Error
![adldap5](https://cloud.githubusercontent.com/assets/25320467/24308463/603f233c-109e-11e7-9a30-5d360109b409.JPG)

![adldap6](https://cloud.githubusercontent.com/assets/25320467/24308467/6041eafe-109e-11e7-9d2a-4e2e199c2ffc.JPG)

### Steps To Reproduce:
Login with username with an uppercase character instead of a lowercase character.

**Comment by jameskraus** [comment]
Can you make a sample github repo to demonstrate the issue? I'm a lazy bastard.

**Comment by jameskraus** [comment]
Also, which database are you using?

**Comment by wesleyeduardof** [comment]
postgres 9.6

**Comment by jameskraus** [comment]
The problem might have to do with the fact that most people are using mysql, which is not case sensitive when searching. I just switched to Postgres, but I think it handles case sensitivity differently depending on how you query it.

**Comment by jameskraus** [comment]
Hey, no need to make a demonstration repo. It turns out my app has the same bug.

**Comment by stevebauman** [comment]
I've personally never used postgres, but I've never experienced this issue with MySQL with using usernames or emails.

This may be tricky to implement though.

The only way we could sort of enforce all useranames to be lower case is run a `strtolower` on all attributes being synced in the importer and then lowercase their username on authentication.

Anyone have any thoughts on an implementation?

**Comment by wesleyeduardof** [comment]
stevebauman, i'll try it here first. Https://www.postgresql.org/docs/current/static/citext.html. Then I'll tell you what happened.
Thanks jameskraus

**Comment by stevebauman** [comment]
Thanks @wesleyeduardof. Could you also give something another try?

Technically, shouldn't this also be an issue with Laravel itself as well?

For example, the `unique` validation rule that's present on the standard Laravel install inside the `RegisterController`, uses the same `where()` query:

https://github.com/laravel/framework/blob/5.4/src/Illuminate/Validation/DatabasePresenceVerifier.php#L49

Can you try a fresh laravel application using Postgre and try registering an account with the same email address and see if it throws the same exception?

**Comment by jameskraus** [comment]
FYI, if you sync you users by guid instead of username, this issue will disappear. Then again, you have to write an import script to sync by guid.

**Comment by jameskraus** [comment]
Well, first, you'll want to lowercase the usernames on login by adding this to your LoginController:
```
    /**
     * Get the needed authorization credentials from the request and
     * convert the username to lowercase to keep case constant.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    protected function credentials(Request $request)
    {
        $credentials = $request->only($this->username(), 'password');
        $credentials[$this->username()] = strtolower($credentials[$this->username()]);
        return $credentials;
    }
```

Then you'll want to create a handler to sync the usernames in a lowercased way:
```
// adldap_auth.php
    'sync_attributes' => [
        'email' => 'userprincipalname',
        'name' => 'cn',
        'guid' => '\App\Ldap\Handlers\GuidAttributeSyncHandler', // This is just for my app
        'username' => '\App\Ldap\Handlers\UsernameAttributeSyncHandler',
    ],
```

```
<?php


namespace App\Ldap\Handlers;

use Adldap\Models\User as LdapUser;
use Illuminate\Database\Eloquent\Model as EloquentModel;

class UsernameAttributeSyncHandler
{
    /**
     * Handles adding a username from the ldap user to the eloquent model.
     *
     * @param LdapUser $ldapUser
     * @param EloquentModel $eloquentModel
     * @return EloquentModel
     */
    public function handle(LdapUser $ldapUser, EloquentModel $eloquentModel)
    {
        $username = $ldapUser->getAccountName();

        // Lowercase for consistent PostgresQL lookups
        $eloquentModel->username = strtolower($username);
        return $eloquentModel;
    }
}
```

And as far as getting syncing to work, I ended up writing my own import script that syncs by guid instead of username because username is unreliable. I would recommend you do the same.

**Comment by stevebauman** [comment]
@jameskraus thanks for testing this! This might actually be the best way to go, since the guid is unchangeable.

I'll keep looking to see if there's a way I can incorporate a fix.

**Comment by wesleyeduardof** [comment]
Guys, the results.
1. Https://www.postgresql.org/docs/current/static/citext.html. Not work.
2. add handler by jameskraus. It work very well.
Thanks jameskraus and stevebauman.

**Comment by stevebauman** [comment]
Thanks for following up @wesleyeduardof.

Are either of you able to test what I suggested above and try registering a user with the same username / email address with different casing? Curious if this is an issue with Laravel.

**Comment by jameskraus** [comment]
@stevebauman 

Just tested it. It allows for registration of `test@test.com` and `TEST@TEST.com`

**Comment by jameskraus** [comment]
It seems like they're already aware of it, but have closed the related ticket...

https://github.com/laravel/framework/issues/9430

**Comment by stevebauman** [comment]
@jameskraus Great, thanks for looking into this!

I figured this would be a framework issue, as there aren't any custom queries that are unique to Adldap2-Laravel.

Surprised that there isn't a fix out yet?

**Comment by wesleyeduardof** [comment]
@jameskraus Https://www.postgresql.org/docs/current/static/citext.html. Not work. I tested.
@stevebauman, it took me a while to run the test only with auth laravel default. Auth continues case-insensitive in postgresql. I tested it with all the created accounts.
![auth_test_postgres](https://cloud.githubusercontent.com/assets/25320467/24452714/8aed8b34-1452-11e7-8279-63ab0ec1842c.JPG)

**Comment by stevebauman** [comment]
Thanks for following up @wesleyeduardof!

Seems like you may have to perform this before authentication so the same user is retrieved every time.

In the case of using Postgre, I would refrain from using the built in `adldap:import` command and just `strtolower` all emails before authentication. You can do this by overriding one method in the default `LoginController`:

```php
// Auth\LoginController.php

protected function credentials(Request $request)
{
    return [
        'email' => strtolower($request->email),
        'password' => $request->password,
    ];
}
```

**Comment by marekr** [comment]
+1 Just had to use the workaround. This should be added to the manual as a note for postgres.

One thing to note which I'm not sure if its just a laravel issue. Most other frameworks and software just in  perform strtolower but this is probably a laravel thing not doing so.

**Comment by hamedbaftam** [comment]
```
$tables = \DB::select('SELECT table_name FROM information_schema.tables WHERE table_schema = \'public\' ORDER BY table_name;');
    $ignores = array('admin_setting', 'model_has_permissions', 'model_has_roles', 'password_resets', 'role_has_permissions', 'sessions');
    foreach ($tables as $table) {
        if (!in_array($table->table_name, $ignores)) {
            $seq = \DB::table($table->table_name)->max('id') + 1;
            \DB::select('ALTER SEQUENCE ' . $table->table_name . '_id_seq RESTART WITH ' . $seq);

        }

    }
```
