### ISSUE TITLE
Rules-declaration-error

### ISSUE THREAD

**Issue by Husky110** [Adldap2/Adldap2-Laravel#286]
- PHP Version: 7.1.2

### Description:
The declaration of the isValid-method within the rules is incompatible with the docs.  
The docs suggtest do to sth like this:
```
public function isValid(LdapUser $ldapUser, EloquentUser $user)
    {
        return $ldapUser->inGroup('MyAwesomeUsergroup');
    }
```
but
the abstract function isValid within the Rule class is declared without variables, causing the following error to occur:  
Declaration of MyApp\Rules\MyRule::isValid(Adldap\Models\User $ldapUser, MyApp\User $user) must be compatible with Adldap\Laravel\Validation\Rules\Rule::isValid()

**Comment by Husky110** [comment]
a temporary workarround works like this:
``
public function isValid()
    {
        $ldapUser = $this->user;
        $eloquentUser = $this->model;
        return $ldapUser->inGroup('MyAwesomeGroup'); //apply any other rules here
    }
``

**Comment by stevebauman** [comment]
Thanks @Husky110! Will have this fixed shortly.

**Comment by stevebauman** [comment]
@Husky110 your second post is the correct usage. I've fixed the docs:

https://github.com/Adldap2/Adldap2-Laravel/blob/master/docs/auth/rules.md

Thanks for pointing this out!
