### ISSUE TITLE
Filter users import

### ISSUE THREAD

**Issue by netopvh** [Adldap2/Adldap2-Laravel#288]
- Laravel Version: 5.4
- Adldap2-Laravel Version: 3.0.4
- PHP Version: 5.6

### Description:
I need help to import users to my database with filter.

users memberof 

how to proceed?

**Comment by stevebauman** [comment]
Please read the documentation on scopes and the import command:

https://github.com/Adldap2/Adldap2-Laravel/blob/master/docs/auth/scopes.md#creating-a-scope

https://github.com/Adldap2/Adldap2-Laravel/blob/master/docs/importing.md#filter
