### ISSUE TITLE
Editing the login form

### ISSUE THREAD

**Issue by fatalh** [Adldap2/Adldap2-Laravel#291]
- Laravel Version: 5.4
- Adldap2-Laravel Version: 3.04
- PHP Version: 5.6

### Description:
I currently have an App where the users are logged in from my database. I need to make Active Directory Connection right now. I configured the Adlap2 in my laravel files, and I am able to see and import all the users from Domain. My problem is how to edit the login.blade.php where the FORM is to reach the App.
Thanks you @stevebauman for helping me !

**Comment by stevebauman** [comment]
Hi @fatalh, I'd be glad to help you out.

Did you enable the `adldap` driver in your `config/auth.php` file?

**Comment by fatalh** [comment]
Yes ,  I did  that  like this :
 'providers' => [
    'users' => [
        'driver' => 'adldap', // Changed from 'eloquent'
        'model' => App\User::class,
    ],
],

**Comment by stevebauman** [comment]
Then you should be able to login using an LDAP account with the standard login form using their email address.

Have you tried?

**Comment by fatalh** [comment]
Yes , I tried again , but it 'is not working. I think it is due to the Form in my login.blade.php, I am new in Laravel

**Comment by fatalh** [comment]
That's my login.blade.php code : 
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Login</div>
                <div class="panel-body">
                    <form class="form-horizontal" role="form" method="POST" action="{{ route('login') }}">
                        {{ csrf_field() }}

                        <div class="form-group{{ $errors->has('username') ? ' has-error' : '' }}">
                            <label for="username" class="col-md-4 control-label">Username</label>

                            <div class="col-md-6">
                                <input id="email" type="text" class="form-control" name="text" value="{{ old('username') }}" required autofocus>


                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('password') ? ' has-error' : '' }}">
                            <label for="password" class="col-md-4 control-label">Password</label>

                            <div class="col-md-6">
                                <input id="password" type="password" class="form-control" name="password" required>

                                @if ($errors->has('password'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('password') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-4">
                                <div class="checkbox">
                                    <label>
                                        <input type="checkbox" name="remember" {{ old('remember') ? 'checked' : '' }}> Remember Me
                                    </label>
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-8 col-md-offset-4">
                                <button type="submit" class="btn btn-primary">
                                    Login
                                </button>

                                <a class="btn btn-link" href="{{ route('password.request') }}">
                                    Forgot Your Password?
                                </a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

**Comment by fatalh** [comment]
Users Migrations

<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateUsersTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('users', function (Blueprint $table) {
            $table->increments('id');
            $table->string('name', 50);
            $table->string('direction', 50);
            $table->string('username')->unique();
            $table->string('password');
            $table->rememberToken();
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('users');
    }
}

**Comment by fatalh** [comment]
`<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateUsersTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('users', function (Blueprint $table) {
            $table->increments('id');
            $table->string('name', 50);
            $table->string('direction', 50);
            $table->string('username')->unique();
            $table->string('password');
            $table->rememberToken();
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('users');
    }
}
`

**Comment by stevebauman** [comment]
Your input field name is wrong in your form:

```html
<input id="email" type="text" class="form-control" name="text" value="{{ old('username') }}" required autofocus>
```

You're setting the input name to `text` when it should be `username`:

```html
<input id="username" type="text" class="form-control" name="username" value="{{ old('username') }}" required autofocus>
```

**Comment by fatalh** [comment]
I did it ,  but it is same problem. When I try to login with the emails , it redirecting me to the login page. Same things  when I do it with my username of the Domain.

**Comment by stevebauman** [comment]
Did you modify the `LoginController` to use the `username` input field?

You may be new to Laravel, but I'd **highly** recommend going through the Laravel documentation as well as how Laravel authentication works before working with other auth drivers.

**Comment by fatalh** [comment]
No, I did not modified the LoginController , can you tell me how to modify it ?
Also I will read carefully the Laravel documentation in order to understand how Laravel authentification works !

**Comment by stevebauman** [comment]
Inside your `LoginController.php`, add a public method named `username()`:

```php
public function username()
{
    return 'username';
}
````

**Comment by fatalh** [comment]
Hello @stevebauman , I updated the LoginController.php as you told me but when I try to login , I see this  : FatalErrorException in User.php line 13:
Trait 'Adldap\Laravel\Traits\AdldapUserModelTrait' not found

**Comment by fatalh** [comment]
I tried to fix it myself , I was not able  !

**Comment by fatalh** [comment]
And this is my User.php file : 
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Adldap\Laravel\Traits\AdldapUserModelTrait;


class User extends Authenticatable
{
    use Notifiable;
    use AdldapUserModelTrait;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'username', 'direction', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}
