### ISSUE TITLE
Can't find adldap_auth.php when vendor:publish

### ISSUE THREAD

**Issue by ArabAgile** [Adldap2/Adldap2-Laravel#292]
- Laravel Version: 5.4
- Adldap2-Laravel Version: 3.0.*
- PHP Version: 7

when running
```php artisan vendor:publish```
Only adldap.php file is generated. not **adldap_auth.php**

**Comment by ArabAgile** [comment]
Kindly mention we've to add the following in config/app.php provider's list:
```Adldap\Laravel\AdldapAuthServiceProvider::class,```

**Comment by stevebauman** [comment]
It's already in the auth driver installation and setup.

https://github.com/Adldap2/Adldap2-Laravel/blob/master/docs/auth/installation.md
