### ISSUE TITLE
selecting attributes

### ISSUE THREAD

**Issue by celiakessassi** [Adldap2/Adldap2-Laravel#294]
- Laravel Version: #.#
- Adldap2-Laravel Version: #.#
- PHP Version: #.#

### Description:
I would like to get users in an array of this form
 [ 0 => ['cn' => '...',"email" => ''.." ] , 1 => ['cn' => '...',"email" => ''.." ] ,...]
didn't find out how to make it work or how to manipulate selected attributes.

**Comment by stevebauman** [comment]
Hi @celiakessassi, here's detailed documentation on all model methods, as well as retrieving attributes:

https://github.com/Adldap2/Adldap2/blob/master/docs/models/model.md#getting-attributes

For you question, since results are returned in Laravel collections, you can do this pretty easily:

```php
$users = Adldap::search()->users()->get()->map(function ($user) {
    return $user->getAttributes();
});;
```

**Comment by celiakessassi** [comment]
thx @stevebauman this what worked for me 
$users = Adldap::search()->users()->get()->map(function ($user) {
    return ['uid'=>$user->uid[0],'email'=>$user->email[0],'cn'=>$user->cn[0]];
    })->toArray();
don't know why but seems that getAttribute don't change anything
