### ISSUE TITLE
Fresh install but cannot login

### ISSUE THREAD

**Issue by shahrinrazmi** [Adldap2/Adldap2-Laravel#297]
- Laravel Version: 5.4
- Adldap2-Laravel Version: 3.0
- PHP Version: 5.6

### Description:
I follow step from 
Quick Start - From Scratch - https://github.com/Adldap2/Adldap2-Laravel/blob/master/docs/quick-start.md

my ldap connection looks ok because i dd() Adldap::auth(); get true
and Adldap::search()->users()->get(); show all the user information

Adldap::auth()->attempt('username','password'); also ok when i test using correct username it return true and false for wrong username

### Problem:
when i tried login using form, it return back to login form, the code looks like not create laravel auth from login post

**Comment by stevebauman** [comment]
Hi @shahrinrazmi,

This seems like a configuration issue. Are you trying to login users by their username or email address?

Can you also post your `config/adldap.php` and `config/adldap_auth.php` file (with sensitive details removed)?

**Comment by shahrinrazmi** [comment]
login by username

i using online ldap test server from this
http://www.forumsys.com/tutorials/integration-how-to/ldap/online-ldap-test-server/

i think the details not sensitive, so i post all the code

**Comment by shahrinrazmi** [comment]
config/adldap.php

return [
    'connections' => [
        'default' => [
            'auto_connect' => true,
            'connection' => Adldap\Connections\Ldap::class,
            'schema' => Adldap\Schemas\OpenLDAP::class,
            'connection_settings' => [
                'account_prefix' => env('ADLDAP_ACCOUNT_PREFIX', 'uid='),
                'account_suffix' => env('ADLDAP_ACCOUNT_SUFFIX', ',dc=example,dc=com'),
                'domain_controllers' => ['ldap.forumsys.com'],
                'port' => env('ADLDAP_PORT', 389),
                'timeout' => env('ADLDAP_TIMEOUT', 5),
                'base_dn' => env('ADLDAP_BASEDN', 'dc=example,dc=com'),
                'admin_account_prefix' => 'cn=',
                'admin_account_suffix' => env('ADLDAP_ADMIN_ACCOUNT_SUFFIX', ',dc=example,dc=com'),
                'admin_username' => env('ADLDAP_ADMIN_USERNAME', 'read-only-admin'),
                'admin_password' => env('ADLDAP_ADMIN_PASSWORD', 'password'),
                'follow_referrals' => false,
                'use_ssl' => false,
                'use_tls' => false,
            ],
        ],
    ],
];

**Comment by shahrinrazmi** [comment]
config/adldap_auth.php


return [
    'connection' => env('ADLDAP_CONNECTION', 'default'),
    'provider' => Adldap\Laravel\Auth\DatabaseUserProvider::class,
    'resolver' => Adldap\Laravel\Auth\Resolver::class,
    'importer' => Adldap\Laravel\Auth\Importer::class,
    'rules' => [
        Adldap\Laravel\Validation\Rules\DenyTrashed::class,
    ],

    'scopes' => [
        Adldap\Laravel\Scopes\UpnScope::class,
    ],

    'usernames' => [
        'ldap' => 'uid',
        'eloquent' => 'username',
    ],

    'login_fallback' => env('ADLDAP_LOGIN_FALLBACK', false),
    'password_sync' => env('ADLDAP_PASSWORD_SYNC', true),
    'windows_auth_attribute' => ['samaccountname' => 'AUTH_USER'],

    'sync_attributes' => [
        'email' => 'mail',
        'name' => 'cn',
    ],

];

**Comment by renanwilliam** [comment]
I have the same issue. At localhost (Win10 Machine) works fine but on Ubuntu server have this login loop.

**Comment by shahrinrazmi** [comment]
i using windows 10, but cannot login. @renanwilliam, do you just follow the tutorial strictly?
or my config missing something?

**Comment by renanwilliam** [comment]
Using the login form I can't login even in Windows. I can login just in API using Passport but I was necessary implement the methods **findForPassport** and **validateForPassportPasswordGrant** in User model.

```php
    public function findForPassport($username)
    {
        $user = $this->where('email', $username)->first();
        if (!$user) {
            $email_parts = explode("@", $username);
            if (count($email_parts) > 0) {
                $login = $email_parts[0];
                $user = $this->where('username', $login)->first();
            }
        }

        return $user;
    }

    public function validateForPassportPasswordGrant($password)
    {
        if (Adldap::auth()->attempt($this->username . '@' . $this->companyid, $password)) {
            return true;
        }

        return false;
    }
```

Are you using Passport too? It's looking as a conflict for me.

**Comment by renanwilliam** [comment]
@shahrinrazmi I found what is my problem. In my case I'm using complete e-mail address to login but I was included this method in my LoginController:
```php
public function username()
{
   return 'username';
}
```

As I not changed anything in resources/views/auth/login.blade.php the form was searching for the username field and returning a required field error. When the method was deleted from LoginController authentication is working in login form and in Passport Routes
