### ISSUE TITLE
when user has to change password, i cant login

### ISSUE THREAD

**Issue by tecnical** [Adldap2/Adldap2-Laravel#299]
- Laravel Version: 5.3
- Adldap2-Laravel Version: dev
- PHP Version: 7.0.12

### Description:
Hi Steve,

When a user try to login and his account has the flag "user must change password at next login" enabled, the user can´t login.
In this case, is returned the login exception? I cannot found it.

thanks

And thanks for the awesome job youre doing!

**Comment by stevebauman** [comment]
Hi @tecnical, thanks for your kind words! :)

Unfortunately this is a limitation of Active Directory.

LDAP authentication will fail for user accounts with the '_user must change password at next login_' flag enabled.

Does this answer your question? Or are you looking for a way to handle this?

**Comment by tecnical** [comment]
I was look for any returning exception in the login time. With that i can redirect user to change password page.

**Comment by stevebauman** [comment]
Right now you can try retrieving the last error returned by your LDAP connection after authentication fails:

```php
Adldap:: getConnection()->getLast
```

**Comment by tecnical** [comment]
Thanks,

I´ll try solve this problem now.

:-)
