### ISSUE TITLE
Remember token isn't set with WindowsAuthenticate Middleware

### ISSUE THREAD

**Issue by munfor** [Adldap2/Adldap2-Laravel#302]
- Laravel Version: 5.4
- Adldap2-Laravel Version: 2.1
- PHP Version: 5.6

### Question:
Thanks to Adldap2-Laravel I can login using the Active Directory. It's perfect!
But I would like use 'remember token' after the user is logged in.
Once the user is logged to be capable to make API calls (via Ajax) using the information provided by remember_token.

The users table has the remember_token field, but it has always a NULL value.
I don't think the a "remember cookie" is generated neither.

Thank you.

**Comment by stevebauman** [comment]
Hi @munfor, the remember token should be created as usual. Are you using the default Laravel `auth:make` scaffolding views / controllers?

**Comment by stevebauman** [comment]
You should have this checkbox on your login form:

```php
<label>
    <input type="checkbox" name="remember" {{ old('remember') ? 'checked' : '' }}> Remember Me
</label>
```

**Comment by munfor** [comment]
Thanks @stevebauman
No, I'm not using Laravel auth:make scaffolding.
I using the WindowsAuthenticate class in mi web midleware group:

```
protected $middlewareGroups = [
    'web' => [
         \App\Http\Middleware\EncryptCookies::class,
         \Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::class,
         \Illuminate\Session\Middleware\StartSession::class,
         \Illuminate\View\Middleware\ShareErrorsFromSession::class,
         \App\Http\Middleware\VerifyCsrfToken::class,
         \Adldap\Laravel\Middleware\WindowsAuthenticate::class
     ]
    ...
]
```
With this config I can log in using Active Directory. It works well!
No login form is required, it logs using the PHP_AUTH_USER id.

For the moment I put the WindowsAuthenticate into api group too. But I don't know if it is correct, because the handle function in WindowsAuthenticate, the $this->auth->check(), which determines if the current user is authenticated, returns always false. I thought because 'remember_token' is not set, but I'm not sure.

```
protected $middlewareGroups = [
    ...
    'api' => [
       'throttle:60,1',
       'bindings',                        
       \Adldap\Laravel\Middleware\WindowsAuthenticate::class
    ],
]
```

**Comment by stevebauman** [comment]
Ohhh okay I understand. Yes the remember token isn't set when logging in through the middleware. This can be changed though...

The `login()` method supports passing in `true` into the second parameter to set the remember field:

https://github.com/laravel/framework/blob/5.4/src/Illuminate/Auth/SessionGuard.php#L400-L408

Right now the middleware only passes in the user:

https://github.com/Adldap2/Adldap2-Laravel/blob/master/src/Middleware/WindowsAuthenticate.php#L65

Going to check a couple things and see if this may break anything before I enable this by default.

**Comment by munfor** [comment]
Thank you!
