### ISSUE TITLE
When must change password on next login is set.

### ISSUE THREAD

**Issue by necrogami** [Adldap2/Adldap2-Laravel#304]
- Laravel Version: 5.3.31
- Adldap2-Laravel Version: 3.0.4
- PHP Version: 7.0.17

### Description:
We're trying to handle it requests to reset passwords and were setting a generic password via setpassword and we want them to be forced to change their password on next login.  Also we want to handle when their password has exipred and needs to be changed.

Currently all it does is fail. 

Is there a method for handling expired / force change password login attempts?

**Comment by stevebauman** [comment]
Hi @necrogami,

There is no method right now for handling this, as all `ldap_bind` requests will return `false` when binding as a user that needs to change their password on next login.

I'm working on implementing this, but for right now, if authentication fails, you can retrieve the last error from your LDAP connection and parse the code to see what error occurred:

https://github.com/Adldap2/Adldap2/blob/master/src/Connections/Ldap.php#L365-L407

http://wiki.servicenow.com/index.php?title=LDAP_Error_Codes#gsc.tab=0

```php
$code = Adldap::getConnection()->getExtendedErrorHex();

if ($code == '532') {
    // Password expired
}
```

**Comment by stevebauman** [comment]
Closing. Related to #122. This is being implemented with the additions of Events in Adldap2 v10.
