### ISSUE TITLE
Creating User With Additional (custom) attribute

### ISSUE THREAD

**Issue by hannylicious** [Adldap2/Adldap2-Laravel#305]
- Laravel Version: #.#
- Adldap2-Laravel Version: #.#
- PHP Version: #.#

**Comment by stevebauman** [comment]
Please use attribute handlers described here:

https://github.com/Adldap2/Adldap2-Laravel/blob/master/docs/auth/syncing.md#attribute-handlers

**Comment by hannylicious** [comment]
I have tried this:
    'sync_attributes' => [
        'name' => 'cn',
        'user_level' => int(1),
    ],
But it did not work (although I do see user_level being added to the user insert!); but it breaks.

And I have tried this:
    'sync_attributes' => [
        'name' => 'cn',
        App\Handlers\LdapAttributeHandler::class,
    ],

with this: 

<?php

namespace App\Handlers;

use App\User as EloquentUser;
use Adldap\Models\User as LdapUser;

class LdapAttributeHandler
{
    /**
     * Synchronizes ldap attributes to the specified model.
     *
     * @param LdapUser     $ldapUser
     * @param EloquentUser $eloquentUser
     *
     * @return void
     */
    public function handle(LdapUser $ldapUser, EloquentUser $eloquentUser)
    {
        $eloquentUser->user_level = 1;
    }
}

That did not work either. I think perhaps I'm doing something incorrectly.

**Comment by stevebauman** [comment]
Are you caching your configuration files?

Also, try `dd()`'ing in your attribute handler, and then authenticate and see if it's properly being registered:

```php
<?php

namespace App\Handlers;

use App\User as EloquentUser;
use Adldap\Models\User as LdapUser;

class LdapAttributeHandler
{
    /**
     * Synchronizes ldap attributes to the specified model.
     *
     * @param LdapUser     $ldapUser
     * @param EloquentUser $eloquentUser
     *
     * @return void
     */
    public function handle(LdapUser $ldapUser, EloquentUser $eloquentUser)
    {
        dd($eloquentUser);
        $eloquentUser->user_level = 1;
    }
}
```

**Comment by hannylicious** [comment]
Alright, I tried to `dd()` it, but it is still not working.

I think I'm probably putting the LdapAttributeHandler file in the wrong spot maybe? Currently it's in app directory.

I have: 
```

    'sync_attributes' => [
        'name' => 'cn',
        App\Handlers\LdapAttributeHandler::class,
    ],
```

and 
```

    public function handle(LdapUser $ldapUser, EloquentUser $eloquentUser)
    {
        dd($eloquentUser);
        $eloquentUser->user_level = 1;        
    }
```

But it's not hitting the dd() - so I don't even think it's hitting the LdapAttributeHandler class.

My error message looks like: 

`Column not found: 1054 Unknown column '0' in 'field list' (SQL: insert into `users` (`email`, `password`, `name`, **`0`** (this should be the user_level), `updated_at`, `created_at`) values (me@my.fullyq.domain, hashedpassword, me, (user level should be here but isn't) , 2017-04-20 13:24:44, 2017-04-20 13:24:44))`

**Comment by stevebauman** [comment]
> I think I'm probably putting the LdapAttributeHandler file in the wrong spot maybe? Currently it's in app directory.

Did you create the app/Handlers directory and insert the hanlder class inside? You have namespaced in as such, and it won't be autoloaded otherwise.

**Comment by hannylicious** [comment]
I created the directory 'Handlers' under 'app' and placed the class in there.

Same result unfortunately - same error message (no, there is no caching going on). Still not seeing the `dd()`.

**Comment by jlsjonas** [comment]
@stevebauman your link is broken
![image](https://user-images.githubusercontent.com/932193/46673085-47569b00-cbd9-11e8-828a-e17e2126ca06.png)

**Comment by stevebauman** [comment]
Hi @jlsjonas, here's the updated link:

https://github.com/Adldap2/Adldap2-Laravel/blob/master/docs/auth.md#syncing-attributes

This may change in the future. The best way to browse the docs is from the index tree on the home page:

https://github.com/Adldap2/Adldap2-Laravel
