### ISSUE TITLE
These credentials don't match record

### ISSUE THREAD

**Issue by anukwgl** [Adldap2/Adldap2-Laravel#306]
- Laravel Version: 5.4
- Adldap2-Laravel Version: 3
- PHP Version: 5.6

### Description:
I am testing with the online test server http://www.forumsys.com/tutorials/integration-how-to/ldap/online-ldap-test-server/ But could not login. it Says credentials don't match the records.

**Comment by anukwgl** [comment]
adldap.php
<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Connections
    |--------------------------------------------------------------------------
    |
    | This array stores the connections that are added to Adldap. You can add
    | as many connections as you like.
    |
    | The key is the name of the connection you wish to use and the value is
    | an array of configuration settings.
    |
    */

    'connections' => [

        'default' => [

            /*
            |--------------------------------------------------------------------------
            | Auto Connect
            |--------------------------------------------------------------------------
            |
            | If auto connect is true, Adldap will try to automatically connect to
            | your LDAP server in your configuration. This allows you to assume
            | connectivity rather than having to connect manually
            | in your application.
            |
            | If this is set to false, you must connect manually before running
            | LDAP operations.
            |
            */

            'auto_connect' => true,

            /*
            |--------------------------------------------------------------------------
            | Connection
            |--------------------------------------------------------------------------
            |
            | The connection class to use to run raw LDAP operations on.
            |
            | Custom connection classes must implement:
            |  \Adldap\Connections\ConnectionInterface
            |
            */

            'connection' => Adldap\Connections\Ldap::class,

            /*
            |--------------------------------------------------------------------------
            | Schema
            |--------------------------------------------------------------------------
            |
            | The schema class to use for retrieving attributes and generating models.
            |
            | You can also set this option to `null` to use the default schema class.
            |
            | Custom schema classes must implement \Adldap\Schemas\SchemaInterface
            |
            */

            'schema' => Adldap\Schemas\OpenLDAP::class,

            /*
            |--------------------------------------------------------------------------
            | Connection Settings
            |--------------------------------------------------------------------------
            |
            | This connection settings array is directly passed into the Adldap constructor.
            |
            | Feel free to add or remove settings you don't need.
            |
            */

            'connection_settings' => [

                /*
                |--------------------------------------------------------------------------
                | Account Prefix
                |--------------------------------------------------------------------------
                |
                | The account prefix option is the prefix of your user accounts in AD.
                |
                | This string is prepended to authenticating users usernames.
                |
                */

                'account_prefix' => env('ADLDAP_ACCOUNT_PREFIX', 'uid='),

                /*
                |--------------------------------------------------------------------------
                | Account Suffix
                |--------------------------------------------------------------------------
                |
                | The account suffix option is the suffix of your user accounts in AD.
                |
                | This string is appended to authenticating users usernames.
                |
                */

                'account_suffix' => env('ADLDAP_ACCOUNT_SUFFIX', ',dc=example,dc=com'),

                /*
                |--------------------------------------------------------------------------
                | Domain Controllers
                |--------------------------------------------------------------------------
                |
                | The domain controllers option is an array of servers located on your
                | network that serve Active Directory. You can insert as many servers or
                | as little as you'd like depending on your forest (with the
                | minimum of one of course).
                |
                | These can be IP addresses of your server(s), or the host name.
                |
                */

                'domain_controllers' => explode(' ', env('ADLDAP_CONTROLLERS', 'ldap.forumsys.com')),

                /*
                |--------------------------------------------------------------------------
                | Port
                |--------------------------------------------------------------------------
                |
                | The port option is used for authenticating and binding to your AD server.
                |
                */

                'port' => env('ADLDAP_PORT', 389),

                /*
                |--------------------------------------------------------------------------
                | Timeout
                |--------------------------------------------------------------------------
                |
                | The timeout option allows you to configure the amount of time in
                | seconds that your application waits until a response
                | is received from your LDAP server.
                |
                */

                'timeout' => env('ADLDAP_TIMEOUT', 5),

                /*
                |--------------------------------------------------------------------------
                | Base Distinguished Name
                |--------------------------------------------------------------------------
                |
                | The base distinguished name is the base distinguished name you'd
                | like to perform query operations on. An example base DN would be:
                |
                |        dc=corp,dc=acme,dc=org
                |
                | A correct base DN is required for any query results to be returned.
                |
                */

                'base_dn' => env('ADLDAP_BASEDN', 'dc=example,dc=com'),

                /*
                |--------------------------------------------------------------------------
                | Administrator Account Suffix
                |--------------------------------------------------------------------------
                |
                | This option allows you to set a different account suffix for your
                | configured administrator account upon binding.
                |
                | If left empty, your `account_suffix` option will be used.
                |
                */

                'admin_account_suffix' => env('ADLDAP_ADMIN_ACCOUNT_SUFFIX', ',dc=example,dc=com'),
                'admin_account_prefix' => env('ADLDAP_ADMIN_ACCOUNT_PREFIX', 'cn='),

                /*
                |--------------------------------------------------------------------------
                | Administrator Username & Password
                |--------------------------------------------------------------------------
                |
                | When connecting to your AD server, a username and password is required
                | to be able to query and run operations on your server(s). You can
                | use any user account that has these permissions. This account
                | does not need to be a domain administrator unless you
                | require changing and resetting user passwords.
                |
                */

                'admin_username' => env('ADLDAP_ADMIN_USERNAME', 'read-only-admin'),
                'admin_password' => env('ADLDAP_ADMIN_PASSWORD', 'password'),

                /*
                |--------------------------------------------------------------------------
                | Follow Referrals
                |--------------------------------------------------------------------------
                |
                | The follow referrals option is a boolean to tell active directory
                | to follow a referral to another server on your network if the
                | server queried knows the information your asking for exists,
                | but does not yet contain a copy of it locally.
                |
                | This option is defaulted to false.
                |
                */

                'follow_referrals' => false,

                /*
                |--------------------------------------------------------------------------
                | SSL & TLS
                |--------------------------------------------------------------------------
                |
                | If you need to be able to change user passwords on your server, then an
                | SSL or TLS connection is required. All other operations are allowed
                | on unsecured protocols.
                | 
                | One of these options are definitely recommended if you 
                | have the ability to connect to your server securely.
                |
                */

                'use_ssl' => false,
                'use_tls' => false,

            ],

        ],

    ],

];

**Comment by anukwgl** [comment]
adldap_auth.php
<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Connection
    |--------------------------------------------------------------------------
    |
    | The LDAP connection to use for laravel authentication.
    |
    | You must specify connections in your `config/adldap.php` configuration file.
    |
    | This must be a string.
    |
    */

    'connection' => env('ADLDAP_CONNECTION', 'default'),

    /*
    |--------------------------------------------------------------------------
    | Provider
    |--------------------------------------------------------------------------
    |
    | The LDAP authentication provider to use depending
    | if you require database synchronization.
    |
    | For synchronizing LDAP users to your local applications database, use the provider:
    |
    | Adldap\Laravel\Auth\DatabaseUserProvider::class
    |
    | Otherwise, if you just require LDAP authentication, use the provider:
    |
    | Adldap\Laravel\Auth\NoDatabaseUserProvider::class
    |
    */

    'provider' => Adldap\Laravel\Auth\DatabaseUserProvider::class,

    /*
    |--------------------------------------------------------------------------
    | Resolver
    |--------------------------------------------------------------------------
    |
    | The resolver that locates users from your LDAP server.
    |
    | Custom resolvers must implement the following interface:
    |
    |   Adldap\Laravel\Auth\ResolverInterface
    |
    */

    'resolver' => Adldap\Laravel\Auth\Resolver::class,

    /*
    |--------------------------------------------------------------------------
    | Importer
    |--------------------------------------------------------------------------
    |
    | The importer that imports LDAP users into your local database.
    |
    | Custom importers must implement the following interface:
    |
    |   Adldap\Laravel\Auth\ImporterInterface
    |
    */

    'importer' => Adldap\Laravel\Auth\Importer::class,

    /*
    |--------------------------------------------------------------------------
    | Rules
    |--------------------------------------------------------------------------
    |
    | Rules allow you to control user authentication requests depending on scenarios.
    |
    | You can create your own rules and insert them here.
    |
    | All rules must extend from the following class:
    |
    |   Adldap\Laravel\Validation\Rules\Rule
    |
    */

    'rules' => [

        // Denys deleted users from authenticating.

        Adldap\Laravel\Validation\Rules\DenyTrashed::class,

        // Allows only manually imported users to authenticate.

        // Adldap\Laravel\Validation\Rules\OnlyImported::class,

    ],

    /*
    |--------------------------------------------------------------------------
    | Scopes
    |--------------------------------------------------------------------------
    |
    | Scopes allow you to restrict the LDAP query that locates
    | users upon import and authentication.
    |
    | All scopes must implement the following interface:
    |
    |   Adldap\Laravel\Scopes\ScopeInterface
    |
    */

    'scopes' => [

        // Only allows users with a user principal name to authenticate.

        Adldap\Laravel\Scopes\UpnScope::class,

    ],

    'usernames' => [

        /*
        |--------------------------------------------------------------------------
        | LDAP
        |--------------------------------------------------------------------------
        |
        | This is the LDAP users attribute that you use to authenticate
        | against your LDAP server. This is usually the users
        |'sAMAccountName' / 'userprincipalname' attribute.
        |
        | If you'd like to use their username to login instead, insert `samaccountname`.
        |
        */

        'ldap' => 'uid',

        /*
        |--------------------------------------------------------------------------
        | Eloquent
        |--------------------------------------------------------------------------
        |
        | This is the attribute that is used for locating
        | and storing the LDAP username above.
        |
        | If you're using a `username` field instead, change this to `username`.
        |
        | This option is only applicable to the DatabaseUserProvider.
        |
        */

        'eloquent' => 'username',

    ],

    /*
    |--------------------------------------------------------------------------
    | Login Fallback
    |--------------------------------------------------------------------------
    |
    | The login fallback option allows you to login as a user located on the
    | local database if active directory authentication fails.
    |
    | Set this to true if you would like to enable it.
    |
    | This option must be true or false and is only
    | applicable to the DatabaseUserProvider.
    |
    */

    'login_fallback' => env('ADLDAP_LOGIN_FALLBACK', false),

    /*
    |--------------------------------------------------------------------------
    | Password Sync
    |--------------------------------------------------------------------------
    |
    | The password sync option allows you to automatically synchronize
    | users AD passwords to your local database. These passwords are
    | hashed natively by laravel using the bcrypt() method.
    |
    | Enabling this option would also allow users to login to their
    | accounts using the password last used when an AD connection
    | was present.
    |
    | If this option is disabled, the local user account is applied
    | a random 16 character hashed password, and will lose access
    | to this account upon loss of AD connectivity.
    |
    | This option must be true or false and is only applicable
    | to the DatabaseUserProvider.
    |
    */

    'password_sync' => env('ADLDAP_PASSWORD_SYNC', true),

    /*
    |--------------------------------------------------------------------------
    | Windows Auth Attribute
    |--------------------------------------------------------------------------
    |
    | This array represents how a user is found when
    | utilizing the Adldap Windows Auth Middleware.
    |
    | The key of the array represents the attribute that the user is located by.
    |
    |     For example, if 'samaccountname' is the key, then your LDAP server is
    |     queried for a user with the 'samaccountname' equal to the value of
    |     $_SERVER['AUTH_USER'].
    |
    |     If a user is found, they are imported (if using the DatabaseUserProvider)
    |     into your local database, then logged in.
    |
    | The value of the array represents the 'key' of the $_SERVER
    | array to pull the users username from.
    |
    |    For example, $_SERVER['AUTH_USER'].
    |
    | This must be an array with a key - value pair.
    |
    */

    'windows_auth_attribute' => ['samaccountname' => 'AUTH_USER'],

    /*
    |--------------------------------------------------------------------------
    | Sync Attributes
    |--------------------------------------------------------------------------
    |
    | Attributes specified here will be added / replaced on the user model
    | upon login, automatically synchronizing and keeping the attributes
    | up to date.
    |
    | The array key represents the Laravel model key, and the value
    | represents the users LDAP attribute.
    |
    | This option must be an array and is only applicable
    | to the DatabaseUserProvider.
    |
    */

    'sync_attributes' => [

        'username' => 'uid',
        'name' => 'cn',

    ],

];

**Comment by anukwgl** [comment]
auth.php
 'providers' => [
        'users' => [
            'driver' => 'adldap',
            'model' => App\User::class,
        ],
logincontroller

    public function username()
    {
        return 'username';
    }

**Comment by anukwgl** [comment]
Is there anything i need to change?

**Comment by stevebauman** [comment]
Hi @anukwgl, please don't open multiple issues containing the same issue.

I will assist you momentarily.

**Comment by anukwgl** [comment]
sure, sorry about it Thank you.

**Comment by stevebauman** [comment]
Hi @anukwgl, your configuration is fine, except one option, the `account_suffix` option:

```php
'account_suffix' => env('ADLDAP_ACCOUNT_SUFFIX', ',dc=example,dc=com'),
```

Unfortunately, OpenLDAP requires you to authenticate with the users entire DN. Right now, Adldap2-Laravel doesn't support OpenLDAP accounts of other OU's.

For this LDAP test server, you can only authenticate users in specific OU's.

To authenticate as a "scientist", you need to insert this `ou` into your `account_suffix` option:

```php
'account_suffix' => env('ADLDAP_ACCOUNT_SUFFIX', 'ou=scientists,dc=example,dc=com'),
```

Then you can authenticate with any of the following users:

- einstein
- newton
- galieleo
- tesla

But you will not be able to authenticate with:

- riemann
- gauss
- euler
- euclid

This is due to them being located inside a different OU.

I'm working on more flexibility right now to further OpenLDAP compatibility.

**Comment by anukwgl** [comment]
Thank you @stevebauman 
I cant even login with the scientists users: It still says these credentials do not match the record.

**Comment by stevebauman** [comment]
Sorry, there's a missing comma:

```php
'account_suffix' => env('ADLDAP_ACCOUNT_SUFFIX', ',ou=scientists,dc=example,dc=com'),
```

**Comment by anukwgl** [comment]
But This is not what exactly I want to work on I just wanted to test the adldap as am new to this authentication. I want to work on Ldap sever which throws the same error. There is the adLogin.php now I want to authenticate it with laravel. here is the code, from which i wanted to work on adldap laravel. please help me with this. I have posted the code with sensitive details removed.
function adLogin($username , $password)
{

    $adServer = "ldap://ipaddress";
    $ldap = ldap_connect($adServer);
    $ldaprdn = 'abc' . "\\" . $username;

    ldap_set_option($ldap, LDAP_OPT_PROTOCOL_VERSION, 3);
    ldap_set_option($ldap, LDAP_OPT_REFERRALS, 0);

    $bind = @ldap_bind($ldap, $ldaprdn, $password);


    if ($bind) {
        $filter="(sAMAccountName=$username)";
        $result = ldap_search($ldap,"dc=abc,dc=lmn",$filter);
        ldap_sort($ldap,$result,"sn");
        $info = ldap_get_entries($ldap, $result);
        for ($i = 0; $i < $info["count"]; $i++) {
            if ($info['count'] > 1)
                break;
            /*          echo "<p>You are accessing <strong> ". $info[$i]["sn"][0] .", " . $info[$i]["givenname"][0] ."</strong><br /> (" . $info[$i]["samaccountname"][0] .")</p>\n";
                        echo '<pre>';
                        var_dump($info);
                        echo '</pre>';
                        $userDn = $info[$i]["distinguishedname"][0];
            */
            error_log("returning true");
            return true;
        }
        @ldap_close($ldap);
    } else {
        error_log("returning false");
      return false;
    }

}

**Comment by anukwgl** [comment]
adldap.php
<?php

return [

   

    'connections' => [

        'default' => [

         

            'auto_connect' => true,

          

            'connection' => Adldap\Connections\Ldap::class,

         

            'schema' => Adldap\Schemas\ActiveDirectory::class,

         

            'connection_settings' => [

              

               'account_prefix' => env('ADLDAP_ACCOUNT_PREFIX', 'abc\\'),
			 

               
                

                'account_suffix' => env('ADLDAP_ACCOUNT_SUFFIX', '@abc.lmn'),
		



              'domain_controllers' => explode(' ', env('ADLDAP_CONTROLLERS', 'ipaddress')),
             


              

                'port' => env('ADLDAP_PORT', 389),

             

                'timeout' => env('ADLDAP_TIMEOUT', 5),

             

            'base_dn' => env('ADLDAP_BASEDN', 'dc=abc,dc=lmn'),
			
				

              

               'admin_account_suffix' => env('ADLDAP_ADMIN_ACCOUNT_SUFFIX', ''),
				
				
              

                'admin_username' => env('ADLDAP_ADMIN_USERNAME', '*******'),
               'admin_password' => env('ADLDAP_ADMIN_PASSWORD', '*******'),
			

			   

             

                'follow_referrals' => false,

             

                'use_ssl' => false,
                'use_tls' => false,

            ],

        ],

    ],

];

**Comment by anukwgl** [comment]
adldap_auth
<?php

return [

  

    'connection' => env('ADLDAP_CONNECTION', 'default'),

 

    'provider' => Adldap\Laravel\Auth\DatabaseUserProvider::class,

   

    'resolver' => Adldap\Laravel\Auth\Resolver::class,

    

    'importer' => Adldap\Laravel\Auth\Importer::class,

   

    'rules' => [

        // Denys deleted users from authenticating.

        Adldap\Laravel\Validation\Rules\DenyTrashed::class,

        // Allows only manually imported users to authenticate.

        // Adldap\Laravel\Validation\Rules\OnlyImported::class,

    ],

   

    'scopes' => [

        // Only allows users with a user principal name to authenticate.

        Adldap\Laravel\Scopes\UpnScope::class,

    ],

    'usernames' => [

      

        'ldap' => 'samaccountname',
 

      

        'eloquent' => 'username',

    ],

    

    'login_fallback' => env('ADLDAP_LOGIN_FALLBACK', false),

  
    

    'password_sync' => env('ADLDAP_PASSWORD_SYNC', true),

 

    'windows_auth_attribute' => ['samaccountname' => 'AUTH_USER'],




    'sync_attributes' => [

       
		'username' => 'samaccountname',
        'name' => 'cn',

    ],

];

**Comment by anukwgl** [comment]
Login controller.php
<?php

namespace App\Http\Controllers\Auth;

use App\Http\Controllers\Controller;
use Illuminate\Foundation\Auth\AuthenticatesUsers;
use Illuminate\Http\Request;


class LoginController extends Controller
{
    /*
    |--------------------------------------------------------------------------
    | Login Controller
    |--------------------------------------------------------------------------
    |
    | This controller handles authenticating users for the application and
    | redirecting them to your home screen. The controller uses a trait
    | to conveniently provide its functionality to your applications.
    |
    */

    use AuthenticatesUsers;


    /**
     * Where to redirect users after login.
     *
     * @var string
     */
    protected $redirectTo = '/home';


    public function __construct()
    {
        $this->middleware('guest')->except('logout');
    }
    public function username()
    {
        return 'username';

    }

**Comment by anukwgl** [comment]
Logincontroller.php
  public function username()
    {
        return 'username';
    }
user.php
protected $fillable = [
        'name', 'username', 'password',
    ];
Changed in blade.php to username and also migrated to username in users table. But still it says these credentials don't match record

**Comment by anukwgl** [comment]
Do I need to change anything in login controller?

**Comment by anukwgl** [comment]
Is there anything I need to check or change to solve the issue?
