### ISSUE TITLE
Import users by group

### ISSUE THREAD

**Issue by netopvh** [Adldap2/Adldap2-Laravel#307]
- Laravel Version: 5.4
- Adldap2-Laravel Version: .3.0.4
- PHP Version: 7.0

### Description:

How to import users to database by group?
I'm using scopes, but i need help to import

**Comment by stevebauman** [comment]
Hi @netopvh, you can see the arguments in the command itself:

https://github.com/Adldap2/Adldap2-Laravel/blob/master/src/Commands/Import.php#L20-L25

To import users based on a group using the import command, type:

```php
php artisan adldap:import --filter="(memberof:1.2.840.113556.1.4.1941:=cn=MyGroup,dc=corp,dc=org)"
```
The following prefix shown above `memberof:1.2.840.113556.1.4.1941:` means it will query for all users inside the given group, as well as nested groups within that group.

Remove this if you just want immediate members imported:

```php
php artisan adldap:import --filter="(cn=MyGroup,dc=corp,dc=org)"
```
