### ISSUE TITLE
Quick start from scratch question

### ISSUE THREAD

**Issue by sheldonvic** [Adldap2/Adldap2-Laravel#308]
- Laravel Version: 5.3
- Adldap2-Laravel Version: 3.0.0
- PHP Version: 5.6.4

### Description:
hello a newbie to laravel, I followed the from quick from scratch documentation, got it to work, was able to authenticate against our AD and land on the dashboard. I see my account stored in the users model, but when I log in with another account, it just replaces my account info with the other account info. doesn't create a new row for the new user. Did I miss a step, a concept? or is that what the binding to the user model is about? or do i have to set true for login_fallback for it to add the user to the user table after first authentication? 

### Steps To Reproduce:
Follow quick from scratch instructions
use username versus email.

**Comment by stevebauman** [comment]
Hi, please update to the latest `v3.0.4` version and try again. Then let me know if you encounter the same issue.
