### ISSUE TITLE
Cant contact LDAP server (only with URL)

### ISSUE THREAD

**Issue by FroeMic** [Adldap2/Adldap2-Laravel#309]
- Laravel Version: 5.4
- Adldap2-Laravel Version: 3.0
- PHP Version: 7.0

### Description:
I am getting the standard Bind Exception (Can't contact LDAP server) when i try connecting to my LDAP server. 
- The weird thing is, if I replace  in `domain_controllers` the url `ldap.myurl.de` with the IP of the server `10.100.0.10` it suddenly works.
- I double checked the url (LDAP browser GUI, telnet), but I can't figure out how to solve this...

**Comment by stevebauman** [comment]
Strange, sounds like a networking / dns issue.

Some questions I have:

- Are you using SSL?
- Are you using OpenLDAP or ActiveDirectory?

Also, keep in mind that Adldap2 will automatically prefix each IP / hostname with `ldap://` or `ldaps://`.

https://github.com/Adldap2/Adldap2/blob/master/src/Connections/ConnectionInterface.php#L14-L26

**Comment by FroeMic** [comment]
Thanks for the quick reply. 

I am connecting to an **OpenLDAP 3 Server** without SSl. 

On top, I have to tunnel into a private network (OpenVPN) to access the server. Could it be that the URL is not resolved properly? (Note, pinging `ldap.myurl.de` works perfectly fine)

**Comment by stevebauman** [comment]
> Could it be that the URL is not resolved properly?

This would most likely be my thought. I encountered this issue with some VPN clients I've used if something isn't working right.

Can you try pinging `ldap://ldap.myurl.de:389`?

**Comment by FroeMic** [comment]
Indeed, `ping -p 389 ldap://ldap.myurl.de` fails. Seems to be an OpenVPN config issue.

Thanks for your help!

**Comment by stevebauman** [comment]
Okay great, thanks for following up!

No problem at all :).

**Comment by Gertiozuni** [comment]
I am having an issue on this. This is the tree i created [https://i.imgur.com/a5UPakB.png](https://i.imgur.com/a5UPakB.png) . Here is my env file 
`ADLDAP_ACCOUNT_PREFIX=uid=
ADLDAP_ACCOUNT_SUFFIX=,ou=users,dc=example,dc=com
ADLDAP_CONTROLLERS=localhost
ADLDAP_PORT=10389
ADLDAP_BASEDN=dc=example,dc=com
ADLDAP_ADMIN_ACCOUNT_PREFIX=uid=
ADLDAP_ADMIN_ACCOUNT_SUFFIX=,ou=system
ADLDAP_ADMIN_USERNAME=admin
ADLDAP_ADMIN_PASSWORD=secret`
 . Nothing else changed. Also this is my connection on apache directory studio [https://i.imgur.com/4IlgM2v.png](https://i.imgur.com/4IlgM2v.png) , [https://i.imgur.com/wpfRwnX.png](https://i.imgur.com/wpfRwnX.png)
