### ISSUE TITLE
missing inserted username to database

### ISSUE THREAD

**Issue by rishal08** [Adldap2/Adldap2-Laravel#312]
- Laravel Version: 5.4
- Adldap2-Laravel Version: 3.0
- PHP Version: 5.6

Dear Sir.

i've succesfully install adldap2, and everything ok.  authen againts AD it seems correct, and i had problems 
When the user is found in AD but not in the database and then they insert it , except the username , would you help to show where I should look inside, to fix it,

thank you so much. and sorry for bad english.

my user model :

```php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Adldap\Laravel\Traits\HasLdapUser;
use Illuminate\Database\Eloquent\SoftDeletes;

class User extends Authenticatable
{
    use Notifiable;
    use SoftDeletes, HasLdapUser;


    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'username', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}
```

``` 
public function up()
    {
        Schema::create('users', function (Blueprint $table) {
            $table->increments('id');
            $table->string('name');
            $table->string('username')->unique();
            $table->string('password');
            $table->rememberToken();
            $table->timestamps();
        });
    }
```

login controller

```php
<?php

namespace App\Http\Controllers\Auth;

use App\Http\Controllers\Controller;
use Illuminate\Foundation\Auth\AuthenticatesUsers;

class LoginController extends Controller
{
    /*
    |--------------------------------------------------------------------------
    | Login Controller
    |--------------------------------------------------------------------------
    |
    | This controller handles authenticating users for the application and
    | redirecting them to your home screen. The controller uses a trait
    | to conveniently provide its functionality to your applications.
    |
    */

    use AuthenticatesUsers;

    /**
     * Where to redirect users after login.
     *
     * @var string
     */
    protected $redirectTo = '/';
    
     /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('guest')->except('logout');
    }
    public function username()
    {
        return 'username';
    }
}
```

**Comment by stevebauman** [comment]
Hi @rishal08, this is done through the `sync_attributes` option in your `config/adldap_auth.php` file:

https://github.com/Adldap2/Adldap2-Laravel/blob/master/src/Config/auth.php#L249-L271

    'sync_attributes' => [
        'email' => 'userprincipalname',
        'name' => 'cn',
    ],

In your case, you should insert:

    'sync_attributes' => [
        'username' => 'samaccountname', // Assuming you're using 'samaccountname'.
        'name' => 'cn',
    ],

If you encounter any further issues, let me know. :)

**Comment by rishal08** [comment]
thank you sooo much. sir... it works like a charm. again thank you so much. 
I have been thinking about 3 days how to fix it, wow amazing...  thank you soo much.

**Comment by stevebauman** [comment]
No problem! Glad I could help :smile:

**Comment by rishal08** [comment]
one question again , i'm migrate my application to production environment behind proxy server, with same flow above, if authen againts AD passed and no record on db then register user to database. the process working fine if user accessing from outside proxy server, and then when user accessing inside network. authen always reject even if the user id and password AD is correct..

**Comment by stevebauman** [comment]
How are you authenticating? Are you using the `WindowsAuthenticate` middleware?

This sounds like a networking issue...

**Comment by rishal08** [comment]
WindowsAuthenticate

**Comment by stevebauman** [comment]
Are you hosting with IIS on Windows server? This sounds like an issue with your proxy

**Comment by rishal08** [comment]
yes IIS. and windows server 2008

**Comment by rishal08** [comment]
But the application runs normally if there is a user record  :). oke thank a lot.

**Comment by stevebauman** [comment]
Ok, yea unfortunately I can't be of much help with this. I would need access to your server and knowledge of your network environment to assist you.

No problem!
