### ISSUE TITLE
Attribute Handler Fails

### ISSUE THREAD

**Issue by infernobass7** [Adldap2/Adldap2-Laravel#313]
- Laravel Version: 5.4
- Adldap2-Laravel Version: 3.0.4
- PHP Version: 7.1

### Description:
I recently updated to version 3.0.4. I wanted to try out the handler to see if it would work to set extra data that is not defined in the AD but I want to use it on the User model. I tried to do my first import and it failed saying that ksort was expecting array but got null, string, or integer. The first time I got this error was because the user I was importing did not have a middle name set on the AD. I fixed this by passing an array with one element, "". Then it gave me an error on the attribute that I wanted to set myself. Now it is throwing the same error, when trying to import the password for the user.

### Steps To Reproduce:
1. Install Adldap2-laravel
2. Setup attribute sync to be handled by a handler
3. Try to import a user.

**Comment by stevebauman** [comment]
Hi @infernobass7, can you post your code of the handler and your `config/adldap_auth.php` file that contains the attribute handler?

**Comment by infernobass7** [comment]
Handler:
```
<?php

namespace App\Handlers;

use App\Models\Auth\User as EloquentUser;
use Adldap\Models\User as LdapUser;

class LdapAttributeHandler {

	/**
	* Synchronizes ldap attributes to the specified model.
	*
	* @param LdapUser     $ldapUser
	* @param EloquentUser $eloquentUser
	*
	* @return void
	*/
	public function handle(LdapUser $ldapUser, EloquentUser $eloquentUser)
	{
		$eloquentUser->display_name = $ldapUser->getAttribute('cn');
		$eloquentUser->email = $ldapUser->getAttribute('mail');
		$eloquentUser->first_name = $ldapUser->getAttribute('givenname');
		$eloquentUser->middle_name = $ldapUser->getAttribute('middlename') ?: [''];
		$eloquentUser->last_name = $ldapUser->getAttribute('sn');
		$eloquentUser->ldap_user = [1];
	}
}
```

**Comment by infernobass7** [comment]
adldap_auth:
```
<?php

return [
    'connection' => env('ADLDAP_CONNECTION', 'default'),
    'provider' => Adldap\Laravel\Auth\DatabaseUserProvider::class,
    'resolver' => Adldap\Laravel\Auth\Resolver::class,
    'importer' => Adldap\Laravel\Auth\Importer::class,
    'rules' => [
        // Denys deleted users from authenticating.
        Adldap\Laravel\Validation\Rules\DenyTrashed::class,
        // Allows only manually imported users to authenticate.
        // Adldap\Laravel\Validation\Rules\OnlyImported::class,
    ],
    'scopes' => [
        // Only allows users with a user principal name to authenticate.
        Adldap\Laravel\Scopes\UpnScope::class,
    ],
    'usernames' => [
        'ldap' => 'samaccountname',
        'eloquent' => 'username',
    ],
    'login_fallback' => env('ADLDAP_LOGIN_FALLBACK', true),
    'password_sync' => env('ADLDAP_PASSWORD_SYNC', true),
    'windows_auth_attribute' => ['samaccountname' => 'AUTH_USER'],
    'sync_attributes' => [
		App\Handlers\LdapAttributeHandler::class,
    ],
];
```

**Comment by stevebauman** [comment]
The attributes you're pulling will all be arrays, which is causing your import to fail. Eloquent can't save arrays on your User model:

```php
public function handle(LdapUser $ldapUser, EloquentUser $eloquentUser)
{
    $eloquentUser->display_name = $ldapUser->getAttribute('cn');
    $eloquentUser->email = $ldapUser->getAttribute('mail');
    $eloquentUser->first_name = $ldapUser->getAttribute('givenname');
    $eloquentUser->middle_name = $ldapUser->getAttribute('middlename') ?: [''];
    $eloquentUser->last_name = $ldapUser->getAttribute('sn');
    $eloquentUser->ldap_user = [1];
}
```

You'll need to use the `getFirstAttribute()` method:

```php
public function handle(LdapUser $ldapUser, EloquentUser $eloquentUser)
{
    $eloquentUser->display_name = $ldapUser->getFirstAttribute('cn');
    $eloquentUser->email = $ldapUser->getFirstAttribute('mail');
    $eloquentUser->first_name = $ldapUser->getFirstAttribute('givenname');
    $eloquentUser->middle_name = $ldapUser->getFirstAttribute('middlename') ?: '';
    $eloquentUser->last_name = $ldapUser->getFirstAttribute('sn');
    $eloquentUser->ldap_user = true;
}
```

**Comment by infernobass7** [comment]
Then why do I get the error when trying to import the password?

**Comment by stevebauman** [comment]
> Then why do I get the error when trying to import the password?

What do you mean? Are you performing this sync yourself?

**Comment by infernobass7** [comment]
Nevermind. Before I changed to the getFirstAttribute. I was getting the same error about ksort when it was trying to pull in the password.

**Comment by stevebauman** [comment]
Ok, if you encounter any further issues just give me a shout :smile:

**Comment by infernobass7** [comment]
@stevebauman I am not sure what is causing this issue but I have a seeder that adds companies to the DB then grabs all defined developers and imports their user models from AD. For some reason the import gets hung up at the import.

```
$companies->each(function($company) {
			$company = Company::create($company);
			$company->addAddress(App\Models\General\Address::where('line_1', '312 East Meadow Valley Road')->first());
			if($company->users->count() == 0) {
				collect(config('auth.developers'))->each(function($item) use($company) {
					if(!(User::find($item)) ) {
						\Artisan::call('adldap:import', ['user' => "{$item}"]);
					}

					User::find($item)->allow($company);
				});
			}
		});
```

**Comment by infernobass7** [comment]
Also, I have set up the login screen to default to the database and if not found it goes to AD and imports the user. It imports the user. However, I always get an error trying to authenticate. When I try out the hash from the DB in this [calculator](https://www.dailycred.com/article/bcrypt-calculator) it tells me "invalid salt revision"

**Comment by stevebauman** [comment]
You need to specify the `--no-interaction` parameter with the artisan call since the import command will ask questions. This is why it hangs, since it's waiting on a response to a question that's been asked.

https://github.com/Adldap2/Adldap2-Laravel/issues/283

```php
\Artisan::call('adldap:import', ['user' => "{$item}", '--no-interaction]);
``

**Comment by stevebauman** [comment]
> Also, I have set up the login screen to default to the database and if not found it goes to AD and imports the user. It imports the user. However, I always get an error trying to authenticate. When I try out the hash from the DB in this calculator it tells me "invalid salt revision"

How is this import done? How are you hashing the passwords for these imported users?

**Comment by infernobass7** [comment]
I am just using the password sync. So it is something in the default importer.

**Comment by stevebauman** [comment]
Are you sure? This makes me think otherwise:

> Also, I have set up the login screen to default to the database and if not found it goes to AD and imports the user.

How did you setup authentication to "default to the database"? Did you just enable `login_fallback` in your `config/adldap_auth.php` file? Or did you perform this another way?

**Comment by infernobass7** [comment]
This is my controller method to log them in.

```
if ($this->guard()->attempt($this->credentials($request), $request->has('remember'))) {
	return true;
}

if(! User::find($request->username) && Adldap::search()->users()->where('samaccountname', $request->username)) {
    	\Artisan::call('adldap:import',['user' => $request->username, '--no-interaction']);
	\Auth::guard('ldap')->attempt($this->credentials($request), $request->has('remember'));

	if ($this->guard()->attempt($this->credentials($request), $request->has('remember'))) {
		return true;
	}
}

if($user = User::find($request->username)){
	$this->incrementLoginAttempts($request);
}

return false;
```

**Comment by stevebauman** [comment]
Yea, that isn't going to synchronize passwords. You need to utilize the actual Adldap2 auth driver for this.

https://github.com/Adldap2/Adldap2-Laravel/blob/master/docs/auth/installation.md

Importing users with the `adldap:import` command assigns a random unique password for imported users, because we don't have access to the users password with the command.

See:

https://github.com/Adldap2/Adldap2-Laravel/blob/master/src/Commands/Import.php#L86-L93

In your case above, you'll need to set the users password manually after they've been imported.

Also, you seem to have another guard instance set up for LDAP authnetication?

```php
\Auth::guard('ldap')->attempt($this->credentials($request), $request->has('remember'));
```

This isn't an issue with the importer.

**Comment by infernobass7** [comment]
Basically I only want to hit the ldap connection when the user has not logged in to system before.

**Comment by stevebauman** [comment]
This is most likely because the user already exists with an invalid password. You'll need to delete the user and probably re-authenticate and set their password manually.

Unfortunately I can't help outside of what Adldap2-Laravel provides. These types of solutions will require your sole development and support.
