### ISSUE TITLE
Connection is unsuccessful when using SSL or TLS "Can't contact LDAP server"

### ISSUE THREAD

**Issue by tarreislam** [Adldap2/Adldap2-Laravel#318]
- Laravel Version: 5.2.* (Latest as of today)
- Adldap2-Laravel Version: 3.0.* (Latest as of today)
- PHP Version: 7.0.9
- Domain controller: 2012 r2 with AD CS enterprice CA 

### Description:
When connecting with SSL \ TLS, i recive an "Can't contact LDAP server" error, if i run without it, there is no problem, I have connected with an 3rd party application called "LDAP Admin" and successfully connected with both SSL and TLS to the same server from the same server my Laravel app is hosted on.

Ports used 
ssl@636
tls\nonsecure@389

**Comment by stevebauman** [comment]
Hi @tarreislam, unfortunately TLS and SSL can be difficult to configure in PHP.

When no contact can be made to your LDAP server when using SSL/TLS, this is most likely a configuration issue in PHP itself.

You may need to insert this into your `AppServiceProvider` in the register / boot method:

```php
putenv(‘LDAPTLS_CIPHER_SUITE=NORMAL:!VERS-TLS1.2’);
```

As noted in the comment here:

http://php.net/manual/en/function.ldap-bind.php#118543

Or, you may need to insert this for TLS connectivity:

```php
putenv("TLS_CACERT=/path/to/certificate");
putenv("TLS_REQCERT=never");
```

Your application you're utilizing is most likely not PHP based, but incorporates other solutions for connecting via SSL / TLS.

Can you try the following suggestions above?

I would also suggest reviewing the comments on the `ldap_bind` method in PHP docs as many commenters have resolutions for connecting via SSL / TLS:

http://php.net/manual/en/function.ldap-bind.php

**Comment by tarreislam** [comment]
Hello again.

I tried to put this in my boot\register in my `AppServiceprovider`
```php
        putenv("LDAPTLS_CIPHER_SUITE=NORMAL:!VERS-TLS1.2");
        putenv("TLS_CACERT=c:/SS-ROOT.crt");
        putenv("TLS_REQCERT=never");
        $_ENV['LDAPTLS_CIPHER_SUITE'] = "NORMAL:!VERS-TLS1.2";
        $_ENV['TLS_REQCERT'] = "never";
        $_ENV['TLS_CACERT'] = "c:/SS-ROOT.crt";
```
Also I tried (Form my dev machine running windows) creating `C:\OpenLDAP\sysconf\ldap.conf` as suggested from [http://php.net/manual/en/function.ldap-bind.php](http://php.net/manual/en/function.ldap-bind.php)
```
TLS_REQCERT	never
TLS_CACERT	c:/SS-ROOT.crt
```
but still no luck.

**Comment by Albvadi** [comment]
Same here.

I solved it, disabling the tls request.

Add in the `config\adldap.php` inside the `connection_settings` on your server options, after `use_tls`:
```php
/*
|--------------------------------------------------------------------------
| SSL & TLS
|--------------------------------------------------------------------------
|
| If you need to be able to change user passwords on your server, then an
| SSL or TLS connection is required. All other operations are allowed
| on unsecured protocols.
| 
| One of these options are definitely recommended if you 
| have the ability to connect to your server securely.
|
*/
'use_ssl' => true,
'use_tls' => false,

'custom_options' => [
    // See: http://php.net/ldap_set_option
    LDAP_OPT_X_TLS_REQUIRE_CERT => LDAP_OPT_X_TLS_NEVER
]
```

**Comment by tarreislam** [comment]
@Albvadi Hey, thats pretty good! I will try this asap.

**Comment by stevebauman** [comment]
Thanks so much @Albvadi, really appreciate your help here! Unfortunately I'm not experienced in OpenLDAP, so this is MUCH appreciated.

**Comment by bahman2216** [comment]
Im using successful in windows 7 with wamp64, But I move all my projects and database on Centos 7. It is not work.
`BindException in Guard.php line 80:
Can't contact LDAP server`

Have you any idea?

**Comment by tarreislam** [comment]
@Albvadi this also worked for me, sorry for late answer :) +1

**Comment by stevebauman** [comment]
Thanks for following up @tarreislam.

@bahman2216, if you're still experiencing issues please create a new issue, thanks!
