### ISSUE TITLE
Soft-deletion of disabled/deleted users

### ISSUE THREAD

**Issue by moth** [Adldap2/Adldap2-Laravel#319]
- Laravel Version: 5.2
- Adldap2-Laravel Version: 3.0.*
- PHP Version: 5.6

I've been looking to use the `--delete` option on my importer. I'm a bit confused because we do have a lot of disabled users (as opposed to deleted) and this doesn't appear to pick them up.

I have soft-deletes on the User model.

I suspect that might be the manner in which my IT team are "disabling" people. Is there more than one way to go about this that you know of from the LDAP side? I just need some ammunition to go back to them with.

**Comment by stevebauman** [comment]
Hi @moth,

The `--delete` flag will check to see if the users user account control is equal to `514`. If your IT is basically right clicking users and selecting `Disable` in AD Explorer, then it will set this flag to 514.

I don't believe there's another way they could be disabling users... Though if there is, there's always the option of running your own command against your AD server and checking each users attributes and soft deleting the related users model if it matches your criteria.

**Comment by moth** [comment]
Interesting. I have a bunch of users where `useraccountcontrol` is set to 514, but I'm afraid it's not soft-deleting them.

Is there a spot in the code where I can attempt to debug this?

**Comment by stevebauman** [comment]
There's a couple things we can check. First, can you post your `User.php` model?

Also, can you locate a user who is 100% verified to be disabled, and see what Adldap2 returns? For example:

```php
$user = Adldap::search()->users()->whereEquals('cn', 'disabled-user')->first();

dd($user->isDisabled()); // Should return true.
```

**Comment by moth** [comment]
You know what - I've figured it out. We're removing some user attributes in LDAP at the point of "deletion" - the disabled users are not showing up in my custom filter ;)

Thanks - and sorry!

**Comment by stevebauman** [comment]
Perfect, glad you've resolved it! No problem at all :), thanks for following up.
