### ISSUE TITLE
LDAP Auth Only (No Database Synchronization)

### ISSUE THREAD

**Issue by fatalh** [Adldap2/Adldap2-Laravel#321]
- Laravel Version: 5.4
- Adldap2-Laravel Version: 3.0.4
- PHP Version: 5.6

### Description:
Hi @stevebauman , Thanks you to help me again .
 I have imported  and synchronized all the users of the AD in my database and all is good with that type of  connection. But now I want to try connection without Database ( Just allow connection if user and password match in the AD, and no more with Database ). I read the documenation and I saw I have to set 'provider' => Adldap\Laravel\Auth\NoDatabaseUserProvider::class in  my config/adldap_auth.php ,  I did it . However, I don't know how to re-write the default Laravel views that are generated with the php artisan make:auth .

**Comment by stevebauman** [comment]
Hi @fatalh, you should be able to use the same configuration.

Are you encountering any errors?

**Comment by fatalh** [comment]
Well, I have no error, no messages  with the new app what I want with No database connection. But in the old app where I connected with the users imported in the database, I just set set 'provider' => Adldap\Laravel\Auth\NoDatabaseUserProvider::class in my config/adldap_auth.php .
And I have this error  ""  Trying to get property of non-object  ""

**Comment by fatalh** [comment]
When I try to connect with a good username and wrong password , I have this ""  These credentials do not match our records. "" ... but when I try with a good username and good password , it loads and come back to the same login page with the form empty !

**Comment by fatalh** [comment]
The thing is I don't understand this part in  NoDatabaseUserProvider Documentation :  **Note: You will have to re-write the default Laravel views that are generated with the php artisan make:auth command if you utilize this provider.**   What we need to do  ?

**Comment by fatalh** [comment]
@stevebauman , seems you forgot me !!!

**Comment by fatalh** [comment]
I am still thinking how to fix the problems , please help @stevebauman

**Comment by stevebauman** [comment]
Hi @fatalh,

When I mention "You will have to re-write the default Laravel views that are generated with the php artisan make:auth command if you utilize this provider.", it means you'll need to change code where `Auth::user()` is used in Laravels default views.

For example, in the default views for Laravel, `Auth::user()->name` is specified. This will need to be rewritten to `Auth::user()->getCommonName();` since the actual authenticated user will not be your `User.php` model that is shipped with Laravel.

I cannot guide you through how to configure your LDAP connection, as this is different for each environment.

**Comment by lusaczek** [comment]
Hi,
Please explain to me how to use this provider (Adldap\Laravel\Auth\NoDatabaseUserProvider::class) :)
I don't have file config/adldap_auth.php.
All configuration for AD auth I have in config/adldap.php (config array)
In config/app.php I have "providers" 
        Adldap\Laravel\AdldapServiceProvider::class,
        Adldap\Laravel\AdldapAuthServiceProvider::class,

If I put Adldap\Laravel\Auth\NoDatabaseUserProvider::class on app.php I have exception

(1/1) FatalErrorExceptionCall to undefined method Adldap\Laravel\Auth\NoDatabaseUserProvider::isDeferred()
--
in ProviderRepository.php (line 149)

What am I doing wrong?

**Comment by fatalh** [comment]
Hello @stevebauman,
I have created a new laravel app where I am testing connection without database.  I followed the documentation but I think there is something I missed. When I try to login with a wrong password , I have " The credentials do match ",  but when I try to connect with the right username and password , it is redirecting to the same login page. Where you  think the problem is ?
Well, I did not  run php artisan migrate as I think I won't use the database, just to want to give access to users through AD connection.

**Comment by stevebauman** [comment]
Sounds like you may have an issue with your LoginController or it's not keeping your session.

> Well, I did not run php artisan migrate as I think I won't use the database, just to want to give access to users through AD connection.

What session driver are you using? If you're using the database driver for sessions then you will need a database.

**Comment by riyazpt** [comment]
Auth::user()->getCommonName(); Exception thrown since Auth::user() returns Null.But with Correct Credentials I am able to Login
 if(Adldap::auth()->attempt($userdn, $password, $bindAsUser = true)) 
{
Auth::user()->getCommonName(); //Returns Null
}

**Comment by stevebauman** [comment]
@riyazpt, using `Adldap::auth()->attempt()` only calls an `ldap_bind` on your LDAP server, it does not set up a Laravel session and log users in. You need to utilize the `adldap` auth driver and follow the usage describe there:

https://github.com/Adldap2/Adldap2-Laravel/blob/master/docs/auth.md#installation

**Comment by riyazpt** [comment]
Thank you, i will try that.
Next query is
User dsn from multple domain
Example
Some users may be of domain abc

Username =abc\\riyaz

Some users may be of differnt domain

such as
Username=efg\\steve
How to set this

**Comment by SakethaKrishna** [comment]
@stevebauman how do I set up my provider in auth.php if I'm not using any database to authenticate.
I'm using ldap connection to authenticate the user (Adldap::auth()->attempt($userdn, $password, $bindAsUser = true)). I want  to set up a costume guard in order to create my own Auth::check to use in blade templating
 'providers' => [
        'users' => [
            'driver' => 'ldap',
           
        ],

this is how my provider looks right now. No Model
