### ISSUE TITLE
Sync Array only retrieves first item.

### ISSUE THREAD

**Issue by JuiceCreative** [Adldap2/Adldap2-Laravel#323]
- Laravel Version: 5.4
- Adldap2-Laravel Version: 3.0
- PHP Version: 7.1

### Description:
Trying to sync the memberof field to a database column, however it's only saving the first item in the member field.
I've found in ImportsUsers.php the handleAttributeRetrieval forces just the first item to be saved. 
Unsure on how to override this in my app without changing the vendor files.

### Steps To Reproduce:
php artisan adldap:import with a user that has more than 1 memberof items with the sync_attributes active for that field

**Comment by stevebauman** [comment]
Hi @JuiceCreative, this is intended.

You'll need to create an attribute handler for this scenario described here:

https://github.com/Adldap2/Adldap2-Laravel/blob/master/docs/auth/syncing.md#attribute-handlers

Once you create on and insert the handler, you can sync the `memberof` attribute:

```php
public function handle(LdapUser $ldapUser, EloquentUser $eloquentUser)
{
    $eloquentUser->name = $ldapUser->getCommonName();
    $eloquentUser->memberof = json_encode($ldapUser->getMemberOf());
}
```

**Comment by JuiceCreative** [comment]
Now getting an issue the same as #305 
  ```
 'sync_attributes' => [
        'name' => 'cn',
	    'department' => 'department',
	    'telephone' => 'mobile',
	    'extension' => 'telephonenumber',
	    'email' => 'mail',
	    App\Handlers\LdapAttributeHandler::class,
    ],
```

In my app\Handlers\LdapAttributeHandler.php
```
<?PHP
namespace App\Handlers;

use App\User as EloquentUser;
use Adldap\Models\User as LdapUser;

class LdapAttributeHandler
{
	/**
	 * Synchronizes ldap attributes to the specified model.
	 *
	 * @param LdapUser     $ldapUser
	 * @param EloquentUser $eloquentUser
	 *
	 * @return void
	 */
	public function handle(LdapUser $ldapUser, EloquentUser $eloquentUser)
	{
		dd('We get this far');
		$eloquentUser->groups = json_encode($ldapUser->getMemberOf());
	}

}
```

Cleared all the caches, and the DD never hits. 

```SQLSTATE[42S22]: Column not found: 1054 Unknown column '0' in 'field list' (SQL: update 'users' set 'password' = hashed, 'updated_at' = 2017-05-19 13:30:57, '0' = where 'id' = 209)```

**Comment by stevebauman** [comment]
Can you try only using the attribute handler and remove all other array values? For example:

```php
sync_attributes' => [
    App\Handlers\LdapAttributeHandler::class,
],
```

**Comment by JuiceCreative** [comment]
Same error, I had my original solution like that. 
It's anytime the handler class is added to the sync_attributes array.

**Comment by stevebauman** [comment]
Bizarre, just tried this and works fine as soon as I insert the handler into my config.

Going to try again with a fresh install and see if I encounter this.

**Comment by stevebauman** [comment]
Yup, works without issue on completely fresh install. After running through auth setup, just inserted the class into my config and works without clearing any caches or dumping composers autoload.

There must be something going on in your application.

**Comment by JuiceCreative** [comment]
Seemed to be a version issue, completely my fault. I thought I had updated but I was on a 2.* install.

After upgrading and republishing my configs it seems to be giving me something I can work with now. However $ldapUser->getMemberOf() throws an Undefined Method error, I assume this has been changed to getGroups()?

Thanks for your help!
