### ISSUE TITLE
Auth::attempt() and Adldap::search()->users() are not working

### ISSUE THREAD

**Issue by zhangchengshan** [Adldap2/Adldap2-Laravel#324]
- Laravel Version: 5.4
- Adldap2-Laravel Version: 3.0.4
- PHP Version: 7.0.10

### Description:
```Adldap::auth->attempt($username, $password, true)``` is ok, but ```Auth::attempt($credentials)``` is failed.
debug it, and found ```$query = $this->provider->search()->users``` in Resolver.php , the result is 
![image](https://cloud.githubusercontent.com/assets/6310213/26390065/81c5102c-408f-11e7-8ff0-65aeac85e986.png)
![image](https://cloud.githubusercontent.com/assets/6310213/26390077/8dc04d4c-408f-11e7-8c15-f6a385b4e1f7.png)
```$this->lastAttempted = $user = $this->provider->retrieveByCredentials($credentials);``` get $user is null
But, when i use ```Adldap::search->where('uid', '=', $username)->get()```, i can get the result.

Below is my config
```
# .env
ADLDAP_CONTROLLERS=ip
ADLDAP_BASEDN=ou=user,dc=rr-in,dc=tv
ADLDAP_ACCOUNT_PREFIX=uid=
ADLDAP_ACCOUNT_SUFFIX=,ou=user,dc=rr-in,dc=tv
ADLDAP_ADMIN_USERNAME=xxxx
ADLDAP_ADMIN_PASSWORD=xxxx
ADLDAP_ADMIN_ACCOUNT_PERFIX=cn=
ADLDAP_ADMIN_ACCOUNT_SUFFIX=,dc=rr-in,dc=tv
```
```
# adldap.php
'auto_connect' => true,
'connection' => Adldap\Connections\Ldap::class,
'schema' => Adldap\Schemas\OpenLDAP::class,
```
```
# adldap_auth.php
'username' => ['ldap' => 'uid', 'eloquent'=> 'name']
'sync_attributes' => ['email' => 'mail', 'name' => 'uid']
```
```
# auth.php
'providers' => [
        'users' => [
            'driver' => 'adldap',
            'model' => App\User::class,
        ],
]
```

**Comment by stevebauman** [comment]
Hi @zhangchengshan,

Are you authenticating users by their name and not email? Your configuration specifies this, so just need to know to help you further:

```php
'username' => ['ldap' => 'uid', 'eloquent'=> 'name']
```

**Comment by zhangchengshan** [comment]
@stevebauman thanks for your reply. As you say, i really use name to authenticate users. my ldap info is below
![image](https://cloud.githubusercontent.com/assets/6310213/26413640/2a864560-40df-11e7-92f1-e2b1e6d08d9b.png)
i have no idea for this problem.

**Comment by zhangchengshan** [comment]
@stevebauman maybe i find the reason, my openldap entry have no userprincipalname attribute, but in upnscope.php has ```$builder->whereHas($builder->getSchema()->userPrincipalName());```, and the userPrincipalName function return 'userprincipalname' is in ActiveDirectory.php. but i don't know why the function is called where is in ActiveDriectory.php, my schema set openldap.
```
# adldap.php
'schema' => Adldap\Schemas\OpenLDAP::class,
```
![image](https://cloud.githubusercontent.com/assets/6310213/26495733/4f4f1bf0-4257-11e7-9505-617b301fa144.png)

**Comment by stevebauman** [comment]
Since you're using OpenLDAP you need to remove the UPN Scope inside your adldap_auth.php file.

**Comment by zhangchengshan** [comment]
@stevebauman thanks, Auth::attempt is ok when remove the UPN Scope. But i still cannot login. I found the session attributes is false.
![image](https://cloud.githubusercontent.com/assets/6310213/26824973/da18fbf2-4ae5-11e7-9362-0fd69d4c47e2.png)
![qq 20170606182201](https://cloud.githubusercontent.com/assets/6310213/26824952/c8fcd690-4ae5-11e7-9fff-c062f97c2789.png)
![qq 20170606182123](https://cloud.githubusercontent.com/assets/6310213/26824956/cb7a102c-4ae5-11e7-938c-512d4ff43794.png)
![qq 20170606182241](https://cloud.githubusercontent.com/assets/6310213/26824941/bdc77cda-4ae5-11e7-9505-8afd0baabaf3.png)
![image](https://cloud.githubusercontent.com/assets/6310213/26825036/1d83e186-4ae6-11e7-8858-574451093268.png)
my openldap has no objectsid, so what can i do?

**Comment by stevebauman** [comment]
Hi @zhangchengshan, you must be using the `NoDatabaseUserProvider` in your `adldap_auth.php` if it's looking for the object's SID.

Is this correct?

**Comment by zhangchengshan** [comment]
@stevebauman Thanks a lot! I think I was successful.
