### ISSUE TITLE
Session

### ISSUE THREAD

**Issue by anukwgl** [Adldap2/Adldap2-Laravel#325]
- Laravel Version: 5.4

Description: Hello I have a problem, adldap is working perfectly. I can login with my credentials but my session is not expiring until I logout. Is there anything I need to change or do and I also tried changing lifetime and expire_on_close in config/session.php but nothing worked out.

**Comment by stevebauman** [comment]
Hi @anukwgl, sessions are all managed via Laravel and not Adldap2.

You will need to troubleshoot this in your application unfortunately, as this is a Laravel issue.
