### ISSUE TITLE
ldap_add(): Add: Invalid syntax when trying to create new user

### ISSUE THREAD

**Issue by strozzascotte** [Adldap2/Adldap2-Laravel#331]
- Laravel Version: 5.4.25
- Adldap2-Laravel Version: 3.0.4
- PHP Version: 7.0.15
- OpenLDAP

I've set up a fresh Laravel installation.
Set up default Laravel authentication (php artisan make:auth)
Added 'username' field to the users table and configured this as the authentication field
Configured adldap for authentication works ok and correctly create local users on-the-fly.

Now I want to register new user and create corresponding entry in the OpenLDAP directory.

I tried tu add these lines in the RegisterController.php
`$user = Adldap::make()->user([`
`   'uid'       => $data['username'],`
`   'cn'        => $data['name'],`
`   'mail'      => $data['email'],`
` ]);`
`$user->save();`

but I get this error:

> ldap_add(): Add: Invalid syntax in Ldap.php (line 270)
> 
> at HandleExceptions->handleError(2, 'ldap_add(): Add: Invalid syntax', '/var/www/dev-laravel/swing/vendor/adldap2/adldap2/src/Connections/Ldap.php', 270, array('dn' => 'cn=Ciccio Bombo Cannoniere,dc=mydomain,dc=org', 'entry' => array('uid' => array('ciccio'), 'cn' => array('Ciccio Bombo Cannoniere'), 'mail' => array('ciccio.bombo@something.com'), 'objectclass' => array('top', 'person', 'organizationalperson', 'user'))))
> 

Where am I wrong?

In **auth.php**
`    'providers' => [`
`        'users' => [`
 `           'driver' => 'adldap',`
  `          'model' => App\User::class,`
`        ],`

In **adldap_auth.php**
`'connection' => env('ADLDAP_CONNECTION', 'default'),`
`'provider' => Adldap\Laravel\Auth\DatabaseUserProvider::class,`
`'resolver' => Adldap\Laravel\Auth\Resolver::class,`
`'importer' => Adldap\Laravel\Auth\Importer::class,`
`'rules' => [],`
`'scopes' => [],`
`'usernames' => [`
`  'ldap' => 'uid',`
`  'eloquent' => 'username',`
`],`
`'login_fallback' => false,`
`'password_sync' => env('ADLDAP_PASSWORD_SYNC', true),`
`'sync_attributes' => [`
`  'username' => 'uid',`
`  'email' => 'mail',`
`  'name' => 'cn',`
`],`

**Comment by strozzascotte** [comment]
Well, I worked around the issue manually setting `dn`and `objectClass`, but the possibility of using custom model [(Allow more flexibility with using custom models. #367)](https://github.com/Adldap2/Adldap2/issues/367) would really help in my case.

        $user = Adldap::make()->user([
            'uid'           => $data['username'],
            'cn'            => $data['name'],
            'mail'          => $data['email'],
            'sn'            => $data['name'],
            'userpassword'  => $this->make_ssha_password($data['password']),
         ]);
        $user->setAttribute('objectclass', 'inetOrgPerson');
        $user->setDn('uid=' . $data['username'] . ',' . $user->getDnBuilder()->get());

        $user->save();

**Comment by stevebauman** [comment]
Thanks for the update @strozzascotte, very much appreciated.

This is definitely coming, I'm just trying to sort out the best implementation. Right now it's looking like these model definitions will be stored in the Schema since this object is utilized throughout.
