### ISSUE TITLE
adldap_auth.php not published

### ISSUE THREAD

**Issue by Albvadi** [Adldap2/Adldap2-Laravel#337]
- Laravel Version: 5.4.25
- Adldap2-Laravel Version: 3.0.4
- PHP Version: 7.0.9

### Description:
When installing the library, `config/adldap_auth.php` isn´t published by Artisan..

### Steps To Reproduce:
Run this command cli:
```bash
php artisan vendor:publish --tag="adldap"

//Result
Copied File [\vendor\adldap2\adldap2-laravel\src\Config\config.php] To [\config\adldap.php]
Publishing complete.
```

**Comment by stevebauman** [comment]
Hi @Albvadi, you need to insert the `AdldapAuthServiceProdivider` in your `config/app.php` file and then run `php artisan vendor: publish` for it to publish the auth config.

**Comment by Albvadi** [comment]
My bad...
Thanks for your super quick answer!

**Comment by stevebauman** [comment]
No problem! This is described in the auth driver setup:

https://github.com/Adldap2/Adldap2-Laravel/blob/master/docs/auth/installation.md#laravel-52--up
