### ISSUE TITLE
North Meets South Web Podcast

### ISSUE THREAD

**Issue by strebl** [Adldap2/Adldap2-Laravel#338]
Hey @stevebauman 

I talked to one of the Hosts of the North Meets South Web Podcast and mentioned your awesome package.
Now it got mentioned in the latest episode: http://www.northmeetssouth.audio/30.

Just opened the issue because I thought it may be interesting for you 🙂

Keep up your good work!

**Comment by stevebauman** [comment]
That's awesome @strebl! Thanks so much for sharing this, I'll give it a listen right now.

Really appreciate your kind words 😄
