### ISSUE TITLE
Artisan command adldap:import does not restore soft-deleted users.

### ISSUE THREAD

**Issue by HeyRatFans** [Adldap2/Adldap2-Laravel#339]
- Laravel Version: 5.3.31
- Adldap2-Laravel Version: 3.0.4
- PHP Version: 7.1.6

### Description:

When using the --restore option to the adldap:import command, the soft-deleted users are never restored. This is being caused by the [restore](https://github.com/Adldap2/Adldap2-Laravel/blob/master/src/Commands/Import.php#L253) method in Commands\Import.php never being called. Looks like it needs to be called after the isDeleting check on [line 95](https://github.com/Adldap2/Adldap2-Laravel/blob/master/src/Commands/Import.php#L95)

### Steps To Reproduce:

1. Run: artisan adldap:import to import users into your local application database.
2. Soft-delete any number of users created, using whatever method you deem suitable.
3. Run: artisan adldap:import again.

### Result:
Soft-deleted users are not restored and remain deleted with their deleted_at column set.

### Expected Outcome:
Soft-deleted users should be restored, i.e. their deleted_at column should be null.

**Comment by stevebauman** [comment]
Thanks @HeyRatFans, appreciate the report!

Will be in new release shortly.
