### ISSUE TITLE
What am I doing wrong (ErrorException on incorrect password)

### ISSUE THREAD

**Issue by gunnk** [Adldap2/Adldap2-Laravel#34]
Hi Steve -- First off, thanks for all your hard work on this package!

I've been trying for the last few days to get everything working correctly, but I'm hitting a snag. I spun a nice, clean "test" project with Laravel just to make sure I know how to get everything running properly. I was trying to use Auth methods, but kept getting errors, so I dropped back to the simplest case modifed from your readme documentation like so:

```
// Authenticating.
if (Adldap::authenticate($username, $password)) {
   echo "Passed!<br>";
} else {
   echo "Failed!<br>";
}
```

It works fine is the username and password are correct. If the password is incorrect, though, I the "Whoops, looks like something went wrong." with:

ErrorException in Ldap.php line 502
ldap_bind(): Unable to bind to server: Invalid credentials

That's not what I expected. Is this correct behavior that I need to catch and code for, or should it actually have echoed out "Failed!" as I intended?

Thanks,
Kevin

**Comment by stevebauman** [comment]
Hi @gunnk, if your application is in debug mode (in your `.env` file check `APP_DEBUG=true`), then LDAP errors will be shown by default. You can catch the exception:

```php
// Authenticating
try {
    if (Adldap::authenticate($username, $password)) {
       echo "Passed!<br>";
    } else {
       echo "Failed!<br>";
    }
} catch (\Exception $e) {
    // Binding exception
}
```

Or you can hide the errors using `Adldap::getConnection()->supressErrors();`.

I realize right now that this is inconsistent behavior and ugly when having your application in debug mode, however this has already been overhauled and removed in the upcoming `v6` version.

**Comment by gunnk** [comment]
Oh, wow... thanks Steve! It would never have dawned on me that debug mode was the culprit. I'll use suppressErrors() and get on with my work!

**Comment by stevebauman** [comment]
No problem at all! If you have any more questions or issues please create one and I'll respond as soon as possible.
