### ISSUE TITLE
Artisan command adldap2:import does not work if run as scheduled command.

### ISSUE THREAD

**Issue by HeyRatFans** [Adldap2/Adldap2-Laravel#340]
- Laravel Version: 5.3.31
- Adldap2-Laravel Version: 3.0.4
- PHP Version: 7.1.6

### Description:

When using [Laravel's Scheduler](https://laravel.com/docs/5.3/scheduling) to import users automatically, the command never imports any users because it prompts for confirmation which Laravel automatically answers negatively to. The same issue can be observed by using the --no-interaction option, if you'd rather not set up a schedule.

The reason for the scheduled command is so we can apply roles and permissions to them in the Laravel app, which unfortunately cannot be stored in an LDAP attribute as we don't have permission to do this.

I understand not wanting to proceed automatically with the import, as this might be destructive/problematic for the application database, but would it be possible to add a new option, i.e. --no-confirm or similar to allow the command to continue without confirmation?

Thanks.

### Steps To Reproduce:

1. Schedule the adldap2:import command to run periodically or run with the --no-interaction option.

### Result:
No users are imported. Command completes with the output:

`Found 1 user(s).
Okay, no users were imported / synchronized.`

### Expected Outcome:
Users should be imported successfully.

**Comment by stevebauman** [comment]
Hi @HeyRatFans, this is fixed in `dev-master` right now (https://github.com/Adldap2/Adldap2-Laravel/commit/b292b4ae8d7774450b383f1ae72995abae4317d6), however it will come in a `v3.1` release due to `dev-master` containing other breaking changes.
