### ISSUE TITLE
How to display user information from LDAP to web service

### ISSUE THREAD

**Issue by riskinovitasari** [Adldap2/Adldap2-Laravel#341]
laravel 5.4
adldap2/adldap2-laravel": "^3.0

hi Steve,

I am currently working on a project for my internship program. I created an ldap authentication with laravel 5.4 and adldap 3.
What I want to ask is, how to display information such as first name, email and title from ldap server to my web service? I searched for many references but did not find the steps. I hope you help me or give me a reference step that I can use.

**Comment by stevebauman** [comment]
Hi @riskinovitasari, there's many approaches to accomplish this, however the easiest would be to enable [binding to your User model](https://github.com/Adldap2/Adldap2-Laravel/blob/master/docs/auth/binding.md).

Once you've set that up, you can reference the currently logged in users LDAP record via:

```php
$user = Auth::user();

$user->ldap->getFirstName();
$user->ldap->getLastName();
$user->ldap->getEmail();
$user->ldap->getTitle();
```
