### ISSUE TITLE
These credentials do not match our records.

### ISSUE THREAD

**Issue by JakeHump** [Adldap2/Adldap2-Laravel#348]
- Laravel Version: 5.4
- Adldap2-Laravel Version: current release
- PHP Version: 5.6.28

### Description: 

I keep getting the error that my credentials do not match.  I have read through all of the issues that have already been filed, and have tried a bunch of your tips, and it has led me to an error in line 80 of Guard.php.  It says that it can not connect to the LDAP server.  I know the server is available. My goal is to authenticate using the username (samaccountname).   I will attach a few files that I know you will be interested in.

### Steps To Reproduce:
My adldap_auth.php

```php
return [
    'connection' => env('ADLDAP_CONNECTION', 'default'),
    'provider' => Adldap\Laravel\Auth\DatabaseUserProvider::class,
    'resolver' => Adldap\Laravel\Auth\Resolver::class,
    'importer' => Adldap\Laravel\Auth\Importer::class,
    'rules' => [
        Adldap\Laravel\Validation\Rules\DenyTrashed::class,
   ],
   'scopes' => [
        Adldap\Laravel\Scopes\UpnScope::class,

    ],

    'usernames' => [
        'ldap' => 'samaccountname',
        'eloquent' => 'username',
    ],
    'login_fallback' => env('ADLDAP_LOGIN_FALLBACK', false),

    'password_sync' => env('ADLDAP_PASSWORD_SYNC', true),

    'windows_auth_attribute' => ['samaccountname' => 'AUTH_USER'],
    'sync_attributes' => [


        'username' => 'samaccountname',
        'first_name' => 'GivenName',
        'last_name' => 'Surname'

    ],

];
````

My adldap.php file:

```php
return [

    'connections' => [

        'default' => [

            'auto_connect' => false,
            'connection' => Adldap\Connections\Ldap::class,
            'schema' => Adldap\Schemas\ActiveDirectory::class,
            'connection_settings' => [
            'account_prefix' => env('ADLDAP_ACCOUNT_PREFIX', ''),
            'account_suffix' => env('ADLDAP_ACCOUNT_SUFFIX', ''),
            'domain_controllers' => explode(' ', env('ADLDAP_CONTROLLERS', '')),
            'port' => env('ADLDAP_PORT', 389),
            'timeout' => env('ADLDAP_TIMEOUT', 5),
            'base_dn' => env('ADLDAP_BASEDN', ''),
            'admin_account_suffix' => env('ADLDAP_ADMIN_ACCOUNT_SUFFIX', ''),
            'admin_username' => env('ADLDAP_ADMIN_USERNAME', 'username'),
            'admin_password' => env('ADLDAP_ADMIN_PASSWORD', 'password'),
            'follow_referrals' => false,
            'use_ssl' => false,
            'use_tls' => false,

            ],

        ],

    ],

];
```

My auth.php:

```php
return [
    'defaults' => [
        'guard' => 'web',
        'passwords' => 'users',
    ],
    'guards' => [
        'web' => [
            'driver' => 'session',
            'provider' => 'users',
        ],

        'api' => [
            'driver' => 'token',
            'provider' => 'users',
        ],
    ],
    'providers' => [
        'users' => [
            'driver' => 'adldap', // Changed from 'eloquent'
            'model' => App\User::class,
          ],
      ],
    'passwords' => [
        'users' => [
            'provider' => 'users',
            'table' => 'password_resets',
            'expire' => 60,
        ],
    ],

];
```

**Comment by jasonhoule** [comment]
Is it correct to assume that the values here have been removed? Or do you have the values set in the .env file?

`'domain_controllers' => explode(' ', env('ADLDAP_CONTROLLERS', ''))`

**Comment by JakeHump** [comment]
I set the values in the .env file.   I assume I am supposed to use the FQDN for those domain controllers, correct?  I tried it both ways anyhow.

**Comment by AlbertoRobles** [comment]
I have the same issue, a similar configuration and the same message, but when i try to import users with php artisan adldap:import, it works.

Some suggestion?

**Comment by stevebauman** [comment]
Hi @JakeHump, this sounds like a generic connection issue.

You need to ensure your server is accessible using your FQDN that you've provided in the configuration, and that the ports you've configured are also correct.

**Comment by wtalaverano** [comment]
I have the same issue, a similar configuration and the same message, but when i try to import users with php artisan adldap:import, it works.

Some suggestion?

**Comment by wtalaverano** [comment]
Laravel log

`[2018-05-30 18:53:18] local.INFO: User 'Walter Renzo Talaverano Cruz' has been successfully found for authentication.  
[2018-05-30 18:53:18] local.INFO: User 'Walter Renzo Talaverano Cruz' is being imported.  
[2018-05-30 18:53:18] local.INFO: User 'Walter Renzo Talaverano Cruz' is being synchronized.  
[2018-05-30 18:53:18] local.INFO: User 'Walter Renzo Talaverano Cruz' has been successfully synchronized.  
[2018-05-30 18:53:18] local.INFO: User 'Walter Renzo Talaverano Cruz' is authenticating with username: 'WTalavC'  
[2018-05-30 18:53:18] local.INFO: User 'Walter Renzo Talaverano Cruz' has failed LDAP authentication.  
`

**Comment by stevebauman** [comment]
Hi @wtalaverano, please create a separate issue so we can take a look over your configuration separately, as my suggestions will be referring to the OP.

@JakeHump, do the users authenticating contain a *user principal name*?

I ask as you have the `UpnScope` still inside the your `scopes` array, which may be rejecting users if they do not have a *user principal name*.

Also, looking at your configuration, you will likely need a `account_suffix` to be able to pass Active Directory authentication, since you need to provide a users FQDN (fully qualified domain name) such as `johndoe@company.org`.

Insert your directory's domain name (`@company.org`) into the `account_suffix` option, and see if that resolves your issue.
