### ISSUE TITLE
Oracle

### ISSUE THREAD

**Issue by marijang** [Adldap2/Adldap2-Laravel#349]
- Laravel Version: 5.4
- Adldap2-Laravel Version: latest
- PHP Version: 7

### Description:

I m using laravel with oracle. I don't need password sync.
There is problem with with databaseUserProvider because the PASSWORD is reserved keyword.
So i find solution 

https://github.com/yajra/laravel-oci8/blob/5.4/src/Oci8/Auth/OracleUserProvider.php

How can i use with adldp driver?
i m using Auth::attempt($credentials)
and $credentials = ["password"=>"pp", "username"=>"test"]

Because i don't need to check db user
my workflow is next
1. Check username and pass with AD server
2. IF true then map user only by username

I don't wanna store pass localy

My config is working i can connect and i disabled sync options.

**Comment by stevebauman** [comment]
Hi @marijang,

This isn't yet a configurable option unfortunately, but it's coming. If you're using the Adldap auth driver, you'll need to add a mutator to your User model to prevent it from setting the password field on your User model:

```php
public function setPasswordAttribute($password)
{
    // Do nothing.
}
```

If you'd prefer to write your own implementation, it wouldn't be too difficult. Let me know if this is what you would prefer.
