### ISSUE TITLE
Create new user with sync attributes

### ISSUE THREAD

**Issue by mdbedjaoui** [Adldap2/Adldap2-Laravel#351]
- Laravel Version: 5.4
- Adldap2-Laravel Version: 3.0
- PHP Version: 5.6

### Description:

Is it possible to retrieve a user password (a hash of password or other secure format) and store it in the local database?

**Comment by stevebauman** [comment]
This depends on your LDAP infrastructure. If you have OpenLdap then yes, otherwise if you use ActiveDirectory, then no. You can simply see what attributes are available on your users by dumping the user object (`dd($user)`).

**Comment by stevebauman** [comment]
To elaborate in case of questions, dump the LDAP user object, not your model. For example:

```php
$user = Adldap::search()->users()->find('jdoe');

dd($user);
```

**Comment by mdbedjaoui** [comment]
Thank you for your response...In my case I use Active Directory. Actually, in my application the administrator has the ability to add users with a specific role [Admin, Manager…]. It is possible to retrieve all other LDAP user information, but I need also to find a way to get users password so that I can authenticate users...here is my users table.

![users table](https://user-images.githubusercontent.com/30214715/28251151-4504c240-6a6f-11e7-83d3-3624c00fd503.png)

**Comment by stevebauman** [comment]
You won't be able to retrieve the LDAP users password with active directory. It's not available to be accessed at all.

The only way to retrieve their password is to capture it and try to bind to your LDAP server to see if it's valid.

**Comment by mdbedjaoui** [comment]
When imoprting users unsing the command "php artisan adldap:import", I'm able to import their password also. 

![ciec](https://user-images.githubusercontent.com/30214715/28258851-4fe42ee2-6acb-11e7-8cea-dba2cbe5ecd3.PNG)

I thought that there is a way to synchronize  users AD passwords to my local database.

**Comment by mdbedjaoui** [comment]
When imoprting users unsing the command "php artisan adldap:import", I'm able to import their password also.

![ciec](https://user-images.githubusercontent.com/30214715/28258907-9dc224b6-6acb-11e7-8552-dc65db048ebe.PNG)

I thought that there is a way to synchronize users AD passwords to my local database.

**Comment by mdbedjaoui** [comment]
Last question, if the only way to authenticate users is to try and bind to LDAP server with the values provided and either succeed or fail...**How can I perform that using adldap2 library?**

currently I'm trying to sign in a user with the web guard like this :

`$auth = Auth::guard('web')->attempt(['username'=>$request->username,'password'=>$request->password,'active'=>1]);
        if($auth){
            return redirect()->route('home');
        }`

**Comment by mdbedjaoui** [comment]
Last question, if the only way to authenticate users is to try and bind to LDAP server with the values provided and either succeed or fail...How can I perform that using adldap2 library?

currently I'm trying to sign in a user with the web guard like this :

`$auth = Auth::guard('web')->attempt(['username'=>$request->username,'password'=>$request->password,'active'=>1]);

if($auth){
return redirect()->route('home');}`

**Comment by mdbedjaoui** [comment]
Last question, if the only way to authenticate users is to try and bind to LDAP server with the values provided and either succeed or fail...How can I perform that using adldap2 library?

currently I'm trying to sign in a user with the web guard like this :

`$auth = Auth::guard('web')->attempt(['username'=>$request->username,'password'=>$request->password,'active'=>1]);
        if($auth){
            return redirect()->route('home');
        }`

**Comment by stevebauman** [comment]
> When imoprting users unsing the command "php artisan adldap:import", I'm able to import their password also (hashed versions).

This doesn't import the users password, it sets it as a random 16 character string and then is updated upon login:

https://github.com/Adldap2/Adldap2-Laravel/blob/master/src/Commands/Import.php#L84-L90

**Comment by stevebauman** [comment]
> Last question, if the only way to authenticate users is to try and bind to LDAP server with the values provided and either succeed or fail...How can I perform that using adldap2 library?

No problem :)

You can perform this like so:

```php
use Adldap\Laravel\Facades\Adldap;

if (Adldap::auth()->attempt('username', 'password')) {
    // Bind succeeded to LDAP server. Username and password is valid.
}
```
