### ISSUE TITLE
Implementing adldap2 in Laravel 5.2 with system-specific access 

### ISSUE THREAD

**Issue by philbrowne** [Adldap2/Adldap2-Laravel#352]
- Laravel Version: 5.2
- Adldap2-Laravel Version: 2.1.3
- PHP Version: 5.5.21

### Description:
Hi Steve, Can you help as I am confused how to implement role-based authentication on top of ADLDAP2. Basically I can authenticate with LDAP ok, but I need the system to also check to see if the user is in the users table without adding any rows to it.  The user table has the names only of those who can use the system - not the passwords, so I can then control system access within the system itself and not AD groups. 

I read how this is possible in V3 and read an earlier post that you could also do this in V2 of adldap and Laravel 5.2, which is exactly what I need. You said that it is possible by disabling password sync and adding the Laravel exists rule to your Username/Password validation. I have tried this and changing the 
password_sync to false, but it still writes to the user table.

I'm also confused where to put that Laravel 'exists' rule exactly.  I can't see where/how I add that rule in Laravel 5.2. The only validation I can find in the default Laravel setup is in the Requests folder and relates to updating the user/password. However, this validation is not applied when logging in, only when updating the actual user details. Could you guide me on how this exists rule is applied to the log-in process? I apologise in advance if this is a bit out of scope for the package itself, but it is fundamental for us in being able to use ldap yet retain system-specific access control.

Many thanks

**Comment by stevebauman** [comment]
Hi @philbrowne,

> The user table has the names only of those who can use the system - not the passwords, so I can then control system access within the system itself and not AD groups.

If you don't need to store their password, then you'll have to create your own solution unfortunately. This is being changed in a future release, but right now the password field is mandatory. However, it shouldn't be too difficult to create. Here's a basic implementation:

```php
// app/Http/Controllers/Auth/LoginController.php

public function login(Request $request)
{
    $username = $request->username;

    if ($user = User::whereUsername($username)->first()) {
        // The user is logging in with a valid
        // email address as it's located
        // in our local table.
        if (Adldap::auth()->attempt($username, $request->password)) {
            // LDAP authentication succeeded, now to log them in locally.
            Auth::login($user);

            return redirect()->to('dashboard');
        }
    }

    return redirect()->to('login')->with('message', 'Login failed');
}
```

Does this answer your question for authenticating users locally into your application but not storing their password?

**Comment by philbrowne** [comment]
Thanks Steve, I can understand your code example -that's very helpful. I think I need to put this in RedirectIfAuthenticated so I will give this a try first. I'm thinking if I have a separate table for system users (which admins can configure) then I can system-authenticate first, and let adldap write to the users table as normal for ldap authentication. Thanks for your help.
