### ISSUE TITLE
Artisan import without interaction

### ISSUE THREAD

**Issue by byanke-pcn** [Adldap2/Adldap2-Laravel#354]
Is there a way to run the Artisan import commands (`php artisan adldap:import`) without user interaction? This is something that would be very advantageous to run in a scheduled/scripted fashion.

I was expecting to be able to run with something like `-f` or `-y`, but I don't seem to be able to find any mention of this.

**Comment by stevebauman** [comment]
Hi @byanke-pcn, I just pushed out a new release now that fixes this.

Run `composer update`, then use the `--no-interaction` flag with the `adldap:import` command and it will import your users without interaction, allowing you to run it on a schedule.

**Comment by mitjarobic** [comment]
How would you call this inside another command? This does not work..

$this->call("adldap:import", ['--no-interaction' => true]);

**Comment by toaomatis** [comment]
I'm running into exact the same issue. 
Calling the command from another command
```php
$this->call('adldap:import', ['--delete', '--restore', '--no-interaction']);
```
results in a PHP Error
`The "2" argument does not exist.`

It does not look like the 3rd argument is the real problem, swapping it with the first or second gives the same error. 
When I only pass two arguments (no matter what 2) it works as expected.
