### ISSUE TITLE
Prefix Issues

### ISSUE THREAD

**Issue by claborn** [Adldap2/Adldap2-Laravel#356]
- Laravel Version: 5.4
- Adldap2-Laravel Version: 3.0.4
- PHP Version: 7.1

### Description:
Hi Steve, I am having a bit of difficulty with Auth and I was hoping you could help. I have everything working using the artisan command. I also have everything working if I manually run the ->auth()->attempt. I am not having much luck trying to prefix the domain to the user trying to login with their samaccountname.

for instance DOMAIN\cha.lab

If I try to set the prefix for the account everything breaks, including the import command. I've got a workaround by hardcoding it into the package's Resolver locally, but for obvious reasons this isn't ideal.

I appreciate your time.

**Comment by stevebauman** [comment]
Hi @claborn, can you post the code that you've modified for you to get it working in your application?

Are you looking to save the users domain name in their synchronized model or simply authenticate the user with the prefixed username?

**Comment by claborn** [comment]
I just hardcoded the domain in as below. Whenever I tried to add it to the prefix it would break the admin auth against the LDAP. This happened no matter which prefix I placed it in. I also couldn't get it to honor me adding it manually in the login field.

In Adldap\Laravel\Auth\Resolver 

```
    /**
     * {@inheritdoc}
     */
    public function authenticate(User $user, array $credentials = [])
    {
        $username = $user->getFirstAttribute($this->getLdapUsername());

        //I added this bit. 
        $username = "DOMAIN\\" . $username;

        return $this->provider->auth()->attempt($username, $credentials['password']);
    }
```

**Comment by stevebauman** [comment]
Hi @claborn,

Probably too late for this, but please try the latest release with the `account_prefix` option and try again.

From what I've experienced, I'm only able to pass LDAP authentication via `userPrincipalName` (jdoe@acme.org) or via `distinguishedName` (cn=John Doe,dc=acme,dc=org).
