### ISSUE TITLE
Authenticating with 'username' and incorrect password

### ISSUE THREAD

**Issue by mslindow** [Adldap2/Adldap2-Laravel#357]
- Laravel Version: 5.4
- Adldap2-Laravel Version: I'm not sure
- PHP Version: 7.1.6

### Description:
I login with username (not email) and the correct password and all is good.
If I enter the incorrect password, I get:
file_put_contents(/var/www/laravel/transcript/storage/framework/cache/data/2b/1e/2b1e2b1a50ad5f7bef765a2f642bc9edf5add310): failed to open stream: No such file or directory

It seems that maybe when it is trying to track the number of incorrect logins, it has failed to create the directory before it tries to write a file there. If I manually create the subdirectories .../2b/1e   it resolves the problem, but only for this session and for this user. Why is Laravel trying to write to a folder before it has created it?

### Steps To Reproduce:
I authenticate with my ldap (active directory) username and an incorrect password.

**Comment by stevebauman** [comment]
Hi @mslindow, this is seems to be an application issue that is out of Adldap2's scope.

I would troubleshoot the permissions on the storage folder and see if your application has access to be able to create directories there.

I would also try using a different session driver and see if that resolves your issue.

If you do encounter issues with the Adldap auth driver itself, please create another issue, thanks!
