### ISSUE TITLE
Optional sync_attributes?

### ISSUE THREAD

**Issue by byanke-pcn** [Adldap2/Adldap2-Laravel#359]
- Laravel Version: 5.4.28
- Adldap2-Laravel Version: Current
- PHP Version: 7.x

### Description:
As a simple way of describing administrators in my application, we are using an unused field (otherpager) in our AD and setting it to `1`. On all other users in the directory, it's empty.

This, however, causes issues when I specify it in my `adldap_auth.php` under sync_attributes, causing it to only import users with this value set (administrators), ignoring everyone else.

Is there an way to have optional sync_attributes which could, perhaps, default to a specified value if they are not provided by LDAP?

**Comment by stevebauman** [comment]
Hi @byanke-pcn,

> This, however, causes issues when I specify it in my adldap_auth.php under sync_attributes, causing it to only import users with this value set (administrators), ignoring everyone else.

When you enter a sync attribute that might not exist on the users LDAP model, it should still import the account without issue.

Each attribute is retrieved using the `getFirstAttribute` method on the model:

https://github.com/Adldap2/Adldap2-Laravel/blob/master/src/Auth/Importer.php#L103-L115

https://github.com/Adldap2/Adldap2/blob/master/src/Models/Model.php#L289-L319

For this field your syncing on your local SQL table, is it nullable? Otherwise it will generate an exception trying to save the model.

**Comment by stevebauman** [comment]
Worst case, you can create an `AttributeHandler` to handle this situation:

https://github.com/Adldap2/Adldap2-Laravel/blob/master/docs/auth/syncing.md#attribute-handlers

Example:

```php
namespace App\Handlers;

use App\User as EloquentUser;
use Adldap\Models\User as LdapUser;

class LdapAttributeHandler
{
    /**
     * Synchronizes ldap attributes to the specified model.
     *
     * @param LdapUser     $ldapUser
     * @param EloquentUser $eloquentUser
     *
     * @return void
     */
    public function handle(LdapUser $ldapUser, EloquentUser $eloquentUser)
    {
        $eloquentUser->name = $ldapUser->getCommonName();
        
        if ($pager = $ldapUser->getFirstAttribute('otherpager')) {
            $eloquentUser->otherpager = $pager;
        }
    }
}
```

**Comment by byanke-pcn** [comment]
Fantastic, thank you.

After some additional digging and thanks to your suggestion, I went a similar route: implementing in the user model Mutator.


 ```php
// /app/user.php

class User extends Authenticatablec
{
// [...]
   public function setIsadminAttribute($value)
    {

        // This is required to properly handle null/empty values from AD
        if(is_null($value) || $value != 1) {
          $value = 0;
        }

        $this->attributes['isadmin'] = $value;
    }
// [...]
}
```

**Comment by stevebauman** [comment]
Great! No problem at all :).
