### ISSUE TITLE
v3.0.5 breaking config change

### ISSUE THREAD

**Issue by brightbeagle** [Adldap2/Adldap2-Laravel#360]
The following seems to be a breaking change in a patch update for users with a published adldap_auth config:

https://github.com/Adldap2/Adldap2-Laravel/blob/master/src/Config/auth.php#L151

**Comment by stevebauman** [comment]
@brightbeagle Whoops! This is my fault, I was strictly trying to push the new Import command with a cherry-picked commit. I'll take this release down immediately and re-release with the correct source.

Sorry about this!

**Comment by stevebauman** [comment]
Resolved yesterday: https://github.com/Adldap2/Adldap2-Laravel/releases/tag/v3.0.5

Thanks!
