### ISSUE TITLE
Improper use of their.

### ISSUE THREAD

**Issue by nwmille** [Adldap2/Adldap2-Laravel#362]
- Laravel Version: #.#
- Adldap2-Laravel Version: 3.0.5
- PHP Version: #.#

### Description:
Application failed, server overheated, database became corrupted, and Trump was elected president because of improper use of their. 

// We'll allow binding with a null username and password
// if their empty."

*they are or they're

### Steps To Reproduce:
adldap2\src\Auth\Guard.php

line 63, the comment inside the bind method

**Comment by stevebauman** [comment]
Lol appreciate your attention to detail, fixed: https://github.com/Adldap2/Adldap2/commit/4425a9217ba554afdcaf6dc913cdc349bfd5da8d.

**Comment by nwmille** [comment]
Haha thanks man. Thanks for all the work you do!
