### ISSUE TITLE
How to Delete and Modify users

### ISSUE THREAD

**Issue by absolutearpit** [Adldap2/Adldap2-Laravel#363]
- Laravel Version: 5.4
- Adldap2-Laravel Version: 3.0
- PHP Version: 5.6

### Description: 

Hi,

First of all thank you for developing this library for Laravel. I have been trying to update an entry but not getting a proper statement. I have added new entry by below statement 

            // Creating a user.
            $user = Adldap::make()->user([
                'displayName'   => $firstName,
                'uid'           => $exploreName,
                'cn'            => $exploreName,
                'sn'            => $lastName, // second name
                'mail'          => $email,
                'userpassword'  => $password,
             ]);
            $user->setAttribute('objectclass', 'inetOrgPerson');
            $user->setDn("cn=$exploreName,cn=email,dc=localhost");

            $result = $user->save();

Now my requirement is to update the same entry and then delete. Would be great help if you can tell me how I can update an entry and delete it too.

Thanks in Advance

**Comment by stevebauman** [comment]
Hi @absolutearpit, once you've created an entry, you can locate it by using multiple find methods:

Using your example:

```php
$uid = 'jdoe';

// Using ambiguous naming resolution
$user = Adldap::search()->find($uid);

// Using `findBy` to locate a record by a specific attribute 
$user = Adldap::search()->findBy('uid', $uid);

// Using the users distinguished name
$user = Adldap::search()->findByDn('cn=jdoe,cn=email,dc=localhost');

// Using the users SID or GUID
$user = Adldap::search()->findBySid('S-1-5-21-1004336348-1177238915-682003330-512');

$user = Adldap::search()->findByGuid('119d0d80-699d-4e81-8e4e-5477e22ac1b3');
```

You can browse the documentation for all find methods:

https://github.com/Adldap2/Adldap2/blob/master/docs/query-builder.md#selects

**Comment by absolutearpit** [comment]
That really helped. Thanks @stevebauman
