### ISSUE TITLE
Implementing Rules

### ISSUE THREAD

**Issue by aleex1848** [Adldap2/Adldap2-Laravel#364]
- Laravel Version: 5.4.30
- Adldap2-Laravel Version: 3.0.5
- PHP Version: 7.0.19-1

### Description:
Please help implementing rules to restrict Login.
adldap based login with default settings is okay.
Then i tried to implement a rule like described here: https://github.com/Adldap2/Adldap2-Laravel/blob/master/docs/auth/rules.md

It's a little confusing, because you are adding "App\Rules\DoeRule::class," to adldap_auth, but the Rule is named "class OuRule" so i think there is a typo, right? (DoeRule vs. OuRule)

I created a dir app/Rules, inside a file "AdGroupRule.php", which contains:
```
<?php
namespace App\Rules;

use Adldap\Models\User as LdapUser;
use Adldap\Laravel\Validation\Rules\Rule;

class AdGroupRule extends Rule
{
    /**
     * The LDAP user.
     *
     * @var User
     */
    protected $user;

    /**
     * The Eloquent model.
     *
     * @var Model|null
     */
    protected $model;

    /**
     * Determines if the user is allowed to authenticate.
     *
     * Only allows users in the `Accounting` group to authenticate.
     *
     * @return bool
     */
    public function isValid()
    {
        return $this->user->inGroup('grp_TMT_admin');
    }
}
```

I implemented the rule by adding the following to config/adldap_auth:
```
  'rules' => [

        Adldap\Laravel\Validation\Rules\DenyTrashed::class,
        App\Rules\AdGroupRule::class, //aleex


    ],
```
If i try to login i get this Error:
```
(1/1) FatalThrowableError
Class 'App\Rules\AdGroupRule' not found
```

**Comment by stevebauman** [comment]
Hi @aleex1848,

> It's a little confusing, because you are adding "App\Rules\DoeRule::class," to adldap_auth, but the Rule is named "class OuRule" so i think there is a typo, right? (DoeRule vs. OuRule)

Thanks for noticing this, I've fixed this in the documentation :).

This seems to be an issue in your application. Can you try running `composer dump-autoload` and try again? It seems your class isn't being found by composer and auto-loading it.

**Comment by aleex1848** [comment]
> composer dump-autoload
did the trick. Thank you!

**Comment by stevebauman** [comment]
Great, no problem!
