### ISSUE TITLE
Auth::attempt does not work but Adldap::auth()->attempt works very well

### ISSUE THREAD

**Issue by gcrispyn** [Adldap2/Adldap2-Laravel#365]
- Laravel Version: 5.4
- Adldap2-Laravel Version: 3.0.5
- PHP Version: 7.0

### Description:

Hello everybody,

I can't log my user using Auth::attempt. The result of the method is false. But when I use Adldap::auth()->attempt with the same attributes, It works but my auth user is empty.

The provider of my "web" auth is : 

'ad_users' => [
            'driver' => 'adldap',
            'model' => App\User::class,
        ],

Can you help me?

**Comment by syphernl** [comment]
This problem appears to have been caused in v3.0.5. 
Downgrading to 3.0.4 solved the problem for me. 

It's a bit odd, since the [difference](https://github.com/Adldap2/Adldap2-Laravel/compare/v3.0.4...v3.0.5) between these tags is only relating to the import functionality.

**Comment by stevebauman** [comment]
Hi @gcrispyn,

Those two methods are entirely different forms of authentication.

`Auth::attempt()` calls Laravel's native authentication manager and utilizes the driver you've specified (assuming you've configured the `adldap` driver. There is a ton going on behind the scenes when this method is called.

`Adldap::auth()->attempt()` simply tries to bind to your configured LDAP server and returns the result.

Can you post your `adldap.php` and `adldap_auth.php` files with sensitive details omitted?

**Comment by stevebauman** [comment]
@syphernl, This was my mistake, `v3.0.5` contained incompatible changes that was removed. I recreated the `v3.0.5` tag with the import command changes.

You will have to `composer update` again for it to take effect if you pulled in the original `v3.0.5` before the tag was re-created.

**Comment by pxlcore** [comment]
Hi,
I use the new version 3.0.5 but I still have the same problem as described above.
Version 3.0.4 also do not solve the problem for me.

**Comment by stevebauman** [comment]
Strange... We'll if you encounter any other issues please create one and I can assist you further, thanks!
