### ISSUE TITLE
How to swap ADLDAP connection ?

### ISSUE THREAD

**Issue by psraghul** [Adldap2/Adldap2-Laravel#366]
- Laravel Version: 5.3.31
- Adldap2-Laravel Version: 3.0
- PHP Version: 7.0.10

### Description:
I have 2 domain controllers, and the application should check for users from both domains, when user tries to login. I have configured both the domains in adldap.php file, one as 'default' and other as 'alternateConnection'. Now the problem is, when I use 'default' connection it is allowing users under it and when I change the 'ADLDAP_CONNECTION' to 'alternateConnection', it is allowing users under it. Not able to swap the connection and check users. I have following code in login controller,

protected function attemptLogin(Request $request)
{
	$authenticated = false;
	$credentials = $this->credentials($request);
	if($this->guard()->attempt($credentials,  $request->has('remember'))) { 
		$authenticated = true;
	} else {
		// Login failed, swap and try other connection.
		\Config::set('adldap_auth.connection','alternateConnection'); 
		if($this->guard()->attempt($credentials,  $request->has('remember'))) {  
			print_r($this->guard()); die;
				$authenticated = true;
			}
	}
	if ($authenticated === true ) {
		return redirect()->to('logout');
	}
	//return redirect()->to('login')->withMessage('Credentials are incorrect.');
}

**Comment by psraghul** [comment]
I have checked again, by having only once connection using,

Config::set('adldap_auth.connection', 'alternateConnection'); without any condition, seems that, the configuration is not getting overriden, so the auth attempt is not working. How do I fix this?

**Comment by stevebauman** [comment]
Hi @psraghul, you can't swap connections right now as it's not supported with the Adldap2 auth driver. You'll need to utilize the underlying `adldap` instance and perform authentication / synchronization your own way.
