### ISSUE TITLE
$_SERVER['AUTH_USER'] not populating

### ISSUE THREAD

**Issue by ZaeemFarooqui** [Adldap2/Adldap2-Laravel#367]
- Laravel Version: 5.4
- Adldap2-Laravel Version: 3.0
- PHP Version: 5.6

Description:
My application is connecting to active directory as my accounts in active directory(even the ones not already in local DB) are being authenticated, but my $_SERVER['AUTH_USER'] is not being populated(neither is $_SERVER['REMOTE_USER']). I edited the config/adldap.php default config
as per requirement.
'default' => [
            'auto_connect' => true,
            'connection' => Adldap\Connections\Ldap::class,
            'schema' => Adldap\Schemas\ActiveDirectory::class,
            'connection_settings' => [
                'account_prefix' => env('ADLDAP_ACCOUNT_PREFIX', ''),
                'account_suffix' => env('ADLDAP_ACCOUNT_SUFFIX', ''),
                'domain_controllers' => ['mydomain'],
                'port' => env('ADLDAP_PORT', 389),
                'timeout' => env('ADLDAP_TIMEOUT', 5),
                'base_dn' => env('ADLDAP_BASEDN', 'dc=abc, dc=com'),
                'admin_account_suffix' => env('ADLDAP_ADMIN_ACCOUNT_SUFFIX', ''),
                'admin_username' => env('ADLDAP_ADMIN_USERNAME', 'myadmin'),
                'admin_password' => env('ADLDAP_ADMIN_PASSWORD', 'thepassword'),
                'follow_referrals' => false,
                'use_ssl' => false,
                'use_tls' => false,
]

Is there something that I am missing?
Please help.
Thanks

**Comment by stevebauman** [comment]
Hi @ZaeemFarooqui, the `AUTH_USER` parameter is populated by the PHP server itself. It is not populated by Adldap2.

Please take a look at the middleware requirements note here:

https://github.com/Adldap2/Adldap2-Laravel/blob/master/docs/auth/middleware.md

I can not assist you setting this up, as it's entirely environment driven and experience is required.

**Comment by ZaeemFarooqui** [comment]
Okay, I will look around more.
Thanks for your time @stevebauman.
This library is awesome.
