### ISSUE TITLE
 Login with email or username

### ISSUE THREAD

**Issue by atiladelcanton** [Adldap2/Adldap2-Laravel#368]
- Laravel Version: 5.4
- Adldap2-Laravel Version: 2.1
- PHP Version: 7

### Description:

Currently we are using the normal login, and the login by email AD.
But now we need you to also be able to login through the username AD.
Looking at the adldap_auth file, I saw that you can only specify one or the other.
Is there any way to make the two media available?

tks!

**Comment by stevebauman** [comment]
Hi @atiladelcanton, you'll have to switch the configuration on demand depending on what the user inserts, and then pass in the credentials with this field your user is located correctly by eloquent:

```php
if (filter_var($request->email, FILTER_VALIDATE_EMAIL)) {
    // We're working with an email.
    Config::set('adldap_auth.usernames.eloquent', 'email');

    $credentials = [
        'email' => $request->email,
        'password' => $request->password
    ];
} else {
    // We're working with a username.
    Config::set('adldap_auth.usernames.eloquent', 'username');

    $credentials = [
        'username' => $request->email,
        'password' => $request->password
    ];
}

if (Auth::attempt($credentials, $request->has('remember'))) {
    // Authenticated.
}
```
