### ISSUE TITLE
Use Rule Class in specific function

### ISSUE THREAD

**Issue by ibenettaleb** [Adldap2/Adldap2-Laravel#369]
- Laravel Version: 5.4
- Adldap2-Laravel Version: 3.0
- PHP Version: >=5.6.4

### Description:

**I create this rule :**

```
<?php

    namespace App\Rules;

    use Adldap\Models\User as LdapUser;
    use Adldap\Laravel\Validation\Rules\Rule;

    class AccountingRule extends Rule
    {
        /**
         * The LDAP user.
         *
         * @var User
         */
        protected $user;
        
        /**
         * The Eloquent model.
         *
         * @var Model|null
         */
        protected $model;
        
        /**
         * Determines if the user is allowed to authenticate.
         *
         * Only allows users in the `Accounting` group to authenticate.
         *
         * @return bool
         */   
        public function isValid()
        {
            return $this->user->inGroup('Admin-Portal');
        }
    }


```
i want use this rule just in this function not in all pages :

<img width="465" alt="2017-08-04_10-34-41" src="https://user-images.githubusercontent.com/28574987/28963360-c6536f28-7900-11e7-8565-47296adb7007.png">

_with all due respect_

**Comment by ibenettaleb** [comment]
i can use this in **blade view** 

<img width="523" alt="2017-08-04_16-11-39" src="https://user-images.githubusercontent.com/28574987/28975105-b9484f94-7930-11e7-8e4a-dcb24ae07060.png">

Plz I need Help ?

**Comment by stevebauman** [comment]
Hi @ibenettaleb, you'll need to enable [user model binding](https://github.com/Adldap2/Adldap2-Laravel/blob/master/docs/auth/binding.md).

This will allow you to always have the users LDAP model to check this access:

```blade
@if($this->user->ldap->inGroup('Admin-Portal'))
    I can access the admin portal!
@endif
```

**Comment by ibenettaleb** [comment]
Hi @stevebauman ,
That's what I did : 

User Model
<img width="314" alt="2017-08-07_09-40-55" src="https://user-images.githubusercontent.com/28574987/29018863-982f59da-7b54-11e7-90cb-2c679e56c848.png">

View
<img width="392" alt="2017-08-07_09-43-12" src="https://user-images.githubusercontent.com/28574987/29018911-c80e6cfe-7b54-11e7-91df-f1951bd8567e.png">

Message Error
<img width="767" alt="2017-08-07_09-44-57" src="https://user-images.githubusercontent.com/28574987/29018994-10d314b2-7b55-11e7-83a7-3d1608754203.png">

<img width="768" alt="2017-08-07_09-45-21" src="https://user-images.githubusercontent.com/28574987/29018993-10d159a6-7b55-11e7-9254-f13090514c05.png">
