### ISSUE TITLE
Exporting Users table from a working ADLDAP 2 app To another App without ADLDAP .

### ISSUE THREAD

**Issue by fatalh** [Adldap2/Adldap2-Laravel#371]
- Laravel Version: 5.2.45
- Adldap2-Laravel Version: 3.0.4
- PHP Version: 5.5.9

### Description:
I have two apps. The first app working with ADLDAP 2 and built with Laravel 5.4 and PHP 5.6. The second app is the same app but built with Laravel 5.2 and PHP 5.5.9 without ADLDAP 2.
I want To export Users table of the first app (these users have been imported and Synchronised from the AD Domain) in order To use it in the second App.
So no ADLDAP connection in the second app, but just use the Users table of the first app.
The problem is when I do it, the Users who were not logged  at least one time in the first app can't be connected To the second App. How can I fix it ?

**Comment by stevebauman** [comment]
Hi @fatalh, unfortunately there isn't a way around this. You can't retrieve passwords from ActiveDirectory, so there is no way to sync them without having the user authenticate into your first application.

This would cause headaches over time anyway, as passwords would most likely fall out of sync.

If the user logged into your first application once and then only used your second application, but changed their password on a domain joined computer, they wouldn't be able to use their new password unless they logged into the first application again.

I would offer up an API on your first application using [Laravel Passport](https://laravel.com/docs/5.4/passport), and then authenticate against it with your second application. This way your authenticating through your first application and passwords stay in sync.

However, I cannot assist with setting this up, as it's a large task that has many variables, and you will need to understand how passport works for you to continue with this approach (though it would be the best approach in my personal opinion).

**Comment by fatalh** [comment]
Thank you very much @stevebauman , I Will understand Laravel Passport.
