### ISSUE TITLE
Class 'Adldap\Laravel\Resolvers\UserResolver' not found

### ISSUE THREAD

**Issue by poxin13** [Adldap2/Adldap2-Laravel#373]
- Laravel Version: 5.5-dev
- Adldap2-Laravel Version: v3.0.5
- PHP Version: 7.1

### Description:
New install, maybe related to 5.5 dev? Same setup/install seems to work fine on 5.4.

`Class 'Adldap\Laravel\Resolvers\UserResolver' not found`

`/vendor/adldap2/adldap2-laravel/src/Traits/UsesAdldap.php`

```
public function getResolver()
    {
        $resolver = config('adldap_auth.resolver', Resolver::class);
 
        return $this->resolver ?: $this->resolver = new $resolver($this->getLdapProvider());
    }
```

**Comment by poxin13** [comment]
I did something stupid :)

**Comment by stevebauman** [comment]
No problem! I'm assuming you might have downloaded `dev-master` from composer, as that would lead to this error.
