### ISSUE TITLE
No users found when importing from AD

### ISSUE THREAD

**Issue by hightekjonathan** [Adldap2/Adldap2-Laravel#379]
- Laravel Version: 5.4
- Adldap2-Laravel Version: 3.0
- PHP Version: 7.1.5
- LDAP Type: Active Directory

### Description:
I just setup the adldap2 and adldap2-laravel packages on my app, and configured the configuration files to connect to my domain controllers, but when running `php artisan adldap:import` Its returning `Found 0 user(s).` Which can't be right because in our Users and Groups on the DC it shows ~45 Users. I even tried importing using a custom filter and specifying my user account on the controller

### Steps To Reproduce:
Imported using the command multiple times.
Tried removing one DC
Re-installed the packages from scratch

Below are my config files:

adldap.php
```php
return [
    'connections' => [
        'default' => [
            'auto_connect' => false,
            'connection' => Adldap\Connections\Ldap::class,
            'schema' => Adldap\Schemas\ActiveDirectory::class,
            'connection_settings' => [
                'domain_controllers' => [
                    'bihrle-dc1.ad.bihrle.com'
                ],
                'base_dn' => 'dc=ad,dc=bihrle,dc=com',
                'admin_username' => 'My Username',
                'admin_password' => 'My Password',
            ],
        ],
    ],
];
```

adldap_auth.php
```php
<?php

return [

    'connection' => env('ADLDAP_CONNECTION', 'default'),

    'provider' => Adldap\Laravel\Auth\DatabaseUserProvider::class,

    'resolver' => Adldap\Laravel\Auth\Resolver::class,

    'importer' => Adldap\Laravel\Auth\Importer::class,

    'rules' => [

        // Denys deleted users from authenticating.

        Adldap\Laravel\Validation\Rules\DenyTrashed::class,

        // Allows only manually imported users to authenticate.

        // Adldap\Laravel\Validation\Rules\OnlyImported::class,

    ],

    'scopes' => [

        // Only allows users with a user principal name to authenticate.

        Adldap\Laravel\Scopes\UpnScope::class,

    ],

    'usernames' => [

        'ldap' => 'userprincipalname',

        'eloquent' => 'email',

    ],

    'login_fallback' => env('ADLDAP_LOGIN_FALLBACK', false),

    'password_sync' => env('ADLDAP_PASSWORD_SYNC', true),

    'windows_auth_attribute' => ['samaccountname' => 'AUTH_USER'],

    'sync_attributes' => [

        'email' => 'samaccountname',
        'name' => 'name',

    ],
];
```

**Comment by hightekjonathan** [comment]
I was able to resolve the main issue, and it is now finding the users. And it is synchronizing the AD account to the database ONLY if the user is already made. Isn't the importer supposed to create a new user and store it in the database upon successful login? Or did I misunderstand what the importer does?

**Comment by stevebauman** [comment]
You can check your logs to see why user's weren't imported.

If the user isn't there then they weren't located during the import.

Can you validate this before we troubleshoot further?

**Comment by hightekjonathan** [comment]
I can check the log tomorrow when I get back to work. Thank you for the speedy reply!

**Comment by stevebauman** [comment]
Ok sounds good! No problem :).

**Comment by hightekjonathan** [comment]
So I was able to take a look in the logs, and forgot that my User table was modified, so I store both emails, and usernames. I updated the `adldap_auth.php` to compensate for that, but now I have an issue due to I store a longtext in the same table that needs to have a default value. Where is the file that creates the User model before storing it? I think I need to modify that o that I can create the default info to be inseted upon Import/Sync

**Comment by stevebauman** [comment]
@hightekjonathan You have multiple options for this:

- Set a default value in your MySQL table itself
- Use an [Attribute Handler](https://github.com/Adldap2/Adldap2-Laravel/blob/master/docs/auth/syncing.md#attribute-handlers) and set this attribute to something before its saved
- Use Laravel's model events to set this default value when the models 'creating' event is fired
- Listen for the `Adldap\Laravel\Events\AuthenticatedWithCredentials` [event](https://github.com/Adldap2/Adldap2-Laravel/blob/v3.0.5/src/Traits/DispatchesAuthEvents.php#L13-L24) and set the users attribute in your listener

If you need any further assistance just let me know :).
