### ISSUE TITLE
New User created on every login

### ISSUE THREAD

**Issue by davis-thereal** [Adldap2/Adldap2-Laravel#380]
- Laravel Version: v5.5.3
- Adldap2-Laravel Version:  v3.0.5
- PHP Version: 7.0.19-1

### Description:

The ADLDAP2 plugin creates everytime i login a new user and wont use exisiting users with the same email, name and password.

### Steps To Reproduce:

I dont know.

**Comment by stevebauman** [comment]
Are you using PostGre SQL? Or MySql?

**Comment by lastbyte32** [comment]
same problem
i'm using mysql
latest laravel and Adldap2

**Comment by stevebauman** [comment]
I need more information, there's only a generic where clause that uses Laravel's eloquent query builder that locates each user by your specified username:

https://github.com/Adldap2/Adldap2-Laravel/blob/v3.0/src/Auth/Importer.php#L36-L58

Try using laravel's default auth driver and registering a user using an already taken username / email.

If you're experiencing this using the Adldap2 auth driver, then you should also experience this using the default laravel driver when registering new users.

Closing until more information is given with steps to reproduce.
