### ISSUE TITLE
Sync user details when logging in... 

### ISSUE THREAD

**Issue by matteboy99** [Adldap2/Adldap2-Laravel#383]
- Laravel Version: 5.4
- Adldap2-Laravel Version: 3
- PHP Version: 7.1

### Description:
@stevebauman - Is the database sync enabled out of the box? - the docs say as long as you define the sync attributes this should happen when a user is logged in after authenticating.

Cheers

**Comment by stevebauman** [comment]
Hi @matteboy99,

Yes it's enabled by default because the default provider is the `DatabaseUserProvider`:

https://github.com/Adldap2/Adldap2-Laravel/blob/a360038964d3583ae6ea54d56179f882c12ee787/src/Config/auth.php#L20-L38

The sync attributes are utilized by this provider, but not the `NoDatabaseUserProvider`.

**Comment by matteboy99** [comment]
@stevebauman any limitations?

Asking as I've followed the full setup instructions for user Auth - I can auth against a users display name but nothing else. Do I need to alter the my laravel loginController or should the sync just work?

**Comment by stevebauman** [comment]
> I can auth against a users display name but nothing else. Do I need to alter the laravel loginController or should the sync just work?

You can only authenticate users by one attribute (username / email etc.). If you need multiple attributes to authenticate users by, you'll need to modify your `LoginController` and change the username attribute on the fly depending on what the user has entered using `Config::set()`.

**Comment by stevebauman** [comment]
Also to answer your other question, sync should just work. Users attributes are re-synced upon authentication. However, if their login attribute (email / username etc.) is changed, then it will create a new user because it won't be able to locate the existing users record in your local database.

**Comment by matteboy99** [comment]
Hi @stevebauman,
Apologies I've been on annual leave.
I managed to sort the issue by playing around with the config settings to establish a proper connection at the root of where I wanted to search the active directory.
I can sync pretty much anything now which is awesome and auth works perfectly!

Great job!

**Comment by stevebauman** [comment]
Awesome, thanks @matteboy99, appreciate the kind words! :)
