### ISSUE TITLE
Auth::user() always return null although login is successful.

### ISSUE THREAD

**Issue by entrique** [Adldap2/Adldap2-Laravel#384]
- Laravel Version: 5.5
- Adldap2-Laravel Version:  3.0
- PHP Version: 7.1

### Description:
Auth::user returning null although login redirection is successful from Auth::attempt()

$user = Adldap::search()->all(); works by returning all the objects in my AD.

Using:
'provider' => Adldap\Laravel\Auth\NoDatabaseUserProvider::class,

### Steps To Reproduce:
![image](https://user-images.githubusercontent.com/4718721/30411183-0805d1ca-9942-11e7-95e3-4bf1b530ceed.png)
![image](https://user-images.githubusercontent.com/4718721/30411188-1085dade-9942-11e7-8d13-ed01dbe05100.png)

**Comment by stevebauman** [comment]
Hi @entrique,

This is incorrect usage. You're supposed to setup the auth driver and use laravel's default `Auth::attempt()` method:

https://github.com/Adldap2/Adldap2-Laravel/blob/master/docs/auth/installation.md

**Comment by entrique** [comment]
Hi Steven,

I am not using a User model for login. Any example?
