### ISSUE TITLE
Post-tasks for users first login & sync

### ISSUE THREAD

**Issue by Albvadi** [Adldap2/Adldap2-Laravel#386]
- Laravel Version: 5.5
- Adldap2-Laravel Version: 3.0.5
- PHP Version: 7.0.9

### Description:
Hi, it´s possible exec post-tasks after the first login & sync of a ldap user?
I need work with role and permissions and for the first user login from ldap, I need to assign a default role. 

Thanks!

**Comment by stevebauman** [comment]
Hi @Albvadi!

There's lots of different ways to do this, however if you only want this to happen for LDAP users, then you can utilize the `AuthenticatedWithCredentials` event that is fired during authentication:

https://github.com/Adldap2/Adldap2-Laravel/blob/v3.0/src/Events/AuthenticatedWithCredentials.php

However, this event is fired before validation is done (if you have any validation rules) and before the model is actually saved, so you will need to manually save the model (if it doesn't exist) before attaching any roles / permissions to it.

Another option is having an `ldap` column in the users table that is set to true (so you know who is an LDAP user in your database) and then listening for the `created` eloquent event for your `User` model so you can then attach roles to your LDAP users models.

If you need any further assistance setting this up, just give me a shout!
