### ISSUE TITLE
No way to search multiple OU's?

### ISSUE THREAD

**Issue by joveice** [Adldap2/Adldap2-Laravel#389]
Is there no way to search multiple OU's?

If there is how do you do that?

EDIT:

Also, why doesn't 
"CN=Group name, OU=Users, OU=Org, dc=ad, dc=domain, dc=comainending"
work in basedn?

**Comment by stevebauman** [comment]
Hi @joveice,

This isn't possible with LDAP (without some complex configuration):

https://stackoverflow.com/questions/9184978/ldap-root-query-syntax-to-search-more-than-one-specific-ou

You can only set the base DN (which is the scope of the search you're looking for).

Also to answer your question, you're setting your base DN to a group, not an OU.

A group isn't like an OU. You can't set the base DN to a group DN and retrieve all the members inside the group. You must query for the group, and then ask each group for their members:

```php
$group = Adldap::search()->groups()->find('Group name');

$members = $group->getMembers();
```

https://github.com/Adldap2/Adldap2/blob/master/src/Models/Group.php#L15-L31
