### ISSUE TITLE
Using with LDAP

### ISSUE THREAD

**Issue by fzoske** [Adldap2/Adldap2-Laravel#39]
Hi,

I have problems using this against a pure LDAP (no ActiveDirectory) Server.
I figured out, that you're querying for 'objectCategory' which is not present in my schema.
Is it possible to work around this, or do I have to look for another AuthProvider?

**Comment by stevebauman** [comment]
Hi, at the moment in `v5`, the `objectCategory` attribute is a hard-coded `constant` into the creation of models:

https://github.com/Adldap2/Adldap2/blob/v5.2/src/Query/Builder.php#L976

However, this has changed in `v6`, which will be coming out soon. It utilizes a customizable schema object:

https://github.com/Adldap2/Adldap2/blob/master/src/Query/Processor.php#L133. 

Adldap2-Laravel will also be updated at the time of its release, so please stay tuned!

**Comment by fzoske** [comment]
It's been some time now.
Can you estimate the date of release for v6?

**Comment by stevebauman** [comment]
Actually, I'm planning on releasing it tonight. I'm finalizing the documentation as we speak.

https://github.com/Adldap2/Adldap2/tree/master/docs

**Comment by fzoske** [comment]
That are great news. Thank you!
