### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by joveice** [Adldap2/Adldap2-Laravel#390]
Hello.

So I'm now pulling all users including users in groups and the groups.
Is there a way to not display the groups?
And is there a way to get the username? right now I just did $ad->cd then take everything from CN= to the first , . But that's not gonna work out great for later.

**Comment by stevebauman** [comment]
Hi @joveice,

I'm not sure what you mean? Are you able to explain further what you're doing and what you're trying to accomplish with some of your code?

**Comment by joveice** [comment]
@stevebauman Okey so I tried to import users from a group but that didn't work at all. But Adldap::search()->all(); returned all users, even subgroups it looks like, but it does include the groups in the search, so if I have a group named "Admins" It shows up in the results as "Admins". Is there a way to only get the users?

**Comment by stevebauman** [comment]
You need to create a [Scope](https://github.com/Adldap2/Adldap2-Laravel/blob/master/docs/auth/scopes.md).

Once you have a scope created and you've inserted it into your `config/adldap_auth.php` file, you first have to locate the group, and then limit the LDAP query by it.

For example, you could create a directory named `scopes` and use this scope below (`app/scopes/AdminScope.php`):

```php
namespace App\Scopes;

use Adldap\Query\Builder;
use Adldap\Laravel\Facades\Adldap;
use Adldap\Laravel\Scopes\ScopeInterface;

class AdminScope implements ScopeInterface
{
    /**
     * {@inheritdoc}
     */
    public function apply(Builder $builder)
    {
        // Locate our admin group
        $group = Adldap::search()->groups()->find('Admins');
        
        // Restrict our query to users who are members of the 'Admin' group
        $builder->whereMemberOf($group);
    }
}
```

**Comment by stevebauman** [comment]
However, just so you're aware, the above scope will only allow users of your 'Admin' group to authenticate to your application.

If you only want to import admins using the import command, you must use a filter and insert the 'Admin' groups distinguished name when running it:

```cmd
php artisan adldap:import --filter "(memberof=cn=Admins,dc=acme,dc=org)"
```

**Comment by joveice** [comment]
@stevebauman, the scope works great, thanks for the help on that.
But the filter part did not (or I do not know yet). I do believe that the scope broke import, as it returns

[ErrorException]
ldap_escape() expects parameter 1 to be string, object given

Is this just how it is, or do I have to do something to be able to use both?
