### ISSUE TITLE
Scope - These credentials do not match our records

### ISSUE THREAD

**Issue by ownmaster** [Adldap2/Adldap2-Laravel#391]
Hi.

- Laravel Version: 5.5.3
- Adldap2-Laravel Version: 3.0.5
- PHP Version: 7.1.9

Trying to apply scope for authentication. Without scope authentication works fine.
Following [this manual](https://github.com/Adldap2/Adldap2-Laravel/blob/master/docs/auth/scopes.md) I created a scope and registered it. After that authentication gives "These credentials do not match our records" error.
Even when I expanded the scope to the whole domain ('DC=company,DC=com') it still fails.
```
<?php namespace App\Scopes;

use Adldap\Query\Builder;
use Adldap\Laravel\Scopes\ScopeInterface;

class AuthScope implements ScopeInterface
{
    /**
     * Apply the scope to a given LDAP query builder.
     *
     * @param Builder $query
     *
     * @return void
     */
    public function apply(Builder $query)
    {
        // The distinguished name of our LDAP group.
        $group = 'DC=company,DC=com';

        $query->whereMemberOf($group);
    }
}
```
```
'scopes' => [
        Adldap\Laravel\Scopes\UpnScope::class,
        App\Scopes\AuthScope::class,
    ],
```
What can be the reason?

EDIT: I tried to achieve the same goal using [Rules](https://github.com/Adldap2/Adldap2-Laravel/blob/master/docs/auth/rules.md) and inGroup() method and got the same error.
How can I check the problem cause?

**Comment by stevebauman** [comment]
Hi @ownmaster, with your current scope, no users would be allowed to authenticate, so your scope is actually working correctly.

The group you've entered isn't a group, it's your base distinguished name. This is already set in your configuration using the `base_dn` option.

If you want to scope users by their group, you need to either provide the full groups DN to the `whereMemberOf()` method, or if you're looking to scope users by an OU, you'll need to use the `in()` method:

```php
// Group
$group = 'cn=Accounting,ou=Groups,dc=corp,dc=acme,dc=com';

$query->whereMemberOf($group);
```

```php
// OU
$ou = 'ou=User Accounts,dc=corp,dc=acme,dc=com';

$query->in($ou);
```

**Comment by ownmaster** [comment]
Thanks.
The problem I had consisted of 2 parts:
1) I was trying to filter by OU using `whereMemberOf` that you mentioned
2) I was checking groups from Windows AD Users & Computers, and there, for some groups, it shows that user is inside of the group, but the group itself is not actually in user's `memberOf` array.
