### ISSUE TITLE
After importing users, logging in as said users results in "These credentials do not match our records."

### ISSUE THREAD

**Issue by Payden-Pringle** [Adldap2/Adldap2-Laravel#392]
I may be misunderstanding how importing works. I assume the password is pulled from the Domain and hashed upon import, without needing to login as the user first. This is because when I look at the Users table in my database, the password field has a hashed value in it after importing. Unless this is a randomized 16 character password that is mentioned elsewhere, I'm not sure what else that could mean.

- Laravel Version: 5.4.36
- Adldap2-Laravel Version: 3.0.5 w/ adldap2 v7.0.15
- PHP Version: 7.1.9

### Description:
After importing users with `php artisan adldap:import`, logging in as an imported user results in "These credentials do not match our records."

### Steps To Reproduce:

1. Configure adldap2-laravel to where it can successfully import users from a domain.
2. Import a user to the Users table Laravel produces.
3. Setup Laravel authentication.
4. Attempt to login as imported user to Laravel.

If I attempt to register the user with the same username and password through the Register page Laravel produces when you make:auth, that works fine. Then I can login with said user with no issues. It's just imported users that have this problem. 

### Settings:

adldap_auth:

```
<?php

return [
    'connection' => env('ADLDAP_CONNECTION', 'default'),
    'provider' => Adldap\Laravel\Auth\DatabaseUserProvider::class,
    'resolver' => Adldap\Laravel\Auth\Resolver::class,
    'importer' => Adldap\Laravel\Auth\Importer::class,
    'rules' => [
        // Denys deleted users from authenticating.
        Adldap\Laravel\Validation\Rules\DenyTrashed::class,
        // Allows only manually imported users to authenticate.
        // Adldap\Laravel\Validation\Rules\OnlyImported::class,
    ],
    'scopes' => [
        Adldap\Laravel\Scopes\UpnScope::class,
    ],
    'usernames' => [
        'ldap' => 'samaccountname',
        'eloquent' => 'username',
    ],
    'login_fallback' => env('ADLDAP_LOGIN_FALLBACK', true),
    'password_sync' => env('ADLDAP_PASSWORD_SYNC', true),
    'windows_auth_attribute' => ['samaccountname' => 'AUTH_USER'],
    'sync_attributes' => [
        'username' => 'samaccountname',
        'name' => 'cn',
    ],
];
```

adldap:

```
<?php

return [
    'connections' => [
        'default' => [
            'auto_connect' => true,
            'connection' => Adldap\Connections\Ldap::class,
            'schema' => Adldap\Schemas\ActiveDirectory::class,
            'connection_settings' => [
                'account_prefix' => env('ADLDAP_ACCOUNT_PREFIX', ''),
                'account_suffix' => env('ADLDAP_ACCOUNT_SUFFIX', ''),
                'domain_controllers' => explode(' ', env('ADLDAP_CONTROLLERS', 'dc1.domain.com dc2.domain.com')),
                'port' => env('ADLDAP_PORT', 389),
                'timeout' => env('ADLDAP_TIMEOUT', 5),
                'base_dn' => env('ADLDAP_BASEDN', 'DC=DOMAIN,DC=COM'),
                'admin_account_suffix' => env('ADLDAP_ADMIN_ACCOUNT_SUFFIX', ''),
                'admin_username' => env('ADLDAP_ADMIN_USERNAME', 'DOMAIN\user'),
                'admin_password' => env('ADLDAP_ADMIN_PASSWORD', 'password'),
                'follow_referrals' => false,
                'use_ssl' => false,
                'use_tls' => false,
            ],
        ],
    ],
];
```

The only changes made to the LoginController were for username authentication instead of emails. Meaning this was added:

```
    public function username()
    {
    return 'username';
    }
```

**Comment by stevebauman** [comment]
Hi @Payden-Pringle,

> I assume the password is pulled from the Domain and hashed upon import, without needing to login as the user first.

Passwords cannot be retrieved from Active Directory. All imported users have their password set to a random 16 character string:

https://github.com/Adldap2/Adldap2-Laravel/blob/v3.0/src/Commands/Import.php#L115

If a user tries to login and they successfully bind to your LDAP server, and if you have `password_sync` enabled, their password will be updated to their current LDAP password.

Do you have password sync disabled in your `.env`? I see it's enabled in your configuration that you've posted, but since it's using an environment variable, you could have it set to false.

**Comment by Payden-Pringle** [comment]
Thanks @stevebauman That's what I had a feeling was happening. Sorry for my misunderstanding.

I'm not sure what you mean, as my `.env` does not have a `ADLDAP_PASSWORD_SYNC` variable in it.

My use case for adldap2 is to copy a domain controller's list of users. After that, I don't need authentication. Just querying for group membership and things like that. So, knowing that's how importing and binding works is enough.

**Comment by stevebauman** [comment]
Ok sounds good! No problem at all.
