### ISSUE TITLE
Case sensitivity issues with postgresql

### ISSUE THREAD

**Issue by DavidHoagland** [Adldap2/Adldap2-Laravel#395]
- Laravel Version: 5.4
- Adldap2-Laravel Version: 3.0.5
- PHP Version: 5.6.31

### Description:
Postgresql is case sensitive and fails to find users imported from AD if user types their username with wrong casing.
Example
AD username = BobJones
user input = bobjones

The case sensitive search fails to find the user and throws an error because of a duplicate user.

### Steps To Reproduce:

Create Laravel project with Postgresql login and then login again with casing that doesn't match database username.

### Potential Solution:

In Adldap\Laravel\Auth\Importer line 53:
Currently
`$query->where($key, $value);`

Suggestion
`use Illuminate\Database\PostgresConnection;`

`$model->getConnection() instanceof PostgresConnection ? $query->where($key, 'ilike', $value) : $query->where($key, $value);`

This will allow postgres users to more reliably find users that are already in the database.

**Comment by stevebauman** [comment]
This is actually an issue with Laravel itself and exists as an issue using PostGre with the default Laravel database driver:

https://github.com/laravel/framework/issues/9430

Simply `strtolower` your usernames before authentication. This will resolve your issue.

**Comment by harrygulliford** [comment]
@stevebauman Unfortunately this does not help if the username being pulled out of Ldap is capitalized.

**Comment by DavidHoagland** [comment]
I found a functional fix, I change the username to type CIText when I migrate the user table.

**Comment by harrygulliford** [comment]
@DavidHoagland Have just found a fix by overriding the default Adldap2-Laravel Importer class.

1. Within your `/app` dir, create a new folder `Adldap`.
2. Inside that, make a new file `Importer.php`.
3. Copy and paste the code at the bottom of this comment into the new file. Take note of the where query, a string arg has been added in so as though it is not case sensitive ("ILIKE").
4. Open the `/config/adldap_auth.php` file and locate `'importer' => Adldap\Laravel\Auth\Importer::class,` (~line 68). Comment that line out and add `'importer' => App\Adldap\Importer::class,`

Now when it attempts to query the database to check if a value already exists, it'll ignore the case. This will work no matter what field you chose to id the user by (username/email/etc).

```
<?php

namespace App\Adldap;

use Adldap\Models\User;
use Adldap\AdldapException;
use Adldap\Laravel\Auth\ImporterInterface;
use Illuminate\Support\Str;
use Illuminate\Database\Eloquent\Model;

class Importer extends \Adldap\Laravel\Auth\Importer implements ImporterInterface
{

    /**
     * Retrieves an eloquent user by their credentials.
     *
     * @param Model $model
     * @param array $credentials
     *
     * @return Model|null
     */
    protected function findByCredentials(Model $model, array $credentials = [])
    {
        if (empty($credentials)) {
            return;
        }

        $query = $model->newQuery();

        if ($query->getMacro('withTrashed')) {
            // If the withTrashed macro exists on our User model, then we must be
            // using soft deletes. We need to make sure we include these
            // results so we don't create duplicate user records.
            $query->withTrashed();
        }

        foreach ($credentials as $key => $value) {
            if (! Str::contains($key, 'password')) {
                $query->where($key, "ILIKE", $value); // Changed to add "ILIKE" var as PostgreSQL is case sensitive.
            }
        }

        return $query->first();
    }

}
```
