### ISSUE TITLE
User model

### ISSUE THREAD

**Issue by arek071** [Adldap2/Adldap2-Laravel#40]
Hello, could you tell me is it possible to authenticate user by adldap, then store some information in database users table, but without password? I tried to do this, but with no effect :( it still store AD password in users table..

**Comment by stevebauman** [comment]
You'll need to create you're own `AuthUserProvider` and extend the `AdldapAuthUserProvider` (maybe in `app/providers`?). Then override the `syncModelPassword` method. For example:

```php
use Adldap\Laravel\AdldapAuthUserProvider;

class LdapAuthUserProvider extends AdldapAuthUserProvider
{
    protected function syncModelFromAdldap(User $user, Authenticatable $model)
    {
         return $model;
    }
}
```
