### ISSUE TITLE
Username required

### ISSUE THREAD

**Issue by jnmcfly** [Adldap2/Adldap2-Laravel#400]
- Laravel Version: 5.4
- Adldap2-Laravel Version: 
- PHP Version: 7.1.9

### Description:

Hey guys we are running into some wired issues on using adldap2. We are trying to authenticate users over a login form. A manual import via "php artisan"  works fine. Ldap bind works correct and passhash is stored in the database. We are authenticating against a Active Directory with samaccountname. Now back to the login form, laravel throws an error like: 

```
UsernameRequiredException 



A username must be specified.


in Guard.php (line 110) 



at Guard-validateCredentials(null, 'geheim')

in Guard.php (line 34) 



at Guard-attempt(null, 'geheim')

in Resolver.php (line 67) 
```

Some files:

login.blade.php
https://pastebin.com/815RYfni

LoginController.php
https://pastebin.com/es9RLarW

User.php
https://pastebin.com/fr3FJW13

AuthenticatesUsers.php
https://pastebin.com/WaQVn10U

**Comment by mackhankins** [comment]
Yep, I've got a not-null violation when it tries to create a user in 5.5.

**Comment by gbryant200** [comment]
I'm not able to get the 'username' either.

Laravel 5.6.15
adldap2/adldap 8.1.4
adldap2-laravel 4.07
LDAP - Active directory

I've modified my login.blade.php file (changed all 'email' to 'username'):
<div class="form-group row">
                            <label for="username" class="col-sm-4 col-form-label text-md-right">{{ __('Username') }}</label>

                            <div class="col-md-6">
                                <input id="username" type="text" class="form-control{{ $errors->has('username') ? ' is-invalid' : '' }}" name="username" value="{{ old('username') }}" required autofocus>

                                @if ($errors->has('username'))
                                    <span class="invalid-feedback">
                                        <strong>{{ $errors->first('username') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

added to the LoginController.php:
public function username() {
    	return 'username';
    }

If I dd($username, $password) in the Guard.php validateCredentials - $username is null; $password is correct.

any ideas?  Is Laravel defaulting to 'email' somewhere else?  I followed the Quick Start from scratch doc. and updated the config/auth.php driver also.

Any help would be greatly appreciated.

Thanks,

**Comment by gbryant200** [comment]
If I return my username from
public function username() {
     return 'my username'
}

I get a list in the log file:
user 'my username' has been successfully found for authentication
user 'my username' is being synchronized
user 'my username' has been successfully synchronized
user 'my username' is authenticating with username: ''

'my username' isn't added to my local user table.

**Comment by gbryant200** [comment]
I'm having this same issue
