### ISSUE TITLE
After login don't forwards to specific path

### ISSUE THREAD

**Issue by berni69** [Adldap2/Adldap2-Laravel#403]
- Laravel Version: v5.5.4
- Adldap2-Laravel Version: v3.0.5
- PHP Version: 7.1.7

### Description:

After add Adldap to my project after a success login I don't get redirect to /home.  If I use my custom provider I can get logged and redirected to /home. 

### Steps To Reproduce:

I will try to explain my best about my app, I hope you can help me.

I'm trying to access http://myapp/home but after a success login I get redirect to a login page again, if I send invalid credentials then I am able to see a wrong credentials error message. 

I attached my config files for adldap2/adldap2-laravel:

[adldap_auth.txt](https://github.com/Adldap2/Adldap2-Laravel/files/1378763/adldap_auth.txt)
[adldap.txt](https://github.com/Adldap2/Adldap2-Laravel/files/1378764/adldap.txt)

I added the providers to app.php:

```php
    'providers' => array(....
        /*
         * AD LDAP Provider
         */
        Adldap\Laravel\AdldapServiceProvider::class,
        Adldap\Laravel\AdldapAuthServiceProvider::class,);
```

That's my user model:

```php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;


    //Tablename
    public $table = 'TB_Usuarios';

    //ID
    protected $primaryKey = "idUsuario";
    public $incrementing = false;


    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'idUsuario', 'Descripcion', 'Mail', 'Passwd',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'Passwd', 'remember_token',
    ];

    public function getAuthPassword()
    {
        return $this->Passwd;
    }

    public function getAuthIdentifierName()
    {
        return 'Descripcion';
    }

    public function getAuthIdentifier()
    {
        return $this->idUsuario;
    }

}
```

app\auth.php

```php

    'providers' => [
        'users' => [
            //'driver' => 'eloquent',
            'driver' => 'adldap',//ADLDAP
            //'driver' => 'custom', //Paswords locales en DB
            'model' => App\User::class,
        ],
    ],
```

After made the login I get redireted again to the login page, but on the database I¡m able to see how the user information is updated .

**Comment by stevebauman** [comment]
Hi @berni69,

The redirect URL is set in your `app/Http/Controllers/Auth/LoginController`.

You will need to add the following method to this controller and configure it for the URL you would like to redirect users to:

```php
/**
 * The path to redirect authenticated users to.
 *
 * @return string
 */
public function redirectTo()
{
    return url('/');
}
```

If you still experience this issue, please let me know and I'll re-open this issue.

**Comment by berni69** [comment]
I'm still experiencing this issue after add this function to the login controller

LoginController.php
```php
class LoginController extends Controller
{
    /*
    |--------------------------------------------------------------------------
    | Login Controller
    |--------------------------------------------------------------------------
    |
    | This controller handles authenticating users for the application and
    | redirecting them to your home screen. The controller uses a trait
    | to conveniently provide its functionality to your applications.
    |
    */

    use AuthenticatesUsers;

    /**
     * Where to redirect users after login.
     *
     * @var string
     */
    protected $redirectTo = '/home';

    /**
     * The path to redirect authenticated users to.
     *
     * @return string
     */
    public function redirectTo()
    {
        return url('/');
    }


    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('guest')->except('logout');
    }

    public function username()
    {
        return 'idUsuario';
    }


}

```

**Comment by stevebauman** [comment]
Ok so you're authenticating without issue, just return a redirect from the `authenticated` method:

```php
/**
 * The user has been authenticated.
 *
 * @param  \Illuminate\Http\Request  $request
 * @param  mixed  $user
 * @return mixed
 */
protected function authenticated(Request $request, $user)
{
    return redirect('/home');
}
```

If it's still not working, something is going on in your application. Adldap2 doesn't control any redirects or middleware. It's simply an LDAP authentication driver, and as you've shown, it's working on your end.

**Comment by berni69** [comment]
It seems that the redirect works but I found another thing
![imagen](https://user-images.githubusercontent.com/1116133/31612136-0af6ccb2-b27f-11e7-9525-1f7d3806417a.png)
As you can see I made a success login, I redirected to the home page but when I check If I'm logged In the controller the auth check fails and I get redirected again to the login page:

That's constructor:

```php
    public function __construct()
    {
        $this->middleware('auth');
    }
```

The controller is a dummy controller generated with the laravel auth module.

**Comment by stevebauman** [comment]
Sounds like a session driver issue. I've experienced this with earlier versions of Laravel using the `file` session driver.

What is your session driver right now?

**Comment by berni69** [comment]
It happens with predis driver and file session driver.

**Comment by stevebauman** [comment]
I would try with the database driver and see if you still encounter the same issue. Adldap2 does not manage sessions.

**Comment by berni69** [comment]
Happens the same thing, but now I'm able to see the db with a new field:

![imagen](https://user-images.githubusercontent.com/1116133/31612842-7223f5ac-b281-11e7-9a06-67dab465a907.png)

**Comment by stevebauman** [comment]
Strange, can you post your `app/Http/Kernel.php` as well as your `routes/web.php` file?

**Comment by berni69** [comment]
Of course I can:

Kernel.php
```php
<?php

namespace App\Http;

use Illuminate\Foundation\Http\Kernel as HttpKernel;

class Kernel extends HttpKernel
{
    /**
     * The application's global HTTP middleware stack.
     *
     * These middleware are run during every request to your application.
     *
     * @var array
     */
    protected $middleware = [
        \Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode::class,
        \Illuminate\Foundation\Http\Middleware\ValidatePostSize::class,
        \App\Http\Middleware\TrimStrings::class,
        \Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull::class,
        \App\Http\Middleware\TrustProxies::class,
    ];

    /**
     * The application's route middleware groups.
     *
     * @var array
     */
    protected $middlewareGroups = [
        'web' => [
            \App\Http\Middleware\EncryptCookies::class,
            \Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::class,
            \Illuminate\Session\Middleware\StartSession::class,
            // \Illuminate\Session\Middleware\AuthenticateSession::class,
            \Illuminate\View\Middleware\ShareErrorsFromSession::class,
            //\App\Http\Middleware\VerifyCsrfToken::class,
            \Illuminate\Routing\Middleware\SubstituteBindings::class,
        ],

        'api' => [
            'throttle:60,1',
            'bindings',
        ],
    ];

    /**
     * The application's route middleware.
     *
     * These middleware may be assigned to groups or used individually.
     *
     * @var array
     */
    protected $routeMiddleware = [
        'auth' => \Illuminate\Auth\Middleware\Authenticate::class,
        'auth.basic' => \Illuminate\Auth\Middleware\AuthenticateWithBasicAuth::class,
        'bindings' => \Illuminate\Routing\Middleware\SubstituteBindings::class,
        'can' => \Illuminate\Auth\Middleware\Authorize::class,
        'guest' => \App\Http\Middleware\RedirectIfAuthenticated::class,
        'throttle' => \Illuminate\Routing\Middleware\ThrottleRequests::class,
    ];
}
```

web.php
```php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/menu', 'MenuController@index')->name('menu');



```

**Comment by stevebauman** [comment]
Hmmm, looks fine to me...

Whenever you refresh your application, is a new session created in your database? Or do you have the same session upon refresh?

**Comment by berni69** [comment]
I only Saw a Row on my database

**Comment by stevebauman** [comment]
Can you try switching your auth driver to the default `eloquent` and see if you experience this?

**Comment by berni69** [comment]
I reset my branch of the app since the driver of eloquent worked last time, after that I saw that making tests I set this property in the user model:

```php

public function getAuthIdentifier()
    {
        return $this->idUsuario;
    }
```
This break my authentications controllers.

Thanks you for your help,  I appreciate it a lot. :)

**Comment by softmixt** [comment]
Chang: 

1 .env SESSION_DRIVER=database
2.  php artisan session:table 
3. php artisan migrate

then try to login I had same issue with file session driver and by changing to db  problem was solved.
