### ISSUE TITLE
LDAP authentication fails but can ldap user search

### ISSUE THREAD

**Issue by kevin042** [Adldap2/Adldap2-Laravel#404]
- Laravel Version: 5.4.36
- Adldap2-Laravel Version: 3.0
- PHP Version: 5.6.21

### Description:
Hi,

Hope anybody can help me on this since I'm stuck at if for days.
I already set up adldap on my laravel project by following on this link: https://github.com/Adldap2/Adldap2-Laravel but I keep on encountering an error that my credentials did not match on my record.   Just to test my connection I tried searching a user using their username and it returned the user so it means my connection settings is correct.

dd(Adldap::search()->where('samaccountname', '=', request('username'))->get());

**Comment by stevebauman** [comment]
Hi @kevin042, I need more details to help troubleshoot this.

It sounds like a configuration issue, can you post your configuration with sensitive details omitted?

**Comment by kevin042** [comment]
Hello Sir Steve,

Good day,

Thank you for the quick response, please see below my configurations.

File: adldap.php

<?php
return [
    'connections' => [
        'default' => [
            'auto_connect' => true,
            'connection' => Adldap\Connections\Ldap::class,
            'schema' => Adldap\Schemas\ActiveDirectory::class,
            'connection_settings' => [
                'account_prefix' => env('ADLDAP_ACCOUNT_PREFIX', ''),
                'account_suffix' => env('ADLDAP_ACCOUNT_SUFFIX', ''),
                'domain_controllers' => explode(' ', env('ADLDAP_CONTROLLERS', 'XXX.XXX.XX.XX')), //IP Address
                'port' => env('ADLDAP_PORT', 389),
                'timeout' => env('ADLDAP_TIMEOUT', 5),
                'base_dn' => env('ADLDAP_BASEDN', 'OU=XXXXX,DC=XXXXX,DC=XXXXX'),
                'admin_account_suffix' => env('ADLDAP_ADMIN_ACCOUNT_SUFFIX', ''),
                'admin_username' => env('ADLDAP_ADMIN_USERNAME', 'CN=XXXXXXXXX.,OU=XXXXX,OU=XXXXX,OU=XXXXXXX,DC=XXXXXXX,DC=XXXXX'),
                'admin_password' => env('ADLDAP_ADMIN_PASSWORD', 'XXXXXXXX'),
                'follow_referrals' => false,
                'use_ssl' => false,
                'use_tls' => false,
            ],
        ],
    ],
];
[adldap.txt](https://github.com/Adldap2/Adldap2-Laravel/files/1389505/adldap.txt)

File: adldap_auth.php
[adldap_auth.txt](https://github.com/Adldap2/Adldap2-Laravel/files/1389517/adldap_auth.txt)

<?php
return [
    'connection' => env('ADLDAP_CONNECTION', 'default'),
    'provider' => Adldap\Laravel\Auth\DatabaseUserProvider::class,
    'resolver' => Adldap\Laravel\Auth\Resolver::class,
    'importer' => Adldap\Laravel\Auth\Importer::class,
    'rules' => [
        Adldap\Laravel\Validation\Rules\DenyTrashed::class,
    ],
    'scopes' => [
        Adldap\Laravel\Scopes\UpnScope::class,
    ],
    'usernames' => [
        'ldap' => env('ADLDAP_USER_ATTRIBUTE', 'samaccountname'), // Was userprincipalname
        'eloquent' => 'username',
    ],
    'login_fallback' => env('ADLDAP_LOGIN_FALLBACK', false),
    'password_sync' => env('ADLDAP_PASSWORD_SYNC', true),
    'windows_auth_attribute' => ['samaccountname' => 'AUTH_USER'],
    'sync_attributes' => [
        'username' => 'samaccountname',
        'name' => 'cn',
    ],

];

File: app.php (Added to file)
Adldap\Laravel\AdldapServiceProvider::class,
Adldap\Laravel\AdldapAuthServiceProvider::class,

'Adldap' => Adldap\Laravel\Facades\Adldap::class,

File: auth.php (Updated to file)
'providers' => [
        'users' => [
            'driver' => 'adldap', //Was eloquent
            'model' => App\User::class,
        ],
    ],

File: LoginController (in auth directory)

 public function username()
    {
        return config('adldap_auth.usernames.eloquent');
    }

    protected function validateLogin(Request $request)
    {
        $this->validate($request, [
            $this->username() => 'required|string',
            'password' => 'required|string',
        ]);
    }

    protected function attemptLogin(Request $request)
    {

        $credentials = $request->only($this->username(), 'password');
        $username = $credentials[$this->username()];
        $password = $credentials['password'];

        if (Adldap::search()->where('samaccountname', '=', $username)->get()) {
            // the user exists in the LDAP server, with the provided password
            $user = \App\User::where($this->username(), $username)->first();
            if ($user) {
                $this->guard()->login($user, true);

                return redirect('/');
            }else {
                return back()->withErrors([
                    'message' => 'Username and password did not match.'
                ]);
            }
        }
    }

File: .env
ADLDAP_CONNECTION=default
ADLDAP_CONTROLLERS=XXX.XXX.XX.XX // IP Address of AD
ADLDAP_BASEDN=OU=XXXXX,DC=XXXXXX,DC=XXX
ADLDAP_USER_ATTRIBUTE=samaccountname
ADLDAP_USER_FORMAT='CN=XXXXX.,OU=XXXX,OU=XXXX,OU=XXXXXXX,DC=XXXXXX,DC=XXXX'

Those are all the configurations I made on the system.

**Comment by kevin042** [comment]
Hello Sir @stevebauman ,

Good day,

Do you have an update on where I possibly gone wrong on the configuration?

**Comment by kevin042** [comment]
Found the error on the configuration.

**Comment by stevebauman** [comment]
Hi @kevin042, sorry for the long response. Thanks for troubleshooting your issue on your own and resolving it :)

**Comment by kevin042** [comment]
Hi @jLopez23, can you post your code here, I'll take a look at it.

**Comment by jLopez23** [comment]
@kevin042, my problem I post it in the following link: https://github.com/Adldap2/Adldap2-Laravel/issues/580

**Comment by kevin042** [comment]
@jLopez23 ok will take a look at it.

**Comment by jLopez23** [comment]
@kevin042 thanks, I appreciate your help too much.

**Comment by kevin042** [comment]
Hi @jLopez23 are you using Windows AD? if yes try to empty your ADLDAP_ACCOUNT_PREFIX and for the  ADLDAP_ACCOUNT_SUFFIX try using something like "@activedirectory.local"

**Comment by jLopez23** [comment]
@kevin042, I already tried but it does not work, it's just working for me by concatenating the ADLDAP_ADMIN_USERNAME with ADLDAP_ACCOUNT_SUFFIX in my .env file in the following way: ADLDAP_ADMIN_USERNAME = "administrator@activedirectory.local" but as I mentioned before I do not know if this is a good solution

**Comment by kevin042** [comment]
@jLopez23 if it works on that method then it's fine.  Just don't use the administrator account and make sure to secure your .env file

**Comment by jLopez23** [comment]
@kevin042 thanks, some advice on how to protect my .env file
