### ISSUE TITLE
Why no logging?

### ISSUE THREAD

**Issue by marlboro** [Adldap2/Adldap2-Laravel#409]
I really like this package, but it's always been difficult for me to troubleshoot.  It's supposed to be integrated into Laravel, but as far as I can tell, it makes no use of the log.  This would make troubleshooting so much easier.  Would this be possible?

Thanks!

**Comment by stevebauman** [comment]
Hi @marlboro, I completely agree with you. I should build in logging for troubleshooting purposes.

Thanks for the suggestion!

**Comment by stevebauman** [comment]
Logging is now available in `v4.0`:

https://github.com/Adldap2/Adldap2-Laravel/blob/master/docs/auth.md#logging

Events are configurable via the `events` array:

https://github.com/Adldap2/Adldap2-Laravel/blob/3e118ce82c7fb8d90d7fedfe331c825a5812e904/src/Config/auth.php#L286-L305
