### ISSUE TITLE
Adldap::auth()->attempt bypasses config/.env?

### ISSUE THREAD

**Issue by Zazu42** [Adldap2/Adldap2-Laravel#410]
- Laravel Version: 5.4
- Adldap2-Laravel Version: most recent? installed yesterday
- PHP Version: 7

### Description:

First of all im very new to coding github and all the stuff so i'm very sorry if i don't do everything right here.

So what i dont understand: to check if its working i added the line 

Adldap::auth()->attempt('admin', 'pw', true); 

to the constructor of my loginController 

and everything works fine authentication and the migration of the user to the local DB. Now if i remove this line the standard login form displays the error auth.failed. I thought Adldap::auth()->attempt would only check the connection why does it stop working if i remove this line?

really sorry if this is a vague discription. but i thought you may know what config Adldap::auth()->attempt('admin', 'pw', true);  might be bypassing that i made wrong.

**Comment by stevebauman** [comment]
Do you have an 'admin' account configured in your `.env` or `config/adldap.php` file?

Calling `Adldap::auth()->attempt()` with the third argument as `true` will actually bind to your LDAP server as the given user, allowing the Adldap2 auth driver to utilize the bound connection to search for the user and authenticate them correctly.

This would explain why the removal of the line breaks your authentication.

**Comment by Zazu42** [comment]
That makes sense. But I have the same account setup in the env. Maybe I messed up the pre/suffixes. Well if that auth attempt makes it work I just need to use the suffix and prefix that funktion uses to connect? What would that be?

**Comment by stevebauman** [comment]
Your `account_prefix` and `account_suffix` is applied to all accounts (even the administrator account you configure), **unless** you specifically configure the `admin_account_suffix` and `admin_account_prefix`.

If the `auth()->attempt()` method is returning true, simply add your admins username and password into your `.env` file:

```env
ADLDAP_ADMIN_USERNAME=admin
ADLDAP_ADMIN_PASSWORD=password
```

**Comment by Zazu42** [comment]
omg i found it, im so sorry i wasted your time. For some awkward reason i set  'auto_connect' => false, in the adldap.php probably because i did my debugging like this: https://xkcd.com/627/ "follow any instructions" can sometimes mess things up. Thank you some much for this wonderful addon. I appreciate your help so much.

**Comment by stevebauman** [comment]
Hi @Zazu42 that's great! I'm glad you've got it working :).

Thanks for your kind words and no problem at all for assistance.

If you have any other issues let me know!
