### ISSUE TITLE
When the "admin_account_suffix" is set to an empty string "", the "account_suffix" is added when trying to log in as an administrator

### ISSUE THREAD

**Issue by epas1117** [Adldap2/Adldap2-Laravel#411]
- Laravel Version: 5.4
- Adldap2-Laravel Version: 3.0.5
- PHP Version: 7.1

### Description:

Because PHP treats NULL, false, 0, and the empty string as equal.
In line 74 of the Guard.php class the suffix is added despite an empty string "" is set in the admin_account_suffix configuration variable. So it's not possible to log in as an administrator.

### Steps To Reproduce:

1.- Follow the steps on the documentation to log in with the "samaccountname" of an active directory user
2.- Set the "account_suffix" to @domain.com
3.- Set the "admin_account_suffix" to an empty string ""

**Comment by stevebauman** [comment]
This was fixed in the root Adldap2 repository. Adldap2-Laravel `v4.0` now utilizes this new Adldap2 version and will now allow you to use an empty string as the account suffix:

https://github.com/Adldap2/Adldap2/blob/85c7532c4eb9208c5479c2881593e03e29ae277a/src/Auth/Guard.php#L116-L122
