### ISSUE TITLE
Column email not found when authenticating

### ISSUE THREAD

**Issue by aityahiaidir** [Adldap2/Adldap2-Laravel#412]
- Laravel Version: 5.5
- Adldap2-Laravel Version: 3.0.5
- PHP Version: 7.1

### Description:
i configured an authentication with Ldap following the [instructions ](https://github.com/Adldap2/Adldap2-Laravel/blob/master/docs/quick-start.md), the authentication is done correctly since I can retrieve the full name of the user from my Active Directory server, but when the provider tries to insert the user into the database. La ravel raises an exception column email not found

> SQLSTATE[42S22]: Column not found: 1054 Unknown column 'email' in 'field list' (SQL: insert into `users` (`email`, `name`, `password`, `updated_at`, `created_at`) values (my user data) 

the user model used is not the good one, I missed something?

**Comment by stevebauman** [comment]
Looks like you're trying to simply set the users email address when the column doesn't exist.

Are you using a username to authenticate users instead of email?

If so, you will need to change the configuration for this in your `config/adldap_auth.php` file.

**Comment by aityahiaidir** [comment]
normally I made the necessary changes

here is a snippet of my file config/adldap_auth.php

`'usernames' => [

        /*
        |--------------------------------------------------------------------------
        | LDAP
        |--------------------------------------------------------------------------
        |
        | This is the LDAP users attribute that you use to authenticate
        | against your LDAP server. This is usually the users
        |'sAMAccountName' / 'userprincipalname' attribute.
        |
        | If you'd like to use their username to login instead, insert `samaccountname`.
        |
        */

        'ldap' => 'samaccountname',

        /*
        |--------------------------------------------------------------------------
        | Eloquent
        |--------------------------------------------------------------------------
        |
        | This is the attribute that is used for locating
        | and storing the LDAP username above.
        |
        | If you're using a `username` field instead, change this to `username`.
        |
        | This option is only applicable to the DatabaseUserProvider.
        |
        */

        'eloquent' => 'username',

    ]`

**Comment by aityahiaidir** [comment]
I solved the problem,  finally, I had not changed the sync_attributes array

'''sync_attributes' => [

        'username' => 'samaccountname',
        'name' => 'cn',

    ],

it's important to add this step to the tutorial  [Quick Start - From Scratch](https://github.com/Adldap2/Adldap2-Laravel/blob/master/docs/quick-start.md)
