### ISSUE TITLE
Column not found: 1054 Unknown column 'username' in 'where clause'

### ISSUE THREAD

**Issue by rnrstar** [Adldap2/Adldap2-Laravel#413]
- Laravel Version:  v5.5.19
- Adldap2-Laravel Version:  v3.0.5
- PHP Version: 7.0

### Description:
When I try to authenticate using the Laravel login form, I get an error "These credentials do not match our records." So to troubleshoot the issue I added the following to the web.php routes file.

```
Route::get('/test',function () {
$username = '[username]';
$password = '[password]';

$auth = Auth::attempt(['username'=>$username,
					  'password'=>$password]);
	dd($auth);
});
```
With the above, I'm getting the error:

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'username' in 'where clause' (SQL: select * from `users` where `username` = [username] limit 1)

### Steps To Reproduce:
I followed the steps to integrate this package into laravel. 

One other thing I tried was to put in my web.php routes file:

dd(Adldap::search()->users()->get());

This will dump all the users in AD and it works as expected so I'm pretty sure that I'm able to communicate with the AD server.

**Comment by stevebauman** [comment]
Hi @rnrstar, you have to rename the username column in your `create_users_table` migration.

**Comment by rnrstar** [comment]
This is what I have in my migration.
```
Schema::create('users', function (Blueprint $table) {
            $table->increments('id');
            $table->string('name');
            $table->string('email')->unique();
            $table->string('password');
	    $table->string('ipphone');
	    $table->string('infinitylogin');
            $table->rememberToken();
            $table->timestamps();
        });
```
I got this working on another server and I didn't rename the email field.

**Comment by rnrstar** [comment]
When I renamed the email field to username, I no longer got the error about the username column and then it started to complain about the email column being missing. I renamed the email column back to email from username and then created a username column. Got no errors with that but then I was getting "false" returned from my test route and when I tried logging in using the laravel login page, it again said that the credentials were no good.

**Comment by stevebauman** [comment]
Hi @rnrstar, if you're using `username` as your username field instead of the default `email` field, you will have to modify the `config/adldap_auth.php` file to account for this change.

Please take a look at the auth driver installation documentation: https://github.com/Adldap2/Adldap2-Laravel/blob/master/docs/auth/installation.md

If you encounter any other issues, just let me know, thanks!
