### ISSUE TITLE
Auth::user() can't retreive authenticated user by id, no database.

### ISSUE THREAD

**Issue by ChristopheAupet** [Adldap2/Adldap2-Laravel#415]
- Laravel Version: 5.4
- Adldap2-Laravel Version: 3.0
- PHP Version: 5.6.19

### Description:
Hello!

I've might found something not working as intended.

I am currently using this package with the NoDatabaseUserProvider on an ADldap.
Authentication works fine with Auth::attempt and return correct information, the current user is successfully stored in the session.

I verified session information and how Auth retrieves it in  Auth/SessionGuard.php, everything seems to be fine, it gets correct key name and retrieves correct id.

So this leads me to the NoDatabaseUserProvider using retrieveById function using adldap2-larave/src/Auth/Resolver.php on byId function, i dumoed identifier all the way to this point and it's correctly transmitted. So i assume everything works correctly since we arrive in adldap2/src/Query/Builder.php.

Obviously, it's using query function and in this case call $this->connection->search to match objectsId,
so i dumped the query string: (&(objectclass=\70\65\72\73\6f\6e)(objectcategory=\70\65\72\73\6f\6e)(userprincipalname=*)(objectsid=\53\2d\31\2d\35\2d\32\31\2d\2d\31\31\35\32\36\38\35\32\33\37\2d\32\32\39\35\30\30\31\32\35\2d\2d\31\31\39\36\32\32\35\32\35\33\2d\33\35\30\30))

It's already out of my knowledge but all params seems to have correct value and the results contains : resource(393, ldap result).

So i am assuming processor might not be able to match parameters with previous results.

Please tel me if i am missing something.

**Comment by stevebauman** [comment]
Hi @ChristopheAupet, this is due to the current Adldap2-Laravel version using Adldap2 v7.0.

v8.0 corrects the object SID binary conversion, which is currently used in Adldap2-Laravel's `dev-master` branch.

**Comment by stevebauman** [comment]
Also just to mention, in the new version, GUID's are used instead of the users ObjectSID.

It's more reliable and unique to each user regardless of domain:

https://github.com/Adldap2/Adldap2/commit/90331598169de6ec5446917fefb6334fa72e4a47

**Comment by ChristopheAupet** [comment]
Well thank you for the answer and i agree with the switch on GUID, can't wait to see the update.

**Comment by stevebauman** [comment]
Hi @ChristopheAupet, `v4.0` has been released and now utilizes the users `objectGUID` instead of their `objectSID` which was being incorrectly generated from binary.

**Comment by ChristopheAupet** [comment]
Hey thank you for this update.
I have to mention something about this v4.0 composer reject my upgrade do to my php version wich is as previously mentioned PHP 5.6.19.
Is it intended to works only with PHP 7 or higher ?

**Comment by stevebauman** [comment]
Hi @ChristopheAupet, yes it is, as mentioned in the [Requirements](https://github.com/Adldap2/Adldap2-Laravel#requirements) section of the readme.

**Comment by ChristopheAupet** [comment]
Oh sorry i did not notice it. So it s time for a php upgrade.
Thank you a lot for your help.

**Comment by stevebauman** [comment]
No problem @ChristopheAupet!
