### ISSUE TITLE
Auth::attempt works but can't get AD User details

### ISSUE THREAD

**Issue by allanbritos** [Adldap2/Adldap2-Laravel#416]
- Laravel Version: 5.4
- Adldap2-Laravel Version: 3.0.5
- PHP Version: 5.6.30

### Description:

Hi, this is actually a question regarding the capabilities of this package. I have successfully accomplished the authentication of a user by trying with different variations on the configuration, below what worked for me to:

.env
ADLDAP_BASEDN=dc=domain,dc=com
ADLDAP_USER_ATTRIBUTE=uid
ADLDAP_USER_FORMAT=%s@domain.com

On controller:
$user_format = env('ADLDAP_USER_FORMAT', 'cn=%s,'.env('ADLDAP_BASEDN', ''));
$userdn = sprintf($user_format, $username);
$result = Adldap::auth()->attempt($userdn, $password, $bindAsUser = true);

Now, what I would need is to retrieve a specific attribute from the AD for the user that just tried to authenticate. Can this be done without changing my authprovider?

I've already tried:

//$userdn is formated as user@domain.com

$user = Adldap::search()->where('uid','=',$userdn)->get();
and 
$search = Adldap::search()->users()->find($userdn);

both cases return null.

OUTPUT:
"$USER:"
null
"$SEARCH:"
Collection {#274 ▼
  #items: []
}

Thanks in advance for any help you can provide.
Allan

**Comment by allanbritos** [comment]
Ok just by try and error (and checking aldap2 documentation) I'm able to find users but ONLY! when I use the 'contains' statement, for example:

$result = $search
                ->select(['cn','samaccountname','mail','description'])
                ->where('cn','contains','allan')
                ->limit(5)
                ->get();

This gets me 5 records with their respective attributes, however when I try the below:

$result = $search
                ->select(['cn','samaccountname','mail','description'])
                ->where('samaccountname','=','allan.s')
                ->get();

the result is empty;

also if my where statement is:

->where('samaccountname','contains','allan.s')

the result is also empty, the only difference is the (.) dot in the username

Your advice is greatly appreciated!
Allan

**Comment by stevebauman** [comment]
Hi @allanbritos,

Are you using OpenLDAP or some other LDAP provider? This will help me troubleshoot with you.

Also, you mention that on your controller you're using `Adldap::auth()->attempt()` to authenticate users. This won't authenticate users for your Laravel application and set up a session (unless you're doing it manually).

Did you follow the Adldap2-Laravel auth driver setup shown here?:

https://github.com/Adldap2/Adldap2-Laravel/blob/master/docs/auth/installation.md

**Comment by allanbritos** [comment]
Hi @stevebauman,

I sincerely appreciate your response! For your reference, I'm working with Windows Active Directory.

First I will explain the scope of what I'm trying to accomplish:

I'm working on a custom Single Sign On for my legacy apps. Currently they connect to a .NET SOAP service (built 6 years back) which simply return true/false + user identifier (stored at the AD profile). If the result is true then the app takes the uid received by the service and creates the session.

What I want is to remove the dependency on .NET and incorporate this functionality into one single API made on Laravel, this API handles authentication using Passport so I don't need to setup the auth driver for adldap2-laravel since I'm using it only to check if a username/password is correct for a user and then return the uid for him.

Through the course of this implementation I got to understand the scope of both Adldap2 and Adldap2-Laravel, so I did the following:

```
//using the same values as in the original post + ADLDAP_ACCOUNT_SUFFIX
$config = [
      'account_suffix' => env('ADLDAP_ACCOUNT_SUFFIX'),
      'domain_controllers' => [env('ADLDAP_CONTROLLERS')],
      'base_dn' => env('ADLDAP_BASEDN'),
      'admin_username' => env('ADLDAP_ADMIN_USERNAME'),
      'admin_password' => env('ADLDAP_ADMIN_PASSWORD'),
];

try {
      $ad = new \Adldap\Adldap();
      $ad->addProvider($config);
      $provider = $ad->connect();
      if ($provider->auth()->attempt($username, $password)) {
            print("Success!");
            $user = $provider->search()->users()->find($username);
            dump($user);
      } 
      else {
            dump("Username/Password not Correct");
      }
} 
catch (\Adldap\Auth\BindException $e) {
      dump('ERROR:'.$e);
}
```

This code returns the full **$user** successfully with all the attributes I need, it also gives me the capability of creating the config from a model where I can store multiple providers (since I have segregated domains for prod, nonprod and QA) so from there I will build the required output for the legacy apps.

However I would like to understand why using the adldap2-laravel implementation, everything works up to  **auth->attempt()** but then it breaks on the **search()** of a user at the AD? not sure if it is a bug or it is simply out of the scope of this package but I thought it would be good to bring it to your attention.

Thanks for the great work and contribution!

Best Regards,
Allan

**Comment by Jkrane** [comment]
Hi Allan and Steve,

I am working with ADFS making some in-house apps using the latest Adldap2-Laravel (v5.0.2). First for Allan, did you get your scenario above to work? If so, could you please share what route you ended using to get the search functionality to work?

Steve,

First and foremost, thank you for your contribution here, it is tremendous and I do appreciate all your feedback on people's questions about the package. I was hoping to be able to use the DatabaseUserProvider version set up in auth.php like so:

    'providers' => [
        'users' => [
              'driver' => 'ldap',
              'model'  => App\User::class,
        ],
    ],

and be able to use the inGroup function. What I quickly discovered was that the inGroup functionality is not part of App\User, or at least not the way I am trying to do it. Basically, what I am doing is using adldap2 to get authentication from our ad, grab the group, and then handoff to Passport where I generate a token that is scoped using their group. 

Is there someway to grab the group using DatabaseUserProvider method without doing the "search" functionality Allan used above? Basically I am trying to avoid to trips to ADFS if possible.

Thank you,
Jon

**Comment by Jkrane** [comment]
Steve,

I answered my question, what I needed to understand was model binding:

https://adldap2.github.io/Adldap2-Laravel/#/auth/model-binding?id=model-binding

I added the following to my user model:

use Adldap\Laravel\Traits\HasLdapUser;

I can now access the ldap methods!

Thanks again for making awesome documentation, maintaining this package, and keeping up with our questions!
'
Best regards, Jon
