### ISSUE TITLE
How do i configure my LDAP connection in the config/adldap.php and config/adldap_auth  files.

### ISSUE THREAD

**Issue by scotrolex** [Adldap2/Adldap2-Laravel#417]
- Laravel Version: 5.4
- Adldap2-Laravel Version: 3.0
- PHP Version: 7.0

### Description:
I'm a new user of laravel. I use laravel 5.4. am trying to use ldap authentication in my project .
I followed the tutorial from https://github.com/Adldap2/Adldap2-Laravel.

I stopped at this step because I did not know how to use this code and Don't know how to configure my LDAP connection in the config/adldap.php file but i have a openldap server install on my system.

Thanks in advance

First, configure your LDAP connection in the config/adldap.php file.

Then, you can perform all methods on your Adldap connection through its facade like so:

use Adldap\Laravel\Facades\Adldap;

// Finding a user.
$user = Adldap::search()->users()->find('john doe');

// Searching for a user.
$search = Adldap::search()->where('cn', '=', 'John Doe')->get();

// Authenticating against your LDAP server.
if (Adldap::auth()->attempt($username, $password)) {
// Passed!
}

// Running an operation under a different connection:
$users = Adldap::getProvider('other-connection')->search()->users()->get();

// Creating a user.
$user = Adldap::make()->user([
'cn' => 'John Doe',
]);

$user->save();
Or you can inject the Adldap interface into your controllers:

use Adldap\AdldapInterface;

class UserController extends Controller
{
/**
 * @var Adldap
 */
protected $adldap;

/**
 * Constructor.
 *
 * @param AdldapInterface $adldap
 */
public function __construct(AdldapInterface $adldap)
{
    $this->adldap = $adldap;
}

/**
 * Displays the all LDAP users.
 *
 * @return \Illuminate\View\View
 */
public function index()
{
    $users = $this->adldap->search()->users()->get();

    return view('users.index', compact('users'));
}
}

I will be grateful if you help me  @stevebauman

**Comment by krunaladaptit** [comment]
I am facing the same problem

**Comment by johana57** [comment]
Actually i am having the same problem. Heeeeelp please.

**Comment by scotrolex** [comment]
@johana57  this is issue has been here since last year  nobody  want to help me..  so I left the project unfinished. I think we should work together and help each other.

**Comment by johana57** [comment]
Yeah, great! I am working with:
Laravel Version: 5.5
Adldap2-Laravel Version: 4.0
PHP Version: 7.0

@scotrolex

**Comment by johana57** [comment]
I followed these steps for the configuration:
https://github.com/Adldap2/Adldap2-Laravel/blob/master/docs/quick-start.md

But I have the doubt regarding the configuration of the files adldap.php and adldap_auth.php.
I do not know if the server data should be placed there or in the .env, I have seen in some post that place them in the .env

And sorry for my english Haha!

@scotrolex

**Comment by scotrolex** [comment]
let me go through the configuration link i will get back to you .@johana57 and your english is fine .

**Comment by stevebauman** [comment]
Hi @scotrolex,

> I stopped at this step because I did not know how to use this code and Don't know how to configure my LDAP connection in the config/adldap.php file but i have a openldap server install on my system.

This package assumes you have full knowledge of configuring and working with your LDAP distribution type (Active Directory / OpenLDAP / FreeIPA etc.).

Unfortunately I can't assist you directly with your server configuration, as this is entirely dependent on your environment.

However, I'll link the configuration documentation as well as the authentication setup for your reference as it will help you get started:

[Configuration](https://github.com/Adldap2/Adldap2/blob/master/docs/configuration.md)

[Auth Installation & Configuration](https://github.com/Adldap2/Adldap2-Laravel/blob/master/docs/auth.md#installation)

I'll leave this issue open for discussion and other users looking to help.

**Comment by scotrolex** [comment]
We will be grateful sir .

**Comment by scotrolex** [comment]
@stevebauman if you can please make a tutorials videos starting from installation then setups .I  and @johana57 will be very grateful .cause we have gone through the configuration links still having the same error. I am using Ubuntu 16.04.

**Comment by stevebauman** [comment]
Hi @scotrolex, I'll be working on new documentation, as I know it is definitely lacking right now.

Time has been tight for me, but it's coming, promise!

**Comment by scotrolex** [comment]
Thank you @stevebauman you are the man.

**Comment by isaqueprofeta** [comment]
@scotrolex Try this:

  Minimal config for .env:
  ```
  ADLDAP_CONTROLLERS=myldapserver.example.com
  ADLDAP_ADMIN_USERNAME=cn=admin,dc=example,dc=com
  ADLDAP_ADMIN_PASSWORD=password
  ADLDAP_BASEDN=dc=example,dc=com
  ```

  Changes on adldap_auth.php on scopes and usernames comment out windows features and use OpenLDAP ones, and use authenticate with dn:

  ```php
   'scopes' => [
       // Adldap\Laravel\Scopes\UpnScope::class,
       Adldap\Laravel\Scopes\UidScope::class,
   ],
   'usernames' => [
       'ldap' => [
           'discover' => 'mail',
           'authenticate' => 'dn',
       ],
       'eloquent' => 'email',
       // 'windows' => [
       //     'discover' => 'samaccountname',
       //     'key' => 'AUTH_USER',
       // ],
   ],
  ```
  
  Changes on adldap.php on schema and connection_settings:

  ```php
   'schema' => Adldap\Schemas\OpenLDAP::class,
   'connection_settings' => [
       'account_prefix' => env('ADLDAP_ACCOUNT_PREFIX', ''),
   ],
  ```

**Comment by stevebauman** [comment]
Documentation has been updated and more is on the way along with tutorials.

**Comment by scotrolex** [comment]
thanks
