### ISSUE TITLE
Adldap::auth()->attempts works, but Auth::attempt with same params doesn't

### ISSUE THREAD

**Issue by MartinMulder** [Adldap2/Adldap2-Laravel#418]
- Laravel Version: 5.5.19
- Adldap2-Laravel Version: 3.0.* (and dev-master)
- PHP Version: 7.1.8-1

### Description:
If i try to authenticate with Auth::attempt() it always fails, but authenticating with Adldap::auth()->attempt works.
I tried to authenticate with userprincipalname and samaccountname. Both doesn't work.
Importing account also doesn't work (0 users found).
Querying users does work!

when doing an Auth::attempt from tinker I get the following message:
    ldap_get_entries() expects parameter 2 to be an resource, boolean given in ..../adldap2/src/Connections/Ldap.php on line 112

Here is my adldap.conf
```
<?php
return [
    'connections' => [
        'default' => [
            'auto_connect' => false,
            'connection' => Adldap\Connections\Ldap::class,
            'schema' => Adldap\Schemas\ActiveDirectory::class,
            'connection_settings' => [
                'account_prefix' => env('ADLDAP_ACCOUNT_PREFIX', ''),
                'account_suffix' => env('ADLDAP_ACCOUNT_SUFFIX', ''),
                'domain_controllers' => explode(' ', env('ADLDAP_CONTROLLERS', 'corp-dc1.corp.acme.org corp-dc2.corp.acme.org')),
                'port' => env('ADLDAP_PORT', 389),
                'timeout' => env('ADLDAP_TIMEOUT', 5),
                'base_dn' => env('ADLDAP_BASEDN', 'dc=corp,dc=acme,dc=org'),
                'admin_account_suffix' => env('ADLDAP_ADMIN_ACCOUNT_SUFFIX', ''),
                'admin_username' => env('ADLDAP_ADMIN_USERNAME', 'username'),
                'admin_password' => env('ADLDAP_ADMIN_PASSWORD', 'password'),
                'follow_referrals' => false,
                'use_ssl' => false,
                'use_tls' => false,
            ],
        ],
    ],
];
```
adldap_auth.conf
```
<?php
return [
    'connection' => env('ADLDAP_CONNECTION', 'default'),
    'provider' => Adldap\Laravel\Auth\DatabaseUserProvider::class,
    'resolver' => Adldap\Laravel\Auth\Resolver::class,
    'importer' => Adldap\Laravel\Auth\Importer::class,
    'rules' => [
        Adldap\Laravel\Validation\Rules\DenyTrashed::class,
    ],
    'scopes' => [
        Adldap\Laravel\Scopes\UpnScope::class,
    ],
    'usernames' => [
        'ldap' => 'samaccountname',
        'eloquent' => 'username',
    ],
    'login_fallback' => env('ADLDAP_LOGIN_FALLBACK', false),
    'password_sync' => env('ADLDAP_PASSWORD_SYNC', true),
    'windows_auth_attribute' => ['samaccountname' => 'AUTH_USER'],
    'sync_attributes' => [
        'email' => 'userprincipalname',
        'name' => 'cn',
        'username' => 'samaccountname',
    ],
];
```
relevant env:
```
ADLDAP_CONTROLLERS=<ldapHost>
ADLDAP_PORT=389
ADLDAP_BASEDN=dc=domain,dc=nl
ADLDAP_ADMIN_USERNAME=<userName>
ADLDAP_ADMIN_PASSWORD=<password>
```

I can't find where it is going wrong....

**Comment by stevebauman** [comment]
Hi @MartinMulder,

Can you try setting `auto_connect` to `true` and inserting an `account_suffix` for your domain?

For example:

```php
'account_suffix' => env('ADLDAP_ACCOUNT_SUFFIX', '@corp.domain.com'),
```

After adding this, you may need to modify your admin username in your `env` if it already has this suffix.

Once you've done this, try authenticating again and your issues should be resolved.

**Comment by MartinMulder** [comment]
The autoconnect optioneel die the truck, thanks!Op 10 nov. 2017 16:24 schreef Steve Bauman <notifications@github.com>:Hi @MartinMulder,
Can you try setting auto_connect to true and inserting an account_suffix for your domain?
For example:
'account_suffix' => env('ADLDAP_ACCOUNT_SUFFIX', '@corp.domain.com'),
After adding this, you may need to modify your admin username in your env if it already has this suffix.
Once you've done this, try authenticating again and your issues should be resolved.

**Comment by stevebauman** [comment]
Awesome, glad you've got it working :), no problem!
