### ISSUE TITLE
Binding to User model not working

### ISSUE THREAD

**Issue by mihdannewitz** [Adldap2/Adldap2-Laravel#419]
- Laravel Version: 5.5.19
- Adldap2-Laravel Version: 3.0.5
- PHP Version: 7.1.8

### Description:

SSO works without a problem. But the ldap model on the user model is always `null`.

```php
User {#213 ▼
  #fillable: array:3 [▶]
  #hidden: array:2 [▶]
  #connection: "mysql"
  #table: null
  #primaryKey: "id"
  #keyType: "int"
  +incrementing: true
  #with: []
  #withCount: []
  #perPage: 15
  +exists: true
  +wasRecentlyCreated: false
  #attributes: array:8 [▶]
  #original: array:8 [▶]
  #changes: []
  #casts: []
  #dates: []
  #dateFormat: null
  #appends: []
  #dispatchesEvents: []
  #observables: []
  #relations: []
  #touches: []
  +timestamps: true
  #visible: []
  #guarded: array:1 [▶]
  #rememberTokenName: "remember_token"
  +ldap: null
}
```

### Steps To Reproduce:

I started with a fresh installation of Laravel 5.5.19, completet the "Installation & Basic Setup" guide and setup SSO.

Everything works as expected. Once a user visits the app, a database entry gets created and the user is logged in. But the ldap model on the user model is always `null`.

I do have included the Trait in my `User.php`

```php
<?php

namespace App;

use Adldap\Laravel\Traits\HasLdapUser;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable, HasLdapUser;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

}

```

**Comment by stevebauman** [comment]
Hi @mihdannewitz This is a known issue with the SSO middleware. Binding simply wasn't added into it, which is my mistake.

This has already been fixed on the master branch, and a new release will be out soon.

**Comment by stevebauman** [comment]
This fix was released in `v4.0`. Binding now occurs automatically after the `Authenticated` event takes place, so no matter where you authenticate, it will now bind properly.

https://github.com/Adldap2/Adldap2-Laravel/blob/master/src/Listeners/BindsLdapUserModel.php

**Comment by jhosepharaujo** [comment]
Hi, this fix not work for me. See my composer.json
`{
...
    "name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "type": "project",
    "require": {
        "php": ">=7.0.0",
        "adldap2/adldap2-laravel": "^4.0",
        "fideloper/proxy": "~3.3",
        "laravel/framework": "5.5.*",
        "laravel/tinker": "~1.0"
...
    },`

I'm using this setting but it is not working.

`User {#240 ▼
  #fillable: array:4 [▶]
  #hidden: array:2 [▶]
  #connection: "sqlite"
  #table: null
  #primaryKey: "id"
  #keyType: "int"
  +incrementing: true
  #with: []
  #withCount: []
  #perPage: 15
  +exists: true
  +wasRecentlyCreated: false
  #attributes: array:8 [▶]
  #original: array:8 [▶]
  #changes: []
  #casts: []
  #dates: []
  #dateFormat: null
  #appends: []
  #dispatchesEvents: []
  #observables: []
  #relations: []
  #touches: []
  +timestamps: true
  #visible: []
  #guarded: array:1 [▶]
  #rememberTokenName: "remember_token"
  +ldap: null
}`


What can be happening?

**Comment by stevebauman** [comment]
Hi @jhosepharaujo, are you authenticating through the SSO middleware and do you have the `adldap` driver enabled and configured?

**Comment by jhosepharaujo** [comment]
I had not added Middleware in kernel.php. But even adding did not work.

`   protected $middleware = [
        \Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode::class,
        \Illuminate\Foundation\Http\Middleware\ValidatePostSize::class,
        \App\Http\Middleware\TrimStrings::class,
        \Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull::class,
        \App\Http\Middleware\TrustProxies::class,
        \Adldap\Laravel\Middleware\WindowsAuthenticate::class,
    ];`

I'm trying to follow this tutorial [https://github.com/jotaelesalinas/laravel-simple-ldap-auth](url)

**Comment by jhosepharaujo** [comment]
I would like to apply ACL using LDAP. Retrieve the user and check which group he belongs to view the content. How can I do this?

**Comment by stevebauman** [comment]
You need to set up SSO on your web server, otherwise the middleware will do nothing. I can't assist you with doing so, every web server and application is unique.

For your other issue, you will need to enable the binding LDAP users to your model and then you will could implement a middleware or something to check which group they are apart of and restrict access.

Please read the available documentation for properly binding LDAP users to their model.
