### ISSUE TITLE
Disable New User Creation

### ISSUE THREAD

**Issue by dgeyer263** [Adldap2/Adldap2-Laravel#42]
How can I tell Adldap2 to not create a new user in the users table when successful login, I want it to look at the users in the users table and only allow authentications of where the usernames from the users table match Active Directory, and update the records in-case of a AD communication issue using 'login_fallback' => true

Thanks for help in advance!

**Comment by dgeyer263** [comment]
I got it to work by modifying the src/AdldapAuthUserProvider.php


protected function getModelFromAdldap(User $user, $password)
{
....
// Create the model instance of it isn't found.
        //if (!$model instanceof Model) {
        //    $model = $this->createModel();
        //}
        if(!$model){
            return $model;
        }
....
}

How can I override outside the vendor directory, due to updates overwriting the file!

**Comment by dgeyer263** [comment]
I fixed it by writing a custom function in AuthController.php and then passing it to the postLogin function after my checks, changed my routes file to call the new function postLoginLDAP on POST.

~~~~~~~~~~~~~~~~

/**
     * Handle a login request to the application before passing it to LDAP.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function postLoginLDAP(Request $request)
    {
        if(!User::whereUsername($request->username)->count())
        {
            return redirect()->back()
                        ->withInput($request->only('username', 'remember'))
                        ->withErrors([
                            'username' => 'This account is not allowed to access the system!',
                        ]);
        }
        return $this->postLogin($request);
    }


~~~~~~~~~~~~~~~~

**Comment by stevebauman** [comment]
Glad to hear you've solved your issue! Apologies for the long response on this.
