### ISSUE TITLE
Issue with Passwords

### ISSUE THREAD

**Issue by theodorosf** [Adldap2/Adldap2-Laravel#421]
- Laravel Version: 5.5
- Adldap2-Laravel Version: current
- PHP Version: 7.1

### Description:

I am importing manually users from LDAP without issue, 

# php artisan adldap:import user@email
..........
> Successfully imported / synchronized 1 user(s).

I can see the user inside the database, 

1. Name
2. E-mail
3. Password

The passwords looks fine and hashed, 
However, for some reason we are not able to login with the account's password.

> These credentials do not match our records.

It looks that for some reason the synced passwords are not working as excepted. 

Can you advice us please? 

Thank you very much

**Comment by stevebauman** [comment]
Hi, do you have the Adldap2-Laravel auth driver enabled and password_sync set to true?

When you import users via the import command, it uses a random 16 character string as the password, it does not retrieve the users current AD password because this isn't possible.

**Comment by theodorosf** [comment]
Hi Steve,

Thank you very much, understood. So we cannnot sync through the import command. 

We have managed everything, we retrieve data without issues but unfortunately,  we were not able to fully integrate with the Auth driver :( Can we re-try to configure the driver for single sign on, and send you what we did so maybe you can help and advice us ?

**Comment by stevebauman** [comment]
Hi @theodorosf, yes of course, I'd be glad to help you.

If you're using single sign on, are you use the `WindowsAuthenticateMiddleware`?

https://github.com/Adldap2/Adldap2-Laravel/blob/master/docs/auth/middleware.md

**Comment by tphil** [comment]
Hi Steve,

Thank you very much for your time and your valuable help. Let's ignore the SSO for now.
We will be very happy if we can just sign-in and sync attributes to the database, i am pasting you the code.

1. addap.php

`<?php

return [

    'connections' => [

        'default' => [

            'auto_connect' => true,

            'connection' => Adldap\Connections\Ldap::class,

            'schema' => Adldap\Schemas\ActiveDirectory::class,

            'connection_settings' => [

                'account_prefix' => env('ADLDAP_ACCOUNT_PREFIX', ''),

                'account_suffix' => env('ADLDAP_ACCOUNT_SUFFIX', '@francoudi.com'),

                'domain_controllers' => explode(' ', env('ADLDAP_CONTROLLERS', '10.5.90.4')),

                'port' => env('ADLDAP_PORT', 389),

                'timeout' => env('ADLDAP_TIMEOUT', 15),

                'base_dn' => env('ADLDAP_BASEDN', 'OU=ROOT_OU,DC=francoudi,DC=com'),

                'admin_account_suffix' => env('ADLDAP_ADMIN_ACCOUNT_SUFFIX', ''),

                'admin_username' => env('ADLDAP_ADMIN_USERNAME', 'theodorosf'),

                'admin_password' => env('ADLDAP_ADMIN_PASSWORD', ''),

                'follow_referrals' => false,

                'use_ssl' => false,
                'use_tls' => false,

            ],

        ],


    ],

];
`

2. adldap_auth.php

`<?php

return [


    'connection' => env('ADLDAP_CONNECTION', 'default'),

    'provider' => Adldap\Laravel\Auth\DatabaseUserProvider::class,

    'resolver' => Adldap\Laravel\Auth\Resolver::class,

    'importer' => Adldap\Laravel\Auth\Importer::class,

    'rules' => [

        Adldap\Laravel\Validation\Rules\DenyTrashed::class,

        // Adldap\Laravel\Validation\Rules\OnlyImported::class,
    ],

    'scopes' => [

        Adldap\Laravel\Scopes\UpnScope::class,
    ],

    'usernames' => [

        'ldap' => 'samaccountname',

        'eloquent' => 'username',
    ],

    'login_fallback' => env('ADLDAP_LOGIN_FALLBACK', false),

    'password_sync' => env('ADLDAP_PASSWORD_SYNC', true),

    'windows_auth_attribute' => ['samaccountname' => 'AUTH_USER'],

    'sync_attributes' => [

        'username' => 'samaccountname',
        'name' => 'cn',

    ],

];
`

3. auth.php

`<?php

return [


    'defaults' => [
        'guard' => 'web',
        'passwords' => 'users',
    ],

    'guards' => [
        'web' => [
            'driver' => 'session',
            'provider' => 'users',
        ],

        'api' => [
            'driver' => 'token',
            'provider' => 'users',
        ],
    ],

    'providers' => [
        'users' => [
            'driver' => 'adldap', // Changed from 'eloquent'
            'model' => App\User::class,
            'table' => 'users',
        ],

        // 'users' => [
        //     'driver' => 'database',
        //     'table' => 'users',
        // ],
    ],

    'passwords' => [
        'users' => [
            'provider' => 'users',
            'table' => 'password_resets',
            'expire' => 60,
        ],
    ],

];
`
4. LoginController

`<?php

namespace App\Http\Controllers\Auth;

use App\Http\Controllers\Controller;
use Illuminate\Foundation\Auth\AuthenticatesUsers;

class LoginController extends Controller
{
    use AuthenticatesUsers;

    /**
     * Where to redirect users after login.
     *
     * @var string
     */
    protected $redirectTo = '/home';

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('guest')->except('logout');
    }

    public function username()
    {
        return 'username';
    }
}
`
5. Login.blade.php

`@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Login</div>

                <div class="panel-body">
                    <form class="form-horizontal" method="POST" action="{{ route('login') }}">
                        {{ csrf_field() }}

                        <div class="form-group{{ $errors->has('Username') ? ' has-error' : '' }}">
                            <label for="username" class="col-md-4 control-label">Username</label>

                            <div class="col-md-6">
                                <input id="Username" type="tesxt" class="form-control" name="Username" value="{{ old('Username') }}" required autofocus>

                                @if ($errors->has('Username'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('Username') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('password') ? ' has-error' : '' }}">
                            <label for="password" class="col-md-4 control-label">Password</label>

                            <div class="col-md-6">
                                <input id="password" type="password" class="form-control" name="password" required>

                                @if ($errors->has('password'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('password') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-4">
                                <div class="checkbox">
                                    <label>
                                        <input type="checkbox" name="remember" {{ old('remember') ? 'checked' : '' }}> Remember Me
                                    </label>
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-8 col-md-offset-4">
                                <button type="submit" class="btn btn-primary">
                                    Login
                                </button>

                                <a class="btn btn-link" href="{{ route('password.request') }}">
                                    Forgot Your Password?
                                </a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
`

6. create_users_table.php

` public function up()
    {
        Schema::defaultStringLength(191);
        Schema::create('users', function (Blueprint $table) {
            $table->increments('id');
            $table->string('name');
            $table->string('username')->unique();
            $table->string('password');
            $table->rememberToken();
            $table->timestamps();
        });
    }`

**Comment by stevebauman** [comment]
Thanks for pasting all the code, this helps tremendously. Your configuration looks fine, what happens when you try to log users in?

One thing to note, are you using PostGre or just MySQL / MariaDB?

**Comment by stevebauman** [comment]
Also in your base DN set: `OU=ROOT_OU,DC=francoudi,DC=com`, are the user accounts you're trying to authenticate with contained inside this OU at all?

**Comment by tphil** [comment]
Nothing happens when i try to log users in, no error, no login, just the login page refreshed and keeps the username on field. 

Yes, this users is inside the ROOT_OU. I am able to collect user information with this base DN without any issue, if i remove the ROOT_OU i can collect users but not the same users. (The employs is inside this Organization Unit) the System users are outside this OU and i can collect with just DC=francoudi,DC=com.

I am using MySQL/MariaDB.

**Comment by stevebauman** [comment]
Ok thanks for the quick replies. Just for a quick longshot, can you lowercase the `Username` input form field to just `username`? As well as the errors etc.

**Comment by stevebauman** [comment]
Hmmm... I think I've seen this before... What session driver are you using in your application?

**Comment by tphil** [comment]
It's fresh/clean installation of Laravel 5.5. 

`'driver' => env('SESSION_DRIVER', 'file'),`

Do you want to see the full code of the session.php file?

**Comment by stevebauman** [comment]
Nope that's fine, one moment let me look over everything again...

**Comment by stevebauman** [comment]
When you try to log a user in, do you see a new session file created in your storage directory?

It's located in `/storage/framework/sessions`

**Comment by tphil** [comment]
Yes, there session files inside. Also, I re-tested and a new file generated.

**Comment by stevebauman** [comment]
Okay so new sessions are being created fine. Can you remove the imported users from the database and see if you login if a new user is created successfully in your `users` table?

**Comment by tphil** [comment]
`users` table it's already empty. No new records after I log a user.

**Comment by tphil** [comment]
I re-tested the connection, I didn't import the users. 

```
# php artisan adldap:import
Found 705 user(s).

Would you like to display the user(s) to be imported / synchronized? (yes/no) [No]:
```

**Comment by stevebauman** [comment]
This is very strange... We have two options here, we could do a screen share and I could resolve your issue this way, or you can go into the `vendor/adldap2/adldap2-laravel/src/Auth/Resolver.php` file and call a `dd()` (dump & die) inside the methods inside to see where it's not locating your user.

**Comment by stevebauman** [comment]
If you'd prefer the latter, you can try `dd()`ing in this method in the resolver:

https://github.com/Adldap2/Adldap2-Laravel/blob/v3.0/src/Auth/Resolver.php#L36-L48


```php
if (empty($credentials)) {
    return;
}
    
$user = $this->query()
    ->whereEquals($this->getLdapUsername(), $credentials[$this->getEloquentUsername()])
    ->first();

dd($user);
```

**or**

`dd($user)` in this method in the `DatabaseUserProvider`:

https://github.com/Adldap2/Adldap2-Laravel/blob/v3.0/src/Auth/DatabaseUserProvider.php#L107-L120

**Comment by stevebauman** [comment]
Once you've edited these files, try authenticating again and see if any user models are dumped, and we'll go from there.

**Comment by tphil** [comment]
Very appreciate your efforts for still working with me to found the root cause the issue.
I added the dd($user); in both files but no dump & die occur's.
We can do Team Viewer if you wish

**Comment by stevebauman** [comment]
Ok no problem. Can you send your ID to steven_bauman@outlook.com?

**Comment by stevebauman** [comment]
This was due to the Trust Proxy middleware in the global middleware stack in `app/Http/Kernel.php`.

Upon login, it was denying the request and redirecting back automatically with no session error messages.

Once the middleware was removed, authentication worked without issue.

Thanks again to @tphil for allowing me to connect via TeamViewer to locate this issue :).
