### ISSUE TITLE
How to disable/enable exist account?

### ISSUE THREAD

**Issue by sonminh18** [Adldap2/Adldap2-Laravel#423]
- Laravel Version: 5.5
- Adldap2-Laravel Version: 2.0
- PHP Version: 5.6

### Description:
Hello, I have searched several days about how to disable and enable exist account on ldap server, but I can't find any solution for this issue. Please help!!

**Comment by stevebauman** [comment]
Hi @sonminh18,

Just to clarify, are you looking to disable the LDAP account **through** Adldap2?

**Comment by sonminh18** [comment]
Hi,
Yes,I'm using Adldap2 package and I want to disable/enable LDAP account. But I have found the solution to disable or enable account by set attributes useraccountcontrol.
Default useraccountcontrol attributes for standard user is: 512. So if we plus 2 to this, It's disabled account.
[https://support.microsoft.com/en-us/help/305144/how-to-use-the-useraccountcontrol-flags-to-manipulate-user-account-pro](url) 
Here is my code. It had working for my purpose.
```
$data=$this->adldap->getProvider('default')->search()->users()->find($username);
$data->setAttribute('useraccountcontrol',514);
$data->save();
```
Thank for your answer.

**Comment by stevebauman** [comment]
That's great that you've resolved your issue! Thanks for following up.

This is also supported in the root Adldap2 repository for setting the account control, but I do have to document this better:

https://github.com/Adldap2/Adldap2/blob/master/src/Models/Attributes/AccountControl.php
