### ISSUE TITLE
Import restore (-r, --restore) does not work

### ISSUE THREAD

**Issue by ownmaster** [Adldap2/Adldap2-Laravel#425]
Version 3.0.5.
`php artisan adldap:import --filter "something" -r` doesn't work.
I have checked Commands/Import.php and it seems that `restore(User $user, Model $model)` method is just not being called anywhere.

**Comment by stevebauman** [comment]
Whoops! I fixed this in master, but not on the `v3` branch. Pushing now.

Thanks :)

**Comment by ownmaster** [comment]
I'm not familiar with the release procedure, so I'm curious - when approximately this fix can be published?

**Comment by stevebauman** [comment]
Hi @ownmaster, this has been fixed in `v4.0` and I'm pushing a new release out now with this fix in the `v3.0` branch.

**Comment by stevebauman** [comment]
Hi @ownmaster, apologies for this. I'll push out a new v3 release now. Thanks!

**Comment by ownmaster** [comment]
Thanks, v3.0.9 is OK.
