### ISSUE TITLE
Call to undefined method Adldap\Laravel\Resolvers\UserResolver::getLdapUsername()

### ISSUE THREAD

**Issue by rwattogl** [Adldap2/Adldap2-Laravel#428]
- Adldap2-Laravel Version: Master
- PHP Version: 7.1

### Description:
 [Symfony\Component\Debug\Exception\FatalThrowableError]
  Call to undefined method Adldap\Laravel\Resolvers\UserResolver::getLdapUsername()

\adldap2\adldap2-laravel\src\Commands\Console\Import.php:219
\adldap2\adldap2-laravel\src\Commands\Console\Import.php:222

Both refer to renamed methods in commit c9324974e33e163dc4b7cc1599fdc53841742087

### Steps To Reproduce:

Run user import via `artisan`

**Comment by stevebauman** [comment]
Thanks! This is only for the master branch though, however will still have this fixed shortly.
