### ISSUE TITLE
Feature: Please add new event that fires after the eloquent model has been saved

### ISSUE THREAD

**Issue by m-lotze-7o7** [Adldap2/Adldap2-Laravel#429]
- Laravel Version: 5.5
- Adldap2-Laravel Version: dev-master
- PHP Version: 7.1

### Description:
Right now the Event Synchronized fires when the Eloquent model attributes have been set. But on the first import the eloquent model is not saved yet. So it is not possible to add a listener that e.g. assigns a role to the eloquent user - at least not on the first import. 

Could you please add an event after the eloquent model has been saved? 
Or maybe add the eloquent model to the event AuthenticationSuccessful?

Thank you.

**Comment by spacemudd** [comment]
https://github.com/Adldap2/Adldap2-Laravel/blob/master/src/Events/AuthenticationSuccessful.php

The 'master' branch has the Event(s) you are talking about. The composer package is still on v3.0 branch however.

**Comment by stevebauman** [comment]
Hi @m-lotze-7o7, right now you can actually utilize laravel's `Illuminate\Auth\Events\Authenticated` event that is fired after successful authentication.

Though I do have this implemented in the master branch and will be coming for `v4.0`.
