### ISSUE TITLE
adldap_auth.php not publishing

### ISSUE THREAD

**Issue by brockwddb** [Adldap2/Adldap2-Laravel#43]
It looks like you may have missed the publish command on version 1.4. The auth config file is not publishing for me.

**Comment by stevebauman** [comment]
The new version contained no changes to the publishing command for the `AdldapAuthServiceProvider`. It works as intended.

Ensure your configuration isn't being cached and you've inserted the `AdldapAuthServiceProvider` in your `config/app.php` file.

**Comment by brockwddb** [comment]
Well, I'm a bit of a jerk now aren't I? I did forget to put the provider. Sorry about that!

**Comment by stevebauman** [comment]
No problem at all! Please don't hesitate to create more issues if your encounter any, thanks!
