### ISSUE TITLE
My samaccountname isn't found when I know it exists

### ISSUE THREAD

**Issue by newtekDev** [Adldap2/Adldap2-Laravel#437]
- Laravel Version: 5.5
- Adldap2-Laravel Version: 3.0
- PHP Version: 7.1

### Description:
This is probably due to my minimal understanding of LDAP, but my samaccountname which I know exists is not being found (and is not allowing a successful authentication). To debug I ran: 
```
var_dump(Adldap::search()->where('cn', '=', 'bneff')->get());
```
at the beginning of the login page to see if anything would come up, and I get this response:
```
/home/vagrant/Code/api/vendor/adldap2/adldap2/src/Query/Builder.php:770:
object(Adldap\Query\Builder)[491]
  public 'columns' => 
    array (size=0)
      empty
  public 'filters' => 
    array (size=3)
      'and' => 
        array (size=1)
          0 => 
            array (size=3)
              ...
      'or' => 
        array (size=0)
          empty
      'raw' => 
        array (size=0)
          empty
  public 'limit' => int 0
  public 'paginated' => boolean false
  protected 'sortByField' => string '' (length=0)
  protected 'sortByDirection' => string '' (length=0)
  protected 'sortByFlags' => null
  protected 'dn' => string 'xxxx-xxxx-xxxx' (length=14)
  protected 'recursive' => boolean true
  protected 'read' => boolean false
  protected 'raw' => boolean false
  protected 'nested' => boolean false
  protected 'connection' => 
    object(Adldap\Connections\Ldap)[485]
      protected 'connection' => resource(11, ldap link)
      protected 'bound' => boolean true
      protected 'useSSL' => boolean false
      protected 'useTLS' => boolean false
  protected 'grammar' => 
    object(Adldap\Query\Grammar)[490]
  protected 'schema' => 
    object(Adldap\Schemas\ActiveDirectory)[486]
```

From what I can tell this means no results are coming up (columns => 0). Is there anything else I need to change?

Thanks in advance,
Barnet

**Comment by stevebauman** [comment]
Hi @newtekDev,

You shouldn't be receiving a Query object when calling `get()` on the Adldap query builder, it always returns a collection instance, even if no records are found.

Are you sure you're running the code you've shown above?

Also, you must search for a `samaccountname` equal to `bneff`, not the `cn` (common name) if that is indeed what you are looking for.

Columns should be empty unless you specify it in the query using `Adldap::search()->select(['cn', 'samaccountname'])` etc. If columns are empty, it simply retrieves all fields for each LDAP record from your server.

**Comment by newtekDev** [comment]
Okay so I'm probably approaching this from the wrong angle.

I use my samaccountname to login on other systems. Using Adldap2-Laravel I keep getting an unsuccessful login ('credentials do not match') even though I know they are the right creds. What is the proper way to debug?

**Comment by newtekDev** [comment]
In another App that we use that has homebuilt LDAP auth the authentication work like this:

First the App connects to LDAP, then
```
$userSearchResult = $this->ldapConnectionObj->GetUserData($username);
$userDn = $this->ldapConnectionObj->ParseUserDn($userSearchResult);
```
Then it binds the $userDn with the provided password and on successfully binding, authenticates successfully.

**Comment by stevebauman** [comment]
I would try modifying your configuration values inside your `config/adldap_auth.php` file.

I'll need to know more information though. Are you using the `DatabaseUserProvider` to sync your users to a local database or are you using the `NoDatabaseUserProvider` to just provide LDAP authentication?

**Comment by newtekDev** [comment]
Here is my `adldap_auth.php`:
```
return [
    'connection' => env('ADLDAP_CONNECTION', 'default'),
    'provider' => Adldap\Laravel\Auth\DatabaseUserProvider::class,
    'resolver' => Adldap\Laravel\Auth\Resolver::class,
    'importer' => Adldap\Laravel\Auth\Importer::class,
    'rules' => [
        // Denys deleted users from authenticating.
        Adldap\Laravel\Validation\Rules\DenyTrashed::class,
        // Allows only manually imported users to authenticate.
        // Adldap\Laravel\Validation\Rules\OnlyImported::class,
    ],
    'scopes' => [
        // Only allows users with a user principal name to authenticate
        Adldap\Laravel\Scopes\UpnScope::class,
    ],
    'usernames' => [
        'ldap' => 'samaccountname',
        'eloquent' => 'username',
    ],
    'login_fallback' => env('ADLDAP_LOGIN_FALLBACK', false),
    'password_sync' => env('ADLDAP_PASSWORD_SYNC', true),
    'windows_auth_attribute' => ['samaccountname' => 'AUTH_USER'],
    'sync_attributes' => [
        'email' => 'userprincipalname',
        'name' => 'cn',
    ],
];
```

I am using `DatabaseUserProvider`

**Comment by newtekDev** [comment]
Is there a good resource to look up on configuration, I'm very unfamiliar with how LDAP works and because of that I can't really debug on my own to see what I'm doing wrong.

**Comment by stevebauman** [comment]
> Is there a good resource to look up on configuration, I'm very unfamiliar with how LDAP works and because of that I can't really debug on my own to see what I'm doing wrong.

It's no problem, we'll get you sorted and working here.

There is documentation of each configuration value for LDAP connections here:

https://github.com/Adldap2/Adldap2/blob/master/docs/configuration.md#definitions

Also documentation on the `adldap_auth.php` configuration here:

https://github.com/Adldap2/Adldap2-Laravel/blob/master/docs/auth/installation.md#basic-setup

First, you'll need to modify your `sync_attributes` as these are what are synchronized for each new LDAP user in your database. Since you're using usernames, it should be:

```php
'sync_attributes' => [
    'username' => 'samaccountname',
    'name' => 'cn',
],
```

Also, since you're using a `samaccountname` to authenticate users, you'll need to insert an `account_suffix` that is equal to your domain suffix. For example, `@corp.acme.org` or `@domain.local` etc.

This is being changed in `v4.0` where you'll just be able to use a users distinguished name to authenticate rather than use these, but for now you'll have to provide the suffix.

Try the changes I've mentioned and let me know if it works!

**Comment by newtekDev** [comment]
That worked! Thank you . very much!

**Comment by stevebauman** [comment]
Awesome! Glad you're up and running :)

If you encounter any other issues, please don't hesitate to create one here.
