### ISSUE TITLE
Testing Question

### ISSUE THREAD

**Issue by jasonlbeggs** [Adldap2/Adldap2-Laravel#438]
- Laravel Version: 5.5
- Adldap2-Laravel Version: ^3.0
- PHP Version: 7.1

### Question:
What is the recommended way to generate users in tests with this package when using the NoDatabaseProvider?

**Comment by stevebauman** [comment]
Hi @jasonlbeggs, great question! I haven't documented this at all currently, so after I go through this here I'll create some docs for this scenario. I also need to modify Adldap2 to make this easier.

You'll need to create mock users using the `Adldap\Models\User` model.

This model adheres to the `UserContract` supplied in Laravel's test cases, so you can use the `actingAs()` method in test cases:

```php
/**
 * Set the currently logged in user for the application.
 *
 * @param  \Illuminate\Contracts\Auth\Authenticatable  $user
 * @param  string|null  $driver
 * @return $this
 */
public function actingAs(UserContract $user, $driver = null)
{
    $this->be($user, $driver);

    return $this;
}
```

Here's an example implementation:

```php
public function test_ad_user()
{
    $c = Mockery::mock(ConnectionInterface::class);

    $g = new Grammar();

    $b = new Builder($c, $g);

    $user = new User([
        'objectsid' => [
            hex2bin('010500000000000515000000dcf4dc3b833d2b46828ba62800020000')
        ],
        'cn' => ['Bauman, Steve'],
    ], $b);

    $this->actingAs($user);

    dd(auth()->user()); // Returns instance of \Adldap\Models\User
    dd(auth()->id()); // Returns "S-1-5-21-1004336348-1177238915-682003330-512"
}
```

You can then create a helper method in your testing to simply construct and sign in users for test cases that require authentication.

Remember, you'll need to construct dummy data for the signed in user if you require it for testing.

For example, if you checking groups on the authenticated LDAP user, you will need to provide a `memberof` attribute when creating mock users.

If you need any more information or assistance, comment back and I'll re-open this.

Thanks!

**Comment by jasonlbeggs** [comment]
Thanks for the help! I'll be sure to watch out for the changes on the upgrade.

I ended up just going ahead and making an AdldapUserFactory class instead of a function. This will make it easier for me to add on different states and extend the functionality. It functions pretty well as a drop in replacement for what I was already doing.

```php
<?php

use Adldap\Connections\ConnectionInterface;

class AdldapUserFactory
{
    public static function create($overrides = [])
    {
        $c = Mockery::mock(ConnectionInterface::class);

        $g = new \Adldap\Query\Grammar();

        $b = new \Adldap\Query\Builder($c, $g);

        $user = new \Adldap\Models\User(array_merge([
            'objectsid' => [
                hex2bin('010500000000000515000000dcf4dc3b833d2b46828ba62800020000')
            ],
            'cn' => ['User, Test'],
        ], $overrides), $b);

        return $user;
    }
}
```

The only thing that is kind of weird is all my tests that use this are returning null in the terminal when I run them now. Do you have any ideas what could be causing that by chance?

![image](https://user-images.githubusercontent.com/25065083/33768016-62ec3276-dbf2-11e7-9def-fb608d54435a.png)
