### ISSUE TITLE
ldap_bind OK; Adldap::auth() OK; Auth::attempt NOT.

### ISSUE THREAD

**Issue by MarceloNG** [Adldap2/Adldap2-Laravel#439]
- Laravel Version: 5.5.23
- Adldap2-Laravel Version: 3.0.6
- PHP Version: 7.1.10

### Description:
It always fails when I try to authenticate with Auth::attempt(). It succeeds when authenticating with ldap_bind or Adldap::auth().
I did my best, but I can`t figure it out!

Here is my controller:
```
use Adldap\Laravel\Facades\Adldap;
    use Illuminate\Support\Facades\Auth;

    public function index()
    {   
        $ldaphost = "company.com";
        $ldapport = 389;
        $userkey = "abcd";
        $userpass = "password";
        $exclusivename = "CN=".$userkey.",OU=ASDF,OU=ASV-RF,OU=Users,DC=company,DC=com";
        
        $ds = ldap_connect($ldaphost) or die("Could not connect to $ldaphost");
        
        //$bind = ldap_bind($ds,$exclusivename, $userpass); // return true
       
        //$bind=Adldap::auth()->attempt($userkey, $userpass); // return true
    
        //$bind=Auth::attempt(['username' => $userkey, 'password' => $userpass]); //return false
        //$bind=Auth::attempt(['username' => $exclusivename, 'password' => $userpass]); //return false
        
        dd($bind);
    }
```

.ENV
```
ADLDAP_ACCOUNT_SUFFIX=OU=ASDF,OU=ASV-RF,OU=Users,DC=company,DC=com
ADLDAP_CONTROLLERS=company.com
ADLDAP_BASEDN=
ADLDAP_ADMIN_USERNAME=
ADLDAP_ADMIN_PASSWORD=
```

Here is my adldap_auth.php.
```
<?php`

return [
     'connection' => env('ADLDAP_CONNECTION', 'default'),
   'provider' => Adldap\Laravel\Auth\DatabaseUserProvider::class,
    'resolver' => Adldap\Laravel\Auth\Resolver::class,
    'importer' => Adldap\Laravel\Auth\Importer::class,
    'rules' => [
        Adldap\Laravel\Validation\Rules\DenyTrashed::class,
    ],
    'scopes' => [
        //Adldap\Laravel\Scopes\UpnScope::class,
    ],
    'usernames' => [
        'ldap' => 'userprincipalname',
        'eloquent' => 'username',
    ],
    'login_fallback' => env('ADLDAP_LOGIN_FALLBACK', false),
    'password_sync' => env('ADLDAP_PASSWORD_SYNC', true),
    'windows_auth_attribute' => ['samaccountname' => 'AUTH_USER'],
    'sync_attributes' => [
        //'email' => 'userprincipalname',
        //'name' => 'cn',
        //'username' => 'samaccountname',
    ],
];
```

adldap.php
```
<?php

return [
    'connections' => [
        'default' => [
            'auto_connect' => true,
            'connection' => Adldap\Connections\Ldap::class,
            'schema' => Adldap\Schemas\ActiveDirectory::class,
            'connection_settings' => [
                'account_prefix' => env('ADLDAP_ACCOUNT_PREFIX', ''),
                'account_suffix' => env('ADLDAP_ACCOUNT_SUFFIX', ''),
                'domain_controllers' => explode(' ', env('ADLDAP_CONTROLLERS', '')),
                'port' => env('ADLDAP_PORT', 389),
                'timeout' => env('ADLDAP_TIMEOUT', 5),
                'base_dn' => env('ADLDAP_BASEDN', 'petrobras.biz'),
                'admin_account_suffix' => env('ADLDAP_ADMIN_ACCOUNT_SUFFIX', ''),
                'admin_username' => env('ADLDAP_ADMIN_USERNAME', 'username'),
                'admin_password' => env('ADLDAP_ADMIN_PASSWORD', 'password'),
                'follow_referrals' => false,
                'use_ssl' => false,
                'use_tls' => false,
            ],
        ],
    ],
];

```

**Comment by stevebauman** [comment]
Hi @MarceloNG, are you using ActiveDirectory or OpenLDAP?

**Comment by MarceloNG** [comment]
Almost certain that it is ActiveDirectory.

**Comment by bencornwell** [comment]
I've hit a very similar issue while authenticating against an ActiveDirectory instance.

Not sure if it's relevant but I've noticed that Adldap\Auth\Guard::attempt() isn't called via Auth::attempt() . I am confident that I've followed the ServiceProvider setup correctly.

**Comment by bencornwell** [comment]
To narrow this down further:
`$provider = \Adldap::getProvider('default' );
dd($provider->search()->users()->get());  //empty Collection
dd($provider->search()->all());       	  //full Collection of AD records`

**Comment by bencornwell** [comment]
I have solved this in the situation I have been working on: The AD instance does not use the 'objectcategory' classification , presumably for compatibility purposes. My integration now works like a charm if I change ./config/adldap.php such that: 

`'schema' => Adldap\Schemas\OpenLDAP::class`

Might be worth a try @MarceloNG :-)

**Comment by stevebauman** [comment]
Hi @MarceloNG,

There's some issues with your configuration, first your `base_dn` is incorrect. You will need to locate your base distinguished name and insert the correct one, this is likely why you're not authenticating properly as it needs to discover the correct user account on your LDAP server first, prior to authentication.

When your base DN is incorrect, you will receive no results from your LDAP server.

Secondly, you've commented out the `sync_attributes` array values, which is responsible for properly syncing user data (besides the users password) into your local database.

Also I'm not sure since this wasn't specified and might have been omitted for security reasons, but your `ADLDAP_BASEDN` in your `.env` file is empty, so you will also not receive any records from your LDAP connection, or be able to authenticate users.

The `ADLDAP_CONTROLLERS` string must also be a comma separated list of either IP addresses or host names of your LDAP servers.

Make the above corrections and just comment back if you still encounter issues and I will re-open this issue, thanks!

**Comment by MarceloNG** [comment]
Hi, @bencornwell @stevebauman 
I finally figure out how to configure it! It is working perfectly!!
Sorry to spend your time.
Thanks!!

**Comment by stevebauman** [comment]
Awesome, glad you're up and running @MarceloNG! No problem at all :)

**Comment by muzammilaskari** [comment]
@MarceloNG I am facing the same issue, could you please assist me how you figured it out?
Thanks
