### ISSUE TITLE
Username is not valid format

### ISSUE THREAD

**Issue by ditoskas** [Adldap2/Adldap2-Laravel#440]
- Laravel Version: 5.5.24
- Adldap2-Laravel Version: v3.0.5
- PHP Version: 7.1
- LDAP Type: Active Directory 

### Description:
Hello, 
I use the below code to check if a user is valid
````
$credentials = $request->only($this->username(), 'password'); 
$username = $credentials[$this->username()];
$password = $credentials['password'];
$user_format = env('ADLDAP_USER_FORMAT', 'cn=%s,'.env('ADLDAP_BASEDN', ''));
$userdn = sprintf($user_format, $username);
if(Adldap::auth()->attempt($userdn, $password, $bindAsUser = true))
````

By using username and password it is working for most of the users except the users that they have the symbol '-' on the username.
E.g. 
t_dimitris is working
t-dimitris is not working 
Both accounts are valid and the passwords have been confirmed by login on the windows.
The error that i received is that the "Username is not valid format"

**Comment by stevebauman** [comment]
Strange, I can't seem to replicate this issue... Can you post a stack trace with sensitive details omitted?

**Comment by ditoskas** [comment]
Ignore this issue, my mistake I had extra validation with [w] regex and failed there sorry and thank you!

**Comment by stevebauman** [comment]
No problem, glad you got it working!
