### ISSUE TITLE
No Interaction Flag - Import Command

### ISSUE THREAD

**Issue by stevebauman** [Adldap2/Adldap2-Laravel#441]
Overwrote this change, this time I won't screw up, promise :wink:

**Comment by benyanke** [comment]
Thanks a ton! I was wondering why my deploys broke when I upgraded my packages!

**Comment by stevebauman** [comment]
No problem! Released [v3.0.8](https://github.com/Adldap2/Adldap2-Laravel/releases/tag/v3.0.8)

**Comment by syphernl** [comment]
@stevebauman Seems like you [overwrote this change](https://github.com/Adldap2/Adldap2-Laravel/commit/c76bd4867ee0736c0cbd9ed8187aeb08821d9ad4#diff-aabffc53a4b698cf36c8a87be7a6daa4) again? :cry:

**Comment by syphernl** [comment]
Yes since I switched back to your repo instead of my fork my hourly imports stopped working.

**Comment by stevebauman** [comment]
Can you post your usage of the command that is scheduled? Are you calling the command from the laravel scheduler? In this case you need to pass in `true` into the `--no-interaction` param:

```php
$this->artisan('adldap:import', ['--no-interaction' => true]);
```

**Comment by stevebauman** [comment]
Just tried fresh `v3.0.8` instance, works fine the `--no-interaction` flag using command line?

**Comment by syphernl** [comment]
It's being called trough the Laravel scheduler via a intermediary console command that deals with some other logic. Both the custom importer and the actual call to the one of Adldap is being done using the `no-interaction` flag:

The call to `adldap:import`:
```php
        $this->call(
            'adldap:import',
            [
                '--filter' => sprintf('(memberof:1.2.840.113556.1.4.1941:=%s)', $dn),
                '--delete' => true,
                '--restore' => true,
                '--no-interaction' => true,
            ]
        );
```

It only worked with my custom fork where I explicitly check for the `no-interaction` flag.

**Comment by stevebauman** [comment]
This sounds like a Laravel or Symfony issue. Which version of Laravel are you using?

**Comment by stevebauman** [comment]
Can you also try calling the command directly with the `--no-interaction` flag and see if it works on your installation? This will help us narrow it down a bit.

**Comment by stevebauman** [comment]
I just haven't received any other reports of this not working for othe

**Comment by 36864** [comment]
I tried to replicate this using tinker.
The first call always fails but subsequent calls on the same tinker session work normally. Here's the output:
```
Psy Shell v0.8.16 (PHP 7.1.10 — cli) by Justin Hileman
>>> Artisan::call('adldap:import', ['--no-interaction']);
PHP Warning:  ldap_start_tls(): Unable to start TLS: Protocol error in D:\projects\test\vendor\adldap2\adldap2\src\Connections\Ldap.php on line 202
=> 0
>>> Artisan::call('adldap:import', ['--no-interaction']);
=> 0
```

**Comment by stevebauman** [comment]
> As a side note, there appears to be no difference between using ['--no-interaction' => true] and ['--no-interaction']

There is when using multiple flags. I experienced this running tests locally calling commands from the artisan method. Having multiple flags without a value generates an exception:

https://github.com/Adldap2/Adldap2-Laravel/blob/aa124052bb5d3bbf48c1f685976f071a9651f16c/tests/Console/ImportTest.php#L150

The issue with the artisan call using tinker is strange, I'll see if I can replicate.

I definitely don't have that issue when using non SSL / TLS connections.

**Comment by 36864** [comment]
I've been trying to debug further, but I'm not entirely sure where to look.

I added a dump() statement to the startTLS() function before ldap_start_tls() and it only got hit once, which seems to suggest that after trying to establish a TLS connection once and failing, it stops trying to use TLS.

I'm unable to verify this, but unless the connection is being established elsewhere, that seems to be the case as data does get imported into my database every time after the first one.

**Comment by syphernl** [comment]
@stevebauman Odd. The `--no-interaction` directly works fine on `adldap:import` however if I do it via the `call()` in my own command it doesn't. Even though the argument is being passed along.

```
Array
(
    [--no-interaction] => 1
    [--filter] => (memberof:1.2.840.113556.1.4.1941:=CN=XXXXXX)
    [--delete] => 1
    [--restore] => 1
    [command] => adldap:import
)
```

The only way to get it to work for me is to explicitly check for the `no-interaction` flag from inside the `adldap:import` command. ISTM that the `$default` doesn't work if it is being called from inside another command.

**Comment by stevebauman** [comment]
@syphernl What version of Laravel are you using? 

I'm able to call the command from the Laravel scheduler just fine without interaction:

```php
// Importing one user
$schedule->command('adldap:import sbauman', ['--no-interaction'])
            ->everyMinute();

// Importing all users
$schedule->command('adldap:import', ['--no-interaction'])
            ->everyMinute();

// Importing users with a filter
$dn = 'CN=Accounting,OU=SecurityGroups,DC=Acme,DC=Org';

$filter = sprintf('(memberof:1.2.840.113556.1.4.1941:=%s)', $dn);

$schedule->command('adldap:import', ['--no-interaction', '--filter' => $filter])
    ->everyMinute();
```

**Comment by 36864** [comment]
Calling through the scheduler works fine. Calling through the `Artisan` façade also works fine (suspect the issue I was having is a separate matter entirely, more on that when I figure it out). Calling through another command's `call` method does not work.
Minimal test case:

```
//routes/console.php
Artisan::command('import-proxy', function () {
	$this->call('adldap:import', ['--no-interaction' => true]);
})->describe('indirect call to adldap:import');
```

```
>php artisan import-proxy
  Found 81 user(s).

 Would you like to display the user(s) to be imported / synchronized? (yes/no) [no]:
 >
```

I haven't been able to figure out where you're defining the --no-interaction flag behavior. If you can point me in the right direction I may be able to debug further.

**Comment by stevebauman** [comment]
Hi @36864, the `--no-interaction` behavior is built into Symfony commands. When the console command is ran **is not interactive**, Symfony will return the default value:

https://github.com/symfony/console/blob/bf56f79b8604e4dd32c236048606c507e9dbbcd3/Helper/QuestionHelper.php#L35-L71

**Comment by 36864** [comment]
The problem seems to lie in the `Illuminate\Console\Command::call` method. It runs a new command using a `new ArrayInput` object which is interactive by default and seems to ignore the --no-interaction flag.

I'll do some more legwork and if I can't fix it I'll raise an issue over at the laravel repo.

@syphernl as a workaround, you could use `Artisan::call` instead of `$this->call` in your command.

**Comment by syphernl** [comment]
Thanks @36864!

**Comment by stevebauman** [comment]
Thanks again @36864! Very much appreciated :)
