### ISSUE TITLE
Please require adldap2/adldap2 8.0.* instead of 7.0.*

### ISSUE THREAD

**Issue by mattyh88** [Adldap2/Adldap2-Laravel#442]
- Laravel Version: 5.5.25
- Adldap2-Laravel Version: 3.0.8
- PHP Version: 7.1.9
- LDAP Type: Active Directory

### Description:
Can you require adldap2/adldap2 8.0.* instead of 7.0.* please? 
Requiring 7.0.* installs v7.0.15 but the bind() function seems to have strange behaviour in the Adldap\Auth\Guard class. 

`$prefix = $prefix ?: $this->configuration->get('account_prefix');
$suffix = $suffix ?: $this->configuration->get('account_suffix');`

Should be (as done in versions 8.0.*):

`$prefix = is_null($prefix) ? $this->configuration->get('account_prefix') : $prefix;
$suffix = is_null($suffix) ? $this->configuration->get('account_suffix') : $suffix;`

**Comment by stevebauman** [comment]
Hi @mattyh88, unfortunately I can't just switch versions like this, as it would go against semantic versioning. There are many changes between `v7.0` and `v8.0`, and it could cause many backwards compatibility issues for users.

If you'd like to speed up the release of Adldap2-Laravel `v4.0`, then I would love some PR's for documentation and other additions :smile:

**Comment by stevebauman** [comment]
Oh no that's okay :smile:, I'm planning to release `v4.0` ASAP, but unfortunately documentation has been holding me back ☹️
