### ISSUE TITLE
Other (e.g., implementation specific) error

### ISSUE THREAD

**Issue by nicodi92** [Adldap2/Adldap2-Laravel#443]
- Laravel Version: 5.4
- Adldap2-Laravel Version: 3.0
- PHP Version: 7.1
- LDAP Type: 

### Description:
I've install the package, follow the doc to initialize my adldap.php file and when i try this:
 $users = Adldap::getProvider('other-connection')->search()->users()->get();
        dd($user);
in my frontend i've this error: Other (e.g., implementation specific) error

**Comment by stevebauman** [comment]
Sorry, need much more information than this.

I'll need your LDAP type, as well as your `adldap.php` and `adldap_auth.php` files posted (with sensitive details omitted) as well as the actual exception you receive.
