### ISSUE TITLE
__call method is missing from DatabaseUserProvider.php

### ISSUE THREAD

**Issue by c0py** [Adldap2/Adldap2-Laravel#444]
- Laravel Version: 5.5.25
- Adldap2-Laravel Version: 3.0.8
- PHP Version: 7.1.7
- LDAP Type: Active Directory

### Description:

__call method is missing from DatabaseUserProvider.php (required for jwt-auth 1.0+). Browsing source code here on Github I can see the method but when downloading release 3.0.8 the method is not available in the archive file "DatabaseUserProvider.php", as a workaround I copy the code directly from Github and paste into the file found in vendor folder.

### Steps To Reproduce:

Download release 3.0.8 zip file open src/Auth/DatabaseUserProvider.php then search for "public function __call", it will be missing.

**Comment by stevebauman** [comment]
This is a separate auth driver.

Are you using both of these somehow together? I don't understand.

**Comment by c0py** [comment]
No problem, was just trying to help...

The function here: https://github.com/Adldap2/Adldap2-Laravel/blob/9c8438c031737a1ad3e7a0d3abce8d9e70f84b6e/src/Auth/DatabaseUserProvider.php#L194 is missing from all releases, when will it be available?
