### ISSUE TITLE
Help Needed to Configure these settings in config/adldap.php and config/adldap_auth.php

### ISSUE THREAD

**Issue by riyazpt** [Adldap2/Adldap2-Laravel#445]
Hi Steve,
very urgent  
I tried  to connect LDAP native php  with following parameters 
    $dsn              ="india.local";
    $username    ="india\\abcd.efg";
    $password       ="xxxxx"
     $ds               = ldap_connect($dsn,389);
     $connection = ldap_bind($ds,username,$password);
    dd($connection );
which returns TRUE;
in laravel 5.4 login controller 
But I couldn't configure these settings in config/adldap.php and config/adldap_auth.php

Please help  to configure settings .

**Comment by stevebauman** [comment]
Hi @riyazpt, each configuration option is extensively documented inside the published files.

You can also refer to this document for further information: 

https://github.com/Adldap2/Adldap2/blob/master/docs/configuration.md

Thanks!
