### ISSUE TITLE
Can not import users neither perform successful login

### ISSUE THREAD

**Issue by nikolovinn** [Adldap2/Adldap2-Laravel#447]
- Laravel Version: 5.2.45
- Adldap2-Laravel Version: 3.0
- PHP Version: 5.6.32
- LDAP Type: OpenLDAP

### Description:

I am new to LDAP and I am trying to make import from OpenLDAP server to a MySql database through Laravel Application. Also, I am trying to authenticate the users through the LDAP server. I have been fighting for 1-2 weeks and I have a small success. 

1. I have connection to the OpenLDAP server
2. When I try to get the users  $users = Adldap::search()->users()->get(); I get some result but it is not collection of Users objects but a collection with one OrganizationalUnit object.

Unfortunately, I can not import any users. When I run `php artisan adldap:import` I get 'Found (0) users'. However, in the OrganizatioalUnit object, I see the four users listed: 

`Collection {#676 ▼
  #items: array:1 [▼
    0 => OrganizationalUnit {#665 ▼
         #original: array:7 [▼
             "uniquemember" => array:4 [▼
                   0 => "uid=dewe1136,cn=users,cn=websphereportal,cn=stoapplications"
                   1 => "uid=dewe1523,cn=users,cn=websphereportal,cn=stoapplications"
                   2 => "uid=dewe1590,cn=users,cn=websphereportal,cn=stoapplications"
                   3 => "uid=dexc0384,cn=users,cn=WebSpherePortal,CN=STOAPPLICATIONS"
`

In addittion when I try to login the attempt method always returns false:

```
        $username = Input::get('username');
	$password = Input::get('password');

        if (Adldap::auth()->attempt($username,$password)) {
            return Redirect::intended('index');
        }
        else {
            return Redirect::to('login')->withInput();
        }
```

Here you can find my config files:

adldap.php:
```
return [
    'connections' => [
        'default' => [
            'auto_connect' => true,
            'connection' => Adldap\Connections\Ldap::class,
            'schema' =>  Adldap\Schemas\OpenLDAP::class, // Adldap\Schemas\OpenLDAP::class
            'connection_settings' => [
                'account_prefix' => env('ADLDAP_ACCOUNT_PREFIX', ''),
                'account_suffix' => env('ADLDAP_ACCOUNT_SUFFIX', ''),
                'domain_controllers' => explode(' ', env('ADLDAP_CONTROLLERS', 'corp-dc1.corp.acme.org corp-dc2.corp.acme.org')),
                'port' => env('ADLDAP_PORT', 636),
                'timeout' => env('ADLDAP_TIMEOUT', 5),
                'base_dn' => env('ADLDAP_BASEDN'),
                'admin_account_suffix' => env('ADLDAP_ADMIN_ACCOUNT_SUFFIX', ''),
                'admin_username' => env('ADLDAP_ADMIN_USERNAME', 'username'),
                'admin_password' => env('ADLDAP_ADMIN_PASSWORD', 'password'),
                'follow_referrals' => false,
                'use_ssl' => true,
                'use_tls' => false,
            ],
        ],
    ],
];
```
adldap_auth.php:
```
return [
    'connection' => env('ADLDAP_CONNECTION', 'default'),
    'provider' => Adldap\Laravel\Auth\DatabaseUserProvider::class,
    'resolver' => Adldap\Laravel\Auth\Resolver::class,
    'importer' => Adldap\Laravel\Auth\Importer::class,
    'rules' => [
        Adldap\Laravel\Validation\Rules\DenyTrashed::class,
    ],
    'scopes' => [
    ],
    'usernames' => [
        'ldap' => 'uid',
        'eloquent' => 'username',
    ],
    'login_fallback' => env('ADLDAP_LOGIN_FALLBACK', false),
    'password_sync' => env('ADLDAP_PASSWORD_SYNC', true),
    'windows_auth_attribute' => ['samaccountname' => 'AUTH_USER'],
    'sync_attributes' => [

        'email' => 'mail',
        'name' => 'cn',
    ],
];
```

Here you can see some screenshot from  LDAP Apache Directory Studio:
![mail attachment](https://user-images.githubusercontent.com/10062425/34202145-9204791a-e57f-11e7-8f63-018b7999ee80.gif)
![mail attachment-1](https://user-images.githubusercontent.com/10062425/34202146-92203d44-e57f-11e7-9474-8356ebb9e85f.gif)
![mail attachment-2](https://user-images.githubusercontent.com/10062425/34202147-924146ce-e57f-11e7-8c09-0e74383df4b2.gif)
![mail attachment-3](https://user-images.githubusercontent.com/10062425/34202148-925d4522-e57f-11e7-8742-5ebe8692580f.gif)

Could you please give me a hint what I can do wrong? May be its a confign issue..?

**Comment by stevebauman** [comment]
Hi @nikolovinn,

This is likely because your `base_dn`. Your LDAP server will return no results when the base distinguished name to search upon is incorrect.

Can you please check your `base_dn` (looks like you've set it in your `.env` file)? 

Looking at the attributes photo you've attached, it's likely: `cn=websphereportal,cn=stoapplications`.

If you still encounter this problem, just comment back and I'll re-open this issue. Thanks! :)

**Comment by nikolovinn** [comment]
Hi @stevebauman 

Thanks for the fast reply. I tried changing the `base_dn` to what you suggested -
 `cn=websphereportal,cn=stoapplications`. However after this call `$users = Adldap::search()->users()->get();` I just received collection with a lot of OrganizationalUnits and not Users. See the screenshot:
![capture](https://user-images.githubusercontent.com/10062425/34246456-5a5c0150-e637-11e7-848d-210e77a263d7.PNG)

In addition when I run `php artisan adldap:import` I still got 0 users to import

This is my .env file:

```
ADLDAP_CONTROLLERS=ldap.stoinside-qa.com
ADLDAP_ADMIN_USERNAME=***********
ADLDAP_ADMIN_PASSWORD=************
ADLDAP_BASEDN=cn=app.extendedpim,cn=groups,cn=WebSpherePortal,CN=STOAPPLICATIONS
ADLDAP_ADMIN_ACCOUNT_SUFFIX=,cn=Bindusers,cn=Applications,CN=STOLDAPADMIN
ADLDAP_ACCOUNT_PREFIX=uid=
ADLDAP_ACCOUNT_SUFFIX=,cn=users,cn=WebSpherePortal,CN=STOAPPLICATIONS
```

Do you have any ideas? Thank you!

**Comment by nikolovinn** [comment]
Hi again @stevebauman ,

Plese also check my OpenLDAP.php schema. I added the following method: 

```
public function objectCategoryPerson()
    {
        return 'groupofuniquenames';
    }
```

Without this method I do not get the OrganizationalUnit collection when calling `$users = Adldap::search()->users()->get();`. May be its wrong...

```
<?php

namespace Adldap\Schemas;


class OpenLDAP extends ActiveDirectory
{
    /**
     * {@inheritdoc}
     */
    public function objectCategory()
    {
        return 'objectclass';
    }

    /**
     * {@inheritdoc}
     */
    public function objectClassPerson()
    {
        return 'inetorgperson';
    }

    /**
     * {@inheritdoc}
     */
    public function objectClassOu()
    { 
        return 'groupofuniquenames';
    }

    /**
     * {@inheritdoc}
     */
    public function objectClassGroup()
    {
        return 'groupofnames';
    }

    /**
     * {@inheritdoc}
     */
    public function objectGuid()
    {
        return 'entryuuid';
    }

    /**
     * {@inheritdoc}
     */
    public function distinguishedName()
    {
        return 'cn';
    }

    /**
     * {@inheritdoc}
     */
    public function distinguishedNameSubKey()
    {
        //
    }

    // ADDED BY ME
    public function objectCategoryPerson()
    {
        return 'groupofuniquenames';
    }
}
```

**Comment by nikolovinn** [comment]
Hi @stevebauman ,

Could you please help me with the issue. I tried all different configuration and I can not set it up to work... What I understood that LDAP server that I use is IBM Security Directory Server in Version 6.4.0 (Fix Pack 11). Would that change the configuration? OR is it even possible to use your extension for this server?
