### ISSUE TITLE
Sync password is not working when users model is not use default connection

### ISSUE THREAD

**Issue by freefcw** [Adldap2/Adldap2-Laravel#450]
- Laravel Version: 5.5
- Adldap2-Laravel Version: 060524fd9728953d5388dd1bc25e8a6097bfb48f
- PHP Version: 7.0
- LDAP Type: Active Directory

### Description:

passwords.sync is not working,
cause me set enable passwords.sync in adldap.

why:

SyncPassword will detect should sync password by hasPasswordColumn,

In hasPasswordColumn, Schema::hasColumn whill use default database connection to fetch table schema, when user set another default connection of database, this will fetch nothing, cause sync password failed.

### Steps To Reproduce:

1. make too database name db1, db2
2. set users table in db1,
3. set default database connection db2

try login a new accoutn ,will found password column in table is emtpy.

fix:

1. just depend on config
2. get db connection of user model, so will use right database

**Comment by stevebauman** [comment]
Hi @freefcw, thanks!

This will be fixed shortly.

**Comment by freefcw** [comment]
Thanks for you job!
