### ISSUE TITLE
Sync user's groups and OU's to DB on first pass, no user->id

### ISSUE THREAD

**Issue by TipTopNick** [Adldap2/Adldap2-Laravel#456]
- Laravel Version: 5.5.28
- Adldap2-Laravel Version: 8.0.10
- PHP Version: 7.0.22
- LDAP Type: Active Directory

I've been using Adldap2 for the past few months (even updated to the newest version) and I love it.
My issue is I can't sync something like groups to my database on the first pass (@ first login or first adldap:import) as it requires a user_id and there in not one yet (at least in my LdapAttributHandler).

Here's my LdapAttributeHandler code:
```
public function handle(LdapUser $ldapUser, EloquentUser $eloquentUser)
	{
            $eloquentUser->someAttr = $ldapUser->getSomeAttr(); // No problem syncing single attributes I need to users table
//          $eloquentUser->save(); // To get id doesn't work/save because password isn't synced (is null) and can't let null password's. I do have ADLDAP_PASSWORD_SYNC = true
//          $id = ($eloquentUser->id) ? $eloquentUser->id : DB::table('users')->max('id') + 1; // Hack to get next number in users table to use as ID but if sync fails = BAD DATA!

            $this->syncUserGroups($ldapUser, $eloquentUser); // Function works great if user is already in DB otherwise the groups can't sync because there is no $eloquentUser->id to associate group id with
	}
```
So as you can see I need the user's id so I can attach them to groups/ou's/etc... in the database.  I was going down the events/listeners path and going to grab the users->id from the DB after Authenticated or maybe Synchronized? but wanted to see if there is an easier way to grab the new users id around this point.

Thanks!

**Comment by stevebauman** [comment]
Hi @TipTopNick, glad you like using Adldap2! :)

You will need to utilize an event listener for this, as attribute handlers are only for setting attributes onto the users model during synchronization.

The event you'll want to use is `Adldap\Laravel\Events\AuthenticationSuccessful`.

It's fired directly after the users password is synced and the users model is saved:

https://github.com/Adldap2/Adldap2-Laravel/blob/master/src/Auth/DatabaseUserProvider.php#L141

However, this event doesn't actually include the users model. I'm going to push an update right now to include this into the event so you're able to utilize this, and you will then be able to use the users model in your listener to sync your user groups.

Thanks for bringing this up!

**Comment by TipTopNick** [comment]
That's awesome, I was already heading in that direction and have that one set up in my EventServiceProvider.  I also have App/Listeners/LogAuthSuccessful.php and can get the event.

```
AuthenticationSuccessful {#### ▼
  +user: User {#### ▼
    +exists: true
    #dn: "CN=TipTopNick,OU=AdLdap2,OU=Laravel,DC=mypc,DC=local"
    #query: Builder {#### ▶}
    #schema: ActiveDirectory {####}
    #modifications: []
    +dateFormat: "Y-m-d H:i:s"
    #timestampFormat: "YmdHis.0Z"
    #attributes: array:105 [▶]
    #original: array:105 [▶]
  }
}
```
Currently I'm attempting to drill down in that $event->User->attributes array to grab the samaccountname and find the matching username in my users table to grab the id.  Are you saying, when you push that update I should be able to pull the user->id directly from the user model that will be attached to this event (awesome!)?  Or will I still need to query the user from the DB?
Once I get that user->id I'll sync the groups/ou's/etc.. at that point.

I appreciate all the work that you've put into Adldap2.

**Comment by stevebauman** [comment]
> Are you saying, when you push that update I should be able to pull the user->id directly from the user model that will be attached to this event (awesome!)?

Yup that's exactly what I'm saying :)

I just pushed an update to include the users model with the `AuthenticationSuccessful` event, so you can utilize the users saved model and perform any operations needed on it.

The event now has a `$model` property to access the users eloquent model, so now you can sync user groups from your LDAP user that is logging in.

Here's an example listener (probably not relevant to your application, but just for explanation):

```php
namespace App\Listeners;

use App\Group;
use Adldap\Laravel\Events\AuthenticationSuccessful;

class SyncUserGroups
{
    public function handle(AuthenticationSuccessful $event)
    {
        // Instance of App\User;
        $user = $event->model;
        
        // Instance of Adldap\Models\User;
        $ldap = $event->user;

        $groups = $ldap->getGroupNames($recursive = true);

        foreach ($groups as $group) {
            $group = Group::firstOrCreate(['name' => $group]);

            $group->users()->save($user);
        }
    }
}
```

v4.0.4 will be released momentarily and you will then be able to utilize this new property.

Thanks for the suggestion!

**Comment by TipTopNick** [comment]
Steve, this works fantastic for syncing attributes when users are logging/logged in!  However it does not sync attributes when running adldap:import.

Is there an event where I get the user->id while the users are being imported -running adldap:import- so I can use it to sync all attributes that need the user->id? 

I attempted using "Importing" and "Synchronizing" events however the user doesn't seem to be created yet at those points (unless there is someway to return the users model in one of those like you did in AuthenticationSuccessful).

Again, thanks for this awesome package!
