### ISSUE TITLE
These credentials do not match our records.

### ISSUE THREAD

**Issue by SuperDicq** [Adldap2/Adldap2-Laravel#46]
I'm trying to get Adldap Auth to work and I get the follow message on my login screen when I try to login with valid creditentials: 
```
These credentials do not match our records.
```

I do not get any connection errors from Adldap so I think my config is correctly set up.

I also tried doing a `$ad->search()->all();` and the result is an empty ArrayCollection.

I'm not quite sure where this issue lies and how to debug this further.

**Comment by stevebauman** [comment]
Hi @SuperDicq,

Are you using the default `app/Http/Auth/AuthController` that comes pre-installed with Laravel?

Also, do you have `APP_DEBUG=true` in your `.env`? If you don't you won't see any connection errors from Adldap.

**Comment by SuperDicq** [comment]
Yes, I'm using the default `AuthController` that I've modified for usernames.

```
class AuthController extends Controller
{
    /*
    |--------------------------------------------------------------------------
    | Registration & Login Controller
    |--------------------------------------------------------------------------
    |
    | This controller handles the registration of new users, as well as the
    | authentication of existing users. By default, this controller uses
    | a simple trait to add these behaviors. Why don't you explore it?
    |
    */

    use AuthenticatesAndRegistersUsers, ThrottlesLogins;
    
    protected $username = 'username';

    /**
     * Create a new authentication controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('guest', ['except' => 'getLogout']);
    }

    /**
     * Get a validator for an incoming registration request.
     *
     * @param  array  $data
     * @return \Illuminate\Contracts\Validation\Validator
     */
    protected function validator(array $data)
    {
        return Validator::make($data, [
            'name' => 'required|max:255',
        	'username' => 'required|max:255|unique:users',
            'password' => 'required|confirmed|min:6',
        ]);
    }
}
```
And yes I do have `APP_DEBUG` set to true.

**Comment by stevebauman** [comment]
Ok, are you using OpenLDAP or ActiveDirectory?

Also, can you post your `adldap_auth.php` configuration?

**Comment by SuperDicq** [comment]
We're using ActiveDirectory.

Here is my `adldap_auth.php` file.

```
<?php

return [
    'username_attribute' => ['username' => 'samaccountname'],
    'login_fallback' => false,
    'password_key' => 'password',
    'login_attribute' => 'samaccountname',
    'select_attributes' => [
        //
    ],

];
```

**Comment by stevebauman** [comment]
Hmmmm everything looks fine... Can you try inserting this at the top of your `app/Http/routes.php` file and see what the result is?

```php
$username = 'myusername';
$password = 'mypassword';

dd(Adldap::authenticate($username, $password));
```

**Comment by SuperDicq** [comment]
The output is `true`

**Comment by stevebauman** [comment]
Ok, can you try inserting this at the top of your `app/Http/routes.php` file and see what the result instance is?

```php
dd(Adldap::users()->find('myusername'));
```

Need to see if an instance of `Adldap\Models\User` is returned.

**Comment by SuperDicq** [comment]
The response here is `false`

**Comment by stevebauman** [comment]
Ok, looks like this may be the issue.

Can you try:

```php
dd(Adldap::search()->where('cn', '=', 'My Name')->get());
```

And see what instances are returned (if any)?

**Comment by SuperDicq** [comment]
It seems like an empty ArrayCollection.
```
ArrayCollection {#263 ▼
  -elements: []
}
```

**Comment by stevebauman** [comment]
Hmm, do you have a `base_dn` set in your `config/adldap.php` file? Or have SSL / TLS enabled?

**Comment by SuperDicq** [comment]
```
	'connection_settings' => [
	
		'account_suffix'        => '@qlic',
		'domain_controllers'    => ['OFFICE.QLIC.NL'],
		'port'                  => 389,
		'base_dn'               => 'dc=QLIC-SRV01', 
		'admin_username'        => '****',
		'admin_password'        => '****',
		'follow_referrals'      => false,
		'use_ssl'               => false,
		'use_tls'               => false,
		'use_sso'               => false,
	]
```

**Comment by stevebauman** [comment]
Can you try:

```php
dd(Adldap::getRootDse());
```

And check the attribute `rootdomainnamingcontext`? Your `base_dn` needs to match this value.

**Comment by SuperDicq** [comment]
Fixed it.
My `base_dn` was not correct.
I found the right `base_dn` by typing in `dsquery computer` in cmd.exe on the server.

Thanks for your help.

**Comment by stevebauman** [comment]
Great! Glad you've solved it!

No problem at all. If you encounter any further issues please create an issue. I'd be glad to help.

I'll create a troubleshooting document so I can keep track of these issues.

**Comment by vermaboys** [comment]
I have solved this issue. Click https://github.com/vermaboys/change-error-message-of-login-laravel5.4
