### ISSUE TITLE
[Question] How do you implement Scopes?

### ISSUE THREAD

**Issue by entrique** [Adldap2/Adldap2-Laravel#460]
- Laravel Version: #.#
- Adldap2-Laravel Version: #.#
- PHP Version: #.#
- LDAP Type: 

### Description:
This is my builder
    public function apply(Builder $query)
    {
        // The distinguished name of our LDAP group.
        $bigroup = Adldap::search()->groups()->find('BIGroup');

        $query->whereMemberOf($bigroup);
    }

adldap_auth
    'scopes' => [

        // Only allows users with a user principal name to authenticate.

        Adldap\Laravel\Scopes\UpnScope::class,

        //Only allows users under BIGroup to Login
        App\Scopes\BIGroup::class,

    ],

It still allows all users from the domain to log in.

**Comment by stevebauman** [comment]
Hi @entrique,

Can you try this instead:

```php
public function apply(Builder $query)
{
    // The distinguished name of our LDAP group.
    $bigroup = Adldap::search()->groups()->find('BIGroup');

    $query->whereMemberOf($bigroup->getDn());
}
```

Also, clear your configuration cache by calling `php artisan config:clear` and then try again and see if this still occurs?

**Comment by entrique** [comment]
Thanks. I got it working!
