### ISSUE TITLE
Import user's relational data (groups) via adldap:import, no user->id

### ISSUE THREAD

**Issue by TipTopNick** [Adldap2/Adldap2-Laravel#461]
- Laravel Version: 5.5.28
- Adldap2-Laravel Version: 8.0.10
- PHP Version: 7.0.22
- LDAP Type: Active Directory

> This can be in relation to issue #456 (you may check my last comment on it after it closed, -great job on that btw).

I'm attempting to use adldap:import to create data in my DB tables that completely imports (and syncs) active directory.  However I need user->id (the user model) for each user to get relations for attributes such as the user<->groups when importing and creating relational data.

Is there a way you can suggest to do this?

I'm Loving Adldap2!

**Comment by stevebauman** [comment]
Hi @TipTopNick, thanks for the kind words! I'm glad you like it :smile:

I see what you're saying, as the `AuthenticationSuccessful` event is only fired (obviously) during authentication and not during imports, and there are no events that are fired when a user is saved during an import.

I'll definitely need to add an event for this use case, but if you need this right now, you can extend the original command and override the `save` method.

I'm not sure how your group management is configured for your application, but here's an example:

```php
namespace App\Console;

use App\Group;
use Adldap\Laravel\Commands\Console\Import;

class LdapImport extends Import
{
    protected function save(User $user, Model $model) : bool
    {
        if (parent::save($user, $model)) {
            $group = Group::where(['name' => 'admin'])->first();

            $model->groups()->save($group);
        }
    }
}
```

You'd want to optimize the above example (such as only retrieving the group you want once so it's not queried for when importing every single user).

I will be implementing an event for this scenario though!

**Comment by stevebauman** [comment]
Hi @TipTopNick,

This will be in a new release shortly, however you can now create a listener and utilize the event `Adldap\Laravel\Events\Imported` to retrieve the newly imported user:

```php
namespace App\Listeners;

use App\Group;
use Adldap\Laravel\Events\Imported;

class SyncGroups
{
    public function handle(Imported $event)
    {
        // The LDAP users record.
        $user = $event->user;

        // The LDAP users eloquent model.
        $model = $event->model;

        // Performing a group check on the users LDAP record
        // before adding them into our application group.
        if ($user->inGroup('IT')) {
            $administrators = Group::where(['name' => 'administrators'])->first();

            $model->groups()->save($administrators);
        }
    }
}
```

**Comment by SandeepAgrahari** [comment]
Yes @TipTopNick , I am facing same thing.

**Comment by SandeepAgrahari** [comment]
Hi @TipTopNick 

I solved this issue by using Synchronized even in place of imported event.
