### ISSUE TITLE
Retrieved LDAP objects are empty

### ISSUE THREAD

**Issue by Roemerb** [Adldap2/Adldap2-Laravel#462]
- Laravel Version: 5.5.28
- Adldap2-Laravel Version: 4.0.4
- PHP Version: 7.2.1
- LDAP Type: OpenLDAP

### Description:
(I'm a bit of an LDAP noob, but I'm trying by best, sorry if I make any uninformed comments)

I have an issue similar to #209  and #426. After verifying my base DN, `Adldap::search()->get()` is no longer empty, but I still can't query any information about my LDAP users. The only properties that the results have are `exists` and `dateFormat`. This is the output of `Adldap::search()->get()`:

```php
>>> Adldap::search()->get()
=> Illuminate\Support\Collection {#961
     all: [
       Adldap\Models\Entry {#955
         +exists: true,
         +dateFormat: "Y-m-d H:i:s",
       },
       Adldap\Models\Entry {#956
         +exists: true,
         +dateFormat: "Y-m-d H:i:s",
       },
       Adldap\Models\Entry {#957
         +exists: true,
         +dateFormat: "Y-m-d H:i:s",
       },
       Adldap\Models\Entry {#958
         +exists: true,
         +dateFormat: "Y-m-d H:i:s",
       },
     ],
   }
```

It does not work if I change the admin password (I get an error that states that the credentials are invalid) so I know that I am logged in to the server. Using `findByDN` I can find single users, but I get the same result: I can only see that it exists but no other information. Obviously, this means `Auth::attempt` doesn't work either 😢  Here is a screenshot of my LDAP staging server's structure:

![screenshot](https://i.imgur.com/MeBgKhF.png)

As you can see, it's nothing complicated, and the number of results from `search()` matches the number of objects on the server.

*config/adldap.php:*

Completely stock. `.env`:
ADLDAP_CONTROLLERS=[IP address of my server]
ADLDAP_BASEDN=dc=focus,dc=nl
ADLDAP_ADMIN_USERNAME=cn=admin,dc=focus,dc=nl
ADLDAP_ADMIN_PASSWORD=[Admin password]

*config/adldap_auth.php:*

Completely stock

Eventually, I want my users to authenticate either by the `ldap_dn` property of their Eloquent user objects (+ a password of course), or a number that is also attached to the user objects. In the latter case the DN will be the same for all users except for that number.

All help is appreciated. Thanks in advance!

**Comment by stevebauman** [comment]
Hi @Roemerb,

Did you change your schema in your `config/adldap.php` file to `OpenLDAP`?

**Comment by Roemerb** [comment]
@stevebauman Thanks for your reply. I forgot to change this and have now, however, it doesn't seem to help. Output from `Adldap::search()->get()`:

```php
=> Illuminate\Support\Collection {#961
     all: [
       Adldap\Models\Entry {#955
         +exists: true,
         +dateFormat: "Y-m-d H:i:s",
       },
       Adldap\Models\Entry {#956
         +exists: true,
         +dateFormat: "Y-m-d H:i:s",
       },
       Adldap\Models\User {#957
         +exists: true,
         +dateFormat: "Y-m-d H:i:s",
       },
       Adldap\Models\User {#958
         +exists: true,
         +dateFormat: "Y-m-d H:i:s",
       },
     ],
   }
```

I rebooted Homestead to make sure the changes went into effect.

**Comment by stevebauman** [comment]
Oh hang on, are you doing this from `php artisan tinker`? It won't display all the properties.

You'll need to call either a dump & die (`dd()`), or explicitly retrieve the attributes:

```bash
> $user = \Adldap::search()->users()->get()->first();

> $user->getAttributes();
```

**Comment by Roemerb** [comment]
Ah I was! This solved the issue. Glad I'm now able to find my LDAP attributes. Hopefully I'll get the Laravel auth to work!

**Comment by stevebauman** [comment]
Ok great, thanks for following up.

If you encounter any further issues, give me a shout!
