### ISSUE TITLE
Can't import an user

### ISSUE THREAD

**Issue by pmirandaarias** [Adldap2/Adldap2-Laravel#464]
- Laravel Version: 5.4
- Adldap2-Laravel Version: #.#
- PHP Version: 7.1.10
- LDAP Type: Active Directory

Description: I use the command ` php artisan adldap:import someemail`, everything goes well, it found the user, then I put yes, yes.  Then the last message is `Successfully imported / synchronized 0 user(s).`

Why is not importing the user? My provider is:

`'provider' => Adldap\Laravel\Auth\DatabaseUserProvider::class,`

**Comment by pmirandaarias** [comment]
adldap_auth.php:

'connection' => env('ADLDAP_CONNECTION', 'default'),
    'provider' => Adldap\Laravel\Auth\DatabaseUserProvider::class,
    'resolver' => Adldap\Laravel\Auth\Resolver::class,
    'importer' => Adldap\Laravel\Auth\Importer::class,
    'rules' => [
        Adldap\Laravel\Validation\Rules\DenyTrashed::class,
    ],
    'scopes' => [
        Adldap\Laravel\Scopes\UpnScope::class,
    ],
    'usernames' => [
        'ldap' => 'administrador',
        'eloquent' => 'email',
    ],
    'login_fallback' => env('ADLDAP_LOGIN_FALLBACK', false),
    'password_sync' => env('ADLDAP_PASSWORD_SYNC', true),
    'windows_auth_attribute' => ['samaccountname' => 'AUTH_USER'],
    'sync_attributes' => [
        'email' => 'userprincipalname',
        'name' => 'cn',
    ],

-------------
adldap.php

    'connections' => [
        'default' => [
            'auto_connect' => true,
            'connection' => Adldap\Connections\Ldap::class,
            'schema' => Adldap\Schemas\ActiveDirectory::class,
            'connection_settings' => [
                'account_prefix' => env('ADLDAP_ACCOUNT_PREFIX', ''),
                'account_suffix' => env('ADLDAP_ACCOUNT_SUFFIX', '@redcne.cne.cl'),
                'domain_controllers' => explode(' ', env('ADLDAP_CONTROLLERS', '10.0.0.230')),
                'port' => env('ADLDAP_PORT', 389),
                'timeout' => env('ADLDAP_TIMEOUT', 5),
                'base_dn' => env('ADLDAP_BASEDN', 'dc=redcne,dc=cne,dc=cl'),
                'admin_account_suffix' => env('ADLDAP_ADMIN_ACCOUNT_SUFFIX', '@redcne.cne.cl'),
                'admin_username' => env('ADLDAP_ADMIN_USERNAME', 'administrador'),
                'admin_password' => env('ADLDAP_ADMIN_PASSWORD', 'Cne_2157'),
                'follow_referrals' => false,
                'use_ssl' => false,
                'use_tls' => false,
            ],
        ],
    ],

**Comment by stevebauman** [comment]
Hi, can you check your log? All users who can't be imported are logged with the exception.

**Comment by pmirandaarias** [comment]
Which log? Adldap log? or php, mysql

**Comment by stevebauman** [comment]
The Laravel log file stored in your applications `storage` directory.

**Comment by pmirandaarias** [comment]
2018-01-24 13:33:16] production.ERROR: Unable to import user Alonso Arriagada Aguayo. SQLSTATE[42S22]: Column not found: 1054 Unknown column 'name' in 'field list' (SQL: insert into `users` (`email`, `name`, `password`, `updated_at`, `created_at`) values (aarriagada@redcne.cne.cl, Alonso Arriagada Aguayo, $2y$10$GTKVp.6aqny6ugA7r/qBKeMiMz6zP3H4rw3uYn0t2CDnvKUBNkZqK, 2018-01-24 13:33:16, 2018-01-24 13:33:16))

**Comment by pmirandaarias** [comment]
meh... I'm using "Laravel-boilerplate"... and the users table is like this:

![image](https://user-images.githubusercontent.com/20463330/35336777-3953b22e-00f8-11e8-90a1-09c6e8a08638.png)

**Comment by pmirandaarias** [comment]
Should I say goodbye to Adldap2? :( I need to connect to LDAP with this system...

**Comment by stevebauman** [comment]
Looks like your users table doesn't have a `name` column and you're syncing a name column in your `sync_attributes`.

**Comment by stevebauman** [comment]
The exception is clear on your issue, this isn't an Adldap2 problem, this is a configuration issue.

**Comment by pmirandaarias** [comment]
In that case, should I try to adding to

    'sync_attributes' => [

        'email' => 'userprincipalname',
        'name' => 'cn',

    ],

The rest of attributes that I have on my table?

**Comment by stevebauman** [comment]
If you don't want your users to have a name, then you need to remove the `name` key in your `sync_attributes` array.

**Comment by pmirandaarias** [comment]
got it, it works. Thanks.

**Comment by pmirandaarias** [comment]
Last question, is there a way to add the same pass of LDAP to my db with the import?

**Comment by jonathan-bird** [comment]
To anyone looking back on this, you could technically just change `name` key in `sync_attributes` array to `first_name` which is what I've done. It's not ideal, but I'm about to dig deep to see if I could somehow split based on space and then insert into both first_name and last_name.
