### ISSUE TITLE
Can't authenticate against LDAP server

### ISSUE THREAD

**Issue by pmirandaarias** [Adldap2/Adldap2-Laravel#465]
What password is stored when you are importing users from AD?

I've just imported some users, and there are stored password on my db now but, what passwords are? how are their made?

**Comment by stevebauman** [comment]
Hi, when importing users, a random 16 character password is used.

This is updated (if you use password sync) to their correct password when they login.

This is described in the import documentation.

**Comment by pmirandaarias** [comment]
I have:

    'password_sync' => env('ADLDAP_PASSWORD_SYNC', true),

But is not working.

**Comment by stevebauman** [comment]
What do you mean? Are you able to login successfully?

You'll see the hash password change for the user account that was imported upon login.

**Comment by pmirandaarias** [comment]
No, it says that credentials are not found. 

First, In my db I only have 1 user (Admin), you can see it here:

![image](https://user-images.githubusercontent.com/20463330/35350234-17ab5ab8-011c-11e8-94f8-d657463f7287.png)

Then I import a user from AD, like this:
![image](https://user-images.githubusercontent.com/20463330/35350260-2981aaf8-011c-11e8-9578-10afed66def2.png)

And it's there as the image shows. As I said before, i have `true` this:

    'password_sync' => env('ADLDAP_PASSWORD_SYNC', true),

But now if I try to login with "mcorvalan@cne.cl" and it's password. I know that the password is correct because I can check it with: 

    Adldap::auth()->attempt(str_replace('@cne.cl', '', $request->email), $request->password)
    //returns true.

So I don't get it where's the problem.

**Comment by stevebauman** [comment]
This is your first issue:

> Adldap::auth()->attempt(str_replace('@cne.cl', '', $request->email), $request->password)
> //returns true.

If your configuration is the same as your previously posted issue, then you won't be able to authenticate correctly as you're including an account suffix of `'@redXXX.XXX.cl'`. Since you're using users email addresses to authenticate, simply leave this as an empty string.

You don't need to change the `admin_account_suffix`.

Remember, the suffix and prefix'es are added onto **all** usernames.

What's happening right now when you authenticate with `mcorvalan@cne.cl`, it's appending the suffix onto this email, which turns out to be: `mcorvalan@cne.cl@cne.cl`, which will fail LDAP authentication against your server.

Give that a shot and let me know if you still have problems logging in.

**Comment by pmirandaarias** [comment]
Doesn't work. Actually, I just was using:

    Adldap::auth()->attempt(str_replace('@cne.cl', '', $request->email), $request->password)
    //returns true.

only for to be sure that the password was ok for 'mcorvalan', that's why I remove the '@cne.cl' from the request->email string. attempt() returns true with that. But I thought that I don't need to touch LoginController.php, but in my case... maybe it's a problem on how the user is validated, because as I said in the other issue (should posted in this one all the info, my mistake) I'm using "Laravel-boilerplate". So LoginController.php looks right now like this:

    public function login(Request $request) {
        //$user = \Adldap::search()->users()->findBy('samaccountname', str_replace('@cne.cl', '', $request->email));
        //dd($user);
        if(\Adldap::auth()->attempt(str_replace('@cne.cl', '', $request->email), $request->password)){
                print_r("success");
		//die();
	}
	$this->validateLogin($request);
	if ($this->hasTooManyLoginAttempts($request)) {
        	$this->fireLockoutEvent($request);
	        return $this->sendLockoutResponse($request);
	}
	if ($this->attemptLogin($request)) {
		return $this->sendLoginResponse($request);
	}
	$this->incrementLoginAttempts($request);

	return $this->sendFailedLoginResponse($request);
    } 

So, my .env file has this now:

ADLDAP_CONTROLLERS=x.x.x.x
#ADLDAP_ACCOUNT_SUFFIX=@redcne.cne.cl
ADLDAP_ACCOUNT_SUFFIX=
ADLDAP_PORT=389
ADLDAP_BASEDN="dc=redcne,dc=cne,dc=cl"
ADLDAP_ADMIN_ACCOUNT_SUFFIX=@redcne.cne.cl
ADLDAP_ADMIN_USERNAME=administrador
ADLDAP_ADMIN_PASSWORD=xxxxxx
ADLDAP_PASSWORD_SYNC=true

**Comment by pmirandaarias** [comment]
If it's necessary this is what 

    $user = \Adldap::search()->users()->findBy('samaccountname', str_replace('@cne.cl', '', $request->email));
    dd($user);

shows (with sn, givennma and mail expanded):

User {#1536 ▼
  +exists: true
  +dateFormat: "Y-m-d H:i:s"
  #dn: "CN=Manuel Corvalan,OU=TI,OU=Depto Admin y Finanzas,OU=CNE,DC=redcne,DC=cne,DC=cl"
  #query: Builder {#1543 ▶}
  #schema: ActiveDirectory {#1538}
  #attributes: array:131 [▶]
  #original: array:131 [▼
    "objectclass" => array:4 [▶]
    0 => "objectclass"
    "cn" => array:1 [▶]
    1 => "cn"
    "sn" => array:1 [▼
      0 => "Corvalan"
    ]
    2 => "sn"
    "description" => array:1 [▶]
    3 => "description"
    "physicaldeliveryofficename" => array:1 [▶]
    4 => "physicaldeliveryofficename"
    "telephonenumber" => array:1 [▶]
    5 => "telephonenumber"
    "givenname" => array:1 [▶]
    6 => "givenname"
    "distinguishedname" => array:1 [▼
      0 => "CN=Manuel Corvalan,OU=TI,OU=Depto Admin y Finanzas,OU=CNE,DC=redcne,DC=cne,DC=cl"
    ]
    7 => "distinguishedname"
    "instancetype" => array:1 [▶]
    8 => "instancetype"
    "whencreated" => array:1 [▶]
    9 => "whencreated"
    "whenchanged" => array:1 [▶]
    10 => "whenchanged"
    "displayname" => array:1 [▶]
    11 => "displayname"
    "usncreated" => array:1 [▶]
    12 => "usncreated"
    "memberof" => array:8 [▶]
    13 => "memberof"
    "usnchanged" => array:1 [▶]
    14 => "usnchanged"
    "department" => array:1 [▶]
    15 => "department"
    "homemta" => array:1 [▶]
    16 => "homemta"
    "proxyaddresses" => array:2 [▶]
    17 => "proxyaddresses"
    "homemdb" => array:1 [▶]
    18 => "homemdb"
    "mdbusedefaults" => array:1 [▶]
    19 => "mdbusedefaults"
    "mailnickname" => array:1 [▶]
    20 => "mailnickname"
    "name" => array:1 [▶]
    21 => "name"
    "objectguid" => array:1 [▶]
    22 => "objectguid"
    "useraccountcontrol" => array:1 [▶]
    23 => "useraccountcontrol"
    "badpwdcount" => array:1 [▶]
    24 => "badpwdcount"
    "codepage" => array:1 [▶]
    25 => "codepage"
    "countrycode" => array:1 [▶]
    26 => "countrycode"
    "badpasswordtime" => array:1 [▶]
    27 => "badpasswordtime"
    "lastlogoff" => array:1 [▶]
    28 => "lastlogoff"
    "lastlogon" => array:1 [▶]
    29 => "lastlogon"
    "pwdlastset" => array:1 [▶]
    30 => "pwdlastset"
    "primarygroupid" => array:1 [▶]
    31 => "primarygroupid"
    "userparameters" => array:1 [▶]
    32 => "userparameters"
    "objectsid" => array:1 [▶]
    33 => "objectsid"
    "admincount" => array:1 [▶]
    34 => "admincount"
    "accountexpires" => array:1 [▶]
    35 => "accountexpires"
    "logoncount" => array:1 [▶]
    36 => "logoncount"
    "samaccountname" => array:1 [▶]
    37 => "samaccountname"
    "samaccounttype" => array:1 [▶]
    38 => "samaccounttype"
    "showinaddressbook" => array:5 [▶]
    39 => "showinaddressbook"
    "legacyexchangedn" => array:1 [▶]
    40 => "legacyexchangedn"
    "userprincipalname" => array:1 [▶]
    41 => "userprincipalname"
    "objectcategory" => array:1 [▶]
    42 => "objectcategory"
    "msnpallowdialin" => array:1 [▶]
    43 => "msnpallowdialin"
    "dscorepropagationdata" => array:5 [▶]
    44 => "dscorepropagationdata"
    "lastlogontimestamp" => array:1 [▶]
    45 => "lastlogontimestamp"
    "msexchrequireauthtosendto" => array:1 [▶]
    46 => "msexchrequireauthtosendto"
    "textencodedoraddress" => array:1 [▶]
    47 => "textencodedoraddress"
    "mail" => array:1 [▼
      0 => "mcorvalan@cne.cl"
    ]
    48 => "mail"
    "msexchhomeservername" => array:1 [▶]
    49 => "msexchhomeservername"
    "msexchalobjectversion" => array:1 [▶]
    50 => "msexchalobjectversion"
    "msexchmailboxsecuritydescriptor" => array:1 [▶]
    51 => "msexchmailboxsecuritydescriptor"
    "msexchuseraccountcontrol" => array:1 [▶]
    52 => "msexchuseraccountcontrol"
    "msexchmailboxguid" => array:1 [▶]
    53 => "msexchmailboxguid"
    "msexchreciplimit" => array:1 [▶]
    54 => "msexchreciplimit"
    "msexchpoliciesincluded" => array:1 [▶]
    55 => "msexchpoliciesincluded"
    "msexchwhenmailboxcreated" => array:1 [▶]
    56 => "msexchwhenmailboxcreated"
    "msexchrbacpolicylink" => array:1 [▶]
    57 => "msexchrbacpolicylink"
    "msexchrecipienttypedetails" => array:1 [▶]
    58 => "msexchrecipienttypedetails"
    "msexchuserculture" => array:1 [▶]
    59 => "msexchuserculture"
    "msexchmobilemailboxflags" => array:1 [▶]
    60 => "msexchmobilemailboxflags"
    "msexchrecipientdisplaytype" => array:1 [▶]
    61 => "msexchrecipientdisplaytype"
    "msexchtextmessagingstate" => array:2 [▶]
    62 => "msexchtextmessagingstate"
    "msexchsafesendershash" => array:1 [▶]
    63 => "msexchsafesendershash"
    "msexchversion" => array:1 [▶]
    64 => "msexchversion"
    "dn" => "CN=Manuel Corvalan,OU=TI,OU=Depto Admin y Finanzas,OU=CNE,DC=redcne,DC=cne,DC=cl"
  ]
  #modifications: []
  #timestampFormat: "YmdHis.0Z"
}

**Comment by pmirandaarias** [comment]
I'll put again all my files:

LoginController.php

    public function login(Request $request){
        //	$user = \Adldap::search()->users()->findBy('samaccountname', str_replace('@cne.cl', '', $request->email));
        //dd($user);
        /*if(\Adldap::auth()->attempt(str_replace('@cne.cl', '', $request->email), $request->password))
        {print_r("entre auth"); die();}*/

        $this->validateLogin($request);

        if ($this->hasTooManyLoginAttempts($request)) {
            $this->fireLockoutEvent($request);

            return $this->sendLockoutResponse($request);
        }

        if ($this->attemptLogin($request)) {
            return $this->sendLoginResponse($request);
        }
        $this->incrementLoginAttempts($request);

        return $this->sendFailedLoginResponse($request);
    }
    
adldap_auth.php

    return [
        'connection' => env('ADLDAP_CONNECTION', 'default'),
        'provider' => Adldap\Laravel\Auth\DatabaseUserProvider::class,
        'resolver' => Adldap\Laravel\Auth\Resolver::class,
        'importer' => Adldap\Laravel\Auth\Importer::class,
        'rules' => [
            Adldap\Laravel\Validation\Rules\DenyTrashed::class,
        ],
        'scopes' => [
            Adldap\Laravel\Scopes\UpnScope::class,
        ],
        'usernames' => [
            'ldap' => 'samaccountname',
            'eloquent' => 'email',
        ],
        'login_fallback' => env('ADLDAP_LOGIN_FALLBACK', true),
        'password_sync' => env('ADLDAP_PASSWORD_SYNC', true),
        'windows_auth_attribute' => ['samaccountname' => 'AUTH_USER'],
        'sync_attributes' => [
            'email' => 'mail',
            'first_name' => 'givenname',
            'last_name'=>'sn',
        ],
    ];

adldap.php

    return [
        'connections' => [
            'default' => [
                'auto_connect' => true,
                'connection' => Adldap\Connections\Ldap::class,
                'schema' => Adldap\Schemas\ActiveDirectory::class,
                'connection_settings' => [
                    'account_prefix' => env('ADLDAP_ACCOUNT_PREFIX', ''),
                    'account_suffix' => env('ADLDAP_ACCOUNT_SUFFIX', '@redcne.cne.cl'),
                    'domain_controllers' => explode(' ', env('ADLDAP_CONTROLLERS', '10.0.0.230')),
                    'port' => env('ADLDAP_PORT', 389),
                    'timeout' => env('ADLDAP_TIMEOUT', 5),
                    'base_dn' => env('ADLDAP_BASEDN', 'dc=redcne,dc=cne,dc=cl'),
                    'admin_account_suffix' => env('ADLDAP_ADMIN_ACCOUNT_SUFFIX', '@redcne.cne.cl'),
                    'admin_username' => env('ADLDAP_ADMIN_USERNAME', 'administrador'),
                    'admin_password' => env('ADLDAP_ADMIN_PASSWORD', 'Cne_2157'),
                    'follow_referrals' => false,
                    'use_ssl' => false,
                    'use_tls' => false,
                ],
            ],
        ],
    ];

auth.php

    use App\Models\Access\User\User;

    return [
        'defaults' => [
            'guard' => 'web',
            'passwords' => 'users',
        ],
        'guards' => [
            'web' => [
                'driver' => 'session',
                'provider' => 'users',
            ],

            'api' => [
                'driver' => 'token',
                'provider' => 'users',
            ],
        ],
        'providers' => [
            'users' => [
                //'driver' => 'eloquent',
                'driver' => 'adldap',
                'model' => User::class,
            ],
            // 'users' => [
            //     'driver' => 'database',
            //     'table' => 'users',
            // ],
        ],
        'passwords' => [
            'users' => [
                'provider' => 'users',
                'table' => 'password_resets',
                'expire' => 60,
            ],
        ],
    ];

.env

    ADLDAP_CONTROLLERS=X.X.X.X
    ADLDAP_ACCOUNT_SUFFIX=@redcne.cne.cl
    ADLDAP_PORT=389
    ADLDAP_BASEDN="dc=redcne,dc=cne,dc=cl"
    ADLDAP_ADMIN_ACCOUNT_SUFFIX=@redcne.cne.cl
    ADLDAP_ADMIN_USERNAME=administrador
    ADLDAP_ADMIN_PASSWORD=XXXXX
    ADLDAP_PASSWORD_SYNC=true

**Comment by pmirandaarias** [comment]
Isn't Adldap2 re-hashing a hashed pass from AD with Password Synchronization? I still can't get this, dunno what its happening with the stored pass in my db

**Comment by stevebauman** [comment]
Hi @pmirandaarias, I haven't had time to look into your issue fully yet, but to answer your question:

When Adldap2 `password_sync` is enabled, once a user successfully passes authentication against your LDAP server, the password that was used is hashed and set on your local users database record.

Passwords cannot be read or retrieved from your LDAP server, this would be a massive security issue if that was indeed the case.

Disabling password sync simply sets a random 16 character hashed string for the local users database record.

**Comment by stevebauman** [comment]
You can also take a look at the `SyncPassword` command source code to see exactly what is going on:

https://github.com/Adldap2/Adldap2-Laravel/blob/master/src/Commands/SyncPassword.php

**Comment by pmirandaarias** [comment]
mmm, so I need first to authenticate against your LDAP and then Adldap2 will do the pass sync? Where should I do that authentication , I thought that I shouln't touch the auth code.
