### ISSUE TITLE
Getting `ValidationException` on login for email: "These credentials do not match our records."

### ISSUE THREAD

**Issue by Roemerb** [Adldap2/Adldap2-Laravel#467]
- Laravel Version: 5.5.28
- Adldap2-Laravel Version: 4.0.4
- PHP Version: 7.2.1
- LDAP Type: OpenLDAP

### Description:
Over the past few days, I've been driven slightly mad by LDAP. I just can't get it to work for some reason. I've tried any combination of `'usernames'` configuration in `adldap_auth.php` that I can think of, but I keep coming back to the same error. When I attempt to log in (in Chrome), I get a `ValidationException`. In the Validation response it has one error for the `email` property, which I use as a "username" to log in: `"These credentials do not match our records."`. I don't really get this. Does this just mean that the password was incorrect? I'm very sure that the password I entered is the same as the users password on the LDAP server. Here's my configuration:

__auth.php__:

I changed nothing other than the driver of the `users` provider.
```
<?php

return [
    'defaults' => [
        'guard' => 'web',
        'passwords' => 'users',
    ],
    'guards' => [
        'web' => [
            'driver' => 'session',
            'provider' => 'users',
        ],

        'api' => [
            'driver' => 'token',
            'provider' => 'users',
        ],
    ],
    'providers' => [
        'users' => [
            'driver' => 'adldap',
            'model' => App\User::class,
        ],
        // 'users' => [
        //     'driver' => 'database',
        //     'table' => 'users',
        // ],
    ],
    'passwords' => [
        'users' => [
            'provider' => 'users',
            'table' => 'password_resets',
            'expire' => 60,
        ],
    ],
];
```

__adldap.php__:

I'm pretty sure the issue isn't in here as I can fetch users just fine in `php artisan tinker`

```
<?php

return [
    'connections' => [
        'default' => [
            'auto_connect' => env('ADLDAP_AUTO_CONNECT', true),
            'connection' => Adldap\Connections\Ldap::class,
            'schema' => Adldap\Schemas\OpenLDAP::class,
            'connection_settings' => [
                'account_prefix' => env('ADLDAP_ACCOUNT_PREFIX', ''),
                'account_suffix' => env('ADLDAP_ACCOUNT_SUFFIX', ''),
                'domain_controllers' => explode(' ', env('ADLDAP_CONTROLLERS', '')),
                'port' => env('ADLDAP_PORT', 389),
                'timeout' => env('ADLDAP_TIMEOUT', 5),
                'base_dn' => env('ADLDAP_BASEDN', ''),
                'admin_account_prefix' => env('ADLDAP_ADMIN_ACCOUNT_PREFIX', ''),
                'admin_account_suffix' => env('ADLDAP_ADMIN_ACCOUNT_SUFFIX', ''),
                'admin_username' => env('ADLDAP_ADMIN_USERNAME', ''),
                'admin_password' => env('ADLDAP_ADMIN_PASSWORD', ''),
                'follow_referrals' => false,
                'use_ssl' => env('ADLDAP_USE_SSL', false),
                'use_tls' => env('ADLDAP_USE_TLS', false),
            ],
        ],
    ],
];
```

__adldap_auth.php__:

Note that the values for `usernames` are my current ones. I also tried the defualt, `uid`, `email`, `employeeNumber`' and lots of other things. The aim is that I can log in to Laravel with the password from LDAP and the `mail` property from LDAP as username.

```
<?php

return [
    'connection' => env('ADLDAP_CONNECTION', 'default'),
    'provider' => Adldap\Laravel\Auth\DatabaseUserProvider::class,
    'rules' => [
        // Denys deleted users from authenticating.
        Adldap\Laravel\Validation\Rules\DenyTrashed::class,
        // Allows only manually imported users to authenticate.
        // Adldap\Laravel\Validation\Rules\OnlyImported::class,

    ],
    'scopes' => [

        // Only allows users with a user principal name to authenticate.
        // Remove this if you're using OpenLDAP.
        Adldap\Laravel\Scopes\UpnScope::class,

        // Only allows users with a uid to authenticate.
        // Uncomment if you're using OpenLDAP.
        // Adldap\Laravel\Scopes\UidScope::class,

    ],
    'usernames' => [
        'ldap' => [
            'discover' => 'mail',
            'authenticate' => 'dn',
        ],
        'eloquent' => 'email',
        'windows' => [
            'discover' => 'samaccountname',
            'key' => 'AUTH_USER',
        ],
    ],
    'passwords' => [
        'sync' => env('ADLDAP_PASSWORD_SYNC', false),
        'column' => 'password',
    ],
    'login_fallback' => env('ADLDAP_LOGIN_FALLBACK', false),
    'sync_attributes' => [

        'email' => 'userprincipalname',

        'name' => 'cn',

    ],
    'logging' => [
        'enabled' => true,
        'events' => [
            \Adldap\Laravel\Events\Importing::class => \Adldap\Laravel\Listeners\LogImport::class,
            \Adldap\Laravel\Events\Synchronized::class => \Adldap\Laravel\Listeners\LogSynchronized::class,
            \Adldap\Laravel\Events\Synchronizing::class => \Adldap\Laravel\Listeners\LogSynchronizing::class,
            \Adldap\Laravel\Events\Authenticated::class => \Adldap\Laravel\Listeners\LogAuthenticated::class,
            \Adldap\Laravel\Events\Authenticating::class => \Adldap\Laravel\Listeners\LogAuthentication::class,
            \Adldap\Laravel\Events\AuthenticationFailed::class => \Adldap\Laravel\Listeners\LogAuthenticationFailure::class,
            \Adldap\Laravel\Events\AuthenticationRejected::class => \Adldap\Laravel\Listeners\LogAuthenticationRejection::class,
            \Adldap\Laravel\Events\AuthenticationSuccessful::class => \Adldap\Laravel\Listeners\LogAuthenticationSuccess::class,
            \Adldap\Laravel\Events\DiscoveredWithCredentials::class => \Adldap\Laravel\Listeners\LogDiscovery::class,
            \Adldap\Laravel\Events\AuthenticatedWithWindows::class => \Adldap\Laravel\Listeners\LogWindowsAuth::class,
            \Adldap\Laravel\Events\AuthenticatedModelTrashed::class => \Adldap\Laravel\Listeners\LogTrashedModel::class,
        ],
    ],
];
```

In my `LoginController`, the `username()` function returns `email` like default:

```php
    public function username()
    {
        return 'email';
    }
```

This is a CSV export via `phpLDAPAdmin` of the user I want to authenticate with, so that you have all the attributes, just how they are on the LDAP server:

```
"dn","cn","employeenumber","gidnumber","givenname","homedirectory","loginshell","mail","objectclass","sn","uid","uidnumber","userpassword"
"cn=Roemer Bakker,dc=focus,dc=nl","Roemer Bakker","12345","501","Roemer","/home/users/rbakker","/bin/sh","rbakker@focus.nl","inetOrgPerson | posixAccount | top","Bakker","rbakker@focus.nl",""
```

The `uid` and `mail` are the same. It does not really matter to me which is used for authentication.

Does anyone know where this issue comes from?
Thanks in advance.

**Comment by stevebauman** [comment]
Hi @Roemerb, I totally understand. We'll get you up and running, don't worry :smile:

First things first, can you change your sync attributes array from:

```php
'sync_attributes' => [

    'email' => 'userprincipalname',

    'name' => 'cn',

],
```

To:

```php
'sync_attributes' => [

    'email' => 'mail', // Changed to mail.

    'name' => 'cn',

],
```

Also, after the change can you try authenticating with a valid user and checking your Laravel logs to see where the authentication failure occurs?

**Comment by stevebauman** [comment]
Oh also, please remove the `UpnScope` in your configuration as well! This is likely blocking your user from authenticating as OpenLDAP users do not contain `userprincipalname`'s

> // Only allows users with a user principal name to authenticate.
> // Remove this if you're using OpenLDAP.

**Comment by stevebauman** [comment]
There are a lot of configuration options (a blessing and a curse unfortunately), but we'll get you working.

**Comment by Roemerb** [comment]
@stevebauman That's a relief to hear! Thanks in advance! Those two suggestions definitely seemed to help, as I now get a different error:

```
Adldap \ Auth \ UsernameRequiredException
A username must be specified.
```

**Comment by Roemerb** [comment]
Ah, it seems like `validateCredentials` is being called without the `$username` argument for some reason, this should be the `email` from the request:

![Screenshot](https://i.imgur.com/G5kYaO6.png)

**Comment by stevebauman** [comment]
Did you modify the `LoginController` at all besides the `username` method?

Also can you try modifying (under `usernames.ldap`):

```php
'authenticate' => 'dn',
```

To:

```php
'authenticate' => 'distinguishedname',
```

**Comment by stevebauman** [comment]
It looks like there is no username being passed to bind to your LDAP server, this is controlled via the `useranames.ldap.authenticate` configuration option.

**Comment by Roemerb** [comment]
@stevebauman Yes I changed it to `dn` however, I just changed it back to `distinguishedname` and I still get the same error. Also tried `distinguishedName` with capital n. If I use `uid`, `mail` or `employeeNumber` I get the original ValidationException with `The given data was invalid.` for the email property.

**Comment by Roemerb** [comment]
@stevebauman Oh and no, I did not edit the LoginController further:

```
<?php

namespace App\Http\Controllers\Auth;

use App\Http\Controllers\Controller;
use Illuminate\Foundation\Auth\AuthenticatesUsers;

class LoginController extends Controller
{
    /*
    |--------------------------------------------------------------------------
    | Login Controller
    |--------------------------------------------------------------------------
    |
    | This controller handles authenticating users for the application and
    | redirecting them to your home screen. The controller uses a trait
    | to conveniently provide its functionality to your applications.
    |
    */

    use AuthenticatesUsers;

    /**
     * Where to redirect users after login.
     *
     * @var string
     */
    protected $redirectTo = '/home';

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('guest')->except('logout');
    }

    public function username()
    {
        return 'email';
    }
}

```

**Comment by Roemerb** [comment]
Okay I found that the issue is in line 100 of `UserResolver`. The `getFirstAttribute()` function returns `null` when it's called with `dn`. I `dd`'ed the entirety of `$user` to see why `dn` is different than the rest:

```php
User {#679 ▼
  +exists: true
  #dn: "cn=Roemer Bakker,dc=focus,dc=nl"
  #query: Builder {#668 ▶}
  #schema: OpenLDAP {#646}
  #modifications: []
  +dateFormat: "Y-m-d H:i:s"
  #timestampFormat: "YmdHis.0Z"
  #attributes: array:25 [▼
    "cn" => array:1 [▼
      0 => "Roemer Bakker"
    ]
    0 => "cn"
    "givenname" => array:1 [▶]
    1 => "givenname"
    "gidnumber" => array:1 [▶]
    2 => "gidnumber"
    "homedirectory" => array:1 [▶]
    3 => "homedirectory"
    "sn" => array:1 [▶]
    4 => "sn"
    "loginshell" => array:1 [▶]
    5 => "loginshell"
    "objectclass" => array:3 [▶]
    6 => "objectclass"
    "uidnumber" => array:1 [▶]
    7 => "uidnumber"
    "uid" => array:1 [▶]
    8 => "uid"
    "mail" => array:1 [▶]
    9 => "mail"
    "userpassword" => array:1 [▶]
    10 => "userpassword"
    "employeenumber" => array:1 [▶]
    11 => "employeenumber"
    "dn" => "cn=Roemer Bakker,dc=focus,dc=nl"
  ]
  #original: array:25 [▶]
}
```

So it seems like `getFirstAttribute()` returns `null` for the attributes that are not in an _array_. As you can see, `dn` is a just a string in `attributes` but attributes like `cn` are in an array by themselves. Do you know why this is?

**Comment by Roemerb** [comment]
@stevebauman Do you have any idea?

**Comment by legreco** [comment]
Does login with email actually work? 
I'm still trying to understand what wrong with my configuration. 
I'm still unable to login with email :(

**Comment by stevebauman** [comment]
Hey @Roemerb, this seems to only occur with OpenLDAP, as it doesn't look like it returns the distinguished name as an attribute from a search result. Going to see if I can resolve this, thanks!

**Comment by stevebauman** [comment]
Hey @Roemerb, I've updated the root Adldap2 repository to `v8.1.2`, can you run `composer update` and try you configuration again?

**Comment by Roemerb** [comment]
Hey Steve,

It works now!! So glad to say that. Been fighting on and off with this for about 2 weeks but it finally works. I

Thanks so much for helping me. If you're okay with it, I'm thinking of restructuring the documentation for this package a bit. In my opinion, it would be better if they were more stepwise. When I initially started struggling, I had just followed the instructions for laravel 5.5. That's why I didn't know about the scope that I had to change as well as the other openldap specific stuff. Had there be another 'guide' for OpenLDAP / active directory specific stuff, I think I would have found it earlier.

Thanks again for helping with this issue though.

**Comment by stevebauman** [comment]
Awesome! Glad you're up and running.

> If you're okay with it, I'm thinking of restructuring the documentation for this package a bit. In my opinion, it would be better if they were more stepwise.

I'm more than okay with you restructuring the documentation, it's definitely lacking and unfortunately I haven't had much time to make it as clear and thorough as I'd like.

Send some PR's when you're ready!

**Comment by pascalbaljet** [comment]
v8.1.2 broke it for me but it worked fine with v8.1.1, I'm using OpenLDAP btw.

`Arr::pull($attributes, 'dn')` returns an array (https://github.com/Adldap2/Adldap2/commit/9c8bb7bc72f0c11c5d511dda4b0c2de3415875ac#diff-b01f2ba80c47f5889a59b33570e7e76fR196) which can't be casted to a string (https://github.com/Adldap2/Adldap2/commit/9c8bb7bc72f0c11c5d511dda4b0c2de3415875ac#diff-7ed9b959bdea1746ccfa06980ecdab56R328).

**Comment by stevebauman** [comment]
Hey @pascalbaljet, that's strange? Is this a setting for OpenLDAP that's configurable per environment?

I don't have much knowledge with OpenLDAP unfortunately, so I rely on everyone else for this.

I've created an issue here for this:

https://github.com/Adldap2/Adldap2/issues/495

**Comment by stevebauman** [comment]
Hey @pascalbaljet, just resolved this and will have a release shortly: https://github.com/Adldap2/Adldap2/commit/1d1f36d96cf7cdf2616b20b09b977ebf960e3193

**Comment by pascalbaljet** [comment]
Thanks! I’ll test it later today and post the results!

**Comment by pascalbaljet** [comment]
@stevebauman It has been fixed, thank you! Could you tag a new version?
