### ISSUE TITLE
Class 'Adldap\Laravel\Facades\Adldap\adLDAP' not found

### ISSUE THREAD

**Issue by thill0822** [Adldap2/Adldap2-Laravel#468]
- Laravel Version: 5.2.45
- PHP Version: 7.0

I've followed the installation instructions. 
- Ran `composer update`
- Updated the `config/app.php` service provider and facade
- Ran `php artisan vendor:publish --tag="adldap"`

In my controller, I added `use Adldap\Laravel\Facades\Adldap;` and then in the function: 

        $adldap = new adldap\adLDAP();
        $provider = $adldap->connect();
        return([$provider]);

The error I get is as follows: 

`  FatalThrowableError in HomeController.php line 36: Class 'Adldap\Laravel\Facades\Adldap\adLDAP' not found `

I'm not sure what I'm doing wrong here?

**Comment by stevebauman** [comment]
Hi, your use statement is incorrect.

It should be: `Adldap\Laravel\Facades\Adldap`

Not: `Adldap\Laravel\Facades\Adldap\adLDAP`
