### ISSUE TITLE
Couldn't able to work login_fallback

### ISSUE THREAD

**Issue by luf** [Adldap2/Adldap2-Laravel#47]
I have set the option "login_fallback" true but I'm still getting ldap_bind(): Unable to bind to server: Invalid credentials error for the local db user.
The users who exist in AD can login but local db users gets the error above.

**Comment by stevebauman** [comment]
Hi @luf, You must have debugging enabled for it to be showing bind errors.

Inside your `.env` you need to disable debugging:

```php
APP_DEBUG=false
```
