### ISSUE TITLE
User Authentication not working: using username instead of email

### ISSUE THREAD

**Issue by thill0822** [Adldap2/Adldap2-Laravel#471]
- Laravel Version: 5.2
- PHP Version: 7.1
- LDAP Type: Active Directory

I'm attempting to go through the Auth Driver docs and am hitting some issues. I can authenticate manually, and I'm trying to get the login screen to link up to ADLDAP now.
The error I'm getting is `ErrorException in UserResolver.php line 75: Undefined index: email`

I've updated my user model to use username instead of email and my database reflects this.

The [Usernames](https://github.com/Adldap2/Adldap2-Laravel/blob/master/docs/auth.md#usernames) section has a snippet of code to update. This doesn't exist in my `adldap_auth.php`. If I add this to the file (updating email to username), the error message goes away, but instead, I get 'These credentials do not match our records.'

**Comment by stevebauman** [comment]
Hi @thill0822,

> The Usernames section has a snippet of code to update. This doesn't exist in my adldap_auth.php

Sounds like you're using the `v3.0` version and looking at the `v4.0` documentation.

Can you update to `v4.0` and re-publish your configuration files by deleting them completely and using `php artisan vendor:publish`?

I'll be able to help you out further when I know the version you're running on.

**Comment by thill0822** [comment]
Thanks @stevebauman. 

I've updated the files and tested again, can still validate the login via `Adldap::auth()->attempt`. 

Now I'm seeing `These credentials do not match our records.` when trying to use the standard login. I'm not getting any other errors.

**Comment by thill0822** [comment]
Okay @stevebauman 

I've been trying again. On my homecontroller, straight into the homepage I've added this code to test: 

      $auth =  Auth::attempt([$username, $password]);
       return([$auth]);

Where the `$username` and `password` are hard coded. I'm assuming this should work via the LDAP integration if I'm reading [the docs](https://github.com/Adldap2/Adldap2-Laravel/blob/master/docs/auth.md#logging-in) correctly. 

I'm getting the following error when trying this: 

ErrorException in UserResolver.php line 75: Undefined index: username

Still can't find where I'm going wrong...

**Comment by thill0822** [comment]
@stevebauman - any suggestions?

**Comment by stevebauman** [comment]
Hi @thill0822, your above code usage is incorrect, you need to supply key -> values to the array in `Auth::attempt()`:

```php
$credentials = [
    'username' => $username,
    'password' => $password,
];

if (Auth::attempt($credentials)) {
    //
}
```

**Comment by thill0822** [comment]
Thank you. 

Found the credentials formatting issue and an update of some of my settings fixed this issue.

**Comment by stevebauman** [comment]
Great, glad you've resolved it! No problem.

**Comment by saurabh-mishrr** [comment]
Hey Guys, 
I am facing the same issue. To check my credentials I used **Tinker**

`use \Adldap\Laravel\Facades\Adldap;`
`Adldap::auth()->attempt('username', 'password', $bindAsUser = true)`

With given username and password it's giving me true in return, but while I am trying this using web interface I am getting '_These credentials do not match our records._' error.

My **LoginController** has authenticate method i.e.
`public function authenticate(Request $request)`
 `   {`
  `      if (Adldap::auth()->attempt($request->username, $request->password, $bindAsUser = true)) {`
  `          return redirect()->intended('dashboard');`
  `      }`
  `  }`

My **ldap_auth.username** is
`        'ldap' => [`

 `           'discover' => 'username',`

`            'authenticate' => 'password',`

`        ],`

I have changed field's name from **email** to **username** in view file. Can you please tell my what I am doing wrong here?

**Comment by stevebauman** [comment]
Hi @saurabh-mishrr,

You need to use Laravel's authentication facade, not Adldap. Calling `Adldap::auth()->attempt()` simply binds to your LDAP server. It does not authenticate you into your Laravel application.

Example:

```php
public function authenticate(Request $request)
{
    if (Auth::attempt($request->only('username', 'password')) {
        return redirect()->intended('dashboard');
    }
}
```

**Comment by saurabh-mishrr** [comment]
Thanks @stevebauman for your quick response.

> You need to use Laravel's authentication facade, not Adldap. Calling Adldap::auth()->attempt() simply binds to your LDAP server. It does not authenticate you into your Laravel application.

I've modified my `LoginController` as you suggested, but still it's giving me same error. 

> You mentioned that you changed your email input field to username in the login view file. Did you also do this on your users database table migration?

> You will also need to update the eloquent config option in config/ldap_auth.php to username as well.

Actually I'm using `NoDatabaseUserProvider`, So I don't think so I need to modify `eloquent` in `config/ldap_auth.php`. Though I have changed `ldap_auth.username.ldap.discover` as `username` and `ldap_auth.username.ldap.authenticate` as `password`.

For more understanding please find below mentioned details.
**.env**
`LDAP_HOSTS=IP GOES HERE`
`LDAP_BASE_DN='SOME TEXT GOES HERE'`

**auth.php**
`providers.username.driver = 'ldap'`
`model is commented because I'm not using eloquent`

Please find attached file, it has fields that we are using in ldap.

[ldap_fields.txt](https://github.com/Adldap2/Adldap2-Laravel/files/2775324/ldap_fields.txt)

for `.env's LDAP_BASE_DN`, I'm using `DistinguishedName` column from ldap.
for `username`, I'm using `UserPrincipalName` column from ldap.

**Comment by muzammilaskari** [comment]
@saurabh-mishrr did you solved this issue? Because I am facing the same problem which you faced a little while ago.
