### ISSUE TITLE
BindException Invalid credentials  in Guard.php 

### ISSUE THREAD

**Issue by legreco** [Adldap2/Adldap2-Laravel#472]
- Laravel Version: 5.4
- Adldap2-Laravel Version: 4.0.6.
- PHP Version: 7.0.10
- LDAP Type: Active Directory 

### Description:
when i try
```
 $user = \Adldap\Laravel\Facades\Adldap::search()->users()->first();

    dd($user);
```
i get the bind exception error

My adldap file
```
<?php

return [

    'connections' => [

        'default' => [

            'auto_connect' => env('ADLDAP_AUTO_CONNECT', true),
 

            'connection' => Adldap\Connections\Ldap::class,

     
            'schema' => Adldap\Schemas\ActiveDirectory::class,


            'connection_settings' => [
       

                'account_prefix' => env('ADLDAP_ACCOUNT_PREFIX', ''),

       

                'account_suffix' => env('ADLDAP_ACCOUNT_SUFFIX', ''),

          

                'domain_controllers' => explode(' ', env('ADLDAP_CONTROLLERS', 'mydomain.org')),

          
                'port' => env('ADLDAP_PORT', 389),

          

                'timeout' => env('ADLDAP_TIMEOUT', 5),


                'base_dn' => env('ADLDAP_BASEDN', 'OU=ou,DC=dc,DC=dc,DC=dc'),

         

                'admin_account_prefix' => env('ADLDAP_ADMIN_ACCOUNT_PREFIX', ''),
                'admin_account_suffix' => env('ADLDAP_ADMIN_ACCOUNT_SUFFIX', ''),

       

                'admin_username' => env('ADLDAP_ADMIN_USERNAME', 'username'),
                'admin_password' => env('ADLDAP_ADMIN_PASSWORD', 'password'),


                'follow_referrals' => false,

          

                'use_ssl' => env('ADLDAP_USE_SSL', false),
                'use_tls' => env('ADLDAP_USE_TLS', false),

            ],

        ],

    ],

];
```

NOTE 
1. the same configuration works with another project (with Adldap2-Laravel Version: 3.*)
1=>2 the username and the password are correct

**Comment by stevebauman** [comment]
Hi @legreco,

Only the `adldap_auth.php` configuration file was updated from Adldap2-Laravel v3.0. The `adldap.php` configuration file that contains your connection settings was not updated with this new release.

However, the `account_suffix` / `account_prefix` options operate differently when `null` is passed instead of an empty string.

What are you using as a username to bind to your LDAP server? For example, the `userPrincipalName`, the `sAMAccountName`, the `distinguishedName` etc.

**Comment by legreco** [comment]
Hi @stevebauman 
For binding i am using the sAMAccountName . 

My final goal is to be able to login users via their email (userprincipalname) and their ActiveDirectory password

When i make the correct changes in the adldap_auth.php file and login controller  i  cant login via email
with the password on Active directory, but i can login with the database password (login fallback true).
 
I think this happen because the the binding failed so it fallback to database authentication.

**Comment by stevebauman** [comment]
> For binding i am using the sAMAccountName .
> 
> My final goal is to be able to login users via their email (userprincipalname) and their ActiveDirectory password

Try binding with their `userprincipalname`. You won't be able to bind with their `samaccountname` unless you provide a domain prefix (for example `ACME\jdoe`).

There's three ways you can bind through Active Directory:

Type | Format
--- | ---
User Principal Name | `sbauman@acme.org`
Domain Level Log-on Name | `ACME\sbauman`
Full Distinguished Name | `cn=Bauman, Steve,ou=Users,dc=acme,dc=org`

**Comment by legreco** [comment]
when i put
```
 'admin_account_prefix' => null,
    'admin_account_suffix' => '@acme.org',
 'account_prefix' =>null,
 'account_suffix' => null,
 'admin_username' => 'sbauman',
  'admin_password' => 'password',
```
I am able to bind to the server because 
```
 $user = \Adldap\Laravel\Facades\Adldap::search()->users()->first();

    dd($user);
```
I can dd a user

but i still cant login via email
 my email is
 somethingbefore.sbauman@acme.org

My complete auth file
```
<?php

return [

  
    'connection' => 'default',


    'provider' => Adldap\Laravel\Auth\DatabaseUserProvider::class,

  
    'rules' => [

      
        Adldap\Laravel\Validation\Rules\DenyTrashed::class,

     

    ],


    'scopes' => [

     
        Adldap\Laravel\Scopes\UpnScope::class,

       

    ],

    'usernames' => [

      

        'ldap' => [

            'discover' => 'userprincipalname',

            'authenticate' => 'userprincipalname',

        ],

     

        'eloquent' => 'email',

      

        'windows' => [

            'discover' => 'samaccountname',

            'key' => 'AUTH_USER',

        ],

    ],

    'passwords' => [

     

        'sync' => false,

      

        'column' => 'password',

    ],

    

    'login_fallback' => false,

    

    'sync_attributes' => [

        'email' => 'userprincipalname',

        'first_name' => 'givenname',

    ],

  

    'logging' => [

        'enabled' => true,

        'events' => [

            \Adldap\Laravel\Events\Importing::class => \Adldap\Laravel\Listeners\LogImport::class,
            \Adldap\Laravel\Events\Synchronized::class => \Adldap\Laravel\Listeners\LogSynchronized::class,
            \Adldap\Laravel\Events\Synchronizing::class => \Adldap\Laravel\Listeners\LogSynchronizing::class,
            \Adldap\Laravel\Events\Authenticated::class => \Adldap\Laravel\Listeners\LogAuthenticated::class,
            \Adldap\Laravel\Events\Authenticating::class => \Adldap\Laravel\Listeners\LogAuthentication::class,
            \Adldap\Laravel\Events\AuthenticationFailed::class => \Adldap\Laravel\Listeners\LogAuthenticationFailure::class,
            \Adldap\Laravel\Events\AuthenticationRejected::class => \Adldap\Laravel\Listeners\LogAuthenticationRejection::class,
            \Adldap\Laravel\Events\AuthenticationSuccessful::class => \Adldap\Laravel\Listeners\LogAuthenticationSuccess::class,
            \Adldap\Laravel\Events\DiscoveredWithCredentials::class => \Adldap\Laravel\Listeners\LogDiscovery::class,
            \Adldap\Laravel\Events\AuthenticatedWithWindows::class => \Adldap\Laravel\Listeners\LogWindowsAuth::class,
            \Adldap\Laravel\Events\AuthenticatedModelTrashed::class => \Adldap\Laravel\Listeners\LogTrashedModel::class,

        ],
    ],

];
```

**Comment by stevebauman** [comment]
Can you check your logs and see what's in there after you trying logging in with your email?

Also, can you double check in your AD server that your `userPrincipalName` that you're using to login with is correct?

**Comment by legreco** [comment]
I try to search the user i was currently trying to login via email (userPrincipalName). with
```
$search = \Adldap\Laravel\Facades\Adldap::search()->where('samaccountname', '=', 'sbauman')->get();

    dd($search);
```
I find this user but i was surprised when i see the userprincipalname was sbauman@acme.org
because i  always thougth the userprincipalneme was the email .
I used sbauman@acme.org and login was ok
I take a look at the other attributes and i see a  'mail' attribute that was somethingbefore.sbauman@acme.org
I changed
```
 'ldap' => [

            'discover' => 'mail', //from userPrincipalName

            'authenticate' => 'mail', // from userPrincipalName

        ],
```
But i cant login with somethingbefore.sbauman@acme.org

**Comment by legreco** [comment]
@stevebauman 
after reading this issue
https://github.com/Adldap2/Adldap2-Laravel/issues/330

i put 
```
'ldap' => [

            'discover' => 'mail',

            'authenticate' => 'userprincipalname',

        ],
```
and everything is ok.
(i dont understand why putting both dicover and authenticate to mail doesnt work ).
Thanks a lot!

**Comment by stevebauman** [comment]
Hi @legreco, this is expected behavior with your user configuration you've shown above.

You want to use the `userprincipalname` as the authentication attribute because this attribute is allowed to be used as a username for binding against your AD server.

Since your `mail` attribute on the account you're logging in with isn't the same as their `userprincipalname`, their bind attempt against your server will be rejected, since it's not a valid attribute to bind with.

You want to use the `mail` attribute for the `ldap.discover` configuration option because this is the attribute you're using for users to actually log in with.

When you configure the `ldap.discover` option, your server is queried for a user with the `mail` attribute equal to what you enter in your login form. For your example, your server would be queried with the filter: `(mail=somethingbefore.sbauman@acme.org)`.

Once the user is located with that filter, then we can retrieve their `userprincipalname` for binding to your LDAP server.

Hope I'm making this clear enough, but as always if you have any further questions just give me a shout :smile:

Glad you've resolved your issue!

**Comment by legreco** [comment]
@stevebauman 
Thanks a lot, your explanation is very clear.

**Comment by ajeetverma59** [comment]
Hi , i am trying to implement ldap with laravel 5.4 but its not working. can u please share complete configration code.
thanks
