### ISSUE TITLE
Filters values are not raw

### ISSUE THREAD

**Issue by roycetest** [Adldap2/Adldap2-Laravel#473]
- Laravel Version: 5.6
- Adldap2-Laravel Version: 4.0
- PHP Version: 7.1
- LDAP Type: OpenLDAP? -

Description:

When I try to autheticate using Laravel I see the LDAP filters are hex encoded and not RAW.
I am trying to find a way to configure either Laravel or adldap2-laravel to always use RAW and not use hex encoding for values.

Steps To Reproduce:

Just configure Laravel to use adldap2-lararvel and login with valid LDAP user

**Comment by stevebauman** [comment]
Hi @roycetest,

The reason they are not raw is for your protection. Allowing this to be configurable globally would be a bad idea.

Is there a reason you're wanting to disable escaping values?

If you're looking to use raw filters and values, you can use the following methods:

```php
// whereRaw
Adldap::search()->whereRaw('cn', '=', 'jdoe')->get();

// orWhereRaw
Adldap::search()->orWhereRaw('cn', '=', 'jdoe')->get();

// rawFilter
Adldap::search()->rawFilter('(cn=jdoe)')->get();
```

**Comment by roycetest** [comment]
Thanks, after digging and digging.... I am now able to use adldap2-laravel to work properly.
