### ISSUE TITLE
OnlyImported rule seems to always return true for DatabaseUserProvider

### ISSUE THREAD

**Issue by fitztrev** [Adldap2/Adldap2-Laravel#474]
- Laravel Version: 5.5.34
- Adldap2-Laravel Version: 4.0.6
- PHP Version: 7.2
- LDAP Type: Active Directory
- Provider set in config: `Adldap\Laravel\Auth\DatabaseUserProvider::class`

### Description:

I'm trying to have it so that only accounts that I manually import are able to login. When I enable the `OnlyImported` rule, it's always returning `true`, though.

I tried to figure out what's happening. If I am incorrect in my assumption of how this *is* working or *should* work, just let me know and I'll try to figure out another way to accomplish it.

### Details:

1. It appears `retrieveByCredentials()` is run before `validateCredentials()`.
2. `retrieveByCredentials()` is what imports a user and syncs the local users table.
3. `validateCredentials()` then checks against any rules, including `OnlyImported`
4. The user model exists because of step 2, so `OnlyImported` is always going to return true

### Steps To Reproduce:

Provider set in config: `Adldap\Laravel\Auth\DatabaseUserProvider::class`

I have an empty users table. I do not run any import commands. With the `OnlyImported` rule applied, I am still able to login and a record is created in my local users table.

**Comment by stevebauman** [comment]
Hi @fitztrev,

I would try flushing your configuration cache and try again with an empty users table (`php artisan config:clear`).

> The user model exists because of step 2, so `OnlyImported` is always going to return true

This isn't the case, as the model is only saved **after** all rules pass in validation:

https://github.com/Adldap2/Adldap2-Laravel/blob/master/src/Auth/DatabaseUserProvider.php#L131-L140

This rule only checks that the model exists, which will not be true if the rule is enabled properly:

https://github.com/Adldap2/Adldap2-Laravel/blob/master/src/Validation/Rules/OnlyImported.php

The model will exist if the user is imported via `php artisan adldap:import`.

Can you give the suggested fixes a try and see if it resolves your issue?

**Comment by fitztrev** [comment]
@stevebauman Thank you very much. Everything is working great now.

**Comment by stevebauman** [comment]
Awesome @fitztrev! Glad it's resolved :smile:

No problem at all.
