### ISSUE TITLE
NoDatabaseUserProvider - byCredentials returns null

### ISSUE THREAD

**Issue by WisienDot** [Adldap2/Adldap2-Laravel#475]
- Laravel Version: 5.5
- Adldap2-Laravel Version: 4.0
- PHP Version: 7.1
- LDAP Type: Active Directory

### Description:
I would like to make use of NoDatabaseUserProvider and authenticate users through the AD server. Currently I'm facing and issue with `byCredentials` method in `Adldap\Laravel\Resolvers\UserResolver` class. When discover & authenticate usernames are set to `userprincipalname` this method returns no results and therefore I cannot authenticate a user.

### Steps To Reproduce:
I did some debug of the package and it looks like user retrieve is not working correctly:
`$this->query()->whereEquals($field, $username)->first()`
During debugging I tried to use a facade to achieve the same goal and in such a case everything seems to work fine:
`\Adldap\Laravel\Facades\Adldap::search()->users()->whereEquals($field, $username)->first()`
This is strange because a dump of the Builder object looks exactly the same, but gives totally different result. 

**Facade:**
`
Builder {#281 ▼
  +columns: array:1 [▶]
  +filters: array:3 [▼
    "and" => array:3 [▼
      0 => array:3 [▼
        "field" => "objectclass"
        "operator" => "="
        "value" => "\70\65\72\73\6f\6e"
      ]
      1 => array:3 [▼
        "field" => "objectcategory"
        "operator" => "="
        "value" => "\70\65\72\73\6f\6e"
      ]
      2 => array:3 [▼
        "field" => "userprincipalname"
        "operator" => "="
        "value" => "..."
      ]
    ]
    "or" => []
    "raw" => []
  ]
  +limit: 0
  +paginated: false
  #sortByField: ""
  #sortByDirection: ""
  #sortByFlags: null
  #dn: "..."
  #type: "search"
  #raw: false
  #nested: false
  #connection: Ldap {#262 ▶}
  #grammar: Grammar {#279}
  #schema: ActiveDirectory {#263}
}
`

**Original solution:**
`
Builder {#279 ▼
  +columns: array:1 [▶]
  +filters: array:3 [▼
    "and" => array:3 [▼
      0 => array:3 [▼
        "field" => "objectclass"
        "operator" => "="
        "value" => "\70\65\72\73\6f\6e"
      ]
      1 => array:3 [▼
        "field" => "objectcategory"
        "operator" => "="
        "value" => "\70\65\72\73\6f\6e"
      ]
      2 => array:3 [▼
        "field" => "userprincipalname"
        "operator" => "="
        "value" => "..."
      ]
    ]
    "or" => []
    "raw" => []
  ]
  +limit: 0
  +paginated: false
  #sortByField: ""
  #sortByDirection: ""
  #sortByFlags: null
  #dn: "..."
  #type: "search"
  #raw: false
  #nested: false
  #connection: Ldap {#262 ▶}
  #grammar: Grammar {#278}
  #schema: ActiveDirectory {#263}
}
`
### My current setup:
**adldap_auth.php**
`
        'ldap' => [
            'discover' => 'userprincipalname',
            'authenticate' => 'userprincipalname',
        ],
`
` 'provider' => Adldap\Laravel\Auth\NoDatabaseUserProvider::class,`
**auth.php**
`
    'providers' => [
        'users' => [
            'driver' => 'adldap',
        ],
`

Does anyone have any idea what is happening?

**Comment by stevebauman** [comment]
Hi @WisienDot,

What are you using as the name of the username field on your login form?

**Comment by stevebauman** [comment]
Also, can you debug and see what the `$field` and `$username` attributes are equal to here?:

https://github.com/Adldap2/Adldap2-Laravel/blob/master/src/Resolvers/UserResolver.php#L80

**Comment by WisienDot** [comment]
Hello @stevebauman,
Field name is "email" but I'm mapping that to "userprincipalname" at the level of my loginController.

$field = "userprincipalname";
$username = "my correct email address from the input"

**Comment by stevebauman** [comment]
Ok, can you verify that the `base_dn` you've set in your `adldap.php` configuration file is correct?

This may be why you aren't receiving results. If the `base_dn` is incorrect, you won't receive any search results.

**Comment by WisienDot** [comment]
It's working correctly for the facade so I assume that base_dn is correct.

**Comment by WisienDot** [comment]
This:
`\Adldap\Laravel\Facades\Adldap::search()->users()->whereEquals($field, $username)->first()`
returns:
`
User {#278 ▼
  +exists: true
  #query: Builder {#281 ▶}
  #schema: ActiveDirectory {#263}
  #modifications: []
  +dateFormat: "Y-m-d H:i:s"
  #timestampFormat: "YmdHis.0Z"
  #attributes: array:70 [▶]
  #original: array:70 [▶]
}
`
While this:
`$this->query()->whereEquals($field, $username)->first()`
returns:
`
null
`

**Comment by stevebauman** [comment]
Ok hmm... Do you have any `scopes` you've added into the `adldap_auth.php` configuration file?

**Comment by WisienDot** [comment]
No scopes defined.

**Comment by stevebauman** [comment]
Can you clear your configurations cache to triple check using `php artisan config:clear`?

**Comment by WisienDot** [comment]
Still doesn't work. The only difference that I noticed in Builder setup is Ldap connection bound set to false for original solution while for faced it's set to true.

**Comment by stevebauman** [comment]
That means that you're not actually connected to your LDAP server.

Can you post your configs with sensitive details omitted and make sure you're able to retrieve LDAP search results outside of authentication? Such as creating a web route and simply dumping search results?

**Comment by WisienDot** [comment]
Already tried using faced in the web route file and it works just fine.
`Adldap::search()->users()->whereEquals('userprincipalname', $username)->first();`

**Comment by WisienDot** [comment]
Output of the query from we route:
`
User {#158 ▼
  +exists: true
  #query: Builder {#160 ▶}
  #schema: ActiveDirectory {#153}
  #modifications: []
  +dateFormat: "Y-m-d H:i:s"
  #timestampFormat: "YmdHis.0Z"
  #attributes: array:70 [▶]
  #original: array:70 [▶]
}
`
What configuration would you like to see?

**Comment by WisienDot** [comment]
I found the configuration mistake. I set the auto_connect flag to false at the initial state of this project to avoid issues on docker boot (I had no admin credentials at that time). What a silly issue - sorry for bothering you at all but I was a bit frustrated after few days of debugging. 

Thanks for all you help and time. This is a really helpful library - great job!

**Comment by stevebauman** [comment]
Awesome, glad you've resolved it, appreciate your quick follow up :)

Thanks for the kind words!

**Comment by groundbreaker08** [comment]
Hi @stevebauman , thank you for replying. I was able to retrieve all the attributes using search and it seems there is a mail attribute. 

![image](https://user-images.githubusercontent.com/8444947/36803647-1d0477b8-1cf3-11e8-9a83-1247373ec369.png)
Also tried emailAddress but still getting a null value.
