### ISSUE TITLE
Missing 'mail' in the AD data

### ISSUE THREAD

**Issue by mbarlund** [Adldap2/Adldap2-Laravel#476]
- Laravel Version: 5.5
- Adldap2-Laravel Version: 3.*
- PHP Version: 7.0
- LDAP Type: Active Directory

### Description:
The packages is working fine but then I realized the `userprincipalname` was not the email address desired. The desired one is `mail` but that field is not returned with the data.

I'm using the ActiveDirectory schema but only getting about 31 attributes and `mail` is not one of them.

Is there a setting I am missing or is this an issue with the ActiveDirectory config? The field does exist though and is populated. 

Thanks in advance!

**Comment by stevebauman** [comment]
Hi @mbarlund, by default, Adldap2 returns all attributes given by the server.

Can you provide a screenshot (with sensitive details omitted) that shows the `mail` attribute set on your AD user that you're trying to log in with?

**Comment by mbarlund** [comment]
The app is authenticating and then storing the `sync_attributes` but `mail` is `null`. 

I did discover that I get different results based on there I run the following:
`$search = \Adldap::search()->where('samaccountname', '=', 'mbarlund')->get();`

Notice when this is run from Resolver.php the attributes array contains 107 items where as Importer.php returns only 65. The search from Resolver.php gives me the mail attribute. But Importer.php is where the sync is happening but no `mail`.

vendor/adldap2/adldap2-laravel/src/Auth/Resolver.php
![adresolver](https://user-images.githubusercontent.com/229608/35958534-168c935a-0c56-11e8-8497-e2bc6e5276df.JPG)

vendor/adldap2/adldap2-laravel/src/Auth/Importer.php
![adimporter](https://user-images.githubusercontent.com/229608/35958538-20fee252-0c56-11e8-8721-1bc49f53e20f.JPG)

**Comment by stevebauman** [comment]
Are you sure these two objects shown in the pictures are the exact same? Can you validate that they have identical distinguished names?

**Comment by mbarlund** [comment]
Well I am unable to replicate this issue now. Repeating the above returned the same data both times.
And `mail` is being returned and syncing on login.

Moving on - thanks for listening :)
