### ISSUE TITLE
Login attempts to create a new database entry each time (Duplicate entry error)

### ISSUE THREAD

**Issue by thill0822** [Adldap2/Adldap2-Laravel#477]
- Laravel Version: 5.2
- PHP Version: 7.1
- LDAP Type: Active Directory

### Description:
The first time I log in, it's working fine. I can then log out and try and log in again, but I get an error: 

```
QueryException in Connection.php line 729:
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '' for key 'users_username_unique' (SQL: insert into `users` (`name`, `updated_at`, `created_at`) values (john doe, 2018-02-07 15:38:56, 2018-02-07 15:38:56))
```

I've noticed it's creating an entry in the users table of the database and syncing the name from the LDAP information, which is what we want. 

If I delete that database entry, it'll allow me to log in again, so if looks like it's trying to add a new entry every time rather than check for an existing entry first. 

Shouldn't it be checking for an existing entry first? What am I missing?

**Comment by stevebauman** [comment]
Hi @thill0822, from the error you posted, it looks like no username is inserted into the user. Since you're using usernames to authenticate, did you update your `sync_attributes` in your `adldap_auth.php` file?

For example:

```php
'syc_attributes' => [
    // This 'username' key must be present to sync
    // users correctly with your configuration.
    'username' => 'samaccountname',

    'name' => 'cn',
],
```

**Comment by stevebauman** [comment]
Also, if you're by chance using Postgre as your SQL database, you'll need to `strtolower()` your usernames **before** authentication, as Postgre is by default **case sensitive**.

For example, these usernames would cause issues since they have different casing, and a new user would be created for each (this is a Postgre issue, not Laravel or Adldap2 related):

- johndoe
- jOHNdoe
- Johndoe
- johnDOE

**Comment by thill0822** [comment]
@stevebauman found it! The `username` wasn't set in the `sync_attributes`. All is working correctly now.

Thanks!

**Comment by stevebauman** [comment]
Awesome, no problem @thill0822! Glad you've resolve it. Appreciate the quick response :)
