### ISSUE TITLE
Adldap Import User Attributes

### ISSUE THREAD

**Issue by ZacNespral21** [Adldap2/Adldap2-Laravel#478]
- Laravel Version: 5.5
- Adldap2-Laravel Version: 4.0
- PHP Version: 7.0
- LDAP Type: Active Directory

### Description:

I used the php artisan adldap:import command to import all ldap users and I could successfully login so everything works with the exception I am unable to sync in all the user attributes from ldap, for example I need to get the "department" for each user. I am able to get the department for the user once he logs in via the getAttributes() but I need it during the import/sync command. I went through the documentation but wasn't able to find anything on importing user attributes. What am I missing?

**Comment by stevebauman** [comment]
Hi @ZacNespral21, please fill out the version information that is provided in the issue template. I need it to help you with your issue.

Once it is filled, I will re-open this issue.

**Comment by ZacNespral21** [comment]
Hi @stevebauman I updated my version information, my apologies I thought I put that in there...

**Comment by stevebauman** [comment]
@ZacNespral21 No problem.

Here is the documentation for importing user attributes:

https://github.com/Adldap2/Adldap2-Laravel/blob/master/docs/auth.md#syncing-attributes

You need to edit the `sync_attributes` array in your `adldap_auth.php` file.

If you run into any issues, please let me know, thanks!

**Comment by ZacNespral21** [comment]
@stevebauman Wow I don't know how I missed that, I got it working perfectly! Thanks!

**Comment by stevebauman** [comment]
No problem! Thanks for the quick follow up :)
