### ISSUE TITLE
Authenticate using mail and password

### ISSUE THREAD

**Issue by krunaladaptit** [Adldap2/Adldap2-Laravel#479]
- Laravel Version: 5.5
- Adldap2-Laravel Version: 4.0
- PHP Version: 7.1.12
- LDAP Type: Active Directory

### Description:
I want to authenticate using mail and password instead of username and password.
So do we have any document for it?

**Comment by ChristopheAupet** [comment]
Do you have a config/adldap_auth.php ? If you do not please check Providers section of the documentation, it will allow you to chose authentication parameters and so on.

**Comment by pmirandaarias** [comment]
There you have to use something like:

    'sync_attributes' => [
        'email' => 'userprincipalname',
        'name' => 'cn',
    ]

**Comment by stevebauman** [comment]
Hi @krunaladaptit, as @ChristopheAupet has mentioned, please read the setup page for authentication providers:

https://github.com/Adldap2/Adldap2-Laravel/blob/master/docs/auth.md#basic-setup
