### ISSUE TITLE
ErrorException : Undefined index: samaccountname with NoDatabaseUserProvider

### ISSUE THREAD

**Issue by karakayasemi** [Adldap2/Adldap2-Laravel#480]
- Laravel Version: 5.5.34 
- Adldap2-Laravel Version: 4.0.6
- PHP Version: 7.2
- LDAP Type: Active Directory

### Description:
I am getting following error with trying to authenticate with NoDatabaseUserProvider.

ErrorException : Undefined index: samaccountname
…/vendor/adldap2/adldap2-laravel/src/Resolvers/UserResolver.php73

I checked the $credentials array, it has only username and password array keys. I did not understand why we are trying to find samaccountname key. By the way, samaccountname is my LDAP discover attribute.

### Steps To Reproduce:
Try Laravel auth with NoDatabaseUserProvider by setting discover attribute as samaccountname.

**Comment by stevebauman** [comment]
Hi @karakayasemi,

With the `NoDatabaseUserProvider`, the `ldap.discover` attribute is also the key to retrieve the users username from the credentials array, for example, try using:

```php
$credentials = [
    'samaccountname' => $request->username,
    'password' => $request->password,
];

if (Auth::attempt($credentials)) {
    //
}
```

This should resolve your issue.

**Comment by stevebauman** [comment]
If you're using stock Laravel auth controllers, you'll need to extend the `username()` method in your `LoginController` and change your HTML input name of your `username` field to `samaccountname` for example:


```php
// LoginController.php

public function username()
{
    return 'samaccountname';
}
```

```hmtl
<input type="text" name="samaccountname">
```

I know the documentation is lacking right now in this respect, and I'm working to update them soon so it'll be much easier to work with.

**Comment by karakayasemi** [comment]
Thanks @stevebauman, the error has disappeared, now login fails but it is not showing any errors. I believe I will succeed eventually :).

**Comment by karakayasemi** [comment]
I guess we should keep open this issue until the documentation updated.

**Comment by stevebauman** [comment]
> I guess we should keep open this issue until the documentation updated.

Yea I agree, thanks for the prompt response!

**Comment by karakayasemi** [comment]
@stevebauman I checked, I am sure that my LDAP connection setting is working, I can take information of a user from LDAP server. But Laravel login does not work even though I have entered the correct password. It is giving credentials error. "These credentials do not match our records.". Is there anything that I forget to authenticate with NoDatabaseUserProvider.

**Comment by stevebauman** [comment]
Can you post your configuration files with sensitive details omitted?

**Comment by ChristopheAupet** [comment]
+1 i have the same issue. I link you my "config/adldap.php", "config/adldap_auth.php" and my "config/auth.php" do you need some more informations ?

[adldap_auth.txt](https://github.com/Adldap2/Adldap2-Laravel/files/1737405/adldap_auth.txt)
[auth.txt](https://github.com/Adldap2/Adldap2-Laravel/files/1737406/auth.txt)
[adldap.txt](https://github.com/Adldap2/Adldap2-Laravel/files/1737409/adldap.txt)

**Comment by syphernl** [comment]
I've been working on upgrading one of our apps to Laravel 5.6 and also the latest version of Adldap2-Laravel. However, I'm faced with the very same issue here.

Following the `samaccountname` key change resulted in fixing the Undefined index error but users cannot login like @karakayasemi described.

Here is the topmost part of the logs (let me know if you need the whole) but hopefully it points you in the right direction!

```
[2018-03-26 15:25:52] local.ERROR: Adldap\Auth\BindException: Invalid credentials in /vagrant/vendor/adldap2/adldap2/src/Auth/Guard.php:85
Stack trace:
#0 /vagrant/vendor/adldap2/adldap2/src/Auth/Guard.php(98): Adldap\Auth\Guard->bind('ADMINUSERHERE', 'ADMINPASSWORDHERE', '', '')
#1 /vagrant/vendor/adldap2/adldap2/src/Connections/Provider.php(225): Adldap\Auth\Guard->bindAsAdministrator()
#2 /vagrant/vendor/adldap2/adldap2-laravel/src/AdldapServiceProvider.php(100): Adldap\Connections\Provider->connect()
```

The credentials that are being used _are_ valid as they are currently being used by the app running in production on an older version of Adldap2/Adldap2-Laravel.

**Comment by oguzoztinaz** [comment]
Hi, I had that error before too. I had changed my username attribute as "samaccountname" and I had my error disappear but still couldn't login just as @karakayasemi did. However, after I had changed "bind_users_by" attribute in ldap_auth.php file as "samaccountname" as well, and it worked. You can try that.

**Comment by karakayasemi** [comment]
Looks like @oguzoztinaz solution works. Closing the issue favor of it.
