### ISSUE TITLE
Attempt passes, but search returns null

### ISSUE THREAD

**Issue by cbloss** [Adldap2/Adldap2-Laravel#481]
- Laravel Version: 5.5
- Adldap2-Laravel Version: 4.06
- PHP Version: 7.2
- LDAP Type: Active Directory

### Description:
I am able to use attempt to login, but when I use the login form, it won't create a new users. I started with a fresh install of Laravel because I thought I was slamming my head on an existing app. I'm using this package on several other but it seems like the latest updates is throwing me for a loop. 

### Steps To Reproduce:
Like I said, I have a fresh install. I've changed all my env variables to what I'm using previously. I try to login, and I get bounced back with a "These credentials do not match our records.". If I use Adldap::auth(), it works. It's like I cannot create a user. I am using email and not username

These were the only env variables that I changed: 
```
ADLDAP_ADMIN_USERNAME=xxx
ADLDAP_ADMIN_PASSWORD=xxx
ADLDAP_CONTROLLERS=xx
ADLDAP_ADMIN_ACCOUNT_SUFFIX=xxx
ADLDAP_BASEDN=xxx
ADLDAP_PASSWORD_SYNC=true
```
I have a completely blank Users table. I'm at a lost as to what to do. Any clue?

THANKS!

**Comment by cbloss** [comment]
Nevermind! I was missing a couple of settings. >_< Sorry!

**Comment by stevebauman** [comment]
No problem! Thanks for the quick update :)
