### ISSUE TITLE
No model is configured. You must configure a model to use with the [Adldap\Laravel\Auth\DatabaseUserProvider].

### ISSUE THREAD

**Issue by pmirandaarias** [Adldap2/Adldap2-Laravel#483]
I'm getting this error:

```
No model is configured. You must configure a model to use with the [Adldap\Laravel\Auth\DatabaseUserProvider].

in AdldapAuthServiceProvider.php (line 90)

at AdldapAuthServiceProvider->newUserProvider(object(BcryptHasher), array('driver' => 'adldap', 'table' => 'User::class'))
in AdldapAuthServiceProvider.php (line 37)
```

Any idea?

I have in auth.php:

    'providers' => [
         'users' => [
             'driver' => 'adldap',
             'table' => 'User::class',
         ],
    ],

And in adldap_auth.php:

    'provider' => Adldap\Laravel\Auth\DatabaseUserProvider::class,

**Comment by stevebauman** [comment]
Hi @pmirandaarias, you're using the wrong array key for specifying your model.

Also, you can't use class constants in single quoted strings.

It should be:

```php
'providers' => [
     'users' => [
         'driver' => 'adldap',
         'model' => User::class,
     ],
],
```
