### ISSUE TITLE
Auth ldap do not match our records

### ISSUE THREAD

**Issue by happskiy** [Adldap2/Adldap2-Laravel#484]
- Laravel Version: 5.2.45
- Adldap2-Laravel Version: 4.0.6
- PHP Version: 7.0.27
- LDAP Type: Active Directory

### Description:
Hi Steve, I started with a simple - [quick-start.md](https://github.com/Adldap2/Adldap2-Laravel/blob/master/docs/quick-start.md#quick-start---from-scratch)

Import of users is ok
My problem with web authorization - "These credentials do not match our records."
I tested two simple, and one new user, through `Adldap::auth()->attempt('euler', 'password')`

`Psy Shell v0.7.2`
`---> Adldap::auth()->attempt('ldaptest', 'Password')`
`---> true`

Laravel log:
`local.INFO: User 'ldaptest' has been successfully found for authentication`
`local.INFO: User 'ldaptest' is being synchronized.`
`local.INFO: User 'ldaptest' has been successfully synchronized.`
`local.INFO: User 'ldaptest' is authenticating with username: 'CN=ldaptest,CN=Users,DC=mydomain,DC=test'`
`local.INFO: User 'ldaptest' has failed LDAP authentication.`

Steve, please help with the solution to this problem...

### Steps To Reproduce:
adldap.php:
``<?php

return [

    'connections' => [
        'default' => [
            'auto_connect' => env('ADLDAP_AUTO_CONNECT', true),
            'connection' => Adldap\Connections\Ldap::class,
            'schema' => Adldap\Schemas\ActiveDirectory::class,
            'connection_settings' => [
                'account_prefix' => env('ADLDAP_ACCOUNT_PREFIX', ''),
                'account_suffix' => env('ADLDAP_ACCOUNT_SUFFIX', '@mydomain.test'),
                'domain_controllers' => explode(' ', env('ADLDAP_CONTROLLERS', 'mydomainctrls')),
                'port' => env('ADLDAP_PORT', 389),
                'timeout' => env('ADLDAP_TIMEOUT', 5),
                'base_dn' => env('ADLDAP_BASEDN', 'CN=Users,DC=mydomain,DC=test'),
                'admin_account_prefix' => env('ADLDAP_ADMIN_ACCOUNT_PREFIX', ''),
                'admin_account_suffix' => env('ADLDAP_ADMIN_ACCOUNT_SUFFIX', '@mydomain.test'),
                'admin_username' => env('ADLDAP_ADMIN_USERNAME', 'domian admin'),
                'admin_password' => env('ADLDAP_ADMIN_PASSWORD', 'admin_password'),
                'follow_referrals' => true,
                'use_ssl' => env('ADLDAP_USE_SSL', false),
                'use_tls' => env('ADLDAP_USE_TLS', false),

];

adldap_auth.php:
[adldap_auth.txt](https://github.com/Adldap2/Adldap2-Laravel/files/1727824/adldap_auth.txt)

**Comment by stevebauman** [comment]
Hi @happskiy, can you change your `ldap.authenticate` attribute to `samaccountname` and try again?

**Comment by stevebauman** [comment]
For example:

```php
// adldap_auth.php
'ldap' => [

    'discover' => 'userprincipalname',

    'authenticate' => 'samaccountname' // <- Here

],
```

**Comment by happskiy** [comment]
It's working! You are awesome! Thank you)

**Comment by stevebauman** [comment]
Awesome, glad you're up and running.

Thanks for your kind word @happskiy! Appreciate it :)
