### ISSUE TITLE
Suddenly stop seeing AD users on import

### ISSUE THREAD

**Issue by pmirandaarias** [Adldap2/Adldap2-Laravel#486]
- Laravel Version: 5.4
- Adldap2-Laravel Version: 4
- PHP Version: 7
- LDAP Type: Active Directory

I was importing users without problem till few days, and after a git pull I can't see them anymore. When I use:

`php artisan adldap:import`

I got a `Found 0 user(s).` message.

But when I test in the Login with:

`dd(\Adldap::auth()->attempt(str_replace('@xxx.cl', '', $request->email), $request->password));`

(I do that `str_replace` on the email because the AD config needs `sammaaccount` which is only the first part of the email).

I get `true` when the user comes from AD and `false` when was only created in my system and not imported. Actually, I cant try to login with credentials that exists in AD and not in my system and I got `true` also which is correct. So I don't understand if my configs are ok, why I'm getting 0 users found now.

I've tested changing and removing the `ADLDAP_ACCOUNT_SUFFIX` from both `.env` and `app.php` config files and nothing changes.

EDIT: Sorry, I'm new on AD and stuff. I tried from command line the command 

```
[root@xxx]# ldapsearch
ldap_sasl_interactive_bind_s: Can't contact LDAP server (-1)
```
Eh, that means is a AD issue and not mine?

**Comment by stevebauman** [comment]
Hi @pmirandaarias,

> ldap_sasl_interactive_bind_s: Can't contact LDAP server (-1)

This would definitely indicate that your app server cannot contact your LDAP server.

Sounds like you may have changed something in your configuration files. I would double check your git history and see what may have been modified, since it was working previously.

**Comment by stevebauman** [comment]
Unless of course, your AD server is down and it simply can't be contacted.

**Comment by pmirandaarias** [comment]
Ok, but that command is away from my Laravel system, and I haven't touched other files than Laravel config. But ok, I will check all again, thanks @stevebauman

**Comment by pmirandaarias** [comment]
Ok, was my fault. I had `false` the 'auto_connect' value in adldap.php. With `true` I can retrieve all the users from LDAP.

**Comment by stevebauman** [comment]
Thanks for the update @pmirandaarias!

I'm working on brand new docs, so this will be much clearer in the future :)
