### ISSUE TITLE
change objectClass value

### ISSUE THREAD

**Issue by groundbreaker08** [Adldap2/Adldap2-Laravel#489]
- Laravel Version: 5.6
- Adldap2-Laravel Version:  4.0
- PHP Version: 7.2
- LDAP Type: Active Directory

### Description:
I am having a problem signing in because of the target objectClass = person. i dont get all users from our directory if I dont change it to our specific objectClass value.

Can we change objectClass = person to "myValuePerson" (without quotes)? I saw about person_filter but I tried it here in config but it states that it doesnt have any support for it. 

### Steps To Reproduce:
$query = Adldap::search()->users()->get();

Just tried this query and dont get any from our directory because the objectClass is person (in hex)
![image](https://user-images.githubusercontent.com/8444947/36722215-ed0d2ce6-1be7-11e8-8353-1f09945bbbcb.png)

I can get values if I remove users() from the query. Unfortunately I dont want to modify codes from the vendor so I'm looking for other ways to change its value.

I can confirm that my base_dn is working. I tried to make a simple php functions using basic ldap methods and I can get results using my valid email and pass.

**Comment by groundbreaker08** [comment]
Sorry. I think I misunderstood something here. 
I tried using person as my value in my plain php code and it worked there.

Really having a hard time why the filters (search()->users()->where('email',$emamil)->first())wont work during my login attempt. 
But whenever I query (search()->where('mail',$email)->first()) i can get result.

**Comment by stevebauman** [comment]
Hi @groundbreaker08,

You'll need to use a custom schema and override the `objectClassPerson()` method and return your users normal object class attribute name:

https://github.com/Adldap2/Adldap2/blob/master/src/Schemas/ActiveDirectory.php#L63-L69

Once you've created your own schema class that has overriden this method, insert it into your `adldap.php` configuration file:

https://github.com/Adldap2/Adldap2-Laravel/blob/master/src/Config/config.php#L75

Closing this but if you need further assistance give me a shout and I'll open this back up :)

**Comment by groundbreaker08** [comment]
Hi @stevebauman ,

I made some progress here, you were right. I need to create some custom schema. and i override values for filtering then there's a result from the query i never got before.

However, my problem now is even i get a return value from byCredential method, i still can't authenticate.

**Comment by groundbreaker08** [comment]
I confirmed that there were no objectCategory on the filter used. The problem was 
$user instanceof User is getting a false value since the query return an instance of Entry.

Is this a bug? or because there were no objectCategory that is why it can't read that it is an instance of User? 
if that would be the case, is there any way i can override this because i checked all the attributes returned from the server and there is no objectCategory.

**Comment by groundbreaker08** [comment]
This was solved by creating a custom schema and applying to your provider in adldap_auth.php

Note: When i created a custom schema, I placed it in inside the config folder.

**Comment by groundbreaker08** [comment]
Changing of schema of ActiveDirectory to OpenLdap  fixed the issue.

**Comment by stevebauman** [comment]
Hi @groundbreaker08, you specified in the above issue you are running ActiveDirectory?

> LDAP Type: Active Directory

This would by why I was confused at your issue lol.

**Comment by groundbreaker08** [comment]
Hi @stevebauman  , yes at first I run it on ActiveDirectory. Sorry. I think i mixed up the issues here! but to be specific, my problem in changing values for objectClass was resolve by having a custom schema.
