### ISSUE TITLE
Retrieving all groups and sub-groups for a user

### ISSUE THREAD

**Issue by thill0822** [Adldap2/Adldap2-Laravel#491]
Laravel Version: 5.2
PHP Version: 7.1
LDAP Type: Active Directory

### Description:

I have a user who is a member of a group. That group is in turn a member of several other groups. 

If I use `Adldap ::search()->where('cn', '=', 'username')->get()` to retrieve a user, I'm only seeing the top level group that they are a member of. Is there an easy way to drill down into the user's groups to see the full list of member groups as well?

**Comment by stevebauman** [comment]
Hi @thill0822,

There's a couple ways you can do this. If you simply want **all** groups the user is apart of, then you will need to use the `getGroups()` method on the returned user and supply a second argument to indicate you want groups of groups (recursive) included in the results.

Here's an example:

```php
$user = Adldap::search()->users()->where('cn', '=', 'jdoe')->first();

// Single level groups
$groups = $user->getGroups();

// All Nested groups
$groups = $user->getGroups($fields = ['*'], $recursive = true);
```

Or, retrieve the group and then call `getGroups()` on that instance:

```php
$user = Adldap::search()->users()->where('cn', '=', 'jdoe')->first();

foreach ($user->getMemberOf() as $dn) {
    $group = Adldap::search()->findByDn($dn);

    $groups = $group->getGroups();
}
```

Hope this answers your question! If not, leave a comment and I'll re-open this issue.

**Comment by thill0822** [comment]
That's worked great, thanks @stevebauman!
