### ISSUE TITLE
Returns an instance of Entry but needs an instance of User

### ISSUE THREAD

**Issue by groundbreaker08** [Adldap2/Adldap2-Laravel#493]
- Laravel Version: 5.6
- Adldap2-Laravel Version: 4.0
- PHP Version: 7.2
- LDAP Type: EDIT - OpenLDAP

### Description:
After confirming that there were no objectCategory on the filter used. (my search in ldap doesnt need objectCategory that's why it was removed)
Found out that the problem was $user instanceof User is getting a false value since the query return an instance of Entry.

It says here that this really returns a value in an instance of Entry
![image](https://user-images.githubusercontent.com/8444947/36830018-b97c3996-1d5c-11e8-9a73-cd146a0b49cb.png)

### Steps To Reproduce:
We need to create a custom schema and run this in our terminal to show the die we placed temporarily on the method. 
I want to search using email and an objectClass of person. The valid ldap search i used before needs a mail attribute.

`  public function objectClassPerson()
   {
      return "somePerson";
   }

    public function objectCategoryPerson()
    {
        return 'somePerson';
    }

    public function objectCategory()
    {
        return 'objectclass';
    }

    public function employeeId()
    {
        return 'uid';
    }

    public function commonName()
    {
        return 'cn';
    }

    public function anr()
    {
        return 'mail';
    }

    public function userId()
    {
        return 'uid';
    }`

`php artisan adldap:import someEmail`

**Comment by stevebauman** [comment]
This sounds like you're not using ActiveDirectory. What LDAP variant are you using?

**Comment by groundbreaker08** [comment]
Hi @stevebauman . just updated the LDAP type usage. and yes. it's not ActiveDirectory. and referred also this issue to #21

**Comment by lyustiz** [comment]
Laravel Version: 5.6
adldap2/adldap2-laravel Version: 4.0
PHP Version: 7.2
Schema: Adldap\Schemas\OpenLDAP::class,

file: vendor\adldap2\adldap2-laravel\src\Resolvers\UserResolver.php
function byCredentials();
line:
`return $this->query()->whereEquals($field, $username)->first();`
Error: always return false

Cause: 
file: vendor\adldap2\adldap2\src\Schemas\OpenLDAP.php
don't read param objectClassPerson() ->'inetorgperson'
instead, read the param from:
file: \vendor\adldap2\adldap2\src\Schemas\BaseSchema.php 
objectClassPerson() ->'person'

sorry for my English.

**Comment by stevebauman** [comment]
Hi @groundbreaker08, you need to use the `OpenLDAP` schema in your `adldap.php` configuration file.

> It says here that this really returns a value in an instance of Entry

This comment wasn't meant to be taken literally in the context of Adldap2 Model classes. I use the word "entry" in many comments throughout the code to refer to raw LDAP records. Even still, the `Entry` model is a sub-class of the base `Model` class and will pass this `instance of` check.

Once you set your schema to OpenLDAP, clear your configuration cache using `php artsian config:clear` and then try re-authenticating.

If you still encounter problems just let me know and I will re-open this issue.
