### ISSUE TITLE
Couldn't get distinguished name of an OU

### ISSUE THREAD

**Issue by chinthakanm** [Adldap2/Adldap2-Laravel#494]
Hi @stevebauman ,
I tried with below methods to get DN of an OU.

$ou->getAttributes();
$ou->getAttribute('dn');

These methods were not working for OU model. 
It says these methods do not exist.
I want to search for specific OU ( like: name='Domain Users' ) and 
get other attributes ( like: $dn = $ou->getAttribute('dn'); ) if that OU exist.

**Comment by stevebauman** [comment]
Hi @chinthakanm, that's strange. Try using `getDn()`:

```php
$ou->getDn();

// Or:

$ou->getDistinguishedName();
```

**Comment by stevebauman** [comment]
Hang on, it says the methods don't exist?

Can you post your usage on how you're retrieving an OU?

**Comment by chinthakanm** [comment]
Hi @stevebauman,

Thank you very much for replying me.
That code is in my office computer and today i'm on holiday. Therefore I can't access it right now. 
I will post my code tomorrow.

**Comment by chinthakanm** [comment]
Hi @stevebauman,

Thank you very much for replying me.

This is my Controller code
[Create OU Controller.txt](https://github.com/Adldap2/Adldap2-Laravel/files/1777249/Create.OU.Controller.txt)

This is the view which I used
[Create OU view.txt](https://github.com/Adldap2/Adldap2-Laravel/files/1777241/Create.OU.view.txt)

Again thank u for helping me.

**Comment by stevebauman** [comment]
Hey @chinthakanm, you're currently doing:

```html
@foreach( $ous as $ou )
    <option value="{{ $ou->getAttribute(''dn') }}">{{ $ou->getName() }}</option>
@endforeach
```

```html
@foreach($ous as $ou)
    <option value="{{ $ou->getDn() }}">{{ $ou->getName() }}</option>
@endforeach
```

**Comment by stevebauman** [comment]
Unless the error is occurring elsewhere? Can you post your exact exception that you receive?

Need more information to help you.

**Comment by chinthakanm** [comment]
Hi @stevebauman,

@foreach( $ous as $ou )
    <option value="{{ $ou->getAttribute('dn') }}">{{ $ou->getName() }}</option>
@endforeach

Yep. this was one place gave exception that getAttribute() method doesn't exist.
and also in my controller ( I have uploaded controller class ) I have used getAttribute('dn') method
and gave same error the getAttribute() method doesn't exist.

And then I replaced getAttribute('dn') method to following methods. but gave same error.
getAttributes()
getDn()
getDistinguishedName()

The exception was, These methods don't exist.

**Comment by chinthakanm** [comment]
Actually, understading controller functions are bit difficult and sorry for that.

Think in my OU controller, I want to search DN of an OU. below is the function I'm going to use.

![code](https://user-images.githubusercontent.com/33538620/36947724-de5f4a6e-1ff5-11e8-9dbd-c2666f0f6cf8.JPG)

And when I'm going to run, it will give an error the getAttribute() method doesn't exist.
same error occur for below methods
getAttributes()
getDn()
getDistinguishedName()

**Comment by stevebauman** [comment]
What is the search returning? Dump and die what is being returned.

**Comment by chinthakanm** [comment]
Hi @stevebauman 
Got the point. Problem solved.
Search returning a collection OU model. 
But I had worked with it as single OU model. That's the reason I could't access those methods.
Now I changed code like below.

![asty](https://user-images.githubusercontent.com/33538620/37049302-806113fa-2196-11e8-831b-d24c40fbf884.PNG)

This works properly.
And again thank u very much for help me.

**Comment by stevebauman** [comment]
Great @chinthakanm! Glad you've resolved it.

No problem! Thanks for following up :)
