### ISSUE TITLE
User Principal Name with Apostrophe

### ISSUE THREAD

**Issue by SirPoot-** [Adldap2/Adldap2-Laravel#495]
- Laravel Version: v5.5.33
- Adldap2-Laravel Version: v3.0.9
- PHP Version: 7.2.2-3
- LDAP Type: Active Directory

### Description:

I changed the ldap user attribute from samaccountname to userprincipalname. This has been working perfectly until we hired a new employee with an apostrophe in her username and she is unable to login.

I know one option would be to remove the apostrophe, but I would like to get it working, if possible.

Any help is appreciated.

**Comment by stevebauman** [comment]
Hi @SirPoot-, can you elaborate on *not working*?

Do you receive an exception? Does it just say invalid credentials?

Can you dump & die through the whole request cycle in the Adldap library and see where it fails?

**Comment by SirPoot-** [comment]
@stevebauman Thank you for your quick reply. This issue was a face palm moment for me.

We had a rule restricting access to a particular AD Group. The generic error "These credentials do not match our records" (which I appreciate during the the authentication process) made me believe it was not passing through the apostrophe in the username.

Thank you again for a great solution.

**Comment by stevebauman** [comment]
Hey @SirPoot-, no problem! Happens all the time lol.

Glad you were able to get it working, and thanks for following up! Much appreciated. :)
