### ISSUE TITLE
Overriding class UserResolver method byCredentials

### ISSUE THREAD

**Issue by groundbreaker08** [Adldap2/Adldap2-Laravel#498]
- Laravel Version: 5.6
- Adldap2-Laravel Version: 4.0
- PHP Version: 7.2
- LDAP Type: Active Directory

### Description:
Is there any way to override this method: byCredentials?

### Steps To Reproduce:
public function byCredentials(array $credentials = [])
    {
        if (empty($credentials)) {
            return;
        }

        $provider = Config::get('adldap_auth.provider', DatabaseUserProvider::class);

        // Depending on the configured user provider, the
        // username field will differ for retrieving
        // users by their credentials.
        if ($provider == NoDatabaseUserProvider::class) {
            $username = $credentials[$this->getLdapDiscoveryAttribute()];
        } else {
            $username = $credentials[$this->getEloquentUsernameAttribute()];
        }

        $field = $this->getLdapDiscoveryAttribute();

        return $this->getProvider()->search()->whereEquals($field, $username)->first(); // edit
        return $this->query()->whereEquals($field, $username)->first();
    }

**Comment by stevebauman** [comment]
Hi @groundbreaker08, yes definitely.

The user resolver is called using its facade `Adldap\Laravel\Facades\Reolver`. You can use the facade's `swap()` method to use your own implementation:

```php
namespace App\Resolvers;

use Adldap\Laravel\Resolvers\UserResolver as AdldapUserResolver;

class CustomUserResolver extends AdldapUserResolver
{
   public function byCredentials(array $credentials = [])
    {
        // ...
    }
}
```

Then, call the `swap()` method somewhere in your application before authentication:

```php
use Adldap\Laravel\Facades\Resolver;
use App\Resolvers\CustomUserResolver;

$resolver = new CustomUserResolver(app('adldap'));

Resolver::swap($resolver);
```

**Comment by groundbreaker08** [comment]
Thanks @stevebauman . this works. 
created my custom resolver then override login method of AuthenticateUsers in LoginController Class.
then placed it before attemptLogin.

`// swap my custom UserResolver
        $resolver = new UserResolver(app('adldap'));
        Resolver::swap($resolver);
        if ($this->attemptLogin($request)) {
            return $this->sendLoginResponse($request);
        }`

**Comment by stevebauman** [comment]
Awesome, glad it works! Thanks for following up.

**Comment by fructosetransport** [comment]
Hi guys, trying to do something similar to the above but for another function in another adldap class but cannot get the custom extension to instantiate.

Laravel Version: 5.8
Adldap2-Laravel Version: 6.0
PHP Version: 7.2
LDAP Type: Active Directory

Description:
Is there any way to override this method: bindAsAdministrator?

Steps To Reproduce:
    public function bindAsAdministrator()
    {
        	$this->bind(
            	$this->configuration->get('username'),
            	$this->configuration->get('password')
        	);
    }
