### ISSUE TITLE
Model binding not working after upgrade to 4.0.7

### ISSUE THREAD

**Issue by matbeard** [Adldap2/Adldap2-Laravel#499]
- Laravel Version: 5.5
- Adldap2-Laravel Version: 4.0.7
- PHP Version: 7.1
- LDAP Type: Active Directory

### Description:
After upgrading from 3.0.4 to 4.0.7 I can no longer retrieve the LDAP model for the authenticated user. This was working perfectly with 3.0.4.

I'm using IIS with Windows Authentication and the SSO Middleware, all of which is working fine after the upgrade.

### Steps To Reproduce:
After successfully authenticating:
`var_dump(Auth::user()->ldap)`
result: `null`

**Comment by matbeard** [comment]
My apologies. I had a typo in the config file:
`'eloquent' => 'usernname',`

**Comment by stevebauman** [comment]
No problem, thanks for following up! Much appreciated :)
