### ISSUE TITLE
Requirements could not be reolved from Composer

### ISSUE THREAD

**Issue by barttt** [Adldap2/Adldap2-laravel#5]
Trying to install on top of working laravel 5.1 on Ubuntu dev server
Added the        "adldap2/adldap2-laravel": "1.1.*" line to composer.json file.
Ran composer update and got:
------------------ snip ----------------------------------
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - adldap2/adldap2-laravel v1.1.0 requires adldap2/adldap2 5.1.* -> satisfiable by adldap2/adldap2[v5.1.0, v5.1.1, v5.1.2, v5.1.3, v5.1.4, v5.1.5, v5.1.6, v5.1.7].
    - adldap2/adldap2-laravel v1.1.1 requires adldap2/adldap2 5.1.* -> satisfiable by adldap2/adldap2[v5.1.0, v5.1.1, v5.1.2, v5.1.3, v5.1.4, v5.1.5, v5.1.6, v5.1.7].
    - adldap2/adldap2-laravel v1.1.2 requires adldap2/adldap2 5.1.* -> satisfiable by adldap2/adldap2[v5.1.0, v5.1.1, v5.1.2, v5.1.3, v5.1.4, v5.1.5, v5.1.6, v5.1.7].
    - adldap2/adldap2 v5.1.7 requires ext-ldap * -> the requested PHP extension ldap is missing from your system.
    - adldap2/adldap2 v5.1.6 requires ext-ldap * -> the requested PHP extension ldap is missing from your system.
    - adldap2/adldap2 v5.1.5 requires ext-ldap * -> the requested PHP extension ldap is missing from your system.
    - adldap2/adldap2 v5.1.4 requires ext-ldap * -> the requested PHP extension ldap is missing from your system.
    - adldap2/adldap2 v5.1.3 requires ext-ldap * -> the requested PHP extension ldap is missing from your system.
    - adldap2/adldap2 v5.1.2 requires ext-ldap * -> the requested PHP extension ldap is missing from your system.
    - adldap2/adldap2 v5.1.1 requires ext-ldap * -> the requested PHP extension ldap is missing from your system.
    - adldap2/adldap2 v5.1.0 requires ext-ldap * -> the requested PHP extension ldap is missing from your system.
    - Installation request for adldap2/adldap2-laravel 1.1.* -> satisfiable by adldap2/adldap2-laravel[v1.1.0, v1.1.1, v1.1.2].

How can I resolve this?
Thanks

**Comment by barttt** [comment]
got ldap installed with an apt-get install php5-ldap
and an apache2 restart cmd

**Comment by barttt** [comment]
then it ran on the composer update..
Sorry to bug.

**Comment by stevebauman** [comment]
No problem, please don't hesitate to create another issue if you encounter any, thanks!

**Comment by barttt** [comment]
Hi Steve-
Thanks for the quick reply.
Great support!

Perhaps I should ask this online, but I’ll fire it off from here anyway..
New to laravel, so sorry if this is a dumb question.
Can you point me to any info on dual authentication (eg using ldap and the local DB)?
We need to use ldap as a failsafe but the local DB as the primary authentication source, probably using a blank password in the local DB to differentiate.

----------------------------------------
Bart Thompson
Software Engineer
Alpha Research & Technology
----------------------------------------

**Comment by stevebauman** [comment]
Adldap-Laravel actually creates local database entries so you're able to attach data to the user traditionally, however it doesn't allow authenticating traditionally if that fails... You'd have to switch the auth driver in run-time using `config('auth.driver', 'eloquent');` and then try to authenticate your user again.

**Comment by barttt** [comment]
Thanks again Steve


----------------------------------------
Bart Thompson
Software Engineer
Alpha Research & Technology
----------------------------------------

**Comment by kymani20100** [comment]
search for ldap in your php.ini file and enable **;extension=ldap** ....that should do the trick
