### ISSUE TITLE
Authenticating event is not invoked 

### ISSUE THREAD

**Issue by paulosscruz** [Adldap2/Adldap2-Laravel#500]
- Laravel Version: 5.6
- Adldap2-Laravel Version: 4.0
- PHP Version: 7.2
- LDAP Type: Active Directory

### Description:

The Authenticating event is not invoked when SSO middleware is enabled.

```
public function handle(Request $request, Closure $next)
    {
        if (!$this->auth->check()) {
            // Retrieve the users account name from the request.
            if ($account = $this->account($request)) {
                // Retrieve the users username from their account name.
                $username = $this->username($account);

                // Finally, retrieve the users authenticatable model and log them in.
                if ($user = $this->retrieveAuthenticatedUser($username)) {
                    $this->auth->login($user, $remember = true);
                }
            }
        }

        return $next($request);
    }
```

**Comment by stevebauman** [comment]
Hi @paulosscruz,

Which authentication event are you talking about? There is a separate auth event for the SSO middleware:

https://github.com/Adldap2/Adldap2-Laravel/blob/master/src/Middleware/WindowsAuthenticate.php#L55-L103

https://github.com/Adldap2/Adldap2-Laravel/blob/0453624657c53f5eb8d43cafdaa36bb2d6088887/src/Middleware/WindowsAuthenticate.php#L94-L100

**Comment by stevebauman** [comment]
There's also the built in Laravel auth event you can utilize as well.

**Comment by paulosscruz** [comment]
Hi @stevebauman ,

The event that I am referring to is the:

> 'Adldap\Laravel\Events\Authenticating'

But in fact, I did not think of using the Laravel authentication event. That will solve my problem!

Thanks.

**Comment by stevebauman** [comment]
Hi @paulosscruz, you're right, it should contain some of the events as the other providers.

I'll fix this :)

**Comment by stevebauman** [comment]
Hmmm at second though @paulosscruz, the `Authenticating` events wouldn't be suited here, as there is no actual LDAP binding that is occurring. That is what the events purpose is in the Resolver.

If you're using the WindowsAuthenticate middleware, the LDAP user has already passed LDAP authentication via the web server and a bind is never called through this route.

I think using Laravel's authenticating events can be used instead if required and would be better suited for this scenario.

If you can think of a use case that this would work, please let me know and I will re-open this. Thanks!
