### ISSUE TITLE
Pagination not working

### ISSUE THREAD

**Issue by hrmshandy** [Adldap2/Adldap2-Laravel#502]
- Laravel Version: 5.5
- Adldap2-Laravel Version: 4.0
- PHP Version: 7.2
- LDAP Type: ActiveDirectory

### Description:
load query with paginate is too long and always return http error 500
```php
Adldap::search()->users()->paginate(50, 2)->getResults();
```

![image](https://user-images.githubusercontent.com/8230690/37275376-9b45afda-2611-11e8-93c5-1953acb99b8c.png)

if I reverse users() and search() like this 
```php 
Adldap::users()->search()->paginate(50, 2)->getResults();
```
an error appears like this:

![image](https://user-images.githubusercontent.com/8230690/37275202-214e44ee-2611-11e8-8420-acfa2a6310cd.png)

and if without users(), the result is empty
```php 
Adldap::search()->paginate(50, 2)->getResults();
```

**Comment by stevebauman** [comment]
Hi @hrmshandy,

For your first issue, you're calling it backwards. You should be calling `search()` first:

**Your usage:**

```php
Adldap::users()->search()->paginate(50, 2)->getResults();
```

**Should be:**

```php
Adldap::search()->users()->paginate(50, 2)->getResults();
```

If the result is empty, verify your `base_dn` in your configuration is correct. Even if there is one character missing, you won't receive anything.

If you still continue to have issues please let me know and I'll re-open this, thanks!

**Comment by brutalVinz** [comment]
Your users() method is taking so much memory/time when trying to get all users from an AD. (in my case we got 11k users). This part of code is optimized:


`// RECUPERATION DE TOUS LES COMPTES SANS LIMITATION (>1000) AVEC CONTROLE DE PAGINATION
	public function allNoRange($con)
	{
		ldap_set_option($con, LDAP_OPT_PROTOCOL_VERSION, 3);
		$filter = "(&(objectClass=user)(sAMAccountName=*))";
		$fields = array("company","distinguishedName","cn","givenName","sn","mail","sAMAccountName","whenCreated","department");
		$fullTab=array();
		// enable pagination with a page size of 100.
		$pageSize = 500;
		$cookie = '';
		do
		{
			ldap_control_paged_result($con,$pageSize,false,$cookie);
			$result = ldap_search($con,$_ENV["ADLDAP_BASEDN"], $filter, $fields);
			$entries = ldap_get_entries($con, $result);
			foreach ($entries as $key=>$e)
			{
				// jump the "count" of each page
				if($key=="count" && (is_int($e)))
					continue;
				
				// feed the final user array
				if(isset($e["samaccountname"][0]))
					$fullTab[$e['samaccountname'][0]]=$e;				
			}
			ldap_control_paged_result_response($con, $result, $cookie);
		}while($cookie !== null && $cookie != '');

		// reset paged result
		ldap_control_paged_result($con, 1000, false, $cookie);
		return $fullTab;
	}`

**Comment by stevebauman** [comment]
> Your users() method is taking so much memory/time when trying to get all users from an AD.

Of course it's going to use more memory than running raw LDAP commands. That's like saying Eloquent uses more memory than running raw queries against the database.

An ORM retrieves data from its source and adds the resulting data into an object which in turn allocates memory and resources.

Now in terms of time, that's definitely debatable. I'd like to see a comparison of identical LDAP queries against an Adldap2 query. My thought is that you're not requesting specific attributes or a large enough page size, but are with your posted raw LDAP query.

That being said, this is a free, open source package. You're welcome to send a pull request, modify the code yourself, or simply not use the library if you prefer raw LDAP commands.

**Comment by brutalVinz** [comment]
Steve, you've made a really great work.
I use your ADLDAP2 package for many APPS at our IT department. So many
thanks for this great work.

I don't feel experienced enought  with LARAVEL FACADE actually so i wont
modify your package yet... Maybe later for a pull request
Here we go for a benchmark:

*Get group Members with ADLDAP2 *
$group = Adldap::search()->groups()->find($sAMAccountName);
$group->getMembers();
[image: image.png]



*Get group Members with raw method on a group with ~1800 users*
[image: image.png]



Le mer. 23 oct. 2019 à 15:15, Steve Bauman <notifications@github.com> a
écrit :
