### ISSUE TITLE
extracting ldap properties from within a controller

### ISSUE THREAD

**Issue by rbmcgowan** [Adldap2/Adldap2-Laravel#507]
- Laravel Version: 5.6
- Adldap2-Laravel Version: current 
- PHP Version: 7.1
- LDAP Type:  OpenLDAP 

### Description:

I'm trying to get the company attribute from ldap via ...

$userldap = Adldap::search()->where('mail', '=', auth::user()->email)->get();
$company = $userldap->company;

The user is found and retrieved by the first line.

But all I get is "Property [company] does not exist on this collection instance." however when I dd($userldap) I can see the company attribute (and its value) ok. I guess I am misunderstanding how to extract LDAP attributes from the ldap model.

Any pointers? sorry for hassling you with my lack of knowledge.

**Comment by stevebauman** [comment]
Hi @rbmcgowan,

Whenever you call the method `get()` it returns a **Collection**, regardless if there is only one record to return.

A collection is a glorified PHP array with extra functionality.

You should loop over the results, or call the `first()` method:

```php
// Looping over the results:
$users = Adldap::search()->where('mail', '=', auth::user()->email)->get();

foreach ($users as $user) {
    echo $user->company;
}
```

```php
// For your example, use `first()`:
$userldap = Adldap::search()->where('mail', '=', auth::user()->email)->first();

$company = $userldap->company;
```

**Comment by rbmcgowan** [comment]
thanks @stevebauman, I should have thought of that, so obvious in hindsight. thanks for your help.

**Comment by stevebauman** [comment]
No problem at all @rbmcgowan! I only care about helping out and getting you up and running.
