### ISSUE TITLE
Yet again, Auth::attempt does not work, but Adldap::auth()->attempt does.

### ISSUE THREAD

**Issue by MrBrax** [Adldap2/Adldap2-Laravel#508]
- Laravel Version: 5.6.12
- Adldap2-Laravel Version: 4.0.7
- PHP Version: 7.2
- LDAP Type: ActiveDirectory

### Description:
Auth::attempt does not work, but Adldap::auth()->attempt does. I don't see why they would be different.
I don't want to use an admin account, i'm only doing authentication (and configuring it doesn't help either).

The login attempts doesn't even get logged in the adldap logging functions.

Yes, i've added the trait to the user model.
Yes, i've changed the authentication provider to adldap.
Yes, i've configured the base dn correctly.
Yes, i've tried every possible combination of adldap_auth.php config values for usernames/etc.
Yes, i've went through every issue here regarding this, but either the solution doesn't work or the user just said "fixed it".

**Comment by MrBrax** [comment]
>Can you check your log files after trying to login to see where the authentication attempt stops?

there's nothing in the log, it's as if it's not even trying to authenticate

>What are you wanting to authenticate users with (samaccountname, userprincipalname etc.)?

anything, their raw username on their input part at least

>Post your adldap_auth.php file with sensitive details omitted
>Post your adldap.php file with sensitive details omitted

adldap.php
````
<?php

return [

    'connections' => [

        'default' => [

            'auto_connect' => env('ADLDAP_AUTO_CONNECT', false),

            'connection' => Adldap\Connections\Ldap::class,

            'schema' => Adldap\Schemas\ActiveDirectory::class,

            'connection_settings' => [

                'account_prefix' => env('ADLDAP_ACCOUNT_PREFIX', ''),

                'account_suffix' => env('ADLDAP_ACCOUNT_SUFFIX', ''),

                'domain_controllers' => explode(' ', env('ADLDAP_CONTROLLERS', 'corp-dc1.corp.acme.org corp-dc2.corp.acme.org')),

                'port' => env('ADLDAP_PORT', 389),

                'timeout' => env('ADLDAP_TIMEOUT', 5),

                'base_dn' => env('ADLDAP_BASEDN', 'dc=corp,dc=acme,dc=org'),

                'admin_account_prefix' => env('ADLDAP_ADMIN_ACCOUNT_PREFIX', ''),
                'admin_account_suffix' => env('ADLDAP_ADMIN_ACCOUNT_SUFFIX', ''),

                'admin_username' => env('ADLDAP_ADMIN_USERNAME', ''),
                'admin_password' => env('ADLDAP_ADMIN_PASSWORD', ''),

                'follow_referrals' => true,

                'use_ssl' => env('ADLDAP_USE_SSL', false),
                'use_tls' => env('ADLDAP_USE_TLS', false),

            ],

        ],

    ],

];
````

adldap_auth.php
````
<?php

return [

    'connection' => env('ADLDAP_CONNECTION', 'default'),

    'provider' => Adldap\Laravel\Auth\DatabaseUserProvider::class,

    'rules' => [
        Adldap\Laravel\Validation\Rules\DenyTrashed::class,
    ],

    'scopes' => [
        Adldap\Laravel\Scopes\UpnScope::class,
    ],

    'usernames' => [
        
        'ldap' => [

            'discover' => 'userprincipalname',

            'authenticate' => 'distinguishedname',

        ],

        'eloquent' => 'username',

        'windows' => [

            'discover' => 'samaccountname',

            'key' => 'AUTH_USER',

        ],

    ],

    'passwords' => [

        'sync' => env('ADLDAP_PASSWORD_SYNC', false),

        'column' => 'password',

    ],

    'login_fallback' => env('ADLDAP_LOGIN_FALLBACK', false),

    'sync_attributes' => [

        'username' => 'samaccountname',

        'email' => 'mail',

        'firstname' => 'givenname',

        'lastname' => 'sn'

    ],
    
    'logging' => [

        'enabled' => true,

        'events' => [

            \Adldap\Laravel\Events\Importing::class => \Adldap\Laravel\Listeners\LogImport::class,
            \Adldap\Laravel\Events\Synchronized::class => \Adldap\Laravel\Listeners\LogSynchronized::class,
            \Adldap\Laravel\Events\Synchronizing::class => \Adldap\Laravel\Listeners\LogSynchronizing::class,
            \Adldap\Laravel\Events\Authenticated::class => \Adldap\Laravel\Listeners\LogAuthenticated::class,
            \Adldap\Laravel\Events\Authenticating::class => \Adldap\Laravel\Listeners\LogAuthentication::class,
            \Adldap\Laravel\Events\AuthenticationFailed::class => \Adldap\Laravel\Listeners\LogAuthenticationFailure::class,
            \Adldap\Laravel\Events\AuthenticationRejected::class => \Adldap\Laravel\Listeners\LogAuthenticationRejection::class,
            \Adldap\Laravel\Events\AuthenticationSuccessful::class => \Adldap\Laravel\Listeners\LogAuthenticationSuccess::class,
            \Adldap\Laravel\Events\DiscoveredWithCredentials::class => \Adldap\Laravel\Listeners\LogDiscovery::class,
            \Adldap\Laravel\Events\AuthenticatedWithWindows::class => \Adldap\Laravel\Listeners\LogWindowsAuth::class,
            \Adldap\Laravel\Events\AuthenticatedModelTrashed::class => \Adldap\Laravel\Listeners\LogTrashedModel::class,

        ],
    ],

];
````

.env
````
ADLDAP_CONNECTION=default
ADLDAP_CONTROLLERS=X
ADLDAP_USE_SSL=true
ADLDAP_PORT=636
ADLDAP_BASEDN=X
ADLDAP_ACCOUNT_SUFFIX=X
LDAPTLS_REQCERT=never
````

I gave up and just made it manually log on with Adldap::auth(), i spent a total of 7 hours straight on this and i need to move on.

**Comment by stevebauman** [comment]
Hi @MrBrax, thanks for the quick response.

First up, `auto_connect` needs to be `true` **unless you connect manually**. This is described right above the feature:

> If this is set to false, you **must** connect manually before running LDAP operations.

https://github.com/Adldap2/Adldap2-Laravel/blob/master/src/Config/config.php#L32

Secondly, turn *off* `follow_referrals`, as this *may* cause issues locating users or other LDAP records.

Thirdly:

> there's nothing in the log, it's as if it's not even trying to authenticate

This sounds like you don't have the Adldap2-Laravel auth driver configured in your `auth.php` file, **or** your configuration is being cached, in which case it wouldn't take effect until you run a `php artisan config:clear`.

Fourthly, have you changed your `LoginController` at all to match your `username` field in you're trying to authenticate with, as well as your Laravel blade template to match?

> I gave up and just made it manually log on with Adldap::auth(), i spent a total of 7 hours straight on this and i need to move on.

If you're not looking to spend more time troubleshooting and move on, please let me know so I can close this issue out. No use wasting either of our time.

**Comment by MrBrax** [comment]
I've tried having autoconnect both enabled and disabled, it makes no difference.

Follow referrals makes no difference.

The auth driver is configured, and i have cleared the config cache.

The login controller has been changed yes, but it's custom anyway.

**Comment by MrBrax** [comment]
> Regardless if it seems to make no difference, it needs to be set to true at least for troubleshooting here.

I've tried both.

> Have you tried simply dumping and dying throughout the authentication request cycle to see where it stops?

I'm dumping in the login controller but the auth thing doesn't appear in the trace. There's no error, it just returns false.

> Can you post your auth.php file?
````
<?php

return [

    'defaults' => [
        'guard' => 'web',
        'passwords' => 'users',
    ],

    'guards' => [
        'web' => [
            'driver' => 'session',
            'provider' => 'users',
        ],

        'api' => [
            'driver' => 'token',
            'provider' => 'users',
        ],
    ],

    'providers' => [

        'users' => [
            'driver' => 'adldap',
            'model' => App\User::class
        ],

    ],

    'passwords' => [
        'users' => [
            'provider' => 'users',
            'table' => 'password_resets',
            'expire' => 60,
        ],
    ],

];
````

>This is pretty crucial, can you post this as well?

Why? Why shouldn't Auth::attempt() work anywhere?

**Comment by stevebauman** [comment]
> I'm dumping in the login controller but the auth thing doesn't appear in the trace. There's no error, it just returns false.

Usually I just temporarily edit the PHP files what `Auth::attempt()` is calling. For example, you can modify the `DatabaseUserProvider` at [this line](https://github.com/Adldap2/Adldap2-Laravel/blob/master/src/Auth/DatabaseUserProvider.php#L101) and call `dd($user)` to see if a user is actually being located, and even if the `DatabaseUserProvider` is even being called at all.

```php
// Retrieve the LDAP user who is authenticating.
$user = Resolver::byCredentials($credentials);

dd($user);
```

> Why? Why shouldn't Auth::attempt() work anywhere?

Yes, but you may be passing the wrong array keys into the `attempt()` method. I'm just trying to cover our bases here so I can help you troubleshoot. I need the full picture.

**Comment by MrBrax** [comment]
It returns null.

>Yes, but you may be passing the wrong array keys into the attempt() method. I'm just trying to cover our bases here so I can help you troubleshoot. I need the full picture.

I'm not, it's basically just `Auth::attempt( ['username' => $username, 'password' => $password] ) ` and the data is correct, i've `dd` on them.

**Comment by stevebauman** [comment]
Can you change your `ldap.discover` attribute to `samaccountname` and try authenticating again with the `dd($user)` in place to see if a user is being returned?

**Comment by MrBrax** [comment]
Still nothing.

Tried removing the suffix too.

**Comment by stevebauman** [comment]
Ok, before your `Auth::attempt()` is called in the controller, can you see if you can locate the user you're trying to auth with?:

```php
use Adldap\Laravel\Facades\Adldap;

$user = Adldap::search()->where('samaccountname', '=', $username)->first();

dd($user);

// Auth::attempt()...
```

**Comment by MrBrax** [comment]
null too. but that wouldn't work either since the user hasn't bound to ldap yet

**Comment by stevebauman** [comment]
Oh *facepalm* hang on, you're not connected to your LDAP server and you don't have an admin_username or admin_password specified. That's why `auto_connect` makes no difference and you're not receiving anything from your queries.

This package **requires** a user and password to be able to bind to your LDAP server **prior** to the user authenticating. This allows for a ton of other features such as using alternate attributes for authentication.

If you can't use an LDAP service account of some sort for this web application, then you will definitely need to create your own home grown solution.

**Comment by MrBrax** [comment]
I tried using the admin account earlier and it didn't work so i just assumed you didn't need it anyway.

I'm able to auth using Adldap::auth()->attempt() though, so i don't see why the regular method wouldn't work.

Yeah, i'll go back to using Adldap::auth()->attempt() instead.

**Comment by stevebauman** [comment]
> I tried using the admin account earlier and it didn't work so i just assumed you didn't need it anyway.

Configuration options make all the difference. Flexibility comes at a cost of troubleshooting and issues unfortunately.

> Yeah, i'll go back to using Adldap::auth()->attempt() instead.

Ok sounds good!
