### ISSUE TITLE
modification of other entries / raw ldap commands handling

### ISSUE THREAD

**Issue by GergelyLakatos** [Adldap2/Adldap2-Laravel#511]
- Laravel Version: 5.5
- Adldap2-Laravel Version: 4.0.7
- PHP Version: 7.0.7
- LDAP Type: OpenLDAP 

### Description: 

I'm working on a project, what uses ldap for authentication. I could do with this lib succesfully (I really like the way it works). However I have to modify the user entries and the other entries (of the user). I found some example how can I update the authenticated user, but I didn't found a solution (example) for make a modification (or removing) other entries.

### Question:

Is there any example, how can I run raw commands via adldap laravel? Or there is a nice way to run modification / removing / creating other entries (not users!).

Thanks for the answers in advance!

**Comment by stevebauman** [comment]
Hi @GergelyLakatos, good question!

Just to clarify, you're looking to modify the actual LDAP records of users? Or are you looking to modify the users imported models?

**Comment by GergelyLakatos** [comment]
@stevebauman Thanks for the respond! :)

Actually I've never made an LDAP connection in PHP before. I have experience in Java. Thats why I based my question on my Java knowledge. In java you have to write the "raw" LDAP commands, and you fill it, with the variables.

As I wrote upper the ldap bind authentication is clear and working and I like it. But it has another logic what I got to know. I can understand, that If I want to update something, I search it, I got back a user obj, what I can modify and save. 
But I want to ask, that is there any option that I define a raw command, what I can run.
e.g.: Like [linux terminal](https://www.linux.com/learn/managing-ldap-command-line-linux) so I defined a command text what I send to the ldap server.

I spent some time for googling it, but I didnt find any answer for that, so I guess the answer is no.

**Comment by warlord0** [comment]
Not to detract from this excellent authentication tool, but I think you'd be best placed looking at ldaptools for really manipulating the data from a php environment.

https://github.com/ldaptools/ldaptools

**Comment by stevebauman** [comment]
Hi @GergelyLakatos, you can modify any entry returned from an Adldap2 search result.

Adldap2 is a complete encompassing LDAP solution for PHP. Adldap2-Laravel simply provides some extra features (authentication) as well as easy access to your LDAP server.

This is shown in the [basic usage](https://github.com/Adldap2/Adldap2-Laravel#usage) section of the package.

To modify an LDAP record, simply modify its attributes. Here's an example:

```php
use Adldap\Laravel\Facades\Adldap;

$user = Adldap::search()->users()->where('cn', '=', 'Doe, John')->first();

$user->cn = 'Jane Doe';

$user->save();
```

Hope this answers your questions. Otherwise comment back and I'll give further assistance. Thanks!

**Comment by stevebauman** [comment]
Also @warlord0, this package extends from the base Adldap2 package.

All functionality from the base is available in Adladp2-Laravel.

**Comment by GergelyLakatos** [comment]
@stevebauman and @warlord0 Thanks! I got the answer this is a way, and only way to modify entries.
Many thanks!
