### ISSUE TITLE
One user can't authenticate in ad

### ISSUE THREAD

**Issue by newtekDev** [Adldap2/Adldap2-Laravel#512]
- Laravel Version: 5.4
- Adldap2-Laravel Version: 3.0
- PHP Version: 7.2
- LDAP Type: ActiveDirectory

### Description:
I have everything set up fine and every user in the AD can login, except one. When I run this:
```
Adldap::search()->users()->find('{F.LASTNAME}');
```
I get the proper result, but when they login or I import the authentication fails/user is not added. The thing about this user is that its the only user that has a period in the samaccountname after the first inital, could this be the issue?

**Comment by newtekDev** [comment]
After doing some more research, I am finding a lot of discrepancies between my AD records and what is imported. I have at least 10 AD users so far which are not getting imported, but when I use the search like above, even with ones that do not have the period in the name, I get the correct result.

What would cause this discrepancy?

**Comment by stevebauman** [comment]
Hi @newtekDev,

> The thing about this user is that its the only user that has a period in the samaccountname after the first inital, could this be the issue?

What error do you receive when you try to import this user via `adldap:import` command?

> What would cause this discrepancy?

Are these 10 AD users located in a different OU or have some sort of differentiation from the others that are successfully imported? I'll need to see the exception logs to help you debug this.

**Comment by newtekDev** [comment]
**What error do you receive when you try to import this user via adldap:import command?**

I just tried this command:
```
vagrant@homestead:~/Code/api$ php artisan adldap:import --filter "(samaccountname=f.lastname)"
**Found 0 user(s).**

 Would you like to display the user(s) to be imported / synchronized? (yes/no) [no]:
 > 
```
**Are these 10 AD users located in a different OU or have some sort of differentiation from the others that are successfully imported? I'll need to see the exception logs to help you debug this.**

 I tried comparing the setup for all of the users, there is nothing unique about each of them and there are plenty of other users that have the same setup that are imported. However, I have what to learn about LDAP, is there anything specifically I could look for?

**Comment by stevebauman** [comment]
Hi @newtekDev,

Do you have any configured scopes in your `adldap_auth.php` file?

Can you post it here for me to look at?

**Comment by newtekDev** [comment]
heres my file, I only changed the sync_attributes:
```
<?php

return [
    'connection' => env('ADLDAP_CONNECTION', 'default'),
    'provider' => Adldap\Laravel\Auth\DatabaseUserProvider::class,
    'resolver' => Adldap\Laravel\Auth\Resolver::class,
    'importer' => Adldap\Laravel\Auth\Importer::class,
    'rules' => [
        // Denys deleted users from authenticating.
        Adldap\Laravel\Validation\Rules\DenyTrashed::class,
        // App\Rules\AllowedGroups::class,
        // Allows only manually imported users to authenticate.
        // Adldap\Laravel\Validation\Rules\OnlyImported::class,
    ],
    'scopes' => [
        // Only allows users with a user principal name to authenticate
        Adldap\Laravel\Scopes\UpnScope::class,
    ],
    'usernames' => [
        'ldap' => 'samaccountname',
        'eloquent' => 'username',
    ],
    'login_fallback' => env('ADLDAP_LOGIN_FALLBACK', true),
    'password_sync' => env('ADLDAP_PASSWORD_SYNC', true),
    'windows_auth_attribute' => ['samaccountname' => 'AUTH_USER'],
    'sync_attributes' => [
        'username' => 'samaccountname',
        'email' => 'mail',
        'first_name' => 'givenname',
        'last_name' => 'sn',
        'extention' => 'telephonenumber',
    ],
];

```

**Comment by stevebauman** [comment]
Does this user you're trying to authenticate with have a `userPrincipalName`?

If you have the `Adldap\Laravel\Scopes\UpnScope` inside the `scopes` array, this will only allow users with a `userPrincipalName` to authenticate or be imported.

**Comment by warlord0** [comment]
So I thought I'd do some testing at home using my Synology for LDAP and wondered why it failed to logon, but worked from ldapsearch. Turns out the schema has no upn. So this post answered my question :D

**Comment by newtekDev** [comment]
let me give that a shot, is there a reason that is the default?

**Comment by newtekDev** [comment]
That was it! Thanks so much!

**Comment by stevebauman** [comment]
Great glad you've resolved the issue!

It's default because using email is the standard setup in Laravels auth, and since LDAP user principal names are basically email addresses and they already exist by default on most ActiveDirectory users (when the `mail` attribute may not be populated due to having to manually filling it in on user creation in AD).

The scope was implemented as an example and security feature to only allow users with a user principal name to authenticate.

I'll remove this scope as a default, it seems it causes a lot of confusion with devs using Adldap2-Laravel.

Thanks for the feedback and your responses.
