### ISSUE TITLE
v4.0.0 Changelog Missing

### ISSUE THREAD

**Issue by michaellindahl** [Adldap2/Adldap2-Laravel#519]
- Adldap2-Laravel Version: v4.0.0
https://github.com/Adldap2/Adldap2-Laravel/releases/tag/v4.0.0

### Description:
Detailed change log coming shortly.
There is no change log for the v4.0.0 release

**Comment by stevebauman** [comment]
Good catch! Forgot about this, appreciate the reminder.

**Comment by stevebauman** [comment]
Fixed.
