### ISSUE TITLE
Authentication is taking a long time

### ISSUE THREAD

**Issue by bmadala33** [Adldap2/Adldap2-Laravel#523]
- Laravel Version: 5.5
- Adldap2-Laravel Version: 3.0
- PHP Version: 7.1
- LDAP Type: ActiveDirectory

### Description:
i'm using ldap package for authentication. it's working well but the issue is taking nearly 30 seconds to login. can you help me what the issue and where i did wrong/

**Comment by stevebauman** [comment]
Hi @bmadala33,

What is your timeout setting in your `config/adldap.php` file for the connection?

Also, is the connection over VPN or some type of network bridge etc.?

**Comment by bmadala33** [comment]
Hi @stevebauman ,
in my configuration file it has a timeout 5 and i think it doesn't have any network bridge.
my application and my database are on different server.

**Comment by stevebauman** [comment]
If you change your authentication `driver` back to `eloquent` in your `config/auth.php` file, do you still experience a delay in logging in?

For example:

```php
'providers' => [
        'users' => [
            'driver' => 'eloquent', // Switched back to `eloquent` from `adldap`
            'model' => App\User::class,
        ],
```

**Comment by bmadala33** [comment]
hi @stevebauman ,
if i change authentication **driver** back to **eloquent** i don't have any delay in authentication.


thanks

**Comment by stevebauman** [comment]
If you change your `timeout` config option to a lower value such as `1`, does it speed up at all?

**Comment by bmadala33** [comment]
hi @stevebauman ,
i have changed the timeout config option to lower value i.e is 1 not it is little bit faster.

thanks for your great help.

**Comment by stevebauman** [comment]
No problem! I'll mark this as resolved, but if you're still having large delay issues let me know and I'll re-open this issue.
