### ISSUE TITLE
Account suffix not added to admin username

### ISSUE THREAD

**Issue by syphernl** [Adldap2/Adldap2-Laravel#526]
- Laravel Version: 5.6.17
- Adldap2-Laravel Version: 4.0.7
- PHP Version: 7.2.4
- LDAP Type: ActiveDirectory

### Description:
It seems that the `ADLDAP_ACCOUNT_SUFFIX` is not being appended to the `ADLDAP_ADMIN_USERNAME`. 
This has worked fine in v3.x but once we upgraded to 4.x this started happening. 

Now the `ADLDAP_ADMIN_USERNAME` needs to include the suffix, otherwise the verification fails.

**Comment by stevebauman** [comment]
Hi @syphernl,

The account suffix is definitely being applied:

https://github.com/Adldap2/Adldap2/blob/v8.1.4/src/Auth/Guard.php#L78-L80

https://github.com/Adldap2/Adldap2/blob/v8.1.4/src/Auth/Guard.php#L116-L122

Test:

https://github.com/Adldap2/Adldap2/blob/c281dd5359c95e351661891133176bdb06a34fa5/tests/Auth/GuardTest.php#L38

Can you confirm it's not being used?

**Comment by syphernl** [comment]
Odd. Because if I set `ADLDAP_ADMIN_USERNAME=someuser` it fails to authenticate. 
If I set `ADLDAP_ADMIN_USERNAME=someuser@my.domain.tld` it works fine.

**Comment by cyjobes** [comment]
I have the same problem. Suffix is not being added. When I add it manually it works.
"adldap2/adldap2-laravel": "^5.1",
"laravel/framework": "5.7.*",

**Comment by stevebauman** [comment]
Hi guys, this is intended in the new release of `v5.0`, it is in the upgrade guide:

https://adldap2.github.io/Adldap2-Laravel/#/upgrading?id=prefix-and-suffix-changes
