### ISSUE TITLE
Can't access for some attributes in user model

### ISSUE THREAD

**Issue by chinthakanm** [Adldap2/Adldap2-Laravel#528]
- Laravel Version: 5.5
- Adldap2-Laravel Version: ^4.0
- PHP Version: 7.2
- LDAP Type: ActiveDirectory

### Steps To Reproduce:

Hi @stevebauman 

I can't access some attributes in user model

![example](https://user-images.githubusercontent.com/33538620/38996499-f487417a-4408-11e8-988e-3817bf6d3730.PNG)

How can I get values of those attributes ?

When I, dd( $user->getAttributes() ) it shows those attributes and values.

and also I can't update values for those attributes.

![example2](https://user-images.githubusercontent.com/33538620/38996925-dcc56b2e-4409-11e8-9ca9-0892e5fec632.PNG)

I need your help to find out this problem. 
Thank You.

**Comment by stevebauman** [comment]
Hi @chinthakanm,

Some getter / setter methods are not available on all attributes.

You can access all attributes via dynamic properties:

```php
$user->cn;
$user->telephone;
```

Or via `getAttribute()` / `getFirstAttribute()`:

```php
$user->getAttribute('cn'); // Returns `array`
$user->getFirstAttribute('cn'); // Returns `string`
```

Please look at the detailed model guide here:

https://github.com/Adldap2/Adldap2/blob/master/docs/models/model.md
