### ISSUE TITLE
Invalid AD credentials yields ldap_bind: Unable to bind to server

### ISSUE THREAD

**Issue by kunli0** [Adldap2/Adldap2-Laravel#53]
I'm having some issues with getting a response for a failed login. If providing the correct credentials it works just fine. I have login_fallback enabled and it seems to work as intended. 
When attempting to login with a valid AD username and incorrect password I receive the following error 

ldap_bind(): Unable to bind to server: Invalid credentials in ..\vendor\adldap2\adldap2\src\Connections\Ldap.php line 501. 

After shifting through the code I believe I should be getting another error exception with a different message. Thanks for the assistance.

**Comment by stevebauman** [comment]
Do you have `APP_DEBUG=true` in your `env.php`?

**Comment by kunli0** [comment]
Sorry Steve, I was just checking through the other closed issues, and yes Debuging is enabled. Thanks for the quick response.

**Comment by stevebauman** [comment]
No problem at all! Thanks for the quick reply.
