### ISSUE TITLE
NoDatabaseUserProvider is not working

### ISSUE THREAD

**Issue by nicro87** [Adldap2/Adldap2-Laravel#531]
- Laravel Version: 5.6
- Adldap2-Laravel Version: 4.0
- PHP Version: 7.1.10
- LDAP Type: Active Directory

### Description:
Hello,

i'm trying for a long time now to use Adldap without a database.
After getting a little into it, i'm confused if it is possible to use adldap without a database.
The login with the "Admin-Account" to the ldap-Server/ad and "Username" validation is working fine.
But in DiscoveredWithCredentials i get a type error:

use Adldap\Models\User;
 
class DiscoveredWithCredentials
{
    /**
     * The discovered LDAP user before authentication.
     *
     * @var User
     */
    public $user;
 
    /**
     * Constructor.
     *
     * @param User $user
     */
    public function __construct(User $user)
    {
        $this->user = $user;
    }
}

Type error: Argument 1 passed to Adldap\Laravel\Events\DiscoveredWithCredentials::__construct() must be an instance of Adldap\Models\User, instance of Adldap\Models\Entry given, called in /home/xxx/bws/vendor/adldap2/adldap2-laravel/src/Auth/NoDatabaseUserProvider.php on line 51 ◀"

This is where the event is fired:
    public function retrieveByCredentials(array $credentials)
    {
        if ($user = Resolver::byCredentials($credentials)) {
            Event::fire(new DiscoveredWithCredentials($user));
 
            return $user;
        }
    }

Can you please help me to solve this problem?

Thanks in advance
Nico

**Comment by stevebauman** [comment]
Hi @nicro87,

Are you sure you're using ActiveDirectory? It sounds like it's discovering a record from LDAP, but it's not a user.

Can you edit the raw file (`NoDatabaseUserProvider.php`) and try calling `dd()` on the `$user` object that's returned by `$user = Resolver::byCredentials($credentials)`?

Example:

```php
public function retrieveByCredentials(array $credentials)
{
    if ($user = Resolver::byCredentials($credentials)) {
        dd($user); // Here

        Event::fire(new DiscoveredWithCredentials($user));

        return $user;
    }
}
```

Once you do that, browse through the attributes and make sure the object it is locating from your directory is in-fact a user.

**Comment by nicro87** [comment]
Hi @stevebauman,

yes its an LDAP Server powered by the AD we are using.
I found (after trying with my Username) the object in the directory with my attributes.

**Comment by nicro87** [comment]
The output, if it helps:

Entry {#333 ▼
  +exists: true
  #query: Builder {#336 ▶}
  #schema: OpenLDAP {#328}
  #modifications: []
  +dateFormat: "Y-m-d H:i:s"
  #timestampFormat: "YmdHis.0Z"
  #attributes: array:145 [▶]
  #original: array:145 [▼
    "objectclass" => array:4 [▶]
    0 => "objectclass"
    "cn" => array:1 [▶]
    1 => "cn"
    "sn" => array:1 [▶]
    2 => "sn"
    "l" => array:1 [▶]
    3 => "l"
    "postalcode" => array:1 [▶]
    4 => "postalcode"
    "telephonenumber" => array:1 [▶]
    5 => "telephonenumber"
    "usercertificate" => array:2 [▶]
    6 => "usercertificate"
    "givenname" => array:1 [▶]
    7 => "givenname"
    "distinguishedname" => array:1 [▶]
    8 => "distinguishedname"
    "instancetype" => array:1 [▶]
    9 => "instancetype"
    "whencreated" => array:1 [▶]
    10 => "whencreated"
    "whenchanged" => array:1 [▶]
    11 => "whenchanged"
    "displayname" => array:1 [▶]
    12 => "displayname"
    "usncreated" => array:1 [▶]
    13 => "usncreated"
    "info" => array:1 [▶]
    14 => "info"
    "memberof" => array:67 [▶]
    15 => "memberof"
    "usnchanged" => array:1 [▶]
    16 => "usnchanged"
    "department" => array:1 [▶]
    17 => "department"
    "company" => array:1 [▶]
    18 => "company"
    "proxyaddresses" => array:7 [▶]
    19 => "proxyaddresses"
    "streetaddress" => array:1 [▶]
    20 => "streetaddress"
    "targetaddress" => array:1 [▶]
    21 => "targetaddress"
    "extensionattribute1" => array:1 [▶]
    22 => "extensionattribute1"
    "mailnickname" => array:1 [▶]
    23 => "mailnickname"
    "protocolsettings" => array:2 [▶]
    24 => "protocolsettings"
    "extensionattribute14" => array:1 [▶]
    25 => "extensionattribute14"
    "extensionattribute15" => array:1 [▶]
    26 => "extensionattribute15"
    "name" => array:1 [▶]
    27 => "name"
    "objectguid" => array:1 [▶]
    28 => "objectguid"
    "useraccountcontrol" => array:1 [▶]
    29 => "useraccountcontrol"
    "badpwdcount" => array:1 [▶]
    30 => "badpwdcount"
    "codepage" => array:1 [▶]
    31 => "codepage"
    "countrycode" => array:1 [▶]
    32 => "countrycode"
    "employeeid" => array:1 [▶]
    33 => "employeeid"
    "badpasswordtime" => array:1 [▶]
    34 => "badpasswordtime"
    "lastlogon" => array:1 [▶]
    35 => "lastlogon"
    "pwdlastset" => array:1 [▶]
    36 => "pwdlastset"
    "primarygroupid" => array:1 [▶]
    37 => "primarygroupid"
    "objectsid" => array:1 [▶]
    38 => "objectsid"
    "accountexpires" => array:1 [▶]
    39 => "accountexpires"
    "logoncount" => array:1 [▶]
    40 => "logoncount"
    "samaccountname" => array:1 [▶]
    41 => "samaccountname"
    "samaccounttype" => array:1 [▶]
    42 => "samaccounttype"
    "showinaddressbook" => array:2 [▶]
    43 => "showinaddressbook"
    "legacyexchangedn" => array:1 [▶]
    44 => "legacyexchangedn"
    "userprincipalname" => array:1 [▶]
    45 => "userprincipalname"
    "lockouttime" => array:1 [▶]
    46 => "lockouttime"
    "objectcategory" => array:1 [▶]
    47 => "objectcategory"
    "msmqsigncertificates" => array:1 [▶]
    48 => "msmqsigncertificates"
    "msmqdigests" => array:4 [▶]
    49 => "msmqdigests"
    "dscorepropagationdata" => array:5 [▶]
    50 => "dscorepropagationdata"
    "lastlogontimestamp" => array:1 [▶]
    51 => "lastlogontimestamp"
    "usersmimecertificate" => array:1 [▶]
    52 => "usersmimecertificate"
    "textencodedoraddress" => array:1 [▶]
    53 => "textencodedoraddress"
    "mail" => array:1 [▶]
    54 => "mail"
    "mssfu30nisdomain" => array:1 [▶]
    55 => "mssfu30nisdomain"
    "uidnumber" => array:1 [▶]
    56 => "uidnumber"
    "gidnumber" => array:1 [▶]
    57 => "gidnumber"
    "gecos" => array:1 [▶]
    58 => "gecos"
    "unixhomedirectory" => array:1 [▶]
    59 => "unixhomedirectory"
    "loginshell" => array:1 [▶]
    60 => "loginshell"
    "msexchpoliciesincluded" => array:2 [▶]
    61 => "msexchpoliciesincluded"
    "msexchrecipientdisplaytype" => array:1 [▶]
    62 => "msexchrecipientdisplaytype"
    "msexchversion" => array:1 [▶]
    63 => "msexchversion"
    "msexchrecipienttypedetails" => array:1 [▶]
    64 => "msexchrecipienttypedetails"
    "msrtcsip-primaryuseraddress" => array:1 [▶]
    65 => "msrtcsip-primaryuseraddress"
    "msrtcsip-userenabled" => array:1 [▶]
    66 => "msrtcsip-userenabled"
    "msrtcsip-ismaster" => array:1 [▶]
    67 => "msrtcsip-ismaster"
    "msrtcsip-primaryhomeserver" => array:1 [▶]
    68 => "msrtcsip-primaryhomeserver"
    "msexchalobjectversion" => array:1 [▶]
    69 => "msexchalobjectversion"
    "msexchuseraccountcontrol" => array:1 [▶]
    70 => "msexchuseraccountcontrol"
    "msexchmailboxguid" => array:1 [▶]
    71 => "msexchmailboxguid"
    "dn" => array:1 [▶]
  ]

**Comment by stevebauman** [comment]
Hi @nicro87, you're using the `OpenLDAP` schema. You need to use the `ActiveDirectory` schema:

https://github.com/Adldap2/Adldap2-Laravel/blob/master/src/Config/config.php#L54-L75

Please update this in your `adldap.php` file for your current connection.

**Comment by nicro87** [comment]
Now it works. Thank you for the quick help and reply.
But i think you should update the comments on this section. It was not clear to me that i can use this provider or i have to use it.
