### ISSUE TITLE
create users with different objectclass-es

### ISSUE THREAD

**Issue by GergelyLakatos** [Adldap2/Adldap2-Laravel#532]
-   Laravel Version: 5.5
-   Adldap2-Laravel Version: 4.0.7
-   PHP Version: 7.0.7
-   LDAP Type: OpenLDAP

### Create users with different objectclasses!

Hi again!

I want to ask, that is there any best solution that during the creation I can set the objectclass?
My problem, that every usertype has some unique objectclass, what others have not. I can make a schema for every user, but its not so pretty solution.

Thanks in advance!

Greg

**Comment by stevebauman** [comment]
Hi @GergelyLakatos, just set the `objectclass` attribute on the user when you are making one:

```php
$user = Adldap::make()->user();

$user->objectclass = [
    'top',
    'person',
    'organizationalPerson',
    'user',
];

$user->save();
```

**Comment by Moris1** [comment]
Hi Steve,

When I try to create user with defined object class, I get 
ErrorException
ldap_add(): Add: Object class violation
vendor/adldap2/adldap2/src/Connections/Ldap.php:333

`$cn = 'John Doe';
$user = Adldap::make()->user([
	'cn' => 'John Doe',
	'dn' => "cn=John Doe,ou=users,dc=0xm,dc=net",
	'sn' => 'Grant',
	'mail' => 'craiggrant@g1group.co.uk',
]);

$user->objectclass = [
	'top',
	'posixAccount',
	'inetOrgPerson',
];

$user->save();`
