### ISSUE TITLE
entry creation: schema violation error

### ISSUE THREAD

**Issue by GergelyLakatos** [Adldap2/Adldap2-Laravel#541]
-  Laravel Version: 5.5
-   Adldap2-Laravel Version: 4.0.7
-   PHP Version: 7.0.7
-   LDAP Type: OpenLDAP

### Description:

I would like to make a new group, as the doc says:

```
$group = Adldap::make()->group([...]);
$group->setDn($dn);
$group->objectclass = [...];
$group->save(); // or $group->create();
```

Then I got an error:

> ldap_add(): Add: Object class violation at /vendor/adldap2/adldap2/src/Connections/Ldap.php:277

First I checked the server so, I made a test bash script for testing, and it worked.

Then I logged out the $group And i realize, that there is two "hidden", default variable of group object, and they are defined by the Adldap (not me) : `... "entryuuid":null,"objectsid":null, ...`

My question: Is There any solution to create an entry without these "built-in" variables, so kind of "raw way") ?

Thanks for the response in advance! :)

Greg

**Comment by stevebauman** [comment]
Hi @GergelyLakatos, the model doesn't contain any default attributes besides the `objectclass` attribute:

https://github.com/Adldap2/Adldap2/blob/beae26096aabf13cf649a5261434c6a6414924dd/src/Models/Factory.php#L119-L135

I would look at the array you're passing into the `group()` method, as that array will assign new attributes on the model.

To answer your question, absolutely. To make an "empty" LDAP record, call the `Adldap::make()->entry()` method:

https://github.com/Adldap2/Adldap2/blob/beae26096aabf13cf649a5261434c6a6414924dd/src/Models/Factory.php#L67-L79

If you run into any issues let me know! Closing as using the above method is what you will need to use.
