### ISSUE TITLE
Adldap with Oracle case sensitive

### ISSUE THREAD

**Issue by nicro87** [Adldap2/Adldap2-Laravel#542]
Laravel Version: 5.6
Adldap2-Laravel Version: 4.0
PHP Version: 7.1.10
LDAP Type: Active Directory

### Description:
Hello,
its me again. It's just a little problem. After getting all to work, we found out, that adldap with oracle behaves strange if the samaccountname in ldap is in capital letters and the user log in with lower letters. We have an index without duplicates on this field, so adldap can't insert another user in the database and an error on an violated constraint is thrown.
This is because adldap "thinks" that there is a new user, because mysql doesn't matter about case sensitivity I think?!
It would be nice, if you can update your code. When you check the user with the database you should compare it with strtolower or strtoupper. 
i did not dive deeply into your code and i dont know if its a real issue of adldap or of the oracle package. but you can also use lcase or ucase for oracle to compare it.

Thx in advance.
Nico

**Comment by stevebauman** [comment]
Hi @nicro87,

This is expected when using Oracle or Postgre **as they are case-sensitive** by default - unlike MySQL and MSSQL.

You will need to run a `strtolower()` or `strtoupper()` on usernames prior to authentication.

> It would be nice, if you can update your code. When you check the user with the database you should compare it with strtolower or strtoupper.

This is up to the developer on how they would like their usernames formatted, and it's also extremely easy to resolve so I won't be adding this into Adldap2-Laravel.

Let me know if you still encounter issues after trying the suggestion above, and I will re-open if necessary.
