### ISSUE TITLE
can support lumen?

### ISSUE THREAD

**Issue by lifeblood** [Adldap2/Adldap2-Laravel#547]
- Laravel Version: #.#
- Adldap2-Laravel Version: #.#
- PHP Version: #.#
- LDAP Type:

**Comment by stevebauman** [comment]
Hi @lifeblood, I believe you should be able to use Lumen, have you tried it?

If you're unable to get it working, let me know. I don't use Lumen currently, so I don't have any documentation for setting it up in Lumen.
