### ISSUE TITLE
SSO with Fallback

### ISSUE THREAD

**Issue by darthtaco** [Adldap2/Adldap2-Laravel#55]
Many thanks for your work on this project, and I am especially looking forward to the SSO features.  I want to share a specific use case that might not be factored into the current SSO implementation (I may be wrong).  

I have an internal WAN in which SSO will be a perfect application, as we use Apache for web application serving and AD for authentication.  However, we also have a VPN where remote users, although authenticated to the VPN, may not be authenticated on the domain (eg. when `$_SERVER['REMOTE_USER']` is empty).  While the code allows for a fallback for database authentication, it does not appear to allow a cascading fallback from SSO->AD->Database.  Moreover, we have some users who will be "database-only", who don't have AD credentials at all, so such a fallback would be useful in that case as well.  If `sso_enabled => true` then it would appear that the user MUST be authenticated on the domain or else the login will fail. (See https://github.com/Adldap2/Adldap2/blob/v5.2/src/Adldap.php#L262)

I may not be understanding the code correctly, or the intent here, but I would imagine that having a 'fallback' would be very useful and would appreciate your thoughts.

**Comment by jspringe** [comment]
This isn't an answer, but a question. We have users who also VPN into our network. They are all domain users - does the VPN effect `$_SERVER['REMOTE_USER']`? I haven't rolled out our implementation yet, but it would be nice to have a heads up before I do.

**Comment by stevebauman** [comment]
I'm not sure if this is possible? From my limited SSO experience it seems to be an all or nothing protocol, either you give valid credentials or you're not allowed to access the site. Though this is using IIS.

You can extend the middleware itself and override the `returnNextRequest()` method and implement falling back to AD authentication, and then to database:

https://github.com/Adldap2/Adldap2-Laravel/blob/v1.4/src/Middleware/WindowsAuthenticate.php#L95

I'll see what I can do!

**Comment by darthtaco** [comment]
@jspringe I believe it depends on your VPN setup, but I have limited experience.  Might be something you'll want to test by placing a simple `phpinfo.php` file in your application web root.  If its configured correctly, the `$_SERVER['REMOTE_USER']` will be populated.

@stevebauman My use of the word 'fallback' here may have been inappropriate.  What I meant was, present the user with the login page and allow AD credentials to be entered manually.  Right now, with `use_sso => true` I am presented with a login page but even when I enter valid AD credentials, the user fails to authenticate (presumably because the provider is attempting SSO again, and failing).  Does this make sense?

**Comment by stevebauman** [comment]
@darthtaco I wouldn't use the `use_sso` option, as it's on it's way out for the root Adldap repository. It was a half baked implementation in the core repo and it's going to be removed shortly (in the next major release).

Accessing an internal SSO site from a VPN seems to function normally, though worse case the user is greeted with a username and password login box (at least from my experience). I'm not sure if this will differ depending on your VPN. A domain attached machine visiting your internal site through VPN should be able to utilize SSO?

**Comment by darthtaco** [comment]
@stevebauman Ok, thanks for the heads up. I'll avoid SSO for now. I'm anxious to see how it gets implemented in the future.  Again, many kudos for your ongoing work on this.

**Comment by darthtaco** [comment]
@stevebauman You know what, I think I had just been misreading the intent all along.  The `use_sso` flag was confusing me.  All I need to do is add the Middleware, correct?  I think that will give me the behavior I want.

**Comment by stevebauman** [comment]
@darthtaco Yup you're right, all you need is the Middleware for SSO. You don't need to configure anything through the root Adldap instance,

**Comment by darthtaco** [comment]
Perfect, thanks.  That addresses my issue.
