### ISSUE TITLE
Group search with whereEquals

### ISSUE THREAD

**Issue by GergelyLakatos** [Adldap2/Adldap2-Laravel#550]
-    Laravel Version: 5.5
-   Adldap2-Laravel Version: 4.0.7
-    PHP Version: 7.0.7
-    LDAP Type: OpenLDAP

### Description:
Group search with where has some bug. Check the Reproduce below.

### Steps To Reproduce:

It works fine (finding the group), but it's not a group obj:
```
  public static function getGroupbyId($id) {
    Log::info("GroupRepository getGroupbyId called. id=$id");
    $groupbasedn = env('ADLDAP_GROUP_BASEDN', '');
    $group = Adldap::search()->whereEquals('cn', $id)->in($groupbasedn)->first();
    Log::debug("GroupRepository getGroupbyId result=" . json_encode($group));
    return $group;
  }
```

It returns with a null, but I call with the same id...
```
  public static function getGroupbyId($id) {
    Log::info("GroupRepository getGroupbyId called. id=$id");
    $groupbasedn = env('ADLDAP_GROUP_BASEDN', '');
    $group = Adldap::search()->groups()->whereEquals('cn', $id)->in($groupbasedn)->first();
    Log::debug("GroupRepository getGroupbyId result=" . json_encode($group));
    return $group;
  }
```

#### question

Is there a problem in my code, or is it a bug? :)

Thanks for your response (again) !

**Comment by GergelyLakatos** [comment]
I found a solution, its not the nicest one:
```
      ....
      $members = $group->memberuid;
      if(in_array($userId,$members)) {
        Log::info("User is already added!");
        return 1;
      }
      array_push($members, $userId);
      $group->memberuid = $members;
      Log::debug("updated group: " . json_encode($group));
      if($group->save()) {
      ....
```

**Comment by stevebauman** [comment]
Hi @GergelyLakatos, are you using the `OpenLDAP` schema in your `config/adldap.php` configuration file?

**Comment by GergelyLakatos** [comment]
I use that `'schema' => Adldap\Schemas\OpenLDAP::class`. Unfortunately I have to use an existing ldap, what is not managed by me. There are some specific stuff in there, I guess that cause the anomaly.

**Comment by stevebauman** [comment]
Hi @GergelyLakatos,

I'm not too sure I'm understanding correctly. You mentioned that your above example returns the groups properly but they aren't group objects, but the below example (using the `groups()` scope) does not return groups correctly?

If you're still encountering this, could you clarify in further detail what you're experiencing? I will re-open this issue if you are.
