### ISSUE TITLE
sign in under current user

### ISSUE THREAD

**Issue by wertex** [Adldap2/Adldap2-Laravel#552]
- Laravel Version: 5.6
- Adldap2-Laravel Version: 4.0
- PHP Version: 7.2
- LDAP Type: ActiveDirectory

### Description:
Hi
Tell me, please, whether it is possible using your package to pass the authorization in the application without entering the password of the active (logged-in) user. If so, how is it :) Is it enough just to synchronize username / passwords to a local database with AD. Or it is possible to go to AD at every authorization and compare the password? (is enough for these functions of rights in AD if my account can create a user and reset her password)

**Comment by stevebauman** [comment]
Hi @wertex,

This is definitely supported using the `WindowsAuthenticate` middleware as described here:

https://github.com/Adldap2/Adldap2-Laravel/blob/master/docs/auth.md#middleware

You can use either `NoDatabaseUserProvider` or the `DatabaseUserProvider` with this middleware, so it's up to you if you would like to synchronize data to your local application.

This middleware assumes you know how to setup Single Sign-On with IIS or some other form using Apache etc. You can't use this middleware without first enabling this on your web-server.

**Comment by wertex** [comment]
Спасибо за подробный ответ! Видимо пока придется ограничить доступ к web-сервису по IP, т.к. я еще не работал с IIS и планировал использовать open source решения (linux, docker, etc). Поищу что то для Apache. Либо, если получится, попробую проводить синхронизацию с локальной базой данных пользователей.
