### ISSUE TITLE
Search user by name and password

### ISSUE THREAD

**Issue by GiacomoK** [Adldap2/Adldap2-Laravel#554]
- Laravel Version: 5.2
- Adldap2-Laravel Version: ^4.0
- PHP Version: 5.6
- LDAP Type: ActiveDirectory

I don't know howto search an user by name and password.  
I did not find an example.

**Comment by stevebauman** [comment]
Hi @GiacomoK,

You can search by username but not password. That information is hidden and unreadable in LDAP.
