### ISSUE TITLE
Argument passed to DatabaseUserProvider must be Hasher, instance of Application given

### ISSUE THREAD

**Issue by GiacomoK** [Adldap2/Adldap2-Laravel#555]
- Laravel Version: 5.2
- Adldap2-Laravel Version: 4.0
- PHP Version: 5.5
- LDAP Type: ActiveDirectory

I tried to use "DatabaseUserProvider" to syncronize LDAP users with local users, but I get this error:

Argument 1 passed to ...\Auth\DatabaseUserProvider::__construct() must be an instance of Illuminate\Contracts\Hashing\Hasher, instance of Illuminate\Foundation\Application given, called in ...\ProviderRepository.php on line 146

**Comment by stevebauman** [comment]
Hi @GiacomoK, I'm not sure how you're receiving this error.

How did you register the `DatabaseUserProvider`?

**Comment by GiacomoK** [comment]
Hi,  
In the config.app file i added this in the providers array:  

`'provider' => Adldap\Laravel\Auth\DatabaseUserProvider::class`

**Comment by stevebauman** [comment]
That’s incorrect usage. You’re inserting the database user provided into the wrong configuration file.

Please follow the installation documentation:

https://github.com/Adldap2/Adldap2-Laravel/blob/master/docs/auth.md#installation
