### ISSUE TITLE
Check Connection : Unmute thrown Exception in Adldap\Auth\Guard

### ISSUE THREAD

**Issue by superern** [Adldap2/Adldap2-Laravel#557]
- Laravel Version: 5.6
- Adldap2-Laravel Version: latest
- PHP Version: 7.2
- LDAP Type: OpenLDAP

I can successfully create an authentication And this exception is being logged in laravel.log (default). But I want to catch the exception without getting messed with the vendor's file

```
// We'll mute any exceptions / warnings here. All we need to know
        // is if binding failed and we'll throw our own exception.
        if (!@$this->connection->bind($username, $password)) {
            throw new BindException($this->connection->getLastError(), $this->connection->errNo());
        }
```
This piece of code says that it mutes the exception being thrown. I just want to unmute it. Is there any other way? (again, without messing with the vendor's file)

**Comment by superern** [comment]
found a. 
[solution ](https://github.com/Adldap2/Adldap2-Laravel/issues/264) here.

Just wanted to check my connection.

**Comment by superern** [comment]
found a. 
[solution ](https://github.com/Adldap2/Adldap2-Laravel/issues/264) here.

Just wanted to check my connection.

**Comment by stevebauman** [comment]
Thanks for closing your issue and posting your solution @superern! Really appreciate it :)
