### ISSUE TITLE
Query AD multiple times to get all the users

### ISSUE THREAD

**Issue by AntonyMN** [Adldap2/Adldap2-Laravel#558]
- Laravel Version: #.#
- Adldap2-Laravel Version: #.#
- PHP Version: #.#
- LDAP Type: 

### Description:

The Active Directory by default limits to the first 1000, is it possible have multiple queries to an Active Directory so as to pull like up to, 5000 records?

**Comment by stevebauman** [comment]
Hi @AntonyMN,

You will have to use the `paginate()` method as described in the documentation here:

https://github.com/Adldap2/Adldap2/blob/v8.0/docs/query-builder.md#paginating

The `paginate()` method will retrieve all records from your AD.

```php
$users = Adldap::search()->users()->paginate(1000)->getResults();
```
