### ISSUE TITLE
No handle method exists for the given handler class [mail]

### ISSUE THREAD

**Issue by aleex1848** [Adldap2/Adldap2-Laravel#560]
- Laravel Version: 5.5.40
- Adldap2-Laravel Version: 3.0.9
- PHP Version: 7.1.12
- LDAP Type: ActiveDirectory

### Description:
I'm trying to import LDAP users using the artisan command "adldap:import".
Doing it manually with command "php artisan adldap:import user1234 --no-interaction" is successfull.

But i want to import automatically inside my code so i do this:
\Artisan::call('adldap:import', ['user' => 'user1234' ,'--no-interaction'] );
which is not successful.

The logged error is:
local.ERROR: Unable to import user Wurst Hans. No handle method exists for the given handler class [mail]

When i put a dd(get_class($handler)) in here:
https://github.com/Adldap2/Adldap2-Laravel/blob/8c79a01014dc16137a7e2b0c215663c640182f6d/src/Auth/Importer.php#L76

it shows "Illuminate\Support\Facades\Mail" when calling from code.

Wenn i run Artisan:.call manually from Tinker, the dd is not calling, so i guess my problem i related to this "If the AD Field is a class, we'll assume it's an attribute handler."
The "mail"-Attribute is recognised as having a handler, but it' not a handler. It's  Illuminate\Support\Facades\Mail.

Any hints on this?

Thanks !

**Comment by aleex1848** [comment]
I've no idea what i am doing, but as a workaround i changed 

https://github.com/Adldap2/Adldap2-Laravel/blob/8c79a01014dc16137a7e2b0c215663c640182f6d/src/Auth/Importer.php#L74

to 
`            if (class_exists($adField) && $handler = app($adField) and $adField != 'mail') {`

to get it working.

**Comment by stevebauman** [comment]
Hi @aleex1848, can you post your `sync_attributes` array in your `adldap_auth.php` configuration file?

**Comment by aleex1848** [comment]
Hi @stevebauman. Sure:
`    'sync_attributes' => [

        'username' => 'samaccountname',
        'vorname' => 'givenname',
        'nachname' => 'sn',
        'email' => 'mail',
        'telefon' => 'telephonenumber',
        'fax' => 'facsimiletelephonenumber',
        'extension1' => 'extensionattribute1',
        'extension2' => 'extensionattribute2',
        'extension3' => 'extensionattribute3',
        'title' => 'title',
        'ort' => 'l',
        'adresse' => 'streetaddress',
        'plz' => 'postalcode',
        'raum' => 'physicaldeliveryofficename',
        'personalnr' => 'employeenumber',


    ],
`

**Comment by stevebauman** [comment]
Fixed in [v4.0.8](https://github.com/Adldap2/Adldap2-Laravel/releases/tag/v4.0.8).

Thanks!
