### ISSUE TITLE
Is it possible to get the group's 'info' field/attribute?

### ISSUE THREAD

**Issue by xotik** [Adldap2/Adldap2-Laravel#561]
- Laravel Version: 5
- Adldap2-Laravel Version: 3.0.9
- PHP Version: 7.1
- LDAP Type: ActiveDirectory

### Description:
So I need to retrieve the groups from AD that have a specific word in the 'info' field.

I have no problem retrieving the groups and looping through them, but I haven't found anywhere how to access that extra field or attribute that groups can have.

Is that possible to achieve?

Thanks in advance!

**Comment by stevebauman** [comment]
Hi @xotik,

You can retrieve attributes in a number of ways:

```php
$groups = Adldap::search()->groups()->get();

foreach($groups as $group) {
        // Using `getFirstAttribute()`
        $info = $group->getFirstAttribute('info');

        // Using `getAttribute()`
        $info = $group->getAttribute('info', 0);

        // Using dynamic property:
        $info = $group->info;
 }

// Query for info field:
$groups = Adldap::search()->groups()->where('info', 'contains', 'MyInfo')->get();
```

Let me know if you run into issues, thanks!
