### ISSUE TITLE
admin user within a CN

### ISSUE THREAD

**Issue by joearcher** [Adldap2/Adldap2-Laravel#562]
- Laravel Version: 5.6
- Adldap2-Laravel Version: 4.0.7
- PHP Version: 7.2
- LDAP Type: ActiveDirectory

### Description:
My admin user is within another CN. 
I can get results back from the AD with:

Base DN:
CN=service accounts,DC=example,DC=com
admin user: admin

however I need the base DN to be
DC=example,DC=com
and the admin user to be:
cn=admin,cn=service accounts

In order to be able to get the information I need (this is a 3rd party's AD server over which I have no control).
I've tried using the account_suffix and adding 'cn=service accounts' but this does nothing.

Any suggestions appreciated.

**Comment by stevebauman** [comment]
Hi @joearcher,

Simply set your `admin_username` as the administrators full distinguished name.

The `base_dn` is not applied to usernames upon authentication. The `base_dn` is only for performing queries.

```php
`base_dn' => 'dc=example,dc=com',

'admin_username' => 'cn=admin,cn=service accounts,dc=example,dc=com',
'admin_password' => 'password123',
```

If you'd prefer, you can also set it to admins user principal name:

```php
'admin_username' => 'admin@example.com',
```

Let me know if you run into issues and I can re-open this, thanks!
