### ISSUE TITLE
Use ObjectGUID as identifier in case of name change

### ISSUE THREAD

**Issue by manraf** [Adldap2/Adldap2-Laravel#563]
- Laravel Version: 5.6.26
- Adldap2-Laravel Version: 4.0.7
- PHP Version: 7.2.6
- LDAP Type: ActiveDirectory

### Description:
As far as I understand from the documentation, the `DatabaseUserProvider` identifies a user depending on the field specified in the `eloquent` configuration value. Now, this would imply that upon changing the username (e.g. because of marriage and a resulting different surname), the user would be reimported as new user in the application, right? Can this somehow be changed, so that the user is identified using the unique "objectGUID"?

**Comment by stevebauman** [comment]
Hi @manraf,

No problem! Ldaptools is a definitely a great package.

Would you mind me asking why you switched? I'd like to improve this package in whichever way possible, so understanding which limitations you were hit by using Adldap2 would be great!

**Comment by stevebauman** [comment]
Also, this will be implemented in the next day or so with a brand new major version. I'm almost finished the implementation :smile::

- ed34c10f2a915429216a08afbb6a5be672042e9e
- 40876dfa79197b23b503f6c0f8fc2aa899fd0039
- 47890e2d17906422bd956f29db533352aa49023c
- 71677e4391d95044c3cd2bc94f9f8b097481891f
- 894175282c27fd6989c7e8f370a611544ac87f81
- f4516043c35177a78ed8e9d7920197133a8dab15
- be72ee3b9f9954a2a7bad4969fc22e41b4b7f5d1

Working on updating the docs as we speak with the new database field requirement.

**Comment by manraf** [comment]
> Would you mind me asking why you switched? I'd like to improve this package in whichever way possible, so understanding which limitations you were hit by using Adldap2 would be great!

Hm, it was half a year ago, so unfortunately I can't remember the exact reason. It could be that I couldn't figure out how to do it manually using Adldap2 at that time. Also, I had the "username"-based method implemented manually in ldaptools already before even finding Adldap2, so it probably was easiert for me just changing the existing implementation to use the GUID instead...

Looking forward to v6.0!

**Comment by stevebauman** [comment]
Oh okay I understand, thanks so much for letting me know!

**Comment by stevebauman** [comment]
Implemented.
