### ISSUE TITLE
adldap2 uses wrong configuration 

### ISSUE THREAD

**Issue by puseidr** [Adldap2/Adldap2-Laravel#565]
- Laravel Version: 5.6
- Adldap2-Laravel Version: 4.0.7
- PHP Version: 7.2
- LDAP Type: ActiveDirectory

### Description:

i followed the installation guide  (https://github.com/Adldap2/Adldap2-Laravel#installation), but i always get the "Can't contact LDAP server" error message.
google told me this is an error about wrong admin credentials, but the credentials are correct (tested with raw php: ldap_bind)

I've tried to put the the vars inside the ".env" and even in "\config\adldap.php" but nothing works, the package is always using the vars from "\vendor\adldap2\adldap2-laravel\src\Config\config.php"

### Steps To Reproduce:
found this by dumping the $username and $password variables in  Guard.php at line 84
they are always

**Comment by stevebauman** [comment]
Hi @puseidr,

This sounds like an application issue.

Please try clearing your apps configuration cache using `php artisan config:clear` and try again.

If this still doesn’t work, comment back and I will reopen this issue.

**Comment by puseidr** [comment]
Thanks! the cache reset helped :)
