### ISSUE TITLE
Mutating Attributes on Sync

### ISSUE THREAD

**Issue by celticsdigital** [Adldap2/Adldap2-Laravel#566]
- Laravel Version: 5.6
- Adldap2-Laravel Version: 8.0.0
- PHP Version: 7.1.1
- LDAP Type: ActiveDirectory

Description:

I'm trying to store and sync the "whencreated" AD attribute for users in a dateTime column in my local database.  The time in AD is in a "YYYYMMDDhhmmss.TZ" format (ex. 20180718105600.0Z), which is not a valid datetime string for MySQL.  How can I add a handler function that will mutate the provided "whencreated" attribute into the proper format?  I have the function written, I just don't know where to place it.  I'm looking at the schema docs and can't seem to figure out how.  I also need it to run when I use the sync command (`Artisan::call('adldap:import',['--no-interaction']);`).

Any help would be appreciated.

**Comment by stevebauman** [comment]
Hi @celticsdigital,

You will need to use an [Attribute Handler](https://github.com/Adldap2/Adldap2-Laravel/blob/master/docs/auth.md#attribute-handlers).

To retrieve the LDAP users creation date, there's some built in helper methods for you:

```php
$user->getCreatedAt(); // Returns raw created at time in AD date format
$user->getCreatedAtDate(); // Returns the created at time in a mysql formatted date.
$user->getCreatedAtTimestamp(); // Returns the created at time in a unix timestamp format.
```

https://github.com/Adldap2/Adldap2/blob/v8.0/src/Models/Model.php#L559-L589

Example attribute handler:

```php
namespace App\Handlers;

use App\User as EloquentUser;
use Adldap\Models\User as LdapUser;

class LdapAttributeHandler
{
    /**
     * Synchronizes ldap attributes to the specified model.
     *
     * @param LdapUser     $ldapUser
     * @param EloquentUser $eloquentUser
     *
     * @return void
     */
    public function handle(LdapUser $ldapUser, EloquentUser $eloquentUser)
    {
        $eloquentUser->ldap_created_at = $ldapUser->getCreatedAtDate();
    }
}
```
