### ISSUE TITLE
manipulate ldap attributes when sync

### ISSUE THREAD

**Issue by rbmcgowan** [Adldap2/Adldap2-Laravel#568]
- Laravel Version: 5.4
- Adldap2-Laravel Version: current
- PHP Version: 7.1
- LDAP Type:  OpenLDAP 

### Description: Is there a way to manipulate the ldap attributes when syncing them ?  

eg to be able to something like ...

'sync_attributes' => [
        'mobile' =>str_replace('-', '', 'mobile'),

**Comment by stevebauman** [comment]
Hi @rbmcgowan,

Yes there is: 

https://github.com/Adldap2/Adldap2-Laravel/blob/master/docs/auth.md#syncing-attributes
