### ISSUE TITLE
Password still works after being changed, password sync is off

### ISSUE THREAD

**Issue by Francismori7** [Adldap2/Adldap2-Laravel#571]
- Laravel Version: 5.6
- Adldap2-Laravel Version: latest
- PHP Version: 7.2
- LDAP Type: AD

### Description:
Old password still works, password sync is off.

Not sure why, but my old password, and the new one, both work fine and let me login, weirdly enough...

**Comment by stevebauman** [comment]
Hi @Francismori7, did you have `login_fallback` enabled? This may have been the cause, but if you do have multiple DC's this definitely happens as it's happened to me as well.

**Comment by Francismori7** [comment]
Hey @stevebauman, thanks for the reply.

I had it enabled, yes. However I made sure to delete the user from the DB before trying to login with the old password.

Multiple DCs it is.

Thanks!

**Comment by stevebauman** [comment]
Ohh okay, I see. Thanks for the quick follow up, much appreciated! :smile:
