### ISSUE TITLE
Built from scratch, still does not authenticate. 

### ISSUE THREAD

**Issue by dotmiikee** [Adldap2/Adldap2-Laravel#574]
- Laravel Version: Latest
- Adldap2-Laravel Version: Latest
- PHP Version: 7.2
- LDAP Type: Active Directory

### Description:
I was having troubles getting this to work with my existing application I have been working on. So I decided to follow the "Quick Start - From Scratch" guide with a clean install to see if that would even work. After following the guide, I'm still getting the same issue where  When I attempt to login nothing happens. The page refreshes, but no error messages or anything. Is the guide missing something?

APP_DEBUG is set to True.

**Comment by stevebauman** [comment]
Hi @dotmiikee, the best place to look for issues is inside your log files.

Can you let me know what you see in there?

**Comment by dotmiikee** [comment]
I'm not seeing anything in the **laravel.log** file for ADLDAP errors. 

This is the last log, but it's not related as I changed from MSSQL to MYSQL. 

`[2018-08-17 15:51:17] local.ERROR: SQLSTATE[08001]: [Microsoft][ODBC Driver 17 for SQL Server]TCP Provider: No connection could be made because the target machine actively refused it.
 (SQL: select * from sysobjects where type = 'U' and name = migrations) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 08001): SQLSTATE[08001]: [Microsoft][ODBC Driver 17 for SQL Server]TCP Provider: No connection could be made because the target machine actively refused it.
 (SQL: select * from sysobjects where type = 'U' and name = migrations) at C:\\inetpub\\hero\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php:664, PDOException(code: 08001): SQLSTATE[08001]: [Microsoft][ODBC Driver 17 for SQL Server]TCP Provider: No connection could be made because the target machine actively refused it.
 at C:\\inetpub\\hero\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connectors\\Connector.php:68)

**Comment by stevebauman** [comment]
Hmmm, did you set the auth provider to `adldap` in your `config/auth.php` file?

**Comment by dotmiikee** [comment]
This is what I have set. 


    'providers' => [
        'users' => [
            'driver' => 'adldap',
            'model' => App\User::class,
       ],

**Comment by stevebauman** [comment]
Can you try clearing your config cache by running `php artisan config:clear` then log in again?

Also are you sure you're running v4.0 of Adldap2-Laravel? Just making sure.

**Comment by dotmiikee** [comment]
First Off, thank-you for the continued help on this @stevebauman. I have made a little progress.

By typing in username@example.com I was able to authenticate. I also saw that a user record was created in the users table. 

- [2018-08-17 19:59:45] local.INFO: User 'Last Name, First Name' has been successfully found for authentication. 
- [2018-08-17 19:59:45] local.INFO: User 'Last Name, First Name' is being imported.  
- [2018-08-17 19:59:45] local.INFO: User 'Last Name, First Name' is being synchronized.
- [2018-08-17 19:59:45] local.INFO: User 'Last Name, First Name' has been successfully synchronized.
- [2018-08-17 19:59:45] local.INFO: User 'Last Name, First Name' is authenticating with username: 'CN=LastName\, First Name,OU=CORP,OU=Users,DC=local,DC=com'
- [2018-08-17 19:59:45] local.INFO: User 'Last Name, First Name' has successfully passed LDAP authentication.  
- [2018-08-17 19:59:45] local.INFO: User 'Last Name, First Name' has been successfully logged in.

**Things I noticed**
**

1. If I log out and login again I get a sync error because there is a record already with the same username. `[2018-08-17 20:13:40] local.ERROR: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'username' for key 'users_username_unique' (SQL: insert into `users` (`username`, `name`, `password`, `updated_at`, `created_at`) values (username, LastName, Firstname,`

2. If I add @domain.com to **ADLDAP_ACCOUNT_SUFFIX** and only type in my username and password. It does not log me in. It only works if I type in username@domain.com into the login field. 

**

**Comment by stevebauman** [comment]
No problem @dotmiikee! Glad to help :smile:

What database are you using that stores your `users` table? Postgre / MySQL / MSSQL?

**Comment by dotmiikee** [comment]
MySQL currently.

**Comment by stevebauman** [comment]
That's strange, MySQL is case-insensitive by default...

Can you post your `config/adldap.php` and `config/adldap_auth.php` files with sensitive details omitted?

**Comment by dotmiikee** [comment]
Attached with sensitive details omitted: 
[adldap.txt](https://github.com/Adldap2/Adldap2-Laravel/files/2298697/adldap.txt)
[adldap_auth.txt](https://github.com/Adldap2/Adldap2-Laravel/files/2298701/adldap_auth.txt)

**Comment by dotmiikee** [comment]
Since there are two issues in this ticket, and one of the issues has already been reported. I'm going to close this ticket and open a new issue for the issue that has not been reported. 

1. ADLDAP_ACCOUNT_SUFFIX does not seem to be applying appropriately. I've also see other issues reported for this.
#540 
2. For some reason, if a user already exists in the user's table it fails to log them in with the above SQL constraint violation. This is when I'm using MySQL.
#579
