### ISSUE TITLE
query AD before attempt to authenticate

### ISSUE THREAD

**Issue by yellic** [Adldap2/Adldap2-Laravel#577]
- Laravel Version: 5.6
- Adldap2-Laravel Version: 4.0.7
- PHP Version: 7.2.5
- LDAP Type: 

### Description:
Dear Author,

thanks a lot for this great package for AD connection, it saves so much time for me.
it has work for me well i found an issue, not sure if this is supposed to act like this but i would like to ask.

in file Adldap\Laravel\Resolvers\UserResolver.php
per my understanding:

1. query AD to get all users
2. use byCredentials to find out discover field and its value
3. locate user from all users from the query in step 1
4. use $this->getProvider()->auth()->attempt($username, $password) to authenticate user

the question is for my AD server , it supports search users only if you have bind ldap connection with credentials(username and password) ,then you can get user information. but now i am using an anonymous connection to AD, it is ok to authenticate(auth()->attempt(user,password)), but not ok to fetch user then authenticate.

the solution for me now is that i have set ADLDAP_ADMIN_USERNAME and ADLDAP_ADMIN_PASSWORD in my .env.

is it possible to authenticate without query the AD first?

**Comment by stevebauman** [comment]
Hi @yellic,

> is it possible to authenticate without query the AD first?

Unfortunately not with the current authentication driver. If you require this functionality, you can indeed do so quite easily by utilizing the standard `eloquent` driver and importing your users on the fly:

```php
public function login(Request $request)
{
    // Note: This assumes you're using users `userPrincipalName` to
    // authenticate - which is supported in ActiveDirectory.
    if (Adldap::auth()->attempt($request->email, $request->password)) {
        // Locate the local user record, or instantiate a new one.
        $user = User::firstOrNew(['email' => $request->email]);

        // Set the password to a randomized hashed string (if not set):
        if (is_null($user->password)) {
            $user->password = Hash::make(str_random(16));
        }

        $user->save();

        Auth::login($user):

        return redirect('/dashboard');
    }

    // Failed LDAP authentication.
    return redirect('/login);
}
```
