### ISSUE TITLE
Exception in ldap_bind when user tries to log in with wrong password

### ISSUE THREAD

**Issue by PiotrSa** [Adldap2/Adldap2-Laravel#58]
I have integrated Adldap2/Adldap2-Laravel version 1.3 in my Laravel 5.1 application.
I have inserted my settings in config/adldap.php and changed the authentication driver in config/adldap_auth.php to `'adldap'`. Loggging in seems to work but when an AD user tries to log with wrong password then gets an exception in ldap_bind(): Unable to bind to server: Invalid credentials. I would like the Auth::attempt method returns false in case of wrong password posted.
This are options in my config/adldap.pcp:
```php
return [
    'auto_connect' => true,
    'connection' => Adldap\Connections\Ldap::class,
    'connection_settings' => [
        'account_suffix' => '',
        'domain_controllers' => ['serv1.dom.root.local', 'serv2.dom.root.local'],
        'port' => 389,
        'base_dn' => 'dc=dom,dc=root,dc=local',
        'admin_username' => "DOM\\admin3",
        'admin_password' => 'gh7&sjf',
        'follow_referrals' => false,
        'use_ssl' => false,
        'use_tls' => false,
        'use_sso' => false,
    ],
];
```

**Comment by stevebauman** [comment]
Do you have dubugging enabled in your `config/app.php`?

**Comment by PiotrSa** [comment]
Thank you, I'm still new to php and Laravel. It was debug set to true.

**Comment by stevebauman** [comment]
No problem! This seems to actually be an issue for many people. The reason this occurs is in the [`AdldapServiceProvider`](https://github.com/Adldap2/Adldap2-Laravel/blob/v1.4/src/AdldapServiceProvider.php#L54). I may just remove this.

**Comment by strebl** [comment]
:+1: I think it's a good idea to remove this.

**Comment by stevebauman** [comment]
Yea, causing too much confusion. Going to create a new release now.
