### ISSUE TITLE
Adldap::search()->where('userPrincipalName', '=', $request->username)->get();

### ISSUE THREAD

**Issue by CarlJKashnier** [Adldap2/Adldap2-Laravel#582]
- Laravel Version: 5.6
- Adldap2-Laravel Version: 4.0
- PHP Version: 7.2
- LDAP Type:  ActiveDirectory

### Description:
This query string is not returning the groups object:
Adldap::search()->where('userPrincipalName', '=', $request->username)->get();

I can use Adldap to auth the user. But I am unable to pull the groups.

Thanks!

**Comment by stevebauman** [comment]
Hi @CarlJKashnier,

You need to call `getGroups()` on the returned user, or `getMemberOf()` to retrieve the users group membership distinguished names:

**Note**: Remember to use `first()` or `findBy()` if you're looking to retrieve the first result.

```php
$user = Adldap::search()->findBy('userPrincipalName', $request->username);

if ($user) {
    // Will return a collection of Group models that the user is a member of.
    $groups = $user->getGroups();

    // Will return an array of distinguished names of each group that the user is a member of.
    $groupDns = $user->memberof;
}
```

Here are the docs:

https://github.com/Adldap2/Adldap2/blob/master/docs/models/traits/has-member-of.md
