### ISSUE TITLE
Please release a new tag v4.0.8 that uses ^9.0 instead of ^8.0

### ISSUE THREAD

**Issue by acacha** [Adldap2/Adldap2-Laravel#585]
Currenly we cannot use new features 9.0...See:

https://github.com/Adldap2/Adldap2-Laravel/blob/v4.0.7/composer.json

**Comment by stevebauman** [comment]
Hi @acacha, this is intended, as v9.0 includes breaking changes in the query builder and other aspects that may impact developers Laravel applications.

It will be a `v5.0` release to follow semver.

It will be coming in a couple days!

**Comment by acacha** [comment]
agghh ok sorry! No problem. Thanks!

**Comment by stevebauman** [comment]
No problem, thanks for your patience! :smile:

**Comment by KuenzelIT** [comment]
Hi,

will there be some kind of upgrade guide? I'm also looking forward to this to fix the problem with getting contacts when searching for users.

Thanks!

**Comment by stevebauman** [comment]
Hi @KuenzelIT, there will definitely be an upgrade guide.

There won't be many breaking changes, only small configuration & query builder changes, but they are indeed breaking so it requires a major version.

Thanks for your patience guys!

**Comment by m-lotze** [comment]
v4.0.10 upgraded adldap to v9. 

is this intended? it broke quite a lot...

**Comment by stevebauman** [comment]
Hi @m-lotze, just caught this. Created a release from the `v4.0` branch and it seemed to use the new `composer.json` file using `v9.0`...

I'm going to re-create the release. I might have done this somehow, just not sure how.

**Comment by stevebauman** [comment]
@m-lotze New release is now good to go, sorry about that! 🤦‍♂️

**Comment by jwhulette** [comment]
Is there an update when the v5 will be released?

**Comment by stevebauman** [comment]
Released.
