### ISSUE TITLE
Hash::check changed in 5.7

### ISSUE THREAD

**Issue by m-lotze** [Adldap2/Adldap2-Laravel#586]
- Laravel Version: 5.7
- Adldap2-Laravel Version: 4.0.7
- PHP Version: 7.1
- LDAP Type: ActiveDirectory

See this issue on laravel/framework:
https://github.com/laravel/framework/issues/25578

If the ldap user is not in the database SyncPassword stops with a RuntimeException:
`This password does not use the Bcrypt algorithm.`

If this is not changed in laravel, you probably need to change line 88 at `SyncPassword::passwordNeedsUpdate` from:

`if ($this->canSync()) {`

to:
`if ($current !== null && $this->canSync()) {`

**Comment by stevebauman** [comment]
Thanks for letting me know! Will be patched shortly :)
