### ISSUE TITLE
user table and adldap

### ISSUE THREAD

**Issue by st-claude** [Adldap2/Adldap2-Laravel#59]
Hi Steve

i have another question if you could, i tried asking on the laravel irc chat but no luck (either i didn't understand or they didn't ^^) 

when you login with ldap user, a row is automatically inserted in the DB with some information.
what/where is the file(s) doing this insertion ? 

i would like to write some more information in the DB from the ldap server, and update it on the next login if data from ldap server changes.
again it's not an issue with your great package but i would be glad if you could help, or even point me to some specific documentation :)

thanks a lot

**Comment by achillesp** [comment]
You can add more fields to be synced, by declaring them in the config file adldap_auth.php as sync_attributes.
These are updated on every login.

**Comment by st-claude** [comment]
wow ! it's that simple ! and here i was looking to override a postLogin function or else :)
thanks !

**Comment by st-claude** [comment]
i have another small issue which i don't understand.
i have a field in my AD called "Office" so i added in my sync_attributes : 
`
   'sync_attributes' => [

        'name' => 'cn',
        'email' => 'mail',
        'department' => 'department',
        'room' => 'office',
    ],
`
 but it's like it's not recognized 
it works for any other field (like 'room' => 'mobile' for example) but for office, i just receive null...

i'm able to get the office using the model : 
$room = $user->adldapUser->getPhysicalDeliveryOfficeName();

but for the login, trying to update the users table, it fails

any ideas ?
