### ISSUE TITLE
How to use collection methods?

### ISSUE THREAD

**Issue by tontonsb** [Adldap2/Adldap2-Laravel#591]
- Laravel Version: 5.7
- Adldap2-Laravel Version: 4.0
- PHP Version: 7.2
- LDAP Type: ActiveDirectory

### Description:
It seems that the object returned by `Adldap::search()->users()->get()` is a Laravel collection. However I can't the collection methods to work with these objects.

```
$users = Adldap::search()->users()->get();

$sortedUsers = $users->sortBy('cn');  // $sortedUsers remains unsorted

$names = $users->pluck('givenname'); // $names become a collection of nulls
```

**Comment by stevebauman** [comment]
Hi @tontonsb,

Due to LDAP's multi-valued nature (meaning all attributes are actually contained in their own array), you'll likely need to pass in a callback into the collection methods:

```php
use Adldap\Models\User;

$users = Adldap::search()->users()->get();

$sorted = $users->sortBy(function (User $user) {
    return $user->getCommonName();
});
```

I'm going to see if I can resolve this issue for compatibility though, thanks for bringing this up!

**Comment by tontonsb** [comment]
I was working on this today as well and I found a workaround myself. I am not sure how much of a hack is this, but I noticed that the attributes array is not private. So I can `$users->sortBy('attributes.cn')`. And plucking is also possible, but we might also want to unwrap the inner arrays: `$users->pluck('attributes.cn')->collapse()` or `$users->pluck('attributes.cn')->flatten()`.

**Comment by stevebauman** [comment]
Cool! Thanks for letting me know @tontonsb 

I might have to extend the Laravel collection class with our own Adldap collection class and override some of the methods for compatibility...

What are your thoughts?

Here's an example:

```php
namespace Adldap\Models;

use Illuminate\Support\Collection as BaseCollection;

class Collection extends BaseCollection
{
    public function sortBy($callback, $options = SORT_REGULAR, $descending = false)
    {
        if (is_string($callback)) {
                $callback = function (Model $model) use ($callback) {
                       return $model->getFirstAttribute($callback);
                }
        }

        return parent::__sortBy($callback, $options, $descending);
    }
}
```

**Comment by tontonsb** [comment]
Extending Collection would be best, but it would be a lot of work and many methods would be hard to define, as some of the fields might be actual arrays consisting of multiple entries.

Maybe the most natural and intuitive (with respect to both collections and Adldap) would be to extend Adldap's model (or `HasAttributes` trait?) to expand magic getter - not only provide the actual attributes (`$model->cn`) but also mirror the getters? I mean, could `$model->commonName` return the same as `$model->getCommonName()`?

It could be something like this:

public function __get($key)
{
    $getter = 'get'.studly_case($key);  // supports any case like common_name or commonName
    if (method_exists($this, $getter))
        return $this->$getter();

    return $this->getAttribute($key);
}

I think this would allow `$collection->sortBy('commonName')` and also allow to pluck the actual LDAP arrays like `$collection->pluck('attributes.cn')` in case that is desired.

But I suspect that this might break something backwards in cases where getter names are similar to field names. I am not sure if there are examples of this (don't know the codebase and LDAP that well) or you have avoided name collisions intentionally like in `mail` attribute vs `getEmail()` method.

**Comment by stevebauman** [comment]
Fixed in root Adldap2 instance: https://github.com/Adldap2/Adldap2/commit/f1c75e3f45d326e514c66b9f05de61d4d1cc0a81

Overriding the `valueRetriever()` method was the only thing necessary here so the first attribute of Adldap2 models are returned when using collection methods such as `$users->sortBy('cn')`

New release will be out in the coming days with this patch.

Thanks!
