### ISSUE TITLE
Password reset and mail tokens.

### ISSUE THREAD

**Issue by JustJeremy** [Adldap2/Adldap2-Laravel#596]
- Laravel Version: 5.6
- Adldap2-Laravel Version: 4
- PHP Version: 7.1
- LDAP Type: AD

### Description:

Using LDAP with Active Directory and a fallback of local people that can register.  So, there are 2 sets of users that are either AD or Local. The local users will never be put in AD.   We are going by username and not email.  First issue is that validation obviously bombs out on the reset page as that's looking for email not username.  However, using the email chokes in adldap.  
What I need to do is if the user is part of the AD send them to another page offsite that manages that and if they are local I need to be able to send out that token via email and have them come back to change their password. 
I have modified everything so that you can register and log in with username and not being a part of the AD.  We do not have the ability to do any changes to the AD from this application.  I am binding to a user that only has read access.  Hence, sending them offsite to the AD management area.
Suggestions?

**Comment by JustJeremy** [comment]
Update... So I was able to send email to user (any user in database, AD or Local) I was also able to send in that email a link with token to reset their password.  Haven't check yet if I can reset password yet as my fix to send the reset broke the ldap. 
Basically what I did was in the auth.php file added another provider  for the user class with the eloquent driver.  Having 2 drivers for the same model not so good.  It's using whatever model that is last in the list.   I'd sure hate to have to create a new user class file just for local users, if that's even a good solution here.  
When using the adldap driver I always get hung up at vendor/adldap2/adldap2-laravel/src/Resolvers/UserResolver.php  where it's trying to look for username.  However, I'm looking for password reset with email.  I have found several people not only here but on stack having the same problem, not a single solution yet.   I have no desire to edit core adldap files to try get this to work as I'm sure there will be updates in the future.

**Comment by stevebauman** [comment]
Hi @JustJeremy,

What exception do you receive when requesting a password reset?

Since you're using a `username` instead of `email`, did you update the default Laravel scaffolding to follow suit?

There's no doubt you'll need to modify laravel's default scaffolding for this, but to help you further I need more details.

**Comment by stevebauman** [comment]
Exploring this a bit, there's a ton of ways we could do this. Here's one option.

First, your `users` database table must contain an `email` field so your local users have it available, but have it `nullable` (if desired) for your imported AD users.

For example, we could add a little boolean flag to our `users` database table indicating it is imported from ActiveDirectory with a default value of `false` so your local users will always have it set to `false`:

```php
// database/migrations/2014_10_12_000000_create_users_table.php

/**
 * Run the migrations.
 *
 * @return void
 */
public function up()
{
    Schema::create('users', function (Blueprint $table) {
        $table->increments('id');
        $table->string('name');
        $table->string('username')->unique();
        $table->string('email')->unique()->nullable(); // Optionally nullable if you sync your AD users email.
        $table->string('password');
        $table->boolean('from_ad')->default(false); // Defaulted to false for locally registered app users.
        $table->rememberToken();
        $table->timestamps();
    });
}
```

Update your `sync_attributes` in your `adldap_auth.php` file:

> **Note**: I just added the ability to sync raw PHP values in the `sync_attributes` so you're able to pass in `true` / `false` / `array()` / `int` etc. Right now, you'll likely need to use an [Attribute Handler](https://github.com/Adldap2/Adldap2-Laravel/blob/master/docs/auth.md#attribute-handlers).

```php
// Using raw PHP values (setting `from_ad` to `true`):

'sync_attributes' => [
    'username' => 'samaccountname',

    'name' => 'cn',

    'from_ad' => true,
],

// Using an attribute handler:

'sync_attributes' => [
    \App\Handlers\LdapAttributeHandler::class
],
```

The attribute handler (if needed):

```php
namespace App\Handlers;

use App\User as EloquentUser;
use Adldap\Models\User as LdapUser;

class LdapAttributeHandler
{
    /**
     * Synchronizes ldap attributes to the specified model.
     *
     * @param LdapUser     $ldapUser
     * @param EloquentUser $eloquentUser
     *
     * @return void
     */
    public function handle(LdapUser $ldapUser, EloquentUser $eloquentUser)
    {
        $eloquentUser->username = $ldapUser->getAccountName();
        $eloquentUser->name = $ldapUser->getCommonName();
        $eloquentUser->from_ad = true;
    }
}
```

Update your `resources/views/auth/passwords/email.blade.php`:

```html
<form method="POST" action="{{ route('password.email') }}">
    @csrf
    
    <div class="form-group row">
        <label for="username" class="col-md-4 col-form-label text-md-right">{{ __('Username') }}</label>
        <div class="col-md-6">
            <input id="username" type="text" class="form-control{{ $errors->has('username') ? ' is-invalid' : '' }}" name="username" value="{{ old('username') }}" required>
            @if ($errors->has('username'))
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $errors->first('username') }}</strong>
                </span>
            @endif
        </div>
    </div>
    <div class="form-group row mb-0">
        <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
                {{ __('Send Password Reset Link') }}
            </button>
        </div>
    </div>

</form>
```

As well as your `ForgotPasswordController`:

> **Note**: All we're doing here is overriding the methods `sendResetLinkEmail()` and `validateEmail()` methods. When the form is submitted on the forgot password page, we're just checking if we can find the user in the database with `from_ad` set to `true`. If found, we'll redirect them to a custom end-point.

```php
// app/Http/Controllers/Auth/ForgotPasswordController.php

/**
 * Send a reset link to the given user.
 *
 * @param  \Illuminate\Http\Request  $request
 * @return \Illuminate\Http\RedirectResponse|\Illuminate\Http\JsonResponse
 */
public function sendResetLinkEmail(Request $request)
{
    $this->validateEmail($request);

    // See if the user is from ActiveDirectory.
    if ($user = User::whereFromAd(true)->whereUsername($request->username)->first()) {
        // Redirect to custom page.
        return redirect('/');
    }

    // We will send the password reset link to this user. Once we have attempted
    // to send the link, we will examine the response then see the message we
    // need to show to the user. Finally, we'll send out a proper response.
    $response = $this->broker()->sendResetLink(
        $request->only('username')
    );
    
    return $response == Password::RESET_LINK_SENT
        ? $this->sendResetLinkResponse($request, $response)
        : $this->sendResetLinkFailedResponse($request, $response);
}

/**
 * Validate the username for the given request.
 *
 * @param  \Illuminate\Http\Request  $request
 * @return void
 */
protected function validateEmail(Request $request)
{
    $this->validate($request, ['username' => 'required']);
}
```

**Comment by JustJeremy** [comment]
WOW! That was completely unexpected! I had to step away from the computer for a few days and came back to this email from github. Thank you for going way above and beyond on this question! I would have been very satisfied with a point in the right direction on this.  I will be implementing your solution in the next day or so.   I was actually thinking about going the other way with the flag for a local user but your way make way more sense.  It's much appreciated for what you have done here! Thanks! Jer

**Comment by stevebauman** [comment]
No problem @JustJeremy! Let me know if you run into problems and I'd be glad to help.
