### ISSUE TITLE
Driver [adldap] not supported

### ISSUE THREAD

**Issue by barttt** [Adldap2/Adldap2-laravel#6]
Thought I had the install done, perhaps not..
I am getting this error at startup (laravel 5.1 just updated today)
InvalidArgumentException in Manager.php line 90: Driver [adldap] not supported.
If I change the line in auth.php back to 
 'driver' => 'eloquent',
the site comes to life..
Any ideas what I have done wrong?

**Comment by stevebauman** [comment]
Did you may sure you included all the service providers listed in the installation (including the `AdldapAuthServiceProvider`)? Youll also need to register the Facade listed as well.

**Comment by barttt** [comment]
Yup, did both.
I've never run into this error, so don't understand what laravel is trying to tell me.

**Comment by barttt** [comment]
Wait, I missed the authserviceprovider step.
The vendor:publish just gen'd a adldap_auth.php file, and now it comes to life..
Thank you very much for your help

**Comment by stevebauman** [comment]
Ah great, glad to hear you have it resolved!
