### ISSUE TITLE
Adldap2 + Laravel Passport

### ISSUE THREAD

**Issue by tphil** [Adldap2/Adldap2-Laravel#601]
- Laravel Version: 5.7
- Adldap2-Laravel Version: 
- PHP Version: 7.1
- LDAP Type: Active Directory

### Description:

Dear All,

We are creating an application with Laravel only as a backend and use Laravel Passport for API.
Can we somehow integrate the adldap2 with laravel passport please?

**Comment by tphil** [comment]
Tried with 
`'provider' => Adldap\Laravel\Auth\NoDatabaseUserProvider::class,
`
But receiving error:

`ErrorException: Undefined index: userprincipalname in file app\vendor\adldap2\adldap2-laravel\src\Resolvers\UserResolver.php on line 74
`

**Comment by tphil** [comment]
I managed to bypass this, however i am receiving 
`local.ERROR: Adldap\Auth\BindException: Invalid credentials in vendor\adldap2\adldap2\src\Auth\Guard.php:85
Stack trace:`

I copied the information from preview-sly installed adldap that it works, and still works. Any advice please?

**Comment by stevebauman** [comment]
Hi @tphil,

Since you copied your config over from a working installation, can you try running `php artisan config:clear`?

Also, the error you're receiving is coming from your LDAP server saying that the credentials you're trying to connect with are invalid. I would triple check your username and password that you're binding with.

**Comment by tphil** [comment]
Hi Steve,

I managed to access the active directory - however it looks i am facing another issue with the Model and Token, thank you very much for your response.

Call to undefined method Adldap\Models\User::createToken() 

Perhaps i have to turn back the 'provider' => Adldap\Laravel\Auth\DatabaseUserProvider::class, ? instead of NoDatabase?

**Comment by tphil** [comment]
Hi Steve, i think i messed up during trying, 

```[2018-10-15 13:50:33] local.INFO: User 'Full Name' has been successfully found for authentication.  
[2018-10-15 13:50:33] local.ERROR: Class '\User' not found {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Class '\\User' not found at C:\\xampp\\htdocs\\eit\\app\\vendor\\adldap2\\adldap2-laravel\\src\\Auth\\DatabaseUserProvider.php:191)
[stacktrace]```

**Comment by stevebauman** [comment]
Hi @tphil, no problem! Glad to help :smile:

By default, the Adldap2 `User` model isn't compatible with Passport (which is the model that is returned when using the `NoDatabaseUserProvider`. Though I might change this for v5.0.

If you're looking to use the `NoDatabaseUserProvider` with Passport, I think you'll need to create your own `Schema` to return your own *extended* version of the Adldap2 `User` model.

If you would like to use this provider then you'll have to do a bit of adjustments. Let me know if this is the case.

For your issue you just posted, check your `config/auth.php` file that you've properly included your `app\User` model in the configuration. The output class it's complaining about contains no namespace, which is definitely the problem.

**Comment by tphil** [comment]
it works perfect now !!! :) +1 +1 +1 +1

**Comment by stevebauman** [comment]
Great! Glad you've resolved it :)

**Comment by jasonpjohnson** [comment]
> I managed to bypass this, however i am receiving
> `local.ERROR: Adldap\Auth\BindException: Invalid credentials in vendor\adldap2\adldap2\src\Auth\Guard.php:85 Stack trace:`
> 
> I copied the information from preview-sly installed adldap that it works, and still works. Any advice please?

I'm stumped how did you get past 

ErrorException: Undefined index: userprincipalname in file app\vendor\adldap2\adldap2-laravel\src\Resolvers\UserResolver.php on line 74

I continue to get this and I can't shake it..

**Comment by viniciusraupp** [comment]
> By default, the Adldap2 `User` model isn't compatible with Passport (which is the model that is returned when using the `NoDatabaseUserProvider`. Though I might change this for v5.0.
> 
> If you're looking to use the `NoDatabaseUserProvider` with Passport, I think you'll need to create your own `Schema` to return your own _extended_ version of the Adldap2 `User` model.
> 
I would be very grateful if there was compatibility of Laravel Passport and NoDatabaseUserProvider.

I created my own Schema and a custom User Model and implemented some methods, but unsuccessful.

**Comment by stevebauman** [comment]
Hi @jasonpjohnson, are you able to create a seperate issue and I'll assist you there?

@viniciusraupp, I won't be adding Passport support to the `NoDatabaseUserProvider` because the implementation would require a ton of custom setup since we're not actually storing any record of the authenticated user (hence, not being able to store an actual ID of your user to attach tokens to).

I also can't add default compatibility because I would have to add Laravel Passport as a dependency to the core Adldap2 package, which I definitely don't want to add, since that's heavily opinionated and adds bloat.

You can implement your own schema and override the `userModel()` method to return your own Adldap2 `User` model that includes the Passport methods. However, you'll have to figure out how and where to store your access tokens for a user that does not exist in your database (since you're using the `NoDatabaseUserProvider`:

**Your custom Adldap2 `User` model:**

```php
// app/LdapUser.php

use Laravel\Passport\HasApiTokens;
use Adldap\Models\User as BaseModel;

class LdapUser extends BaseModel
{
    use HasApiTokens;

    /**
     * Get all of the user's registered OAuth clients.
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function clients()
    {
        // return $this->hasMany(Passport::clientModel(), 'user_id');
    }

    /**
     * Get all of the access tokens for the user.
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function tokens()
    {
        // return $this->hasMany(Passport::tokenModel(), 'user_id')->orderBy('created_at', 'desc');
    }

    /**
     * Get the current access token being used by the user.
     *
     * @return \Laravel\Passport\Token|null
     */
    public function token()
    {
        return $this->accessToken;
    }

    /**
     * Determine if the current API token has a given scope.
     *
     * @param  string  $scope
     * @return bool
     */
    public function tokenCan($scope)
    {
        return $this->accessToken ? $this->accessToken->can($scope) : false;
    }

    /**
     * Create a new personal access token for the user.
     *
     * @param  string  $name
     * @param  array  $scopes
     *
     * @return \Laravel\Passport\PersonalAccessTokenResult
     */
    public function createToken($name, array $scopes = [])
    {
        return Container::getInstance()->make(PersonalAccessTokenFactory::class)->make(
            $this->getKey(), $name, $scopes
        );
    }

    /**
     * Set the current access token for the user.
     *
     * @param  \Laravel\Passport\Token  $accessToken
     *
     * @return $this
     */
    public function withAccessToken($accessToken)
    {
        $this->accessToken = $accessToken;

        return $this;
    }
}
```

**Your custom schema:**

```php
use Adldap\Schemas\ActiveDirectory;

class LdapSchema extends ActiveDirectory
{
    public function userModel()
    {
        return App\LdapUser::class;
    }
}
```

**Comment by viniciusraupp** [comment]
Thanks for the feedback, your response makes sense, I will rethink my project
