### ISSUE TITLE
NoDatabaseUserProvider not logging me in

### ISSUE THREAD

**Issue by enviouseli** [Adldap2/Adldap2-Laravel#602]
- Laravel Version: 5.7
- Adldap2-Laravel Version: 4.0
- PHP Version: 7.2
- LDAP Type: Active Directory

### Description:
I am trying to use NoDatabaseUserProvider to avoid LDAP user synchronization to database.
It is working fine with "DatabaseUserProvider" as it logs me in perfectly and create database record for the user as well. But NoDatabaseUserProvider brings me back to the login page with no error or message. Below is my adldap_auth.php. Please advise. Thank You.

```php
return [
    'connection' => env('ADLDAP_CONNECTION', 'default'),
    // 'provider' => Adldap\Laravel\Auth\DatabaseUserProvider::class,
    'provider' => Adldap\Laravel\Auth\NoDatabaseUserProvider::class,
    'rules' => [
        Adldap\Laravel\Validation\Rules\DenyTrashed::class,
    ],
    'scopes' => [
        Adldap\Laravel\Scopes\UpnScope::class,
    ],
    'usernames' => [
        'ldap' => [
            'discover' => 'userprincipalname',
            'authenticate' => 'distinguishedname',
        ],
        'eloquent' => 'username',
        'windows' => [
            'discover' => 'samaccountname',
            'key' => 'AUTH_USER',
        ],
    ],
    'passwords' => [
        'sync' => env('ADLDAP_PASSWORD_SYNC', false),
        'column' => 'password',
    ],
    'login_fallback' => env('ADLDAP_LOGIN_FALLBACK', false),
    'sync_attributes' => [
        //'email' => 'userprincipalname',
        'username' => 'userprincipalname',
        'name' => 'cn',
    ],
    'logging' => [
        'enabled' => true,
        'events' => [
            \Adldap\Laravel\Events\Importing::class => \Adldap\Laravel\Listeners\LogImport::class,
            .....
        ],
    ],
];
```
**auth.php**
```php
return [
    'defaults' => [
        'guard' => 'web',
        'passwords' => 'users',
    ],
    'guards' => [
        'web' => [
            'driver' => 'session',
            'provider' => 'users',
        ],
        'api' => [
            'driver' => 'token',
            'provider' => 'users',
        ],
    ],
    'providers' => [
        'users' => [
            // 'driver' => 'eloquent',
            'driver' => 'adldap',
            'model' => App\User::class,
        ],
    ],
    'passwords' => [
        'users' => [
            'provider' => 'users',
            'table' => 'password_resets',
            'expire' => 60,
        ],
    ],
];
```

**Comment by stevebauman** [comment]
Hi @enviouseli, please fill in your LDAP type. I will re-open once updated.

I ask for this information to help debug faster and easier.

**Comment by enviouseli** [comment]
I am using windows and active directory.

**Comment by enviouseli** [comment]
below is my login function of logincontorller. Also is not logging events into my log file, but my own ones are working like "Log::infor('asdfasdf'); below in the code.
```php
public function login(Request $request)
    {
        $credentials = $request->only($this->username(), 'password');
        $username = $credentials[$this->username()];
        $password = $credentials['password'];
        Log::info('log is working..');
        if ( Adldap::auth()->attempt($username, $password, $bindAsUser = false) ) {
            
            $user = \App\User::where($this->username(), $username) -> first();
            if (!$user) {
                $user = new \App\User();
                $user->username = $username;
                $user->password = '';
                $sync_attrs = $this->retrieveSyncAttributes($username);
                foreach ($sync_attrs as $field => $value) {
                    $user->$field = $value !== null ? $value : '';
                }
            }
            $this->guard()->login($user, true);
            return redirect()->to('home')
                ->withMessage('Logged in!');
        }
        
        return redirect()->back()->withMessage('IT WORKS!');
    }
```

**Comment by stevebauman** [comment]
The logging feature is only when using the authentication driver of this package. If you authenticate against your LDAP server manually, logging is not done.

What session driver are you using?

**Comment by enviouseli** [comment]
authentication driver is set to adldap as you can see it the adldap_auth.php.
below is my session settings
```php
SESSION_DRIVER=file
SESSION_LIFETIME=120

**Comment by stevebauman** [comment]
Check to see if any session files are being created in the storage folder. If you don't see any files being created after logging in and being returned to the login page as you've mentioned, then try a different session driver, such as `database`.

If there are files being created for sessions, can you post the content of one of the files here?

**Comment by enviouseli** [comment]
yes it does create a file under storage/framwork/session. Setting were
    'provider' => Adldap\Laravel\Auth\NoDatabaseUserProvider::class,
and 
SESSION_DRIVER=database

below is the content of that file.
```json
a:5:{s:6:"_token";s:40:"JsdEWOUbm9Y3ANeyXD3B4kfKhCOcOIxk5UdHE3WD";s:6:"_flash";a:2:{s:3:"old";a:0:{}s:3:"new";a:0:{}}s:9:"_previous";a:1:{s:3:"url";s:27:"http://localhost:8000/login";}s:50:"login_web_59ba36addc2b2f9401580f014c7f58ea4e30989d";i:2;s:3:"url";a:1:{s:8:"intended";s:26:"http://localhost:8000/home";}}

**Comment by enviouseli** [comment]
issue in the above program is the "$this->guard()->login($user, true);" line in the login function of Login Controller. "true" in the line sets "remember token" parameter, which creates the database record. If you set it to false it will not create the record, and also will not login the user. So all in all it is still not working. will have to think about a work around :(.

**Comment by stevebauman** [comment]
Hi @enviouseli, apologies for the long reply.

This actually won't work the way you've configured it. You're setting your Laravel auth driver to `adldap`, but you're trying to authenticate normally using `guard()->login()` and are passing that a Eloquent model instance. 

It appears you're searching for a user in your LDAP directory, then creating them a user account and manually logging them in. I'm somewhat confused since you're setting the provider to `NoDatabaseUserProvider`, but you are indeed using a database and are manually importing users into your local database from an LDAP user record.

If you want it to work with your current code right now, you can remove the usage of the Adldap2-Laravel auth driver in your `config/auth.php` file:

    'providers' => [
        'users' => [
            'driver' => 'eloquent', // Changed back from 'adldap'
            'model' => App\User::class,
        ],
    ],

If you're still experiencing some confusion with the auth driver, let me know and I will re-open this. Thanks!
