### ISSUE TITLE
Get ldap model for users (not the current authenticated one)

### ISSUE THREAD

**Issue by tobysommer** [Adldap2/Adldap2-Laravel#603]
- Laravel Version: v5.7.9
- Adldap2-Laravel Version: v4.0.10
- PHP Version: 7.2.10
- LDAP Type: Active Directory

### Description:

Hi!

Is it possible to (eager) load the `ldap` relation for each user? E.g. on a `index`-view, where each regular Eloquent-User is listed, I want to display some of their ldap information. Or on a `show`-view, where I see every (Eloquent) detail but ALSO some of their `ldap` details?!

### Steps To Reproduce:

- Basic setup (as per docs)
- create `UserController` and `views/users/index.blade.php` view
- create method
```php
public function index()
{
    $users = User::all();

    return view('users.index', compact('users'));
}
```
- within `views/users/index.blade.php` the `$user->ldap` is always `null`:
```php
@foreach ($users as $user)
    <pre><code>{{ var_dump($user->ldap) }}</code></pre>
@endforeach
```

Thanks in advance :)

**Comment by stevebauman** [comment]
Hi @tobysommer,

Unfortunately there is no option right now to eager load LDAP results with users. The `ldap` property is only set for the currently authenticated user when you have the `Adldap\Laravel\Traits\HasLdapUser` trait on your `User` model.

This would difficult to determine what the foreign relation should be. Your `users` database table would likely need to store an LDAP identifier (such as distinguished name, GUID, SID etc.).

You'll have to retrieve LDAP records for each user you've queried for in your database. Here's an example for retrieving LDAP users if you're syncing their sAMAccountName to the `username` column in your `users` database table:

```php
$users = User::all();

$names = $users->map->username->toArray();

$ldapUsers = Adldap::search()->whereIn('samaccountname', $names)->get();

$users->map(function (User $user) use ($ldapUsers) {
    $user->ldap = $ldapUsers->where('samaccountname', $user->username)->first();
});
```

Let me know if this didn't answer your question, or if you need more information and I'll re-open this.

Thanks! :smile:
