### ISSUE TITLE
Adminless authentication

### ISSUE THREAD

**Issue by AndreaRunner** [Adldap2/Adldap2-Laravel#604]
- Laravel Version: 5.7.10
- Adldap2-Laravel Version: 4.0
- PHP Version: 7.2.11
- LDAP Type: Active Directory

### Description:
All works fine if i set admin_username and admin_password !
NB: the user i try to authenticate is or could be the same that i insert in admin fields

Is possible do not use admin account ?
Thanks in advance

**Comment by stevebauman** [comment]
Hi @AndreaRunner,

The default authentication driver built into Adldap2 doesn't support authenticating without configuring a `admin_username` and `admin_password`.

You can definitely do this yourself quite easily using Adldap2 on it's own:

```php
use Adldap\Adldap;
use Illuminate\Support\Facades\Auth;

public function login(Request $request)
{
    // Attempt LDAP authentication.
    if (Adldap::auth()->attempt($request->username, $request->password)) {
        // Passed LDAP authentication, retrieve their LDAP model:
        $ldap = Adldap::search()->users()->where('samaccountname', $request->username])->first();

        // Now lets try to locate or create their account:
        $user = User::firstOrNew(['username' => $request->username]);
        
        // Sync their attributes
        $user->name = $ldap->getCommonName();
        $user->department = $ldap->getDepartment();

        $user->save();

        Auth::login($user);

        return redirect()->route('dashboard');
    }

     // Auth failed. Redirect:
    return redirect()->route('login');
}
```

Now for the above to work with ActiveDirectory, the authenticating users username would either have to be their full distinguished name (which is ugly and unlikely to be possible since you can't predict what it will be), or their `userPrincipalName` such as `johndoe@company.org`.

**Comment by AndreaRunner** [comment]
Hi @stevebauman,
since the user i try to authenticate have admin rights, i put empty in admin variables in config/adldap.php:
'admin_account_prefix' => env('ADLDAP_ADMIN_ACCOUNT_PREFIX', ''),
'admin_account_suffix' => env('ADLDAP_ADMIN_ACCOUNT_SUFFIX', ''),    
'admin_username' => env('ADLDAP_ADMIN_USERNAME', ''),
'admin_password' => env('ADLDAP_ADMIN_PASSWORD', ''),
and setting the same variables with the user input:
public function login(Request $request){            
        **config(['adldap.connections.default.connection_settings.admin_account_prefix' => 'mydomain\\']);
        config(['adldap.connections.default.connection_settings.admin_username' => $request->username]);
        config(['adldap.connections.default.connection_settings.admin_password' => $request->password]);**

        if(Auth::attempt($request->only(['username', 'password']))) {
            $user = Auth::user();
            
            return redirect()->to('home')
            ->with('message','Logged in!')
            ->with('alert','alert-success');
        }
       
        return redirect()->to('login')
        ->with('message','Hmm... Your username or password is incorrect')
        ->with('alert','alert-danger');
        
    }

Everything works perfect !

**Comment by stevebauman** [comment]
Great glad to hear you got it working @AndreaRunner! Thanks for following up :smile:
