### ISSUE TITLE
Import into local database - Should imported passwords work?

### ISSUE THREAD

**Issue by Dmarthaller** [Adldap2/Adldap2-Laravel#608]
- Laravel Version: 5.7
- Adldap2-Laravel Version: 4.0
- PHP Version: 7.1
- LDAP Type: Windows AD

### Description:
I have configured the software to continue to use the database user class.
  'provider' => Adldap\Laravel\Auth\DatabaseUserProvider::class,

I have configured the software to Sync passwords to the local database
'sync' => env('ADLDAP_PASSWORD_SYNC', true),

i'm running the simple importer:
php artisan adldap:import

I have successfully imported the users and user attributes. Should I at this point be able to log into the system with the same password that the user has setup within AD? 

This is not working. I'm not even sure how this package could set the password correctly as I would guess that it's also encrypted in AD, how is this moved to Laravel with bcyrpt encyrption?

Should I even expect this to work or will the imported user need to manually set their password upon their first login?

**Comment by stevebauman** [comment]
Hi @Dmarthaller, passwords are not retrieved from AD, as this is impossible.

The password sync feature doesn't relate with the importer. When password sync is enabled and a user successfully logs into your application, their `password` that they used is hashed and synced with their local `User` database model.

This feature basically allows you to have the possible flexibility of your directory going down, or removing LDAP authentication in the future and your users would be able to log into your application with the last password they used.

When importing users, a random 16 character string is hashed and set on the users model.

If you're unable to login using your configured LDAP connection, then something may be amiss with your `adldap_auth.php` configuration.
