### ISSUE TITLE
Question - Will this package support any LDAP server?

### ISSUE THREAD

**Issue by bhanu2217** [Adldap2/Adldap2-Laravel#609]
### Description:
Will this package support any LDAP services as listed here 
https://en.wikipedia.org/wiki/Directory_service

Both Microsoft Active directory and open LDAP will be supported?

**Comment by stevebauman** [comment]
Hi @bhanu2217,

Out of the box there is support for ActiveDirectory, OpenLDAP and FreeIPA using the included schema's in the core [Adldap2](https://adldap2.github.io/Adldap2/#/setup?id=schema) package.

You can extend the base schema and include it in your configuration if you need another unsupported directory distro.
