### ISSUE TITLE
Laravel version 5.2.22 error: Class adldap does not exist

### ISSUE THREAD

**Issue by baaskoen** [Adldap2/Adldap2-Laravel#61]
I followed the instructions for Laravel 5.2 but im getting the following error: 

> ReflectionException in Container.php line 738: Class adldap does not exist

**Comment by stevebauman** [comment]
Try performing a `php artisan clear-compiled` and try again. Also ensure you've inserted the `Adldap\Laravel\AdldapServiceProvider::class,` into your `config/app.php`.

**Comment by baaskoen** [comment]
I haven't built anything custom. Just when I attempt to authenticate an user im getting that error. I have tried your suggestions but that didn't help.

**Comment by stevebauman** [comment]
Where in your application are you authenticating? Ensure that you also have the `Adldap\Laravel\AdldapAuthServiceProvider::class,` inside your `config/app.php`.

Can you also post your `config/auth.php` file?

**Comment by baaskoen** [comment]
Ah my bad, I had to include `Adldap\Laravel\AdldapServiceProvider::class,` in my `config/app.php aswell`. Thanks for answering!

**Comment by stevebauman** [comment]
No problem! Glad you've resolved it.

**Comment by riskinovitasari** [comment]
in my case, i get error message **Class 'Adldap\Laravel\AdldapServiceProvider' not found**.  i've tried to run `php artisan clear-compiled` and `php artisan cache:clear`  but still didn't work.

**Comment by stevebauman** [comment]
Hi @risknovitasari, please try running `composer dump-autoload` and try again. It sounds like composer isn't autoloading Adldap2.

**Comment by riskinovitasari** [comment]
i run `composer dump-autoload`, then i get **PHP temp directory (C:\Users\Buppub\AppData\Local\Temp) does not exist or is not writable to Composer.
Set sys_temp_dir in your php.ini Generating autoload files**

then, when i try to run `php artisan vendor:publish` , i still get error message like Class 'Adldap\Laravel\AdldapServiceProvider' not found. Um, i follow tutorial [https://github.com/Adldap2/Adldap2-Laravel/blob/master/docs/quick-start.md](url) and i stuck on steps 10. what should i do?

**Comment by riskinovitasari** [comment]
ah, I've found the problem. I didn't install the adldap package correctly. Thanks for answering @stevebauman

**Comment by kordhrufan** [comment]
How exactly you installed the adldap package? By command or moving the files you downloaded? I'm having the same error as you, and did the `composer dump-autoload` Did I have to move the files I download from the code or the command do that for me?

**Comment by stevebauman** [comment]
@kordhrufan, you need to follow the install instructions. You don't need to move any files at all.

All you do is insert Adldap2 in your applications `composer.json` file:

```json
"adldap2/adldap2-laravel": "3.0.*",
```

Then run `composer update`. Adldap2 and Adldap2-Laravel will be downloaded into your project automatically inside the `vendor` folder.

Then you'll insert the service provider into your `app/config.php` file:

```
Adldap\Laravel\AdldapServiceProvider::class,
```

If you're not experienced with composer or Laravel, I would highly suggest getting to know it through some tutorials first so you know what is going on behind the scenes.

As always, if there's any bugs / issues with the package itself, please create an issue, thanks! :)
