### ISSUE TITLE
rename 'connection_settings' to 'settings'

### ISSUE THREAD

**Issue by Resin01** [Adldap2/Adldap2-Laravel#610]
- Laravel Version: 5.7
- Adldap2-Laravel Version: 5.0
- PHP Version: 7.2
- LDAP Type: ActiveDirectory

### Description:
Upgrade from 4.* to 5.* mentions nothing about needing to rename 'connection_settings' to 'settings' in ldap.php (former adldap.php)

### Steps To Reproduce:
Upgrade from 4.* to 5.0

**Comment by stevebauman** [comment]
Thanks @Resin01! I'll add this to the upgrade guide and close this once done.
