### ISSUE TITLE
NoDatabaseUserProvider work... but redirect to login again

### ISSUE THREAD

**Issue by Albvadi** [Adldap2/Adldap2-Laravel#615]
- Laravel Version: 5.7.12
- Adldap2-Laravel Version: 5.0.0
- PHP Version: 7.1.15
- LDAP Type: ActiveDirectory

### Description:
Hi, how long ago I had no problems! :sweat_smile:

I had configured a new project, with last version of Laravel and last version here, with NoDatabaseUserProvider.

I configured all the data refered to ldap, try to login, but always I´m redirected to the login page without errors...

Same as you suggested in https://github.com/Adldap2/Adldap2-Laravel/issues/531#issuecomment-383548855, I inserted `dd($user);` just after the `Resolver::byCredentials($credentials)` method:

```php
   /**
     *  {@inheritdoc}
     */
    public function retrieveByCredentials(array $credentials)
    {
        if ($user = Resolver::byCredentials($credentials)) {
	        
        	dd($user);
            
        	Event::fire(new DiscoveredWithCredentials($user));

            return $user;
        }
    }
```
The `$user` variable contains all the data correctly from my AD,
![image](https://user-images.githubusercontent.com/6285255/48143947-31a7c480-e2b0-11e8-8e4d-f779f15c5931.png)

but I´m redirected to the login page without error.

There are´nt any log entry, no errors and no sucessfull bind...

Any idea what can I test??

Thank you!

**Comment by stevebauman** [comment]
Hi @Albvadi,

What session driver are you using?

**Comment by Albvadi** [comment]
```env
SESSION_DRIVER=file
```
The file is create in the `storage/session` path with serialized json: token, url, old, new...

**Comment by stevebauman** [comment]
Does the session file that is created contain the GUID of the user authenticating?

**Comment by Albvadi** [comment]
Solved!
Was a problem with the `LDAP_ACCOUNT_SUFFIX`` property...

Sorry for waste your time and thanks as always for your support!! :smiley:
