### ISSUE TITLE
Localhost and extern LDAP-Server

### ISSUE THREAD

**Issue by liqSTAR** [Adldap2/Adldap2-Laravel#618]
- Laravel Version: 5.7
- Adldap2-Laravel Version: 5.0
- PHP Version: 7.2.5
- LDAP Type: ActiveDirectory

### Description:
Followed the instruction: Made from scratch by using usernames and discover on samaccountname.

Error trying to login:
These credentials do not match our records.

First of all: Is it even possible to run the application local and try to Auth::attempt to an LDAP-Server which is not local (extern)?

I'm trying to authenticate to the LDAP-server but no matter what i change in the settings its still the same error. If im changing the correct admin credentials the system isnt even pushing any errors. And its hard to debug for me.

So i tried: php artisan adldap:import but its not finding any users.

So whats the best way to even check if the connection is right and the system finds the server?

### Steps To Reproduce:
https://adldap2.github.io/Adldap2-Laravel/#/auth/introduction?id=quick-start-from-scratch
with username instead of email, samaccountname as discover key.`
```
    'usernames' => [
        'ldap' => [
//            'discover' => 'userprincipalname',
            'discover' => 'samaccountname',
            'authenticate' => 'distinguishedname',
        ],
        'eloquent' => 'username',
        'windows' => [
            'discover' => 'samaccountname',
            'key' => 'AUTH_USER',
        ],
    ],
...
    'sync_attributes' => [
        'username' => 'samaccountname',
        'name' => 'cn',
    ],
```

**Comment by liqSTAR** [comment]
Fixed it myself. Me dumb forgot to revert the magic keys which are checking the entries in the env. So the system hooked with the default ones.

But overall, for me it was important to set the suffix @company.local behind my admin username. So my env entry where:

```
LDAP_AUTO_CONNECT=true
LDAP_HOSTS=company.dyndns.org
LDAP_PORT=389
LDAP_TIMEOUT=10
LDAP_BASE_DN=dc=company,dc=local
LDAP_USERNAME=admin@company.local
LDAP_PASSWORD=reallylongpassword
```

**Comment by liqSTAR** [comment]
Dont know what happend but now im keeping getting this error:

Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_ERROR)
Call to undefined method Illuminate\Events\Dispatcher::fire()

straight after hitting "Login" button.

**Comment by stevebauman** [comment]
Hi @liqSTAR, it seems you're using `dev-master` of the Laravel framework. 

This would likely be the cause, and I wouldn't personally recommend it as changes could occur any time using `dev-master` and could break your entire application (you may be aware of this already, I'm not sure).

Can you use the latest stable and let me know if you still encounter issues? I'll re-open this if you do.

Thanks!

**Comment by liqSTAR** [comment]
Still the same problem. Still getting the Dispatcher::fire() error, that the method is undefined.

![image](https://user-images.githubusercontent.com/12783126/48694928-fd9c9f80-ebdd-11e8-9cd0-b0a106d95972.png)

So how do i set the correct version in my composer.json?

**Comment by liqSTAR** [comment]
i guess 5.8 was still?

Changed it to 5.7 and cloned the 5.7 framwork straight from git. Sorry I'm rubbing ducking so hard :D
