### ISSUE TITLE
Prevent sync of existing users

### ISSUE THREAD

**Issue by HepplerDotNet** [Adldap2/Adldap2-Laravel#622]
- Laravel Version: 5.7
- Adldap2-Laravel Version: 9.1.3
- PHP Version: 7.2.11
- LDAP Type: ActiveDirectory

Hi,
I want to sync some attributes from AD to my database, but only on first login!
If the user already exists in database, the record should not be updated.
Can't find any soution in the docs.

**Comment by stevebauman** [comment]
Hi @HepplerDotNet,

You can use an [Attribute Helper](https://adldap2.github.io/Adldap2-Laravel/#/auth/setup?id=attribute-handlers) to perform this:

```php
namespace App\Ldap;

use App\User as EloquentUser;
use Adldap\Models\User as LdapUser;

class LdapAttributeHandler
{
    /**
     * Synchronizes ldap attributes to the specified model.
     *
     * @param LdapUser     $ldapUser
     * @param EloquentUser $eloquentUser
     *
     * @return void
     */
    public function handle(LdapUser $ldapUser, EloquentUser $eloquentUser)
    {
        // Only sync attributes if the user does not already exist in our database.
        if (! $eloquentUser->exists) {
            $eloquentUser->email = $ldapUser->getEmail();
            $eloquentUser->name = $ldapUser->getCommonName();

            // etc...
        }
    }
}
```

Your `config/ldap_auth.php` file:

```php
'sync_attributes' => [
    \App\Ldap\LdapAttributeHandler::class
],
```

**Comment by stevebauman** [comment]
However, keep in mind if their email changes (or whatever attribute you're using as a users username), this won't take that into account as a new account will be created for them in your app's database since it won't know what their previous username was.
