### ISSUE TITLE
[Question] How to allow users which are locked in AD?

### ISSUE THREAD

**Issue by HepplerDotNet** [Adldap2/Adldap2-Laravel#628]
- Laravel Version: 5.7
- Adldap2-Laravel Version: 5.0.1
- PHP Version: 7.2.11
- LDAP Type: ActiveDirectory

Hi,
my goal is to provide a self-service for our AD users. If account is locked in AD (e.g. too many bad password attempts), user should login to portal an unlock themselve. Locked doesn't mean disabled in this context.

But currently if user is locked in AD he can't login to portal: User 'XXX' has failed LDAP authentication.

Is it even possible to allow locked users?

**Comment by stevebauman** [comment]
Hi @HepplerDotNet,

Unfortunately ActiveDirectory will always return false with an LDAP bind when a user account is locked, or has expired.

You will either have to have an alternate authentication route or have the users go into some type of "account recovery" process to verify their identity and perform a password reset themselves.

For example, you could use the password sync option, so their last password that they logged in successfully with would be stored in your local users database table, so you could ask users to perform a login (against the default `eloquent` authentication guard) with the last password they used to login to your application and access the reset utility.

Though, this would require the users to know their last used password in your application.

An ideal scenario (in my opinion) is to have users setup some security questions and answers upon their first successful login into your application (you would have to add this security question functionality yourself) and then when their AD account becomes locked out, the user could visit your AD self-service portal and you could check these security questions and log the user into their account manually (using `Auth::login($user)`) to reset their password after performing verification on these questions.

I hope this helps you in some way, but if you want to have any further discussion about this, feel free to leave a comment and I'll re-open this, thanks!

**Comment by HepplerDotNet** [comment]
@stevebauman to extend DatabaseUserProvider I have written an interface and check for this interface in AdldapAuthServiceProvider see #629
