### ISSUE TITLE
Error on start application

### ISSUE THREAD

**Issue by netopvh** [Adldap2/Adldap2-Laravel#63]
Need help! You are showing an error message on my application.

I've done all necessary configuration, but not yet worked.

ErrorException in CreatesUserProviders.php line 40:
Authentication user provider [] is not defined. (View: E:\Projetos\PHP\scac\resources\views\layouts\app.blade.php) (View: E:\Projetos\PHP\scac\resources\views\layouts\app.blade.php)

Here is the page where the error occurs. app.blade.php

`@if (auth()->check())
                        <li><a href="{{ url('/login') }}">Login</a></li>
                        <li><a href="{{ url('/register') }}">Register</a></li>
                    @else
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                 <span class="caret"></span>
                            </a>

                            <ul class="dropdown-menu" role="menu">
                                <li><a href="{{ url('/logout') }}"><i class="fa fa-btn fa-sign-out"></i>Logout</a></li>
                            </ul>
                        </li>
                    @endif`

My app.php config

`        /*
         * Application Service Providers...
         */
        App\Providers\AppServiceProvider::class,
        App\Providers\AuthServiceProvider::class,
        App\Providers\EventServiceProvider::class,
        App\Providers\RouteServiceProvider::class,
        Adldap\Laravel\AdldapServiceProvider::class,
        Adldap\Laravel\AdldapAuthServiceProvider::class,`

**Comment by netopvh** [comment]
Sorry , most could not format the code on github editor .

**Comment by stevebauman** [comment]
Looks like you haven't configured your `config/auth.php` file correctly.

Please follow the relevant guide and let me know if you still encounter issues:

For Laravel 5.1:
https://github.com/Adldap2/Adldap2-Laravel#laravel-51

For Laravel 5.2:
https://github.com/Adldap2/Adldap2-Laravel#laravel-52

**Comment by netopvh** [comment]
Thank you!!

**Comment by stevebauman** [comment]
No problem!
