### ISSUE TITLE
Auth:attempt() always fails

### ISSUE THREAD

**Issue by FroeMic** [Adldap2/Adldap2-Laravel#642]
- Laravel Version: 5.5
- Adldap2-Laravel Version: 4.0
- PHP Version: 7.1
- LDAP Type: OpenLDAP

### Description:

My problem is that `Auth::attempt()` does not authenticate the user. However the ldap configuration seems to work as `Adldap::auth->attempt()` works as expected.

```
// returns false, but should return true
Route::get('auth/test0', function (Request $request) {
        dd(Auth::attempt(['dn' =>'CN=Michael Froehlich,OU=XX,dc=internal,dc=YYY,dc=de', 'password' => 'ZZZ']));
});

// returns true and should return true
Route::get('auth/test1', function (Request $request) {
        dd(Adldap::auth()->attempt('CN=Michael Froehlich,OU=XX,dc=internal,dc=YYY,dc=de', 'ZZZ'));
});
```

I have wasted hours into investigating why the heck it won't work, but could not figure it out yet. I have noticed that `Auth::attempt()` never triggers the attempt function in Adldap2/Auth/Guard.php.

https://github.com/Adldap2/Adldap2/blob/a368bebad714c0c13f1a6a19d76aa3dc5e553b9b/src/Auth/Guard.php#L58

 Investigating further I found the issue potentially in the `retrieveByCredentials()` function of the DatabaseUserProvider class: The comparison `($user instanceof User)` evaluates to false, even though `Resolver::byCredentials($credentials);` returns a result from the LDAP server.

https://github.com/Adldap2/Adldap2-Laravel/blob/8d6a47feb490f0e3e090f5102728455caaed0371/src/Auth/DatabaseUserProvider.php#L103

Any ideas why this could be the case?

**Comment by stevebauman** [comment]
Hi @FroeMic,

I'd be glad to help you out with this.

Did you set the `schema` option to `OpenLDAP` described [here](https://adldap2.github.io/Adldap2/#/setup?id=schema)?

**Comment by FroeMic** [comment]
I am not 100% sure here, but I suspect that the problem arises, because the object returned by `Adldap2/Guard.php->attempt()`is of type `Adldap\Models\Entry` and not of type `Adldap\Models\User;` (see issue description).

This is possibly related to https://github.com/Adldap2/Adldap2-Laravel/issues/21

The object returned by the OpenLDAP Server looks as follows:

```
Entry {#356 ▼
  +exists: true
  #query: Builder {#358 ▶}
  #schema: OpenLDAP {#350}
  #modifications: []
  +dateFormat: "Y-m-d H:i:s"
  #timestampFormat: "YmdHis.0Z"
  #attributes: array:19 [▼
    "userpassword" => array:1 [▼
      0 => "{SSHA}XXX" //redacted
    ]
    0 => "userpassword"
    "distinguishedname" => array:1 [▼
      0 => "CN=Michael Froehlich,OU=2016 Spring,OU=Classes,OU=People,OU=CDTM,DC=internal,DC=cdtm,DC=de"
    ]
    1 => "distinguishedname"
    "samaccountname" => array:1 [▼
      0 => "froehlichm"
    ]
    2 => "samaccountname"
    "name" => array:1 [▼
      0 => "Michael Froehlich"
    ]
    3 => "name"
    "givenname" => array:1 [▼
      0 => "Michael"
    ]
    4 => "givenname"
    "objectclass" => array:4 [▼
      0 => "organizationalPerson"
      1 => "person"
      2 => "extensibleObject"
      3 => "top"
    ]
    5 => "objectclass"
    "cn" => array:1 [▼
      0 => "Michael Froehlich"
    ]
    6 => "cn"
    "sn" => array:1 [▼
      0 => "Froehlich"
    ]
    7 => "sn"
    "mail" => array:1 [▼
      0 => "michael.froehlich@cdtm.de"
    ]
    8 => "mail"
    "dn" => array:1 [▼
      0 => "CN=Michael Froehlich,OU=2016 Spring,OU=Classes,OU=People,OU=CDTM,dc=internal,dc=cdtm,dc=de"
    ]
  ]
  #original: array:19 [▼
    "userpassword" => array:1 [▼
      0 => "{SSHA}XXX" //redacted
    ]
    0 => "userpassword"
    "distinguishedname" => array:1 [▼
      0 => "CN=Michael Froehlich,OU=2016 Spring,OU=Classes,OU=People,OU=CDTM,DC=internal,DC=cdtm,DC=de"
    ]
    1 => "distinguishedname"
    "samaccountname" => array:1 [▼
      0 => "froehlichm"
    ]
    2 => "samaccountname"
    "name" => array:1 [▼
      0 => "Michael Froehlich"
    ]
    3 => "name"
    "givenname" => array:1 [▼
      0 => "Michael"
    ]
    4 => "givenname"
    "objectclass" => array:4 [▼
      0 => "organizationalPerson"
      1 => "person"
      2 => "extensibleObject"
      3 => "top"
    ]
    5 => "objectclass"
    "cn" => array:1 [▼
      0 => "Michael Froehlich"
    ]
    6 => "cn"
    "sn" => array:1 [▼
      0 => "Froehlich"
    ]
    7 => "sn"
    "mail" => array:1 [▼
      0 => "michael.froehlich@cdtm.de"
    ]
    8 => "mail"
    "dn" => array:1 [▼
      0 => "CN=Michael Froehlich,OU=2016 Spring,OU=Classes,OU=People,OU=CDTM,dc=internal,dc=cdtm,dc=de"
    ]
  ]
}
```

**Comment by stevebauman** [comment]
Hi @FroeMic,

I see in your config you've added:

```
// if set to 'ldap' as described in the docs
// it will not work (https://adldap2.github.io/Adldap2-Laravel/#/auth/introduction)
```

This is because you are using v4.0 and not v5.0. The docs you are reading are for version v5.0.

> I am not 100% sure here, but I suspect that the problem arises, because the object returned by Adldap2/Guard.php->attempt()is of type Adldap\Models\Entry and not of type Adldap\Models\User; (see issue description).

This is definitely the issue, as the returned object is checked to ensure a `User` model instance is returned:

https://github.com/Adldap2/Adldap2-Laravel/blob/4e38b0b504f0b573bd4c6bf84571ea37a6025e6a/src/Auth/DatabaseUserProvider.php#L100-L103

This seems like a schema issue since the schema object is a responsible for mapping LDAP results to Adldap models. You can see this process occur here:

https://github.com/Adldap2/Adldap2/blob/7f1852bc65801dc1db873e68156758c59ddc391c/src/Query/Processor.php#L103-L140

Can you ensure your configuration isn't being cached by Laravel by using `php artisan config:clear` and try again? Once we rule that out quickly, we can move forward.

**Comment by FroeMic** [comment]
I have cleared the config cache as described, but the issue persists.

I further investigated the mapping of the LDAP results to the model(s) and this is what I have figured out so far – I have added full debug output below.

From my understanding the issue arises, because the `array_intersect()` method has no intersecting values between `$classes` and `$mappings`.

`$classes = ["organizationalperson", "person", "extensibleobject", "top"]`
`$mappings = ["computer", "contact", "inetorgperson", "groupofnames", "container", "printqueue", "groupofuniquenames"]`

For a User-Model to be returned, the key "inetorgperson" schould be in the classes array (I guess).


### Full debug output

```
    /**
     * Returns a new LDAP Entry instance.
     *
     * @param array $attributes
     *
     * @return Entry
     */
    public function newLdapEntry(array $attributes = [])
    {
        $objectClass = $this->schema->objectClass();

        //dd($this->schema);    // = OpenLdap
        //dd($objectClass);     // = "objectclass"

        if (array_key_exists($objectClass, $attributes) && array_key_exists(0, $attributes[$objectClass])) {
            // Retrieve all of the object classes from the LDAP
            // entry and lowercase them for comparisons.
            $classes = array_map('strtolower', $attributes[$objectClass]);

            //dd($classes); // 
            //= [
            //    "count" => "4"
            //    0 => "organizationalperson"
            //    1 => "person"
            //    2 => "extensibleobject"
            //    3 => "top"
            // ]

            // Retrieve the model mapping.
            $models = $this->map();
            //dd($models); 
            // = [
            //    "computer" => "Adldap\Models\Computer"
            //    "contact" => "Adldap\Models\Contact"
            //    "inetorgperson" => "Adldap\Models\User"
            //    "groupofnames" => "Adldap\Models\Group"
            //    "container" => "Adldap\Models\Container"
            //    "printqueue" => "Adldap\Models\Printer"
            //    "groupofuniquenames" => "Adldap\Models\OrganizationalUnit"  
            // ]


            // Retrieve the object class mappings (with strtolower keys).
            $mappings = array_map('strtolower', array_keys($models));
            //dd($mappings);
            // = [
            //    0 => "computer"
            //    1 => "contact"
            //    2 => "inetorgperson"
            //    3 => "groupofnames"
            //    4 => "container"
            //    5 => "printqueue"
            //    6 => "groupofuniquenames"
            // ]


            // Retrieve the model from the map using the entry's object class.
            $map = array_intersect($mappings, $classes);
            // dd($map); = []

            if (count($map) > 0) {
                // Retrieve the model using the object class.
                $model = $models[current($map)];

                // Construct and return a new model.
                return $this->newModel([], $model)
                    ->setRawAttributes($attributes);
            }
        }

        // A default entry model if the object class isn't found.
        return $this->newModel()->setRawAttributes($attributes);
    }
```

**Comment by stevebauman** [comment]
Hi @FroeMic,

Thanks for your thorough debugging and explanation! Helps me immensely to be able to point you in the right direction.

Your OpenLDAP schema seems to differ from the standard 'inetorgperson' object class that is usually associated with LDAP user records (correct me if I'm wrong, as I don't use OpenLDAP in my own production environment).

You will have to create and extend the built in OpenLDAP schema with your own and override a method to indicate to the Query Processor which model is associated with the `User` model.

Here's what you'll need to create:

**Schema** (for example, located in the `app\Schemas` directory):
```php
namespace App\Schemas;

use Adldap\Schemas\OpenLDAP as BaseSchema;

class OpenLDAP extends BaseSchema
{
    /**
     * {@inheritdoc}
     */
    public function objectClassPerson()
    {
        return 'organizationalperson';
    }
    
    /**
     * {@inheritdoc}
     */
    public function objectClassUser()
    {
        return 'organizationalperson';
    }
}
```

Then insert this schema into your `config/ldap.php` file here:

https://github.com/Adldap2/Adldap2-Laravel/blob/857266d7d6928cbf43111c1fe1f1f41f35d93956/src/Config/config.php#L88

Can you give that a shot and let me know how it goes? Thanks!

**Comment by FroeMic** [comment]
Hi @stevebauman!

Adding the Schema subclass resolved the issue like a charm.

Thank you for your help & have a good start into 2019!

**Comment by stevebauman** [comment]
Awesome @FroeMic! Appreciate your quick responses and debugging.

No problem at all, and you as well!
