### ISSUE TITLE
Import Single User from AD to app database

### ISSUE THREAD

**Issue by smockermaster** [Adldap2/Adldap2-Laravel#644]
- Laravel Version: 5.7.15
- Adldap2-Laravel Version: 5
- PHP Version: 7.1.19
- LDAP Type: ActiveDirectory

### Description:
Hello, Steve!

That's not, exactly, an issue..., it's a question about something I've not found in documentation.

To add a single user from AD to app database (and to use ldap_auth), I read and display a list of AD users (only active accounts) in an index view. I want be able to add a single user from this list without use the import command from console..., can I do this??

Thank you very much!

### Steps To Reproduce:
To get active users from AD

`$ad_users = Adldap::search()->users()`
`->where('userAccountControl', '!', '514')`
`->where('userAccountControl', '!', '66050')->get();`

**Comment by stevebauman** [comment]
Hi @smockermaster!

If you want to import a single user from your directory into your application you can call the command problematically using the `Artisan` facade:

```php
use Illuminate\Support\Facades\Artisan;

$user = 'jdoe@corp.acme.org';

Artisan::call("adldap:import $user", ['--no-interaction']);
```

Or, you can even instantiate the importer yourself by providing it your `User` model and the users LDAP model, along with an array containing their username:

```php
use App\User;
use Adldap\Laravel\Facades\Adldap;
use Adldap\Laravel\Commands\Import;

// Find the LDAP user to import.
$user = Adldap::search()->users()->find('jdoe');

// The users username mapping (simply named credentials to match the parameter name):
// This is how your local database record of the LDAP user is located for synchronization.
$credentails = [
    'email' => $user->getEmail(),
];

// Create the importer:
$importer = new Import($user, new User(), $credentials);

// Run the import. The synchronized *unsaved* model will be returned:
$model = $importer->handle();

// Save the returned model.
$model->save();
```

If you run into any issues with the above or need help with anything else, just comment back and I'll re-open this. Thanks! :smile:

**Comment by smockermaster** [comment]
Hello @stevebauman,

I've solved it partially using this:
`$model->password = Hash::make('some_password');`
`$model->save();`

However, I don't be sure thats it's orthodox...

**Comment by stevebauman** [comment]
Hi @smockermaster, sorry about that, I gave you an incorrect example, give this a shot for using the `Artisan` facade:

```php
Artisan::call('adldap:import', ['user' => 'sbauman@acme.org', '--no-interaction']);
```

For the second example, I forgot to also mention that you will need to set a temporary password for the user models since it's a non-nullable field in your database:

```php
use App\User;
use Adldap\Laravel\Facades\Adldap;
use Adldap\Laravel\Commands\Import;

// Find the LDAP user to import.
$user = Adldap::search()->users()->find('jdoe');

// The users username mapping (simply named credentials to match the parameter name):
// This is how your local database record of the LDAP user is located for synchronization.
$credentails = [
    'email' => $user->getEmail(),
];

// Create the importer:
$importer = new Import($user, new User(), $credentials);

// Run the importer. The synchronized *unsaved* model will be returned:
$model = $importer->handle();

// Set a random password for the user model.
$model->password = Hash::make(str_password(16));

// Save the returned model.
$model->save();
```

To clarify your comment about password synchronization, enabling this sets your users model password to their inputted password *upon logging in*, not through import. It is impossible to retrieve the users actual password from ActiveDirectory, as that would be a major security risk.

If you're unable to login using the Adldap2 auth driver, that's a separate issue all-together. Let me know if this is the case, thanks!

**Comment by smockermaster** [comment]
Thank you, @stevebauman 

All work fine now with second option! First option cause me problems yet.

Thanks for solve my doubts about password synchronization..., I fought with that...

**Comment by stevebauman** [comment]
Great! Glad you were able to use one of the approaches.

If you encounter any further issues feel free to create one and I'll assist you there. Thanks!
