### ISSUE TITLE
 ConfigurationException: Option schema must be a valid class

### ISSUE THREAD

**Issue by sagaio** [Adldap2/Adldap2-Laravel#647]
- Laravel Version: 5.7
- Adldap2-Laravel Version: 5.0
- PHP Version: 7.2
- LDAP Type: OpenLDAP

### Description:
In LoginController.php I'm overriding the function login() to allow a user configured setting for the LDAP connection and it goes something like this:

```
$LDAPconfig = [
    'hosts'          => $hosts,
    'base_dn'        => $basedn,
    'account_prefix' => $accountPrefix,
    'account_suffix' => $accountSuffix,
    'username'       => $username,
    'password'       => $password,
    'port'           => $port,
    'schema'         => '\Adldap\Adldap\Schemas\OpenLDAP::class',
];

$config = new \Adldap\Configuration\DomainConfiguration($LDAPconfig); // <--- here the exception is thrown

$connectionName = 'ldap-' . time();

$provider = new Adldap();
$provider->addProvider($config, $connectionName);
$provider->setDefaultProvider($connectionName);
```

I keep getting the Adldap\Configuration\ConfigurationException `Option schema must be a valid class.` from `vendor\adldap2\adldap2\src\Configuration\Validators\ClassValidator.php`.

I've tried to change the namespacing of the `schema` key and setting it with or without quotes.
```
'\Adldap\Adldap\Schemas\OpenLDAP::class'
'\Adldap\Schemas\OpenLDAP::class'
'Adldap\Adldap\Schemas\OpenLDAP::class'
'Adldap\Schemas\OpenLDAP::class'

\Adldap\Adldap\Schemas\OpenLDAP::class
\Adldap\Schemas\OpenLDAP::class
Adldap\Adldap\Schemas\OpenLDAP::class
Adldap\Schemas\OpenLDAP::class
```

but the message keeps repeating...

I'm using `use Adldap\Adldap;` and not the use `Adldap\Laravel\Facades\Adldap;`.

What am I doing wrong? I can't find a single issue related to this in Adldap2-Laravel or Adldap2 repo.

**Comment by stevebauman** [comment]
Hi @sagaio,

In the first example you've posted trying: `'\Adldap\Adldap\Schemas\OpenLDAP::class',`, but this has an extra namespace attached (`Adldap`) and quotes which would not be valid (since the `::class` suffix has been added).

All the configuration validator does is check if the value given is an existing class:

https://github.com/Adldap2/Adldap2/blob/master/src/Configuration/Validators/ClassValidator.php#L18

Are you sure you've typed the proper class string? It should be exactly:

```php
'schema' => \Adldap\Schemas\OpenLDAP::class
```

**Comment by sagaio** [comment]
Thanks for the answer, it's working now!

When looking through the stacktrace I saw that pretty far down it tried using the Illuminate Auth and there for the issue.
