### ISSUE TITLE
How to setup a custom provider and still authenticate in Laravel?

### ISSUE THREAD

**Issue by sagaio** [Adldap2/Adldap2-Laravel#649]
- Laravel Version: 5.7
- Adldap2-Laravel Version: 5.1.1
- PHP Version: 7.2
- LDAP Type: ActiveDirectory

### Description:

User is not authenticated even though auth() passes.

I have setup the `login()` function to use a configuration that is fetched from the database instead of the one specified in `ldap_auth.php` config file.

When running this the `$provider->auth()` passes and user is redirected to `/dashboard` but the user is never authenticated in Laravel according to the Auth section in debugbar so a `Illuminate\Auth\AuthenticationException` is thrown when it's going to `/dashboard` and the user is redirected to the login page again:

```
use Adldap\Laravel\Facades\Adldap;

class LoginController extends Controller
{
    protected function guard($guard = 'web')
    {
        return $guard;
    }
    
    public function userLogin(Request $request)
    {
        $LDAPconfig = [
            'hosts'          => $hosts,
            'base_dn'        => $basedn,
            'account_prefix' => $accountPrefix,
            'account_suffix' => $accountSuffix,
            'username'       => $username,
            'password'       => $password,
            'port'           => $port,
            'schema'         => $schema
        ];

        $config = new \Adldap\Configuration\DomainConfiguration($LDAPconfig);

        $provider = new \Adldap\Connections\Provider($config, null, $schema);
        $provider->connect();

        if($provider->auth($request->$usernameName, $request->password)) {
            Log::info('Success: user authentication successful.');
            return redirect('/dashboard');
        }
    }
}
```

auth.php:
```

'guards' => [
    'localadmin' => [
        'driver' => 'session',
        'provider' => 'localadmin',
    ],

    'web' => [
        'driver' => 'session',
        'provider' => 'users',
    ],
],

'providers' => [
    'localadmin' => [
        'driver' => 'eloquent',
        'model' => App\LocalAdmin::class
    ],
    'users' => [
        'driver' => 'ldap',
        'model' => App\User::class
    ],
],
```

I know this setup is incorrect since I'm not using the Adldap Facade but I've tried using that and with `Adldap::addProvider($config, 'name');` but that just gives me an error saying the Schema option must be a valid class. But looking through the stacktrace It's somehow not adhereing the the configuration I provide but instead fetching the default connection in `ldap_auth.php` config.

I've spent 6 days now searching through both repos but I just can't find out how to set this up.

Any ideas how to achieve authentication this way with custom configuration for the provider?

**Comment by sagaio** [comment]
So I've changed the login() method to set the config values at runtime:

```
config([
    'ldap.connections.default.settings.schema'         => $schema,
    'ldap.connections.default.settings.account_prefix' => $accountPrefix,
    'ldap.connections.default.settings.account_suffix' => $accountSuffix,
    'ldap.connections.default.settings.hosts'          => $hosts,
    'ldap.connections.default.settings.port'           => $port,
    'ldap.connections.default.settings.base_dn'        => $basedn,
    'ldap.connections.default.settings.username'       => $username,
    'ldap.connections.default.settings.password'       => $password,
]);
```

If I `dd('ldap.connections.default')` it displayes the correct values. I'm however still not authenticated locally even though I run through the Facade this time:

```
if(Adldap::auth($request->$usernameName, $request->password)) {
    Log::info('Success: user authentication successful.');
    return redirect('/dashboard');
}
```

It's the same behaviour, redirecting to /dashboard but then same exception and redirected to login.

Has this something to do with multiple guards or a misconfiguration of my guards?

**Comment by stevebauman** [comment]
Hi @sagaio,

Calling `Adldap::auth()` or `$provider->auth()` does nothing besides sending an LDAP Bind request to your LDAP server. It does not authenticate you into Laravel at all.

You need to use Laravel's `Auth` facade as you would normally to authenticate a user into your application and configure the guards (as you already have) in your `config/auth.php` file.

To authenticate using a different guard in Laravel, call:

```php
$credentials = $request->only('username', 'password');

if (Auth::guard('localadmin')->attempt($credentials)) {
    return redirect('/dashboard');
}

// Or using the default guard you've configured, likely "users"
if (Auth::attempt($credentials)) {
    return redirect('/dashboard');
}

// Or explicitly:
if (Auth::guard('users')->attempt($credentials)) {
    return redirect('/dashboard');
}
```

If you still run into issues, let me know and I'll re-open this. Thanks!

**Comment by sagaio** [comment]
This was my bad, I had the follwing in my routes file:

`Route::group(['middleware' => ['auth:web,', 'auth:localadmin']], function() { ... }`

I changed it to:
`Route::group(['middleware' => ['auth:web,localadmin']], function() { ... }`

And it works!

So sorry for making you reopen this. Thank you so much for the support @stevebauman!

**Comment by stevebauman** [comment]
Oh no worries @sagaio! Glad you’re able to resolve it!

Thanks for the quick follow up. Let me know if you encounter any further issues! :smile:
