### ISSUE TITLE
Get thumbnailphoto from AD

### ISSUE THREAD

**Issue by netopvh** [Adldap2/Adldap2-Laravel#65]
Hi, 

I wonder how get thumbnailphoto from AD ? I tried many ways more could not.

help please. :+1:

**Comment by stevebauman** [comment]
https://github.com/Adldap2/Adldap2/blob/v5.2/src/Models/User.php#L667

```php
$user = Adldap::users()->find('jdoe');

$photo = $user->getThumbnailPhoto();
```

**Comment by netopvh** [comment]
I did it this way:

`$user = Adldap::users()->find(Auth::user()->username);

        $photo = $user->thumbnailphoto;

       // dd($photo);

        return view('home', compact('photo'));`


more returned me an error.
htmlentities() expects parameter 1 to be string, array given

**Comment by stevebauman** [comment]
Try:

```php
$photo = $user->getThumbnailEncoded();
```

**Comment by ilyadavydyuk** [comment]
How to fix `Call to a member function getThumbnailEncoded() on null` if user haven't thumb?

**Comment by stevebauman** [comment]
Hi @ilyadavydyuk, it sounds like you're trying to call `getThumbnailEncoded()` on null. You wouldn't receive this error if an actual user instance is returned.
