### ISSUE TITLE
How to test user authentication from LDAP in Unit Testing

### ISSUE THREAD

**Issue by oranges13** [Adldap2/Adldap2-Laravel#650]
- Laravel Version: 5.6
- Adldap2-Laravel Version: ^5.1
- PHP Version: 7.1
- LDAP Type: ActiveDirectory

### Description:
I have an application where all my users are expected to authenticate through LDAP. However, there's little documentation on how to test or mock these types of users.

The complicating issue is that my User model does not have a password field, as I'm not syncing or storing that attribute.

How should I approach writing unit tests that validate whether a user can login, without using actual credentials in my test?

**Comment by stevebauman** [comment]
Hi @oranges13,

Are you using the `DatabaseUserProvider`? If so, you can log in users normally in your tests by passing in your `User` model:

```php
abstract class TestCase extends BaseTestCase
{
    use CreatesApplication, RefreshDatabase;

    public function signIn($user = null)
    {
        Auth::login($user ?? factory(User::class)->create());
    }
}
```

```php
public function test_home_page()
{
    $this->signIn();

    $this->get('/home')->assertOk();
}
```

I may be misunderstanding your question though. Are you looking to actually test LDAP authentication in your tests? Or test that logging in works using the `ldap` auth driver?

**Comment by stevebauman** [comment]
Ohh okay I see what you’re saying. I don’t have access to a computer right now (on my phone at the moment), but I’ll post test code you can try when I can.

You’ll definitely have to setup some mocks on the LDAP connection.

Will get back to you soon!

**Comment by stevebauman** [comment]
Hi @oranges13,

I just created a quick test and this worked great:

```php
<?php

namespace Tests\Feature;

use App\User;
use Tests\TestCase;
use Adldap\Laravel\Facades\Adldap;
use Adldap\Laravel\Facades\Resolver;
use Illuminate\Support\Facades\Auth;

class AuthTest extends TestCase
{
    /**
     * Returns a new LDAP user model.
     *
     * @param array $attributes
     *
     * @return \Adldap\Models\User
     */
    protected function makeLdapUser(array $attributes = [])
    {
        $provider = config('ldap_auth.connection');

        return Adldap::getProvider($provider)->make()->user($attributes);
    }

    /**
     * A basic test example.
     *
     * @return void
     */
    public function test_ldap_authentication_works()
    {
        $credentials = ['email' => 'jdoe@email.com', 'password' => '12345'];

        $user = $this->makeLdapUser([
            'objectguid'            => ['cc07cacc-5d9d-fa40-a9fb-3a4d50a172b0'],
            'cn'                    => ['John Doe'],
            'userprincipalname'     => ['jdoe@email.com'],
        ]);

        Resolver::shouldReceive('byCredentials')->once()->andReturn($user)
            ->shouldReceive('authenticate')->once()->andReturn(true);

        $this->post(route('login'), $credentials)->assertRedirect('/dashboard');

        $this->assertInstanceOf(User::class, Auth::user());
    }
}
```

Can you give it a shot? I'll close this but will re-open if you have issues. I'll also be adding this into the docs. :smile:

**Comment by oranges13** [comment]
This worked out excellent! Thank you so much!

For anyone else using Active Directory, you can change the created user credentials to include `samaccountname` (and `mail` if you need the sync to operate) and it works just as described above:

```php
public function test_user_can_login_with_correct_credentials() {
	$credentials = ['username' => 'jdoe', 'password' => '12345'];

    	$user = $this->makeLdapUser([
    		'objectguid' => [$this->faker->uuid()],
		'cn' => ['John Doe'],
		// We are using active directory
		'samaccountname' => ['jdoe'],
		'mail' => ['jdoe@mydomain.com'],
	    ]);

    	Resolver::shouldReceive('byCredentials')->once()->andReturn($user)
		->shouldReceive('authenticate')->once()->andReturn(true);

    	$response = $this->post(route('login'), $credentials)->assertRedirect(route('admin.index'));

	$this->assertInstanceOf(User::class, Auth::user());
}
```

**Comment by stevebauman** [comment]
Great, glad you're up and running @oranges13! No problem at all :smile:

**Comment by michaelhume** [comment]
Hi @stevebauman , I really appreciate this snippet. Unfortunately I'm getting an error when attempting to use this with 'username' in the credentials:

My setup:
- php 7.3.12
- laravel 6.6.2
- adldap2/adldap2-laravel ^6.0

My code:

`
    protected function makeLdapUser(array $attributes = [])
    {
        $provider = config('ldap_auth.connection');
        return Adldap::getProvider($provider)->make()->user($attributes);
    }
    
    /** @test **/
    public function test_ldap_authentication_works()
    {
        $credentials = ['username' => 'jdoe', 'password' => '12345'];

        $user = $this->makeLdapUser([
	        'samaccountname'		=> ['jdoe'],
	        'objectguid'            => [ $this->faker->uuid() ],
            'cn'                    => ['John Doe'],
            'mail'					=> ['jdoe@nanofab.com'],
        ]);

        Resolver::shouldReceive('byCredentials')->once()->andReturn($user)
            ->shouldReceive('authenticate')->once()->andReturn(true);

        $response = $this->post(route('login'), $credentials)
		        	->assertRedirect(route('home'));

        $this->assertInstanceOf(User::class, Auth::user());
    }`

The response:
`Mockery\Exception\BadMethodCallException: Received Mockery_2_Adldap_Laravel_Resolvers_UserResolver::getLdapDiscoveryAttribute(), but no expectations were specified
`

If I switch to email credentials, the 500 status code goes away but the user is not authenticated. Once I switch to username (the same as my actual implementation) I get the exception.
I do have some sync_attributes in my ldap_auth. I've tried including them without any luck.

Hopefully I'm missing something obvious??

**Comment by stevebauman** [comment]
Hi @michaelhume,

The above example is out of date now, you will have to use this:

```php
<?php

namespace Tests\Feature;

use App\User;
use Tests\TestCase;
use Adldap\Laravel\Facades\Adldap;
use Adldap\Laravel\Facades\Resolver;
use Illuminate\Support\Facades\Auth;
use Illuminate\Foundation\Testing\WithFaker;

class AuthTest extends TestCase
{
    use WithFaker;

    /**
     * Returns a new LDAP user model.
     *
     * @param array $attributes
     *
     * @return \Adldap\Models\User
     */
    protected function makeLdapUser(array $attributes = [])
    {
        $provider = config('ldap_auth.connection');

        return Adldap::getProvider($provider)->make()->user($attributes);
    }

    /**
     * A basic test example.
     *
     * @return void
     */
    public function test_ldap_authentication_works()
    {
        $credentials = ['email' => 'jdoe@email.com', 'password' => '12345'];

        $user = $this->makeLdapUser([
            'objectguid'            => [$this->faker->uuid],
            'cn'                    => ['John Doe'],
            'userprincipalname'     => ['jdoe@email.com'],
        ]);

        Resolver::shouldReceive('byCredentials')->once()->with($credentials)->andReturn($user)
            ->shouldReceive('getDatabaseIdColumn')->twice()->andReturn('objectguid')
            ->shouldReceive('getDatabaseUsernameColumn')->once()->andReturn('email')
            ->shouldReceive('getLdapDiscoveryAttribute')->once()->andReturn('userprincipalname')
            ->shouldReceive('authenticate')->once()->andReturn(true);

        $this->post(route('login'), $credentials)->assertRedirect('/dashboard');

        $this->assertInstanceOf(User::class, Auth::user());
    }
}
```

Let me know if this works for you :smile:

**Comment by michaelhume** [comment]
A bit more info: my ldap_auth contains
`
    'identifiers' => [

        'ldap' => [

            'locate_users_by' => 'samaccountname',

            'bind_users_by' => 'distinguishedname',

        ],



`

**Comment by stevebauman** [comment]
Ok, with that config, swap the authentication test with this:

```php
/**
    * A basic test example.
    *
    * @return void
    */
public function test_ldap_authentication_works()
{
    $credentials = ['email' => 'jdoe@email.com', 'password' => '12345'];

    $user = $this->makeLdapUser([
        'objectguid'        => [$this->faker->uuid],
        'cn'                => ['John Doe'],
        'samaccountname'    => ['jdoe'],
    ]);

    Resolver::shouldReceive('byCredentials')->once()->with($credentials)->andReturn($user)
        ->shouldReceive('getDatabaseIdColumn')->twice()->andReturn('objectguid')
        ->shouldReceive('getDatabaseUsernameColumn')->once()->andReturn('username')
        ->shouldReceive('getLdapDiscoveryAttribute')->once()->andReturn('samaccountname')
        ->shouldReceive('authenticate')->once()->andReturn(true);

    // Modify this line to assert your home page redirection:
    $this->post(route('login'), $credentials)->assertRedirect('/dashboard');

    $this->assertInstanceOf(User::class, Auth::user());
}
```

Can you check if that works for you?

**Comment by michaelhume** [comment]
Holy that was fast!

That got me on the right path, after a few tweaks... this worked:

`$credentials = ['username' => 'jdoe', 'password' => '12345'];

        $user = $this->makeLdapUser([
	        'samaccountname'		=> ['jdoe'],
	        'objectguid'            => [ $this->faker->uuid() ],
            'cn'                    => ['John Doe'],
            'mail'					=> ['jdoe@nanofab.com'],
            'userprincipalname'     => ['jdoe'],
            
        ]);

        Resolver::shouldReceive('byCredentials')->once()->with($credentials)->andReturn($user)
            ->shouldReceive('getDatabaseIdColumn')->twice()->andReturn('guid')
            ->shouldReceive('getDatabaseUsernameColumn')->once()->andReturn('email')
            ->shouldReceive('getLdapDiscoveryAttribute')->once()->andReturn('userprincipalname')
            ->shouldReceive('authenticate')->once()->andReturn(true);
`

**Comment by stevebauman** [comment]
Awesome @michaelhume! Really glad you're up and running. Let me know if you run into anything else.

**Comment by michaelhume** [comment]
Thank you!

For feedback, this also worked - I had to add a few fields to satisfy DB integrity constraints.

`
$credentials = ['username' => 'jdoe', 'password' => '12345'];

    $user = $this->makeLdapUser([
        'objectguid'        => [$this->faker->uuid],
        'cn'                => ['John Doe'],
        'samaccountname'    => ['jdoe'],
        'mail'					=> ['jdoe@email.com'],
    ]);

    Resolver::shouldReceive('byCredentials')->once()->with($credentials)->andReturn($user)
        ->shouldReceive('getDatabaseIdColumn')->twice()->andReturn('guid')
        ->shouldReceive('getDatabaseUsernameColumn')->once()->andReturn('username')
        ->shouldReceive('getLdapDiscoveryAttribute')->once()->andReturn('samaccountname')
        ->shouldReceive('authenticate')->once()->andReturn(true);
`

Outstanding!!!

**Comment by michaelhume** [comment]
One more issue @stevebauman ,

When attempting to make new users in multiple using:

`$ldap_user = Adldap::getProvider(config('ldap_auth.connection'))->make()->user($user_attributes);`

tests it I'm getting 

````
Illuminate\Contracts\Container\BindingResolutionException: Target class [config] does not exist.

 ( stack trace )

Caused by
ReflectionException: Class config does not exist
````

for each subsequent test using the snippet
