### ISSUE TITLE
Problems with the NoDatabaseUserProvider

### ISSUE THREAD

**Issue by hurik** [Adldap2/Adldap2-Laravel#652]
- Laravel Version: 5.7.21
- Adldap2-Laravel Version: 9.1.4
- PHP Version: 7.2.13
- LDAP Type: OpenLDAP

### Description:
I can't get the NoDatabaseUserProvider working with the [Forum Systems Online LDAP Test Server](https://www.forumsys.com/tutorials/integration-how-to/ldap/online-ldap-test-server/). I get it working with the DatabaseUserProvider. But with the NoDatabaseUserProvider, after a trying to login, I'm redirected back to the login page. When I check the logs in Telescope, I see that the LDAP authentication was working:
![telescopelog](https://user-images.githubusercontent.com/1187778/51709030-a673da80-2025-11e9-9e34-b06a29b8fa4d.png)

Do I miss something?

### Steps To Reproduce:
Here is my project: https://github.com/hurik/Adldap2-Laravel-NoDatabaseUserProvider-Example-Project

Thanks, for your help.

**Comment by stevebauman** [comment]
Hi @hurik, that online test server does return users `entryuuid`'s with search results, only their `uid`, `cn`, `mail`, and `sn`.

You would get a successful login for the first try, as their record would be located by their `uid`, however, upon loading a protected page, their `entryuuid` is queried for as this is the attribute that is stored in the Laravel session for quickly retrieving the users LDAP model:

https://github.com/Adldap2/Adldap2-Laravel/blob/b398fc27a5abcec63506a2d3ab7bd7d5ab315466/src/Auth/NoDatabaseUserProvider.php#L15-L25

https://github.com/Adldap2/Adldap2-Laravel/blob/b398fc27a5abcec63506a2d3ab7bd7d5ab315466/src/Resolvers/UserResolver.php#L54-L60

**Comment by Haziqasyraff** [comment]
I'm having the same issue, has been logged in and authenticated, but when called using Auth::user(), it's not there. However, there is my uid stored in session.
