### ISSUE TITLE
Can import, authenticate and search user but can't login

### ISSUE THREAD

**Issue by kotaknishit** [Adldap2/Adldap2-Laravel#655]
- Laravel Version: 5.5
- Adldap2-Laravel Version: 4.0
- PHP Version: 7.0
- LDAP Type: OpenLDAP

###: I am not able to login.

I am getting below query while debugging.

adldap\vendor\adldap2\adldap2\src\Connections\Ldap.php in 
search($dn, $filter, array $fields, $onlyAttributes = false, $size = 0, $time = 0)

below is the result of filter.

**filter:(&(objectclass=\70\65\72\73\6f\6e)(uid=*) mail=\61\62\63\40\65\78\61\6d\70\6c\65\2e\63\6f\6d))**

It is converting to HEX string.

If I use below 
1) **&(uid=*)(mail=abc@example.com))** 
 
OR  

2) ldapsearch -ZZ -Wx -D "cn=admin,dc=example,dc=com" -b "dc=example,dc=com" "(mail=\61\62\63\40\65\78\61\6d\70\6c\65\2e\63\6f\6d)" -H ldap:// -LLL

Using 1) and 2) I am able to find the user.
 
Attached my config file.

[adldap.txt](https://github.com/Adldap2/Adldap2-Laravel/files/2812472/adldap.txt)
[adldap_auth.txt](https://github.com/Adldap2/Adldap2-Laravel/files/2812473/adldap_auth.txt)

**Comment by stevebauman** [comment]
Hi @kotaknishit, try the following configuration changes:

1. Remove all of your account prefixes and suffixes (`account_prefix`, `account_suffix`, `admin_account_prefix`, `admin_account_suffix`).
2. Change your `admin_username` to the **full* distinguished name of your accounts username (`cn=john doe,ou=Users,ou=Company,dc=example,dc=com`)
3. Change your `usernames.ldap.discover` to `mail`
4. Change your `usernames.ldap.authenticate` to `dn`

Make those changes, flush your config cache (if being cached using `php artisan config:clear`), then try again.

Let me know if it works,thanks!

**Comment by stevebauman** [comment]
Great, glad you were able to resolve it @kotaknishit! No problem at all :smile:
