### ISSUE TITLE
Laravel fails to respond after composer require

### ISSUE THREAD

**Issue by WaskiWabit** [Adldap2/Adldap2-Laravel#656]
- Laravel Version: 5.7.19
- Adldap2-Laravel Version: Latest
- PHP Version: 7.1.26
- LDAP Type: AD

### Description:
Laravel fails to respond (ERR_CONNECTION_RESET) after I run the following:
**composer require adldap2/adldap2-laravel**

### Steps To Reproduce:

Simply run:
**composer require adldap2/adldap2-laravel**

Then try to load a laravel page.

**Comment by stevebauman** [comment]
Hi @WaskiWabit,

This is not an issue with Adldap2-Laravel. `ERR_CONNECTION_RESET` is a browser response that simply means you cannot access the site you're trying to visit - which would be a server issue.

I just tested a brand new Laravel project using the latest Adldap2-Laravel version and there was no issue.

**Comment by WaskiWabit** [comment]
That's funny because I get ERR_CONNECTION_RESET right after I run the composer command to include your libraries. Before that, it is fine and responds accordingly.

**Comment by stevebauman** [comment]
Have you tried requiring other composer packages? I'm unable to reproduce your issue.

**Comment by WaskiWabit** [comment]
Yes. I wiped out the 5.7 instance and recreated a 5.4 instance thinking maybe it was a version issue. Same result for both.

**Comment by stevebauman** [comment]
Have you checked your PHP log for errors? I literally just performed each of your steps again in another test, and it works without issue. All travis-ci tests are also passing. I still can't reproduce at all locally.

Do you have the LDAP extension enabled on your PHP install?

**Comment by WaskiWabit** [comment]
Hmm. This is weird. Yes I have the LDAP extension enabled. Your libs won't install without it enabled.

**Comment by stevebauman** [comment]
Is your composer installation and your server looking at the same exact binaries of PHP?

**Comment by WaskiWabit** [comment]
Hmm that's a great question. I do have XAMPP installed with php 5 and Bitnami Wampstack installed with php 7. I disable the xampp of course but there could be some crossover in the environment vars. How would I check. Again, thanks for your assistance.

**Comment by WaskiWabit** [comment]
That was it Steve. Composer was being called from the XAMPP install and not Bitnami. Thanks a ton man. You lead me down the right path.

**Comment by stevebauman** [comment]
Awesome @WaskiWabit! Glad you were able to resolve it. Thanks for following up quickly throughout this.

I've had this issue personally and it took me a while to figure out what was going on, so figured it could be related 😅

**Comment by WaskiWabit** [comment]
No problem @stevebauman :)
