### ISSUE TITLE
All searches return an empty collection

### ISSUE THREAD

**Issue by ctyler69** [Adldap2/Adldap2-Laravel#657]
- Laravel Version: 5.7
- Adldap2-Laravel Version: 5.1
- PHP Version: 7.3
- LDAP Type: ActiveDirectory 

I believe I have all of my settings correct:

//Here is the ldap.php file
<php
return [

    'connections' => [
        'default' => [
            'auto_connect' => env('LDAP_AUTO_CONNECT', true),
            'connection' => Adldap\Connections\Ldap::class,
            'settings' => [

                'schema' => Adldap\Schemas\ActiveDirectory::class,
				'account_prefix' => env('LDAP_ACCOUNT_PREFIX', ''),
                'account_suffix' => env('LDAP_ACCOUNT_SUFFIX', 'mydomain.com'),
				'hosts' => explode(' ', env('LDAP_HOSTS', '10.0.0.0')), //This is correct and verified
                'port' => env('LDAP_PORT', 636),
				'timeout' => env('LDAP_TIMEOUT', 5),
				'base_dn' => env('LDAP_BASE_DN', 'CN=Users,DC=mydomain,DC=com'), 
				'username' => env('good_username'),
                'password' => env('correct_password'),
				'follow_referrals' => false,
				'use_ssl' => env('LDAP_USE_SSL', true),
                'use_tls' => env('LDAP_USE_TLS', false),

            ],

        ],

    ],

];

Now with this set up - in the route web.php I have

use Adldap\Laravel\Facades\Adldap;

Route::get('/', function () {
    $search2 = Adldap::search()->users()->get();
    dd($search2 );
    return view('welcome');
});

This should be enough to retrieve all the AD users and it always returns an empty collection. 

Is there anything that I can try?

**Comment by stevebauman** [comment]
Hi @ctyler69, I'll help you out and get you up and running.

Can you verify that your `base_dn` is set properly? This is the first thing to check when performing searches.

I ask about the base DN, as you've set it to `CN=Users,DC=mydomain,DC=com` (might be different, since you may have added it in to your `.env` file). Usually a `base_dn` would consist of domain components (in your case `DC=mydomain,DC=com`).

**Comment by ctyler69** [comment]
Hi @stevebauman ,
I was deidentifying the domain/ip info. I have verified it with active directory. If I go into Active Directory and Computer, right click users, select properties, select attribute Editor Tab and scroll down to distinguishedName it say: CN=Users,DC=mydomain,DC=com. (Actual domain name). I have tried adding it just like that and DC=mydomain,DC=com. Same results.

**Comment by stevebauman** [comment]
Ok, can you check your laravel logs to ensure there's no connection issue going on with Adldap2 and your server? If there isn't we can rule that out and continue on.

**Comment by ctyler69** [comment]
There is no connection errors listed. Also, if I change a port number or something it throws an error:
Can't contact LDAP server
So it seems to be connecting fine. It does act like the base dn is incorrect but it is not.

**Comment by stevebauman** [comment]
Ok great. Hmmm, can you try running the following and see if you get anything back?:

```php
Route::get('/', function () {
    $root = Adldap::search()->getRootDse();

    dd($root);
});
```

**Comment by ctyler69** [comment]
RootDse {#223 ▼
  +exists: true
  #query: Builder {#216 ▼
    +columns: array:1 [▶]
    +filters: array:3 [▶]
    +limit: 1
    +paginated: false
    #sortByField: ""
    #sortByDirection: ""
    #sortByFlags: null
    #dn: ""
    #type: "read"
    #raw: false
    #nested: false
    #connection: Ldap {#210 ▶}
    #grammar: Grammar {#217}
    #schema: ActiveDirectory {#213}
  }
  #schema: ActiveDirectory {#213}
  #modifications: []
  +dateFormat: "Y-m-d H:i:s"
  #timestampFormat: "YmdHis.0Z"
  #attributes: array:44 [▶]
  #original: array:44 [▶]
}

**Comment by ctyler69** [comment]
I did not clear the cache. I just did and ran:
Route::get('/', function () {
    $root = Adldap::search()->getRootDse();

    dd($root->getFirstAttribute('defaultnamingcontext'));
});
And this was was returned:
"DC=comlivserv,DC=com"

**Comment by stevebauman** [comment]
Ok, can you enter that into your `base_dn` configuration value and then try performing a global search on users via `Adldap::search()->users()->get()` and see if you get results back?

**Comment by ctyler69** [comment]
I copied and pasted the value into the base_dn
Then
$search2 = Adldap::search()->users()->get();
 dd($search2);
Returns:

Collection {#220 ▼
  #items: []
}

**Comment by ctyler69** [comment]
If it helps, I was using adldap successfully. I was able to search and add users to AD.

**Comment by stevebauman** [comment]
Hi @ctyler69,

> If it helps, I was using adldap successfully. I was able to search and add users to AD.

What do you mean? Are you up and running now?

**Comment by stevebauman** [comment]
Oh okay. The older adLDAP library isn't maintained by me or have much at all in common with Adldap2 (besides the name of course).

It still looks like something is off in your config, as you originally suggested that `DC=mydomain,DC=com` was indeed your base DN, but it seemed to differ from the base DN returned from Adldap (`DC=comlivserv,DC=com`).

If this is incorrect by a single character, no search results will be returned.

Are you able to locate individual users in your domain via a `findByDn()`:

```php
$user = Adldap::search()->findByDn('cn=John Doe,dc=acme,dc=org');

dd($user);
```

If so, then your configured `base_dn` is still incorrect.

**Comment by ctyler69** [comment]
I have an update. So I deleted everything and started over. As I said early, I used adldap (the currently abandoned one) on another box. So I made sure a had all of the php extensions installed on both boxes. There were some installed on the previous box that were not installed on the new.  Then I installed laravel and adldap2/laravel. I added all of the config data. 

Boom it worked. 

Thank you for your help and patience Steve.

**Comment by stevebauman** [comment]
Hey @ctyler69, awesome! Glad you were able to resolve the issue. Also no problem at all!

If you encounter any other problems, feel free to create an issue here and I'll help you out. :smile:

**Comment by muzammilaskari** [comment]
@stevebauman please let me know do I need to write admin username and password in .env in order to perform searches only and basic authentication?
I am in deep trouble performing AD Authentication in my project, It will be great favor if you help me a little.

Bundles of thanks in advance.

**Comment by stevebauman** [comment]
Hi @muzammilaskari,

Yes you do - unless your domain allows anonymous binds, then you can set the username and password to `null`.
