### ISSUE TITLE
Active directory windows

### ISSUE THREAD

**Issue by annibale93** [Adldap2/Adldap2-Laravel#658]
- Laravel Version: 5.7
- Adldap2-Laravel Version: #.#
- PHP Version: 7
- LDAP Type: 

Hi i am new and i setup ldap authentication in my project laravel. I set all setting and the ldap work with the testing credentials (eulero, riemann) but if i set the setting of my active directory the ldap doesn't work. How can i do to setup windows active directory account? I insert all parameters. What are the steps?

**Comment by stevebauman** [comment]
Hi @annibale93,

Please read the [quick start](https://adldap2.github.io/Adldap2-Laravel/#/auth/introduction?id=quick-start-from-scratch) and other [authentication setup](https://adldap2.github.io/Adldap2-Laravel/#/auth/setup) documentation.
