### ISSUE TITLE
Definitive Implementation Guide

### ISSUE THREAD

**Issue by WaskiWabit** [Adldap2/Adldap2-Laravel#659]
* Laravel Version: 5.7.19
* Adldap2-Laravel Version: Latest
* PHP Version: 7.1.26
* LDAP Type: AD

### Description:

Is there a definitive guide to implementing basic authentication in Laravel? I am getting mixed results with google. Some documentation is very old, and some is incomplete. Please help. Thanks!

**Comment by stevebauman** [comment]
Hi @WaskiWabit,

Have you looked at the docs site for the authentication setup guide?

https://adldap2.github.io/Adldap2-Laravel/#/auth/setup

**Comment by WaskiWabit** [comment]
Yes I have but it seems that other sites say things that involve editing the LoginController. Amongst other things. I don't see these in your docs tho so it makes it very confusing to me.

**Comment by stevebauman** [comment]
I wouldn't really trust outside sources as being valid documentation - I don't control those nor know what they say.

There's a quick start guide from scratch on the docs site as well:

https://adldap2.github.io/Adldap2-Laravel/#/auth/introduction?id=quick-start-from-scratch

Anything you need to modify is listed in there.

**Comment by stevebauman** [comment]
If you run into issues setting things up I can help you out, but there's already a lot of documentation for getting started on the docs site. I can't help you if I don't know what you need help with outside of what is already in the docs.

**Comment by WaskiWabit** [comment]
For instance, 
```
The DatabaseUserProvider allows you to synchronize LDAP users to your applications database.

To use it, insert it in your config/ldap_auth.php in the provider option:
```

But I don't have a config/ldap_auth.php

Just  config/ldap.php

**Comment by stevebauman** [comment]
You need to publish the `ldap_auth.php` configuration file. This is in the auth setup guide:

https://adldap2.github.io/Adldap2-Laravel/#/auth/installation?id=laravel-55

> When using Laravel 5.5, the service providers are registered automatically, **however you will still need to publish the configuration file using the command below:**
>
> `php artisan vendor:publish --provider="Adldap\Laravel\AdldapAuthServiceProvider"`

**Comment by WaskiWabit** [comment]
I don't know why I didn't see this. Thanks!
