### ISSUE TITLE
Question. Full documentation to configure the application to create new users on AD

### ISSUE THREAD

**Issue by bmarsilio** [Adldap2/Adldap2-Laravel#66]
Could you show me some documention about how I prepare my application to use the create users feature? I followed the https://github.com/Adldap2/Adldap2/blob/v5.2/docs/models/USER.md doc but didn't work well

Thanks

**Comment by stevebauman** [comment]
```php
use Adldap\Laravel\Facades\Adldap;

$user = Adldap::users()->newInstance();

$user->cn = 'John Doe';
$user->telephone = '555 555 5555';

if ($user->save()) {
    // User was created successfully.
}
```

**Comment by ParthSarth** [comment]
Having the same issue. 

Relevant code:

 ```
$attributes=array(
                "userName"=>$employee->userName,
                "logon_name"=>$employee->userName."@server.martinfg.com",
                "firstname"=>$employee->FN,
                "surname"=>$employee->LN,
                "company"=>"MIG",
                "email"=>$employee->email,
                "container"=>array("User Accounts","Users"),
                "password"=>$fields['password'],
            );
        $user = Adldap::users()->create($attributes);
        
        dd($user); //RETURNS FALSE
```

$user should be true but it returns as false. Also tried with 'newInstance()' :

`
$adldap = new \Adldap\Adldap($config);
$user = $adldap->users()->newInstance();
        $user->setDistinguishedName('CN=John Doe,CN=Users,DC=server,DC=martinfg,DC=com');
        $user->setFirstName($employee->FN);
        $user->setLastName($employee->LN);
        $user->setUserAccountControl('512');
        $user->setAccountName($employee->userName);
	$user->setPassword('H@tr!ck');
        
        $adNewUser = $user->save(); 
        dd($adNewUser); //RETURNS FALSE`
