### ISSUE TITLE
Multi Auth with different ldap_auth configuration

### ISSUE THREAD

**Issue by gopankombiyil** [Adldap2/Adldap2-Laravel#660]
- Laravel Version: 5.7
- Adldap2-Laravel Version: 5.1
- PHP Version: 7.2
- LDAP Type: AD

### Description:
adldap2-laravel is working perfectly for me, my challenge is I have two different Auth databases and needs LDAP auth for both, My challenge now is the Auth config for both are different, even if I have defined two different connections in config/ldap.php both are using config from config/ldap_auth.php file, is there a way to define different auth configuration for different connections?

**Comment by stevebauman** [comment]
Hi @gopankombiyil, this is a great question.

Right now the `ldap_auth.php` file does not support separate configurations for each LDAP connection you have configured. You will have to create a separate auth provider (in your `auth.php` config file) for each of your databases and override the `ldap_auth` at run-time before calling `Auth::attempt()` in your `LoginController`.

I'll look into seeing how easy this would be to introduce into the current configuration, but it does seem like this could be somewhat difficult and would be pretty configuration heavy, which could lead to more confusion.

**Comment by gopankombiyil** [comment]
Thanks for the update @stevebauman . I tried to override the auth config by extending the AdldapAuthServiceProvider.php with no positive outcomes. 

Could you please give me an idea how to override the config in Login controller, I have 2 different type of users, two different auth providers and two different ldap connections in config. The only issue at the moment is, both connections are trying to use same auth config.
