### ISSUE TITLE
Custom error message for rule

### ISSUE THREAD

**Issue by hurik** [Adldap2/Adldap2-Laravel#662]
- Laravel Version: 5.7.25
- Adldap2-Laravel Version: 5.1.1
- PHP Version: 7.2.13
- LDAP Type: OpenLDAP

### Description:
I have a rule which checks if the user is in one of three groups. The rule is working nicely, but a user which isn't in one of the groups tries to login he get the error "These credentials do not match our records.".
Is there an easy way to change the error message to something like "You don''t have the permission to login.", for users which entered right credentials but doesn't have permission because they aren't members of the three groups.

Thanks for your help.

**Comment by stevebauman** [comment]
Hi @hurik,

For authentication rules, you can actually leverage the `AuthenticationRejected` event when a rule fails, and set a flash message to your login page to display the error:

https://github.com/Adldap2/Adldap2-Laravel/blob/a4230d533060e1f35172007bf170120d60956fe7/src/Auth/DatabaseUserProvider.php#L136-L158

Example:

```php
use Adldap\Laravel\Events\AuthenticationRejected;

Event::listen(AuthenticationRejected::class, function ($event) {
    session()->flash('ldap.error', "You don't have the permission to login.");
}
```

Then in your view, you can check to see if this session key is set, and hide the other credential errors that will be returned when authentication is rejected.

**Comment by stevebauman** [comment]
Quick and dirty example in your login view:

```blade
<input id="email" type="email" class="form-control{{ $errors->has('email') ? ' is-invalid' : '' }}" name="email" value="{{ old('email') }}" required autofocus>

@if ($errors->has('email') || session()->has('ldap.error'))
    <span class="invalid-feedback" role="alert">
        <strong>{{ $errors->first('email') || session()->get('ldap.error') }}</strong>
    </span>
@endif
```

**Comment by hurik** [comment]
Thank you very much for your fast help! It is working nicely!

**Comment by stevebauman** [comment]
No problem! Glad it’s working for you :smile:

**Comment by CyberDracula** [comment]
is this still the only way to handle errors base on failed rules/scopes? or did something changed in Adldap2 and now we also have a way to handle this OoB?
