### ISSUE TITLE
Duplicate DC using DnBuilder

### ISSUE THREAD

**Issue by drifter104** [Adldap2/Adldap2-Laravel#663]
- Laravel Version: 5.7.6
- Adldap2-Laravel Version: 5.1.1
- PHP Version: 7.2
- LDAP Type: Active Directory

### Description:

When creating a DN using DnBuilder for a new user, the Dc value appears to be added twice.

### Steps To Reproduce:

Using the following code

$user = Adldap::make()->user();
			$user->setCommonName($dbrequest->firstname." ".$dbrequest->lastname[0]);
			$user->setFirstName($dbrequest->firstname);
			$user->setLastName($dbrequest->lastname);
			$user->setDisplayName($dbrequest->firstname." ".$dbrequest->lastname);
			$user->setAttribute('SamAccountName', $dbrequest->firstname.$dbrequest->lastname[0]);
			$user->setAttribute('proxyAddresses', "SMTP:$dbrequest->firstname." . "$dbrequest->lastname" . "@example.com");
			$dn = $user->getDnBuilder();
			$dn->addCn($dbrequest->firstname." ".$dbrequest->lastname);
			$dn->addOu('SomeOU');
			$dn->addOU('SomeOU');
			$dn->addOU('SomeOU');
			$dn->addDc('xxintranet');
			$dn->addDc('com');			
			$user->setDn($dn);
                        $user->save()

Will return the following

+organizationUnits: array:3 [▼
    0 => "SomeOU"
    1 => "SomeOU"
    2 => "SomeOU"
  ]
  +domainComponents: array:4 [▼
    0 => "xxintranet"
    1 => "com"
    2 => "xxintranet"
    3 => "com"

**Comment by drifter104** [comment]
Strangely if I build the user with the following code it doesn't add the duplicate Dc.

$user = Adldap::make()->user([
			'cn' => ($dbrequest->firstname." ".$dbrequest->lastname[0]),
			'givenname' => ($dbrequest->firstname),
			'sn' => ($dbrequest->lastname),
			'dn' => "cn=$dbrequest->firstname $dbrequest->lastname,ou=SomeOu,ou=SomeOu,ou=SomeOu,dc=xxintranet,dc=com"
			]);

It appears as though the default behaviour of adding the base_dn is being completed to "early" in the process. I've added extra code to the OP to  make it more obvious

**Comment by stevebauman** [comment]
Hi @drifter104,

This is actually intended. Calling `getDnBuilder()` on a **new** model will create a DN builder instance with your `base_dn` included, so you don't have to add it yourself:

https://github.com/Adldap2/Adldap2/blob/f38a58161c07a295f67d3e8877c4236cdd9170e6/src/Models/Model.php#L372-L384

If you want a new instance to avoid this feature, call the `getNewDnBuilder()` instead:

https://github.com/Adldap2/Adldap2/blob/f38a58161c07a295f67d3e8877c4236cdd9170e6/src/Models/Model.php#L386-L396
