### ISSUE TITLE
Unable to login when ldap connection is unavailable (sync set to true)

### ISSUE THREAD

**Issue by JsonWud** [Adldap2/Adldap2-Laravel#668]
- Laravel Version: 5.7.26
- Adldap2-Laravel Version: 5.1.1
- PHP Version: 7.1.9
- LDAP Type: ActiveDirectory

Description: I have configured Adldap2-Laravel according to the setup docs, and it works as expected when my ActiveDirectory server is up. When I pause my AD server VM to simulate the connection going down, I am unable to login with credentials that work when the AD server is available. I'm wondering if I am missing some setting or if I misunderstand the expected behavior. Below is my ldap_auth.php file. I only have the following configured in my .env file:
LDAP_USERNAME=administrator@domain1
LDAP_PASSWORD=********
LDAP_PASSWORD_SYNC=true

Steps To Reproduce:
1. With database, laravel app, and AD server running, login with test user successfully.
2. Pause AD server vm, simulating the connection going down.
3. Attempt login with the same test user.
4. Receive error message "These credentials do not match our records." on the login page and see the following error in the log file:
[2019-02-14 20:08:18] local.ERROR: Adldap\Auth\BindException: Can't contact LDAP server in C:\MyApps\appWithAdLdap2\vendor\adldap2\adldap2\src\Auth\Guard.php:78

**Comment by JsonWud** [comment]
`---------- ldap_auth.php contents ----------
<?php

return [

    'connection' => env('LDAP_CONNECTION', 'default'),

    'provider' => Adldap\Laravel\Auth\DatabaseUserProvider::class,

    'model' => App\User::class,

    'rules' => [

        Adldap\Laravel\Validation\Rules\DenyTrashed::class,

    ],

    'scopes' => [

    ],

    'usernames' => [

        'ldap' => [

            'discover' => 'userprincipalname',

            'authenticate' => 'distinguishedname',
            // 'authenticate' => 'userprincipalname',

        ],

        'eloquent' => 'email',

        'windows' => [

            'discover' => 'samaccountname',

            'key' => 'AUTH_USER',

        ],

    ],

    'passwords' => [

        'sync' => env('LDAP_PASSWORD_SYNC', true),

        'column' => 'password',

    ],


    'login_fallback' => env('LDAP_LOGIN_FALLBACK', false),


    'sync_attributes' => [

        'email' => 'userprincipalname',

        'name' => 'cn',

    ],

    'logging' => [

        'enabled' => true,

        'events' => [

            \Adldap\Laravel\Events\Importing::class => \Adldap\Laravel\Listeners\LogImport::class,
            \Adldap\Laravel\Events\Synchronized::class => \Adldap\Laravel\Listeners\LogSynchronized::class,
            \Adldap\Laravel\Events\Synchronizing::class => \Adldap\Laravel\Listeners\LogSynchronizing::class,
            \Adldap\Laravel\Events\Authenticated::class => \Adldap\Laravel\Listeners\LogAuthenticated::class,
            \Adldap\Laravel\Events\Authenticating::class => \Adldap\Laravel\Listeners\LogAuthentication::class,
            \Adldap\Laravel\Events\AuthenticationFailed::class => \Adldap\Laravel\Listeners\LogAuthenticationFailure::class,
            \Adldap\Laravel\Events\AuthenticationRejected::class => \Adldap\Laravel\Listeners\LogAuthenticationRejection::class,
            \Adldap\Laravel\Events\AuthenticationSuccessful::class => \Adldap\Laravel\Listeners\LogAuthenticationSuccess::class,
            \Adldap\Laravel\Events\DiscoveredWithCredentials::class => \Adldap\Laravel\Listeners\LogDiscovery::class,
            \Adldap\Laravel\Events\AuthenticatedWithWindows::class => \Adldap\Laravel\Listeners\LogWindowsAuth::class,
            \Adldap\Laravel\Events\AuthenticatedModelTrashed::class => \Adldap\Laravel\Listeners\LogTrashedModel::class,

        ],
    ],

];`

**Comment by stevebauman** [comment]
Hi @JsonWud,

You have to enable the `login_fallback` option alongside the `password_sync` option to be able to login when the connection fails.

Give that a shot and let me know if you encounter issues.

**Comment by JsonWud** [comment]
Thank you, Steve. That worked. The docs were not clear that both had to be set to true. Thanks again.

**Comment by stevebauman** [comment]
Thanks @JsonWud, I'll update the docs to reflect this, I appreciate you letting me know! :smile:
