### ISSUE TITLE
Package install issue

### ISSUE THREAD

**Issue by JshuSlater** [Adldap2/Adldap2-Laravel#669]
- Laravel Version: 5.7.26
- Adldap2-Laravel Version: Latest
- PHP Version: 7.2.15
- LDAP Type: ActiveDirectory

Description:
I have an issue, when trying to install adldap-laravel. When run **composer require adldap2/adldap2-laravel** server returns:
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for adldap2/adldap2-laravel ^5.1 -> satisfiable by adldap2/adldap2-laravel[v5.1.0, v5.1.1].
    - Can only install one of: adldap2/adldap2[v9.0.x-dev, v10.0.1].
    - Can only install one of: adldap2/adldap2[v9.0.x-dev, v10.0.1].
    - Can only install one of: adldap2/adldap2[v9.0.x-dev, v10.0.1].
    - Conclusion: install adldap2/adldap2 v9.0.x-dev
    - Installation request for adldap2/adldap2 (locked at v10.0.1, required as ^10.0) -> satisfiable by adldap2/adldap2[v10.0.1].


Installation failed, reverting ./composer.json to its original content.

```

Here is my composer.json require section:
```
"require": {
        "php": "^7.1.3",
        "adldap2/adldap2": "^10.0",
        "fideloper/proxy": "^4.0",
        "laravel/framework": "5.7.*",
        "laravel/tinker": "^1.0"
    },
```

**Comment by Ranfty** [comment]
I had something similar a few days ago. Try the following:

1. Remove `adldap2` from your vendors directory.
2. Delete the following `adldap2/adldap2` section from your `composer.lock`:

```
    "packages": [
        {
            "name": "adldap2/adldap2",
            "version": "v9.1.4",
            "source": {
                "type": "git",
                "url": "https://github.com/Adldap2/Adldap2.git",
                "reference": ""
            },
            ...
        }
    ]
```

3. Run `composer require adldap2/adldap2-laravel`

**Comment by JshuSlater** [comment]
**Ranfty,** thank u for reply.

I think it's wrong decision, because if i do ecxatly what you reccomended, server returns:

```
./composer.json has been updated


  [RuntimeException]
  Your composer.lock was created before 2012-09-15, and is not supported anymore. Run "composer update" to generate a new one.
```

If i run `composer update`, it will install adldap2/adldap2 package, because composer.json still contains the same requirements.

Also, if I delete adldap2/adldap2 requirement from composer.json, then run `1. composer require adldap2/adldap2-laravel` server returns:
```

Using version ^5.1 for adldap2/adldap2-laravel
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install adldap2/adldap2-laravel v5.1.1
    - Installation request for adldap2/adldap2-laravel ^5.1 -> satisfiable by adldap2/adldap2-laravel[v5.1.0, v5.1.1].
    - Conclusion: don't install adldap2/adldap2 v10.0.1
    - adldap2/adldap2-laravel v5.1.0 requires adldap2/adldap2 ^9.0 -> satisfiable by adldap2/adldap2[v9.0.0, v9.0.1, v9.0.2, v9.0.x-dev, v9.1.0, v9.1.1, v9.1.2, v9.1.3, v9.1.4].
    - Can only install one of: adldap2/adldap2[v9.0.0, v10.0.1].
    - Can only install one of: adldap2/adldap2[v9.0.1, v10.0.1].
    - Can only install one of: adldap2/adldap2[v9.0.2, v10.0.1].
    - Can only install one of: adldap2/adldap2[v9.0.x-dev, v10.0.1].
    - Can only install one of: adldap2/adldap2[v9.1.0, v10.0.1].
    - Can only install one of: adldap2/adldap2[v9.1.1, v10.0.1].
    - Can only install one of: adldap2/adldap2[v9.1.2, v10.0.1].
    - Can only install one of: adldap2/adldap2[v9.1.3, v10.0.1].
    - Can only install one of: adldap2/adldap2[v9.1.4, v10.0.1].
    - Installation request for adldap2/adldap2 (locked at v10.0.1) -> satisfiable by adldap2/adldap2[v10.0.1].


Installation failed, reverting ./composer.json to its original content.

```
Or am i did something wrong?

**Comment by stevebauman** [comment]
Hi @JshuSlater, this is because you have both `adldap2/adldap2` and `adldap2/adldap2-laravel` in your `composer.json` file.

You can only have one or the other, as the `adldap2/adldap2-laravel` automatically requires `adldap2/adldap2` as shown here:

https://github.com/Adldap2/Adldap2-Laravel/blob/293721cd55b9410e274985ec6f869ea0cc499275/composer.json#L9

Adldap2 v10 is not yet compatible with Adldap2-Laravel, so that is why you're getting the require error.

If you need version 10 of Adldap2, you can require the `dev-master` version of Adldap2-Laravel. However a new major version of Adldap2-Laravel will be coming out in the coming days with new features (`v6.0`).

**Comment by JshuSlater** [comment]
Thanks a lot @stevebauman, @Ranfty! My bad. Sometghing made me think adldap2-laravel requires adldap2 package.

After deleting adldap2/adldap2 from vendor folder (and require record from composer.json), i run "composer update". After that package was installed successfully.

**Comment by stevebauman** [comment]
No worries @JshuSlater! Glad you were able to resolve the issue :smile:
