### ISSUE TITLE
sync_attributes not working for office number ?

### ISSUE THREAD

**Issue by st-claude** [Adldap2/Adldap2-Laravel#67]
hello there :)

i have a field in my AD called "Office" so i added in my sync_attributes :
`
'sync_attributes' => [

    'name' => 'cn',
    'email' => 'mail',
    'department' => 'department',
    'room' => 'office',
],

`
but it's like it's not recognized
it works for any other field (like 'room' => 'mobile' for example, i got the mobile number written in the users database) but for office, i just receive null...

i'm able to get the office using the model :
$room = $user->adldapUser->getPhysicalDeliveryOfficeName();

but for the login, trying to update the users table, it seems to not receiving anything, and thus writing NULL in the db

is it a bug or do i do i miss something/do something wrong ?

thanks

**Comment by stevebauman** [comment]
If `getPhysicalDeliveryOfficeName ()` works, then you actually need to sync the attribute named `physicaldeliveryofficename`.

**Comment by st-claude** [comment]
indeed, thanks !
