### ISSUE TITLE
Tag for Laravel 5.8

### ISSUE THREAD

**Issue by harrygulliford** [Adldap2/Adldap2-Laravel#678]
Hi @stevebauman, any chance in tagging a new version for 5.8 support? Thanks a million!

**Comment by stevebauman** [comment]
Hi @harrygulliford, I’ll be able to tomorrow when I’m home. I’m in India at the moment (returning to Canada tomorrow) and I don’t have access to a computer with a solid connection right now. I really appreciate your patience! :smile:

**Comment by stevebauman** [comment]
`v5.1.2` released. Thanks!

**Comment by ThomHurks** [comment]
@stevebauman Did you accidentally release v6 as 5.1.2? All the config files are different and 5.1.2 pulls in ADLDAP v10 now, that doesn't seem like a release that only fixes Laravel 5.8 compatibility.

**Comment by stevebauman** [comment]
Shoot, I must have chosen the wrong branch! Was doing it from a smartphone so that’s completely my mistake, apologies. I’ll be able to push out a proper release tomorrow once I’m home from vacation. Thanks for letting me know!

I pulled the release from GitHub and Packagist.

**Comment by ThomHurks** [comment]
@stevebauman No problem. This is what you get when trying to work on a vacation; never work on vacation ;)

**Comment by stevebauman** [comment]
Haha truth @ThomHurks! Okay I've released the proper version now. Appreciate your patience!

**Comment by zahirzohair** [comment]
Hi everyone, I got this issue:   Call to undefined method Illuminate\Events\Dispatcher::fire()
I tried many suggestions from github and other resources but no luck yet.
 is there any other solution please ? thanks!

**Comment by stevebauman** [comment]
Hey @zahirzohair,

What version are you using? This was patched in v6.

**Comment by zahirzohair** [comment]
laravel verion 5.8 
"Adldap2/Adldap2-Laravel": "6.0.0". 
when i run composer update it shows the following: 
- Installation request for adldap2/adldap2-laravel 6.0.0 -> satisfiable by adldap2/adldap2-laravel[v6.0.0].

  To enable extensions, verify that they are enabled in your .ini files:
    - C:\xampp\php\php.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.

**Comment by stevebauman** [comment]
Sounds like there’s a requirement missing in your PHP installation? Is your LDAP extension enabled?

**Comment by zahirzohair** [comment]
I am not sure. yah I enabled this : extension=ldap   in php.ini file. now composer update runs but the app still shows the  " Call to undefined method Illuminate\Events\Dispatcher::fire() "

**Comment by stevebauman** [comment]
What’s the stack trace? Is it for sure being called by Adldap2-Laravel?

**Comment by zahirzohair** [comment]
this is the error message:
  Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_ERROR)
Call to undefined method Illuminate\Events\Dispatcher::fire()

and this is the directory that shows there:
Symfony\Component\Debug\Exception\FatalThrowableError 
…/vendor/santigarcor/laratrust/src/Traits/LaratrustHasEvents.php46

**Comment by stevebauman** [comment]
Seems that Laratrust is causing this error, not Adldap2.

**Comment by zahirzohair** [comment]
yah it shows that but i cannot bring any changes in that file because that is in /Vendor. anyway, thank you very much for your time and effort. @stevebauman

**Comment by stevebauman** [comment]
Yeah you might have to notify the authors of that package and let them know their package isn’t compatible with Laravel 5.8. No problem at all!
