### ISSUE TITLE
Model Issue

### ISSUE THREAD

**Issue by bstump** [Adldap2/Adldap2-Laravel#68]
I'm getting this issue when I try to post the login form:

Call to undefined method Adldap\Laravel\Facades\Adldap::users()

I've went through and installed all of the LDAP extensions on my LEMP server, but I keep getting this. Any ideas?

**Comment by stevebauman** [comment]
Have you registered the facade in your `config/app.php` file?

https://github.com/Adldap2/Adldap2-Laravel#installation

```php
'Adldap' => Adldap\Laravel\Facades\Adldap::class
```

**Comment by bstump** [comment]
Yes, but I had to register with the key 'adldap' (not a capital A) because that class returns 'adldap' instead of 'Adldap'. Even if I correct it, I'm getting the same error. This is Laravel 5.2 and I followed those instructions but seem to still be having an issue.

**Comment by stevebauman** [comment]
I don't think the casing of the key makes a difference. Try clearing your configurations cache by performing:

```cmd
php artisan config:clear
```

**Comment by stevebauman** [comment]
Are you still having this issue?

**Comment by bstump** [comment]
I ended up using another library. This can be closed. Thanks.
