### ISSUE TITLE
Login attempts failing using samaccountname

### ISSUE THREAD

**Issue by sachaw** [Adldap2/Adldap2-Laravel#680]
- Laravel Version: 5.7
- Adldap2-Laravel Version: 5.1.1
- PHP Version: 7.3
- LDAP Type: ActiveDirectory

### Description:
Unable to login, it was previously working but upon deploying a fresh instance of my application it has stopped, my setup is as follows:

**ldap_auth.php**
`
'ldap' => [
            'discover' => 'samaccountname',
            'authenticate' => 'distinguishedname',
        ],
`

sending a valid normal authentication request (via passport) returns the normal invalid credentials response:
`
{
  "error": "invalid_credentials",
  "message": "The user credentials were incorrect."
}
`

when calling `dldap::search()->users()->find('username')` where `username` is a valid `samaccountname` it returns the user correctly.

However when calling `Adldap::auth()->attempt('username', 'password')` where `username` is a valid `samaccountname` the attempt returns `false`

Upon calling the above statement again but supplementing `username` for a valid `displayname`/`name` or `distinguishedname` it returns `true`.

any idea why this might be happening, or some advice/steps to better debug, thanks.

**Comment by stevebauman** [comment]
Hi @sachaw,

ActiveDirectory only allows authentication using users `userPrincipalName` or their `distinguishedName`. `samAccountName`s cannot be used for binding.

If you’d like to use `samAccountName`s, use the `account_suffix` config option and insert your domains `userPrincipalName` suffix (such as “@corp.acme.org”.

If you need any further explanation or still run into issues give me a shout and I’ll reopen this, thanks!

**Comment by sachaw** [comment]
Thanks for the reply, but that's not exactly my issue, may main issue is despite having my `discover` attribute set to `samaccountname` and `authenticate` set to `distinguishedname` I cannot login, using passport.
Even if I set `discover` and `authenticate` to `
userPrincipalName` it keeps returning an invalid credentials response

so basically:
I can call `Adldap::auth()->attempt` but it ignores what ever ` discover` is set to.
I cannot login normally with anything

Thanks.

**Comment by stevebauman** [comment]
The config attributes you’re referring to (`discover` & `authenticate`) only relate to the Adldap2-Laravel auth driver when calling Laravel’s `Auth::attempt()` facade.

They have no effect on the root Adldap2 instance when calling `Adldap::auth()->attempt();` - this is calling a direct `ldap_bind()` to your server which does not support using `samAccountName`s. When calling `Adldap::auth()->attempt()`, you **must** provide the users username as their full distinguished name *or* their userPrincipalName.

I hope I’m making sense, but if you need further clarification give me a shout and I’ll reopen this.

Thanks!
