### ISSUE TITLE
Adldap configuration could not be found.

### ISSUE THREAD

**Issue by saabarukyatto** [Adldap2/Adldap2-Laravel#682]
- Laravel Version: 5.7
- Adldap2-Laravel Version: 5.1.1
- PHP Version: 7.2.11
- LDAP Type: ActiveDirectory

I followed this guide thoroughly, so the alias is declared, the config files are presents etc...
https://adldap2.github.io/Adldap2-Laravel/#/auth/introduction

But when trying out the test code:
`$users = \Adldap\Laravel\Facades\Adldap::search()->users()->get();
dd($users);`

I'm getting this weird error:
Adldap configuration could not be found. Try re-publishing using `php artisan vendor:publish`.

By looking at where the error comes from it seems that Adldap can't find the config file somehow.
Re-publishing changes nothing. Clearing the app cache doesn't help either.
No similar issue could be found on google... I'm pretty stuck right now.

-S

**Comment by stevebauman** [comment]
Did you clear your config cache using `php artisan config:clear`? Also, does the `ldap.php` config file exist in your `config/` directory?

**Comment by saabarukyatto** [comment]
Will try in a few minutes. Thanks for the fast reply.

**Comment by stevebauman** [comment]
No problem! I’m standing by :smile:

**Comment by saabarukyatto** [comment]
Yep config:clear solved the issue, thank you very much.

**Comment by saabarukyatto** [comment]
Is this command in the documentation ?

**Comment by stevebauman** [comment]
Great! Glad you resolve the issue. The `php artisan config:clear` method is a Laravel command and isn’t related to Adldap2.

Config caching has to be enabled by the developer per Laravel application so it is not contained in the documentation as this would affect any package you install that requires a published configuration file.
