### ISSUE TITLE
Call to undefined method Illuminate\Events\Dispatcher::fire()

### ISSUE THREAD

**Issue by sachaw** [Adldap2/Adldap2-Laravel#684]
- Laravel Version: 5.8
- Adldap2-Laravel Version: 5.1.1
- PHP Version: 7.3
- LDAP Type: ActiveDirectory

### Description:
After submitting an auth request using the scaffolding, it returns the following exception
`Call to undefined method Illuminate\Events\Dispatcher::fire()`

I replicated it on a clean install following
`https://adldap2.github.io/Adldap2-Laravel/#/auth/introduction` exactly

**Comment by ThomHurks** [comment]
A release will be out soon with Laravel 5.8 support, for now stick to Laravel 5.7. See #678

**Comment by sachaw** [comment]
Thanks for the response, is there any way to get it to work, i.e. pulling from master/another branch for now?

**Comment by ThomHurks** [comment]
Latest from branch v5 should work I think.

**Comment by bgarrison25** [comment]
I will attempt this since im getting the same issue trying to go to 5.8

**Comment by bgarrison25** [comment]
After upgrading to 5.1.2 I got the following error: Authentication user provider [adldap] is not defined.

**Comment by stevebauman** [comment]
Hi @bgarrison25, in v5 the auth driver was renamed from `adldap` to `ldap`. This is described in the upgrade guide:

https://adldap2.github.io/Adldap2-Laravel/#/upgrading?id=authentication-driver
