### ISSUE TITLE
Adding newly registered users to OpenLDAP directory

### ISSUE THREAD

**Issue by pprotas** [Adldap2/Adldap2-Laravel#686]
- Laravel Version: 5.8
- Adldap2-Laravel Version: 9.0
- PHP Version: 7.2
- LDAP Type: OpenLDAP

### Description:
After a lot of trial and error i got my login system to work using [the quickstart guide](https://adldap2.github.io/Adldap2-Laravel/#/auth/introduction?id=quick-start-from-scratch). I was wondering if there is a similar tutorial/document for **registering** users to my LDAP server using Adldap2, seeing as currently my newly registered users only get added to the MySQL database and i can't use their credentials to login ("These credentials do not match our records." error). Maybe i'm doing something wrong, i am new to this framework and ldap.

### Steps To Reproduce:
1. Follow the quickstart guide (i used OpenLDAP)
2. Register a new user in register.blade.php
3. Try to log in with the newly created user
4. Can't log in

**Comment by stevebauman** [comment]
Hi @pprotas,

There is no built in functionality for registering users and creating them in your LDAP server. You will have to build this yourself.

When you register a new user using Laravel's default registration controllers and views, it will simply register a user normally in your MySQL database, but it will not touch your LDAP server in any way.

If you would like to allow MySQL registered users to log in normally into your application, as well as LDAP users, set the `login_fallback` option to `true` in your `ldap_auth.php` configuration file.
