### ISSUE TITLE
Unable to retrieve Primary Group from Active Directory

### ISSUE THREAD

**Issue by rizalkadis** [Adldap2/Adldap2-Laravel#687]
- Laravel Version: 5.7.28
- Adldap2-Laravel Version: 10.0.3
- PHP Version: 7.2.11
- LDAP Type: ActiveDirectory

**Description:**

I want to get Primary Group for the users using the script below:-

$groups = $users->getPrimaryGroup();

but unfortunately it return nothing. I try to find the root cause by looking at getPrimaryGroup() method in User.php. When I put this script print_r($this->getConvertedSid()); , the SID is different from the SID in Active Directory.

The SID display on the screen is "S-1-5-21-26790432-3878837506-1146548017-1344" but the actual SID in Active Directory is "S-1-5-21-26790432-3878837506-1146548017-2503".

Anyone can help on this issue?

**Comment by stevebauman** [comment]
Hi @rizalkadis,

Can you post your whole script? Will help to debug easier.

**Comment by rizalkadis** [comment]
> Hi @rizalkadis,
> 
> Can you post your whole script? Will help to debug easier.

Hi @stevebauman 

Sorry, my mistake because I echo wrong variable. The framework can retrieve the SID correctly which is "S-1-5-21-26790432-3878837506-1146548017-2503". However, when I try to retrieve the primary group from UserController.php, no groups were display on the screen. Below is the code:

<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Repositories\UserRepository;
use Illuminate\Support\Facades\Auth;
use App\Repositories\RoleRepository;
use Adldap\AdldapInterface;

class UserController extends Controller
{
	
	protected $user;
	protected $role;
	protected $ldap;

    public function __construct(
		UserRepository $userRepository,
		RoleRepository $roleRepository,
		AdldapInterface $ldap
	)
    {
        $this->user = $userRepository;
		$this->role = $roleRepository;
		$this->ldap = $ldap;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if ($request->wantsJson()) {
            return $this->user->jsGrid($request);
        }
		
		$users = $this->ldap->search()->users()->findBy('samaccountname', 'farhana');
		

		if ($users) {
			$groups = $users->getPrimaryGroup();
		}
				

        return view('users.index', compact('users','groups'));
    }
}

**Comment by rizalkadis** [comment]
Just to add more information, I edit vendor\adldap2\adldap2\src\Models\User.php as give below:

 ```
public function getPrimaryGroup()
   {
		
        $groupSid = preg_replace('/\d+$/', $this->getPrimaryGroupId(), $this->getConvertedSid());
	echo "SID : ".$groupSid;
	echo "<br>";
	echo "Result : ";
	var_dump($this->query->newInstance()->findBySid($groupSid));
		
	exit();
        return $this->query->newInstance()->findBySid($groupSid);
    }
```

The ouput if given below:

SID : S-1-5-21-26790432-3878837506-1146548017-2503
Result : bool(false)

Seem like it can't retrieve the primary group by the SID given.

**Comment by stevebauman** [comment]
Hmmm strange... What is your `base_dn` set to in your configuration?

**Comment by stevebauman** [comment]
It's possible that your primary group isn't being located if you set your `base_dn` to something higher than the actual base DN of your directory.

Usually the default primary group resides in `CN=Users,DC=corp,DC=acme,DC=org`, so if you set your `base_dn` to `OU=Users,DC=corp,DC=acme,DC=org`, then a primary group won't be located due to it being located outside the scope the base DN you have given.

Let me know and we can continue debugging :smile:

**Comment by rizalkadis** [comment]
Hi @stevebauman ,

My ldap configuration is 

`'base_dn' => env('LDAP_BASE_DN', 'ou=user directory,dc=corp,dc=acme,dc=org'),`

So I took your advice and change it to

`'base_dn' => env('LDAP_BASE_DN', 'dc=corp,dc=acme,dc=org'),`

Now, it works like a charm. I can see the group

`CN=server,OU=group directory,dc=corp,dc=acme,dc=org`

Thank you so much!

**Comment by stevebauman** [comment]
Awesome @rizalkadis! Glad you were able to resolve it. No problem at all :smile:
