### ISSUE TITLE
How do I create a user?

### ISSUE THREAD

**Issue by damcclean** [Adldap2/Adldap2-Laravel#688]
- Laravel Version: 5.8.0
- Adldap2-Laravel Version: 5.1
- PHP Version: 7.2
- LDAP Type: Active Directory

### Description:
I'm trying to create a User using the code below. Although, it's not working. I've attempted to try and find where this would be in the source code but could not find it. How would I do this?

```
use Adldap\Laravel\Facades\Adldap;
...
$user = Adldap::make()->user([
            'cn' => $request->name
        ]);
```

**Comment by stevebauman** [comment]
Hi there @damcclean,

This documentation resides in the core Adldap2 repository here:

https://adldap2.github.io/Adldap2/#/models/model?id=creating-updating

You're almost there with the code you've posted. You need to call `save()` after constructing a new `User` model:

```php
use Adldap\Laravel\Facades\Adldap;

$user = Adldap::make()->user([
    'cn' => $request->name
]);

$user->save();
```

However, this will create a user in your configured `base_dn` that resides in your `config/ldap.php` file.

You will likely need to create your user a distinguished name:

```php
use Adldap\Laravel\Facades\Adldap;

$user = Adldap::make()->user([
    'cn' => $request->name,
    'dn' => "cn={$request->name},ou=User,dc=acme,dc=org"
]);

$user->save();
```

You can also use the DN builder to create distinguished names for you:

```php
use Adldap\Laravel\Facades\Adldap;

$user = Adldap::make()->user([
    'cn' => $request->name,
]);

$dn = $user->getDnBuilder()->addOu('Users'); // Built DN will be: "CN=John Doe,OU=Users,DC=acme,DC=org";

$user->setDn($dn);

$user->save();
```

If you encounter any issues, please comment back and I'll re-open this. Thanks!

**Comment by stevebauman** [comment]
Another note:

You'll likely want to create the user with an account name, password, and then mark the account as enabled. This unfortunately has to be done in two different save events, as ActiveDirectory won't let you enable an account without a password:

```php
$user = Adldap::make()->user([
    'cn' => $request->name,
]);

// Create the users distinguished name.
$dn = $user->getDnBuilder()->addOu('Users'); // Built DN will be: "CN=John Doe,OU=Users,DC=acme,DC=org";

// Set the users DN, account name, and password.
$user->setDn($dn);
$user->setAccountName('jdoe');
$user->setPassword('correct-horse-battery-staple');

$user->save();

// Get a new account control object.
$ac = $user->getUserAccountControlObject();

// Mark the account as enabled (normal).
$ac->accountIsNormal();

// Set the account control on the user and save it.
$user->setUserAccountControl($ac)->save();
```

**Comment by damcclean** [comment]
Hey, thanks for your response! I'll let you know if I have any further questions.

**Comment by Zainubaba** [comment]
when i use 
![image](https://user-images.githubusercontent.com/76861922/148013759-10ce52f4-149a-4091-a95d-d7189785dc58.png)
this show error 
![image](https://user-images.githubusercontent.com/76861922/148013815-14ce75db-86d1-4b61-83b2-c62265172993.png)
but login with active directory is fine with ldap

**Comment by vimaltest099** [comment]
Hi All,

$user=$adldap->search()->users()->findBy('userPrincipalName', $attributes['userPrincipalName']);
                        $password='@%fedfC!0ud#0$t!ng';
                        $user->setPassword($password);
                        $user->save();
                        
                    when i am doing this,getting error ldap_modify_batch(): Batch Modify: Server is unwilling to perform": 
                    To check weather ssl or tls i am checking by \Log::info($adldap->getConnection()->isUsingSSL()); and getting 1 on laravel-logs
                    
                   anyone have solution ?
