### ISSUE TITLE
Set User Role Based on LDAP Authentication and Roles Table

### ISSUE THREAD

**Issue by requincreative** [Adldap2/Adldap2-Laravel#689]
- Laravel Version: #.# 5.8.3
- Adldap2-Laravel Version: #.# 10.0
- PHP Version: #.# 7.3.2
- LDAP Type: ActiveDirectory

### Description:

I am using the ADLDAP2 - Laravel to authenticate my users and I have it working successfully with Laravel 5.8.3.

The only thing I would like to do is loop through my Roles table (id, ad_group, name)and check the AD group membership of the authenticated user and then update the role column (assign a role) to my user in the Users table.

I have the following code written but I don't know where to place it in order to have it run as soon as the the user is successfully authenticated against LDAP:

```
if ( $this->ldap != null) {

        $user = User::findOrFail($this->id);
        $roles = Role::all();

          foreach ($roles as $role) {
             $assigned = $this->ldap->inGroup($role->name) ? $role->id : 0;    
           }
    
         $user->role = $assigned;
            $user->save();
     } 
```

This is currently placed in my User model as a function that is called in the template for testing.

Of course it should not run if an LDAP connection is not detected or it will error out.

**Comment by requincreative** [comment]
I finally figured out a solution using the authenticated method override in LoginController

`
protected function authenticated($request)
    {

        
         if ( request()->user()->ldap != null) {

            $user = User::findOrFail(request()->user()->id);
            $roles = Role::all();
    
            foreach ($roles as $role) {
                $assigned = request()->user()->ldap->inGroup($role->name) ? $role->id : 0;    
            }
            
            $user->role = $assigned;
            $user->save();
    
             } 
    }
   
`

**Comment by stevebauman** [comment]
Hi @requincreative,

Just wanted to chime in here for a couple of alternate approaches as well (though what you're doing is not wrong at all) for anyone looking at this in the future.

Using an [LDAP Attribute Handler](https://adldap2.github.io/Adldap2-Laravel/#/auth/setup?id=attribute-handlers) to sync your user roles upon login:

```php
namespace App\Handlers;

use App\User as EloquentUser;
use Adldap\Models\User as LdapUser;

class LdapAttributeHandler
{
    /**
     * Synchronizes LDAP attributes to the specified model.
     *
     * @param LdapUser     $ldapUser
     * @param EloquentUser $eloquentUser
     *
     * @return void
     */
    public function handle(LdapUser $ldapUser, EloquentUser $eloquentUser)
    {
        $eloquentUser->name = $ldapUser->getCommonName();

        $roles = Role::all();

        foreach ($roles as $role) {
            $assigned = $ldapUser->inGroup($role->name) ? $role->id : 0;    
        }
        
        $eloquentUser->role = $assigned;
        $eloquentUser->save();
    }
}
```

Or listen for the `Adldap\Laravel\Events\AuthenticationSuccessful` event and sync their roles upon login:

> **Note**: You can also use the `Adldap\Laravel\Events\Imported` event if you only want to sync their role upon their *first* login only.

```php
<?php

namespace App\Listeners;

use Adldap\Laravel\Events\AuthenticationSuccessful;

class SynchronizeUserRoleFromLDAP
{
    /**
     * Handle the event.
     *
     * @param AuthenticationSuccessful $event
     *
     * @return void
     */
    public function handle(AuthenticationSuccessful $event)
    {
        $roles = Role::all();

        foreach ($roles as $role) {
            $assigned = $event->user->inGroup($role->name) ? $role->id : 0;    
        }
        
        $event->model->role = $assigned;
        $event->model->save();
    }
}
```

Thanks for following up with your implementation and closing the issue.
