### ISSUE TITLE
I can import users, but login failed

### ISSUE THREAD

**Issue by ahmad980098** [Adldap2/Adldap2-Laravel#690]
- Laravel Version: 5.6
- Adldap2-Laravel Version: 5.1
- PHP Version: 7.2
- LDAP Type: OpenLDAP
### Description:
I used this library to sync my laravel app with openLDAP server.
when I tried to test with forumsys.com openLdap server everything is ok,but when I try to sync it with my customers openLdap server I cant login,

I connected to the server successfully.
I can see and import users successfully by
`php artisan adldap:import`

### but when I try to login with a user, I got an error  "invalid credentials" 

my .env config:
`LDAP_SCHEMA=OpenLDAP
LDAP_HOSTS="my host IP"
LDAP_BASE_DN=ou=test1,ou=test2,dc=example,dc=com
LDAP_USER_ATTRIBUTE=uid
LDAP_USER_FORMAT=uid=%s,test1,ou=test2,dc=example,dc=com
LDAP_CONNECTION=default`
ldap.php file:
`'connections' => [

		'default' => [
			'auto_connect' => env('LDAP_AUTO_CONNECT', false),
			'connection' => Adldap\Connections\Ldap::class,
			'settings' => [

				// replace this line:
				// 'schema' => Adldap\Schemas\ActiveDirectory::class,
				// with this:
				'schema' => env('LDAP_SCHEMA', '') == 'OpenLDAP' ?
					Adldap\Schemas\OpenLDAP::class :
					( env('LDAP_SCHEMA', '') == 'FreeIPA' ?
						Adldap\Schemas\FreeIPA::class :
						Adldap\Schemas\ActiveDirectory::class ),

				'account_prefix' => env('LDAP_ACCOUNT_PREFIX', ''),
				'account_suffix' => env('LDAP_ACCOUNT_SUFFIX', ''),
				'hosts' => explode(' ', env('LDAP_HOSTS', 'corp-dc1.corp.acme.org corp-dc2.corp.acme.org')),
				'port' => env('LDAP_PORT', 389),
				'timeout' => env('LDAP_TIMEOUT', 5),
				'base_dn' => env('LDAP_BASE_DN', 'dc=corp,dc=acme,dc=org'),
				'username' => env('LDAP_ADMIN_USERNAME', ''),
				'password' => env('LDAP_ADMIN_PASSWORD', ''),
				'follow_referrals' => env('LDAP_FOLLOW_REFERRALS', false),
				'use_ssl' => env('LDAP_USE_SSL', false),
				'use_tls' => env('LDAP_USE_TLS', false),
			],
		],

	],`
ldap_auth.php file:
`<?php
return [
    'connection' => env('LDAP_CONNECTION', 'default'),

    'provider' => Adldap\Laravel\Auth\DatabaseUserProvider::class,

    'model' => App\User::class,

    'rules' => [

        // Denys deleted users from authenticating.

        Adldap\Laravel\Validation\Rules\DenyTrashed::class,

        // Allows only manually imported users to authenticate.

        // Adldap\Laravel\Validation\Rules\OnlyImported::class,

    ],

    'scopes' => [

        // Only allows users with a user principal name to authenticate.
        // Suitable when using ActiveDirectory.
        // Adldap\Laravel\Scopes\UpnScope::class,

        // Only allows users with a uid to authenticate.
        // Suitable when using OpenLDAP.
        // Adldap\Laravel\Scopes\UidScope::class,

    ],

	'usernames' => [

		'ldap' => [

			// replace this line:
			// 'discover' => 'userprincipalname',
			// with this one:
			'discover' => env('LDAP_USER_ATTRIBUTE', 'userprincipalname'),

			// replace this line:
			// 'authenticate' => 'distinguishedname',
			// with this one:
			'authenticate' => env('LDAP_USER_ATTRIBUTE', 'distinguishedname'),

		],

		// replace this line:
		// 'eloquent' => 'email',
		// with this one:
		'eloquent' => 'username',

	],

    'passwords' => [

        'sync' => env('LDAP_PASSWORD_SYNC', false),

        'column' => 'password',

    ],

    'login_fallback' => env('LDAP_LOGIN_FALLBACK', false),

	'sync_attributes' => [
		// 'field_in_local_db' => 'attribute_in_ldap_server',
		'username' => 'uid', // was 'email' => 'userprincipalname',
		'name' => 'cn',
		'phone' => 'telephonenumber',
	],

    'logging' => [

        'enabled' => true,

        'events' => [

            \Adldap\Laravel\Events\Importing::class => \Adldap\Laravel\Listeners\LogImport::class,
            \Adldap\Laravel\Events\Synchronized::class => \Adldap\Laravel\Listeners\LogSynchronized::class,
            \Adldap\Laravel\Events\Synchronizing::class => \Adldap\Laravel\Listeners\LogSynchronizing::class,
            \Adldap\Laravel\Events\Authenticated::class => \Adldap\Laravel\Listeners\LogAuthenticated::class,
            \Adldap\Laravel\Events\Authenticating::class => \Adldap\Laravel\Listeners\LogAuthentication::class,
            \Adldap\Laravel\Events\AuthenticationFailed::class => \Adldap\Laravel\Listeners\LogAuthenticationFailure::class,
            \Adldap\Laravel\Events\AuthenticationRejected::class => \Adldap\Laravel\Listeners\LogAuthenticationRejection::class,
            \Adldap\Laravel\Events\AuthenticationSuccessful::class => \Adldap\Laravel\Listeners\LogAuthenticationSuccess::class,
            \Adldap\Laravel\Events\DiscoveredWithCredentials::class => \Adldap\Laravel\Listeners\LogDiscovery::class,
            \Adldap\Laravel\Events\AuthenticatedWithWindows::class => \Adldap\Laravel\Listeners\LogWindowsAuth::class,
            \Adldap\Laravel\Events\AuthenticatedModelTrashed::class => \Adldap\Laravel\Listeners\LogTrashedModel::class,

        ],
    ],`

my attempt login function in AthenticatesUser.php file that returns `false `:
` protected function attemptLogin(Request $request)
    {
	    $credentials = $request->only($this->username(), 'password');
	    $username = $credentials[$this->username()];
	    $password = $credentials['password'];

	    $user_format = env('LDAP_USER_FORMAT', 'cn=%s,'.env('LDAP_BASE_DN', ''));
	    $userdn = sprintf($user_format, $username);

	    if(Adldap::auth()->attempt($userdn, $password, $bindAsUser = true)) {
		    // the user exists in the LDAP server, with the provided password

		    $user = \App\User::where($this->username(), $username)->first();
		    if (!$user) {
		    	// the user doesn't exist in the local database, so we have to create one

			    $user = new \App\User();
			    $user->username = $username;
			    $user->name = $username;
			    $user->password = '';
			    $user->timestamps=Carbon::now();
			    $user->save();
			    $sync_attrs = $this->retrieveSyncAttributes($username);
			    if (is_array($sync_attrs) || is_object($sync_attrs)) {
				    foreach ($sync_attrs as $field => $value) {
					    $user->$field = $value !== null ? $value : '';
				    }
			    }
		    }

				$this->guard()->login($user, true);
				return true;
			
	    }

	    // the user doesn't exist in the LDAP server or the password is wrong
	    // log error
	    return false;
    }
`

**Comment by krisbai** [comment]
Is this problem solved？

**Comment by Vergence007** [comment]
Morning, 
Waiting also for solution about this issue.

**Comment by stevebauman** [comment]
Hi @ahmad980098,

You shouldn't need to do any of what you're doing in the `attemptLogin()` method -- in fact you shouldn't even have to modify it. This is the point of the `ldap_auth.php` configuration file.

The built-in Adldap2-Laravel auth driver imports and authenticates users for you. You are doing this all manually inside of your `attemptLogin()` method. This is why it's not working.

If you can, I'd heavily suggest moving to [LdapRecord](https://github.com/DirectoryTree/LdapRecord).

If you still have this issue after removing all of your modified code, let me know and I'll re-open this issue.

**Comment by Vergence007** [comment]
Hi @stevebauman, Thks for your response.
Could you see my issue #875 it's same without any modification into LoginController.
But i have error "Username must be specified".

See below my larevel_log when i try to login : [2020-06-17 13:09:17] local.INFO: User 'Isaac Newton' has been successfully found for authentication. [2020-06-17 13:09:17] local.INFO: User 'Isaac Newton' is being synchronized. [2020-06-17 13:09:17] local.INFO: User 'Isaac Newton' has been successfully synchronized. [2020-06-17 13:09:17] local.INFO: User 'Isaac Newton' is authenticating with username: '' [2020-06-17 13:09:17] local.ERROR: A username must be specified. {"exception":"[object] (Adldap\\Auth\\UsernameRequiredException(code: 0): A username must be specified."
