### ISSUE TITLE
Model binding is always null

### ISSUE THREAD

**Issue by benjivm** [Adldap2/Adldap2-Laravel#692]
- Laravel Version: 5.8.4
- Adldap2-Laravel Version: 6.0
- PHP Version: 7.3.2
- LDAP Type: ActiveDirectory

### Description:
Model Binding always returns null. All other functionality works as expected: logging in, data synchronization, etc. Here is my `User.php`:

```
use Adldap\Laravel\Traits\HasLdapUser;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable, HasLdapUser;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'username', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}
```

From reading the documentation I should now be able to access the LdapUser model via `$user->ldap`, however this always returns null.

**Comment by stevebauman** [comment]
Thanks @benjivm! I'm able to reproduce this in v6.0. Patch is coming shortly.

**Comment by benjivm** [comment]
Dang you're fast, thanks @stevebauman

**Comment by stevebauman** [comment]
Thanks @benjivm! I try, as I use Adldap2-Laravel in over 10 production applications internally.

Release is being created now, thanks again for bringing this up! My current tests didn't cover the `byModel()` method on the `UserResolver`, but I've now added one to cover it.

**Comment by benjivm** [comment]
Hmm, I am still having issues with this. The property works as expected on the `Auth::user()` class, however I cannot access `$user->ldap` when accessing it through the `App\User` class.

**Comment by stevebauman** [comment]
Hi @benjivm,

>  The property works as expected on the Auth::user() class, however I cannot access $user->ldap when accessing it through the App\User class.

The property is only set on the currently authenticated users model. Calling a `User::get()` method on your `User` eloquent model won't populate the `ldap` property on all returned users.

If you'd like to query for users in your directory, call the root `Adldap` instance:

```php
use Adldap\Laravel\Facades\Adldap;

$users = Adldap::search()->users()->get();
```

> I am also no longer seeing the correct error messages for failed logins, what used to be the "password is required" message, for example, is now just showing validation.required.

This doesn't seem to be related to the above issue, it seems you may have modified your validation rules for your login request?

Let me know if you would like further explanation or if you still need any help, thanks!

**Comment by benjivm** [comment]
Ahh, thanks for clearing up the `HasLdapUser` trait for me.

The validation messages were busted because I accidentally deleted the `resources\lang\en` directory, whoops!

**Comment by stevebauman** [comment]
No problem @benjivm! :smile:

**Comment by viniciusraupp** [comment]
Laravel Version: 5.8.16
Adldap2-Laravel Version: 6.0.5
PHP Version: 7.2
LDAP Type: Active Directory

Hy, model binding it's not working in my project, am I doing something wrong?

Model User.php
```php
use Adldap\Laravel\Traits\HasLdapUser;

class User extends Authenticatable
{
use HasLdapUser, [...];
```

Controller

```php
use Illuminate\Support\Facades\Auth;

class ProfileController extends Controller
{
    public function index()
    {
        $profile = Auth::user();

        // dd($profile); WORK return only DB data
        dd($profile->ldap); // DON'T WORK - return null
    }
```

**Comment by stevebauman** [comment]
Hi @viniciusraupp,

Are you logging in with the `ldap` auth driver?

**Comment by viniciusraupp** [comment]
Hi, thank you for your attention.

Config: auth.php
```php
'providers' => [
        'users' => [
            'driver' => 'ldap',
            'model' => App\User::class,
        ],
```

Migration file: 2014_10_12_000000_create_users_table.php

```php
public function up()
    {
        Schema::create('users', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->string('objectguid')->nullable();
            $table->string('name');
            $table->string('samaccountname');
            $table->string('username')->unique();
            $table->string('userprincipalname');
            $table->string('email');
           [...]
```

config('ldap')
```php
[
     "logging" => false,
     "connections" => [
       "default" => [
         "auto_connect" => true,
         "connection" => "Adldap\Connections\Ldap",
         "settings" => [
           "schema" => "App\Ldap\Schemas\LdapSchema",
           "account_prefix" => "",
           "account_suffix" => "",
           "hosts" => [
             "IP",
           ],
           "port" => "636",
           "timeout" => 5,
           "base_dn" => "dc=domain,dc=com",
           "username" => "DOMAIN\admin",
           "password" => "pwd",
           "follow_referrals" => false,
           "use_ssl" => true,
           "use_tls" => false,
           "custom_options" => [
             24582 => 0,
           ],
         ],
       ],
     ],
   ]

```

Own LDAP User model: 

```php
namespace App\Ldap\Models;

use Adldap\Models\User as Model;
use Illuminate\Foundation\Auth\Access\Authorizable;

class User extends Model
{

}
```

Own LDAP Schema:

```php
namespace App\Ldap\Schemas;

use Adldap\Schemas\ActiveDirectory;
use App\Ldap\Models\User;

class LdapSchema extends ActiveDirectory
{
    public function userModel()
    {
        return User::class;
    }
}
```

**Comment by Giddeon** [comment]
Hello, had anyone solved this issue?
I have the same problem and found no solution to it?

@stevebauman this issue is closed with some solution?
