### ISSUE TITLE
Authentication fails if using custom password column name

### ISSUE THREAD

**Issue by riples** [Adldap2/Adldap2-Laravel#694]
- Laravel Version: 5.6
- Adldap2-Laravel Version: 4.0
- PHP Version: 7.1
- LDAP Type: ActiveDirectory

### Description:
Authentication requires the password column name request to be lowercase. 

### Steps To Reproduce:
I have changed my column name in my Users table to be `Password` instead of `password` (for consistency) and I have made all modifications to settings (where I know of).  However, when I attempt `Auth::attempt( $request->only( ['Username', 'Password'] )` I get back the error `Adldap\Auth\PasswordRequiredException: A password must be specified.`  If I change the request from `Password` to `password`, the Auth works perfectly.  

I can also confirm that my database sync's the user record with `Password`, so it's like the Auth only is requiring the lowercase name.

**Comment by riples** [comment]
I am also finding that changing `objectguid` to `ObjectGUID` isn't syncing either.  Even though I have manually specified the `guid_column` in the config file.

**Comment by riples** [comment]
I have upgraded the library to v6 and it has now resolved the ObjectGUID issue that I was having, but I am still experiencing the same issue with the Password field.

**Comment by stevebauman** [comment]
Hi @riples,

There's a configuration option for your `password` field here:

https://github.com/Adldap2/Adldap2-Laravel/blob/89c3de5765f7dade303787bcfd8f2247a71c63c7/src/Config/auth.php#L252

However for your issue you mention here:

> However, when I attempt Auth::attempt( $request->only( ['Username', 'Password'] ) I get back the error Adldap\Auth\PasswordRequiredException: A password must be specified. If I change the request from Password to password, the Auth works perfectly.

You must specify the `password` array key in your `Auth::attempt()` request lower case. This is actually hard-coded in Laravel's default `EloquentUserProvider` as well. Example:

https://github.com/laravel/framework/blob/cd7486a4355be57e8928f89048a25f30883f202f/src/Illuminate/Auth/EloquentUserProvider.php#L134-L146

You would get a similar `Undefined index: password` exception when using the default Laravel auth provider.

If the input field name has the first letter upper cased, just map the array before calling the `Auth::attempt()` method:

```php
$credentials = [
    'username' => $request->Username,
    'password' => $request->Password
];

if (Auth::attempt($credentials)) {
    // ...
}
```

If you still encounter issues with the above, give me a shout and I'll re-open this, thanks!

**Comment by riples** [comment]
Thanks @stevebauman, I have altered my code to reflect your changes, but now I receive the error `RuntimeException: The &#039;Username&#039; key is missing from the given credentials array. in file /home/vagrant/Code/dras/vendor/adldap2/adldap2-laravel/src/Resolvers/UserResolver.php`.

**Comment by riples** [comment]
Okay, I'm really at a loss here...
`Username` and `password` gives me `ErrorException: Undefined property: Illuminate\Auth\Events\Login::$guard in file...`
`username` and `password` gives me `RuntimeException: The &#039;Username&#039; key is missing from the given credentials array. in file...`
`Username` and `Password` gives me `Adldap\Auth\PasswordRequiredException: A password must be specified. in file ...`
`username` and `Password` gives me `RuntimeException: The &#039;Username&#039; key is missing from the given credentials array. in file...`

So I'm assuming I need uppercase `Username` and lowercase `password`.

I'm simply trying to `Auth` the user details:
```
$credentials = [
            'Username' => $request->Username,
            'password' => $request->Password
        ];

        if( Auth::attempt( $credentials ) ) {
```

I have set all my options accordingly:
...
```
'ldap' => [

            'locate_users_by' => 'samaccountname',

            'bind_users_by' => 'distinguishedname',

        ],
```
...
`'username_column' => 'Username',`
...
`'column' => 'Password',`
...

My users table looks like so:
```
Schema::create( 'users', function( Blueprint $table ) {
            $table->increments( 'Id' );
            $table->string( 'ObjectGUID' )->unique()->nullable();
            $table->string( 'Username', 30 )->unique();
            $table->string( 'FirstName', 30 );
            $table->string( 'LastName', 30 )->nullable();
            $table->string( 'Email' )->unique();
            $table->string( 'Phone', 12 )->nullable();
            $table->string( 'Password' );
            ...
```

And even though I receive the error, it still seems to sync my database entry with the correct data, so it is successfully matching up `Username` and `Password` with capitals.  It only seems to be in the `Auth` request and only since I upgraded to v6.

**Comment by riples** [comment]
Just an FYI...

The new changes referenced in v6.0.1 as documented here [https://github.com/Adldap2/Adldap2-Laravel/commit/980665fe5e62969265e08319995747895c196ef2]() has fixed my issue.  

I can now authenticate using `Username` and `password`.
