### ISSUE TITLE
These credentials do not match our records.

### ISSUE THREAD

**Issue by mgrossenbacher86** [Adldap2/Adldap2-Laravel#698]
- Laravel Version: 5.8
- Adldap2-Laravel Version: 6.0
- PHP Version: 7.1
- LDAP Type: ActiveDirectory

### Description:
Hi, i try to reproduce every single step of the documentation(https://adldap2.github.io/Adldap2-Laravel/#/usage) without any tweak, but i think i missed something.
I'm trying to configure it to work with Ms active directory, using the userprincipalName.
My problem is when I try to login with a username and password (email address), I get the following error:

> These credentials do not match our records

The logging is set to true and this log give me the next information:

**[2019-03-24 22:48:06] local.INFO: LDAP (ldap://10.228.17.20:389) - Connection:  - Operation: Adldap\Auth\Events\Binding - Username:   
[2019-03-24 22:48:07] local.INFO: LDAP (ldap://10.228.17.20:389) - Connection:  - Operation: Adldap\Auth\Events\Bound - Username:**   

As you can see, the Username is empty and doesn't look like correct.

I have also searched related issues but none of them seem to pertain to my situation. 

Thanks for your help

ldap_auth.php

`
return [

    'connection' => env('LDAP_CONNECTION', 'default'),

    'provider' => Adldap\Laravel\Auth\DatabaseUserProvider::class,

    'model' => App\User::class,

    'rules' => [

        // Denys deleted users from authenticating.

        Adldap\Laravel\Validation\Rules\DenyTrashed::class,

        // Allows only manually imported users to authenticate.

        // Adldap\Laravel\Validation\Rules\OnlyImported::class,

    ],

  
    'scopes' => [

        // Only allows users with a user principal name to authenticate.
        // Suitable when using ActiveDirectory.
        // Adldap\Laravel\Scopes\UpnScope::class,

        // Only allows users with a uid to authenticate.
        // Suitable when using OpenLDAP.
        // Adldap\Laravel\Scopes\UidScope::class,

    ],

    'identifiers' => [

     

        'ldap' => [

            'locate_users_by' => 'userprincipalname',

            'bind_users_by' => 'distinguishedname',

        ],

        'database' => [

          
            'guid_column' => 'objectguid',

            'username_column' => 'email',

        ],

      

        'windows' => [

            'locate_users_by' => 'samaccountname',

            'server_key' => 'AUTH_USER',

        ],

    ],

    'passwords' => [

        'sync' => env('LDAP_PASSWORD_SYNC', false),

        'column' => 'password',

    ],
    'login_fallback' => env('LDAP_LOGIN_FALLBACK', false),

    'sync_attributes' => [

        'email' => 'userprincipalname',

        'name' => 'cn',

    ],

   
    'logging' => [

        'enabled' => env('LDAP_LOGGING', true),

        'events' => [

            \Adldap\Laravel\Events\Importing::class => \Adldap\Laravel\Listeners\LogImport::class,
            \Adldap\Laravel\Events\Synchronized::class => \Adldap\Laravel\Listeners\LogSynchronized::class,
            \Adldap\Laravel\Events\Synchronizing::class => \Adldap\Laravel\Listeners\LogSynchronizing::class,
            \Adldap\Laravel\Events\Authenticated::class => \Adldap\Laravel\Listeners\LogAuthenticated::class,
            \Adldap\Laravel\Events\Authenticating::class => \Adldap\Laravel\Listeners\LogAuthentication::class,
            \Adldap\Laravel\Events\AuthenticationFailed::class => \Adldap\Laravel\Listeners\LogAuthenticationFailure::class,
            \Adldap\Laravel\Events\AuthenticationRejected::class => \Adldap\Laravel\Listeners\LogAuthenticationRejection::class,
            \Adldap\Laravel\Events\AuthenticationSuccessful::class => \Adldap\Laravel\Listeners\LogAuthenticationSuccess::class,
            \Adldap\Laravel\Events\DiscoveredWithCredentials::class => \Adldap\Laravel\Listeners\LogDiscovery::class,
            \Adldap\Laravel\Events\AuthenticatedWithWindows::class => \Adldap\Laravel\Listeners\LogWindowsAuth::class,
            \Adldap\Laravel\Events\AuthenticatedModelTrashed::class => \Adldap\Laravel\Listeners\LogTrashedModel::class,

        ],
    ],

];
`
ldap.php

`
return [

    'logging' => env('LDAP_LOGGING', true),

   

    'connections' => [

        'default' => [

           

            'auto_connect' => env('LDAP_AUTO_CONNECT', true),

           

            'connection' => Adldap\Connections\Ldap::class,

           
            'settings' => [

                'schema' => Adldap\Schemas\ActiveDirectory::class,

               
                'account_prefix' => env('LDAP_ACCOUNT_PREFIX', ''),

              

                'account_suffix' => env('LDAP_ACCOUNT_SUFFIX', ''),

               

                'hosts' => explode(' ', env('LDAP_HOSTS', '10.228.17.20')),

              

                'port' => env('LDAP_PORT', 389),

             
                'timeout' => env('LDAP_TIMEOUT', 5),

             

                'base_dn' => env('LDAP_BASE_DN', 'OU=--,OU=--,OU=--,DC=--,DC=corp,DC=--,DC=com'),

                'username' => env('user@...com'),
                'password' => env('password'),

               
                'follow_referrals' => false,

                'use_ssl' => env('LDAP_USE_SSL', false),
                'use_tls' => env('LDAP_USE_TLS', false),

            ],

        ],

    ],

];
`
auth.php

`
return [

 

    'defaults' => [
        'guard' => 'web',
        'passwords' => 'users',
    ],

    'guards' => [
        'web' => [
            'driver' => 'session',
            'provider' => 'users',
        ],

        'api' => [
            'driver' => 'token',
            'provider' => 'users',
            'hash' => false,
        ],
    ],

  

    'providers' => [
        'users' => [
            'driver' => 'ldap',
            'model' => App\User::class,
        ],

        // 'users' => [
        //     'driver' => 'database',
        //     'table' => 'users',
        // ],
    ],

  

    'passwords' => [
        'users' => [
            'provider' => 'users',
            'table' => 'password_resets',
            'expire' => 60,
        ],
    ],

];
`
loginController(default)

`
namespace App\Http\Controllers\Auth;

use App\Http\Controllers\Controller;
use Illuminate\Foundation\Auth\AuthenticatesUsers;

class LoginController extends Controller
{
 

    use AuthenticatesUsers;

    /**
     * Where to redirect users after login.
     *
     * @var string
     */
    protected $redirectTo = '/home';

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('guest')->except('logout');
    }

}
`

**Comment by mgrossenbacher86** [comment]
I forgot to mention, I sure about the ldap information 'cause I use it in another application. Thanks!

**Comment by stevebauman** [comment]
Hi @mgrossenbacher86,

Strange, your logs are saying that it successfully bound to your server with an empty username?

```
[2019-03-24 22:48:06] local.INFO: LDAP (ldap://10.228.17.20:389) - Connection: - Operation: Adldap\Auth\Events\Binding - Username:
[2019-03-24 22:48:07] local.INFO: LDAP (ldap://10.228.17.20:389) - Connection: - Operation: Adldap\Auth\Events\Bound - Username: <-- Here
```

Can you try clearing your config cache using `php artisan config:clear` and try again?

Also, your `base_dn` seems pretty lengthy. Is the user you're authenticating with contained in the OU you've given?

```php
 'base_dn' => env('LDAP_BASE_DN', 'OU=--,OU=--,OU=--,DC=--,DC=corp,DC=--,DC=com'),
```

**Comment by mgrossenbacher86** [comment]
Hi Steve, thanks for your help.

I clear the cache and set a small path of the base dn, to set it more general. My user, it is inside of that base (env('LDAP_BASE_DN', 'OU=--,OU=--,OU=--,DC=--,DC=corp,DC=--,DC=com'),).

The log is showing the same error:

[2019-03-25 16:32:56] local.INFO: LDAP (ldap://10.228.17.20:389) - Connection:  - Operation: Adldap\Auth\Events\Binding - Username:   
[2019-03-25 16:32:56] local.INFO: LDAP (ldap://10.228.17.20:389) - Connection:  - Operation: Adldap\Auth\Events\Bound - Username:   

Do you have some suggestions? because I really lose here

Thanks!

**Comment by stevebauman** [comment]
No problem @mgrossenbacher86! This is definitely strange indeed.

Do you see other logs by attempting a login? You should see about 14 log entries in total when logging is enabled:

```
[2019-03-25 12:39:07] local.INFO: LDAP (ldap://192.168.1.1:389) - Connection:  - Operation: Adldap\Auth\Events\Binding - Username: web@corp.acme.org
[2019-03-25 12:39:07] local.INFO: LDAP (ldap://192.168.1.1:389) - Connection:  - Operation: Adldap\Auth\Events\Bound - Username: web@corp.acme.org
[2019-03-25 12:39:07] local.INFO: User 'Bauman, Steve' has been successfully found for authentication.  
[2019-03-25 12:39:08] local.INFO: User 'Bauman, Steve' is being synchronized.  
[2019-03-25 12:39:08] local.INFO: User 'Bauman, Steve' has been successfully synchronized.  
[2019-03-25 12:39:08] local.INFO: User 'Bauman, Steve' is authenticating with username: 'CN=Bauman\, Steve,OU=Users,DC=corp,DC=acme,DC=org'
[2019-03-25 12:39:08] local.INFO: LDAP (ldap://192.168.1.1:389) - Connection:  - Operation: Adldap\Auth\Events\Attempting - Username: CN=Bauman\, Steve,OU=Users,DC=corp,DC=acme,DC=org
[2019-03-25 12:39:08] local.INFO: LDAP (ldap://192.168.1.1:389) - Connection:  - Operation: Adldap\Auth\Events\Binding - Username: CN=Bauman\, Steve,OU=Users,DC=corp,DC=acme,DC=org
[2019-03-25 12:39:08] local.INFO: LDAP (ldap://192.168.1.1:389) - Connection:  - Operation: Adldap\Auth\Events\Bound - Username: CN=Bauman\, Steve,OU=Users,DC=corp,DC=acme,DC=org
[2019-03-25 12:39:08] local.INFO: LDAP (ldap://192.168.1.1:389) - Connection:  - Operation: Adldap\Auth\Events\Passed - Username: CN=Bauman\, Steve,OU=Users,DC=corp,DC=acme,DC=org
[2019-03-25 12:39:08] local.INFO: LDAP (ldap://192.168.1.1:389) - Connection:  - Operation: Adldap\Auth\Events\Binding - Username: web@corp.acme.org
[2019-03-25 12:39:08] local.INFO: LDAP (ldap://192.168.1.1:389) - Connection:  - Operation: Adldap\Auth\Events\Bound - Username: web@corp.acme.org
[2019-03-25 12:39:08] local.INFO: User 'Bauman, Steve' has successfully passed LDAP authentication.  
[2019-03-25 12:39:08] local.INFO: User 'Bauman, Steve' has been successfully logged in. 
```

**Comment by mgrossenbacher86** [comment]
No, actually this is all:

[2019-03-25 16:31:02] local.INFO: LDAP (ldap://10.228.17.20:389) - Connection:  - Operation: Adldap\Auth\Events\Binding - Username:   
[2019-03-25 16:31:02] local.INFO: LDAP (ldap://10.228.17.20:389) - Connection:  - Operation: Adldap\Auth\Events\Bound - Username:   
[2019-03-25 16:32:56] local.INFO: LDAP (ldap://10.228.17.20:389) - Connection:  - Operation: Adldap\Auth\Events\Binding - Username:   
[2019-03-25 16:32:56] local.INFO: LDAP (ldap://10.228.17.20:389) - Connection:  - Operation: Adldap\Auth\Events\Bound - Username:   

Do you know another test to check if in that case something else is showing in the log?

**Comment by stevebauman** [comment]
Looks like you're not actually authenticating with the Adldap2 auth driver (`ldap`).

Have you modified the `LoginController` that Laravel publishes when running `php artisan auth:make` command?

**Comment by mgrossenbacher86** [comment]
This is the loginController from controller->auth

`class LoginController extends Controller
{
    /*
    |--------------------------------------------------------------------------
    | Login Controller
    |--------------------------------------------------------------------------
    |
    | This controller handles authenticating users for the application and
    | redirecting them to your home screen. The controller uses a trait
    | to conveniently provide its functionality to your applications.
    |
    */

    use AuthenticatesUsers;

    /**
     * Where to redirect users after login.
     *
     * @var string
     */
    protected $redirectTo = '/home';

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('guest')->except('logout');
    }

   

}
`

**Comment by stevebauman** [comment]
Hmmm, I would first try changing your `base_dn` to the following:

```
 'base_dn' => env('LDAP_BASE_DN', 'DC=corp,DC=--,DC=com'),
```

Then try logging in again normally and see if you see additional log entries.

**Comment by shoeyn** [comment]
I'm having the same issue on Laravel 5.8 although my username is being populated. It just seems to give up after bound. Username and IP starred out for security reasons.

```
[2019-04-01 16:42:27] local.INFO: LDAP (ldap://******) - Connection:  - Operation: Adldap\Auth\Events\Binding - Username: ******
[2019-04-01 16:42:27] local.INFO: LDAP (ldap://******) - Connection:  - Operation: Adldap\Auth\Events\Bound - Username: ******
```

**Comment by stevebauman** [comment]
Hi @shoeyn, are those all the log events shown? You should see many more events when logging into your app (shown in [this comment](https://github.com/Adldap2/Adldap2-Laravel/issues/698#issuecomment-476289403)).

**Comment by shoeyn** [comment]
Literally just managed to resolve my issue, the difference was I am using username compared to email and had to change:
```
'identifiers' => [
    'ldap' => [
        'locate_users_by' => 'userprincipalname',
```
to 
```
'identifiers' => [
    'ldap' => [
        'locate_users_by' => 'samaccountname',
```
Wondering whether there's a field mixup for @mgrossenbacher86

**Comment by stevebauman** [comment]
Great to hear @shoeyn! Glad you were able to resolve your issue. This is kind of the double-edge sword of being configuration heavy.

Due to inactivity from the OP, I'm closing this one out.
