### ISSUE TITLE
Cannot access adldap property of model.

### ISSUE THREAD

**Issue by brockwddb** [Adldap2/Adldap2-laravel#7]
@stevebauman I've followed all of the documentation but can't seem to get `Auth::user()->adldapUser` to return anything but null. 

I have added the trait to my user model, turned on `bind_user_to_model` and confirmed that authentication is working properly using the standard Auth controller with the `$username` attribute overridden to be `samaccountname`. 

When doing `dd(Auth::user())` I am also getting a null value on `$adldapUser`. Any help would be greatly appreciated.

**Comment by stevebauman** [comment]
When performing `dd(Auth::user())` after doing authentication, what instance do you get?

**Comment by brockwddb** [comment]
```` php
User {#168 ▼
  #table: "users"
  #fillable: array:3 [▶]
  #hidden: array:2 [▶]
  #connection: null
  #primaryKey: "id"
  #perPage: 15
  +incrementing: true
  +timestamps: true
  #attributes: array:7 [▶]
  #original: array:7 [▶]
  #relations: []
  #visible: []
  #appends: []
  #guarded: array:1 [▶]
  #dates: []
  #dateFormat: null
  #casts: []
  #touches: []
  #observables: []
  #with: []
  #morphClass: null
  +exists: true
  +wasRecentlyCreated: false
  +adldapUser: null
}
````

**Comment by stevebauman** [comment]
Can you clear your configuration cache and try again? Use `php artisan cache:clear`

**Comment by brockwddb** [comment]
Still receiving the same results after clearing the cache.

**Comment by stevebauman** [comment]
Strange, looking into it now

**Comment by brockwddb** [comment]
Thank you for your help!

**Comment by stevebauman** [comment]
No problem at all! 

Also, shoot, the `adldapUser` property is only set during the authentication request, which is not set on every other request. Going to look for a solution here.

**Comment by brockwddb** [comment]
Probably will either have to carry the information along in the session or query AD on every page load.

Might be better to ping AD in case of any information updating.

**Comment by stevebauman** [comment]
Yea I might implement the query on AD every page load since Eloquent already does this as well. I can cache the adldap user, but I'm not too sure how well that would continue to work in the long run.

**Comment by brockwddb** [comment]
I'd agree - probably best to query. One specific reason would be when trying to get the user groups. Since groups are something that frequently change in some implementations, it would probably be best for that to automatically update to save the hassle of logging out / back in for the end user.

**Comment by stevebauman** [comment]
Yea absolutely, and since this feature is opt-in through configuration, I'll add notes to the readme indicating that it is slightly more resource intensive due to the extra query per request. Update will be out shortly, thanks for this!

**Comment by brockwddb** [comment]
Appreciate the help. We're going to be implementing this into our local web apps here at work, so I'll be sure to update you with how it goes.

**Comment by stevebauman** [comment]
Closed with commit, but finishing up with tests and a release will be out shortly!

**Comment by stevebauman** [comment]
Ok, `v1.2.0` is out, you'll have to republish your `adldap_auth.php` configuration file due to the addition of another config option. Please let me know if you encounter any other issues, thanks!

**Comment by brockwddb** [comment]
@stevebauman just a note - remember to update docs to reflect installation of 1.2.0. I got hung up a minute when trying to start fresh - forgot the version incremented. Testing now.

**Comment by stevebauman** [comment]
Yup it's there: https://github.com/Adldap2/Adldap2-laravel/blob/master/README.md#installation

**Comment by brockwddb** [comment]
Sorry - must have been my own mistake on that one! I see that now. Must have had a tab opened that wasn't up to date.

**Comment by brockwddb** [comment]
````php
User {#166 ▼
  #table: "users"
  #fillable: array:3 [▶]
  #hidden: array:2 [▶]
  #connection: null
  #primaryKey: "id"
  #perPage: 15
  +incrementing: true
  +timestamps: true
  #attributes: array:7 [▶]
  #original: array:7 [▶]
  #relations: []
  #visible: []
  #appends: []
  #guarded: array:1 [▶]
  #dates: []
  #dateFormat: null
  #casts: []
  #touches: []
  #observables: []
  #with: []
  #morphClass: null
  +exists: true
  +wasRecentlyCreated: false
  +adldapUser: null
}
````
Am I doing something wrong? I'm still receiving a null value for the adldapUser property.

**Comment by stevebauman** [comment]
Did you re-publish your configuration? You might need to delete the `adldap_auth.php` config file and then re-publish.

**Comment by brockwddb** [comment]
I did. I'm creating a new project to test now.

**Comment by brockwddb** [comment]
I can confirm it is still not working on a new install.

**Comment by stevebauman** [comment]
Hmmm I've tested it in various stages of my application locally and it works fine. I'll re-open this for now while I investigate.

**Comment by brockwddb** [comment]
Sounds good. If it helps, I did a fresh install of Laravel, configured the .env file, added a view to do authentication and installed your package and configured it as per the documentation.

**Comment by stevebauman** [comment]
Worked perfectly on fresh install for me. Started a brand new laravel project and configured everything normally. Installed a fresh `adldap2/adldap2-laravel`, created login form, logged in successfully, dumped the user on the welcome page and the `adldapUser` property on the `User` model is set to Adldap user.

There has to be something on your end you may be forgetting. Did you add the `Adldap` facade? Where are you dumping your user?

**Comment by brockwddb** [comment]
I dumped user in the index route. Yes,  I did add the facade and yes,  the property is set to true. I followed the docs to the T.

**Comment by stevebauman** [comment]
Can you dump the user in a controller and see what that returns using `dd(auth()->user())` and let me know what that returns?

**Comment by brockwddb** [comment]
@stevebauman Okay - just tried that. I'm still getting the same results. I'll try one more time with a fresh install and follow the docs again.

**Comment by brockwddb** [comment]
@stevebauman I am getting the same results with a fresh install. Following the documentation completely. I'm on Laravel version 5.1.17.

Are you sure you're not leaving anything out of the documentation?

**Comment by stevebauman** [comment]
I don't believe I am, I'm going to do a completely fresh install and display all of my steps, give me one moment.

**Comment by brockwddb** [comment]
Sounds good. I'm going to see if I can do any debugging in the classes too.

**Comment by brockwddb** [comment]
One quick note - I tried doing a dd of the $model in the bindAdldapToModel method. It doesn't seem that method is ever called.

````php
    protected function bindAdldapToModel(User $user, Authenticatable $model)
    {
        $model->adldapUser = $user;

        dd($model);

        return $model;
    }
````

**Comment by stevebauman** [comment]
- Created new laravel project using `laravel new adldap-test`
 - Created database in phpmyadmin for laravel migrations
 - Renamed `.env.example` to `.env`
 - Ran `php artisan key:generate
 - Entered DB credentials into `.env` file
 - Ran `php artisan migrate`
 - Added `"adldap2/adldap2-laravel": "1.2.*"` to my `composer.json` file
 - Ran `composer update`
 - Inserted providers into `config/app.php`
```php
    \Adldap\Laravel\AdldapServiceProvider::class,
    \Adldap\Laravel\AdldapAuthServiceProvider::class,
```
 - Inserted Facade into `config/app.php` `'Adldap'    => \Adldap\Laravel\Facades\Adldap::class,`
 - Ran `php artisan vendor:publish`
 - Changed `bind_user_to_model` to `true` in `config/adldap_auth.php`
 - Changed `adldap.php` configuration for my AD server
 - Copied routes from http://laravel.com/docs/5.1/authentication, and placed them below the default welcome route
 - Created dir `resources/views/auth/login.blade.php` and pasted login form from http://laravel.com/docs/5.1/authentication
 - Inserted `AdldapUserModelTrait` onto the default `app/User.php` model
 - Switched auth driver in `config/auth.php` to `adldap`
 - Visited `auth/login`, logged in with LDAP credentials, it redirected me to `home` but that doesn't exist so I just visited the `/` (the welcome page)
 - Pasted `{{ dd(auth()->user()->adldapUser) }}` and ran the welcome page again, and it dumps the Adldap User

**Comment by stevebauman** [comment]
It looks like it may be having issues discovering your user after login?

**Comment by stevebauman** [comment]
Are you by chance checking the remember me token? I didn't override the `retrieveByToken` method. This may be the issue here

**Comment by brockwddb** [comment]
Further debugging

````php
if ($user instanceof User && $this->getBindUserToModel()) {
                $model = $this->bindAdldapToModel($user, $model);
            }
            else{
                dd('test');
            }
````
Always returning "test".

**Comment by stevebauman** [comment]
Try

```php
dd($this->getBindUserToModel()); // Add this

if ($user instanceof User && $this->getBindUserToModel()) {
    $model = $this->bindAdldapToModel($user, $model);
}
else{
    dd('test');
}
```

**Comment by brockwddb** [comment]
````
dd($this->getBindUserToModel()); // Add this --- returns true
dd($user instanceof User); // Returns False
````

It looks like the check to see if the model is a User model is failing for some reason.

For what it's worth, it is working for the login, just not subsequently after being logged in.

**Comment by stevebauman** [comment]
Okay so it's failing to find the user after logging in. Hmmm...

**Comment by brockwddb** [comment]
Yep - that's what it looks like.

`dd($user); // returns false`

**Comment by stevebauman** [comment]
Can you try:

```php
dd($this->getUsernameAttribute());
```

And see what that returns?

**Comment by brockwddb** [comment]
````
array:1 [▼
  "username" => "samaccountname"
]
````

**Comment by stevebauman** [comment]
What are you logging in with? The LDAP users email or their username?

**Comment by brockwddb** [comment]
Username - hold on... might see what the problem is here.

**Comment by brockwddb** [comment]
Okay, I thought I had it figured out.

* Didn't realize I needed to add username field to migrations - did that and updated them.
* Added `'samaccountname' => 'samaccountname',` to sync_attributes property.

Did not fix the issue. I assume I'm pretty close. What am I missing.

**Comment by stevebauman** [comment]
If you're using a username, keep `'username' => 'samaccountname'`

**Comment by brockwddb** [comment]
It's now working. To fix my issue:
* I made the above change for `'username' => 'samaccountname'`.
* I changed my migration's field from `samaccountname` to `username`.
* I made the User's `username` field fillable.
Thank you very much for your help with this. I really do appreciate it, and sorry for the errors on my part.

**Comment by stevebauman** [comment]
Awesome! Really glad you've solved the issue. No problem at all! I'll include some more documentation for this.
