### ISSUE TITLE
My app randomly quits

### ISSUE THREAD

**Issue by subdesign** [Adldap2/Adldap2-Laravel#70]
Hey,
I've set up successfully the adldap authentication combined with Laravel Auth system. I can log in , log out users, get users data well, etc. But, my app randomly quits to login screen, an I can't find any logic how and why does it.  
For pseudo example, I press edit article link, I add some modification, save it. But next time when I press the edit link, app quits to login screen.  Nothing changed meantime..
No error in the logs, I use Laravel 5.1.x latest. 
One thing, it happens only on my production server, on local no such happens. Code base is 100% the same.  
Any idea?  
Thanks

**Comment by stevebauman** [comment]
This sounds like a Laravel session issue. Adldap2-Laravel uses the exact same authentication as Laravel's default `Eloquent` auth driver.

What driver are you using for sessions?

**Comment by subdesign** [comment]
I use "file" driver for sessions.

**Comment by stevebauman** [comment]
Use the `database` driver. I've actually created an issue about this.

https://github.com/laravel/framework/issues/8244

**Comment by subdesign** [comment]
Thanks Steve, I'll try and come back with the result. Btw, this package is nice job!

**Comment by subdesign** [comment]
Now, I click here and there in my admin, and was only one quit: I just pressed F5 in my admin on current page, (list of articles based on Datatables), app quitted to login screen, and a second row appeared in my sessions table! Strange.. I know it's not usable info, just said.

**Comment by subdesign** [comment]
Ok figured out! The admin and the frontend is a different laravel app [...], routes mixed with nginx.  
So when a visitor reached the frontend, my admin session was invalidated. So I renamed the admin's Laravel session cookie variable and now no collision happens.  
Thanks again

**Comment by stevebauman** [comment]
Awesome! Glad to hear you've sorted it out. Thanks for updating on the issue.
