### ISSUE TITLE
[Question] LDAP Test Server

### ISSUE THREAD

**Issue by travisobregon** [Adldap2/Adldap2-Laravel#704]
- Laravel Version: 5.8
- Adldap2-Laravel Version: 6.0.2
- PHP Version: 7.1
- LDAP Type: ActiveDirectory

### Description:
Is there a test LDAP server that you recommend? I saw you referenced one [here](https://github.com/Adldap2/Adldap2-Laravel/issues/612#issuecomment-439935439), but the link is not working anymore. Do you have any other suggestions for Linux?

Thanks.

**Comment by stevebauman** [comment]
Hi @travisobregon,

Here's another step-by-step guide with the same information for setting up ActiveDirectory Lighweight Directory Services:

http://www.rebeladmin.com/2018/02/step-step-guide-setup-active-directory-lightweight-directory-services-ad-lds/

Though for Linux I'm not sure, unfortunately I don't use Linux very often. I would suggest just installing OpenLDAP locally - as it seems pretty straight forward. I've installed OpenLDAP on my Windows machine and it was pretty seamless. This seems like its the easiest option for Linux.

The current online LDAP test server run by forumsys.com won't get you very far with testing, as it's extremely bare-bones and doesn't return user UUIDs.

Let me know if you'd like to discuss further or need any other information.
