### ISSUE TITLE
Login page after success authentication crash ( Illegal offset type )

### ISSUE THREAD

**Issue by netruner** [Adldap2/Adldap2-Laravel#705]
- Laravel Version: 5.2
- Adldap2-Laravel Version: 5.1
- PHP Version: 7.2.15
- LDAP Type:  ActiveDirectory

### Description:

Login page after authentication crash on helpers.php line 360: Illegal offset type not redirect to page set in AuthController.php

    protected $redirectTo = '/dashboard';

> [2019-04-02 22:38:43] local.INFO: User 'firstname.lastname' has been successfully found for authentication.
> [2019-04-02 22:38:43] local.INFO: User 'firstname.lastname' is being synchronized.
> [2019-04-02 22:38:43] local.INFO: User 'firstname.lastname' has been successfully synchronized.
> [2019-04-02 22:38:43] local.INFO: User 'firstname.lastname' is authenticating with username: 'CN= firstname.lastname,OU=IT,OU=ZD,OU=DYR,OU=USD,DC=ad,DC=compa,DC=pl'
> [2019-04-02 22:38:43] local.INFO: User 'firstname.lastname' has successfully passed LDAP authentication.
> [2019-04-02 22:38:43] local.INFO: User 'firstname.lastname' has been successfully logged in.
> [2019-04-02 22:38:43] local.ERROR: ErrorException: Illegal offset type in /Users/netruner/developer/www/sflux/vendor/laravel/framework/src/Illuminate/Support/helpers.php:360

> Whoops, looks like something went wrong.
> 1/1 ErrorException in helpers.php line 360: Illegal offset type
> 
>     in helpers.php line 360
>     at HandleExceptions->handleError('2', 'Illegal offset type', '/Users/netruner/developer/www/sflux/vendor/laravel/framework/src/Illuminate/Support/helpers.php', '360', array('class' => object(User), 'results' => array())) in helpers.php line 360
>     at class_uses_recursive(object(User)) in BindsLdapUserModel.php line 55
>     at BindsLdapUserModel->canBind(object(User)) in BindsLdapUserModel.php line 27
>     at BindsLdapUserModel->handle(object(Login))
>     at call_user_func_array(array(object(BindsLdapUserModel), 'handle'), array(object(Login))) in Dispatcher.php line 347
>     at Dispatcher->Illuminate\Events\{closure}(object(Login))
>     at call_user_func_array(object(Closure), array(object(Login))) in Dispatcher.php line 221
>     at Dispatcher->fire('Illuminate\Auth\Events\Login') in SessionGuard.php line 470
>     at SessionGuard->fireLoginEvent(object(User), false) in SessionGuard.php line 455
>     at SessionGuard->login(object(User), false) in SessionGuard.php line 360
>     at SessionGuard->attempt(array('name' => 'firstname.lastname', 'password' => 'xxxxxxxxx'), false) in AuthenticatesUsers.php line 74
>     at AuthController->login(object(Request))

### Steps To Reproduce:

**Comment by stevebauman** [comment]
Thanks @netruner! This is a bug on the v5.0 branch due to the Laravel helper `class_uses_recursive` not accepting objects and only the classes name.

This is my mistake, as the compatibility was added in Laravel [5.3](https://github.com/laravel/framework/blob/2906b572aa83ff46b8ad57093dd0e859c0ff783f/src/Illuminate/Support/helpers.php#L340-L344), but not in [5.2](https://github.com/laravel/framework/blob/69a980e9d62ef17b4a0be46e73e0a26018100fc9/src/Illuminate/Support/helpers.php#L356-L366).

I'll create a patch on the v5.0 branch now for model binding.

**Comment by stevebauman** [comment]
Released [v5.1.3](https://github.com/Adldap2/Adldap2-Laravel/releases/tag/v5.1.3).
