### ISSUE TITLE
Artisan Import Nested Groups

### ISSUE THREAD

**Issue by kellerisddev** [Adldap2/Adldap2-Laravel#709]
- Laravel Version: 5.8.8
- Adldap2-Laravel Version: 6.0
- PHP Version: 7.2.12
- LDAP Type: ActiveDirectory

### Description:
I am uncertain how to get the command line import to work where it can search within nested or recursive groups for the desired security group

### Steps To Reproduce:

  My Base DN is set to the `OU=Main,DC=Example,DC=Com` in config/ldap.php and everything exists below that.

I have tried to use the following (where xxxxx is the Security Group name that is 4 groups removed from the Main OU) without success (No users found)

```
php artisan adlap:import --filter "(cn=xxxxx,OU=Main,DC=Example,DC=Com)"
php artisan adlap:import --filter "(cn=xxxxx,DC=Example,DC=Com)"
```

IS there a flag to make it look in child groups?

Thanks

**Comment by stevebauman** [comment]
Hi @kellerisddev,

> IS there a flag to make it look in child groups?

Yup! You need to specify a special filter syntax to indicate that you would like all child groups and their members returned.

Here you go:

```bash
php artisan adldap:import --filter "(memberof:1.2.840.113556.1.4.1941:=cn=xxxxx,OU=Main,DC=Example,DC=Com)"
```

This is shown here in the docs as a quick example (calling from the Laravel scheduler:

https://adldap2.github.io/Adldap2-Laravel/#/auth/importing?id=no-interaction

```php
// Importing users with a filter.
$dn = 'CN=Accounting,OU=SecurityGroups,DC=Acme,DC=Org';

$filter = sprintf('(memberof:1.2.840.113556.1.4.1941:=%s)', $dn);

$schedule->command('adldap:import', ['--no-interaction', '--filter' => $filter])
    ->everyMinute();
```

Let me know if you run into any issues :smile:

**Comment by kellerisddev** [comment]
Thanks Steve,

I found that and tried it and it was still not returning any users.  I was unable to find anything in the log files as to why it was failing to find any.

The LDAP Auth is working fine and I am able to import users by group if I list the CN/OU/DC structure explicitly in the filter.

**Comment by stevebauman** [comment]
Do you have any custom scopes applied in your ldap_auth.php file?

**Comment by kellerisddev** [comment]
No sir.  I haven't defined any custom scopes in ldap_auth.php
