### ISSUE TITLE
adldap:import not working with Artisan::call()

### ISSUE THREAD

**Issue by hurik** [Adldap2/Adldap2-Laravel#711]
- Laravel Version: 5.8.10
- Adldap2-Laravel Version: 6.0.2
- PHP Version: 7.2.3
- LDAP Type: OpenLDAP

### Description:
Hello Steve,

after the upgrade from Adldap2-Laravel v5.1.3 to v6.0.2 this is not working anymore: `Artisan::call('adldap:import', ['user' => $username, '--no-interaction']);`

I always getting a `The command "adldap:import" does not exist.` error.

But it working normally when I using the command line.

Thanks for your help.

**Comment by stevebauman** [comment]
Hi @hurik,

Where are you calling the command? I'm not able to reproduce this.

**Comment by hurik** [comment]
I'm calling it at different places and tested others. But it always not working.

Made an new clean project and only installed Adldap2-Laravel, but still got the same problem.

It's only working when I manually add this in the `app\Console\Kernel.php` file:
```
    protected $commands = [
        \Adldap\Laravel\Commands\Console\Import::class,
    ];
```

**Comment by stevebauman** [comment]
Do you have package auto-discovery disabled? The `AdldapAuthServiceProvider` registers this command:

https://github.com/Adldap2/Adldap2-Laravel/blob/master/src/AdldapAuthServiceProvider.php#L41

**Comment by hurik** [comment]
Nope, I didn't deactivated auto-discovery. And it is working fine with v5.1.3. Very strange.

My way around was this post from you here: https://github.com/Adldap2/Adldap2-Laravel/issues/644#issuecomment-450202479 

    $ldapUser = Adldap::search()->users()->findBy('uid', $username);
    $credentials = ['username' => $ldapUser->getObjectGuid()]; // getObjectGuid is uid in my case
    $importer = new Import($ldapUser, new User(), $credentials);
    $model = $importer->handle();
    $model->password = Hash::make(Str::random());
    $model->save();

I closed this issue, because when I'm the only one with the problem it should have something to do with my configuration. To lazy (and to much work) to upgrade my XAMPP at the moment, for a newer PHP version.

Thanks for your help.

**Comment by stevebauman** [comment]
Hi @hurik,

I lied to you - it appears calling artisan via the `Artisan` returns false on the `App::runningInConsole()` method here:

https://github.com/Adldap2/Adldap2-Laravel/blob/5b159130cd747d81e67a2263984cec288c40af0a/src/AdldapAuthServiceProvider.php#L33

I tried calling the command via the `Artisan` facade in a regular application request and I was able to reproduce this.

I've placed the import command outside of this so your use-case will work and you can call the import outside of console scheduler.

Thanks for the report! A new release will be out shortly :smile:

Sorry for the misunderstanding.

**Comment by hurik** [comment]
Thank you, its working again with v6.0.4!

**Comment by stevebauman** [comment]
Awesome great to hear @hurik! Thanks again :smile:
