### ISSUE TITLE
Multiple Connections at run-time

### ISSUE THREAD

**Issue by SagePacheco** [Adldap2/Adldap2-Laravel#712]
- Laravel Version: 5.8.10
- Adldap2-Laravel Version: 6.0.2
- PHP Version: 7.3.3
- LDAP Type: ActiveDirectory

### Description:
Hey There! I'm having an issue that I can't seem to narrow down and would really appreciate some assistance!

I am building a multi-connection AD Login and for some reason I can't get the active connection to swap at run-time as is suggested in issue #230.

Despite successfully changing the ldap_auth connection in the config during run-time, the authentication provider will always stick with the first connection on each authentication attempt. In fact, if the first connection attempt has a valid connection name, all other names on subsequent tries can be completely made-up. Which tells me that the connection is persisted somewhere and not actually read from the config on each authentication attempt.

For example, if credentials for the second domain in the list are used, all three attempts will return as false. As only the first domain connection read from the config is used.

### Steps To Reproduce:

Multiple AD connections added to ldap.php file.
```php
	'connections' => [

		'sheriff' => [

			'auto_connect' => true,
			'connection' => Adldap\Connections\Ldap::class,
			'settings' => [
				'schema' => Adldap\Schemas\ActiveDirectory::class,
				'account_prefix' => '',
				'account_suffix' => '',
				'hosts' => ['omitted'],
				'port' => 389,
				'timeout' => 5,
				'base_dn' => 'omitted',
				'username' => env('SHERIFF_ADMIN_USERNAME'),
				'password' => env('SHERIFF_ADMIN_PASSWORD'),
				'follow_referrals' => false,
				'use_ssl' => env('LDAP_USE_SSL', false),
				'use_tls' => env('LDAP_USE_TLS', false),
			],

		],

		'county' => [

			'auto_connect' => true,
			'connection' => Adldap\Connections\Ldap::class,
			'settings' => [
				'schema' => Adldap\Schemas\ActiveDirectory::class,
				'account_prefix' => '',
				'account_suffix' => '',
				'hosts' => ['omitted'],
				'port' => 389,
				'timeout' => 5,
				'base_dn' => 'omitted',
				'username' => env('COUNTY_ADMIN_USERNAME'),
				'password' => env('COUNTY_ADMIN_PASSWORD'),
				'follow_referrals' => false,
				'use_ssl' => env('LDAP_USE_SSL', false),
				'use_tls' => env('LDAP_USE_TLS', false),
			],

		],

		'cdc' => [

			'auto_connect' => true,
			'connection' => Adldap\Connections\Ldap::class,
			'settings' => [
				'schema' => Adldap\Schemas\ActiveDirectory::class,
				'account_prefix' => '',
				'account_suffix' => '',
				'hosts' => ['omitted'],
				'port' => 389,
				'timeout' => 5,
				'base_dn' => 'omitted',
				'username' => env('CDC_ADMIN_USERNAME'),
				'password' => env('CDC_ADMIN_PASSWORD'),
				'follow_referrals' => false,
				'use_ssl' => env('LDAP_USE_SSL', false),
				'use_tls' => env('LDAP_USE_TLS', false),
			],

		],

	],
```

Login Controller override function:
```php
protected function attemptLogin(Request $request){
     $connections = config('ldap.connections');
     foreach($connections as $connection => $config){
          Config::set('ldap_auth.connection', $connection);
          if($this->guard()->attempt( $this->credentials($request), $request->filled('remember'))){
               return true;
          }
     }
     return false;
}
```

**Comment by stevebauman** [comment]
Hi @SagePacheco,

You won't be able to do this (at least right now - as it's unsupported):

```php
$connections = config('ldap.connections');

foreach($connections as $connection => $config) {
    Config::set('ldap_auth.connection', $connection);

    if($this->guard()->attempt( $this->credentials($request), $request->filled('remember'))){
        return true;
    }
}
```

You will need to have the user select a domain (via a `<select>` on your login form) to authenticate against, and then set the connection prior to authentication.

You won't be able to loop over your connections and `auth()->attempt()` against them.

**Comment by SagePacheco** [comment]
Hey @stevebauman!

Thanks for quick response!
That is actually the exact solution I came up with for another application, but I figured there had to be a better (more invisible) way for my users. Is this an issue of how the Adldap2-Laravel package works? or how Laravel handles providers in general?

**Comment by stevebauman** [comment]
No problem @SagePacheco! :smile:

To elaborate, this is likely due to `UserResolver` in the `__construct()` method as it sets the connection when its created:

https://github.com/Adldap2/Adldap2-Laravel/blob/master/src/Resolvers/UserResolver.php#L43

I think we just need to move this call somewhere else and your use case will work.

Let me update it now and we can give it a shot to see if it works? I would definitely like to support this!

**Comment by SagePacheco** [comment]
Sounds great! Let's do it!

**Comment by stevebauman** [comment]
Okay great! Can you try `dev-master`? It should work fine now since we're retrieving the LDAP provider on every request now.

**Comment by SagePacheco** [comment]
Absolutely! Just give a me a bit and I'll report back.

**Comment by SagePacheco** [comment]
IT WORKS! You're the man, @stevebauman! I've been banging my head against my desk trying to figure this out.

I've tested all three domains in all orders and it does as advertised!

**Comment by stevebauman** [comment]
Awesome @SagePacheco, glad you're up and running! Thanks so much for your kind words :smile:

**Comment by stevebauman** [comment]
Oh also, I'll be creating a new release shortly so you can remove the use of `dev-master` in your `composer` file.

**Comment by SagePacheco** [comment]
Fantastic! Thanks again, you really made my day!

**Comment by kkpriscila** [comment]
@stevebauman, Have you created a new version to remove the use of dev-master in this solution?

**Comment by grantholle** [comment]
@kkpriscila It's in the most recent non `dev-master`, but I'm not sure what version it was first introduced.

@stevebauman Would it be too presumptious to attempt the next connection if one authentication attempt fails? Or maybe adding a configuration option to automatically use another connection if the attempt fails? Just throwing out ideas...
