### ISSUE TITLE
Let us decide if we want automatic DB user creation

### ISSUE THREAD

**Issue by istratos** [Adldap2/Adldap2-Laravel#716]
- Laravel Version: 5.7.28
- Adldap2-Laravel Version: Latest
- PHP Version: 7.2.14
- LDAP Type: ActiveDirectory

### Description:
We have ActiveDirectory auth and the package does its job just fine and we're syncing those records with our App's database. So we're using the DatabaseUserProvider.

We would love to keep performing the AD sync with our DB (cause we use fallback, and to udpate user info/password) but what we would love to do is: **do not let an AD user to log in our app if their user isn't in our DB already.**

What is happening is that, if the user is found in the AD but not on our DB, it creates a new record in our DB automatically. We don't want that, since we're managing these users from another internal app.

Currently I can't find a way to perform this so I found myself patching the source files (I know it should not be done)

In:
`vendor/adldap2/adldap2-laravel/src/Auth/DatabaseUserProvider.php`

Changed line 124 for this one:
```
if ($this->user instanceof User && !is_null($model->id)) {
```

So now it checks if there's already a user (model) in our DB before logging them in, so that the unwanted creation doesn't happen at all.

Of course, we would love to have this feature in the package as a configurable option instead.

Thank you, hope I was clear (english is not my main language)

**Comment by stevebauman** [comment]
Hi @istratos,

This is actually already a configurable feature via the [rule](https://adldap2.github.io/Adldap2-Laravel/#/auth/setup?id=rules) configuration option :smile:

Simply un-comment this rule here:

https://github.com/Adldap2/Adldap2-Laravel/blob/83cd5f392efde04381ba788cd3cf4f81160aebf4/src/Config/auth.php#L72-L74

This rule will prevent users from logging in that do not exist in your local database yet.

**Comment by istratos** [comment]
Thank you very much! I must have missed that in the docs (I'm pretty sure I read the rules section, it just didnt equate rule == disabling this in my mind)

Sorry for the inconvenience.

**Comment by stevebauman** [comment]
No problem @istratos! I'm always glad to help in any way. No incovienience at all.

If you ever need any more help, just give me a shout :smile:
