### ISSUE TITLE
Import users from OpenLDAP - Unable to locate user

### ISSUE THREAD

**Issue by bellu** [Adldap2/Adldap2-Laravel#719]
- Laravel Version: 5.8.4
- Adldap2-Laravel Version: 6.0.5
- PHP Version: 7.2.2
- LDAP Type: OpenLDAP

### Description:
I'm trying to import users from OpenLDAP using the command `php artisan adldap:import`.
I can find the users on the OpenLDAP server, but nothing has been imported or syncronized.
![Schermata 2019-04-25 alle 14 56 39](https://user-images.githubusercontent.com/10274092/56737277-5b737b80-676a-11e9-85ff-d569eec39e51.png)

In the log i found this error:
`local.ERROR: Unable to import user Gabriele Bellucci. Unable to locate a user without a Email`

In the ldap_auth.php i have this configuration for the ldap identifiers:
`'ldap' => [
            'locate_users_by' => 'Email',
            'bind_users_by' => 'distinguishedname',
        ]`
 
I have an email field for the use in the OpenLDAP server, so i can't understand what i'am doing wrong.
![Schermata 2019-04-25 alle 15 04 23](https://user-images.githubusercontent.com/10274092/56737850-a477ff80-676b-11e9-9a83-6913e61ce6f6.png)

Can someone help me?
Thanks

**Comment by stevebauman** [comment]
Hi @bellu,

I the `Email` attribute you're showing is actually named something else behind the scenes. Usually it is `mail` (lowercase).

I would try dumping your users attributes and seeing what you find. Try this:

```php
use Adldap\Laravel\Facades\Adldap;

$user = Adldap::search()->find('gabriele.bullucci@test.com');

dd($user->getAttributes());
```

**Comment by bellu** [comment]
Hi @stevebauman, thanks for the quick reply.
The name of the attribute is `mail` and not `Email`, thanks. Now the import is working fine!

**Comment by stevebauman** [comment]
Awesome, no problem @bellu! Glad you were able to resolve it :smile:
