### ISSUE TITLE
Session does not get saved with database session driver

### ISSUE THREAD

**Issue by Coding-Kiwi** [Adldap2/Adldap2-Laravel#720]
- Laravel Version: 5.8
- Adldap2-Laravel Version: 6.0.5
- PHP Version: 7.3
- LDAP Type: ActiveDirectory
### Description:

Hi,
I have a working authentication,
the only problem is that I can't use the laravel database session driver (file works), because if I do so, the session (namely the user_id of the session) does not get saved after a successful login and I get redirected to the login page.

I "fixed" this by putting

```php
protected function authenticated(Request $request, $user){
    \Session::save();
}
```

in my `app/Http/Controllers/Auth/LoginController.php`

but this doesn't fix that users do not get an error when typing in a wrong password/username

**Comment by stevebauman** [comment]
Hi @Coding-Kiwi,

Are you using the `NoDatabaseUserProvider` by chance? See below from the documentation if so:

https://adldap2.github.io/Adldap2-Laravel/#/auth/setup?id=important-note-about-session-drivers

> When using the database session driver with the NoDatabaseUserProvider, you must change the user_id data type in the generated Laravel sessions migration (database/migrations/2018_05_03_182019_create_sessions_table.php) to varchar. This is because the identifier for LDAP records is a GUID - which contains letters and dashes (incompatible with the integer type of databases).

If not, just let me know and we can continue troubleshooting.

**Comment by Coding-Kiwi** [comment]
No I am using the `DatabaseUserProvider`. I already read that part of the docs but that sadly doesn't apply for me. Thanks in advance for your help

**Comment by stevebauman** [comment]
No problem at all @Coding-Kiwi! Thanks for the quick reply.

That's definitely strange it works with file driver but not with the database driver.

Does any session record get created at all in your database after attempting a successful login?

Also, can you post your `config/session.php` file as well as your `config/auth.php` file?

**Comment by Coding-Kiwi** [comment]
Ok so I tested some more, it is a bit weird because the login sometimes works but sometimes not

Here is what happend in one of my tests:
1) open login page
 -> session in database gets generated with no user_id
2) enter username and password
-> successful login, session in database gets saved with the user_id
3) logout
-> redirect to login page, session in database gets saved with the user_id NULL
2) enter username and password again
-> successful login according to ldap logs
but session in database still has the user_id NULL, so I get redirected to the login page

Here are the files:
`config/session.php`, `config/auth.php`, a log file and the neccessary entries in the `.env`:

[files.zip](https://github.com/Adldap2/Adldap2-Laravel/files/3130169/files.zip)

**Comment by Coding-Kiwi** [comment]
I changed the auth provider back to eloquent and even normal authentication not using your ldap package seems to be broken, you can close this issue if you want.
Sorry to bother you ^^

**Comment by Coding-Kiwi** [comment]
Ok so I set up laravel fresh and installed your package again using the docs and now everything is working perfectly, it had nothing to do with your package .__.
I'm sorry, but thank you so much for the quick answers and help
Keep up the good work

**Comment by stevebauman** [comment]
No problem at all @Coding-Kiwi! Thanks for much for your kind words :smille: I'm glad you were able to resolve it!

I appreciate the quick responses.
