### ISSUE TITLE
trying to return all users fails class 'Adldap/Connections/Provider' does not have a method 'users'

### ISSUE THREAD

**Issue by jeremiahsherrill** [Adldap2/Adldap2-Laravel#724]
- Laravel Version: 5.8
- Adldap2-Laravel Version: 10.0.8
- PHP Version: 7.2
- LDAP Type:  ActiveDirectory 

### Description:

Trying to retrieve a  list of all users fails
```
$users = Adldap::users()->search()->select(['cn','displayname'])->get();
```
`PHP Warning:  call_user_func_array() expects parameter 1 to be a valid callback, class 'Adldap/Connections/Provider' does not have a method 'users' in /home/jeremiah/acms_may/vendor/adldap2/adldap2/src/Adldap.php on line 152`

**Comment by stevebauman** [comment]
Hey @jeremiahsherrill,

You need to call `search()->users()` first not `users()->search()`.

That will resolve your issue.

**Comment by jeremiahsherrill** [comment]
Thanks
