### ISSUE TITLE
Mutiple domain config?

### ISSUE THREAD

**Issue by northify** [Adldap2/Adldap2-Laravel#725]
- Laravel Version: 5.7
- Adldap2-Laravel Version: 6.0
- PHP Version: 7.2.11
- LDAP Type: ActiveDirectory

### Description:
Hi, 
I'm trying to pull user data from 2 domains. I can auth, update users, create new users, all that stuff just fine. But that is only from one domain.  

Is it possible to do these things from two domains? For example I auth using abc.local and can view, update, created whatever in abc.local. But if I want to view, update, created or whatever in 123.local I can't even though my LDAP_USERNAME/LDAP_PASSWORD user has access to do these things in both domains .  

I have set both domains in 'hosts' => explode(' ', env('LDAP_HOSTS', 'ABC.local 123.local')),

### Steps To Reproduce:
So what I'm doing is importing users from each domain separately (because I can't figure out a way to do it from both at the same time).  

I manually change my config to import from ABC.local, then manually change my config to 123.local to import those users.  

Then I login with a user that is in 123.local. I can perform all tasks on users in the 123.local domain.  

Now if I try to perform the same tasks on user in the ABC.local domain I get errors.
An error example would be if I was trying to get the users memberof attributes   

$adldap = $adUser->getAttribute('memberof');  

This would give me an "Call to a member function getAttribute() on null" error because this user is not found in the ABC.local domain. If I have both domains set in my hosts why can't I perform tasks on users from both?

**Comment by stevebauman** [comment]
Hey @northify!

The `hosts` option is for specifying different domain controllers **on the same domain** - not for hosts on seperate domains. This allows a fallback to other domain controllers if one of your controllers goes offline.

For adding another domain, you have to add another connection in your `config/ldap.php` file.

Right now the Adldap2-Laravel auth driver only supports connecting to *one* domain - because several features built into the auth driver can't handle multiple domains (such as the model binding feature).

For multiple domain authentication to function with all features, the users domain would need to be saved in your `users` database table in its own column so it knows which user is located on which domain. Right now this isn't an option - but I'm working on it.

You will definitely have to create a custom scheduled job to import users from **two separate domains** - as this isn't a built in feature.

**Comment by northify** [comment]
Hi,
Thanks for the quick response. Ok I see now how the hosts setting works. Thanks for the explanation.

Hmm OK I think I get what you are saving about adding a another domain saving the users domain in the db. I think this is a great clue at least and will set me in the right direction. Thanks! Great to hear you are working on it... would be a great new feature :)

Has this been brought up in any other post... saving users domain in the db? Maybe I can refer to? Was not able to find anything.

**Comment by stevebauman** [comment]
No problem @northify!

> Has this been brought up in any other post... saving users domain in the db? Maybe I can refer to? Was not able to find anything.

No it hasn't. There has been many other issues reported about supporting multiple domain authentication, but nothing mentioning this requirement specifically.

I know how I could implement it when using the `DatabaseUserProvider` - but I'm still working out how I can support multi-domain auth when using the `NoDatabaseUserProvider. I would likely need to save the domain the user was authenticating with inside their session or something similar. I'd like to support it using both providers so there wouldn't need to be seperate documentation for each or any "gotchas".

I'd be glad to accept any PRs though if you're interested 😄

**Comment by northify** [comment]
Makes allot of since to support both options. Thanks again for the info and you are doing great work.. love this package.

No PRs for me thanks... way over my head. I'll try to hack it together in my app :)

**Comment by stevebauman** [comment]
No problem @northify! Thanks so much for your kind words :smile:, I'm really glad you like using Adldap2!

I'll leave this open so I can update this issue when there are any developments.

**Comment by northify** [comment]
Hi,
I came back to this recently and not sure why I'm getting NULL when using getAdLdapUser() function.

So what I did was set in the the users LDAP_HOSTS and LDAP_HOSTS_DN in the constructor. 
~~~
putenv("LDAP_HOSTS=".$user->ldap_base);
putenv("LDAP_BASE_DN=".$user->ldap_base_dn);
~~~
This is my show function 
~~~
$user = User::find($id);
$adUser = $user->getAdLdapUser();
~~~
If I `dd(env('LDAP_HOSTS'))` I will get the correct host for the user but if I `dd('adUser')` I will get NULL because it is still using this LDAP_HOSTS that is set in my .env file. NOt sure why is is not using the new LDAP_HOSTS set in the constructor.

**Comment by northify** [comment]
I tried to make this a bit easier by adding another Ldap Connection. So in my in my constructor I have `putenv("LDAP_CONNECTION=".$user->connection');`. 

But this seems to connect to default no matter what the user has set as `$user->connection`

**Comment by stevebauman** [comment]
Hi @northify,

What does the `$user->getAdLdapUser();` method do?

**Comment by northify** [comment]
It just returns the ldap user matching the same username.

`return Adldap::search()->users()->where('samaccountname', '=', $this->username)->first();`

**Comment by stevebauman** [comment]
Starting from Laravel 5.7 and up, variables set in your `.env` are immutable, so you can't override them at run-time.

**From the Laravel 5.7 upgrade guide docs**:

> Read-Only env Helper
> Likelihood Of Impact: Low
> 
> Previously, the env helper could retrieve values from environment variables which were changed at runtime. In Laravel 5.8, the env helper treats environment variables as immutable. If you would like to change an environment variable at runtime, consider using a configuration value that can be retrieved using the config helper:
> 
> Previous behavior:
> 
> dump(env('APP_ENV')); // local
> 
> putenv('APP_ENV=staging');
> 
> dump(env('APP_ENV')); // staging
> New behavior:
> 
> dump(env('APP_ENV')); // local
> 
> putenv('APP_ENV=staging');
> 
> dump(env('APP_ENV')); // local

https://laravel.com/docs/5.8/upgrade

**Comment by northify** [comment]
Hmmm this seems to suggest this was changed in 5.8. I will upgrade and test.

But even without using the connection variable I can't seem to get the LDAP_CONNECTION to use anything but "default".
So doing some more testing...
I have 2 connections default and abc.
If I rename default to 123 for example, I get and error that is can not find the default connection.

If I move the default to the second option ('abc', 'default') then it will use the default connection config

Does not matter what I set LDAP_CONNECTION= in the .env it will always use default.

Really weird.

**Comment by stevebauman** [comment]
Whoops! That's my mistake @northify - I misread your version.

Are you caching your application config files? Run `php artisan config:clear` and then try again and see if you still have issues.

**Comment by northify** [comment]
OK yeah no worries... I'm on 5.7

I'm not caching my config files but I ran `php artisan config:clear` just to make sure and still the same issues. No matter what I do it only wants to user the default connection.

**Comment by stevebauman** [comment]
I would use the `Config` facade instead of overriding your .env vars:

```php
Config::set('ldap_auth.connection', 'abc');
```

Give that a shot!

**Comment by northify** [comment]
Hi,

Yes! That did the trick. Thank you for that!!!

**Comment by stevebauman** [comment]
Great, no problem at all!
