### ISSUE TITLE
ldap_auth.php change log

### ISSUE THREAD

**Issue by DanteK15** [Adldap2/Adldap2-Laravel#731]
- Laravel Version: 5.6
- Adldap2-Laravel Version:Not sure where to find what version I'm using
- PHP Version: 7.3.4
- LDAP Type: ActiveDirectory

### Description:
I have a Laravel project using an older version of adldap2-laravel, and when I compare the ldap_auth.php files I noticed there are some changes. Where can I find the change log for this file? It's a file the gets created with a php artisan vendor:publish command, so I'm not sure where to find the change-log for it.

**Comment by stevebauman** [comment]
Hi @DanteK15,

You can view this on the [upgrade guide](https://adldap2.github.io/Adldap2-Laravel/#/upgrading?id=upgrading-from-5-to-6) which is specified in the [releases](https://github.com/Adldap2/Adldap2-Laravel/releases/tag/v6.0.0).

Let me know if you require any further information, thanks!
