### ISSUE TITLE
Multi ADLDAP

### ISSUE THREAD

**Issue by eternia** [Adldap2/Adldap2-Laravel#732]
Hi,

I have a problem with multi ldap connection. I have 2 LDAP connection. If i log my user it's ok. If my user is on the second LDAP im in the impossibility to retrieve information (distinguishedname, object...). Because all information provided by ADLDAP2 is the information of my default connection not of my Asept connection... (sorry bad english...)

`    'connections' => [

		'default' => [
            'auto_connect' => env('LDAP_AUTO_CONNECT', true),
            'connection' => Adldap\Connections\Ldap::class,
            'settings' => [
                'schema' => Adldap\Schemas\ActiveDirectory::class,
                'account_prefix' => env('LDAP_ACCOUNT_PREFIX', ''),
                'account_suffix' => env('LDAP_ACCOUNT_SUFFIX', '@ceicom-cloud.fr'),
                'hosts' => explode(' ', env('LDAP_HOSTS', '10.54.1.100')),
                'port' => env('LDAP_PORT', 389),
                'timeout' => env('LDAP_TIMEOUT', 5),
                'base_dn' => env('LDAP_BASE_DN', 'dc=ceicom-cloud,dc=fr'),
                'username' => env('LDAP_USERNAME', 'Administrateur'),
                'password' => env('LDAP_PASSWORD', '******'),
                'follow_referrals' => false,
                'use_ssl' => env('LDAP_USE_SSL', false),
                'use_tls' => env('LDAP_USE_TLS', false),
            ],
        ],

        'asept' => [
            'auto_connect' => env('LDAP_AUTO_CONNECT', true),
            'connection' => Adldap\Connections\Ldap::class,
            'settings' => [
                'schema' => Adldap\Schemas\ActiveDirectory::class,
                'account_prefix' => env('LDAP_ACCOUNT_PREFIX', ''),
                'account_suffix' => env('LDAP_ACCOUNT_SUFFIX', ''),
                'hosts' => explode(' ', env('LDAP_HOSTS', '10.53.24.11')),
                'port' => env('LDAP_PORT', 389),
                'timeout' => env('LDAP_TIMEOUT', 5),
                'base_dn' => env('LDAP_BASE_DN', 'DC=asept,DC=aseptinmed,DC=fr'),
                'username' => env('LDAP_USERNAME', 'Asept\Administrateur'),
                'password' => env('LDAP_PASSWORD', '*****'),
                'follow_referrals' => false,
                'use_ssl' => env('LDAP_USE_SSL', false),
                'use_tls' => env('LDAP_USE_TLS', false),
            ],
        ],
    ],`

For log user i use this code: (find on the github)
`        $connections = config('ldap.connections');

        foreach ($connections as $connection => $config) {
            config(['ldap_auth.connection' => $connection]);
            session(['ldap_auth.connection' => $connection]);

            if ($this->guard()->attempt($this->credentials($request), $request->filled('remember'))) {

                //Set la conneion sur le bon AD !
                return true;
            }
        }`

My User is logged in ! After the loggin i execute this code:

```
public function authenticated() {;
        //dd(config('ldap_auth.connection'));
		$user = Adldap::search()->users()->find(Auth::user()->name);
		$companyregister=ldap_explode_dn ($user->distinguishedname[0], 1);
	}

```

Laravel: Laravel Framework 5.8.15
adldap2/adldap2: "^10.0",
adldap2/adldap2-laravel: "^6.0",
PHP: 7.3.4
Active Directory

If my User is on the second AD (asept) i obtain an error:
Trying to get property 'distinguishedname' of non-object

PS: (config('ldap_auth.connection') is on "Asept"
If i try; `$user = Adldap::search()->users()->get();`
All object retrieved is on the first LDAP (default) not on Asept

**Comment by eternia** [comment]
nobody ?

**Comment by stevebauman** [comment]
Hi @eternia, apologies for the long reply - this got lost in my inbox.

Can you please update your issue with the details that are requested when creating an issue? Otherwise, I cannot assist you.

- Laravel Version: #.#
- Adldap2-Laravel Version: #.#
- PHP Version: #.#
- LDAP Type: ActiveDirectory / OpenLDAP / FreeIPA?

**Comment by eternia** [comment]
Laravel: Laravel Framework 5.8.15
adldap2/adldap2: "^10.0",
adldap2/adldap2-laravel: "^6.0",
PHP: 7.3.4
Active Directory

**Comment by eternia** [comment]
any idea ?

**Comment by stevebauman** [comment]
Hi @eternia,

What `provider` are you using in your `config/ldap_auth.php` configuration file? Ex. `NoDatabaseUserProvider` or `DatabaseUserProvider`?

**Comment by eternia** [comment]
'provider' => Adldap\Laravel\Auth\DatabaseUserProvider::class,

**Comment by stevebauman** [comment]
Ok, the `distinguishedname` property won't be set on your `App\User` model after authentication - you need to synchronize it if you would like to retrieve it after authentication.

You will need to add the `distinguishedname` column to your `users` database table, then add this column into the `sync_attributes` array located inside the `config/ldap_auth.php` file.

For example:

```php
'sync_attributes' => [
    'email' => 'userprincipalname',
    'name' => 'cn',
    'distinguishedname' => 'distinguishedname',
],
```

If you have any further issues let me know and I can re-open this issue.

**Comment by eternia** [comment]
Yeah just is not the distringuishedname on the BDD it's the distringuishedname retreived by ADLDAP2

$user = Adldap::search()->users()->find(Auth::user()->name);
$companyregister=ldap_explode_dn ($user->distinguishedname[0], 1);

The Adldap::search function search on the first AD only not on the second AD... My user is logged by the second AD (not same domain...)

**Comment by stevebauman** [comment]
Using `Adldap::search()` will use your default connection - if you want to search your other domain, you must specify it via `Adldap::getProvider($providerName)->search()`:

```php
$user = Auth::user();

$ldapUser = Adldap::getProvider('connection-name')->search()->users()->find($user->name);
```
