### ISSUE TITLE
Integrate with Passport problem

### ISSUE THREAD

**Issue by tanshiqi** [Adldap2/Adldap2-Laravel#734]
- Laravel Version: 5.8
- Adldap2-Laravel Version: 6.0.5
- PHP Version: 7.2
- LDAP Type: 

### Description:
I am creating an app with Laravel Passport and Vue SPA. How to  integrate the adldap2 with laravel passport?

### Steps To Reproduce:
In my test controller if I use auth()->attempt():
```
auth()->attempt([
	'username': 'someone',
	'password': 'password'
])
```
It works. If the user does not exist in database, it will be created.
Then I flush the database and I request ‘oauth/token’ from Paw with params:
```
{
  "grant_type": "password",
  "client_id": "2",
  "client_secret": "hyvMnodaKcC5gQibKMVayMtupkUj...",
  "username": "someone",
  "password": "password",
  "scope": ""
}
```
I got error: “The user credentials were incorrect.” and user not be created as well.
My config/auth.php:
```
'guards' => [
        'web' => [
            'driver' => 'session',
            'provider' => 'users',
        ],

        'api' => [
            'driver' => 'passport',
            'provider' => 'users',
            'hash' => false,
        ],
    ],
'providers' => [
        'users' => [
            'driver' => 'ldap', // Was 'eloquent'.
            'model' => App\User::class,
        ],
]
```
Does this package could authentication from LDAP and auto create user and integrate to  generate token?
What could go wrong? Thanks

**Comment by viniciusraupp** [comment]
Maybe this help you #685

**Comment by tanshiqi** [comment]
Thanks a lot. It works. 
In my User model:
```
public function findForPassport($username)
{
    $credentials = [
        'username' => $username,
        'password' => request()->password
    ];
    // Authentication passed and create user if not exist in db
    if (auth()->once($credentials)) {
        return auth()->user();
    };
    return false;
}

public function validateForPassportPasswordGrant($password)
{
    // if authentication passed above then just return true
    return true;
}
```
