### ISSUE TITLE
Logging in not working but Adldap::auth()->attempt() successful

### ISSUE THREAD

**Issue by craigward** [Adldap2/Adldap2-Laravel#735]
Adldap2 Version: 5.1
LDAP Type: OpenLDAP
PHP Version: 7.2
Description:

I have set up a local instance of OpenLdap for testing while working away from my office where we use Active Directory. AD works perfectly, but setting up the local version doesn;t seem to work.

I'm using the following https://github.com/rroemhild/docker-test-openldap docker instance to run OpenLdap.

If I run

```
dd(Adldap::search()->where('cn', '=', 'Philip J. Fry')->get()->toArray(), Adldap::auth()->attempt('Philip J. Fry', 'fry'));
```

I get

```
array:1 [▼
  0 => User {#739 ▶}
]
true
```

However, if I try to log into my app, I receive

These credentials do not match our records.

In my .env file I have it configured as

```
ADLDAP_CONTROLLERS=ldap
ADLDAP_BASEDN=ou=people,dc=planetexpress,dc=com
ADLDAP_ADMIN_USERNAME=admin
ADLDAP_ADMIN_PASSWORD=GoodNewsEveryone
ADLDAP_ADMIN_ACCOUNT_PREFIX=cn=
ADLDAP_ADMIN_ACCOUNT_SUFFIX=",dc=planetexpress,dc=com"
ADLDAP_ACCOUNT_PREFIX=cn=
ADLDAP_ACCOUNT_SUFFIX=",ou=people,dc=planetexpress,dc=com"
ADLDAP_PORT=389
ADLDAP_USE_SSL=false
```

and I have also double checked this setup using LDAP Admin Tool and everything seems correct. I can't figure out why the dd() show a successful auth, but logging in via the app doesnt work.

What could be wrong?

**Comment by craigward** [comment]
I'm using OpenLdap for developing and production runs on.Active Directory. I didn;t realise you had to change schema. There is no environment variable for it so I created

```
'schema' => env('LDAP_SCEHMA','Adldap\Schemas\ActiveDirectory::class'),
```

and in .env
```
LDAP_SCEHMA="Adldap\Schemas\OpenLDAP::class"
```

This doesn't work however, and removing the quotes generates the following error `Option schema must be a valid class.` with quotes it just white screens.

How can I change the schema for different environments?

**Comment by stevebauman** [comment]
HI @craigward,

You will need to remove the `::class` suffix to use it in an .env variable:

```
LDAP_SCEHMA="Adldap\Schemas\OpenLDAP"
```

Also, try removing your suffixes and prefixes configuration and use the full distinguished name of your admin account so it looks like:

```
ADLDAP_CONTROLLERS=ldap
ADLDAP_BASEDN=ou=people,dc=planetexpress,dc=com
ADLDAP_ADMIN_USERNAME="cn=admin,dc=planetexpress,dc=com"
ADLDAP_ADMIN_PASSWORD=GoodNewsEveryone
ADLDAP_PORT=389
ADLDAP_USE_SSL=false
```

When using OpenLDAP, you will also likely need to change the `ldap.discover` (since you're using v5.0) config option to `uid` - as OpenLDAP does not use `userPrincipalName`'s.

Can you give that a shot and let me know if it works for you?

**Comment by craigward** [comment]
Yeah, Removing the `::class` works. Doesn't seem like I have had to change the `ldap.discover` option, worked right away.

Thanks

**Comment by stevebauman** [comment]
Perfect! No problem at all.
