### ISSUE TITLE
User Group Authentication

### ISSUE THREAD

**Issue by netopvh** [Adldap2/Adldap2-Laravel#74]
perform authentication only belong to a particular group. How could I do that?

The only user can authenticate to belong to the Administrators group in AD.

**Comment by stevebauman** [comment]
You can use the limitation filter feature:

https://github.com/Adldap2/Adldap2-Laravel#login-limitation-filter

For example, to only allow users that are in an administrator OU, use:

```php
'limitation_filter' => '(ou=Administrators)',
```

**Comment by netopvh** [comment]
I'm not looking for organizational unit , but the group that the user is included .
I saw that search by mail (mail = * )

Group would be ( * = group ) ?

**Comment by stevebauman** [comment]
```php
'limitation_filter' => '(memberof=CN=YourGroup,OU=Users,DC=YourDomain,DC=com)',
```

**Comment by netopvh** [comment]
Hello Steve sorry, more than I am with many questions , it is my first application with this package.
You can pass an array of groups? ie more than one group ?

**Comment by stevebauman** [comment]
No need to apologize! I'm more than happy to help.

> You can pass an array of groups? ie more than one group ?

Yes you can, you just need to pass the filter with both groups in it with the correct LDAP filter syntax:

```
(|(memberof=CN=YourGroup,OU=Users,DC=YourDomain,DC=com)(memberof=CN=OtherGroup,OU=Users,DC=YourDomain,DC=com))
```

The above filter would mean that the user need to be apart of `YourGroup` **OR** `OtherGroup`.

```
(&(memberof=CN=YourGroup,OU=Users,DC=YourDomain,DC=com)(memberof=CN=OtherGroup,OU=Users,DC=YourDomain,DC=com))
```

The above filter would mean that the user need to be apart of `YourGroup` **AND** `OtherGroup`.

**Comment by azmiik** [comment]
Steve, anyway to allow for nested groups? i.e.

User is a member of group CN=sales,DC=example,DC=com

 CN=sales,DC=example,DC=com is a nested group within CN=AppAllowed,DC=example,DC=com

using the filter

(memberof=CN=AppAllowed,DC=example,DC=com)

Having troubles getting this to work.

Thanks

**Comment by stevebauman** [comment]
> Steve, anyway to allow for nested groups?

This may work:

```
(memberOf:1.2.840.113556.1.4.1941:=CN=AppAllowed,DC=example,DC=com)
```

https://confluence.atlassian.com/crowdkb/active-directory-user-filter-does-not-search-nested-groups-715130424.html

**Comment by azmiik** [comment]
Steve,

  That worked like a champ. 

Thanks

**Comment by stevebauman** [comment]
@azmiik Great to hear, thanks for following up!

**Comment by farhadsadat** [comment]
Hello Steve,
I am new with LDAP. I have 14 Department and 30 Branches in my system. How can I make a user group for multi authentication base on the ldap users.

**Comment by shuegelm** [comment]
Is this limitation_filter still working with newest version? And where to put it?
