### ISSUE TITLE
 RuntimeException  : There were no users found to import.

### ISSUE THREAD

**Issue by georgehk** [Adldap2/Adldap2-Laravel#740]
- Laravel Version: 5.8
- Adldap2-Laravel Version: 6.0
- PHP Version: 7.1.3
- LDAP Type: ActiveDirectory

### Description:I'm getting an error when i run php artisan adldap:migrate
I have ping to my AD server and also tested connection to the AD using ldp.exe.
I'm using username for the authentication
Could you please let me know where is my mistake? thanks

C:\Users\Desktop\blog>php artisan adldap:import

  <b> RuntimeException  : There were no users found to import.</b>

  C:\Users\Desktop\blog\vendor\adldap2\adldap2-laravel\src\Commands\Console\Import.php:62
    58|
    59|         $count = count($users);
    60|
    61|         if ($count === 0) {
    62|             throw new RuntimeException("There were no users found to import.");
    63|         } else if ($count === 1) {
    64|             $this->info("Found user '{$users[0]->getCommonName()}'.");
    65|         } else {
    66|             $this->info("Found {$count} user(s).");

Steps To Reproduce:
<b>my ldap.php</b>
<pre>
return [
    'logging' => env('LDAP_LOGGING', false),
    'connections' => [
        'default' => [
            'auto_connect' => env('LDAP_AUTO_CONNECT', true),
            'connection' => Adldap\Connections\Ldap::class,
            'settings' => [
                'schema' => Adldap\Schemas\ActiveDirectory::class,
                'account_prefix' => env('LDAP_ACCOUNT_PREFIX', ''),
                'account_suffix' => env('LDAP_ACCOUNT_SUFFIX', '@SISSERVER.LOCAL'),
                'hosts' => ['SISSERVER.LOCAL'],
                'port' => env('LDAP_PORT', 389),
                'timeout' => env('LDAP_TIMEOUT', 5),
                'base_dn' => 'dc=SISSERVER,dc=LOCAL',
                'username' => 'Administrator',
                'password' => 'Password',
                'follow_referrals' => false,
                'use_ssl' => env('LDAP_USE_SSL', false),
                'use_tls' => env('LDAP_USE_TLS', false),
            ],
        ],
    ],
];
</pre>
<b>my ldap_auth.php</b>
<pre>
return [
    'connection' => env('LDAP_CONNECTION', 'default'),
    'provider' => Adldap\Laravel\Auth\DatabaseUserProvider::class,
    'model' => App\User::class,
    'rules' => [
        Adldap\Laravel\Validation\Rules\DenyTrashed::class,
    ],
    'scopes' => [
    ],
    'identifiers' => [
        'ldap' => [
            'locate_users_by' => 'samaccountname',
            'bind_users_by' => 'distinguishedname',
        ],
        'database' => [
            'guid_column' => 'objectguid',
            'username_column' => 'username',
        ],
        'windows' => [
            'locate_users_by' => 'samaccountname',
            'server_key' => 'AUTH_USER',
        ],
    ],
    'passwords' => [
        'sync' => env('LDAP_PASSWORD_SYNC', false),
        'column' => 'password',
    ],
    'login_fallback' => env('LDAP_LOGIN_FALLBACK', false),
    'sync_attributes' => [
        'username' => 'samaccountname',
        'name' => 'cn',
    ],
    'logging' => [
        'enabled' => env('LDAP_LOGGING', true),
        'events' => [
            \Adldap\Laravel\Events\Importing::class => \Adldap\Laravel\Listeners\LogImport::class,
            \Adldap\Laravel\Events\Synchronized::class => \Adldap\Laravel\Listeners\LogSynchronized::class,
            \Adldap\Laravel\Events\Synchronizing::class => \Adldap\Laravel\Listeners\LogSynchronizing::class,
            \Adldap\Laravel\Events\Authenticated::class => \Adldap\Laravel\Listeners\LogAuthenticated::class,
            \Adldap\Laravel\Events\Authenticating::class => \Adldap\Laravel\Listeners\LogAuthentication::class,
            \Adldap\Laravel\Events\AuthenticationFailed::class => \Adldap\Laravel\Listeners\LogAuthenticationFailure::class,
            \Adldap\Laravel\Events\AuthenticationRejected::class => \Adldap\Laravel\Listeners\LogAuthenticationRejection::class,
            \Adldap\Laravel\Events\AuthenticationSuccessful::class => \Adldap\Laravel\Listeners\LogAuthenticationSuccess::class,
            \Adldap\Laravel\Events\DiscoveredWithCredentials::class => \Adldap\Laravel\Listeners\LogDiscovery::class,
            \Adldap\Laravel\Events\AuthenticatedWithWindows::class => \Adldap\Laravel\Listeners\LogWindowsAuth::class,
            \Adldap\Laravel\Events\AuthenticatedModelTrashed::class => \Adldap\Laravel\Listeners\LogTrashedModel::class,
        ],
    ],
];
</pre>
<b>my auth.php </b>
<pre>
'providers' => [
        'users' => [
            'driver' => 'ldap', // Was 'eloquent'.
            'model'  => App\User::class,
        ],
    ],
</pre>

**Comment by stevebauman** [comment]
Hi @georgehk,

Firstly, remove your `account_suffix` (@SISSERVER.LOCAL) and include this manually on your administrators username (`'username' => 'Administrator@SISSERVER.LOCAL'`).

Then try changing your `hosts` to the IP address of your domain controller to see if it's a possible DNS issue:

```php
'hosts' => ['192.168.1.1'],
```

All of your other configuration settings are correct. Give that a shot and let me know if it works!

**Comment by georgehk** [comment]
Hello @stevebauman 
I have changed according to your suggestion and the error message gone, however, now for some reason i getting the following message
<pre>
 15/15 [============================] 100%

Successfully imported / synchronized 0 user(s).
</pre>

<b>mi Users migration is:</b>
<pre>

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;
class CreateUsersTable extends Migration
{
    public function up()
    {
        Schema::create('users', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->string('name');
            $table->string('username')->unique();
            $table->string('password');
            $table->rememberToken();
            $table->timestamps();
        });
    }
    public function down()
    {
        Schema::table('users', function (Blueprint $table) {
            $table->dropColumn('username');
        });
    }
}
</pre>
I have added to LoginController.php
<pre>
    public function username()
    {
        return 'username';
    }
</pre>
I have changed in <b>login.blade.php</b> from <b>email</b> to <b>username</b> and try to login and get an error message:
<pre>
 C:\Users\Desktop\blog\vendor\laravel\framework\src\Illuminate\Database\Connection.php
         * @param  array     $bindings
         * @param  \Closure  $callback
         * @return mixed
         *
         * @throws \Illuminate\Database\QueryException
         */
        protected function runQueryCallback($query, $bindings, Closure $callback)
        {
            // To execute the statement, we'll simply call the callback, which will actually
            // run the SQL against the PDO connection. Then we can calculate the time it
            // took to execute and log the query SQL, bindings and time in our memory.
            try {
                $result = $callback($query, $bindings);
            }
     
            // If an exception occurs when attempting to run a query, we'll format the error
            // message to include the bindings with SQL, which will make this exception a
            // lot more helpful to the developer instead of just the database's errors.
            catch (Exception $e) {
                throw new QueryException(
                    $query, $this->prepareBindings($bindings), $e
                );
            }     
            return $result;
        }
             /**
         * Log a query in the connection's query log.
         *
         * @param  string  $query
         * @param  array   $bindings
         * @param  float|null  $time
         * @return void
         */
        public function logQuery($query, $bindings, $time = null)
        {
            $this->event(new QueryExecuted($query, $bindings, $time, $this));
     
            if ($this->loggingQueries) {

Arguments

    "SQLSTATE[42S22]: Column not found: 1054 Unknown column 'objectguid' in 'where clause' (SQL: select * from `users` where `objectguid` = 103dcb09-da36-470e-aac2-5 ▶"

</pre>


Could you please help me to solve this issue?.
Thank you in advance.

**Comment by stevebauman** [comment]
> I have changed according to your suggestion and the error message gone, however, now for some reason i getting the following message

That's good, it's definitely locating users now (seeing 15/15).

> I have changed in login.blade.php from email to username and try to login and get an error message:

You need to create an `objectguid` column in your `users` database table as mentioned in the documentation here:

https://adldap2.github.io/Adldap2-Laravel/#/auth/setup?id=databaseuserprovider

> Note: This provider requires that you add an `objectguid` database column to your users database table. [Read more here](https://adldap2.github.io/Adldap2-Laravel/#/auth/setup?id=guid-column).

This is required so your users can be renamed in your LDAP server but stay properly synchronized with your local apps database.

**Comment by georgehk** [comment]
Hello @stevebauman 

Thank you very much for your great help. it is working fine now :)

**Comment by stevebauman** [comment]
Awesome @georgehk! Glad you were able to resolve it! Thanks for following up.
