### ISSUE TITLE
Can't contact LDAP server

### ISSUE THREAD

**Issue by therituagarwal** [Adldap2/Adldap2-Laravel#741]
- Laravel Version: 5.6
- Adldap2-Laravel Version: 5.1
- PHP Version: 7.2
- LDAP Type: ActiveDirectory

### Description:

Trying to connect to the server and getting below error :

Adldap\Auth\BindException: Can&#039;t contact LDAP server in file /var/www/html/laravel/vendor/adldap2/adldap2/src/Auth/Guard.php on line 79
Stack trace:
  1. Adldap\Auth\BindException-&gt;() /var/www/html/laravel/vendor/adldap2/adldap2/src/Auth/Guard.php:79
  2. Adldap\Auth\Guard-&gt;bind() /var/www/html/laravel/vendor/adldap2/adldap2/src/Auth/Guard.php:90
  3. Adldap\Auth\Guard-&gt;bindAsAdministrator() /var/www/html/laravel/vendor/adldap2/adldap2/src/Connections/Provider.php:229
  4. Adldap\Connections\Provider-&gt;connect() /var/www/html/laravel/vendor/adldap2/adldap2/src/Adldap.php:127
  5. Adldap\Adldap-&gt;connect() /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:223
  6. Illuminate\Support\Facades\Facade-&gt;__callStatic() /var/www/html/laravel/app/Http/Controllers/TestController.php:13
  7. App\Http\Controllers\TestController-&gt;index() /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Routing/Controller.php:54
  8. call_user_func_array() /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Routing/Controller.php:54
  9. Illuminate\Routing\Controller-&gt;callAction() /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php:45
 10. Illuminate\Routing\ControllerDispatcher-&gt;dispatch() /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Routing/Route.php:212
 11. Illuminate\Routing\Route-&gt;runController() /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Routing/Route.php:169
 12. Illuminate\Routing\Route-&gt;run() /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Routing/Router.php:665
 13. Illuminate\Routing\Router-&gt;Illuminate\Routing\{closure}() /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:30
 14. Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}() /var/www/html/laravel/app/Http/Controllers/Controller.php:47
 15. App\Http\Controllers\Controller-&gt;App\Http\Controllers\{closure}() /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:133
 16. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
 17. Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}() /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php:41
 18. Illuminate\Routing\Middleware\SubstituteBindings-&gt;handle() /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:151
 19. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
 20. Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}() /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php:67
 21. Illuminate\Foundation\Http\Middleware\VerifyCsrfToken-&gt;handle() /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:151
 22. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
 23. Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}() /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php:49
 24. Illuminate\View\Middleware\ShareErrorsFromSession-&gt;handle() /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:151
 25. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
 26. Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}() /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php:63
 27. Illuminate\Session\Middleware\StartSession-&gt;handle() /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:151
 28. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
 29. Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}() /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php:37
 30. Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse-&gt;handle() /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:151
 31. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
 32. Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}() /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php:59
 33. Illuminate\Cookie\Middleware\EncryptCookies-&gt;handle() /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:151
 34. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
 35. Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}() /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:104
 36. Illuminate\Pipeline\Pipeline-&gt;then() /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Routing/Router.php:667
 37. Illuminate\Routing\Router-&gt;runRouteWithinStack() /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Routing/Router.php:642
 38. Illuminate\Routing\Router-&gt;runRoute() /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Routing/Router.php:608
 39. Illuminate\Routing\Router-&gt;dispatchToRoute() /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Routing/Router.php:597
 40. Illuminate\Routing\Router-&gt;dispatch() /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:176
 41. Illuminate\Foundation\Http\Kernel-&gt;Illuminate\Foundation\Http\{closure}() /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:30
 42. Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}() /var/www/html/laravel/vendor/fideloper/proxy/src/TrustProxies.php:57
 43. Fideloper\Proxy\TrustProxies-&gt;handle() /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:151
 44. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
 45. Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}() /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php:31
 46. Illuminate\Foundation\Http\Middleware\TransformsRequest-&gt;handle() /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:151
 47. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
 48. Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}() /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php:31
 49. Illuminate\Foundation\Http\Middleware\TransformsRequest-&gt;handle() /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:151
 50. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
 51. Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}() /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php:27
 52. Illuminate\Foundation\Http\Middleware\ValidatePostSize-&gt;handle() /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:151
 53. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
 54. Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}() /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php:62
 55. Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode-&gt;handle() /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:151
 56. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
 57. Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}() /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:104
 58. Illuminate\Pipeline\Pipeline-&gt;then() /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:151
 59. Illuminate\Foundation\Http\Kernel-&gt;sendRequestThroughRouter() /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:116
 60. Illuminate\Foundation\Http\Kernel-&gt;handle() /var/www/html/laravel/public/index.php:55

**Comment by stevebauman** [comment]
Hi @therituagarwal,

This exception just means your web server can't contact your ActiveDirectory server.

Have you ensured your web server that hosts you web app can contact your AD server by hostname or IP address that your placed in your `ldap.php` configuration file in the `hosts` option?

**Comment by therituagarwal** [comment]
Hi @stevebauman 

I tried with IP address and I'm able to connect to ActiveDirectory server. But the problem is I want to use NoDatabaseUserProvider and authorize users on active directory. I followed the steps given here https://adldap2.github.io/Adldap2-Laravel/#/auth/setup, but it's showing Invalid credentials.

**Comment by stevebauman** [comment]
Hi @therituagarwal,

Okay, enable authentication logging by setting the `logging` option to `true` in your `ldap_auth.php` file, then attempt logging into your application again.

Once you've done that, open your log file inside your `storage/logs` directory and post the results here - that will help me debug with you further.

**Comment by therituagarwal** [comment]
Hi @stevebauman 

I enabled and checked logs and found a bug in Account Suffix. I resolved the issue and now users is able to logged in but there is some issue in Auth. See below error in log.

Also I added "authenticate" function in login controller.
public function authenticate(Request $request)
    {
        $credentials = $request->only('samaccountname', 'password');

        if (Auth::attempt($credentials)) {
            // Authentication passed...
            Auth::user();
            return redirect()->intended('admin.index');
        }
        return false;
    }

---------------------------------------------

[2019-06-04 11:24:55] local.INFO: User 'Ritu Agarwal' has been successfully found for authentication.  
[2019-06-04 11:24:55] local.INFO: User 'Ritu Agarwal' is authenticating with username: '***@***.net'  
[2019-06-04 11:24:55] local.INFO: User 'Ritu Agarwal' has successfully passed LDAP authentication.  
[2019-06-04 11:24:55] local.INFO: User 'Ritu Agarwal' has been successfully logged in.  
[2019-06-04 11:24:55] local.ERROR: Call to a member function get() on null {"userId":"7961be3f-4366-4471-a711-f581789ce191","exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function get() on null at /var/www/html/laravel/app/Helpers/Helper.php:113)
[stacktrace]
#0 /var/www/html/laravel/app/Http/Controllers/Controller.php(42): App\\Helpers\\Helper::getLocations()
#1 /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(133): App\\Http\\Controllers\\Controller->App\\Http\\Controllers\\{closure}(Object(Illuminate\\Http\\Request), Object(Closure))
#2 /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#3 /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#4 /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#5 /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#6 /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(67): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#7 /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#8 /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#9 /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#10 /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#11 /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#12 /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#13 /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#14 /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#15 /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#16 /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#17 /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#18 /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#19 /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#20 /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#21 /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#22 /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Routing/Router.php(667): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#23 /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Routing/Router.php(642): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#24 /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Routing/Router.php(608): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#25 /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Routing/Router.php(597): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#26 /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#27 /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#28 /var/www/html/laravel/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#29 /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#30 /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#31 /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#32 /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#33 /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#34 /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#35 /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#36 /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#37 /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#38 /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#39 /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#40 /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#41 /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#42 /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#43 /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#44 /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#45 /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#46 /var/www/html/laravel/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#47 {main}
"} 

In getLocation function I'm trying to access user role from our system "$role = Auth::user()->roles->get(0);"

As user is logged in using active directory, get function is not available. So is there any option to sync properties from current DB as well ?

**Comment by stevebauman** [comment]
Great, glad you were able to get successfully logged in!

> As user is logged in using active directory, get function is not available. So is there any option to sync properties from current DB as well ?

There are definitely many ways of doing this - you will have to create something to sync your local web applications roles by checking your LDAP users group memberships. I do this for many web applications internally.

Here's how I do it:

Create a listener named `SynchronizeRoles` (via `php artisan make:listener SynchronizeRoles`). This listener will listen for the `AuthenticationSuccessful` event that is fired when an LDAP user is successfully logged into your application.

```php
namespace App\Listeners;

use App\Role;
use Adldap\Laravel\Events\AuthenticationSuccessful;

class SynchronizeRoles
{
    /**
     * Synchronize user roles upon successful LDAP authentication.
     *
     * @param AuthenticationSuccessful $event
     *
     * @return void
     */
    public function handle(AuthenticationSuccessful $event)
    {
        // Determine if the LDAP user authenticating is inside the 'Helpdesk Administrators' AD group
        if ($event->user->inGroup('Helpdesk Administrators')) {
            /** @var \App\User $model */
            $model = $event->model;

            // Locate the local web application role and sync it with the user account.
            $role = Role::where('name', '=', 'admin')->firstOrFail();

            $model->roles()->sync($role);
        }
    }
}
```

Then in your `EventServiceProvider` (located inside `Providers/EventServiceProvider.php`) add the event with the listener you created:

```php
namespace App\Providers;

use Illuminate\Foundation\Support\Providers\EventServiceProvider as ServiceProvider;

class EventServiceProvider extends ServiceProvider
{
    /**
     * The event listener mappings for the application.
     *
     * @var array
     */
    protected $listen = [
        \App\Events\PasswordReset::class => [
            \App\Listeners\SendPasswordNotification::class,
        ],
        \Adldap\Laravel\Events\AuthenticationSuccessful::class => [ // <-- Added Event Here
            \App\Listeners\SynchronizeRole::class, // <-- Added Listener Here
        ]
    ];
}
```

Let me know if you need any further assistance and I can re-open this issue. Thanks :smile:

**Comment by stevebauman** [comment]
Also for further reference, you can add more sync attributes to your `ldap_auth.php` file - but you won't be able to synchronize roles this way - only attributes.

https://adldap2.github.io/Adldap2-Laravel/#/auth/setup?id=synchronizing

**Comment by therituagarwal** [comment]
If I use DatabaseUserProvider provider, all functions and attributes defined in Laravel for users will work as is with AD features and functions, right ?

If it is then I'll rather use DatabaseUserProvider and sync attributes from AD to Laravel DB.

**Comment by stevebauman** [comment]
> If I use DatabaseUserProvider provider, all functions and attributes defined in Laravel for users will work as is with AD features and functions, right ?

That’s correct. The `NoDatabaseUserProvider` users an Adldap2 `User` model - while the `DatabaseUserProvider` uses your configured `App\User` model that exists in your local database.

**Comment by therituagarwal** [comment]
That's great, got another task on priority. But check this next week and let you know if it works :)
