### ISSUE TITLE
LDAP property missing from User object

### ISSUE THREAD

**Issue by lotius** [Adldap2/Adldap2-Laravel#743]
- Laravel Version: 5.8.22
- Adldap2-Laravel Version: 6.0.6
- PHP Version: 7.3.4
- LDAP Type: ActiveDirectory

Description:

I'm authenticating my users based on username and password. The AD users authenticate successfully and are logged in to the application. The fields I want are sync'd correctly. The issue is that my logged in User object's 'ldap' property is always null. I can recreate this in Tinker as well. So I can't access any of the ldap methods. 

I re-created a new application from scratch and followed the Adldap2-Laravel instructions to the letter, but I'm getting the same problem. I feel like I'm missing something somewhere. I've done Laravel applications in the past and haven't had this problem.

Steps To Reproduce:

1) I log the user in via Tinker using Auth::attempt(<credentials array>).
2) The user is logged in successfully, but I do get the following...
PHP Warning:  unlink
PHP Warning:  ldap_search(): Search: Bad search filter
PHP Warning:  ldap_get_entries() expects parameter 2 to be resource, bool given
PHP Warning:  ldap_search(): Search: Bad search filter
PHP Warning:  ldap_get_entries() expects parameter 2 to be resource, bool given

Each warning is followed by a file path to the php file the warning originates from. Perhaps this ldap_search() thing is the reason I'm having issues?
3) Once logged in I can access the user via Auth::user(), but as mentioned above, the ldap property is null.

Any direction on this would be much appreciated!

**Comment by stevebauman** [comment]
Hi @lotius,

Did you add the `Adldap\Laravel\Traits\HasLdapUser` trait onto your configured `User` model?

**Comment by lotius** [comment]
@stevebauman 

Yes, sir.
![User_trait](https://user-images.githubusercontent.com/5818515/59435974-5a4aec00-8db4-11e9-8c40-3610eb058614.jpg)

**Comment by lotius** [comment]
I was fairly certain in the past the trait was added automatically during the installation process, but I had to manually add it to my User this time around. Am I just misremembering this?

**Comment by stevebauman** [comment]
@lotius Ok great. Did you also add the `objectguid` ID to your `users` table and configure that column in your `ldap_auth.php` file? If so, is that column being synchronized properly when logging into your application?

**Comment by stevebauman** [comment]
> I was fairly certain in the past the trait was added automatically during the installation process

No the trait isn't added automatically, you have to add it. In past versions the trait wasn't used - the `ldap` property on the `User` model was set automatically when a config option was set.

The trait was added to remove the need for a config option.

**Comment by lotius** [comment]
objectguid was added to the users table and was configured in ldap_auth.php. After a successful login it shows up in the users table in the db as expected.

**Comment by stevebauman** [comment]
Hmm.... Can you try the following?

```php
use Adldap\Laravel\Facades\Resolver;

// Replace the below GUID with a GUID that was synchronized in your database.
$guid = 'bf9679e7-0de6-11d0-a285-00aa003049e2';

$user = Resolver::byId($guid);

dd($user);
```

You can place this in any of your controllers or routes file. This is simply testing that the user resolver is able to locate your synchronized user by it's Object GUID in your directory.

If that successfully returns the LDAP user that owns that GUID, we can continue troubleshooting.

**Comment by lotius** [comment]
Looks like it found it correctly.
![User_resolved](https://user-images.githubusercontent.com/5818515/59438165-96804b80-8db8-11e9-9b56-de5d37ba7bd5.jpg)

**Comment by stevebauman** [comment]
Ok great, can you post your `auth.php` config file as well as your `ldap_auth.php` file?

**Comment by lotius** [comment]
Can do. Redacted certain information, but it's mostly pretty standard stuff.


[ldap_auth.php.txt](https://github.com/Adldap2/Adldap2-Laravel/files/3286778/ldap_auth.php.txt)
[ldap.php.txt](https://github.com/Adldap2/Adldap2-Laravel/files/3286779/ldap.php.txt)

**Comment by stevebauman** [comment]
Hmm everything looks fine.

It seems like the listener possibly isn't being called. Can you try editing the `BindsLdapUserModel.php` file ([here](https://github.com/Adldap2/Adldap2-Laravel/blob/master/src/Listeners/BindsLdapUserModel.php)) and try `dd()`'ing inside the `handle()` method to see if it's actually being called after successful authentication?

**Comment by lotius** [comment]
Looks like it's getting called. Stops any further activity after a login by just doing a dd() at the end of handle().

If I dd($event) I can see the user and the attached ldap property.

**Comment by stevebauman** [comment]
Strange... Can you add `dd()` *after* you have authenticated on the subsequent request?

I'm wondering if it's binding successfully during the authentication attempt, and then afterwards the binding is lost.

**Comment by lotius** [comment]
I'm not sure I understand what you mean.

**Comment by stevebauman** [comment]
Apologies, this is what I mean:

1. Login to your app normally
2. After you've logged in, add `dd()` to the `BindsLdapUserModel`
3. Refresh the page
4. See if the user model in the event has the `ldap` property set

**Comment by lotius** [comment]
Oh! Gotcha.

After a refresh the user model has the ldap property.

**Comment by lotius** [comment]
Ok, man. I just don't get it. Now it's working!    :|    <--potato face

**Comment by stevebauman** [comment]
Oh okay - I think this issue exists primary when running Laravel Tinker? I've seen this issue before...

**Comment by lotius** [comment]
Strange. Some kind of caching problem or something? No idea.

In Tinker I was trying to make sure to Auth::logout() every time. That could be it, though.  Now in Tinker my user's (and other test users) ldap property is showing up. How would I go about confirming?

**Comment by stevebauman** [comment]
I think you may already be doing this, but you can confirm it like so:

```
php artisan tinker

Psy Shell v0.9.9 (PHP 7.3.2 — cli) by Justin Hileman
>>> Auth::attempt(['username' => 'myusername', 'password' => 'mypassword'])
=> true
>>> auth()->user()->ldap;
=> Adldap\Models\User {#3165
     +exists: true,
     +dateFormat: "Y-m-d H:i:s",
}
```

**Comment by lotius** [comment]
Oh, yes. That's what I was doing. My main user and several test users all have the ldap property bound now in Tinker the way I'd expect. I honestly don't know what changed here.

**Comment by stevebauman** [comment]
Strange... Could be caching like you mentioned? Are you caching your configuration files?

**Comment by lotius** [comment]
No, I didn't explicitly cache anything yet. It's basically a fresh install of Laravel as of yesterday. I have not rebooted since I began though.

**Comment by stevebauman** [comment]
Dang, I'm stumped as well!

Is it possible that your AD server was inaccessible for a short period of time? LDAP errors are hidden during authentication - so I'm wondering if that may have been the case (long shot).

**Comment by lotius** [comment]
Possible, but very unlikely. We have 2 DC's and I haven't experienced an outage on them in quite some time. If they were out for any amount of time I'm sure users would be ringing my phone off the hook almost instantly.

Has to be something goofy being cached or still in memory somehow. When I originally was authenticating and it wasn't working yet I didn't yet have the HasLdapUser trait on there yet. I re-read the documentation and saw that I was missing that and added it. Maybe something got goofed from that?

**Comment by stevebauman** [comment]
Ah okay I understand.

> Has to be something goofy being cached or still in memory somehow.

Definitely sounds like a possibility! I'll close this out for now since you've resolved it, but if you have any further issues feel free to create another issue or comment here and I can assist you. :smile:
