### ISSUE TITLE
Get all Root OU

### ISSUE THREAD

**Issue by eternia** [Adldap2/Adldap2-Laravel#744]
Laravel: Laravel Framework 5.8.15
adldap2/adldap2: "^10.0",
adldap2/adldap2-laravel: "^6.0",
PHP: 7.3.4
Active Directory
-----------------------------------------

How to get all root OU ? (just OU in root of AD. Not a full tree of Ou in Ou...)

**Comment by stevebauman** [comment]
Hi @eternia,

Use the `lising()` method to indicate you want only root records and not the full tree.

For example:

```php
$ou = 'ou=Accounting Users,dc=acme,dc=org';

$users = Adldap::search()->in($ou)->listing()->get();
```
