### ISSUE TITLE
Enable or Disable Ldap based in configuration

### ISSUE THREAD

**Issue by Surt** [Adldap2/Adldap2-Laravel#745]
¿It is possible to disable adldap based on configuration?
My app is on-premise and each client differs in its requirements. Some of them does not use ldap and I will like to "disable" it from autoregistering-connect based in configuration.

I did try but since it is in some way "merged" with the auth system I couldn't find a way.

**Comment by stevebauman** [comment]
Hi @Surt,

I'm not sure I fully understand your question - but I'll do my best to help.

You can disable the `auto_connect` option for your configured LDAP connection via run-time if you call `Config::set('ldap.connections.default.auto_connect', false)`.

Or you can simply create another authentication guard in your `config/auth.php` file named `ldap` and then call upon it if it is enabled in your application:

```php
'guards' => [
    'web' => [
        'driver' => 'session',
        'provider' => 'users',
    ],

    'ldap' => [
        'driver' => 'session',
        'provider' => 'ldap',
    ],

    'api' => [
        'driver' => 'token',
        'provider' => 'users',
    ],
],

'providers' => [
    'users' => [
        'driver' => 'database',
        'model' => App\User::class,
    ],

    'ldap' => [
        'driver' => 'ldap',
        'model' => App\User::class,
    ],
],
```

Then when authenticating:

```php
// Somehow check if LDAP authentication is enabled in your application
// This is simply an example.
if (Config::get('settings.ldap_enabled', false)) {
    if (Auth::guard('ldap')->attempt($credentials)) {
        // Authenticated via LDAP.
    }
} else {
        if (Auth::guard('web')->attempt($credentials)) {
        // Authenticated via regular local database account.
    }
}
```

Let me know if you need any further help.
