### ISSUE TITLE
php artisan adldap:import not working

### ISSUE THREAD

**Issue by jerlabor** [Adldap2/Adldap2-Laravel#747]
- Laravel Version: 5.8.24
- Adldap2-Laravel Version: 10.0.11
- PHP Version: 7.3.6
- LDAP Type: ActiveDirectory 

### Description:
Everytime I run the "php artisan adldap:import" it does nothing .. no error on the logs.. but when I use the filter option it can see fetch users and can be imported successfully..

**Comment by stevebauman** [comment]
Hi @jerlabor,

Do you see any output from the command at all? Does it prompt you for any input? Or does it literally do nothing?

**Comment by jerlabor** [comment]
It just pause for a few seconds then no output at all.
![adldap_import](https://user-images.githubusercontent.com/32782572/60310801-1268bf00-9987-11e9-903d-d6159e104498.PNG)

**Comment by stevebauman** [comment]
Strange... Is logging enabled in your `ldap.php`? If not, can you enable it and try again then check your logs and see if anything is output?

**Comment by jerlabor** [comment]
yep same as usual no logs relevant to the "php artisan adldap:import" command
![adldap_log](https://user-images.githubusercontent.com/32782572/60311197-c454bb00-9988-11e9-8d8c-473ea457327b.PNG)

**Comment by jerlabor** [comment]
I solved this through changing the memory size

**Comment by stevebauman** [comment]
Great thanks for letting me know @jerlabor!
