### ISSUE TITLE
When using SSO, rules are not used

### ISSUE THREAD

**Issue by CyrProject** [Adldap2/Adldap2-Laravel#748]
- Laravel Version: 5.8.16
- Adldap2-Laravel Version: 6.0.5
- PHP Version: 7.2
- LDAP Type: ActiveDirectory

### Description:

When using the SSO middleware, the rules in ldap_auth don't seem to apply.

**Comment by stevebauman** [comment]
Hi @CyrProject,

You're right, this is an oversight on my part.

I'll have a patch out shortly. Thanks!

**Comment by CyrProject** [comment]
No problem, I appreciate your prompt response! One of those issues where I wasn't sure if I was crazy as it never seemed to do what I thought it would.

**Comment by stevebauman** [comment]
Lol no problem! We're all patched up.

New release will be coming out shortly when travis tests pass.

**Comment by stevebauman** [comment]
[v6.0.7](https://github.com/Adldap2/Adldap2-Laravel/releases/tag/v6.0.7) is now out. Thanks again!
