### ISSUE TITLE
Can i import data another table(that is not for using as user)?  [Question]

### ISSUE THREAD

**Issue by inyoungk** [Adldap2/Adldap2-Laravel#749]
- Laravel Version: 5.7
- Adldap2-Laravel Version: #.#
- PHP Version: 7.2
- LDAP Type: 

### Description:
Hi, Before starting , I really want to express thankful to this package :)
It is very useful for my system.

Nowadays I make a system that is like human resource program.
So there are tables (users, managers).
I want to import data and store at "users table".
(+ users table is like a member table.)
but the system have to login with "managers table".

Is it possible?? If I can , please give me example code.

thanks in advance.

**Comment by stevebauman** [comment]
Hi @inyoungk,

You can specify a model to use when using the `php artisan adldap:import` command:

```bash
php artisan adldap:import --model "App\Manager"
```

Keep in mind that it will try to use the your configured `sync_attributes` that is located in your `ldap_auth.php` configuration file - so if your `managers` database table does not contain the same columns as your `users` table, you will either have to override the configured `sync_attributes`.

**Comment by SandeepAgrahari** [comment]
Hi @stevebauman,
My requirement is to insert LDAP user data into Mysql multiple tables.
Like user email, password, username, name in one table. and mobile number, gender, and other details in another table.

Kindly help me with the way to achieve this.
