### ISSUE TITLE
Upgraded to Laravel 5.2 (from 5.1.x), broke Adldap2

### ISSUE THREAD

**Issue by sarahkemp** [Adldap2/Adldap2-Laravel#75]
I had this working fine the other day, and I'm sure it is something stupid now, but it is the end of the day and I just can't make sense of it. After updating to 5.2, my login page now gives me the error:

    ErrorException in AdldapAuthServiceProvider.php line 38:
    Argument 2 passed to Adldap\Laravel\AdldapAuthServiceProvider::Adldap\Laravel\{closure}() 
    must be of the type array, null given

The line in question: https://github.com/Adldap2/Adldap2-Laravel/blob/v1.4/src/AdldapAuthServiceProvider.php#L38

Any ideas?

Thanks for reading.

**Comment by stevebauman** [comment]
You need to update your `config/auth.php` file for upgrading from L5.1 to L5.2:

https://github.com/Adldap2/Adldap2-Laravel#laravel-52

**Comment by sarahkemp** [comment]
Yes, I had done the update to config/auth.php. With a clearer head this morning I found my issue was incorrect editing. I had put the adlap driver in the passwords block rather than the providers block somehow.

Wrong:

    'passwords' => [
        'adldap' => [
            'driver' => 'adldap',
            'model' => App\User::class,
        ],
        'users' => [
            'provider' => 'users',
            'email' => 'auth.emails.password',
            'table' => 'password_resets',
            'expire' => 60,
        ],
    ],

Right:

    'providers' => [
        'adldap' => [
            'driver' => 'adldap',
            'model' => App\User::class,
        ],
        'users' => [
            'driver' => 'eloquent',
            'model' => App\User::class,
        ],
    ],
    
Sorry for the trouble.

**Comment by stevebauman** [comment]
No problem, glad you've solved the issue.
