### ISSUE TITLE
Import non authenticatable users

### ISSUE THREAD

**Issue by ismaelw** [Adldap2/Adldap2-Laravel#756]
- Laravel Version: 5.8.24
- Adldap2-Laravel Version: 6.0.6
- PHP Version: 7.2
- LDAP Type: ActiveDirectory

### Description:

I would like to have two AD groups. One for users that can login and do things and the other one for users i want to import into my application.

Right now i can't import users with a special filter (memberof group App_Users) because they are not in my memberOf Scope.

MemberOf Scope - Group "App_Admin"
Filter - Group "App_Users"

Is there any possibility to import users, that shouldn't be allowed to login?

**Comment by stevebauman** [comment]
Hi @ismaelw,

Yes definitely, I do this now internally.

Import all users you want inside your local applications database, then use a [rule](https://adldap2.github.io/Adldap2-Laravel/#/auth/setup?id=rules) to only allow members of "App_Admin" to authenticate:

**Rule:**

```php
namespace App\Rules;

use Adldap\Laravel\Validation\Rules\Rule;

class OnlyApplicationAdministrators extends Rule
{
    /**
     * Determines if the user is allowed to authenticate.
     *
     * @return bool
     */   
    public function isValid()
    {
        return $this->user->inGroup('App_Admin');
    }
}
```

**Config:**

```php
'rules' => [
    \App\Rules\OnlyApplicationAdministrators::class,
],
```

**Comment by ismaelw** [comment]
@stevebauman Thank you so much for your fast reply. 

What I have now is:

- All users to import are in the App_Users group (including the admins from the group App_Admin)
- Rule created, checking if the user is in the group App_Admin
- Added Rule to ldap_auth.php file
- MemberOf Scope checks the user if he is in the group App_Users

With my tests it seems to work. Is this the right way to go how I did it now?

One thing though: After I add a user to the App_Admins group i have to clear the cache that the user can login. Is this right? Or is there still something wrong?

**Comment by stevebauman** [comment]
No problem @ismaelw!

> With my tests it seems to work. Is this the right way to go how I did it now?

Yup, this is definitely the way to go about this.

> One thing though: After I add a user to the App_Admins group i have to clear the cache that the user can login. Is this right? Or is there still something wrong?

You don't have to clear any caches (unless you're caching something yourself).

When you add a user into your `App_Admins` group in ActiveDirectory, they should be able to login to your application without clearing anything. When a user attempts logging into your application, their ActiveDirectory group memberships will be queried for *during that authentication attempt* - they are not cached.

However, if you *remove* a user from your `App_Admins` group and the user is logged into your web application, they will need to logout for the changes to take effect.

**Comment by ismaelw** [comment]
Thanks @stevebauman !

Everything clear now :) Again thanks for this super fast support on this!

**Comment by stevebauman** [comment]
Glad I could help @ismaelw! No problem at all :smile:
