### ISSUE TITLE
is there a way to rollback importing?

### ISSUE THREAD

**Issue by inyoungk** [Adldap2/Adldap2-Laravel#759]
- Laravel Version: 5.7
- Adldap2-Laravel Version: 6.x
- PHP Version: 7.1
- LDAP Type:  ActiveDirectory 

### Description:
Hi,  I have a few questions.

1.I want to rollback after importing user data.
because I develop system that have limit of account.
is there a way i can do?

2. After importing user data, can I get how many user updated or added?
 I think the number of deleted can be accounted with soft deletes. But  updated or added.. I don't know how can get them.

thanks.

**Comment by stevebauman** [comment]
Hi @inyoungk,

> I want to rollback after importing user data. because I develop system that have limit of account. is there a way i can do?

You would have to implement this yourself. There's tons of ways you could accomplish this - such as a `DB::transaction()` if you want pure database rollbacks, or identify / keep track of which users are imported in some way and then delete those accounts after the fact.

> After importing user data, can I get how many user updated or added? I think the number of deleted can be accounted with soft deletes. But updated or added.. I don't know how can get them.

There are several events that are fired during the import process that may help you do this:

- `Adldap\Laravel\Events\Importing` - Fired before the users first import in your database
- `Adldap\Laravel\Events\Synchronized` - Fired every time a user is being synchronized via import
- `Adldap\Laravel\Events\Synchronizing` - Fired every time after a user has been synchronized via import

A list of all events can be found here: https://adldap2.github.io/Adldap2-Laravel/#/auth/events

There's also the option of extending the `Adldap\Laravel\Commands\Console\Import` command and overriding the `import()` method with your own - as it tallies the total number of users imported & synchronized:

https://github.com/Adldap2/Adldap2-Laravel/blob/e7a88e019b13b3a370b31c1e7f5784c5dec1804a/src/Commands/Console/Import.php#L97-L138 

Hope this helps!
