### ISSUE TITLE
Adldap not login with laravel auth?

### ISSUE THREAD

**Issue by umefarooq** [Adldap2/Adldap2-Laravel#76]
Hi i am trying Adldap with laravel auth i have followed all steps in documentation but i am not able to login with AD username and password, without laravel auth using following code i can login with active directory username and password

```Adldap::authenticate($username, $password)```

i am using username as input field.

**Comment by stevebauman** [comment]
Hi, you need to utilize Adldap's auth driver. `Adldap::authenticate($username, $password)` does nothing besides trying to bind to your AD server with the inserted credentials.

https://github.com/Adldap2/Adldap2-Laravel#auth-driver

**Comment by umefarooq** [comment]
Hi  @stevebauman  with auth driver i am not able to login i have followed all steps in documentation. with Adldap::authenticate its working fine

**Comment by umefarooq** [comment]
Hi, i have solved my problem, why we need to add admin_username or password in config file, can we use without admin_username or password.
