### ISSUE TITLE
how to get objectguid?

### ISSUE THREAD

**Issue by inyoungk** [Adldap2/Adldap2-Laravel#762]
- Laravel Version: 5.7
- Adldap2-Laravel Version: 6.x
- PHP Version: 7.1
- LDAP Type: ActiveDirectory

### Description:
Hi, I am importing the data from AD.
So user table that has been saved with data have objectguid data.
It is one of these. (23dd17c8-2d9b-4ec6-9f29-3e56b7e6d403)
these are not broken.

but when i get objectguid, the character was broken, 
I found the solution by googling. The answer was using "bin2hex" method.
after using that objectguid is not broken.

but there are not "-" and also the objectguid is not correct.
To change correct guid, i had to make some function.

```
function getObjectGUID($objectguid){

        $hex_guid=bin2hex($objectguid);
        $hex_guid_to_guid_str = '';
        for($k = 1; $k <= 4; ++$k) {
            $hex_guid_to_guid_str .= substr($hex_guid, 8 - 2 * $k, 2);
        }
        $hex_guid_to_guid_str .= '-';
        for($k = 1; $k <= 2; ++$k) {
            $hex_guid_to_guid_str .= substr($hex_guid, 12 - 2 * $k, 2);
        }
        $hex_guid_to_guid_str .= '-';
        for($k = 1; $k <= 2; ++$k) {
            $hex_guid_to_guid_str .= substr($hex_guid, 16 - 2 * $k, 2);
        }
        $hex_guid_to_guid_str .= '-' . substr($hex_guid, 16, 4);
        $hex_guid_to_guid_str .= '-' . substr($hex_guid, 20);

        return $hex_guid_to_guid_str;
    }

```

For get obejctguid, i have to do all this? Isn't there a simple way to get this?? :(

**Comment by stevebauman** [comment]
Hi @inyoungk,

You must use the `$user->getConvertedGuid()` method:

https://github.com/Adldap2/Adldap2/blob/c406c02b095022555dbad19b4b382ce4b31420af/src/Models/Model.php#L526-L538

Here's an example:

```php
$user = Adldap::search()->users()->find('John Doe');

$guid = $user->getConvertedGuid();
```
