### ISSUE TITLE
Change password encryption

### ISSUE THREAD

**Issue by MarcosRLeao** [Adldap2/Adldap2-Laravel#767]
- Laravel Version: 5.8
- Adldap2-Laravel Version: 6.0
- PHP Version: 7.2
- LDAP Type: 

Good Night!

I need to know how to change password encryption.

because I need to compare the password within the system, so that a logged in user like John for example, can not make a post in the name of Francisco.

![decript](https://user-images.githubusercontent.com/50677003/62256198-b3a7c280-b3d6-11e9-968f-1e88ceb543d0.png)

**Comment by stevebauman** [comment]
Hi @MarcosRLeao,

Simply create a `setPasswordAttribute()` mutator on your `User` model:

```php
class User extends Authenticatable
{
    public function setPasswordAttribute($password)
    {
        $this->attributes['password'] = bcrypt($password);
    }
```

This method will then be used for setting the users password upon logging into your application.

Keep in mind that by default a random string is used when an LDAP user logs into your application. If you want to retain the users password in your local web application, you need to turn on password sync via the `config/ldap_auth.php` config file:

https://adldap2.github.io/Adldap2-Laravel/#/auth/setup?id=sync

**Comment by MarcosRLeao** [comment]
Thank you so much!
It worked
