### ISSUE TITLE
User from API request (using axios, with auth:api middleware) has ´ldap´ property as null

### ISSUE THREAD

**Issue by SebastienDenooz** [Adldap2/Adldap2-Laravel#768]
### Situation:
- Laravel Version: 5.8
- Adldap2-Laravel Version: 6.0.7
- PHP Version: 7.3
- LDAP Type: ActiveDirectory

### Description:
When retrieving the authenticated user from an API request using AXIOS in a vue controller, the `Auth::user()` or `auth()->user()` return the connected user. But the `$user->ldap` property is null.

But when you put `{{auth()->user()->ldap}}` in a view, the result is not null but `DC=....,OU=....etc..`

### Question:
Is there a way to populate this `$user->ldap` property in API request context?

### Steps To Reproduce:
- Install default laravel
- Install passport, use ´\Laravel\Passport\Http\Middleware\CreateFreshApiToken::class´ for the web $middlewareGroups
- Install adldap2-laravel
- Configure the User model with traits:

```php
// ...
class User extends Authenticatable
{
    use HasApiTokens, Notifiable, HasLdapUser;
   // ...
}
```

- Configure a route in api.php:
```php
<?php

use Illuminate\Http\Request;

Route::middleware(['auth:api'])->group(function () {
     Route::resource('/teams','TeamController')->only(['index', 'show']);
});

```
- And the controller:
```php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use TheBoard\User;

class TeamController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user = Auth::user();
        dd($user->ldap);

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

}

```

- Fire request like this one:
`curl 'http://homestead.test/api/teams?format=json' -H 'Accept: application/json, text/plain, */*' -H 'Referer: http://homestead.test/' -H 'X-XSRF-TOKEN: XSRF_TOKEN_HERE_1234567890' -H 'X-CSRF-TOKEN: CSRF_TOKEN_HERE_1234567890' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.87 Safari/537.36' -H 'X-Requested-With: XMLHttpRequest' --compressed --insecure`

**Comment by stevebauman** [comment]
Hi @SebastienDenooz,

This is due to using the `token` driver. The `token` driver does not fire any events - while the `session` driver does, which is what Adldap2-Laravel hooks into to retrieve your logged in user from your configured directory.

If you need this, you will unfortunately need to bind it manually. You can do so by creating your own middleware and setting the property:

```php
use Adldap\Laravel\Facades\Adldap;

/**
 * Handle an incoming request.
 *
 * @param \Illuminate\Http\Request $request
 * @param \Closure                 $next
 *
 * @return mixed
 */
public function handle($request, Closure $next)
{
    if ($user = $request->user()) {
        $user->ldap = Adldap::findByGuid($user->objectguid);
    }
}
```
