### ISSUE TITLE
Having to include prefix with login

### ISSUE THREAD

**Issue by lukepolo** [Adldap2/Adldap2-Laravel#77]
When trying to login I have to add our domain in front to make it work 

protected function bindUsingCredentials($username, $password, $suffix = null)
....

$username = 'blah\\'.$username;

...

Any ideas how to fix this so its not required?

**Comment by stevebauman** [comment]
Can't you include it yourself manually?

```php
$prefix = 'ACME\\';

if (Adldap::authenticate($prefix.$username, $password)) {
    //
}
```

**Comment by lukepolo** [comment]
Was trying to use the regular auth method , I believe that would work
though

**Comment by stevebauman** [comment]
You can still perform the same thing using the included auth driver. Unfortunately this is something the developer will have to include since you can use different attributes for logging in through the configuration, and a prefix won't always be needed.

**Comment by lukepolo** [comment]
Actually you cant, because the method that goes into the auth looks up the user based on that info. My user doesn't have the prefix but is needed for the actual login part.

**Comment by stevebauman** [comment]
Yup you're right, apologies.

Are you not able to utilize the account suffix? If you specify a suffix for your domain then you won't need to use a prefix:

```php
// config/adldap.php
`account_suffix` => '@corp.acme.org',
```

**Comment by lukepolo** [comment]
The problem then becomes finding users with @corp.acme.org. but not all our users have that same suffix and some none at all (this is most likely an issue with our own server)

**Comment by stevebauman** [comment]
> The problem then becomes finding users with @corp.acme.org. but not all our users have that same suffix and some none at all (this is most likely an issue with our own server)

Ok, I'll implement a prefix option for authentication. Thanks for creating an issue about this!

**Comment by lukepolo** [comment]
Thanks , really appreciate that.

**Comment by stevebauman** [comment]
Added in `v6`:

https://github.com/Adldap2/Adldap2/commit/163c7baee696b2594d6eca2b1dfe721328365b16
