### ISSUE TITLE
Site Crashed After Composer Update - Logger

### ISSUE THREAD

**Issue by kellerisddev** [Adldap2/Adldap2-Laravel#773]
- Laravel Version: #5.8.31#
- Adldap2-Laravel Version: #6.0#
- PHP Version: #7.2#
- LDAP Type: Active Directory

### Description:
Performed a "Composer update" commandand now my site has crashed.  When I log in I am getting the following error message:

"Call to undefined method Adldap\Log\EventLogger::log()"

### Steps To Reproduce:

Nothing else changed except running a composer update command

**Comment by stevebauman** [comment]
Hi @kellerisddev,

What version of Adldap2-Laravel are you targeting in your composer.json file?

**Comment by stevebauman** [comment]
Also, please post the entire stack trace with any sensitive details omitted so I can help you track down what caused this.

I would also try running `composer dump-autoload` just to be sure.

**Comment by kellerisddev** [comment]
"adldap2/adldap2-laravel": "^6.0",

**Comment by kellerisddev** [comment]
`Symfony\Component\Debug\Exception\FatalThrowableError 
…\vendor\adldap2\adldap2\src\Adldap.php181
73
Adldap\Adldap Adldap\{closure}
…\vendor\adldap2\adldap2\src\Events\Dispatcher.php266
72
Adldap\Events\Dispatcher Adldap\Events\{closure}
…\vendor\adldap2\adldap2\src\Events\Dispatcher.php112
71
Adldap\Events\Dispatcher dispatch
…\vendor\adldap2\adldap2\src\Events\Dispatcher.php94
70
Adldap\Events\Dispatcher fire
…\vendor\adldap2\adldap2\src\Auth\Guard.php243
69
Adldap\Auth\Guard fireBindingEvent
…\vendor\adldap2\adldap2\src\Auth\Guard.php98
68
Adldap\Auth\Guard bind
…\vendor\adldap2\adldap2\src\Auth\Guard.php121
67
Adldap\Auth\Guard bindAsAdministrator
…\vendor\adldap2\adldap2\src\Connections\Provider.php234
66
Adldap\Connections\Provider connect
…\vendor\adldap2\adldap2-laravel\src\AdldapServiceProvider.php111
65
Adldap\Laravel\AdldapServiceProvider addProviders
…\vendor\adldap2\adldap2-laravel\src\AdldapServiceProvider.php68
64
Adldap\Laravel\AdldapServiceProvider Adldap\Laravel\{closure}
…\vendor\laravel\framework\src\Illuminate\Container\Container.php791
63
Illuminate\Container\Container build
…\vendor\laravel\framework\src\Illuminate\Container\Container.php671
62
Illuminate\Container\Container resolve
…\vendor\laravel\framework\src\Illuminate\Container\Container.php619
61
Illuminate\Container\Container make
…\vendor\laravel\framework\src\Illuminate\Foundation\Application.php767
60
Illuminate\Foundation\Application make
…\vendor\adldap2\adldap2-laravel\src\AdldapAuthServiceProvider.php55
59
Adldap\Laravel\AdldapAuthServiceProvider Adldap\Laravel\{closure}
…\vendor\laravel\framework\src\Illuminate\Container\Container.php791
58
Illuminate\Container\Container build
…\vendor\laravel\framework\src\Illuminate\Container\Container.php671
57
Illuminate\Container\Container resolve
…\vendor\laravel\framework\src\Illuminate\Container\Container.php619
56
Illuminate\Container\Container make
…\vendor\laravel\framework\src\Illuminate\Foundation\Application.php767
55
Illuminate\Foundation\Application make
…\vendor\laravel\framework\src\Illuminate\Container\Container.php1233
54
Illuminate\Container\Container offsetGet
…\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php175
53
Illuminate\Support\Facades\Facade resolveFacadeInstance
…\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php144
52
Illuminate\Support\Facades\Facade getFacadeRoot
…\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php231
51
Illuminate\Support\Facades\Facade __callStatic
…\vendor\adldap2\adldap2-laravel\src\Listeners\BindsLdapUserModel.php33
50
Adldap\Laravel\Listeners\BindsLdapUserModel handle
…\vendor\laravel\framework\src\Illuminate\Events\Dispatcher.php366
49
 call_user_func_array
…\vendor\laravel\framework\src\Illuminate\Events\Dispatcher.php366
48
Illuminate\Events\Dispatcher Illuminate\Events\{closure}
…\vendor\laravel\framework\src\Illuminate\Events\Dispatcher.php196
47
Illuminate\Events\Dispatcher dispatch
…\vendor\laravel\framework\src\Illuminate\Auth\SessionGuard.php618
46
Illuminate\Auth\SessionGuard fireAuthenticatedEvent
…\vendor\laravel\framework\src\Illuminate\Auth\SessionGuard.php132
45
Illuminate\Auth\SessionGuard user
…\vendor\laravel\framework\src\Illuminate\Auth\GuardHelpers.php60
44
Illuminate\Auth\SessionGuard check
…\vendor\laravel\framework\src\Illuminate\Auth\Middleware\Authenticate.php62
43
Illuminate\Auth\Middleware\Authenticate authenticate
…\vendor\laravel\framework\src\Illuminate\Auth\Middleware\Authenticate.php41
42
Illuminate\Auth\Middleware\Authenticate handle
…\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php163
41
Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
…\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php53
40
Illuminate\Routing\Pipeline Illuminate\Routing\{closure}
…\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\VerifyCsrfToken.php75
39
Illuminate\Foundation\Http\Middleware\VerifyCsrfToken handle
…\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php163
38
Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
…\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php53
37
Illuminate\Routing\Pipeline Illuminate\Routing\{closure}
…\vendor\laravel\framework\src\Illuminate\View\Middleware\ShareErrorsFromSession.php49
36
Illuminate\View\Middleware\ShareErrorsFromSession handle
…\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php163
35
Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
…\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php53
34
Illuminate\Routing\Pipeline Illuminate\Routing\{closure}
…\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php56
33
Illuminate\Session\Middleware\StartSession handle
…\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php163
32
Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
…\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php53
31
Illuminate\Routing\Pipeline Illuminate\Routing\{closure}
…\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse.php37
30
Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse handle
…\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php163
29
Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
…\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php53
28
Illuminate\Routing\Pipeline Illuminate\Routing\{closure}
…\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\EncryptCookies.php66
27
Illuminate\Cookie\Middleware\EncryptCookies handle
…\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php163
26
Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
…\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php53
25
Illuminate\Routing\Pipeline Illuminate\Routing\{closure}
…\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php104
24
Illuminate\Pipeline\Pipeline then
…\vendor\laravel\framework\src\Illuminate\Routing\Router.php682
23
Illuminate\Routing\Router runRouteWithinStack
…\vendor\laravel\framework\src\Illuminate\Routing\Router.php657
22
Illuminate\Routing\Router runRoute
…\vendor\laravel\framework\src\Illuminate\Routing\Router.php623
21
Illuminate\Routing\Router dispatchToRoute
…\vendor\laravel\framework\src\Illuminate\Routing\Router.php612
20
Illuminate\Routing\Router dispatch
…\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php176
19
Illuminate\Foundation\Http\Kernel Illuminate\Foundation\Http\{closure}
…\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php30
18
Illuminate\Routing\Pipeline Illuminate\Routing\{closure}
…\vendor\fideloper\proxy\src\TrustProxies.php57
17
Fideloper\Proxy\TrustProxies handle
…\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php163
16
Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
…\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php53
15
Illuminate\Routing\Pipeline Illuminate\Routing\{closure}
…\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TransformsRequest.php21
14
Illuminate\Foundation\Http\Middleware\TransformsRequest handle
…\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php163
13
Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
…\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php53
12
Illuminate\Routing\Pipeline Illuminate\Routing\{closure}
…\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TransformsRequest.php21
11
Illuminate\Foundation\Http\Middleware\TransformsRequest handle
…\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php163
10
Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
…\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php53
9
Illuminate\Routing\Pipeline Illuminate\Routing\{closure}
…\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\ValidatePostSize.php27
8
Illuminate\Foundation\Http\Middleware\ValidatePostSize handle
…\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php163
7
Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
…\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php53
6
Illuminate\Routing\Pipeline Illuminate\Routing\{closure}
…\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode.php62
5
Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode handle
…\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php163
4
Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
…\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php53
3
Illuminate\Routing\Pipeline Illuminate\Routing\{closure}
…\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php104
2
Illuminate\Pipeline\Pipeline then
…\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php151
1
Illuminate\Foundation\Http\Kernel sendRequestThroughRouter
…\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php116
0
Illuminate\Foundation\Http\Kernel handle
…\public\index.php55`

**Comment by stevebauman** [comment]
Strange... `EventLogger::log()` is definitely a [method](https://github.com/Adldap2/Adldap2/blob/beb3c9cc28de752d6c3b0221605035659eccc42e/src/Log/EventLogger.php#L31-L45).

Can you run `composer dump-autoload` and try again?

Also, is this happening on only authentication attempts?

**Comment by kellerisddev** [comment]
Thank you.  Just ran composer dump-autoload again.  Here is the results:

`Generating optimized autoload files> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi
Discovered Package: adldap2/adldap2-laravel
Discovered Package: barryvdh/laravel-dompdf
Discovered Package: beyondcode/laravel-dump-server
Discovered Package: fideloper/proxy
Discovered Package: intervention/image
Discovered Package: lab404/laravel-impersonate
Discovered Package: laravel/tinker
Discovered Package: maddhatter/laravel-fullcalendar
Discovered Package: nesbot/carbon
Discovered Package: nunomaduro/collision
Discovered Package: spatie/laravel-permission
Discovered Package: webklex/laravel-imap
Discovered Package: webpatser/laravel-uuid
Package manifest generated successfully.                                                                                                                                                                                                                                             Generated optimized autoload files containing 14018 classes`

This laravel install requires users to be logged in so I have the auth middleware on all routes.

It appears to be attached to the authentication attempts only

**Comment by stevebauman** [comment]
Ok, do you have logging enabled in your `config/ldap.php` config file?

**Comment by kellerisddev** [comment]
I do not, I didn't see that as an option when I installed and configured.

**Comment by stevebauman** [comment]
Did you upgrade Adlda2-Laravel from `v5.0`? Or has this application been using `v6.0` from the beginning?

**Comment by kellerisddev** [comment]
I honestly don't remember what version I was using when i installed it.  It has been at least 6 months ago.

**Comment by kellerisddev** [comment]
Oh, wait, it looks like I was already on 6:

`failed to open stream: HTTP request failed! 
https://repo.packagist.org could not be fully loaded, package information was loaded from the local cache and may be out of date
Updating dependencies (including require-dev)
Package operations: 6 installs, 50 updates, 1 removal
  - Removing symfony/contracts (v1.0.2)
  - Updating symfony/polyfill-ctype (v1.11.0 => v1.12.0): Downloading (100%)         
  - Updating vlucas/phpdotenv (v3.3.3 => v3.4.0): Loading from cache
  - Updating symfony/css-selector (v4.2.4 => v4.3.3): Loading from cache
  - Updating symfony/polyfill-php72 (v1.11.0 => v1.12.0): Downloading (100%)         
  - Updating symfony/polyfill-mbstring (v1.11.0 => v1.12.0): Downloading (100%)         
  - Updating symfony/var-dumper (v4.2.4 => v4.3.3): Loading from cache
  - Updating symfony/routing (v4.2.4 => v4.3.3): Loading from cache
  - Updating symfony/process (v4.2.4 => v4.3.3): Loading from cache
  - Updating symfony/polyfill-intl-idn (v1.11.0 => v1.12.0): Downloading (100%)         
  - Installing symfony/mime (v4.3.3): Loading from cache
  - Updating symfony/http-foundation (v4.2.4 => v4.3.3): Loading from cache
  - Installing symfony/event-dispatcher-contracts (v1.1.5): Loading from cache
  - Updating symfony/event-dispatcher (v4.2.4 => v4.3.3): Loading from cache
  - Updating symfony/debug (v4.2.4 => v4.3.3): Loading from cache
  - Installing symfony/polyfill-php73 (v1.12.0): Downloading (100%)         
  - Updating symfony/http-kernel (v4.2.4 => v4.3.3): Loading from cache
  - Updating symfony/finder (v4.2.4 => v4.3.3): Loading from cache
  - Installing symfony/service-contracts (v1.1.5): Loading from cache
  - Updating symfony/console (v4.2.4 => v4.3.3): Loading from cache
  - Updating symfony/polyfill-iconv (v1.11.0 => v1.12.0): Downloading (100%)         
  - Updating doctrine/lexer (v1.0.1 => 1.1.0): Loading from cache
  - Updating egulias/email-validator (2.1.7 => 2.1.10): Loading from cache
  - Updating swiftmailer/swiftmailer (v6.2.0 => v6.2.1): Loading from cache
  - Updating opis/closure (3.1.6 => 3.3.1): Loading from cache
  - Installing symfony/translation-contracts (v1.1.5): Loading from cache
  - Updating symfony/translation (v4.2.4 => v4.3.3): Loading from cache
  - Updating nesbot/carbon (2.16.2 => 2.22.3): Downloading (100%)         
  - Updating league/flysystem (1.0.46 => 1.0.53): Loading from cache
  - Updating erusev/parsedown (v1.7.2 => 1.7.3): Loading from cache
  - Updating laravel/framework (v5.8.8 => v5.8.31): Downloading (100%)         
  - Updating ralouphie/getallheaders (2.0.5 => 3.0.3): Loading from cache
  - Updating guzzlehttp/psr7 (1.5.2 => 1.6.1): Loading from cache
  - Updating tightenco/collect (v5.8.8 => v5.8.31): Downloading (100%)         
  - Updating nikic/php-parser (v4.2.1 => v4.2.3): Downloading (100%)         
  - Updating adldap2/adldap2 (v10.0.6 => v10.0.11): Downloading (100%)         
  - Updating adldap2/adldap2-laravel (v6.0.2 => v6.0.7): Downloading (100%)         
  - Updating fideloper/proxy (4.1.0 => 4.2.0): Loading from cache
  - Updating intervention/image (2.4.2 => 2.5.0): Downloading (100%)         
  - Updating lab404/laravel-impersonate (1.3.0 => 1.4.0): Downloading (100%)         
  - Updating laravel/tinker (v1.0.8 => v1.0.9): Loading from cache
  - Updating spatie/laravel-permission (2.36.1 => 2.37.0): Downloading (100%)         
  - Updating webklex/laravel-imap (1.4.0 => 1.4.2): Downloading (100%)         
  - Updating beyondcode/laravel-dump-server (1.2.2 => 1.3.0): Downloading (100%)         
  - Updating filp/whoops (2.3.1 => 2.5.0): Downloading (100%)         
  - Updating mockery/mockery (1.2.2 => 1.2.3): Downloading (100%)         
  - Updating sebastian/exporter (3.1.0 => 3.1.1): Downloading (100%)         
  - Updating sebastian/environment (4.1.0 => 4.2.2): Loading from cache
  - Updating phpunit/php-timer (2.1.1 => 2.1.2): Loading from cache
  - Updating theseer/tokenizer (1.1.0 => 1.1.3): Loading from cache
  - Updating phpunit/php-token-stream (3.0.1 => 3.1.0): Loading from cache
  - Updating phpdocumentor/reflection-docblock (4.3.0 => 4.3.1): Loading from cache
  - Updating phpspec/prophecy (1.8.0 => 1.8.1): Loading from cache
  - Updating myclabs/deep-copy (1.8.1 => 1.9.3): Downloading (100%)         
  - Updating phpunit/phpunit (7.5.8 => 7.5.14): Loading from cache
  - Updating paragonie/sodium_compat (v1.9.1 => v1.10.1): Downloading (100%)         
  - Installing webpatser/laravel-uuid (3.0.2): Downloading (100%)         
symfony/event-dispatcher-contracts suggests installing psr/event-dispatcher
symfony/service-contracts suggests installing symfony/service-implementation
Writing lock file
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi
Discovered Package: adldap2/adldap2-laravel
Discovered Package: barryvdh/laravel-dompdf
Discovered Package: beyondcode/laravel-dump-server
Discovered Package: fideloper/proxy
Discovered Package: intervention/image
Discovered Package: lab404/laravel-impersonate
Discovered Package: laravel/tinker
Discovered Package: maddhatter/laravel-fullcalendar
Discovered Package: nesbot/carbon
Discovered Package: nunomaduro/collision
Discovered Package: spatie/laravel-permission
Discovered Package: webklex/laravel-imap
Discovered Package: webpatser/laravel-uuid
Package manifest generated successfully.`

**Comment by stevebauman** [comment]
Ok, can you validate that the `Adldap\Log\EventLogger` class exists in your applications `vendor\adldap2\adldap2\Log` folder?

**Comment by kellerisddev** [comment]
I see EventLogger in the `vendor\adldap2\adldap2\src\Log` folder

**Comment by stevebauman** [comment]
Very strange... Logging was added in `v6.0`, so you've had the logging feature already for a while.

What else changed with your application prior to running `composer update`?

**Comment by kellerisddev** [comment]
I attempted to run a composer install of another package and found a error 

`composer require "webpatser/laravel-uuid:^3.0"
The "https://repo.packagist.org/packages.json" file could not be downloaded: SSL: An existing connection was forcibly closed by the remote host.

send of 158 bytes failed with errno=10054 An existing connection was forcibly closed by the remote host.

failed to open stream: HTTP request failed! 
https://repo.packagist.org could not be fully loaded, package information was loaded from the local cache and may be out of date
./composer.json has been updated
Loading composer repositories with package information`

**Comment by kellerisddev** [comment]
I renamed the config/ldap.php and config/ldap_auth.php files and I was able to log in again.  Does that mean that there is an issue with those files or that without them I am not using LDAP?

**Comment by stevebauman** [comment]
Yeah something is going on with your connectivity with Packagist. I would delete the entire `vendor` folder and try complete reinstall using `composer install`.

Does the server / host where you have this app running have access to the internet?

**Comment by stevebauman** [comment]
> I renamed the config/ldap.php and config/ldap_auth.php files

What did you rename them from?

**Comment by kellerisddev** [comment]
I renamed them to ldap_old.php and ldap_auth_old.php and left them in the config directory

**Comment by kellerisddev** [comment]
I tried running these commands:

php artisan vendor:publish --provider=Adldap\Laravel\AdldapServiceProvider
php artisan vendor:publish --provider=Adldap\Laravel\AdldapAuthServiceProvider

No new files were generated

**Comment by stevebauman** [comment]
Does the server / host where you have this app running have access to the internet?

**Comment by kellerisddev** [comment]
Yes, it does.  I was able to ping google.com

**Comment by stevebauman** [comment]
Ok, delete the `vendor` folder and re-download all packages via `composer install`. Make sure no errors are encountered while downloading the packages. Afterwards, try logging in again and see if you encounter the same issue.

Let me know!

**Comment by kellerisddev** [comment]
Ok, carried out your instructions and I can log in again.

I deleted the ldap.php and ldap_auth.php files from the config folder and ran the commands below:

php artisan vendor:publish --provider=Adldap\Laravel\AdldapServiceProvider
php artisan vendor:publish --provider=Adldap\Laravel\AdldapAuthServiceProvider

I still don't see the new ldap.php and ldap_auth.php files, so how can I be using LDAP to successfully login?

**Comment by stevebauman** [comment]
When you run `php artisan vendor:publish` alone, do you see those service providers as selectable options?

> I still don't see the new ldap.php and ldap_auth.php files, so how can I be using LDAP to successfully login?

Have you configured it via your `.env` file?

**Comment by kellerisddev** [comment]
No, I don't have anything for LDAP configured in my .env file.

I just went back to the documentation and see that the quotes were missing from the provider name

php artisan vendor:publish --provider=Adldap\Laravel\AdldapServiceProvider

supposed to be 

php artisan vendor:publish --provider="Adldap\Laravel\AdldapServiceProvider"

**Comment by stevebauman** [comment]
> No, I don't have anything for LDAP configured in my .env file.

Oh so you haven't configured Adldap2-Laravel at all yet?

> I just went back to the documentation and see that the quotes were missing from the provider name

Did the config files publish correctly and are you receiving any errors?

**Comment by kellerisddev** [comment]
Believe that all got it working again.

Thank you very much

**Comment by stevebauman** [comment]
Great, no problem! Thanks for your quick responses and for closing the issue out.
