### ISSUE TITLE
Is there some up-to-date tutorial?

### ISSUE THREAD

**Issue by getJv** [Adldap2/Adldap2-Laravel#776]
Info: php7.2, laravel 5.8.

Guys it is impossible make Adldap2-Laravel to working here. I already did the tutorial documentation but nothing is working at all. Nothing to DatabaseUserProvider or NoDatabaseUserProvider.

Someone else is with dificults too? or someone has a up-to-date tutorial?

**Comment by stevebauman** [comment]
Hi @getJv,

Hard to help without any information about directory or configuration.

Are you receiving exceptions? What LDAP server type are you connecting to (ActiveDirectory, OpenLDAP etc.)? Are you able to connect and query your LDAP server at all?

**Comment by getJv** [comment]
Hey Steve, Thanks for your time.

I already figure out where the problem were.  
Our AD has two kind of users. 
One of them allows the auth without the prefix, only require the username and pass.

To other case i need to pass the domain company as prefix, like Domain\username.

Went needed to use the manually  LDAP connection (the-old-way ) to realize this config problem.

The 'account_prefix' attibute has saved my life. :1st_place_medal:

**Comment by stevebauman** [comment]
Awesome, thanks for following up @getJv! Really appreciate it :heart:

**Comment by shabeebrizvi** [comment]
@getJv  It's been almost a week trying to find out what is wrong with my code. Wasted my thanksgiving too.... LOL Can you please share the code. I am new to programming and ad as well.

**Comment by shabeebrizvi** [comment]
@stevebauman  I followed this link https://github.com/jotaelesalinas/laravel-simple-ldap-auth and for adminless on openldap is works perfectly. But when i am trying to implement the same it wont

BTW i did change the userprincipalname with sAMAccountName. 

I WOULD REALLY APPRECIATE YOUR HELP!!!

**Comment by getJv** [comment]
Hey @shabeebrizvi at that time i wrote a post to register my knowlage.

[here is the post](https://medium.com/@jhonatanvinicius/get-adldap-laravel-in-4-steps-eccad1ac8563)

Be aware about to info prefix or suffix. (at you ldap.php file)
