### ISSUE TITLE
Unsupported Laravel 6.0.0

### ISSUE THREAD

**Issue by hihuangwei** [Adldap2/Adldap2-Laravel#777]
- Laravel Version: #.#
- Adldap2-Laravel Version: #.#
- PHP Version: #.#
- LDAP Type:

**Comment by stevebauman** [comment]
Thanks @hihuangwei! I'm working on this right now.

**Comment by stevebauman** [comment]
Done - [v6.0.8](https://github.com/Adldap2/Adldap2-Laravel/releases/tag/v6.0.8) has just been released.

Thanks!
