### ISSUE TITLE
Show all users on select field

### ISSUE THREAD

**Issue by netopvh** [Adldap2/Adldap2-Laravel#78]
Hello, I would list all the AD users in a select field. I as follows gave an error.

```php
$users = Auth::user()->adldapUser->select('mailnickname','displayname');

return view('modules.lancamentos.index', compact('users'));
```

Can someone help me

**Comment by netopvh** [comment]
I tried as follows

```php
$users = Adldap::users()->search()->select(['cn','displayname'])->all();
```
more gave an error

```php
Call to undefined method Adldap\Query\Builder::all()
```

**Comment by stevebauman** [comment]
> $users = Adldap::users()->search()->select(['cn','displayname'])->all();

Should be:

```php
$users = Adldap::users()->search()->select(['cn','displayname'])->get();
```

> $users = Auth::user()->adldapUser->select('mailnickname','displayname');

This is incorrect usage. The `adldapUser` property is a **single** Adldap User model instance that is bound to the currently authenticated user. You cannot query off of this model.

**Comment by netopvh** [comment]
I as follows:

```php
$users = Adldap::users()->search()->select(['cn','displayname'])->get();

return view('modules.lancamentos.index', compact('users'));
```

My view

```php
{!! Form::select('id_user', $users, null, ['class' => 'form-control', 'placeholder' => 'Select...', 'id' => 'test']) !!}
```

show this error.

```php
htmlentities() expects parameter 1 to be string, object given (View: E:\Projetos\PHP\scac\resources\views\modules\lancamentos\forms\_search.blade.php) (View: E:\Projetos\PHP\scac\resources\views\modules\lancamentos\forms\_search.blade.php)
```

I could tell me why is this happening ?

**Comment by stevebauman** [comment]
Your passing an array of Adldap model objects to a form object. The `select()` method does not perform the same collection method as `pluck()` or `lists()` (which I'm assuming you're intending to perform.

Try:

```php
$users = Adldap::users()->search()->select(['cn','displayname'])->get()->toArray();

$names = [];

foreach ($users as $user) {
   $names[$user->cn[0]] = $user->displayname[0];
}

return view('modules.lancamentos.index', compact('names'));
```
