### ISSUE TITLE
Search returns no results

### ISSUE THREAD

**Issue by Kerneltroll** [Adldap2/Adldap2-Laravel#783]
- Laravel Version: 6
- Adldap2-Laravel Version: 5
- PHP Version: 7.2.0
- LDAP Type: ActiveDirectory

### Description:
When searching LDAP it returns with no results.

Base DN is DC=boxerman,DC=com 
which is set in:
`
'base_dn' => env('LDAP_BASE_DN', 'DC=boxerman,DC=com'),
`
All users are located in the Users OU

I search for users i created, such as admin, boxerman, test, tester 
I am unable to locate these :( 

When I search with findByDn i get
`
false
`
in browser, i can not see any logs to show errors.

### Steps To Reproduce:
`
$user = Adldap::search()->users()->whereEnabled()->get();
dd($user);
`

Returns:

`
Collection {#270 ▼
  #items: []
}
`

This also happens if i try to search groups.

Where am I going wrong? Maybe im over tired! lol

**Comment by stevebauman** [comment]
Hi @Kerneltroll,

Can you post your entire config with sensitive details omitted? Do you have follow referrals enabled?

Also, for your configured username, are you using a userPrincipalName or distinguishedname of the account you want to bind with?

**Comment by Kerneltroll** [comment]
Morning buddy,

Full ldap.php

`
<?php

return [

    'logging' => env('LDAP_LOGGING', false),

    'connections' => [

        'default' => [

            'auto_connect' => env('LDAP_AUTO_CONNECT', true),

            'connection' => Adldap\Connections\Ldap::class,

            'settings' => [

                'schema' => Adldap\Schemas\ActiveDirectory::class,

                'account_prefix' => env('LDAP_ACCOUNT_PREFIX', ''),

                'account_suffix' => env('LDAP_ACCOUNT_SUFFIX', '@boxerman.com'),

                'hosts' => explode(' ', env('LDAP_HOSTS', 'boxerman.com')),

                'port' => env('LDAP_PORT', 389),

                'timeout' => env('LDAP_TIMEOUT', 5),

                'base_dn' => env('LDAP_BASE_DN', 'DC=boxerman,DC=com'),

                'username' => env('admin@boxerman.com'),
                'password' => env('thegame'),

                'follow_referrals' => false,

                'use_ssl' => env('LDAP_USE_SSL', false),
                'use_tls' => env('LDAP_USE_TLS', false),

            ],

        ],

    ],

];

`

Hope this helps!

**Comment by stevebauman** [comment]
Ok remove your account suffix and try retrieving users again. Let me know if it works!

**Comment by Kerneltroll** [comment]
I've removed it (new settings config): 

`
            'settings' => [

                'schema' => Adldap\Schemas\ActiveDirectory::class,

                'account_prefix' => env('LDAP_ACCOUNT_PREFIX', ''),

                'account_suffix' => env('LDAP_ACCOUNT_SUFFIX', ''),

                'hosts' => explode(' ', env('LDAP_HOSTS', 'boxerman.com')),

                'port' => env('LDAP_PORT', 389),

                'timeout' => env('LDAP_TIMEOUT', 5),

                'base_dn' => env('LDAP_BASE_DN', 'DC=boxerman,DC=com'),

                'username' => env('admin@boxerman.com'),
                'password' => env('thecakeisalie'),

                'follow_referrals' => false,

                'use_ssl' => env('LDAP_USE_SSL', false),
                'use_tls' => env('LDAP_USE_TLS', false),
`

However when i run the following:
`
$user = Adldap::search()->users()->whereEnabled()->get(); dd($user);
`

It returns:
`
Collection {#270 ▼
  #items: []
}
`

**Comment by Kerneltroll** [comment]
Also worth noting:
`
C:\>dsquery user -name admin*
"CN=Administrator,CN=Users,DC=boxerman,DC=com"
"CN=Admin Admin,CN=Users,DC=boxerman,DC=com"
`

**Comment by Kerneltroll** [comment]
Fixed this:

For people having this issue, because i did not set anything in env i had to change the ldap.php a little:

`
  'username' => env('LDAP_USERNAME', 'admin@boxerman.com'),
                'password' => env('LDAP_PASSWORD', 'imstupid'),
`

Note the LDAP_USERNAME and LDAP_PASSWORD.

Hope nobody runs into the mind block i had!!
