### ISSUE TITLE
IIS Windows Authentication for LDAP connection instead of Username/Password.

### ISSUE THREAD

**Issue by oneilwebmaster** [Adldap2/Adldap2-Laravel#785]
- Laravel Version: 5.8.26
- Adldap2-Laravel Version: 10.0.11
- PHP Version: 7.2
- LDAP Type: ActiveDirectory

### Description:

Our IT staff would like us to not have the password for the account used to connect to AD and make changes. Is there any way to simply connect/bind without supplying credentials and instead use the IIS/application pool identity user. I have already tested connecting this way via normal PHP ldap_bind and it works, but it does not work when I try to do: $adldap->connect('default'); and then search. I have checked providing credentials directly also does work, but that's what I'm trying to get past doing.

**Comment by stevebauman** [comment]
Hi @oneilwebmaster,

> Is there any way to simply connect/bind without supplying credentials and instead use the IIS/application pool identity user. I have already tested connecting this way via normal PHP ldap_bind and it works

How did you go about doing this? To my knowledge, the only way to do this would be to setup NTLM authentication on your IIS site - but this doesn't pass the users password to PHP, only the username.

**Comment by oneilwebmaster** [comment]
Unfortunately I spoke too soon! I had read [this stackoverflow](https://stackoverflow.com/questions/25039083/php-ldap-binding-ad-with-the-servers-user-account) and tried doing an ldap_bind but apparently even though it will bind like that, it's anonymous and ldap_search will not work. That's a shame. Seems like there isn't any other way to get around having the username/password available in the .env (or some file). You can probably close this unless you have another idea.

**Comment by stevebauman** [comment]
Ah I figured as much. The only idea I have for your issue would be to encrypt the users LDAP password in their session, and bind to your LDAP server on every authenticated user requests.

Technically this could still be decrypted by the site owner though.
