### ISSUE TITLE
Crazy php builtin empty() function return value on adldap\user attribute

### ISSUE THREAD

**Issue by flartet** [Adldap2/Adldap2-Laravel#786]
- Laravel Version: 5.8
- Adldap2-Laravel Version: 6.0
- PHP Version: 7.3
- LDAP Type: OpenLDAP

### Description:
Hi,
I'll try to be able to explain the problem (which might not be adldap2 related, not sure at this point).

**Problem is : When I get an Adldap\User attribute, the empty() function on this attribute returns true even if the attribute itself is set.**

My full die/dump test is this one 

`dd([0 => "student"], empty([0 => "student"]), $this->getAdldapUser()->$attr, empty($this->getAdldapUser()->$attr), $this->username, empty($this->username));`

I also tried with a normal name, not a variable for $attr in $this->getAdldapUser()->$attr 
So, it's (don't know how to give a screenshot of the dd() ) :
1. a manually created array
2. is that array empty ? (false)
3. an attr on the adldap user, which is exactly the array on dump
4. is that attr return value empty ? (**true**) ???
5. let's display a eloquent value on the current User Model (username displayed fine)
6. is that username empty() (of course false)

So, the question is why the hell empty() considers the adldap\user -> attr as empty when it's not
Can it be related with the way attributes are retrieved ?
empty() is supposed to work well with functions returns unlike isset()

Thanks a lot for the reading.

**Comment by stevebauman** [comment]
Fixed in the root Adldap2 repository. Thanks for the report!

**Comment by stevebauman** [comment]
Released [v10.1.1](https://github.com/Adldap2/Adldap2/releases/tag/v10.1.1).
