### ISSUE TITLE
User Cleanup

### ISSUE THREAD

**Issue by nerdalertdk** [Adldap2/Adldap2-Laravel#787]
- Laravel Version: 5.8
- Adldap2-Laravel Version: 6.0
- PHP Version: 7.2
- LDAP Type: FreeIPA

### Description:

So I had a weird problems that I traced back to inconsistent between our FreeIPA and the Laravel database.

We had 50 users that was deleted in our FreeIPA and created again. (new uid and guid) but same mail adresse. In my laravel database emails must be unique, this resulted in we could not import the 50 "new" users because there old ghost account was still in the database.

How do you keep the to databases synced ?

Create an AD user.
Sync with laravel
Delete the AD user
Create AD user with same email address
Sync with laravel
Get "error" 0 synced.

**Comment by stevebauman** [comment]
Hi @nerdalertdk,

The `import` command will never delete users in your database - this could be very destructive if someone configured Adldap2-Laravel incorrectly.

In your case, I would extend the built in console command, override the `import()` and `save()` method, add each successfully imported users GUID into an array, and then query your database users whom do not have the GUID and delete them. I'll show you an example.

Run the following:

```
php artisan make:command LdapImport
```

Then in the generated command:

```php
<?php

namespace App\Console\Commands;

use Adldap\Models\User;
use App\User as AppUser;
use Illuminate\Database\Eloquent\Model;
use Adldap\Laravel\Commands\Console\Import as BaseImport;

class LdapImport extends BaseImport
{
    /**
     * The synchronized user guids.
     *
     * @var array
     */
    protected $guids = [];

    /**
     * {@inheritDoc}
     */
    public function import(array $users = []) : int
    {
        $imported = parent::import($users);

        AppUser::query()->whereNotIn('objectguid', $this->guids)->delete();

        return $imported;
    }

    /**
     * {@inheritDoc}
     */
    protected function save(User $user, Model $model) : bool
    {
        $wasImported = parent::save($user, $model);

        $this->guids[] = $user->getObjectGuid();

        return $wasImported;
    }
}
```

Insert the command into your `App\Console\Kernel.php` file. This will override the `adldap:import` command with your own instance.

If your users have dependencies in your application that must be deleted (such as foreign keys), you may need to change the `AppUser::query()` to retrieve each user and delete them individually so eloquent events are fired:

```php
AppUser::query()->whereNotIn('objectguid', $this->guids)->get()->each->delete();
```

Please test this command prior to placing it into production, but it should be a good starting point so you can synchronize your objects effectively!

**Comment by stevebauman** [comment]
Also keep in mind that the `save()` method only returns `true` when the user was **imported** - meaning it has not yet existed before in your database. This method returns false if the user already exists in your database.

An exception will be generated if synchronization fails, so you can be sure that the guids you add to the `$guids` property have been synchronized.

**Comment by nerdalertdk** [comment]
Thanks, only change i did was this.

```
AppUser::withTrashed()->whereNotIn('objectGuid', $this->guids)->forceDelete();
```
