### ISSUE TITLE
Filter based on enabled/disabled status

### ISSUE THREAD

**Issue by nspaul** [Adldap2/Adldap2-Laravel#788]
- Laravel Version: 5.8
- Adldap2-Laravel Version: 6.0.8
- PHP Version: 7.3.8
- LDAP Type: ActiveDirectory

### Description:
I would like to be able to filter a search query based on whether a user is disabled or enabled. I know I can do something like this to filter on, say, the name:
`$users = $ldap->search()->users()->where('cn', 'starts_with', 'Paul')->get();`

And I could include all users by omitting the `where` clause, but then I'd have to deal with pagination. I'd love for the initial query to handle the filtering for me, if possible. Then when I feed my `$users` array to the blade template, it only has users that I care to deal with.

**Comment by stevebauman** [comment]
Hi @nspaul,

This is actually already built into the [query builder](https://github.com/Adldap2/Adldap2/blob/7e9f66413c718597f0afa79d6e7ad3cf22123998/src/Query/Builder.php#L1221-L1239) using `whereEnabled()` and `whereDisabled()`.

```php
$enabledUsers = $ldap->search()->users()->whereEnabled()->get();

$disabledUsers = $ldap->search()->users()->whereDisabled()->get();
````

Hope this answers your question!
