### ISSUE TITLE
php artisan vendor:publish --tag="adldap" FYI

### ISSUE THREAD

**Issue by tarreislam** [Adldap2/Adldap2-Laravel#79]
$ php artisan vendor:publish --tag="adlap"
Nothing to publish for tag [adlap].

$ php artisan vendor:publish
Copied File [\vendor\adldap2\adldap2-laravel\src\Config\config.php] To [\config\adldap.php]
Publishing complete for tag []!

**Comment by stevebauman** [comment]
Not sure what the issue is here? The spelling for the tag `adldap` is incorrectly spelled (`adlap`).

**Comment by tarreislam** [comment]
I am sorry, im pretty sure i copied both directly from the page, but apperently not! thank you

**Comment by stevebauman** [comment]
No problem at all!
