### ISSUE TITLE
Assign Roles/Permissions with Spatie Laravel Permission on Import

### ISSUE THREAD

**Issue by kellerisddev** [Adldap2/Adldap2-Laravel#792]
- Laravel Version: #5.8#
- Adldap2-Laravel Version: #6.0#
- PHP Version: #7.1.3#
- LDAP Type: ActiveDirectory

### Description:

I am using the AdLDAP2-Laravel and Spatie Laravel-Permissions and I would like to know if there is a way that I can map users to specific roles/permissions upon bulk import using the import command?

Can this be done with an override?

I can't figure out what file or function I should be looking at.

**Comment by stevebauman** [comment]
Hi @kellerisddev,

This is absolutely possible. I would use an event listener and listen on the `Adldap\Laravel\Events\Synchronized` event, as this event includes the saved Laravel database model and your LDAP user model:

```php
<?php

namespace App\Listeners;

use App\Role;
use Adldap\Laravel\Events\Synchronized;

class AssignUserRoles
{
    /**
     * Handle the event.
     *
     * @param Synchronized $event
     *
     * @return void
     */
    public function handle(Synchronized $event)
    {
        if ($this->user->inGroup('Administrators') {
            $adminRole = Role::firstOrFail(['name' => 'administrator']);

            $this->model->roles()->attach($adminRole);
        }
    }
}
```

You'll definitely want to modify the above listener for you own use, but it should get you started!

**Comment by kellerisddev** [comment]
Hi Steve,

I am just now following up on this and I have never used Event Listeners in Laravel before.  I have implemented the following in a Listener called ADSyncRoles

I ran the command `php artisan make:listener` and named it  ADSyncRoles

`
namespace App\Listeners;

use App\AdRole;
use Illuminate\Support\Facades\Log;

use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;

use Adldap\Laravel\Events\Synchronized;

use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Contracts\Queue\ShouldQueue;

class ADSyncRoles
{
        
    public function handle(Synchonrized $event)
    {
        Log::info("User '{$event->user->getCommonName()}' is being synced with Laravel.");
    }

}
`

I have also added the following to my EventServiceProvider.php file:

`  protected $listen = [
             'Adldap\Laravel\Events\Imported' => [
            'App\Listeners\ADSyncRoles',
        ],      
    ];`

Now when I run `php artisan adldap:import` from the command line I do not see anything logging.

Am I missing something

**Comment by kellerisddev** [comment]
Nevermind, I wasn't passing the filter to the console command on import.  Working now. Thanks
