### ISSUE TITLE
Cannot retrieve data with NoDatabaseUserProvider

### ISSUE THREAD

**Issue by Haziqasyraff** [Adldap2/Adldap2-Laravel#799]
- Laravel Version: 6.2
- Adldap2-Laravel Version: 6.0
- PHP Version: 7.2
- LDAP Type: OpenLDAP

### Description:

I have authenticated and logged in using the NoDatabaseUserProvider, however, when trying to retrieve data using Instance of \Adldap\Models\User.

### Steps To Reproduce:
When trying this code: 
```
$user = Auth::user();
echo $user->getCommonName();
echo $user->getAccountName();
```

This was the log:
```
local.ERROR: Call to a member function getCommonName() on null {"userId":"77777777-7777-6669-6962-657461313130","exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function getCommonName() on null at ***********\routes\\web.php:33)
```

I think the 'userId' does not exist in LDAP. Instead it is the uid in LDAP. Any ideas?

**Comment by stevebauman** [comment]
Hi @Haziqasyraff,

If you dump the returned user from the `Auth::user()` call, what is returned? An Adldap model instance or something else?

```
dd(Auth::user());
```

**Comment by Haziqasyraff** [comment]
It currently returns null

**Comment by muzammilaskari** [comment]
@Haziqasyraff did you find out way to solve this? I am facing same issue in my current project
