### ISSUE TITLE
[1.4] Target [Adldap\Contracts\Adldap] is not instantiable

### ISSUE THREAD

**Issue by tarreislam** [Adldap2/Adldap2-Laravel#80]
LDAP works on my local windows server, but when i try to run it at my linux server i get this message:

1/1BindingResolutionException in Container.php line 752:Target [Adldap\Contracts\Adldap] is not instantiable while building [App\Http\Controllers\Admin\AdminController].

Both servers have ldap 3001 installed

I couldnt updload a zip file but here is the controller im trying to use it in.

http://pastebin.com/wShTUyPi

edit: i have also tried using the facade in linux, but then i get "class Adldap does not exist"

**Comment by stevebauman** [comment]
Have you inserted the service provider in your `config/app.php` file and cleared your config cache using `php artisan cache:clear`?

**Comment by tarreislam** [comment]
Yes, the server has the same repo as me, and I can navigate to other controllers without any errors. And yes, I tried to clear cache

**Comment by stevebauman** [comment]
The `AdldapServiceProvider` binds the `Adldap\Contracts\Adldap`, so that service provider isn't being registered somehow. Are you sure your deployed repo contains the adldap package in your `vendor` folder?

**Comment by tarreislam** [comment]
I cannot triple check it right now but I'm 99% sure its there since I can see the service providers in my **app/config.php** @ git

```
        Adldap\Laravel\AdldapServiceProvider::class,
        Adldap\Laravel\AdldapAuthServiceProvider::class
```
And I ran an extra git fetch merge + composer update + dumpautoload without any errors @ the Ubuntu machine.

**Comment by tarreislam** [comment]
Ok now I checked the ubuntu machine again and I can confirm both adldap2 and adldap2-laravel exists in the vendor directory with their respective service provider in config/app.php

Another git fetch + merge and composer update yield nothing, I also tried to clear the cache again without any change in the error code.

What could cause the problem?

**Comment by stevebauman** [comment]
Hmm I'm not sure if these two contain any large differences:

```
Ubuntu                  Windows
Vendor Version 20421 => Vendor Version 20433
```

Try running `composer dump-autoload` and `php artisan clear-compiled` on the Ubuntu machine?

**Comment by tarreislam** [comment]
We had to move to production so i didn't have time to continue on the Linux machine, later in Q2 we will attempt Linux again. So you can close / leave this issue open if you want to.

**Comment by stevebauman** [comment]
Ok, I'll close the issue for now, but definitely just leave a comment when you attempt this further and I'll open it back up, thanks!
