### ISSUE TITLE
Show or log real reason for failed login attempt

### ISSUE THREAD

**Issue by Sebi94nbg** [Adldap2/Adldap2-Laravel#808]
- Laravel Version: 6.5
- Adldap2-Laravel Version: 6.0.8
- PHP Version: 7.2
- LDAP Type: ActiveDirectory

### Description:

Is there any way to get the real reason for the failed login? Eg. one of these:

- User not found
- User is forced to set a new password (password expired or user is forced to set a new password)
- User is not member of the required Active Directory group
- ...

The `Auth::attempt()` method returns only a boolean value. I would like to show my users the real reason for the failed login attempt.

I also would like to log these into the database. For example using a Listener / Event.

Currently, I've a Listener, which simply logs `Authentication failed. Wrong username or password.` for the `AuthenticationFailed $event` event. But eg. when a user is forced to set a new password or he is not member of the required Active Directory group, this log message is simply incorrect. In this case, the log message should be `Authentication failed. User is forced to set a new password first.` or `Authentication failed. User is not member of the required Active Directory group.`.

Is this somehow possible to identify and log? Below, you'll find my current listener code:

```php
<?php

namespace App\Listeners;

use App\User;
use Illuminate\Support\Facades\Log;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Contracts\Queue\ShouldQueue;
use Adldap\Laravel\Events\AuthenticationFailed;
use App\Http\Controllers\Helpers\WatchdogController;
use function GuzzleHttp\json_encode;

class LogAuthFailure
{
    /**
     * Create the event listener.
     *
     * @return void
     */
    public function __construct()
    {
        //
    }

    /**
     * Handle the event.
     *
     * @param  AuthenticationFailed  $event
     * @return void
     */
    public function handle(AuthenticationFailed $event)
    {
        $user = User::where('email', '=', $event->user->getEmail())->first();

        try {
            new WatchdogController(
                (isset($user->id)) ? $user->id : null,
                2, // Active Directory (LDAP) Login
                1, // Info
                'Authentication failed. Wrong username or password.' // Message
            );
        } catch (Exception $ex) {
            Log::critical('WATCHDOG: Failed to save new entry due to this error: ' . $ex->getMessage());
        }
    }
}
```

**Comment by stevebauman** [comment]
Hi @Sebi94nbg,

You can call various methods on the user that is set on the `AuthenticationFailed` event:

```php
if (! $event->user->inGroup('Accounting')) {
    // User is not apart of the 'Accounting' group.
}

if ($event->user->passwordExpired()) {
    // Users password is expired.
}

use Adldap\Models\Attributes\UserAccountControl;

$uac = $event->user->getUserAccountControlObject()

if ($uac->has(AccountControl::ACCOUNTDISABLE )) {
    // Account is disabled.
}
```

You can also swap the `Resolver` for your own instance to fire your own custom event if the user is not found:

```php
namespace App;

use Adldap\Laravel\Resolvers\UserResolver;

class LdapUserResolver extends UserResolver
{
    public function byCredentials(array $credentials = [])
    {
        $user = parent::byCredentails($credentials);

        if ($user) {
            return $user;
        }

        event(new \App\Events\MyCustomEvent());
    }
}
```

Then, swap the resolver with your own (maybe in your `AppServiceProvider::boot` method):

```php
use App\LdapUserResolver;
use Adldap\Laravel\Resolvers\Resolver;

Resolver::swap(app(LdapUserResolver::class));
```

Hope this helps!

**Comment by Sebi94nbg** [comment]
Thanks @stevebauman , this helped already a lot! :)

`$event->user->inGroup()` is never fired, because my `LoginController` does never fire the event in order to log anything:

```php
public function login(Request $request)
    {
        if (! Auth::attempt(
                $request->only(['samaccountname', 'password']),
                (isset($request->remember)) ? true : false
            )
        )
        {
            return redirect()->route('login')->with([
                'alert_type' => 'danger',
                'message' => 'Either your username or password is incorrect or you do not have the required permissions.'
            ])->withInput($request->except('password'));
        }

        return redirect()->route('home')->with([
            'alert_type' => 'success',
            'message' => 'You have successfully logged in!'
        ]);
    }
```

Do I need to change this logic in order to log this `$event->user->inGroup()` result as well? Or is this a bug of this package?

**Comment by stevebauman** [comment]
Glad I could help!

> $event->user->inGroup() is never fired, because my LoginController does never fire the event in order to log anything:

That isn't an event that is fired - it's a check to see what group your ActiveDirectory user is in.

The example is shown to be used inside of your own custom listener for the `AuthenticationFailed` event. You've already posted code for your custom listener. Put this check inside your listener and log whatever you verify on your ActiveDirectory user.

> Do I need to change this logic in order to log this $event->user->inGroup() result as well? Or is this a bug of this package?

I'm not sure what you mean by this. Again, inside of your custom listener, you can log whatever you check on the `user` that failed authentication:

```php
if (! $event->user->inGroup('Accounting')) {
    logger()->error("User {$user->getCommonName()} is not a member of 'Accounting'.");
}
```

This is not a built in feature of Adldap2-Laravel, you will have to log these checks yourself.

**Comment by Sebi94nbg** [comment]
Above you've seen my `LoginController`. This is my current `app/Listeners/LogAuthFailure.php`:

```php
<?php

namespace App\Listeners;

use App\User;
use Illuminate\Support\Facades\Log;
use Adldap\Laravel\Events\AuthenticationFailed;
use Adldap\Models\Attributes\AccountControl;
use App\Http\Controllers\Helpers\WatchdogController;

class LogAuthFailure
{
    /**
     * Create the event listener.
     *
     * @return void
     */
    public function __construct()
    {
        //
    }

    /**
     * Handle the event.
     *
     * @param  AuthenticationFailed  $event
     * @return void
     */
    public function handle(AuthenticationFailed $event)
    {
        // User is not apart of the required group.
        if (! $event->user->inGroup(config('ldap_auth.required_group_dn'))) {
            $message = 'Authentication failed. User is not member of the required group \''.config('ldap_auth.required_group_dn').'\'.';
        }

        // Users password is expired.
        if ($event->user->passwordExpired()) {
            $message = 'Authentication failed. Users password expired.';
        }

        // User account is expired.
        if ($event->user->isExpired()) {
            $message = 'Authentication failed. User account is expired.';
        }

        // Account is disabled.
        $uac = $event->user->getUserAccountControlObject();
        if ($uac->has(AccountControl::ACCOUNTDISABLE)) {
            $message = 'Authentication failed. User account is disabled.';
        }

        // If none of the above cases matched: Wrong username or password
        if (! isset($message)) {
            $message = 'Authentication failed. Wrong username or password.';
        }

        $user = User::where('email', '=', $event->user->getEmail())->first();

        try {
            new WatchdogController(
                (isset($user->id)) ? $user->id : null,
                2, // Active Directory (LDAP) Login
                1, // Info
                $message // Message
            );
        } catch (Exception $ex) {
            Log::critical('WATCHDOG: Failed to save new entry due to this error: ' . $ex->getMessage());
        }
    }
}
```
When I test the listener I get all `$message`s, which I want. But I never get the `$message` for the `inGroup()` check.

When I add the user to the required AD group, the user is able to login.

When I disable the user account, the user is not able to login and it logs the respective message `Authentication failed. User account is disabled.`.

When I enable the user account again and remove the user from the required group, the user is NOT able to login and I would expect, that it logs the respective `Authentication failed. User is not member of the required group '<group_dn>'` message, but it doesn't log it. That's the reason, why I think, that the event `AuthenticationFailed` is not fired, which calls the above shown listener `LogAuthFailure`.

I hope, I've explained it understandable.

**Comment by Sebi94nbg** [comment]
Any idea?

**Comment by Sebi94nbg** [comment]
I could solve this issue by replacing the [scope](https://adldap2.github.io/Adldap2-Laravel/#/auth/setup?id=scopes) with a [rule](https://adldap2.github.io/Adldap2-Laravel/#/auth/setup?id=rules).
