### ISSUE TITLE
[Adldap2] Adding/Creating User Issue

### ISSUE THREAD

**Issue by ParthSarth** [Adldap2/Adldap2-Laravel#81]
@stevebauman

Hi, I'm an having as issue with creating a user with Adldap.

Relevant code:

```
$attributes=array(
                "userName"=>$employee->userName,
                "logon_name"=>$employee->userName."@mydc.com",
                "firstname"=>$employee->FN,
                "surname"=>$employee->LN,
                "company"=>"MIG",
                "email"=>$employee->email,
                "container"=>array("User Accounts","Users"),
                "password"=>$fields['password'],
            );
        $user = Adldap::users()->create($attributes);

        dd($user); //RETURNS FALSE
```
$user should be true but it returns as false. Also tried with 'newInstance()' :

`
```
$adldap = new \Adldap\Adldap($config);
$user = $adldap->users()->newInstance();
        $user->setDistinguishedName('CN=John Doe,CN=Users,DC=mydc,DC=com');
        $user->setFirstName($employee->FN);
        $user->setLastName($employee->LN);
        $user->setUserAccountControl('512');
        $user->setAccountName($employee->userName);
    $user->setPassword('H@tr!ck');

        $adNewUser = $user->save(); 
        dd($adNewUser); //RETURNS FALSE
````

**Comment by stevebauman** [comment]
```php
$attributes=array(
    "userName"=>$employee->userName,
    "logon_name"=>$employee->userName."@mydc.com",
    "firstname"=>$employee->FN,
    "surname"=>$employee->LN,
    "company"=>"MIG",
    "email"=>$employee->email,
    "container"=>array("User Accounts","Users"),
    "password"=>$fields['password'],
);
```

Some of these attributes you're specifying don't actually exist.

For example, the `email` attribute is actually named `mail` in AD. As well as the `container`, I'm assuming you're trying to make the user apart of multiple groups (which would be the `memberof` attribute). Another example is the `logon_name` attribute you're specifying, which is actually `samaccountname`. All attributes you set **must** exist on your AD installation.

**Comment by ParthSarth** [comment]
That cleared it up. Was able to get it working using `newInstance()`

Still not able to do it using `create($attributes)` but as long as a new user can be create one way, it's fine.

Thank you.

**Comment by stevebauman** [comment]
Thanks for following up so quickly! Glad you've resolved the issue.

The create method is definitely a different alternative and may return different results like you've mentioned over `newInstance()`.

Please let me know if you encounter any further issues, thanks.

**Comment by ParthSarth** [comment]
The

**Comment by stevebauman** [comment]
Reopen intentional?

**Comment by ParthSarth** [comment]
Yes. Ran into a problem again.

We were able to add a user, but we're having trouble setting the password.
This part works:

```
        $adldap = new \Adldap\Adldap($config);  
        
        $user = $adldap->users()->newInstance();

        
        $user->setAccountName($employee->userName);
        $user->setDistinguishedName("CN=".$employee->FN." ".$employee->LN.",CN=Users,DC=server,DC=mydc,DC=com");
        $user->setFirstName($employee->FN);
        $user->setLastName($employee->LN);
        $user->setCompany("d");
        $user->setEmail($employee->email);
        $user->setUserPrincipalName($employee->userName."@mydc.com");
      

        $user->save();

```

But doing this does not:

```
        $adldap = new \Adldap\Adldap($config);  
        
        $user = $adldap->users()->newInstance();

        
        $user->setAccountName($employee->userName);
        $user->setDistinguishedName("CN=".$employee->FN." ".$employee->LN.",CN=Users,DC=server,DC=mydc,DC=com");
        $user->setFirstName($employee->FN);
        $user->setLastName($employee->LN);
        $user->setCompany("d");
        $user->setEmail($employee->email);
        $user->setUserPrincipalName($employee->userName."@mydc.com");

        $user->setPassword("adtest1234");
      
        $user->save();
```

I looked at this closed issue - https://github.com/Adldap2/Adldap2/issues/38 
and change my code to look like this:

```
        $adldap = new \Adldap\Adldap($config);  
        
        $user = $adldap->users()->newInstance();

        
        $user->setAccountName($employee->userName);
        $user->setDistinguishedName("CN=".$employee->FN." ".$employee->LN.",CN=Users,DC=server,DC=martinfg,DC=com");
        $user->setFirstName($employee->FN);
        $user->setLastName($employee->LN);
        $user->setCompany("d");
        $user->setEmail($employee->email);
        $user->setUserPrincipalName($employee->userName."@mydc.com");
      

        if($user->save()){
            $user->setPassword("test1234");
            $user->disable();
            dd($user);
        }

```

... and it's still not working. We're able to create the user, but not able to enable or set password.

**Comment by ParthSarth** [comment]
@stevebauman

If you have the time and could investigate the issue over the weekend, I'd greatly appreciate it. I won't have the actual code in front of me till Monday anyway, but I hope to have something to try by then to resolve this issue. Thanks!

**Comment by stevebauman** [comment]
Hey @ParthSarth, would be glad to look into it, I'm going to do so now.

What type of connection are you using to your LDAP server? SSL or TLS?

**Comment by ParthSarth** [comment]
Great. Appreciate it.

Using SSL.

**Comment by stevebauman** [comment]
You don't receive a `Server is unwilling to perform` exception right?

**Comment by stevebauman** [comment]
It's unfortunate but I don't have access to use my AD server over SSL or TLS, so I'm actually unable to test the actual functionality, only ensure that the correct variables are set and passed to modify the password correctly.

**Comment by ParthSarth** [comment]
We do receive a `Server is unwilling to perform` exception. But only when including `setPassword`.

And when we are able to add a user successfully (without `setPassword`) the user is automatically created as disabled.

**Comment by ParthSarth** [comment]
Could you just walk me through how to set a password for a user during creation and/or immediately after they have been created? Just an example or something. (Creating the user through `newInstance()`)

**Comment by ParthSarth** [comment]
I was look at this issue -  https://github.com/Adldap2/Adldap2/issues/58 - if it was relevant, but that person's running into the same problem as me. 

This fix is what I currently have: https://github.com/Adldap2/Adldap2/commit/e6af03c2707d81ffb7c9b63c1d91cbfebc55756c

**Comment by stevebauman** [comment]
The exception `Server is unwilling to perform` means your AD server is refusing to set the password for the user. Is your configured admin account with Adldap a domain administrator?

**Comment by ParthSarth** [comment]
Yup. Admin account configured with adldap as domain admin.

So, then, we shouldn't be getting that error right? Just calling the `setPassword` method during account creation should work properly, right? 'Cause for some reason it's not...

**Comment by stevebauman** [comment]
> So, then, we shouldn't be getting that error right?

No you shouldn't. In regards to you code listed here:

```php
if($user->save()){
    $user->setPassword("test1234");
    $user->disable();

    dd($user);
}
```

You're calling the `$user->disable()` method, are you able to just call the `$user->save()` method right after calling `$user->setPassword();`?

**Comment by ParthSarth** [comment]
Yup. Tried that. I removed the disabled. It was something I got from looking at the other issue I quoted (Adldap2/Adldap2#38 ), but then realized it wasn't relevant. Mostly because the user created is disabled on creation anyway.

So as of now, we have this:

```
        $adldap = new \Adldap\Adldap($config);  

        $user = $adldap->users()->newInstance();


        $user->setAccountName($employee->userName);
        $user->setDistinguishedName("CN=".$employee->FN." ".$employee->LN.",CN=Users,DC=server,DC=mydc,DC=com");
        $user->setFirstName($employee->FN);
        $user->setLastName($employee->LN);
        $user->setCompany("d");
        $user->setEmail($employee->email);
        $user->setUserPrincipalName($employee->userName."@mydc.com");


        $user->save(); 
```

And doing this right after-


```
 $user->save(); 

if($user->save()){
    $user->setPassword("test1234");

    $user->save();
}
```

- does not work.

**Comment by stevebauman** [comment]
> Mostly because the user created is disabled on creation anyway.

Can you try this? Not tested, but experimenting:

```php
if ($user->save()) {
    $user->lockouttime = 0;
    $user->pwdlastset = 0;

    $user->setPassword('Password123');

    $user->save();
}
```

Also try:

```php
if ($user->save() && $user->enable()) {
    $user->setPassword('Password123');

    $user->save();
}
```

**Comment by ParthSarth** [comment]
Hey, back at work today and just got a chance to try your suggestions.

Doing:
```
// Enabling the user before setting a password.
if ($user->save() && $user->enable()) {
    $user->setPassword('Password123');

    $user->save();
}
```
gives me this error- ```
FatalErrorException in AddEmployeeController.php line 110:
Call to undefined method Adldap\Models\User::enable()
```

And the first one just gives me false when I `dd($user->save());` after save password.

I think enabling the user and then setting password might do the trick, but there is not method to call to enable the new user.

**Comment by stevebauman** [comment]
Whoops! Apologies, you're right that doesn't exist, we need to set the user account control. Set it to `512`:

$user->setUserAccountControl(512);

if ($user->save()) {
    $user->setPassword('Password123');

    $user->save();
}

**Comment by ParthSarth** [comment]
It worked!

This is how to final setup looks:

```
            $adldap = new \Adldap\Adldap($config);  
            
            $user = $adldap->users()->newInstance();

            
            $user->setAccountName($employee->userName);
            $user->setDistinguishedName("CN=".$employee->FN." ".$employee->LN.",CN=Users,DC=dc,DC=mydc,DC=com");
            $user->setFirstName($employee->FN);
            $user->setLastName($employee->LN);
            $user->setCompany("company");
            $user->setEmail($employee->email);
            $user->setUserPrincipalName($employee->userName."@mydc.com");
            

            // Save the user.
            if ($user->save()) {
                // enable the new user.
                $user->setUserAccountControl(512);
               //set new user password
                $user->setPassword('Password123');

                // save the user.
                dd($user->save()); // should give out true
            }
```
Took a while but finally got it.
 
Thanks a lot for the help, really appreciate it.

**Comment by stevebauman** [comment]
Perfect! No problem at all, really glad this is resolved. This is definitely going in the documentation.

Thanks for following up so quickly.

**Comment by ParthSarth** [comment]
No problem. Yes, please add this in the documentation, it'll be really helpful. Enabling user and setting password is really important.
