### ISSUE TITLE
ldap_auth.php config file not being copied

### ISSUE THREAD

**Issue by Gramcito** [Adldap2/Adldap2-Laravel#812]
- Laravel Version: 6.5.1
- Adldap2-Laravel Version: 6.0
- PHP Version: 7.3
- LDAP Type: ActiveDirectory

### Description:
Running the php artisan vendor:publish cli command result in only on config file being published: ldap.php; ldap_auth.php is not copied to the config folder. 

Running 
```
php artisan vendor:publish --provider=Adldap\Laravel\AdldapAuthServiceProvider
```
results in a "Unable to locate publishable resources".

### Steps To Reproduce:
Run the above command.

**Comment by m1ch3lp3r3z** [comment]
Hi, you probably already fixed this but just in case someone else is facing this issue, I fixed it by surrounding the class name with (double) quotes.

**Comment by stevebauman** [comment]
Thanks for posting your solution @m1ch3lp3r3z! Going to close this out, as that is currently in the installation docs.
