### ISSUE TITLE
Query returns empty

### ISSUE THREAD

**Issue by gabriiellduarte** [Adldap2/Adldap2-Laravel#822]
- Laravel Version: 5.8
- Adldap2-Laravel Version: 10.2.1
- PHP Version: 7.2.18
- LDAP Type: ActiveDirectory

### Description: 

When trying to list users with Adldap :: search () -> users () -> select (['cn', 'samaccountname', 'mail']) -> get (); I get the empty array, authentication always occurs but the problem only appears when using as php running on the same machine as activedirectory runs if the query is done on an external host the query is successful

**Comment by stevebauman** [comment]
Hi @gabriiellduarte,

What is your `base_dn` set to in your configuration? Are you sure it is correct?

Do you also have `auto_connect` set to `true` in your `ldap.php` configuration file?

**Comment by stevebauman** [comment]
Also, if you’re using Adldap2 on the actual ActiveDirectory server, try using `127.0.01` as the host, or the fully qualified name of the PC `CORP-DC1.acme.org`.

**Comment by gabriiellduarte** [comment]
@stevebauman auto_connect is true and i tried to change to localhost, 127.0.0.1, "domain name" but all give the same thing

**Comment by gabriiellduarte** [comment]
my configs on php then all activateds

**Comment by gabriiellduarte** [comment]
laravel logs nothing errors

**Comment by stevebauman** [comment]
Have you enabled logging in the `ldap.php` file?

**Comment by stevebauman** [comment]
Also, are you caching your configuration files?

**Comment by gabriiellduarte** [comment]
Logging activated and working follow my print of connection log

![image](https://user-images.githubusercontent.com/11770579/70958181-28625d00-2057-11ea-97ea-ae0d198c68ef.png)

**Comment by stevebauman** [comment]
Strange, there’s no “Filter: “ shown in the log.

Can you post your `ldap.php` file with sensitive details removed (username / password / host etc)?

**Comment by gabriiellduarte** [comment]
![image](https://user-images.githubusercontent.com/11770579/70991263-deed2e80-20a5-11ea-825f-d0ee59baf4a8.png)

**Comment by stevebauman** [comment]
Turn off `follow_referrals` and try again

**Comment by gabriiellduarte** [comment]
Perfect, thanks

**Comment by stevebauman** [comment]
Did that work?

**Comment by gabriiellduarte** [comment]
Yes, working

**Comment by stevebauman** [comment]
Awesome, great to hear!
