### ISSUE TITLE
'X' Key is missing from the given credentials array

### ISSUE THREAD

**Issue by jerlabor** [Adldap2/Adldap2-Laravel#824]
- Laravel Version: 6.2
- Adldap2-Laravel Version: 6.0
- PHP Version: 7.2
- LDAP Type: 

### Description:

Requesting a GET request using Axios returns an error of "The 'username' key is missing from the given credentials array."

### Steps To Reproduce:
```
axios.get('/api/user?api_token='+this.token)
                    .then(res => console.log(res))
                    .catch(e => console.log(e))

```

**Comment by stevebauman** [comment]
The Adldap2-Laravel auth driver is not compatible with API authentication. You must change your `api` guard `provider` to a compatible driver (such as `eloquent` or `database`).
