### ISSUE TITLE
Kernel

### ISSUE THREAD

**Issue by unixtime** [Adldap2/Adldap2-Laravel#83]
Upgrading to package 2.0 is giving me an error. reverted back to 1.4 - I am not sure if I am missing something in 2.0

I also used the new `adldap.conf` config. 

<pre>
Call to undefined method Adldap\Laravel\Middleware\WindowsAuthenticate::getDefaultConnectionName() in /Volumes/Docker/ASPortal/auth/vendor/adldap2/adldap2-laravel/src/Traits/ImportsUsers.php on line 246
</pre>

<pre>
    protected $middlewareGroups = [
        'web' => [
            \App\Http\Middleware\EncryptCookies::class,
            \Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::class,
            \Illuminate\Session\Middleware\StartSession::class,
            \Illuminate\View\Middleware\ShareErrorsFromSession::class,
            \App\Http\Middleware\VerifyCsrfToken::class,
            \Adldap\Laravel\Middleware\WindowsAuthenticate::class,

        ],
</pre>

It works perfect in 1.4

Thank you.

**Comment by stevebauman** [comment]
Fix coming shortly, thanks!

**Comment by unixtime** [comment]
You simply rock!!!

**Comment by stevebauman** [comment]
Haha thanks! Appreciate you using Adldap2!
