### ISSUE TITLE
API Authentication: The 'email' key is missing from the given credentials array.

### ISSUE THREAD

**Issue by shaqaruden** [Adldap2/Adldap2-Laravel#830]
- Laravel Version: 6.2
- Adldap2-Laravel Version: 6.0
- PHP Version: 7.3.13
- LDAP Type: ActiveDirectory

### Description: 
I am trying to setup API Token authentication for my project. I followed [Laravel's Guide)[https://laravel.com/docs/6.x/api-authentication] for implementing it but I am getting the `The 'email' key is missing from the given credentials array.` exception when submitting a get request to a protected endpoint. I have attempted with and without hashing the api_token and tried every option of authentication(passing in url, sending as form_param, and bearer).

passing the api_token in the url just returns unauthenticated, the others return the email error.

Here is my api.php file
```php
<?php

use Illuminate\Http\Request;

Route::group(['middleware' => ['auth:api']], function () {
    Route::resource('location', 'LocationController');
});
```

Here is the guards from config/auth.php
```php
<?php
 'guards' => [
        'web' => [
            'driver' => 'session',
            'provider' => 'users',
        ],

        'api' => [
            'driver' => 'token',
            'provider' => 'users',
            'hash' => false,
        ],
    ],
```

I created a listener to actually create the API token upon login
EventServiceProvider
```php
<?php

namespace App\Providers;

use Adldap\Laravel\Events\AuthenticationSuccessful;
use App\Listeners\CreateAPIToken;
use Illuminate\Auth\Events\Registered;
use Illuminate\Auth\Listeners\SendEmailVerificationNotification;
use Illuminate\Foundation\Support\Providers\EventServiceProvider as ServiceProvider;

class EventServiceProvider extends ServiceProvider
{
    /**
     * The event listener mappings for the application.
     *
     * @var array
     */
    protected $listen = [
        Registered::class => [
            SendEmailVerificationNotification::class,
        ],
        AuthenticationSuccessful::class => [
            CreateAPIToken::class
        ],
    ];

    /**
     * Register any events for your application.
     *
     * @return void
     */
    public function boot()
    {
        parent::boot();

        //
    }
}
```
CreateAPIToken
```php
<?php

namespace App\Listeners;

use App\User;
use Illuminate\Support\Str;

class CreateAPIToken
{
    /**
     * Handle the event.
     *
     * @param  object  $event
     * @return void
     */
    public function handle($event)
    {
        $user = User::where('email', '=', $event->user->getUserPrincipalName())->first();
        $token = Str::random(80);

        if($user->api_token === null) {
            $user->api_token = $token;
            $user->save();
        }
    }
}
```

### Steps To Reproduce:
Using Insomnia REST Client, create get request to /api/location and set bearer token to api_token in database. Send request

**Comment by stevebauman** [comment]
Hi @shaqaruden,

The Adldap2-Laravel auth driver does not  support using the API Token guard. Have you configured your `users` provider to use the `ldap` driver inside of your `auth.php` file?

**Comment by shaqaruden** [comment]
Yes I do

**Comment by stevebauman** [comment]
Then you must configure your `api` guard to use a different `provider` that has the `eloquent` or `database` driver, because those drivers are able to save and retrieve tokens from your users database table.

The LDAP driver does not support saving tokens to your LDAP user, as it has no where to store them properly (no database). It's possible it could support this in the future by using an LDAP attribute that could hold a string, but that opens a big can of worms and possible bugs / issues that could occur along the way.

**Comment by shaqaruden** [comment]
For anyone coming across this same issue. What I did was I created a new middleware called BearerToken and use that to authenticate the API Token. This middleware only works for Bearer but you can easily create your own middleware that captures more types of tokens. Here is my middleware class

```php
<?php

namespace App\Http\Middleware;

use App\User;
use Closure;
use Exception;
use Illuminate\Support\Facades\Auth;

class BearerToken
{

    protected $token;
    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @return mixed
     */
    public function handle($request, Closure $next)
    {
        $authorization_header = explode(' ', $request->header('Authorization'));

        if($authorization_header[0] === 'Bearer') {
            $this->token = $authorization_header[1];
        } else {
            abort(401, 'Bearer Token not specified.');
        }
        
        if(User::where('api_token', '=', $this->token)->first() === null) {
            abort(401, 'Bearer Token Mismatch.');
        }
        
        return $next($request);
    }
}
```

**Comment by shaqaruden** [comment]
> 
> 
> Then you must configure your `api` guard to use a different `provider` that has the `eloquent` or `database` driver, because those drivers are able to save and retrieve tokens from your users database table.
> 
> The LDAP driver does not support saving tokens to your LDAP user, as it has no where to store them properly (no database). It's possible it could support this in the future by using an LDAP attribute that could hold a string, but that opens a big can of worms and possible bugs / issues that could occur along the way.
> 
> ```
> // config/auth.php
> 
> // ...
> 
>  'providers' => [
>         'users' => [
>             'driver' => 'eloquent',
>             'model' => App\User::class,
>         ],
> 
>     //...
> ```

Wouldn't just allowing us to specify what column in our users table is the api_token be enough information for ADLDAP2-Laravel (and some other code changes) to support api tokens?

**Comment by stevebauman** [comment]
Unfortunately no - the `TokenGuard` calls the `retrieveByCredentials()` method on your configured provider, but instead of passing credentials with a `username` or `email` key, it passes a configured `storageKey`. This means that the LDAP auth driver would not be able to locate a user in your LDAP directory by the given `storageKey` value, so no user could be returned to validate the token.

```php
// vendor/laravel/framework/src/Illuminate/Auth/TokenGuard.php

// ...
$user = $this->provider->retrieveByCredentials([
    $this->storageKey => $this->hash ? hash('sha256', $token) : $token,
]);
```

It's possible to support it by reworking a lot of the configuration, but that would require a lot of work, testing, documentation and an upgrade / usage guide.

If you're up for the challenge, I'd definitely accept a PR!

**Comment by adesugbaa** [comment]
@shaqaruden Hi I am interested in your workaround. I have a project that uses Adldap for LDAP integration, and it works perfectly for the web application.

I need to integrate an API to support mobile devices, and I am unable to validate requests with a Bearer token. How exactly do I integrate the middleware?
