### ISSUE TITLE
Unable to install this package in new laravel project (6.2)

### ISSUE THREAD

**Issue by matheenulla6** [Adldap2/Adldap2-Laravel#833]
Hi 

Unable to install this package in new project. I am getting error like this 

Problem 1
    - adldap2/adldap2-laravel v6.0.8 requires adldap2/adldap2 ^10.1 -> satisfiable by adldap2/adldap2[v10.1.0, v10.1.1, v10.2.0, v10.2.1, v10.2.2].
    - adldap2/adldap2-laravel v6.0.0 requires adldap2/adldap2 ^10.0 -> satisfiable by adldap2/adldap2[v10.0.0, v10.0.1, v10.0.10, v10.0.11, v10.0.2, v10.0.3, v10.0.4, v10.0.5, v10.0.6, v10.0.7, v10.0.8, v10.0.9, v10.1.0, v10.1.1, v10.2.0, v10.2.1, v10.2.2].
    - adldap2/adldap2-laravel v6.0.1 requires adldap2/adldap2 ^10.0 -> satisfiable by adldap2/adldap2[v10.0.0, v10.0.1, v10.0.10, v10.0.11, v10.0.2, v10.0.3, v10.0.4, v10.0.5, v10.0.6, v10.0.7, v10.0.8, v10.0.9, v10.1.0, v10.1.1, v10.2.0, v10.2.1, v10.2.2].
    - adldap2/adldap2-laravel v6.0.2 requires adldap2/adldap2 ^10.0 -> satisfiable by adldap2/adldap2[v10.0.0, v10.0.1, v10.0.10, v10.0.11, v10.0.2, v10.0.3, v10.0.4, v10.0.5, v10.0.6, v10.0.7, v10.0.8, v10.0.9, v10.1.0, v10.1.1, v10.2.0, v10.2.1, v10.2.2].
    - adldap2/adldap2-laravel v6.0.3 requires adldap2/adldap2 ^10.0 -> satisfiable by adldap2/adldap2[v10.0.0, v10.0.1, v10.0.10, v10.0.11, v10.0.2, v10.0.3, v10.0.4, v10.0.5, v10.0.6, v10.0.7, v10.0.8, v10.0.9, v10.1.0, v10.1.1, v10.2.0, v10.2.1, v10.2.2].
    - adldap2/adldap2-laravel v6.0.4 requires adldap2/adldap2 ^10.0 -> satisfiable by adldap2/adldap2[v10.0.0, v10.0.1, v10.0.10, v10.0.11, v10.0.2, v10.0.3, v10.0.4, v10.0.5, v10.0.6, v10.0.7, v10.0.8, v10.0.9, v10.1.0, v10.1.1, v10.2.0, v10.2.1, v10.2.2].
    - adldap2/adldap2-laravel v6.0.5 requires adldap2/adldap2 ^10.0 -> satisfiable by adldap2/adldap2[v10.0.0, v10.0.1, v10.0.10, v10.0.11, v10.0.2, v10.0.3, v10.0.4, v10.0.5, v10.0.6, v10.0.7, v10.0.8, v10.0.9, v10.1.0, v10.1.1, v10.2.0, v10.2.1, v10.2.2].
    - adldap2/adldap2-laravel v6.0.6 requires adldap2/adldap2 ^10.0 -> satisfiable by adldap2/adldap2[v10.0.0, v10.0.1, v10.0.10, v10.0.11, v10.0.2, v10.0.3, v10.0.4, v10.0.5, v10.0.6, v10.0.7, v10.0.8, v10.0.9, v10.1.0, v10.1.1, v10.2.0, v10.2.1, v10.2.2].
    - adldap2/adldap2-laravel v6.0.7 requires adldap2/adldap2 ^10.0 -> satisfiable by adldap2/adldap2[v10.0.0, v10.0.1, v10.0.10, v10.0.11, v10.0.2, v10.0.3, v10.0.4, v10.0.5, v10.0.6, v10.0.7, v10.0.8, v10.0.9, v10.1.0, v10.1.1, v10.2.0, v10.2.1, v10.2.2].
    - adldap2/adldap2 v10.2.2 requires ext-ldap * -> the requested PHP extension ldap is missing from your system.
    - adldap2/adldap2 v10.2.1 requires ext-ldap * -> the requested PHP extension ldap is missing from your system.
    - adldap2/adldap2 v10.2.0 requires ext-ldap * -> the requested PHP extension ldap is missing from your system.
    - adldap2/adldap2 v10.1.1 requires ext-ldap * -> the requested PHP extension ldap is missing from your system.
    - adldap2/adldap2 v10.1.0 requires ext-ldap * -> the requested PHP extension ldap is missing from your system.
    - adldap2/adldap2 v10.0.9 requires ext-ldap * -> the requested PHP extension ldap is missing from your system.
    - adldap2/adldap2 v10.0.8 requires ext-ldap * -> the requested PHP extension ldap is missing from your system.
    - adldap2/adldap2 v10.0.7 requires ext-ldap * -> the requested PHP extension ldap is missing from your system.
    - adldap2/adldap2 v10.0.6 requires ext-ldap * -> the requested PHP extension ldap is missing from your system.
    - adldap2/adldap2 v10.0.5 requires ext-ldap * -> the requested PHP extension ldap is missing from your system.
    - adldap2/adldap2 v10.0.4 requires ext-ldap * -> the requested PHP extension ldap is missing from your system.
    - adldap2/adldap2 v10.0.3 requires ext-ldap * -> the requested PHP extension ldap is missing from your system.
    - adldap2/adldap2 v10.0.2 requires ext-ldap * -> the requested PHP extension ldap is missing from your system.
    - adldap2/adldap2 v10.0.11 requires ext-ldap * -> the requested PHP extension ldap is missing from your system.
    - adldap2/adldap2 v10.0.10 requires ext-ldap * -> the requested PHP extension ldap is missing from your system.
    - adldap2/adldap2 v10.0.1 requires ext-ldap * -> the requested PHP extension ldap is missing from your system.
    - adldap2/adldap2 v10.0.0 requires ext-ldap * -> the requested PHP extension ldap is missing from your system.
    - Installation request for adldap2/adldap2-laravel ^6.0 -> satisfiable by adldap2/adldap2-laravel[v6.0.0, v6.0.1, v6.0.2, v6.0.3, v6.0.4, v6.0.5, v6.0.6, v6.0.7, v6.0.8].

  To enable extensions, verify that they are enabled in your .ini files:
    - C:\xampp\php\php.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.

Installation failed, reverting ./composer.json to its original content.

my composer.json file

 "require": {
        "php": "^7.2",
        "fideloper/proxy": "^4.0",
        "laravel/framework": "^6.2",
        "laravel/tinker": "^2.0"
    },

**Comment by ArtemNehoda** [comment]
sudo apt-get install php7.2-ldap (in Debian and Ubuntu )

**Comment by matheenulla6** [comment]
I am windows

**Comment by matheenulla6** [comment]
solved @ArtemNehoda  thank you I got to know the reason why it is not installing.

**Comment by patricioprp** [comment]
> sudo apt-get install php7.2-ldap (en Debian y Ubuntu)

esto me funcion ok! con laravel 5.5
