### ISSUE TITLE
Model binding with Socialite authentication breaks between 5.1.3 and 6.0.8

### ISSUE THREAD

**Issue by ctstimjackson** [Adldap2/Adldap2-Laravel#834]
- Laravel Version: 5.8
- Adldap2-Laravel Version: 6.0.8
- PHP Version: 7.2.15
- LDAP Type: Active Directory

### Description:
I have an application that authenticates users via Socialite. I'm using Socialite Providers - Microsoft Azure (https://socialiteproviders.netlify.com/providers/microsoft-azure.html). We have on-prem AD that we are syncing to Azure to facilitate SSO.

- Authentication works as expected and users are able to login as expected.
- I'm using Adldap2-Laravel to pull on-prem group memberships and other AD attributes that are not stored in Azure. 

In Adldap2-Laravel 5.1.3:
- I retrieve the user returned from Socialite authentication and either find or create the user in `App\User`.  
- I `Auth::login($user)`.
- `Auth::user()` returns an instance of `App\User`.
- `App\User` is set up with Adldap2-Laravel model binding.
- `Auth::user()->ldap` returns the Active Directory object for that user.

In Adldap2-Laravel 6.0.8, `Auth::user()->ldap` returns `null`.
- I've updated Adldap2-Laravel to 6.0.8.
- I've published the `ldap` and `ldap_auth` config files and configured appropriately.
- I've confirmed that I can use the `Adldap` facade to connect to and query my Active Directory.
- I've added the `objectguid` column to `App\User`.
- I've created a new project that does LDAP authentication (instead of SAML via Azure) and confirmed that model binding works.

My question is:
Is this an expected change between the major versions? Is there a way to bind `Auth\User` to an Active Directory object when authenticating via other means besides LDAP?

**Comment by ctstimjackson** [comment]
I actually ended up figuring this out... it had to do with the syncing of the `objectguid` column. Because my authentication isn't through LDAP, I don't think this was happening correctly. I thought that it should try to fall back to UPN based on this statement in the documentation **(Authentication Driver > Identifiers > GUID Column):**

> If you have user records already inside your database with a null objectguid value, then it will be set automatically if a user authenticates with the same username that is contained in your configured in your username_column option.

However, I think that since I wasn't using LDAP to authenticate, that fallback wasn't happening.

What I ended up doing was once I return an authenticated user from Socialite, I check if the `objectguid` column is populated... if so, I continue on and model binding works as expected. If the `objectguid` column is `null`, I query AD and use **Adldap2-Laravel**'s `Guid` class (`\Adldap\Models\Attributes\Guid`) to return the appropriate `objectguid` and then save that to `App\User`. Then, model binding works as expected.

Hope that makes sense. Thank you for the wonderful library, I really enjoy using it!

**Comment by ctstimjackson** [comment]
Also, I was able to figure this out because of your logging feature you just added. So thank you!

**Comment by stevebauman** [comment]
Thanks for your kind words @ctstimjackson! :heart: I'm glad you were able to investigate and resolve this.

Keep an eye out for an [LdapRecord](https://ldaprecord.com) Laravel driver in the next couple days. It's a complete rebuild of this package with much more flexibility and easier usage. I'll be putting together tons of docs and screencasts to make setting things up easier. :smile:
