### ISSUE TITLE
Switch to LdapRecord package instead of Adldap2

### ISSUE THREAD

**Issue by rcerljenko** [Adldap2/Adldap2-Laravel#837]
Adldap2 readme clearly states:
"LdapRecord is a rebuild of Adldap2 with an easier API, better documentation, and more features to help you integrate LDAP into your awesome PHP applications with no hair-pulling necessary.

Adldap2 will continue to be supported with bug & security fixes - but will not receive feature updates."

https://github.com/DirectoryTree/LdapRecord

**Comment by stevebauman** [comment]
Hi @rcerljenko!

I've rebuilt Adldap2-Laravel into its own [LdapRecord-Laravel](https://github.com/DirectoryTree/LdapRecord-Laravel) repository. I'm working on finishing the [documentation](https://ldaprecord.com/docs/laravel) as we speak.

Once this is complete, a notice will be placed on this repository indicating the same as the Adldap2 repo.

Hope to see you soon over there!

**Comment by rcerljenko** [comment]
@stevebauman super! Thanks!  :)
