### ISSUE TITLE
Environment variable changes?

### ISSUE THREAD

**Issue by HeartlandTechie** [Adldap2/Adldap2-Laravel#840]
- Laravel Version: any
- Adldap2-Laravel Version: >5
- PHP Version: any
- LDAP Type: any

### Description:

Why did this change?

```
                'admin_username' => env('ADLDAP_ADMIN_USERNAME'),
                 'admin_password' => env('ADLDAP_ADMIN_PASSWORD'),
                 'username' => env('ADLDAP_USERNAME'),
                 'password' => env('ADLDAP_PASSWORD'),
```

Currently:

                'username' => env('LDAP_USERNAME', 'username'),
                'password' => env('LDAP_PASSWORD', 'secret'),

**Comment by stevebauman** [comment]
Hi @HeartlandTechie,

This changed from version v4 to v5:

https://github.com/Adldap2/Adldap2-Laravel/blob/v4.0/src/Config/config.php

https://github.com/Adldap2/Adldap2-Laravel/blob/v5.0/src/Config/config.php

I wanted clearer environment variables relating directly to LDAP.

You can always change them back to their original - it's simply a published default.

**Comment by stevebauman** [comment]
If you're referring to the names of the configuration options (`admin_username` to `username`), this was modified in the core Adldap2 repository. The options were renamed to be more clear that an administrator account does not need to be used for connecting to your LDAP server.

I had several questions on both repositories with users confused with this naming convention and I wanted to ensure the next major version had clear options.

**Comment by HeartlandTechie** [comment]
Just noting . . . I've chased my tail for a while now on this one .  . . reinstalled and started from scratch and just copied my .env file from another working instance . . . propagated the same issue.  Grr.  I always grit my teeth when swapping to another new ADLDAP and Laravel version.

**Comment by stevebauman** [comment]
Sorry for the troubles @HeartlandTechie! ❤️ 

There won’t be any further major version releases for Adldap2-Laravel, so you can definitely rest easy knowing these won’t be changed again.
