### ISSUE TITLE
How to login user with NoDatabaseUserProvider

### ISSUE THREAD

**Issue by muzammilaskari** [Adldap2/Adldap2-Laravel#841]
- Laravel Version: 6.14
- Adldap2-Laravel Version: 6.0
- PHP Version: 7.2
- LDAP Type: Open ldap

Hi,
First of all thanks for you wonderful package, I am able to login Successfully with DatabaseUserProvider but the problem is that I do not want to save/sync user in local database, so for that I am using NoDatabaseUserProvider, But I don't know what `$user` should be passed to `            $this->guard()->login($user, true);` for making session and logging In.
I've am using file as session and completely followed the documentation, I am sharing my LoginController > attemptLogin() method below:

```
protected function attemptLogin(Request $request)
    {
        $credentials = $request->only($this->username(), 'password');
        $username = $credentials[$this->username()];
        $password = $credentials['password'];

        $user_format = env('LDAP_USER_FORMAT', 'cn=%s,'.env('LDAP_BASE_DN', ''));
        $userdn = sprintf($user_format, $username);

        if(Adldap::auth()->attempt($userdn, $password, $bindAsUser = true)) {

//            $user = Auth::user(); // returns null
//            dd($user);  // returns null


       
       //if  I use **DatabaseUserProvider** then below code works fine and I get eloquent User object
      // but i do not want to save user in my database so I do not need code below:
      // writing this just for the $user reference
//         $user = \App\User::where($this->username(), $username)->first();
//            if (!$user) {

//                $user = new \App\User();
//               $user->username = $username;
//               $user->password = '';

//                $sync_attrs = $this->retrieveSyncAttributes($username);
//                foreach ($sync_attrs as $field => $value) {
//                   $user->$field = $value !== null ? $value : '';
//              }
//            }

            $this->guard()->login($user, true); // how to get this $user to make laravel session and login
            return true;
        }

        // the user doesn't exist in the LDAP server or the password is wrong
        // log error
        return false;
    }
```

Advance thanks for your help, Please reply me ASAP because I am struck on this for more than a week, thanks

**Comment by stevebauman** [comment]
Hi @muzammilaskari,

You don't need to call `Adldap::auth()->attempt` - this is simply binding to your LDAP server and will not start a Laravel session. You must use Laravel's `Auth::attempt` method.

However, you should only need to modify the `credentials` method inside of your `LoginController`:

```php
// app/Http/Controllers/Auth/LoginController.php

class LoginController extends Controller
{
    // ...

    protected function credentials(Request $request)
    {
        return [
            'uid' => $request->get('username'),
            'password' => $request->get('password'),
        ];
    }
}
```

You will need to modify the above if you are using email addresses instead of usernames:

```php
return [
    'mail' => $request->get('email'),
    'password' => $request->get('password'),
];
```

Then, inside of your `config/ldap_auth.php` file you must change the `provider` and the `identifiers` array:

```php
// ...

// Changed to 'NoDatabaseUserProvider':
'provider' => Adldap\Laravel\Auth\NoDatabaseUserProvider::class,

'ldap' => [

    // Changed to 'uid':
    'locate_users_by' => 'uid',

    'bind_users_by' => 'distinguishedname',

],
```

I also understand your need for support - if you [sponsor](https://github.com/sponsors/stevebauman) me on GitHub - I can offer dedicated issue priority.

**Comment by muzammilaskari** [comment]
Hi @stevebauman ,

I really appreciate your help and I understand the usage too, but I am facing little trouble while using the `credentials` method, since I am using [test ldap server](https://www.forumsys.com/tutorials/integration-how-to/ldap/online-ldap-test-server/) adn I see that the method `authenticate` in `/Resolvers/UserResolver` class should receive `username` in format `uid=newton,dc=example,dc=com` format but when I dd username in `authenticate` method, it prints `newton` only. If I give static value `uid=newton,dc=example,dc=com` to the username, the code works fine and it logs me in. 

Could you please assist me in setting up configuration? I am attaching code of LoginController.php, ldap_auth.php and .env file in attachments.

Thanks in advance

**.env**

`APP_NAME=ldapAuth
APP_ENV=local
APP_KEY=base64:hJLQJiSQMEd/jWWVGOZV6027BAy5ozGkO/WSO7RvQBk=
APP_DEBUG=true
APP_URL=http://localhost

LOG_CHANNEL=stack

LDAP_SCHEMA=OpenLDAP
LDAP_HOSTS=ldap.forumsys.com
LDAP_BASE_DN=dc=example,dc=com
LDAP_USER_ATTRIBUTE=uid
LDAP_USER_FORMAT=uid=%s,dc=example,dc=com
LDAP_CONNECTION=default

DB_CONNECTION=sqlite

BROADCAST_DRIVER=log
CACHE_DRIVER=file
QUEUE_CONNECTION=sync
SESSION_DRIVER=file
SESSION_LIFETIME=120

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_DRIVER=smtp
MAIL_HOST=smtp.mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null
MAIL_FROM_ADDRESS=null
MAIL_FROM_NAME="${APP_NAME}"

AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_DEFAULT_REGION=us-east-1
AWS_BUCKET=

PUSHER_APP_ID=
PUSHER_APP_KEY=
PUSHER_APP_SECRET=
PUSHER_APP_CLUSTER=mt1

MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"`


**LoginController**

`namespace App\Http\Controllers\Auth;

use App\Http\Controllers\Controller;
use App\Providers\RouteServiceProvider;
use Illuminate\Foundation\Auth\AuthenticatesUsers;
use Illuminate\Http\Request;

class LoginController extends Controller
{
    /*
    |--------------------------------------------------------------------------
    | Login Controller
    |--------------------------------------------------------------------------
    |
    | This controller handles authenticating users for the application and
    | redirecting them to your home screen. The controller uses a trait
    | to conveniently provide its functionality to your applications.
    |
    */

    use AuthenticatesUsers;

    /**
     * Where to redirect users after login.
     *
     * @var string
     */
    protected $redirectTo = RouteServiceProvider::HOME;

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('guest')->except('logout');
    }

    public function username()
    {
        return 'username';
    }

    protected function credentials(Request $request)
    {
        return [
            'uid' =>  'newton',
            'password' => 'password',
        ];
    }
}`

**ldap_auth.php**
`<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Connection
    |--------------------------------------------------------------------------
    |
    | The LDAP connection to use for Laravel authentication.
    |
    | You must specify connections in your `config/ldap.php` configuration file.
    |
    */

    'connection' => env('LDAP_CONNECTION', 'default'),

    /*
    |--------------------------------------------------------------------------
    | Provider
    |--------------------------------------------------------------------------
    |
    | The LDAP authentication provider to use depending
    | if you require database synchronization.
    |
    | For synchronizing LDAP users to your local applications database, use the provider:
    |
    | Adldap\Laravel\Auth\DatabaseUserProvider::class
    |
    | Otherwise, if you just require LDAP authentication, use the provider:
    |
    | Adldap\Laravel\Auth\NoDatabaseUserProvider::class
    |
    */

    'provider' => Adldap\Laravel\Auth\NoDatabaseUserProvider::class,

    /*
    |--------------------------------------------------------------------------
    | Model
    |--------------------------------------------------------------------------
    |
    | The model to utilize for authentication and importing.
    |
    | This option is only applicable to the DatabaseUserProvider.
    |
    */

    'model' => App\User::class,

    /*
    |--------------------------------------------------------------------------
    | Rules
    |--------------------------------------------------------------------------
    |
    | Rules allow you to control user authentication requests depending on scenarios.
    |
    | You can create your own rules and insert them here.
    |
    | All rules must extend from the following class:
    |
    |   Adldap\Laravel\Validation\Rules\Rule
    |
    */

    'rules' => [

        // Denys deleted users from authenticating.

        Adldap\Laravel\Validation\Rules\DenyTrashed::class,

        // Allows only manually imported users to authenticate.

        // Adldap\Laravel\Validation\Rules\OnlyImported::class,

    ],

    /*
    |--------------------------------------------------------------------------
    | Scopes
    |--------------------------------------------------------------------------
    |
    | Scopes allow you to restrict the LDAP query that locates
    | users upon import and authentication.
    |
    | All scopes must implement the following interface:
    |
    |   Adldap\Laravel\Scopes\ScopeInterface
    |
    */

    'scopes' => [

        // Only allows users with a user principal name to authenticate.
        // Suitable when using ActiveDirectory.
        // Adldap\Laravel\Scopes\UpnScope::class,

        // Only allows users with a uid to authenticate.
        // Suitable when using OpenLDAP.
        // Adldap\Laravel\Scopes\UidScope::class,

    ],

    'identifiers' => [

        /*
        |--------------------------------------------------------------------------
        | LDAP
        |--------------------------------------------------------------------------
        |
        | Locate Users By:
        |
        |   This value is the users attribute you would like to locate LDAP
        |   users by in your directory.
        |
        |   For example, using the default configuration below, if you're
        |   authenticating users with an email address, your LDAP server
        |   will be queried for a user with the a `userprincipalname`
        |   equal to the entered email address.
        |
        | Bind Users By:
        |
        |   This value is the users attribute you would
        |   like to use to bind to your LDAP server.
        |
        |   For example, when a user is located by the above attribute,
        |   the users attribute you specify below will be used as
        |   the 'username' to bind to your LDAP server.
        |
        |   This is usually their distinguished name.
        |
        */

        'ldap' => [

            'locate_users_by' => env('LDAP_USER_ATTRIBUTE', 'uid'),
            'bind_users_by' => env('LDAP_USER_ATTRIBUTE', 'uid')

        ],

        'database' => [

            /*
            |--------------------------------------------------------------------------
            | GUID Column
            |--------------------------------------------------------------------------
            |
            | The value of this option is the database column that will contain the
            | LDAP users global identifier. This column does not need to be added
            | to the sync attributes below. It is synchronized automatically.
            |
            | This option is only applicable to the DatabaseUserProvider.
            |
            */

            'guid_column' => 'objectguid',

            /*
            |--------------------------------------------------------------------------
            | Username Column
            |--------------------------------------------------------------------------
            |
            | The value of this option is the database column that contains your
            | users login username.
            |
            | This column must be added to your sync attributes below to be
            | properly synchronized.
            |
            | This option is only applicable to the DatabaseUserProvider.
            |
            */

            'username_column' => 'username',

        ],

        /*
        |--------------------------------------------------------------------------
        | Windows Authentication Middleware (SSO)
        |--------------------------------------------------------------------------
        |
        | Local Users By:
        |
        |   This value is the users attribute you would like to locate LDAP
        |   users by in your directory.
        |
        |   For example, if 'samaccountname' is the value, then your LDAP server is
        |   queried for a user with the 'samaccountname' equal to the value of
        |   $_SERVER['AUTH_USER'].
        |
        |   If a user is found, they are imported (if using the DatabaseUserProvider)
        |   into your local database, then logged in.
        |
        | Server Key:
        |
        |    This value represents the 'key' of the $_SERVER
        |    array to pull the users account name from.
        |
        |    For example, $_SERVER['AUTH_USER'].
        |
        */

        'windows' => [

            'locate_users_by' => 'samaccountname',

            'server_key' => 'AUTH_USER',

        ],

    ],

    'passwords' => [

        /*
        |--------------------------------------------------------------------------
        | Password Sync
        |--------------------------------------------------------------------------
        |
        | The password sync option allows you to automatically synchronize users
        | LDAP passwords to your local database. These passwords are hashed
        | natively by Laravel using the Hash::make() method.
        |
        | Enabling this option would also allow users to login to their accounts
        | using the password last used when an LDAP connection was present.
        |
        | If this option is disabled, the local database account is applied a
        | random 16 character hashed password upon first login, and will
        | lose access to this account upon loss of LDAP connectivity.
        |
        | This option is only applicable to the DatabaseUserProvider.
        |
        */

        'sync' => env('LDAP_PASSWORD_SYNC', false),

        /*
        |--------------------------------------------------------------------------
        | Column
        |--------------------------------------------------------------------------
        |
        | This is the column of your users database table
        | that is used to store passwords.
        |
        | Set this to `null` if you do not have a password column.
        |
        | This option is only applicable to the DatabaseUserProvider.
        |
        */

        'column' => 'password',

    ],

    /*
    |--------------------------------------------------------------------------
    | Login Fallback
    |--------------------------------------------------------------------------
    |
    | The login fallback option allows you to login as a user located in the
    | local database if active directory authentication fails.
    |
    | Set this to true if you would like to enable it.
    |
    | This option is only applicable to the DatabaseUserProvider.
    |
    */

    'login_fallback' => env('LDAP_LOGIN_FALLBACK', false),

    /*
    |--------------------------------------------------------------------------
    | Sync Attributes
    |--------------------------------------------------------------------------
    |
    | Attributes specified here will be added / replaced on the user model
    | upon login, automatically synchronizing and keeping the attributes
    | up to date.
    |
    | The array key represents the users Laravel model key, and
    | the value represents the users LDAP attribute.
    |
    | You **must** include the users login attribute here.
    |
    | This option is only applicable to the DatabaseUserProvider.
    |
    */

    'sync_attributes' => [

        'username' => 'uid',
        'name' => 'cn',
        'phone' => 'telephonenumber',

    ],

    /*
    |--------------------------------------------------------------------------
    | Logging
    |--------------------------------------------------------------------------
    |
    | User authentication attempts will be logged using Laravel's
    | default logger if this setting is enabled.
    |
    | No credentials are logged, only usernames.
    |
    | This is usually stored in the '/storage/logs' directory
    | in the root of your application.
    |
    | This option is useful for debugging as well as auditing.
    |
    | You can freely remove any events you would not like to log below,
    | as well as use your own listeners if you would prefer.
    |
    */

    'logging' => [

        'enabled' => env('LDAP_LOGGING', true),

        'events' => [

            \Adldap\Laravel\Events\Importing::class                 => \Adldap\Laravel\Listeners\LogImport::class,
            \Adldap\Laravel\Events\Synchronized::class              => \Adldap\Laravel\Listeners\LogSynchronized::class,
            \Adldap\Laravel\Events\Synchronizing::class             => \Adldap\Laravel\Listeners\LogSynchronizing::class,
            \Adldap\Laravel\Events\Authenticated::class             => \Adldap\Laravel\Listeners\LogAuthenticated::class,
            \Adldap\Laravel\Events\Authenticating::class            => \Adldap\Laravel\Listeners\LogAuthentication::class,
            \Adldap\Laravel\Events\AuthenticationFailed::class      => \Adldap\Laravel\Listeners\LogAuthenticationFailure::class,
            \Adldap\Laravel\Events\AuthenticationRejected::class    => \Adldap\Laravel\Listeners\LogAuthenticationRejection::class,
            \Adldap\Laravel\Events\AuthenticationSuccessful::class  => \Adldap\Laravel\Listeners\LogAuthenticationSuccess::class,
            \Adldap\Laravel\Events\DiscoveredWithCredentials::class => \Adldap\Laravel\Listeners\LogDiscovery::class,
            \Adldap\Laravel\Events\AuthenticatedWithWindows::class  => \Adldap\Laravel\Listeners\LogWindowsAuth::class,
            \Adldap\Laravel\Events\AuthenticatedModelTrashed::class => \Adldap\Laravel\Listeners\LogTrashedModel::class,

        ],
    ],

];`

**Comment by muzammilaskari** [comment]
@stevebauman 
Thanks for your help, I had to provide `LDAP_ACCOUNT_PREFIX` and `LDAP_ACCOUNT_SUFFIX` in `.env` or` ldap.php` and after that i was able to login with `NoDatabaseUserProvider` and create session.

**Comment by muzammilaskari** [comment]
Hi @stevebauman 

Since I was using test LDAP server for my local development and I was able to login using **forumsys** but now I've deployed my project on Production and when I enter the details of my production LDAP server it says _the credentials are not correct_ 

I changed following entries. 

In `.env` file
```
LDAP_SCHEMA=OpenLDAP
LDAP_HOSTS=myserverhost
LDAP_BASE_DN=myserverdn
LDAP_CONNECTION=default
```
In `config/ldap_auth.php`
```
'ldap' => [

    // Changed to 'userprincipalname':
    'locate_users_by' => 'userprincipalname',

    'bind_users_by' => 'distinguishedname',

],
```
In `LoginController.php`

```
// app/Http/Controllers/Auth/LoginController.php

class LoginController extends Controller
{
    // ...

    protected function credentials(Request $request)
    {
        return [
            'userprincipalname' => $request->get('username'),
            'password' => $request->get('password'),
        ];
    }
}
```
It took my whole day to change configurations and do hit and try but it didn't work really, 
I tried adding `LDAP_ACCOUNT_SUFFIX` and `LDAP_ACCOUNT_PREFIX` in my `.env` as well but that didn't help. Please let me know where I am making mistake.

Thanks in advance for your help and time.
