### ISSUE TITLE
Import - Flag users in DB that are not in the AD Group

### ISSUE THREAD

**Issue by Groganj89** [Adldap2/Adldap2-Laravel#846]
- Laravel Version: 5.8
- Adldap2-Laravel Version: Latest
- PHP Version: 7.1
- LDAP Type: ActiveDirectory

### Description:

Hi Guys

I was wondering if there is a way when you run adldap:import, if people have been removed from the AD Group, it will recognize that in the database and not delete them, but flag them "as deleted" so to speak?

**Comment by stevebauman** [comment]
Hi @Groganj89,

Create an event listener for the following event:

```
Adldap\Laravel\Events\Synchronized
```

Then, inside your listener:

```php
public function handle(Synchronized $event)
{
    if (!$event->user->inGroup('My Group')) {
        $event->model->deleted = true;
    }
}
```

This will check if the user is not a member of `My Group`, then set a `deleted` column on the users database record to `true`.

**Comment by Groganj89** [comment]
Hi Steve

Sorry I have just been doing what you said then read what you put properly. I don't think this would work in my situation. 

So my filter imports/synchronises from a group lets call is "My_Group" and it syncronises and saves 4 individuals for example into the "People" table in my database. 

What I want to achieve is that if the person has been removed from the group on AD, that they are marked as "IsDeleted" in the MySQL database people table so that when we use our purge function in our app, it can see those that "IsDeleted = Yes" and purge them from the database. 

Do you think something like that is possible?
