### ISSUE TITLE
Can't connect to LDAP server - Using SSL

### ISSUE THREAD

**Issue by ZuggieTM** [Adldap2/Adldap2-Laravel#847]
- Laravel Version: 6
- Adldap2-Laravel Version: 6
- PHP Version: 7.3

I keep getting error message when trying to connect with SSL. I works perfectly fine without, but when I try to attach my Cert and connect, I just get "Can't contact LDAP server in C:\laragon\www\webmaster\vendor\adldap2\adldap2\src\Auth\Guard.php:107"

ldap.php

    'connections' => [

        'default' => [

            'auto_connect' => true,

            'connection' => Adldap\Connections\Ldap::class,

            'schema' => Adlap\Schemas\ActiveDirectory::class,

            'settings' => [
                'hosts' => explode(' ', env('LDAP_HOST')),
                'port' => env('LDAP_PORT', 389),
                'base_dn' => env('LDAP_BASE_DN'),
                'username' => env('LDAP_USERNAME'),
                'password' => env('LDAP_PASSWORD'),
                'use_ssl' => true,
                'use_tls' => false,
                'account_suffix' => '@domain.local',

                'custom_options' => [
                    LDAP_OPT_X_TLS_CACERTFILE => "c:/Users/jba/certs/ca.cert"
                ]
            ],
        ],
    ],

**Comment by stevebauman** [comment]
Hi @ZuggieTM,

You must use port `636` to connect to your LDAP server via SSL.

Also, to my knowledge, SSL LDAP connections do not require a client certificate. Only TLS connections do (hence LDAP_OPT_X_**TLS**_CACERTFILE)

**Comment by ZuggieTM** [comment]
It is using 636. setting 'use_ssl' sets it to 636 and doesn't look at 'port' => env('LDAP_PORT', 389)

[2020-02-24 14:06:35] local.WARNING: LDAP (ldaps://domain.local:636) - Connection: default - Operation: Failed - Username: user - Reason: Can't contact LDAP server

**Comment by stevebauman** [comment]
You're right - though unfortunately there isn't any assistance I can give you if your web server is reporting that it can't contact your LDAP server over SSL. You will need to login to your AD server and ensure it's configured and accessible.

If you're using Windows 10 Pro, you can enable ADSI edit and attempt connecting over SSL to ensure it is working properly.

**Comment by ZuggieTM** [comment]
LDAP is running on windows 2012 server and I'm connecting from my local machine running windows 10.

I tried using ldp.exe to test the connection and it seems to work just fine as long as the certificate from my ldap server is installed. As soon as i remove it from "Trusted" in my windows 10 certificates, it stops working. This is Why I'm trying to send the certificate from ADLDAP2 on my laravel application.

If this is not doable, would you know if I can disable the cert requirement on the ldap server?

**Comment by stevebauman** [comment]
In ldp.exe are you specifying port 636? Just ticking the boxes to make sure I'm on the same page as you.

**Comment by ZuggieTM** [comment]
Port is set to 636 and SSL is ticked.

**Comment by ZuggieTM** [comment]
ld = ldap_sslinit("domain.local", 636, 1);
Error 0 = ldap_set_option(hLdap, LDAP_OPT_PROTOCOL_VERSION, 3);
Error 81 = ldap_connect(hLdap, NULL);
Server error: <empty>
Error <0x51>: Fail to connect to domain.local.

**Comment by stevebauman** [comment]
Hmm okay let's try this. Create the following file on your computer:

```
C:\OpenLDAP\sysconf\ldap.conf
```

Edit it, and paste in:

```
TLS_REQCERT never
```

Then, restart your local web server and try connecting again in your Laravel application. Let me know how it goes!

**Comment by ZuggieTM** [comment]
Dude! I love you man! You seriously saved me from getting a ton of gray hair (more than I already have). It works!
I have no idea what that tiny files does, but it works!

Thank you so much! I need something to celebrate with now!

**Comment by stevebauman** [comment]
Haha I'm glad you're up and running! ❤️  Thanks so much for your kind words!

I'm a dirty liar by the way - I told you the wrong information:

> Also, to my knowledge, SSL LDAP connections do not require a client certificate. Only TLS connections do (hence LDAP_OPT_X_TLS_CACERTFILE)

By default, PHP will look at this location for an `ldap.conf` file. This file configures LDAP TLS / SSL connectivity. In the file you can specify a certificate file path so you're sure you're connected securely.

In regards to your second question - I've written about this on the new LdapRecord library:

https://ldaprecord.com/docs/configuration/#ssl-amp-tls

> The ldap.conf file is located in the following default locations:
> 
> Windows: `C:\OpenLDAP\sysconf\ldap.conf` (The directories will not exist, create them and add the file)
> Linux: `/etc/ldap/ldap.conf`

> However, using TLS_REQCERT never can be a bit of a security risk as it will ignore invalid certificates.
> 
> It's recommended to copy your domain CA cert to:
>
> Windows: `C:\OpenLDAP\sysconf`
> Linux: `/etc/ssl/certs`
> Then, reference it in your `ldap.conf` with the full file path using (replace my-custom-path with the location of the file):

```
TLS_CACERT my-custom-path/ca.pem
TLS_REQCERT hard
```

I'll close this for now but if you encounter any further issues feel free to create an issue and I'd be glad to help you out further. :smile:
