### ISSUE TITLE
ldap login with email

### ISSUE THREAD

**Issue by Moris1** [Adldap2/Adldap2-Laravel#849]
- Laravel Version: 6.16
- Adldap2-Laravel Version: 10.2
- PHP Version: 7.2
- LDAP Type: OpenLDAP

Dear adldap-laravel support/developers

Im trying to implement your package into Laravel 6.16.
I used your installation guide and guide on this page: https://github.com/jotaelesalinas/laravel-simple-ldap-auth

in app/Http/Controllers/Auth/LoginController
in method attemptLogin 

if I execute auth method with userdn bellow then response is TRUE.
$userdn = 'cn=John Doe,ou=users,dc=0xm,dc=net';
$ldap_auth = Adldap::auth()->attempt($userdn, $password, $bindAsUser = true);

But I want users to login with email address not username(John Doe, i use John Doe to not write here my name ;) ).

I guess I need to check first if provided email address matches any record in our ldap. And if it matches then I need to get users dn. 
Then I can run this auth method.

Could you help me please with that. Sorry if this is duplicated issue.
Thanks Jan

**Comment by stevebauman** [comment]
Hi @Moris1,

> I used your installation guide and guide on this page

That is not my installation guide - and as such I cannot support it.

Please create an issue on that repository and ask the author of that guide for assistance. Thanks!

**Comment by Moris1** [comment]
Hi Steve,

just ignore that foreign guide.

Adldap::auth()->attempt();
This is method from your package Adldap\Laravel\Facades\Adldap;

As I said if I use $userdn = 'cn=Jan Moravek,ou=users,dc=0xm,dc=net' 
Adldap::auth()->attempt($userdn, $password, $bindAsUser = true);

Then it works. I need to get first userdn based on email user submitted during login.
What adldap method should I use to get userdn based on email address?

Thanks
Jan

**Comment by stevebauman** [comment]
You must first configure a `username` and `password` inside of your `ldap.php` configuration so Adldap can connect and search your directory, prior to calling `auth()->attempt()` on your user to verify their credentials.

Then, you can perform the following:

```php
$user = Adldap::search()->users()->find('John Doe');

$ldap_auth = Adldap::auth()->attempt($user->getDn(), $password, $bindAsUser = true);
```

There is no way around providing credentials to Adldap to connect to your server to retrieve a user prior to calling the `auth()->attempt()` method - unless your LDAP server allows anonymous authentication.

**Comment by stevebauman** [comment]
The guide you've provided suggests using no credentials to connect to your LDAP server prior to calling `auth()->attempt()`. There is no way to retrieve a user from your LDAP server without **first** connecting to your LDAP server with a configured user account.

It's exactly like having your database credentials inside of your `.env` file. How would Laravel know to connect to your database without credentials? Answer: it can't. Adldap2 must know what credentials to use to search your LDAP directory.

**Comment by Moris1** [comment]
Hi Steve,
I really appreciate your help.
I'm really new to Laravel. I made setup of ldap.php and ldap_auth before.
I have setup domain administrator credentials in .enf
LDAP_USERNAME=cn=admin,dc=0xm,dc=net
LDAP_PASSWORD=*********

I will let you know when I have progress.
Thanks again 
Jan

**Comment by Moris1** [comment]
Hi Steve,

I'm getting NULL when searching for user by submitted email address($submittedaddress).
$user = Adldap::search()->users()->findBy('mail', $submittedaddress);

But Adldap should be connected because if I use Adldap::auth->attempt with correct userDn then I get true.

Could you advice?
Thanks
Jan

**Comment by Moris1** [comment]
Hi Steve,

by using findBy
Adldap::search()->where('mail', '=', 'johndoe@gmail.com')->get();
I get NULL

by using search->where
Adldap::search()->where('mail', '=', 'johndoe@gmail.com')->get()
I get collection object(Adldap\Query\Collection)
How can I get users dn from this collection?
And why findBy mail doesnt find the user but search where mail does find the user?

Thanks
Jan
