### ISSUE TITLE
[2.0] Find and Search working - but failing on Authentication

### ISSUE THREAD

**Issue by moth** [Adldap2/Adldap2-Laravel#85]
Hello,
I'm up and running with 5.2 and 2.0.*. In my instance, I need to `username` rather than email logins, and everything seems to be working with find and search;

`$user = Adldap::getProvider('default')->search()->users()->find('username');`
`$search = Adldap::getProvider('default')->search()->where('cn', '=', 'username')->get();`

Using Auth returns false;

`Adldap::getProvider('default')->auth()->attempt($username, $password)`

I've run through some closed issues here of a similar type - #188, but the closest I've got now is just via your docs.

Front-end error is ` These credentials do not match our records.`

Hope you can help!

Thanks,
Mike

**Comment by stevebauman** [comment]
Did you insert an `account_suffix` inside your configuration? This would be your domain controller:

```php
'account_suffix' => '@corp.acme.org',
```

This is appended on to the end of the users username **before** authenticating.

**Comment by moth** [comment]
No.. But Even with it (based off the `base_dn`) I get the same error.

**Comment by moth** [comment]
Ops. Sorry - I had that in `admin_account_suffix`, not `account_suffix`.

Logged in ;)

Thanks!

**Comment by stevebauman** [comment]
No problem at all, thanks the quick follow-up! :)
