### ISSUE TITLE
findBy mail doesnt work but search mail does

### ISSUE THREAD

**Issue by Moris1** [Adldap2/Adldap2-Laravel#850]
- Laravel Version: 6.16
- Adldap2-Laravel Version: 10.2
- PHP Version: 7.2
- LDAP Type: OpenLDAP

Adldap::search()->users()->findBy('mail', 'johndoe@gmail.com')
returns NULL

But using search->where I get my user
$user = Adldap::search()->where('mail', '=', 'johndoe@gmail.con')->first();

Why findBy mail doesnt find the user? Is it due to some ldap configuration?

When I call ->getGroups on $user found by search->where I get this error
Symfony\Component\Debug\Exception\FatalThrowableError
Call to undefined method Adldap\Models\Entry::getGroups()

Thanks for help
Jan

**Comment by stevebauman** [comment]
HI @Moris1,

It looks like you may have not switched your `schema` to OpenLDAP in your configuration:

```
// From...
'schema' => Adldap\Schemas\ActiveDirectory::class,

// To...
'schema' => Adldap\Schemas\OpenLDAP::class,
```

**Comment by Moris1** [comment]
Hi Steve,

you are completely right.
I really appreciate your help.
Now I can also call getGroups method. However it is empty.
I know its is not your job, but could you refer me to some manual(link) explaining what is the correct way to assign users to groups in phpldapadmin? 

Jan
