### ISSUE TITLE
[Question] Objectguid

### ISSUE THREAD

**Issue by Naghal** [Adldap2/Adldap2-Laravel#857]
- Laravel Version: 6.15
- Adldap2-Laravel Version: 6
- PHP Version: 7.4
- LDAP Type: ActiveDirectory 

**Context**
To migrate from version 5 to 6 of this package, we must now add `objectguid` column in our user model. However,  the user table I am working with is from a third party and I am not allowed to add fields in the table.

**Question**
 Is it possible to use v6 without a guid column?

**Comment by stevebauman** [comment]
Hi @Naghal,

Unfortunately no, and I honestly wouldn't recommend it if it was possible.

The `objectguid` is used to make sure the correct user is synchronized, even if their username changes.

In v5 and older versions of Adldap2-Laravel, if you changed a users username, it would create a brand new database user record for them the next time they signed in, which would break relationships and other data they may have been attached to in your database, requiring you to manually delete the new user record, and then update the old one.

I would probably extend the `DatabaseUserProvider` and insert your own custom one inside of the config here:

https://github.com/Adldap2/Adldap2-Laravel/blob/0c828772333936f4c26c1ce27bd372008eae7e6e/src/Config/auth.php#L36

Though this is very application specific so I can't really assist in the implementation.

Hope this helps!
