### ISSUE TITLE
Organizational limitations with GUID and Models

### ISSUE THREAD

**Issue by alanondra** [Adldap2/Adldap2-Laravel#861]
- Laravel Version: 6.18.2
- Adldap2-Laravel Version: 6.0.9
- PHP Version: 7.4.3
- LDAP Type: ActiveDirectory

### Description:

I am contending with the following organizational limitations. I cannot push back on any of these. I have to be able to use this specific package, with the following rules ("or else"):

- I cannot add a GUID column. I have to be able to resolve by username.
- Users fetched via the Auth facade must be database Models. We need to be able to query off of them, and adding an extra layer to resolving the Model adds complexity for team members not as familiar with Laravel
- The User table is the One Source of Truth and cannot be arbitrarily modified by any application except what is built specifically to modify it. This is not that application. I've attached an Observer to throw an Exception whenever a creating/updating/restoring/deleting event is dispatched.

If any modifications can be suggested to meet these requirements it would be appreciated. I've already spent the day trying to facilitate a variety of other changes and looking for workarounds for the above issues. I don't have the wiggle room for dogmatic approaches right now.

**Comment by stevebauman** [comment]
Hi @alanondra,

1. If your usernames in your directory *never* change, you should use the v5 branch. However, you will need to fork it and update for Laravel 6/7 compatibility.
2. Usernames in your database will obviously have to match the usernames in your Active Directory.
3. You'll need to make an authentication rule to prevent non-existing users to be created. This can be easily enabled by a default rule included in v5 of Adldap2-Laravel [here](https://github.com/Adldap2/Adldap2-Laravel/blob/v5.1.3/src/Validation/Rules/OnlyImported.php).

Hope this helps!

**Comment by alanondra** [comment]
1. Usernames may change. Not sure we can or should fork it. It defeats the entire purpose of trying to use a version-controlled external library for a task we don't have the bandwidth to maintain.
2. Understood.
3. Thanks, I'll take a look at this to see how it works.

**Comment by stevebauman** [comment]
> Usernames may change.

Actually, since Adldap2-Laravel won't be able to update or create user records, you can ignore my statement about it. My mistake.

> Not sure we can or should fork it. It defeats the entire purpose of trying to use a version-controlled external library for a task we don't have the bandwidth to maintain.

That's the only way unfortunately. I simply can't justify the time or purpose for updating past branches for current Laravel compatibility.

Closing this, but feel free to comment back if you have any further questions and I'll do my best to help you out 👍

**Comment by stevebauman** [comment]
You absolutely can -- the code is MIT and open-source.

**Comment by stevebauman** [comment]
That sounds rough -- I'm not sure what else to tell you honestly. When v6 was built - GUID's were intended to be a mandatory requirement.

I'm not able to spend time on building a feature set that is required for your application, unless you're willing to pay of course. ❤️
