### ISSUE TITLE
Scopes Are Not Working in LUMEN

### ISSUE THREAD

**Issue by anuragyadav8949** [Adldap2/Adldap2-Laravel#864]
@stevebauman  Hey, I need a little help here, 
please help me to resolve this issue as soon as possible

As I am trying to implement Adldap into **LUMEN**
My Authentication working perfectly! everything is running good
but the scope is not working
Where i am restricting a user if he is not a member of that group.

As described into Documentation of Scope (https://adldap2.github.io/Adldap2-Laravel/#/auth/setup?id=scopes)
I remove comment in file  **ldap_auth.php** in scopes array as described.

`$scopes => [
Adldap\Laravel\Scopes\UpnScope::class, 
BVIPackage\LdapAuth\PMToolScopes::class
],`

The PMToolScopes file is where we are checking user belongs to the group or not
`<?php
namespace BVIPackage\LdapAuth;

//namespace Adldap\Laravel\Scopes;

use Adldap\Query\Builder;
use Adldap\Laravel\Scopes\ScopeInterface;

class PMToolScopes implements ScopeInterface
{
    /**
     * Apply the scope to a given LDAP query builder.
     *
     * @param Builder $query
     *
     * @return void
     */
    public function apply(Builder $query)
    {
        // The distinguished name of our LDAP group.
       //LDAP_BASE_DN="CN=Employee,OU=Managers,OU=Leaders,DC=example,DC=com"	
        $scopes = env('LDAP_BASE_DN');
        $query->whereMemberOf($scopes);
    }
}
`

The Authentication i have written into trait 
where the authentication is working perfectly,
`if (Adldap::auth()->attempt('$username', $password, $bindAsUser = true)) {
            //dd($user = Auth::user());
            dd('LDAP authenticated');
}else {
dd(''LDAP Authentication Failed);
}`

**My Issue here is File name PMTool.php it is not  executed**
to check whether the user belongs to the group or not,
I am not getting the life cycle the way it will execute neither a dd() is working,
And if i made some syntax error then too m not getting any error, and getting authenticated**

What i am doing wrong do i need to add the PMTool.php file into ServiceProvide of the package?
or something else
The inbuilt file Adldap\Laravel\Scopes\UpnScope::class,  is also not getting executed
_(i didi some syntact error into that but then to authentication has no error)_

**Some INFO ABOUT THE LDAP**
I am using **OpenLDAP**
The authentication method is **SASL**

ldapsearch using cmd
ldapsearch -h <ip> -p 389 -D <mailid> -w <pwd> -b CN=Employee,OU=Managers,OU=Leaders,DC=example,DC=com
which is giving me a record (So it seems this is working OK)

**Comment by stevebauman** [comment]
Hi @anuragyadav8949,

This is wrong:

```php
if (Adldap::auth()->attempt('$username', $password, $bindAsUser = true)) {
    //dd($user = Auth::user()); dd('LDAP authenticated');
} else {
    dd(''LDAP Authentication Failed);
}
```

You must use Laravel's native  `Auth::attempt()`, which I don't believe is available in Lumen.

**Adldap2-Laravel's authentication driver is meant to be used with Laravel, not Lumen.**

See:

https://lumen.laravel.com/docs/7.x/authentication

**Comment by stevebauman** [comment]
To elaborate, I simply can't help as I don't use Lumen myself -- I don't have enough knowledge on what works and what doesn't.

From what I do understand, you will likely have to implement your own way to execute scopes if you are using Lumen and not Laravel. Adldap2-Laravel adds a new Laravel authentication driver that utilizes sessions, and Lumen **does not use sessions**:

> Since Lumen does not support session state, incoming requests that you wish to authenticate must be authenticated via a stateless mechanism such as API tokens.

**Comment by anuragyadav8949** [comment]
> Hi @anuragyadav8949,
> 
> This is wrong:
> 
> ```
> if (Adldap::auth()->attempt('$username', $password, $bindAsUser = true)) {
>     //dd($user = Auth::user()); dd('LDAP authenticated');
> } else {
>     dd(''LDAP Authentication Failed);
> }
> ```
> 
> You must use Laravel's native `Auth::attempt()`, which I don't believe is available in Lumen.
> 
> **Adldap2-Laravel's authentication driver is meant to be used with Laravel, not Lumen.**
> 
> See:
> 
> https://lumen.laravel.com/docs/7.x/authentication

Thank you soo much for the reply.
This authentication method I have referenced from the Adlap2-laravel documentation.
And my authentication works perfectly on the server

**Comment by anuragyadav8949** [comment]
> To elaborate, I simply can't help as I don't use Lumen myself -- I don't have enough knowledge on what works and what doesn't.
> 
> From what I do understand, you will likely have to implement your own way to execute scopes if you are using Lumen and not Laravel. Adldap2-Laravel adds a new Laravel authentication driver that utilizes sessions, and Lumen **does not use sessions**:
> 
> > Since Lumen does not support session state, incoming requests that you wish to authenticate must be authenticated via a stateless mechanism such as API tokens.

Thank you soo much for looking into my concern will extend the functionality to make it work in Lumen.
Thank you soo much for the help @stevebauman
