### ISSUE TITLE
ldap_modify_batch(): Naming violation

### ISSUE THREAD

**Issue by pi-paul** [Adldap2/Adldap2-Laravel#868]
- Laravel Version: 5.7
- Adldap2-Laravel Version: 5.1
- PHP Version: 7.1.3
- LDAP Type: OpenLDAP

### Description:

I'm unable to update user CN for some reason.

```
$user = Adldap::getProvider(config('adldap.connection'))->search()->where('cn', '=', 'user@email.com')->first();
$user->cn = 'user2@email.com';
$user->update();
```

It returns the following error,
PHP Warning:  ldap_modify_batch(): Batch Modify: Naming violation in /var/www/http/vendor/adldap2/adldap2/src/Connections/Ldap.php on line 309

The user exists.

Same error when I try setAttribute()
`$user->setAttribute('cn', 'user2@email.com');`

Not sure what I'm doing wrong.

**Comment by stevebauman** [comment]
Hi @pi-paul,

You cannot modify a `cn` (common name) directly. A rename operation must be performed.

https://adldap2.github.io/Adldap2/#/models/model?id=moving-renaming
