### ISSUE TITLE
How to use AdldapUserModelTrait other than in User Model

### ISSUE THREAD

**Issue by bahjaat** [Adldap2/Adldap2-Laravel#87]
>class Employee extends Model
>{
>    use AdldapUserModelTrait;
> ....

Got a DB field named 'username'.

>$employee = Employee::find(1);
>$employee->adldapUser

is returning NULL

Is this posible?

**Comment by stevebauman** [comment]
Is `Employee` your configured auth driver model in `config/auth.php`?

**Comment by bahjaat** [comment]
No, that's my `User` class and is working fine (with a column call `username`).
Beside that I have an `Employee` class with also a column called `username` which is 'connected' to my Active Directory.
I am trying to use the trait in my `Employee` class too, but without success.

Did something like this in my model as a workaround
<pre>
public function getAdldapUserAttribute() {
        $adldapUser = \Adldap::getProvider('default')->search()->users()->find($this->username);
        if (!is_null($adldapUser)) return $adldapUser;
        throw new \Adldap\Exceptions\ModelNotFoundException(sprintf('AdldapUser (%s) not found', $this->username));
}
</pre>

**Comment by stevebauman** [comment]
This trait is only meant to be applied to the User model that is associated with your logged in users. The `adldapUser` property will always be null for users that aren't logged in.

The goal for this was to easily retrieve the current logged in LDAP user details on demand using the config option `bind_user_to_model` option.

Using an accessor like you've shown would be too resource intensive. For example:

```php
$users = User::all();

foreach ($users as $user) {
    // For each individual user, this would query your AD server.
    //So potentially, if we retrieve 500 users from our local DB,
    /// we'd hit our AD server 500 times.
    $user->adldapUser;
}
```

**Comment by bahjaat** [comment]
Ok, thanks for letting me know.
