### ISSUE TITLE
Illuminate\Support\Traits\ForwardsCalls not found

### ISSUE THREAD

**Issue by riples** [Adldap2/Adldap2-Laravel#872]
- Laravel Version: 5.6
- Adldap2-Laravel Version: 6.1
- PHP Version: 7.4
- LDAP Type: ActiveDirectory

### Description:
My local test environment upgraded Adldap2 from 6.0 => 6.1 and has since broken my authentication process.  Laravel now hard faults with the error `Symfony\Component\Debug\Exception\FatalErrorException: Trait &#039;Illuminate\Support\Traits\ForwardsCalls&#039; not found in file /home/vagrant/Code/dras/vendor/adldap2/adldap2-laravel/src/Auth/DatabaseUserProvider.php on line 23` when trying to call the Adldap2 library.

Having a look at the source files, I notice that `DatabaseUserProvider.php` now makes a call to `Illuminate\Support\Traits\ForwardCalls`, however, this file does not exist.  This seems to be a new piece of code in version 6.1, but I cannot find any release notes around this, nor can I find any reference to this in the upgrade documentation on the website.

**Comment by stevebauman** [comment]
Shoot this is my mistake @riples.

I verified in early versions of Laravel, but I did not test in 5.6.

Give me a moment to make a patch — thanks so much for notifying me of this.

**Comment by riples** [comment]
No stress at all.  
Thanks for sorting this out.

**Comment by stevebauman** [comment]
Ok we're all set! :tada:

Run `composer update` in a moment to pull in [v6.1.1](https://github.com/Adldap2/Adldap2-Laravel/releases/tag/v6.1.1).

Thanks again!

**Comment by riples** [comment]
Thanks heaps @stevebauman for the speedy turnaround.
