### ISSUE TITLE
On import/sync does the user's id remain consistent?

### ISSUE THREAD

**Issue by mkered77** [Adldap2/Adldap2-Laravel#877]
- Laravel Version: Latest
- Adldap2-Laravel Version: Latest
- PHP Version: 7.2.27
- LDAP Type: ActiveDirectory

I have successfully set up my connection and imported all the users in AD. 

Question: When I sync my users via import on the CLI, will the id for each user remain unchanged? I've created a simple asset management application that requires the user's id be used as an identifier for who is in possession of an asset. In my Google searches and documentation reading, I can't find this information.

**Comment by stevebauman** [comment]
Hi @mkered77,

The users database ID will not change -- nor will the users `objectguid`.

The only thing that may change would be your users username email address, or other information you choose to synchronize -- if they change in your Active Directory server.

Adldap2-Laravel uses the users Object GUID to synchronize each record, so this is not an issue.

Hope this helps!

**Comment by mkered77** [comment]
Awesome. Just wanted to confirm. Thanks for the info and the very useful package.

**Comment by stevebauman** [comment]
Happy to help @mkered77! :smile:

Thanks for your kind words. ❤️
