### ISSUE TITLE
f

### ISSUE THREAD

**Issue by nyneplus** [Adldap2/Adldap2-Laravel#878]
- Laravel Version: #.#
- Adldap2-Laravel Version: #.#
- PHP Version: #.#
- LDAP Type:

**Comment by stevebauman** [comment]
Going to need some details 👍

**Comment by nyneplus** [comment]
I am very sorry. I had the page open but was away. I guess it was my cat running over my keyboard

**Comment by stevebauman** [comment]
Lol no problem @nyneplus! ❤️
