### ISSUE TITLE
Two Hosts with different base_dn for import users

### ISSUE THREAD

**Issue by olkotz** [Adldap2/Adldap2-Laravel#883]
I have a question about import:

Can i have two differents host an each one has your own base dn and the command imports me the users of both Active Directory?

Example: LDAP_HOSTS=14.222.14.12 10.225.16.46 and LDAP_BASE_DN="DC=example.base.dn,DC=net" "DC=example2.base.dn,DC=com"

The both active directory have the same user and password for import

**Comment by stevebauman** [comment]
Hi @olkotz,

Adldap2-Laravel doesn't support importing or authenticating from multiple LDAP connections. If you need this, you must use [LdapRecord-Laravel](https://github.com/DirectoryTree/LdapRecord-Laravel) instead.

Thanks!
