### ISSUE TITLE
Post ADLDAP sync processing

### ISSUE THREAD

**Issue by schn-webmaster** [Adldap2/Adldap2-Laravel#886]
- Laravel Version: 5.8
- Adldap2-Laravel Version: 6.0.7
- PHP Version: 7.1.33
- LDAP Type: ActiveDirectory

### Description: Where/when/how to implement post ADLDAP sync process

The 'cn' in the AD that I am using has inconsistent formatting.

I am using 'cn' as one of the sync_attributes, but I need to do some post sync processing to clean it up.

What is the recommended way to implement post sync processing ?

**Comment by stevebauman** [comment]
Hi @schn-webmaster, I would recommend you use an Attribute Handler to perform this required attribute processing *during* synchronization rather than after:

https://adldap2.github.io/Adldap2-Laravel/#/auth/setup?id=attribute-handlers

Hope this helps!
