### ISSUE TITLE
Help with recent Laravel integration

### ISSUE THREAD

**Issue by justageek** [Adldap2/Adldap2-Laravel#891]
- Laravel Version: 6.18.6
- Adldap2-Laravel Version: 10.3.0
- PHP Version:7.3
- LDAP Type: ActiveDirectory

### Description:

Hi Steve,  you helped us integrate your library to it hits 2 different ldap servers during authentication, and I am just now gettnig back to the code because we sat on the new feature forever, I'm getting an error Undefined property: App\Auth\AuditPortalUserProvider::$eloquent during authentication, and I have no idea why it suddenly stopped working, I have tested this completely before, so something must have changed.  Any guidance is appreciated.

**Comment by stevebauman** [comment]
Hi @justageek,

Can you post the code for `AuditPortalUserProvider`?

**Comment by justageek** [comment]
Steve, I feel dumb, all I needed to do was re-run composer install, so you can close this.

**Comment by stevebauman** [comment]
No problem @justageek! Happens to all of us 😄 

Thanks for the quick follow up 👍
