### ISSUE TITLE
problem with two factor authentication

### ISSUE THREAD

**Issue by dcorrea-estrav** [Adldap2/Adldap2-Laravel#894]
- Laravel Version: 8.6
- Adldap2-Laravel Version: 1.7.2
- PHP Version: 7.4
- LDAP Type:  ActiveDirectory 

### Description:
Normal authentication works quite well, but when I try to configure the two-factor authentication that laravel 8 brings, I have a problem trying to validate the token.
![Captura de pantalla 2020-09-29 a la(s) 10 41 44 a  m](https://user-images.githubusercontent.com/54317215/94581324-8ce65580-0240-11eb-95bb-7c5806b58c7e.png)

**Comment by stevebauman** [comment]
Hi @dcorrea-estrav,

I think you may have intended to post this on the LdapRecord-Laravel repository, but no worries 👍 

You cannot use two-factor authentication with LdapRecord-Laravel. You must disable it inside of your `config/fortify.php` file in the `features` key.

**Comment by dcorrea-estrav** [comment]
> Hi @dcorrea-estrav,
> 
> I think you may have intended to post this on the LdapRecord-Laravel repository, but no worries 👍
> 
> You cannot use two-factor authentication with LdapRecord-Laravel. You must disable it inside of your `config/fortify.php` file in the `features` key.

Thanks for your help

**Comment by stevebauman** [comment]
No problem @dcorrea-estrav!

I am however going to see if this is something I can implement and get working with LdapRecord-Laravel. Stay tuned for updates on the [LdapRecord-Laravel](https://github.com/DirectoryTree/LdapRecord-Laravel) repository! 👍

**Comment by ivanomatteo** [comment]
```
/**
 * workaround for two factor auth
 */
class LaravelLdapUserProvider extends DatabaseUserProvider
{

    public function validateCredentials(Authenticatable $model, array $credentials)
    {
        if (!$this->retrieveByCredentials([
            config('fortify.username') => $model->name,
            'password' => $credentials['password'],
        ])) {
            return false;
        }
        return parent::validateCredentials($model, $credentials);
    }
}
```
