### ISSUE TITLE
Soft Delete Users who are no longer in Active Directory

### ISSUE THREAD

**Issue by kellerisddev** [Adldap2/Adldap2-Laravel#896]
- Laravel Version: 5.8
- Adldap2-Laravel Version: Latest
- PHP Version: 7.4
- LDAP Type: ActiveDirectory

Is there any way to soft delete database users who are no longer in Active Directory?

I have soft deletes set up and working.   I perform a nightly adldap import and ideally I would like to soft delete uses who are no longer returned on import.

Thanks

**Comment by kellerisddev** [comment]
I found another way to go about this.

**Comment by stevebauman** [comment]
Hi @kellerisddev, glad you were able to figure this out!

This is actually an included feature in LdapRecord-Laravel if you’re ever looking to make the jump.

I appreciate you closing the issue out 👍
