### ISSUE TITLE
Different username_attribute

### ISSUE THREAD

**Issue by strebl** [Adldap2/Adldap2-laravel#9]
Hey @stevebauman, I started playing with the package, great work! :+1: 

While playing around, I found an error.
If you have a User Model without an email address, you can't login.

I think following lines need to be more generalized: https://github.com/Adldap2/Adldap2-laravel/blob/master/src/AdldapAuthUserProvider.php#L83-L103

The login fails, because it tries to insert an email address to the database which doesn't exist there.

**Comment by stevebauman** [comment]
Yup absolutely right, definitely not intended. Fixing now, thanks!
