### ISSUE TITLE
Microsoft Azure compatibility

### ISSUE THREAD

**Issue by freescout-helpdesk** [Adldap2/Adldap2-Laravel#900]
- Laravel Version: 5.5
- Adldap2-Laravel Version: v4.0.10
- PHP Version: 7.2
- LDAP Type: ActiveDirectory

### Description:
Is Adldap2 compatible with Microsoft Azure Active Directory? There is an issue connecting to the Azure: https://github.com/freescout-helpdesk/freescout/issues/869

### Steps To Reproduce:
Try to connect to Microsoft Azure Active Directory.

**Comment by stevebauman** [comment]
Hi @freescout-helpdesk,

It is, but you will have to configure Azure AD Domain Services to offer an LDAPS endpoint to connect to:

https://docs.microsoft.com/en-us/azure/active-directory-domain-services/tutorial-configure-ldaps

I hope this helps! Let me know if you have any further questions 👍

**Comment by freescout-helpdesk** [comment]
Resolved:

> it turns out that you have two admin prefixes set cn= and uid=, looking at the ADDS documentation for the bind request
> https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-adts/6a5891b8-928e-4b75-a4a5-0e3b77eaca52
> 
> AADS expects allows the use of the full DN to do the match so instead of using the username (sAMAccountName) to do the login, I was able to bind use the CN.
> 
> For anyone in the future attempting this, install active directory explorer onto a joined machine and find the full DN of the user. The ldap module sets the bindrequest using "CN={bind user},{Bind DN string}"
