### ISSUE TITLE
Rules/DenyTrashed Throws error - PHP 8.0

### ISSUE THREAD

**Issue by Honokai** [Adldap2/Adldap2-Laravel#907]
## Environment
- Laravel Version: 8.26.1
- Adldap2-Laravel Version: 6.1.4
- PHP Version: 8.0.2
- LDAP Type: ActiveDirectory

### Description:
On auth validation, Rule **DenyTrashed** throws error on php 8, where on older php versions would be a warning.
 
I did a work-around creating a rule pretty much the same but adding a condition to function `isTrashed()`
```php
if ($this->model == null) {
    return false;
} else {
    return method_exists($this->model, 'trashed') && $this->model->trashed();
}
```
![image](https://user-images.githubusercontent.com/54319084/107808277-1312bc80-6d48-11eb-8c33-c4dd96a4d2ba.png)

**Comment by stevebauman** [comment]
Hi @Honokai,

This has been resolved via a PR that I just merged: #906 

I'll make a new release shortly containing this fix 👍
