### ISSUE TITLE
Active Directory command for DN is not showing the result.

### ISSUE THREAD

**Issue by Renu-2610** [Adldap2/Adldap2-Laravel#908]
I am using active directory (ADLDAP2 in Laravel)

when I fired this command "php artisan adldap:import". It shows all the userlist. but  when I use this with DN like "php artisan adldap:import --filter "(CN=Grp_TAMS_Admins,OU=Service Accounts,DC=ems,DC=gov,DC=kw)" ". Its showing "There were no users found to import."

can anyone help me out ?

![image](https://user-images.githubusercontent.com/74037105/110066215-eb3ad580-7d96-11eb-90eb-1a149f865fff.png)

**Comment by stevebauman** [comment]
Hi @Renu-2610,

The syntax of your filter is wrong -- I believe this is what you're looking for:

```bash
php artisan adldap:import --filter "(memberOf=CN=Grp_TAMS_Admins,OU=Service Accounts,DC=ems,DC=goc,DC=kw)"
```

Can you give that a shot?

**Comment by Renu-2610** [comment]
Hello @stevebauman,

Thanks for this command, Now it's working.
