### ISSUE TITLE
Sync Password not working 

### ISSUE THREAD

**Issue by starking8b** [Adldap2/Adldap2-Laravel#910]
I  want to import users from my LDAP database to MySQL database with passwords to allow users log in by there default password. I enabled the sync password option but it seems to generate a random password, so users not able to log in using their own LDAP password 
  ```
 'passwords' => [
 
        'sync' => env('LDAP_PASSWORD_SYNC', true),

      'column' => 'password',

    ],
```
and when  I running this command 
`php artisan adldap:import`
it importing users but the passwords are wrong

**Comment by stevebauman** [comment]
Hi @starking8b,

Password synchronization only works on a per-user basis during authentication, as this is the only time the password is available in plain text, and can be hashed securely.

You cannot access a users LDAP password during import, or through any other means. This would be a massive security risk if this were possible, as you could effectively dump the your LDAP directory and all of their passwords in plain text.

Hope this helps!

**Comment by manuEbg** [comment]
> 
> 
> Hi @starking8b,
> 
> Password synchronization only works on a per-user basis **_during authentication_**, as this is the only time the password is available in plain text, and can be hashed securely.
> 
> You cannot access a users LDAP password during import, or through any other means. This would be a massive security risk if this were possible, as you could effectively dump the your LDAP directory and all of their passwords in plain text.
> 
> Hope this helps!

Hello, I am also facing this problem right now.
Do you mean that when the user logs into my webpage, i ask the LdapServer if the credentials are correct. In this case i would store them to the Database?
