### ISSUE TITLE
Create new user with sync attributes

### ISSUE THREAD

**Issue by jtoler** [Adldap2/Adldap2-Laravel#92]
I do not know if this is possible at all....

When the user logs in and adds the user to the user table with the sync attributes I have set up; which is perfect.... Since I am using Adldap for authentication, I need no registration and therefore have no create user method set up. I have created a method that will search an adldap group of about 300-400 users and return those users successfully. 

`$users = $this->adldap->getProvider('default')->search()->users()->rawFilter($filter)->get();`

I would like to pre enter these users into my users table the same way it does when I log in for the first time. I would like to do this because I need to be able to create permission and roles for each user ahead of time. Is there someway to call what method does the actual table insert when you log in?

**Comment by stevebauman** [comment]
Hey @jtoler,

Yup it's possible, you actually just need to `use` the trait `Adldap\Laravel\Traits\ImportsUsers` trait.

Here's an example of usage:

```php
class UserController extends Controller
{
    use ImportsUsers;

    /**
     * Returns a new auth model instance.
     *
     * @return \Illuminate\Database\Eloquent\Model
     */
    public function createModel()
    {
        $model = $this->auth->getProvider()->getModel();

        return new $model();
    }

    public function import()
    {
        $users = $this->adldap->getProvider('default')->search()->users()->rawFilter($filter)->get();

        foreach ($users as $user) {
            $this->getModelFromAdldap($user, str_random());
        }
    }
}
```

**Comment by jtoler** [comment]
Thanks!

**Comment by stevebauman** [comment]
No problem :)

**Comment by jtoler** [comment]
Actually can you please possibly answer one more thing? 
```
foreach ($users as $user) {
       $this->getModelFromAdldap($user, str_random());
}
```
What if I wanted to change a $user variable? Like say I wanted to set $user->department = "Department"? If I do it before the getModelFromAdldap would it change anything?

**Comment by stevebauman** [comment]
If you manually set the Adldap users department, that will be what is imported into your local website database.

**Comment by jtoler** [comment]
You sir, are awesome! Thanks again!

**Comment by jtoler** [comment]
One last issue I would like to fix... I am trying to implement Entrust for roles and permissions.
https://github.com/Zizaco/entrust

This works inside my routes.php as a function:
```
$user1 = App\User::find(1);
$role = Role::where('name','=','Custom Role')->first();
$user1->attachRole($role);
```

But this doesn't work in the import function. 
```
$role = Role::where('name','=','Custom Role')->first();
$user->attachRole($role);
```
I get:
`Fatal error: Call to undefined method Adldap\Models\User::roles()`

I assume because however Entrust creates those methods the getModelfromAdldap does not find them? Would I have to possibly create a "ldapAtrributeHandler" of some sort? I could just say User::find($id) in the import loop but that would most likely double the time the import function is already taking looking for 400+ users.

**Comment by stevebauman** [comment]
> I get:
Fatal error: Call to undefined method Adldap\Models\User::roles()

That would be correct. The `$user` variable show above is an instance of `Adldap\Models\User`, not your laravel `App\User` model.

> Would I have to possibly create a "ldapAtrributeHandler" of some sort?

Actually, I'd recommend overriding the `ImportsUsers` trait method `syncModelFromAdldap(User $user, Authenticatable $model)`. That way you have both models in hand. Be sure to call the parent trait method though.

**Comment by jtoler** [comment]
Could you be so kind as to show me what you mean exactly with the example you gave me in your first reply above?

**Comment by stevebauman** [comment]
> Could you be so kind as to show me what you mean exactly with the example you gave me in your first reply above?

Of course, here's an example:

```php
use Adldap\Laravel\Traits\ImportsUsers;
use Adldap\Models\User;
use Illuminate\Contracts\Auth\Authenticatable;

class UserController extends Controller
{
    use ImportsUsers {
        syncModelFromAdldap as traitSyncModelFromAdldap;
    }

    /**
     * {@inheritdoc}
     */
    public function syncModelFromAdldap(User $user, Authenticatable $model)
    {
        $this->syncModelFromAdldap($user, $model);

        $role = Role::where('name', '=', 'Administrator')->first();

        if ($user->inGroup('Domain Admins')) {
            // Looks like this AD user is a domain admin.
            // We'll give them the administrator role.
            $model->attachRole($role);
        }
    }
}
```

**Comment by jtoler** [comment]
That makes sense now! Although every time I run the import it duplicates the users and attached roles. Is it because of the createModel()? I want it to be a new user or update the user every time it is ran.

**Comment by stevebauman** [comment]
Ah yes you're right, typo! Changed:

From:
```php
foreach ($users as $user) {
    $this->syncModelFromAdldap($user, str_random());
}
```

To:
```php
foreach ($users as $user) {
    $this->getModelFromAdldap($user, str_random());
}
```

**Comment by jtoler** [comment]
Doing that gives me this error:

> Type error: Argument 2 passed to App\Http\Controllers\UserImportController::bindAdldapToModel() must implement interface Illuminate\Contracts\Auth\Authenticatable, null given

This is what I have based off your kind and much appreciated help... I do have those lines commented out in importAUsers() when I get this error based off that change.
```
use Adldap\Contracts\AdldapInterface;
use Adldap\Laravel\Traits\ImportsUsers;
use Adldap\Models\User;
use Illuminate\Contracts\Auth\Authenticatable;
use App\Role;

class UserImportController extends Controller
{
    use ImportsUsers {
        syncModelFromAdldap as traitSyncModelFromAdldap;
    }

    /**
     * @var AdldapInterface
     */
    protected $adldap;

    /**
     * Constructor.
     *
     * @param AdldapInterface $adldap
     */
    public function __construct(AdldapInterface $adldap)
    {
        $this->adldap = $adldap;
    }

    /**
     * Returns new a new eloquent user instance.
     *
     * @return Models\User
     */
    public function createModel()
    {
        return new \App\User();
    }

    /**
     * {@inheritdoc}
     */
    protected function syncModelFromAdldap(User $user, Authenticatable $model)
    {
        // We're calling the parent trait sync method. This will actually create
        // the user in our local database if they don't already exist.
        $this->traitSyncModelFromAdldap($user, $model);

        // Grab our local administrator role.
        $role = Role::where('name', '=', 'staff')->firstOrFail();
        $model->attachRole($role);
    }

    /**
     * Imports users into the local database.
     *
     * @internal param $users
     */
    public function importAllUsers()
    {
        // Import A users
        foreach ($this->getAUsers() as $user) {
            // Assign user as a member of department
            $user->department = 'Department 1';
           /** This is where I would really like to set the roles. But trying it your way for now and have this commented out .**/
            //$role = Role::where('name', '=', 'staff')->firstOrFail();
            //$model->attachRole($role);
        }

        // Import B users
        foreach ($this->getBUsers() as $user) {
             $user->department = 'Department 2';
            $this->getModelFromAdldap($user, str_random());
        }
    }
```

**Comment by stevebauman** [comment]
Ohhh yes apologies, you need to return the laravel model inside the `syncModelFromAdldap()` method:

```php
/**
 * {@inheritdoc}
 */
protected function syncModelFromAdldap(User $user, Authenticatable $model)
{
    // We're calling the parent trait sync method. This will set all attributes on the
    // model that we have in our adldap_auth.php configuration.
    $this->traitSyncModelFromAdldap($user, $model);

    // Grab our local administrator role.
    $role = Role::where('name', '=', 'Administrator')->firstOrFail();

    // Check if our AD user is a domain admin.
    if ($user->inGroup('Domain Admins')) {
        // Looks like this AD user is a domain admin.
        // We'll give them the administrator role.
        $model->attachRole($role);
    }

    return $model;
}
```

**Comment by jtoler** [comment]
How could I set the role in each for loop? Because the way I have it set up, I only know what their role should be if inside the for loop. Example: I tried to do something like this...
```
foreach ($this->getAUsers() as $user) {
            // Assign user as a member of department
            $user->department = 'Department 1';
            $model = $this->syncModelFromAdldap($user, $this->createModel());
            $role = Role::where('name', '=', 'staff')->firstOrFail();
            $model->attachRole($role);
}
```

Just so you know I am feeling bad to keep asking for you help with this!

**Comment by jtoler** [comment]
There is no central group in LDAP so each getXUsers gets particular group already.

**Comment by stevebauman** [comment]
The method `getModelFromAdldap()` returns the updated / created laravel user model.

```php
/**
 * Imports users into the local database.
 *
 * @internal param $users
 */
public function importAllUsers()
{
    // Import A users
    foreach ($this->getAUsers() as $user) {
        // Assign user as a member of department
        $user->department = 'Department 1';

        $model = $this->getModelFromAdldap($user, str_random());

        $role = Role::where('name', '=', 'staff')->firstOrFail();

        $model->attachRole($role);
    }

    // Import B users
    foreach ($this->getBUsers() as $user) {
        $user->department = 'Department 2';
        $this->getModelFromAdldap($user, str_random());
    }
}
```

**Comment by jtoler** [comment]
Thanks! Those were the only things holding me back from finishing this up. Sorry for such the bother!

**Comment by stevebauman** [comment]
Perfect! No problem at all. Please don't hesitate to create another issue if you encounter anything further, thanks :)

**Comment by epas1117** [comment]
Hi @stevebauman, 

Is this still possible in version 3.0.5??

**Comment by stevebauman** [comment]
Hi @epas1117, there was a lot of discussion here, what exactly are you wanting to know is still possible?

You can import users using the [import command](https://github.com/Adldap2/Adldap2-Laravel/blob/master/docs/importing.md), or you can create a command / database seeder to import and sync users yourself if you would prefer:


```php
use App\User;
use Adldap\Laravel\Facades\Adldap;

class DatabaseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $users = Adldap::search()->users()->get();

        foreach ($users as $user) {
            User::firstOrCreate([
                'username' => $user->getAccountName(),
                'name' => $user->getCommonName(),
            ]);
        }
    }
}
```

Is this what type of functionality you're looking for?

**Comment by epas1117** [comment]
I want to use the trait "Adldap\Laravel\Traits\ImportsUsers" like you said in the post above, so I can search users from a group form the AD and to import/synchronize that users to my local database. 

Thx for answering.
