### ISSUE TITLE
Laravel 9 Support

### ISSUE THREAD

**Issue by inuru** [Adldap2/Adldap2-Laravel#922]
- Laravel Version: 9.0
- Adldap2-Laravel Version: 6.1
- PHP Version: 8.1
- LDAP Type: ActiveDirectory

### Description:
Add support for laravel 9

### Steps To Reproduce:
Change composer.json to require "laravel/framework": "^7.0"

got error

> Problem 1
>     - Conclusion: don't install laravel/framework v9.0.0-beta.1 (conflict analysis result)
>     - Conclusion: don't install laravel/framework v9.0.0-beta.2 (conflict analysis result)
>     - Conclusion: don't install laravel/framework v9.0.0-beta.3 (conflict analysis result)
>     - Conclusion: don't install laravel/framework v9.0.0-beta.4 (conflict analysis result)
>     - illuminate/support[v5.6.0, ..., 5.8.x-dev] require php ^7.1.3 -> your php version (8.1.2) does not satisfy that requirement.
>     - illuminate/support[v6.0.0, ..., v6.19.1] require php ^7.2 -> your php version (8.1.2) does not satisfy that requirement.
>     - illuminate/support[v7.0.0, ..., v7.28.4] require php ^7.2.5 -> your php version (8.1.2) does not satisfy that requirement.
>     - illuminate/support[v8.0.0, ..., v8.11.2] require php ^7.3 -> your php version (8.1.2) does not satisfy that requirement.
>     - adldap2/adldap2-laravel[v6.1.2, ..., v6.1.5] require illuminate/support ~5.5|~6.0|~7.0|~8.0 -> satisfiable by illuminate/support[v5.5.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev].    
>     - adldap2/adldap2-laravel[v6.1.0, ..., v6.1.1] require illuminate/support ~5.5|~6.0|~7.0 -> satisfiable by illuminate/support[v5.5.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev].
>     - Only one of these can be installed: illuminate/support[v5.5.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev, v9.0.0-beta.1, ..., 9.x-dev], laravel/framework[v9.0.0-beta.1, ..., 9.x-dev]. 
> laravel/framework replaces illuminate/support and thus cannot coexist with it.
>     - Root composer.json requires laravel/framework ^9.0 -> satisfiable by laravel/framework[v9.0.0-beta.1, ..., 9.x-dev].
>     - Root composer.json requires adldap2/adldap2-laravel ^6.1 -> satisfiable by adldap2/adldap2-laravel[v6.1.0, ..., v6.1.5].

**Comment by stevebauman** [comment]
Hi @inuru,

Once it comes out of beta I will update the `composer.json` 👍

**Comment by safen** [comment]
Is it support laravel 9 ??

**Comment by inuru** [comment]
> Is it support laravel 9 ??

Yes. I use it on my upgraded laravel 9 and it work perfectly

**Comment by safen** [comment]
thank you

**Comment by MarcosRLeao** [comment]
When I give the command

composer require adldap2/adldap2-laravel

retorn this:


Problem 1
    - adldap2/adldap2-laravel v6.1.6 requires adldap2/adldap2 ^10.1 -> satisfiable by adldap2/adldap2[v10.1.0, ..., v10.4.2].      
    - adldap2/adldap2-laravel[v6.1.0, ..., v6.1.1] require illuminate/support ~5.5|~6.0|~7.0 -> found illuminate/support[v5.5.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev] but these were not loaded, likely because it conflicts with another require.
    - adldap2/adldap2-laravel[v6.1.2, ..., v6.1.5] require illuminate/support ~5.5|~6.0|~7.0|~8.0 -> found illuminate/support[v5.5.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.
    - adldap2/adldap2[v10.1.0, ..., v10.4.0] require psr/log ~1.0 -> found psr/log[1.0.0, ..., 1.1.4] but the package is fixed to 3.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - adldap2/adldap2[v10.4.1, ..., v10.4.2] require psr/simple-cache ~1.0|~2.0 -> found psr/simple-cache[1.0.0, 1.0.1, 2.0.0, 2.x-dev] but the package is fixed to 3.0.0 (lock file version) by a partial update and that version does not match. Make sure you list 
it as an argument for the update command.
    - Root composer.json requires adldap2/adldap2-laravel ^6.1 -> satisfiable by adldap2/adldap2-laravel[v6.1.0, ..., v6.1.6].     

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require adldap2/adldap2-laravel:*" to figure out if any version is installable, or "composer require adldap2/adldap2-laravel:^2.1" if you know which you need.  

how do i solve this

**Comment by MarcosRLeao** [comment]
> > Is it support laravel 9 ??
> 
> Yes. I use it on my upgraded laravel 9 and it work perfectly


I did not find the LoginController .php in the laravel 9 structure.
for this:

public function username()
{
    return 'username';
}

How did you make it work?

**Comment by inuru** [comment]
> I did not find the LoginController .php in the laravel 9 structure. for this:
> 
> public function username() { return 'username'; }
> 
> How did you make it work?

LoginController was removed since Laravel 7. It will generated automatically when you install laravel/ui package [https://github.com/laravel/laravel/commit/b5bb91fea79a3bd5504cbcadfd4766f41f7d01ce](url)

**Comment by vahidalvandi** [comment]
plase add support php 8
