### ISSUE TITLE
technical qustion

### ISSUE THREAD

**Issue by vahidalvandi** [Adldap2/Adldap2-Laravel#927]
I have not used ldap until now. Does this plugin only coordinate the users table with the active directory? Does it mean that the original structure of Laravel is preserved?
And is it always equivalent to LDAP information in the users table?

**Comment by stevebauman** [comment]
Hi @vahidalvandi,

I’d recommend using LdapRecord-Laravel and following the installation guide there. I no longer support Adldap2.

https://ldaprecord.com/docs/laravel/v2

In regards to your question, LdapRecord-Laravel and Adldap2-Laravel have both offered database synchronization mechanisms. This means that the LDAP users who log into your application will be automatically synchronized into your local applications database. I’ve written extensively on this on the docs website, so I’d recommend reading it thoroughly.
