### ISSUE TITLE
online ldap test server

### ISSUE THREAD

**Issue by vahidalvandi** [Adldap2/Adldap2-Laravel#928]
I am a linux developer and I know how to set up windows server to start active directory and I tried to find a way to test it.
Do you think this can be suitable for testing?

 https://www.forumsys.com/2022/05/10/online-ldap-test-server/

**Comment by stevebauman** [comment]
Hi @vahidalvandi,

It depends on the type of testing you’d like to perform.

If you’re looking for simply connectivity testing, then that service will work fine.

If you’re looking for more in-depth testing, such as creation of objects, I’d recommend using LdapRecord-Laravel that includes a suite of test tools:

https://ldaprecord.com/docs/laravel/v2/testing

If you want to test against a real LDAP server, you can use an OpenLDAP docker image that you can get up and running inside of GitHub actions. I use this to test LdapRecord against a real LDAP server:

https://github.com/DirectoryTree/LdapRecord/blob/master/.github/workflows/run-integration-tests.yml

**Comment by vahidalvandi** [comment]
I wish you could show the same method that you test yourself in the form of a video for us Linux, the things we want to test Windows..

**Comment by stevebauman** [comment]
I think that’s a good idea, but there just isn’t enough of a demand for it for me to spend the time in making such a production.

You can take a look at some of the integration tests here:

https://github.com/DirectoryTree/LdapRecord/tree/master/tests/Integration

I also have written some other tests in the past with the LdapRecord directory emulator here:

https://github.com/DirectoryTree/Watchdog/blob/master/tests/WatchdogRunTest.php

Hope this helps!
