### ISSUE TITLE
undefined method Adldap\Adldap::users()

### ISSUE THREAD

**Issue by jmhabermann** [Adldap2/Adldap2-Laravel#94]
Hi,

I run composer update and now i get this error : 
FatalErrorException in Facade.php line 215:Call to undefined method Adldap\Adldap::users()

I can't find a way out.

Thanks.

**Comment by stevebauman** [comment]
Did you upgrade to v2?

**Comment by jmhabermann** [comment]
Yes

**Comment by stevebauman** [comment]
The API has been changed been changed quite dramatically. Please view the documentation on the root Adldap2 repository:

https://github.com/Adldap2/Adldap2

**Comment by jmhabermann** [comment]
Ok. Thanks. I Will take a  look.
You can close this issue.


-------- Message d'origine --------
De : Steve Bauman <notifications@github.com>
Date :27/04/2016 22:24 (GMT+01:00)
À : Adldap2/Adldap2-Laravel <Adldap2-Laravel@noreply.github.com>
Cc : Jean Marc Habermann <jm.habermann@axysweb.com>, Author <author@noreply.github.com>
Objet : Re: [Adldap2/Adldap2-Laravel] undefined method Adldap\Adldap::users() (#94)


The API has been changed been changed quite dramatically. Please view the documentation on the root Adldap2 repository:

https://github.com/Adldap2/Adldap2

-

**Comment by stevebauman** [comment]
Ok, please create another issue if you encounter any further problems.

Also just for a quick example on the changes:

Before:
```php
$users = Adldap::users()->all();
```

After:
```php
$users = Adldap::getDefaultProvider()->search()->users()->get();
```

You'll also need to republish your configuration files.
