### ISSUE TITLE
Option to disable password sync to local database

### ISSUE THREAD

**Issue by mateenmoosa** [Adldap2/Adldap2-Laravel#99]
One of the features of this awesome plugin is that it allows a graceful fallback to local database of authentication in cases when Active Directory is unavailable. In order to accomplish that, the encrypted password is stored in the local database. This is the case even when this feature is turned off.

It would be preferable not to store passwords in the local database at all, so I propose that a flag be added in the configuration which would not sync the password field to the local database.

I believe the change would be in the file, "src/Traits/ImportsUsers.php" to skip the line 55.

`// Sync the users password.`
`$model = $this->syncModelPassword($model, $password);`

**Comment by stevebauman** [comment]
Hi @mateenmoosa, I definitely agree that this should be configurable. Though there are some considerations we should think about.

For example, by default laravel's `users` table migration includes a non-nullable `password` field. In this case, should the password be filled with a `bcrypt()`'ed random string?

**Comment by stevebauman** [comment]
Added implementation. Working on docs and tests, then will be released. Thanks!

**Comment by mateenmoosa** [comment]
Thanks for the quick fix!

I like the idea of a random string being placed there. I was initially
thinking of dropping that column in a migration, but your solution is
better.

Cheers.
On Wed, May 11, 2016 at 3:33 PM Steve Bauman <notifications@github.com>
wrote:

> Added implementation. Working on docs and tests, then will be released.
> Thanks!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Adldap2/Adldap2-Laravel/issues/99#issuecomment-218581301>
>
-- 
--
Mateen
